-- Fill in COS 201's course outline gap using COS 261's content: COS 201 and
-- COS 261 are the same course (Computer Programming I / Java), just filed
-- under different codes -- COS 261 in Computer Science's own outline, COS
-- 201 everywhere else it is cross-listed as a service course. Every
-- department's existing COS 201 row previously had either nothing (Crop
-- Science) or only a short note about the code discrepancy (Geology, Math,
-- Physics and Astronomy, Pure and Industrial Chemistry, Statistics), with
-- no real description or topics.
--
-- Nothing is removed: each existing note is preserved inline, with COS
-- 261's full 13-topic description appended on top. 6 rows updated.
-- Safe to re-run: keyed by course_code + department, so re-running against
-- already-fixed rows just re-applies the same content.
-- =============================================================================

update public.course_outlines
   set description = '(This course is filed as COS 261 in the Computer Science department''s own outline; description and topics reused from there, since it is the same course under a different code.) Introduction to problem solving methods and algorithm development; designing, coding, debugging and documenting programs using techniques of good programming style. An IDE; the Java virtual machine; writing a Java program, packages, simple Java programs; data types; control constructs; classes; keyboard input; file I/O using byte streams, character streams, and buffered streams; writing text files in Java; the File class; standard streams.', topics = '["Introduction to problem solving methods and algorithm development", "designing, coding, debugging and documenting programs using techniques of good programming style", "An IDE", "the Java virtual machine", "writing a Java program, packages, simple Java programs", "data types", "control constructs", "classes", "keyboard input", "file I/O using byte streams, character streams, and buffered streams", "writing text files in Java", "the File class", "standard streams"]'::jsonb
 where course_code = 'COS 201' and department = 'Crop Science';

update public.course_outlines
   set description = '(This course is filed as COS 261 in the Computer Science department''s own outline; description and topics reused from there, since it is the same course under a different code.) Introduction to problem solving methods and algorithm development; designing, coding, debugging and documenting programs using techniques of good programming style. An IDE; the Java virtual machine; writing a Java program, packages, simple Java programs; data types; control constructs; classes; keyboard input; file I/O using byte streams, character streams, and buffered streams; writing text files in Java; the File class; standard streams. [Note also on file for this row: Printed in this table as "Computer Programming 11"; every other appearance of COS 201 in this document titles it Computer Programming I, used here.]', topics = '["Introduction to problem solving methods and algorithm development", "designing, coding, debugging and documenting programs using techniques of good programming style", "An IDE", "the Java virtual machine", "writing a Java program, packages, simple Java programs", "data types", "control constructs", "classes", "keyboard input", "file I/O using byte streams, character streams, and buffered streams", "writing text files in Java", "the File class", "standard streams"]'::jsonb
 where course_code = 'COS 201' and department = 'Geology';

update public.course_outlines
   set description = '(This course is filed as COS 261 in the Computer Science department''s own outline; description and topics reused from there, since it is the same course under a different code.) Introduction to problem solving methods and algorithm development; designing, coding, debugging and documenting programs using techniques of good programming style. An IDE; the Java virtual machine; writing a Java program, packages, simple Java programs; data types; control constructs; classes; keyboard input; file I/O using byte streams, character streams, and buffered streams; writing text files in Java; the File class; standard streams. [Note also on file for this row: Printed in this table as "Computer Programming 11"; every other appearance of COS 201 in this document titles it Computer Programming I, used here.]', topics = '["Introduction to problem solving methods and algorithm development", "designing, coding, debugging and documenting programs using techniques of good programming style", "An IDE", "the Java virtual machine", "writing a Java program, packages, simple Java programs", "data types", "control constructs", "classes", "keyboard input", "file I/O using byte streams, character streams, and buffered streams", "writing text files in Java", "the File class", "standard streams"]'::jsonb
 where course_code = 'COS 201' and department = 'Mathematics';

update public.course_outlines
   set description = '(This course is filed as COS 261 in the Computer Science department''s own outline; description and topics reused from there, since it is the same course under a different code.) Introduction to problem solving methods and algorithm development; designing, coding, debugging and documenting programs using techniques of good programming style. An IDE; the Java virtual machine; writing a Java program, packages, simple Java programs; data types; control constructs; classes; keyboard input; file I/O using byte streams, character streams, and buffered streams; writing text files in Java; the File class; standard streams. [Note also on file for this row: Printed in this table as "Computer Programming 11"; every other appearance of COS 201 in this document titles it Computer Programming I, used here.]', topics = '["Introduction to problem solving methods and algorithm development", "designing, coding, debugging and documenting programs using techniques of good programming style", "An IDE", "the Java virtual machine", "writing a Java program, packages, simple Java programs", "data types", "control constructs", "classes", "keyboard input", "file I/O using byte streams, character streams, and buffered streams", "writing text files in Java", "the File class", "standard streams"]'::jsonb
 where course_code = 'COS 201' and department = 'Physics and Astronomy';

update public.course_outlines
   set description = '(This course is filed as COS 261 in the Computer Science department''s own outline; description and topics reused from there, since it is the same course under a different code.) Introduction to problem solving methods and algorithm development; designing, coding, debugging and documenting programs using techniques of good programming style. An IDE; the Java virtual machine; writing a Java program, packages, simple Java programs; data types; control constructs; classes; keyboard input; file I/O using byte streams, character streams, and buffered streams; writing text files in Java; the File class; standard streams. [Note also on file for this row: Printed in this table as "Computer Programming 11"; every other appearance of COS 201 in this document titles it Computer Programming I, used here.]', topics = '["Introduction to problem solving methods and algorithm development", "designing, coding, debugging and documenting programs using techniques of good programming style", "An IDE", "the Java virtual machine", "writing a Java program, packages, simple Java programs", "data types", "control constructs", "classes", "keyboard input", "file I/O using byte streams, character streams, and buffered streams", "writing text files in Java", "the File class", "standard streams"]'::jsonb
 where course_code = 'COS 201' and department = 'Pure and Industrial Chemistry';

update public.course_outlines
   set description = '(This course is filed as COS 261 in the Computer Science department''s own outline; description and topics reused from there, since it is the same course under a different code.) Introduction to problem solving methods and algorithm development; designing, coding, debugging and documenting programs using techniques of good programming style. An IDE; the Java virtual machine; writing a Java program, packages, simple Java programs; data types; control constructs; classes; keyboard input; file I/O using byte streams, character streams, and buffered streams; writing text files in Java; the File class; standard streams. [Note also on file for this row: Printed in this table as "Computer Programming 11"; every other appearance of COS 201 in this document titles it Computer Programming I, used here.]', topics = '["Introduction to problem solving methods and algorithm development", "designing, coding, debugging and documenting programs using techniques of good programming style", "An IDE", "the Java virtual machine", "writing a Java program, packages, simple Java programs", "data types", "control constructs", "classes", "keyboard input", "file I/O using byte streams, character streams, and buffered streams", "writing text files in Java", "the File class", "standard streams"]'::jsonb
 where course_code = 'COS 201' and department = 'Statistics';
