-- Backfill missing course_outlines description/topics for shared ancillary
-- courses (GSP101/102/111, ECO101/102/201/203/281/282, BCH201/202, CHM122,
-- COS101, MTH205, STA205) that were showing as "Outline not added yet" in
-- the app under several departments, even though a real, verified
-- description and topics already existed for the exact same course
-- (matched by course_code AND course_title, to avoid merging genuinely
-- different same-coded courses -- several GSP codes are known to carry
-- different real content across different departments' own printed
-- source material within this app, and were deliberately left distinct).
--
-- Also corrects one genuine title/content error: Statistics' own outline
-- had mistakenly reused "Microeconomic Theory I" (ECO 201's title) for
-- ECO 203 as well; ECO 203 is Macroeconomic Theory I per Economics' own
-- outline and the standard ECO course-numbering convention (201/202 =
-- Micro, 203/204 = Macro), corrected here along with its content.
--
-- 32 rows updated. Safe to re-run: each UPDATE is keyed by course_code +
-- department (+ old course_title where a title correction was needed), so
-- re-running against already-fixed rows is a no-op.
-- =============================================================================

update public.course_outlines
   set course_title = 'General Biochemistry I', description = '(Description and topics reused from Pure and Industrial Chemistry''s outline for the same course.) Elective. The cell environment: water and solutes — the unique properties of water, H-bonds, electrostatic interactions, Van der Waals attraction; alkalinity and acidity, pH and pK and their influence on cellular activities; physiological buffers. Cell macromolecules: structure, properties and functions of carbohydrates, lipids, proteins and nucleic acids. Cell structure and function: structure and function of major cell organelles; differences between prokaryotic and eukaryotic cells; biological membranes — organisation, architecture, properties and functions; the cytoplasm — mitochondria, peroxisomes, endoplasmic reticulum, Golgi complex, ribosomes, lysosomes, endosome; the nucleus — the nuclear envelope, chromatin, chromosomes, nucleolus, etc.', topics = '["The cell environment: water and solutes, H-bonds, electrostatic interactions, Van der Waals attraction", "Alkalinity and acidity, pH and pK and their influence on cellular activities", "Physiological buffers", "Structure, properties and functions of carbohydrates, lipids, proteins and nucleic acids", "Structure and function of major cell organelles; differences between prokaryotic and eukaryotic cells", "Biological membranes: organisation, architecture, properties and functions", "The cytoplasm: mitochondria, peroxisomes, endoplasmic reticulum, Golgi complex, ribosomes, lysosomes, endosome", "The nucleus: nuclear envelope, chromatin, chromosomes, nucleolus"]'::jsonb
 where course_code = 'BCH 201' and department = 'Biomedical Engineering';

update public.course_outlines
   set course_title = 'General Biochemistry II', description = '(Description and topics reused from Biochemistry''s outline for the same course.) Enzymes: introduction to biological catalysts, nature, functions and classification of enzymes, factors affecting enzyme action. Energy metabolism: introductory bioenergetics/energy-rich compounds, carbohydrate metabolism — glycolysis and pentose phosphate pathway, the Krebs cycle and the glyoxylate cycle, electron transport and oxidative phosphorylation. Separation of macromolecules: chromatographic methods — thin layer chromatography, gel filtration, ion exchange chromatography, affinity chromatography; electrophoretic methods — nucleic acid gel electrophoresis, electrophoretic sizing of protein, isoelectric focusing.', topics = '["Introduction to biological catalysts: nature, functions and classification of enzymes; factors affecting enzyme action", "Introductory bioenergetics/energy-rich compounds", "Carbohydrate metabolism: glycolysis and pentose phosphate pathway", "The Krebs cycle and the glyoxylate cycle", "Electron transport and oxidative phosphorylation", "Chromatographic methods: thin layer, gel filtration, ion exchange, affinity chromatography", "Electrophoretic methods: nucleic acid gel electrophoresis, protein sizing, isoelectric focusing"]'::jsonb
 where course_code = 'BCH 202' and department = 'Biomedical Engineering';

update public.course_outlines
   set course_title = 'Basic Principles of Organic Chemistry', description = '(Description and topics reused from Mathematics''s outline for the same course.) Elective. Structure and Classification: Historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, homologous series, elemental analysis, molecular formulas, and structural isomerism. Bonding and Reactivity: Isolation and purification methods, functional group concepts, resonance, and aromaticity. Electronic theory in organic chemistry. Functional Groups: Brief study of saturated and unsaturated hydrocarbons, cyclic hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, and aromatic compounds. Comparison of phenols and aryl halides. Stereochemistry and Lipids: Introduction to oils, fats, and stereoisomerism.', topics = '["Structure and Classification: Historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, homologous series, elemental analysis, molecular formulas, and structural isomerism", "Bonding and Reactivity: Isolation and purification methods, functional group concepts, resonance, and aromaticity. Electronic theory in organic chemistry", "Functional Groups: Brief study of saturated and unsaturated hydrocarbons, cyclic hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, and aromatic compounds. Comparison of phenols and aryl halides", "Stereochemistry and Lipids: Introduction to oils, fats, and stereoisomerism"]'::jsonb
 where course_code = 'CHM 122' and department = 'Mechanical Engineering';

update public.course_outlines
   set course_title = 'Introduction to Computer Science', description = '(Description and topics reused from Geology''s outline for the same course.) The programme table prints this course''s code as "SP 101" — a binding-fold scan artefact seen throughout this source; every other department''s programme table in the same document uses COS 101 for this exact title, so that code is used here. Concepts of hardware and software; basic subsystems of a digital computer; characteristics of a digital computer; devices/media; types/classes of computer emphasising the PC; history of computers and their generations. Problem-solving: algorithm, flowchart, pseudocode, program/data, running a program. Programming: introduction to Java/BASIC programming language syntax and programming. Booting and shutdown; types of operating system; user interface; managing information, computer malware (virus, etc); computer network; internet and web usage, e-mail, instant messaging, etc. Office applications; use of a statistical package and a database management system.', topics = '["Concepts of hardware and software", "basic subsystems of a digital computer", "characteristics of a digital computer", "devices/media", "types/classes of computer emphasising the PC", "history of computers and their generations", "Problem-solving: algorithm, flowchart, pseudocode, program/data, running a program", "Programming: introduction to Java/BASIC programming language syntax and programming", "Booting and shutdown", "types of operating system", "user interface", "managing information, computer malware (virus, etc)", "computer network", "internet and web usage, e-mail, instant messaging, etc", "Office applications", "use of a statistical package and a database management system"]'::jsonb
 where course_code = 'COS 101' and department = 'Crop Science';

update public.course_outlines
   set course_title = 'Principles of Economics I', description = '(Description and topics reused from Economics''s outline for the same course.) Nature and significance of Economics; The methodology of economics; Economic tools of analysis; Theories of demand and supply; Elementary analysis; Dynamic theory of price; Elements of price theory; Production theory: Output, cost, law of diminishing returns; Market structure: Perfect competition, monopoly, oligopoly etc; Elementary theory of welfare economics; Determinants for and pricing of productive factors; Interest rate and profit.', topics = '["Nature and significance of Economics", "The methodology of economics", "Economic tools of analysis", "Theories of demand and supply", "Elementary analysis", "Dynamic theory of price", "Elements of price theory", "Production theory: Output, cost, law of diminishing returns", "Market structure: Perfect competition, monopoly, oligopoly etc", "Elementary theory of welfare economics", "Determinants for and pricing of productive factors", "Interest rate and profit"]'::jsonb
 where course_code = 'ECO 101' and department = 'Pure and Industrial Chemistry';

update public.course_outlines
   set course_title = 'Principles of Economics I', description = '(Description and topics reused from Economics''s outline for the same course.) Nature and significance of Economics; The methodology of economics; Economic tools of analysis; Theories of demand and supply; Elementary analysis; Dynamic theory of price; Elements of price theory; Production theory: Output, cost, law of diminishing returns; Market structure: Perfect competition, monopoly, oligopoly etc; Elementary theory of welfare economics; Determinants for and pricing of productive factors; Interest rate and profit.', topics = '["Nature and significance of Economics", "The methodology of economics", "Economic tools of analysis", "Theories of demand and supply", "Elementary analysis", "Dynamic theory of price", "Elements of price theory", "Production theory: Output, cost, law of diminishing returns", "Market structure: Perfect competition, monopoly, oligopoly etc", "Elementary theory of welfare economics", "Determinants for and pricing of productive factors", "Interest rate and profit"]'::jsonb
 where course_code = 'ECO 101' and department = 'Statistics';

update public.course_outlines
   set course_title = 'Principles of Economics II', description = '(Description and topics reused from Economics''s outline for the same course.) Elementary principles of macroeconomics and microeconomics; National income determination; The circular flow of income; Injections, withdrawals and the multiplier; Income determination; consumption, saving and investment functions; Nature and features of money; The banking system and the supply of money; Money supply and price level; International trade; Exchange rate and comparative advantage; Foreign trade and domestic economy; Economic growth; Elementary notion of economic planning; Introduction to Marxist economic theory.', topics = '["Elementary principles of macroeconomics and microeconomics", "National income determination", "The circular flow of income; Injections, withdrawals and the multiplier", "Income determination; consumption, saving and investment functions", "Nature and features of money", "The banking system and the supply of money", "Money supply and price level", "International trade; Exchange rate and comparative advantage", "Foreign trade and domestic economy", "Economic growth", "Elementary notion of economic planning", "Introduction to Marxist economic theory"]'::jsonb
 where course_code = 'ECO 102' and department = 'Statistics';

update public.course_outlines
   set course_title = 'Microeconomic Theory I', description = '(Description and topics reused from Economics''s outline for the same course.) Introduction to microeconomics; Problem of scarce resources; Allocation of resources in product and factor markets with applications to Nigeria and other economies; Supply and demand theory; Cobweb theory; Theory of consumer behavior: utility, preferences, indifference curves, budget constraints; Substitution and Income effects of price change in consumers'' demand; equilibrium concept; Possibility of disequilibrium; Partial equilibrium analyses; General equilibrium analyses; Introduction to economic dynamics.', topics = '["Introduction to microeconomics", "Problem of scarce resources", "Allocation of resources in product and factor markets with applications to Nigeria and other economies", "Supply and demand theory; Cobweb theory", "Theory of consumer behavior: utility, preferences, indifference curves, budget constraints", "Substitution and Income effects of price change in consumers'' demand; equilibrium concept", "Possibility of disequilibrium", "Partial equilibrium analyses; General equilibrium analyses", "Introduction to economic dynamics"]'::jsonb
 where course_code = 'ECO 201' and department = 'Statistics';

update public.course_outlines
   set course_title = 'Macroeconomic Theory I', description = '(Title corrected -- the Statistics department outline had mistakenly reused the ECO 201 title "Microeconomic Theory I" for this row; ECO 203 is Macroeconomic Theory I per the Economics department''s own outline, whose description and topics are reused here.) Introduction to macroeconomics; Goals of macroeconomic analysis; National Income Accounting; Alternative approaches to GNP estimation; GNP and related macroeconomic aggregates; Conceptual problems of estimation and use of national accounts; Introduction to a simple macro-model of a market economy.', topics = '["Introduction to macroeconomics", "Goals of macroeconomic analysis", "National Income Accounting", "Alternative approaches to GNP estimation", "GNP and related macroeconomic aggregates", "Conceptual problems of estimation and use of national accounts", "Introduction to a simple macro-model of a market economy"]'::jsonb
 where course_code = 'ECO 203' and department = 'Statistics';

update public.course_outlines
   set course_title = 'Structure of Nigerian Economy I', description = '(Description and topics reused from Economics'' outline for the same course.) An overview of the Nigerian economy: pre-colonial period, colonial period, post-independence period with special regard to development of economic and social organization; The Nigerian economic system: natural and human resources endowments; An overview of monetary and development institutions in Nigeria; The sectors of the Nigerian economy: their relative sizes, importance and contributions to Nigerian economic development; Sectoral interdependence in the Nigerian economy.', topics = '["An overview of the Nigerian economy: pre-colonial period, colonial period, post-independence period with special regard to development of economic and social organization", "The Nigerian economic system: natural and human resources endowments", "An overview of monetary and development institutions in Nigeria", "The sectors of the Nigerian economy: their relative sizes, importance and contributions to Nigerian economic development", "Sectoral interdependence in the Nigerian economy"]'::jsonb
 where course_code = 'ECO 281' and department = 'Statistics';

update public.course_outlines
   set course_title = 'Structure of Nigerian Economy II', description = '(Description and topics reused from Economics'' outline for the same course.) Nigeria''s economic growth and development: growth of income, employment, wages and prices; National Income and expenditure; Money and monetary institutions; The quest for economic development and fiscal policy; Public development institutions and the quest for economic development; Trade and transportation; A study of social change; Agricultural and industrial production; Trade and transportation; A study of some key industries, e.g. oil, iron and steel, automobile and construction.', topics = '["Nigeria''s economic growth and development: growth of income, employment, wages and prices", "National Income and expenditure", "Money and monetary institutions", "The quest for economic development and fiscal policy", "Public development institutions and the quest for economic development", "Trade and transportation", "A study of social change", "Agricultural and industrial production", "A study of some key industries, e.g. oil, iron and steel, automobile and construction"]'::jsonb
 where course_code = 'ECO 282' and department = 'Statistics';

update public.course_outlines
   set course_title = 'Study Skills and Basic Research Methods', description = '(Description and topics reused from Computer Science''s outline for the same course.) Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, The English Language and the Nigerian society, World English, Levels and Varieties of English — formal, informal, standard, etc., English in Literature and the Media.

Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes, English Language Register, diatypes and dialects.

Listening skill - The listening skill discussed as a receptive and reciprocal activity, Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening.

Reading Skill - The concept of reading as a linguistic organization and a vehicle of communication. Reading Problems, Levels of Reading, Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies (Scanning, Skimming, Phrase reading, Intensive & Extensive reading, Exploiting the topic sentence for main ideas), Reading for details, Reading for evaluation and inference, Reading with questions - SQ3R, PR3, Methods for understanding difficult words in a reading text, Literature reading for study, analysis and comment.

Speaking & Communication Skills - Nature, Process & Development, Principles of Public Speech Making and Social Interaction, The Speech Sounds of English and their Articulation, Phonetic Transcription and Practical Speech Work.

Study Techniques - Choosing study centers and discussion groups, Note-taking during lectures, and from audio-visual equipment, Note-making techniques during private reading and literature search, Summary & Transcoding Techniques, Retrieving information from notes, The dictionary as a study guide.

Basic Research Methods & Term Paper Writing - Research – meaning & nature, Types & Methodology; Data in the Research Process, The Research Report, Process and Techniques, Documentation in Research Reports: Process, Types and Methods, Abbreviations in Research Reports, The term paper as a miniature research report, Practical term paper writing.

Course Evaluation & Grading - Students must attend at least 75% of the lectures to qualify for examination in the course.', topics = '["Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, World English, Levels and Varieties of English", "Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes", "Listening skill - Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening", "Reading Skill - Reading Problems, Levels and Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies, Reading for evaluation and inference", "Speaking & Communication Skills - Principles of Public Speech Making and Social Interaction, Phonetic Transcription and Practical Speech Work", "Study Techniques - Note-taking, Note-making, Summary & Transcoding Techniques", "Basic Research Methods & Term Paper Writing - The Research Report, Documentation, Abbreviations, practical term paper writing"]'::jsonb
 where course_code = 'GSP 101' and department = 'Agricultural and Bioresources Engineering';

update public.course_outlines
   set course_title = 'Study Skills and Basic Research Methods', description = '(Description and topics reused from Computer Science''s outline for the same course.) Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, The English Language and the Nigerian society, World English, Levels and Varieties of English — formal, informal, standard, etc., English in Literature and the Media.

Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes, English Language Register, diatypes and dialects.

Listening skill - The listening skill discussed as a receptive and reciprocal activity, Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening.

Reading Skill - The concept of reading as a linguistic organization and a vehicle of communication. Reading Problems, Levels of Reading, Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies (Scanning, Skimming, Phrase reading, Intensive & Extensive reading, Exploiting the topic sentence for main ideas), Reading for details, Reading for evaluation and inference, Reading with questions - SQ3R, PR3, Methods for understanding difficult words in a reading text, Literature reading for study, analysis and comment.

Speaking & Communication Skills - Nature, Process & Development, Principles of Public Speech Making and Social Interaction, The Speech Sounds of English and their Articulation, Phonetic Transcription and Practical Speech Work.

Study Techniques - Choosing study centers and discussion groups, Note-taking during lectures, and from audio-visual equipment, Note-making techniques during private reading and literature search, Summary & Transcoding Techniques, Retrieving information from notes, The dictionary as a study guide.

Basic Research Methods & Term Paper Writing - Research – meaning & nature, Types & Methodology; Data in the Research Process, The Research Report, Process and Techniques, Documentation in Research Reports: Process, Types and Methods, Abbreviations in Research Reports, The term paper as a miniature research report, Practical term paper writing.

Course Evaluation & Grading - Students must attend at least 75% of the lectures to qualify for examination in the course.', topics = '["Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, World English, Levels and Varieties of English", "Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes", "Listening skill - Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening", "Reading Skill - Reading Problems, Levels and Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies, Reading for evaluation and inference", "Speaking & Communication Skills - Principles of Public Speech Making and Social Interaction, Phonetic Transcription and Practical Speech Work", "Study Techniques - Note-taking, Note-making, Summary & Transcoding Techniques", "Basic Research Methods & Term Paper Writing - The Research Report, Documentation, Abbreviations, practical term paper writing"]'::jsonb
 where course_code = 'GSP 101' and department = 'Biomedical Engineering';

update public.course_outlines
   set course_title = 'Communication in English I', description = '(Description and topics reused from Pure and Industrial Chemistry''s outline for the same course.) Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, The English Language and the Nigerian society, World English, Levels and Varieties of English — formal, informal, standard, etc., English in Literature and the Media.

Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes, English Language Register, diatypes and dialects.

Listening skill - The listening skill discussed as a receptive and reciprocal activity, Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening.

Reading Skill - The concept of reading as a linguistic organization and a vehicle of communication. Reading Problems, Levels of Reading, Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies (Scanning, Skimming, Phrase reading, Intensive & Extensive reading, Exploiting the topic sentence for main ideas), Reading for details, Reading for evaluation and inference, Reading with questions - SQ3R, PR3, Methods for understanding difficult words in a reading text, Literature reading for study, analysis and comment.

Speaking & Communication Skills - Nature, Process & Development, Principles of Public Speech Making and Social Interaction, The Speech Sounds of English and their Articulation, Phonetic Transcription and Practical Speech Work.

Study Techniques - Choosing study centers and discussion groups, Note-taking during lectures, and from audio-visual equipment, Note-making techniques during private reading and literature search, Summary & Transcoding Techniques, Retrieving information from notes, The dictionary as a study guide.

Basic Research Methods & Term Paper Writing - Research – meaning & nature, Types & Methodology; Data in the Research Process, The Research Report, Process and Techniques, Documentation in Research Reports: Process, Types and Methods, Abbreviations in Research Reports, The term paper as a miniature research report, Practical term paper writing.

Course Evaluation & Grading - Students must attend at least 75% of the lectures to qualify for examination in the course.', topics = '["Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, World English, Levels and Varieties of English", "Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes", "Listening skill - Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening", "Reading Skill - Reading Problems, Levels and Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies, Reading for evaluation and inference", "Speaking & Communication Skills - Principles of Public Speech Making and Social Interaction, Phonetic Transcription and Practical Speech Work", "Study Techniques - Note-taking, Note-making, Summary & Transcoding Techniques", "Basic Research Methods & Term Paper Writing - The Research Report, Documentation, Abbreviations, practical term paper writing"]'::jsonb
 where course_code = 'GSP 101' and department = 'Crop Science';

update public.course_outlines
   set course_title = 'Study Skills and Basic Research Methods', description = '(Description and topics reused from Computer Science''s outline for the same course.) Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, The English Language and the Nigerian society, World English, Levels and Varieties of English — formal, informal, standard, etc., English in Literature and the Media.

Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes, English Language Register, diatypes and dialects.

Listening skill - The listening skill discussed as a receptive and reciprocal activity, Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening.

Reading Skill - The concept of reading as a linguistic organization and a vehicle of communication. Reading Problems, Levels of Reading, Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies (Scanning, Skimming, Phrase reading, Intensive & Extensive reading, Exploiting the topic sentence for main ideas), Reading for details, Reading for evaluation and inference, Reading with questions - SQ3R, PR3, Methods for understanding difficult words in a reading text, Literature reading for study, analysis and comment.

Speaking & Communication Skills - Nature, Process & Development, Principles of Public Speech Making and Social Interaction, The Speech Sounds of English and their Articulation, Phonetic Transcription and Practical Speech Work.

Study Techniques - Choosing study centers and discussion groups, Note-taking during lectures, and from audio-visual equipment, Note-making techniques during private reading and literature search, Summary & Transcoding Techniques, Retrieving information from notes, The dictionary as a study guide.

Basic Research Methods & Term Paper Writing - Research – meaning & nature, Types & Methodology; Data in the Research Process, The Research Report, Process and Techniques, Documentation in Research Reports: Process, Types and Methods, Abbreviations in Research Reports, The term paper as a miniature research report, Practical term paper writing.

Course Evaluation & Grading - Students must attend at least 75% of the lectures to qualify for examination in the course.', topics = '["Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, World English, Levels and Varieties of English", "Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes", "Listening skill - Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening", "Reading Skill - Reading Problems, Levels and Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies, Reading for evaluation and inference", "Speaking & Communication Skills - Principles of Public Speech Making and Social Interaction, Phonetic Transcription and Practical Speech Work", "Study Techniques - Note-taking, Note-making, Summary & Transcoding Techniques", "Basic Research Methods & Term Paper Writing - The Research Report, Documentation, Abbreviations, practical term paper writing"]'::jsonb
 where course_code = 'GSP 101' and department = 'Electrical Engineering';

update public.course_outlines
   set course_title = 'The Use of English I', description = '(Description and topics reused from Biochemistry''s outline for the same course.) Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, The English Language and the Nigerian society, World English, Levels and Varieties of English — formal, informal, standard, etc., English in Literature and the Media.

Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes, English Language Register, diatypes and dialects.

Listening skill - The listening skill discussed as a receptive and reciprocal activity, Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening.

Reading Skill - The concept of reading as a linguistic organization and a vehicle of communication. Reading Problems, Levels of Reading, Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies (Scanning, Skimming, Phrase reading, Intensive & Extensive reading, Exploiting the topic sentence for main ideas), Reading for details, Reading for evaluation and inference, Reading with questions - SQ3R, PR3, Methods for understanding difficult words in a reading text, Literature reading for study, analysis and comment.

Speaking & Communication Skills - Nature, Process & Development, Principles of Public Speech Making and Social Interaction, The Speech Sounds of English and their Articulation, Phonetic Transcription and Practical Speech Work.

Study Techniques - Choosing study centers and discussion groups, Note-taking during lectures, and from audio-visual equipment, Note-making techniques during private reading and literature search, Summary & Transcoding Techniques, Retrieving information from notes, The dictionary as a study guide.

Basic Research Methods & Term Paper Writing - Research – meaning & nature, Types & Methodology; Data in the Research Process, The Research Report, Process and Techniques, Documentation in Research Reports: Process, Types and Methods, Abbreviations in Research Reports, The term paper as a miniature research report, Practical term paper writing.

Course Evaluation & Grading - Students must attend at least 75% of the lectures to qualify for examination in the course.', topics = '["Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, World English, Levels and Varieties of English", "Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes", "Listening skill - Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening", "Reading Skill - Reading Problems, Levels and Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies, Reading for evaluation and inference", "Speaking & Communication Skills - Principles of Public Speech Making and Social Interaction, Phonetic Transcription and Practical Speech Work", "Study Techniques - Note-taking, Note-making, Summary & Transcoding Techniques", "Basic Research Methods & Term Paper Writing - The Research Report, Documentation, Abbreviations, practical term paper writing"]'::jsonb
 where course_code = 'GSP 101' and department = 'Electronic Engineering';

update public.course_outlines
   set course_title = 'Study Skills and Basic Research Methods', description = '(Description and topics reused from Computer Science''s outline for the same course.) Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, The English Language and the Nigerian society, World English, Levels and Varieties of English — formal, informal, standard, etc., English in Literature and the Media.

Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes, English Language Register, diatypes and dialects.

Listening skill - The listening skill discussed as a receptive and reciprocal activity, Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening.

Reading Skill - The concept of reading as a linguistic organization and a vehicle of communication. Reading Problems, Levels of Reading, Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies (Scanning, Skimming, Phrase reading, Intensive & Extensive reading, Exploiting the topic sentence for main ideas), Reading for details, Reading for evaluation and inference, Reading with questions - SQ3R, PR3, Methods for understanding difficult words in a reading text, Literature reading for study, analysis and comment.

Speaking & Communication Skills - Nature, Process & Development, Principles of Public Speech Making and Social Interaction, The Speech Sounds of English and their Articulation, Phonetic Transcription and Practical Speech Work.

Study Techniques - Choosing study centers and discussion groups, Note-taking during lectures, and from audio-visual equipment, Note-making techniques during private reading and literature search, Summary & Transcoding Techniques, Retrieving information from notes, The dictionary as a study guide.

Basic Research Methods & Term Paper Writing - Research – meaning & nature, Types & Methodology; Data in the Research Process, The Research Report, Process and Techniques, Documentation in Research Reports: Process, Types and Methods, Abbreviations in Research Reports, The term paper as a miniature research report, Practical term paper writing.

Course Evaluation & Grading - Students must attend at least 75% of the lectures to qualify for examination in the course.', topics = '["Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, World English, Levels and Varieties of English", "Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes", "Listening skill - Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening", "Reading Skill - Reading Problems, Levels and Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies, Reading for evaluation and inference", "Speaking & Communication Skills - Principles of Public Speech Making and Social Interaction, Phonetic Transcription and Practical Speech Work", "Study Techniques - Note-taking, Note-making, Summary & Transcoding Techniques", "Basic Research Methods & Term Paper Writing - The Research Report, Documentation, Abbreviations, practical term paper writing"]'::jsonb
 where course_code = 'GSP 101' and department = 'Mechatronic Engineering';

update public.course_outlines
   set course_title = 'The Use of English I', description = '(Description and topics reused from Biochemistry''s outline for the same course.) Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, The English Language and the Nigerian society, World English, Levels and Varieties of English — formal, informal, standard, etc., English in Literature and the Media.

Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes, English Language Register, diatypes and dialects.

Listening skill - The listening skill discussed as a receptive and reciprocal activity, Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening.

Reading Skill - The concept of reading as a linguistic organization and a vehicle of communication. Reading Problems, Levels of Reading, Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies (Scanning, Skimming, Phrase reading, Intensive & Extensive reading, Exploiting the topic sentence for main ideas), Reading for details, Reading for evaluation and inference, Reading with questions - SQ3R, PR3, Methods for understanding difficult words in a reading text, Literature reading for study, analysis and comment.

Speaking & Communication Skills - Nature, Process & Development, Principles of Public Speech Making and Social Interaction, The Speech Sounds of English and their Articulation, Phonetic Transcription and Practical Speech Work.

Study Techniques - Choosing study centers and discussion groups, Note-taking during lectures, and from audio-visual equipment, Note-making techniques during private reading and literature search, Summary & Transcoding Techniques, Retrieving information from notes, The dictionary as a study guide.

Basic Research Methods & Term Paper Writing - Research – meaning & nature, Types & Methodology; Data in the Research Process, The Research Report, Process and Techniques, Documentation in Research Reports: Process, Types and Methods, Abbreviations in Research Reports, The term paper as a miniature research report, Practical term paper writing.

Course Evaluation & Grading - Students must attend at least 75% of the lectures to qualify for examination in the course.', topics = '["Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, World English, Levels and Varieties of English", "Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes", "Listening skill - Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening", "Reading Skill - Reading Problems, Levels and Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies, Reading for evaluation and inference", "Speaking & Communication Skills - Principles of Public Speech Making and Social Interaction, Phonetic Transcription and Practical Speech Work", "Study Techniques - Note-taking, Note-making, Summary & Transcoding Techniques", "Basic Research Methods & Term Paper Writing - The Research Report, Documentation, Abbreviations, practical term paper writing"]'::jsonb
 where course_code = 'GSP 101' and department = 'Metallurgical and Materials Engineering';

update public.course_outlines
   set course_title = 'Basic Grammar and Varieties of Writing', description = '(Description and topics reused from Computer Science''s outline for the same course.) Part A: Basic Grammar: Introduction. The concept of grammar and its place in language teaching and learning. Parts of speech and their functions (treated in detail). Closed and open class items in parts of speech, Nominalization, Grammatical Structures: the phrase, the clause and the sentence. Elementary Clause Analysis, Sentence Types, Elements and Patterns. Agreement (Grammatical agreement, Notional agreement, Proximity agreement) Agreement with the correlatives. Direct and Reported Speech, Error typology identification and correction.

Part B: Varieties of writing. Introduction (The Meaning, Nature and Purpose of Writing, Writing Types or Genres and their Characteristics). The paragraph as the basic unit of an essay (Types, Development of the Paragraph, Methods of Paragraph Development, The thesis statement). Point of view and style in writing. Qualities of a good piece of writing: Form, Diction and Content in writing. The Mechanics of Writing: punctuation, spelling and capitalization.

Part C: Writing Genres - Planning and choosing your theme. Deciding your genre. Choosing and developing your plot. Point of view, setting and characterization. Using the language that works. Essay Writing — Narration, Description, Exposition and Argumentation. Technical Writing: Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes, own story for practice, Computer-linked writing, types, style, language, and process.', topics = '["Part A: Basic Grammar - The concept of grammar, Parts of speech, Grammatical Structures, Sentence Types, Agreement, Direct and Reported Speech, Error typology", "Part B: Varieties of writing - Meaning, Nature and Purpose of Writing, the paragraph as the basic unit of an essay, the thesis statement, Qualities of a good piece of writing, Mechanics of Writing", "Part C: Writing Genres - Planning and choosing your theme, plot, point of view, setting and characterization", "Essay Writing - Narration, Description, Exposition and Argumentation", "Technical Writing - Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes"]'::jsonb
 where course_code = 'GSP 102' and department = 'Agricultural and Bioresources Engineering';

update public.course_outlines
   set course_title = 'Basic Grammar and Varieties of Writing', description = '(Description and topics reused from Computer Science''s outline for the same course.) Part A: Basic Grammar: Introduction. The concept of grammar and its place in language teaching and learning. Parts of speech and their functions (treated in detail). Closed and open class items in parts of speech, Nominalization, Grammatical Structures: the phrase, the clause and the sentence. Elementary Clause Analysis, Sentence Types, Elements and Patterns. Agreement (Grammatical agreement, Notional agreement, Proximity agreement) Agreement with the correlatives. Direct and Reported Speech, Error typology identification and correction.

Part B: Varieties of writing. Introduction (The Meaning, Nature and Purpose of Writing, Writing Types or Genres and their Characteristics). The paragraph as the basic unit of an essay (Types, Development of the Paragraph, Methods of Paragraph Development, The thesis statement). Point of view and style in writing. Qualities of a good piece of writing: Form, Diction and Content in writing. The Mechanics of Writing: punctuation, spelling and capitalization.

Part C: Writing Genres - Planning and choosing your theme. Deciding your genre. Choosing and developing your plot. Point of view, setting and characterization. Using the language that works. Essay Writing — Narration, Description, Exposition and Argumentation. Technical Writing: Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes, own story for practice, Computer-linked writing, types, style, language, and process.', topics = '["Part A: Basic Grammar - The concept of grammar, Parts of speech, Grammatical Structures, Sentence Types, Agreement, Direct and Reported Speech, Error typology", "Part B: Varieties of writing - Meaning, Nature and Purpose of Writing, the paragraph as the basic unit of an essay, the thesis statement, Qualities of a good piece of writing, Mechanics of Writing", "Part C: Writing Genres - Planning and choosing your theme, plot, point of view, setting and characterization", "Essay Writing - Narration, Description, Exposition and Argumentation", "Technical Writing - Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes"]'::jsonb
 where course_code = 'GSP 102' and department = 'Biomedical Engineering';

update public.course_outlines
   set course_title = 'Communication in English II', description = '(Description and topics reused from Pure and Industrial Chemistry''s outline for the same course.) Part A: Basic Grammar: Introduction. The concept of grammar and its place in language teaching and learning. Parts of speech and their functions (treated in detail). Closed and open class items in parts of speech, Nominalization, Grammatical Structures: the phrase, the clause and the sentence. Elementary Clause Analysis, Sentence Types, Elements and Patterns. Agreement (Grammatical agreement, Notional agreement, Proximity agreement) Agreement with the correlatives. Direct and Reported Speech, Error typology identification and correction.

Part B: Varieties of writing. Introduction (The Meaning, Nature and Purpose of Writing, Writing Types or Genres and their Characteristics). The paragraph as the basic unit of an essay (Types, Development of the Paragraph, Methods of Paragraph Development, The thesis statement). Point of view and style in writing. Qualities of a good piece of writing: Form, Diction and Content in writing. The Mechanics of Writing: punctuation, spelling and capitalization.

Part C: Writing Genres - Planning and choosing your theme. Deciding your genre. Choosing and developing your plot. Point of view, setting and characterization. Using the language that works. Essay Writing — Narration, Description, Exposition and Argumentation. Technical Writing: Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes, own story for practice, Computer-linked writing, types, style, language, and process.', topics = '["Part A: Basic Grammar - The concept of grammar, Parts of speech, Grammatical Structures, Sentence Types, Agreement, Direct and Reported Speech, Error typology", "Part B: Varieties of writing - Meaning, Nature and Purpose of Writing, the paragraph as the basic unit of an essay, the thesis statement, Qualities of a good piece of writing, Mechanics of Writing", "Part C: Writing Genres - Planning and choosing your theme, plot, point of view, setting and characterization", "Essay Writing - Narration, Description, Exposition and Argumentation", "Technical Writing - Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes"]'::jsonb
 where course_code = 'GSP 102' and department = 'Crop Science';

update public.course_outlines
   set course_title = 'Basic Grammar and Varieties of Writing', description = '(Description and topics reused from Computer Science''s outline for the same course.) Part A: Basic Grammar: Introduction. The concept of grammar and its place in language teaching and learning. Parts of speech and their functions (treated in detail). Closed and open class items in parts of speech, Nominalization, Grammatical Structures: the phrase, the clause and the sentence. Elementary Clause Analysis, Sentence Types, Elements and Patterns. Agreement (Grammatical agreement, Notional agreement, Proximity agreement) Agreement with the correlatives. Direct and Reported Speech, Error typology identification and correction.

Part B: Varieties of writing. Introduction (The Meaning, Nature and Purpose of Writing, Writing Types or Genres and their Characteristics). The paragraph as the basic unit of an essay (Types, Development of the Paragraph, Methods of Paragraph Development, The thesis statement). Point of view and style in writing. Qualities of a good piece of writing: Form, Diction and Content in writing. The Mechanics of Writing: punctuation, spelling and capitalization.

Part C: Writing Genres - Planning and choosing your theme. Deciding your genre. Choosing and developing your plot. Point of view, setting and characterization. Using the language that works. Essay Writing — Narration, Description, Exposition and Argumentation. Technical Writing: Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes, own story for practice, Computer-linked writing, types, style, language, and process.', topics = '["Part A: Basic Grammar - The concept of grammar, Parts of speech, Grammatical Structures, Sentence Types, Agreement, Direct and Reported Speech, Error typology", "Part B: Varieties of writing - Meaning, Nature and Purpose of Writing, the paragraph as the basic unit of an essay, the thesis statement, Qualities of a good piece of writing, Mechanics of Writing", "Part C: Writing Genres - Planning and choosing your theme, plot, point of view, setting and characterization", "Essay Writing - Narration, Description, Exposition and Argumentation", "Technical Writing - Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes"]'::jsonb
 where course_code = 'GSP 102' and department = 'Electrical Engineering';

update public.course_outlines
   set course_title = 'The Use of English II', description = '(Description and topics reused from Biochemistry''s outline for the same course.) Part A: Basic Grammar: Introduction. The concept of grammar and its place in language teaching and learning. Parts of speech and their functions (treated in detail). Closed and open class items in parts of speech, Nominalization, Grammatical Structures: the phrase, the clause and the sentence. Elementary Clause Analysis, Sentence Types, Elements and Patterns. Agreement (Grammatical agreement, Notional agreement, Proximity agreement) Agreement with the correlatives. Direct and Reported Speech, Error typology identification and correction.

Part B: Varieties of writing. Introduction (The Meaning, Nature and Purpose of Writing, Writing Types or Genres and their Characteristics). The paragraph as the basic unit of an essay (Types, Development of the Paragraph, Methods of Paragraph Development, The thesis statement). Point of view and style in writing. Qualities of a good piece of writing: Form, Diction and Content in writing. The Mechanics of Writing: punctuation, spelling and capitalization.

Part C: Writing Genres - Planning and choosing your theme. Deciding your genre. Choosing and developing your plot. Point of view, setting and characterization. Using the language that works. Essay Writing — Narration, Description, Exposition and Argumentation. Technical Writing: Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes, own story for practice, Computer-linked writing, types, style, language, and process.', topics = '["Part A: Basic Grammar - The concept of grammar, Parts of speech, Grammatical Structures, Sentence Types, Agreement, Direct and Reported Speech, Error typology", "Part B: Varieties of writing - Meaning, Nature and Purpose of Writing, the paragraph as the basic unit of an essay, the thesis statement, Qualities of a good piece of writing, Mechanics of Writing", "Part C: Writing Genres - Planning and choosing your theme, plot, point of view, setting and characterization", "Essay Writing - Narration, Description, Exposition and Argumentation", "Technical Writing - Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes"]'::jsonb
 where course_code = 'GSP 102' and department = 'Electronic Engineering';

update public.course_outlines
   set course_title = 'Basic Grammar and Varieties of Writing', description = '(Description and topics reused from Computer Science''s outline for the same course.) Part A: Basic Grammar: Introduction. The concept of grammar and its place in language teaching and learning. Parts of speech and their functions (treated in detail). Closed and open class items in parts of speech, Nominalization, Grammatical Structures: the phrase, the clause and the sentence. Elementary Clause Analysis, Sentence Types, Elements and Patterns. Agreement (Grammatical agreement, Notional agreement, Proximity agreement) Agreement with the correlatives. Direct and Reported Speech, Error typology identification and correction.

Part B: Varieties of writing. Introduction (The Meaning, Nature and Purpose of Writing, Writing Types or Genres and their Characteristics). The paragraph as the basic unit of an essay (Types, Development of the Paragraph, Methods of Paragraph Development, The thesis statement). Point of view and style in writing. Qualities of a good piece of writing: Form, Diction and Content in writing. The Mechanics of Writing: punctuation, spelling and capitalization.

Part C: Writing Genres - Planning and choosing your theme. Deciding your genre. Choosing and developing your plot. Point of view, setting and characterization. Using the language that works. Essay Writing — Narration, Description, Exposition and Argumentation. Technical Writing: Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes, own story for practice, Computer-linked writing, types, style, language, and process.', topics = '["Part A: Basic Grammar - The concept of grammar, Parts of speech, Grammatical Structures, Sentence Types, Agreement, Direct and Reported Speech, Error typology", "Part B: Varieties of writing - Meaning, Nature and Purpose of Writing, the paragraph as the basic unit of an essay, the thesis statement, Qualities of a good piece of writing, Mechanics of Writing", "Part C: Writing Genres - Planning and choosing your theme, plot, point of view, setting and characterization", "Essay Writing - Narration, Description, Exposition and Argumentation", "Technical Writing - Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes"]'::jsonb
 where course_code = 'GSP 102' and department = 'Mechatronic Engineering';

update public.course_outlines
   set course_title = 'The Use of English II', description = '(Description and topics reused from Biochemistry''s outline for the same course.) Part A: Basic Grammar: Introduction. The concept of grammar and its place in language teaching and learning. Parts of speech and their functions (treated in detail). Closed and open class items in parts of speech, Nominalization, Grammatical Structures: the phrase, the clause and the sentence. Elementary Clause Analysis, Sentence Types, Elements and Patterns. Agreement (Grammatical agreement, Notional agreement, Proximity agreement) Agreement with the correlatives. Direct and Reported Speech, Error typology identification and correction.

Part B: Varieties of writing. Introduction (The Meaning, Nature and Purpose of Writing, Writing Types or Genres and their Characteristics). The paragraph as the basic unit of an essay (Types, Development of the Paragraph, Methods of Paragraph Development, The thesis statement). Point of view and style in writing. Qualities of a good piece of writing: Form, Diction and Content in writing. The Mechanics of Writing: punctuation, spelling and capitalization.

Part C: Writing Genres - Planning and choosing your theme. Deciding your genre. Choosing and developing your plot. Point of view, setting and characterization. Using the language that works. Essay Writing — Narration, Description, Exposition and Argumentation. Technical Writing: Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes, own story for practice, Computer-linked writing, types, style, language, and process.', topics = '["Part A: Basic Grammar - The concept of grammar, Parts of speech, Grammatical Structures, Sentence Types, Agreement, Direct and Reported Speech, Error typology", "Part B: Varieties of writing - Meaning, Nature and Purpose of Writing, the paragraph as the basic unit of an essay, the thesis statement, Qualities of a good piece of writing, Mechanics of Writing", "Part C: Writing Genres - Planning and choosing your theme, plot, point of view, setting and characterization", "Essay Writing - Narration, Description, Exposition and Argumentation", "Technical Writing - Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes"]'::jsonb
 where course_code = 'GSP 102' and department = 'Metallurgical and Materials Engineering';

update public.course_outlines
   set course_title = 'The Use of Library and Study Skills', description = '(Description and topics reused from Biochemistry''s outline for the same course.) Overview of Library: concepts, history, types and functions. Uses in academic libraries; organization of university library and library users. Library processes and procedures. Acquisition process, Cataloging and classification, LC Scheme, in-House Scheme, DDC. Serials process and circulation processes. Access tools in Library resources: Library catalogues, Indexes, Abstracts, Current contents information in the library. Reference sources: types of reference sources and services. Web resources and online resources. Overview of Databases, Online search strategies for information retrieval. Referencing and citation styles for information reporting. Concept of plagiarism. Learning skills and research skills, ICT skillsets: types of learning and information policies.', topics = '["Overview of Library: concepts, history, types and functions. Uses in academic libraries; organization of university library and library users", "Library processes and procedures. Acquisition process, Cataloging and classification, LC Scheme, in-House Scheme, DDC. Serials process and circulation processes", "Access tools in Library resources: Library catalogues, Indexes, Abstracts, Current contents information", "Reference sources: types of reference sources and services. Web resources and online resources", "Overview of Databases, Online search strategies for information retrieval. Referencing and citation styles for information reporting. Concept of plagiarism", "Learning skills and research skills, ICT skillsets: types of learning and information policies"]'::jsonb
 where course_code = 'GSP 111' and department = 'Biomedical Engineering';

update public.course_outlines
   set course_title = 'Use of Library and Study Skills', description = '(Description and topics reused from Mathematics''s outline for the same course.) Overview of Library: concepts, history, types and functions. Uses in academic libraries; organization of university library and library users. Library processes and procedures. Acquisition process, Cataloging and classification, LC Scheme, in-House Scheme, DDC. Serials process and circulation processes. Access tools in Library resources: Library catalogues, Indexes, Abstracts, Current contents information in the library. Reference sources: types of reference sources and services. Web resources and online resources. Overview of Databases, Online search strategies for information retrieval. Referencing and citation styles for information reporting. Concept of plagiarism. Learning skills and research skills, ICT skillsets: types of learning and information policies.', topics = '["Overview of Library: concepts, history, types and functions. Uses in academic libraries; organization of university library and library users", "Library processes and procedures. Acquisition process, Cataloging and classification, LC Scheme, in-House Scheme, DDC. Serials process and circulation processes", "Access tools in Library resources: Library catalogues, Indexes, Abstracts, Current contents information", "Reference sources: types of reference sources and services. Web resources and online resources", "Overview of Databases, Online search strategies for information retrieval. Referencing and citation styles for information reporting. Concept of plagiarism", "Learning skills and research skills, ICT skillsets: types of learning and information policies"]'::jsonb
 where course_code = 'GSP 111' and department = 'Crop Science';

update public.course_outlines
   set course_title = 'The Use of Library and Study Skills', description = '(Description and topics reused from Biochemistry''s outline for the same course.) Overview of Library: concepts, history, types and functions. Uses in academic libraries; organization of university library and library users. Library processes and procedures. Acquisition process, Cataloging and classification, LC Scheme, in-House Scheme, DDC. Serials process and circulation processes. Access tools in Library resources: Library catalogues, Indexes, Abstracts, Current contents information in the library. Reference sources: types of reference sources and services. Web resources and online resources. Overview of Databases, Online search strategies for information retrieval. Referencing and citation styles for information reporting. Concept of plagiarism. Learning skills and research skills, ICT skillsets: types of learning and information policies.', topics = '["Overview of Library: concepts, history, types and functions. Uses in academic libraries; organization of university library and library users", "Library processes and procedures. Acquisition process, Cataloging and classification, LC Scheme, in-House Scheme, DDC. Serials process and circulation processes", "Access tools in Library resources: Library catalogues, Indexes, Abstracts, Current contents information", "Reference sources: types of reference sources and services. Web resources and online resources", "Overview of Databases, Online search strategies for information retrieval. Referencing and citation styles for information reporting. Concept of plagiarism", "Learning skills and research skills, ICT skillsets: types of learning and information policies"]'::jsonb
 where course_code = 'GSP 111' and department = 'Electrical Engineering';

update public.course_outlines
   set course_title = 'The Use of Library and Study Skills', description = '(Description and topics reused from Biochemistry''s outline for the same course.) Overview of Library: concepts, history, types and functions. Uses in academic libraries; organization of university library and library users. Library processes and procedures. Acquisition process, Cataloging and classification, LC Scheme, in-House Scheme, DDC. Serials process and circulation processes. Access tools in Library resources: Library catalogues, Indexes, Abstracts, Current contents information in the library. Reference sources: types of reference sources and services. Web resources and online resources. Overview of Databases, Online search strategies for information retrieval. Referencing and citation styles for information reporting. Concept of plagiarism. Learning skills and research skills, ICT skillsets: types of learning and information policies.', topics = '["Overview of Library: concepts, history, types and functions. Uses in academic libraries; organization of university library and library users", "Library processes and procedures. Acquisition process, Cataloging and classification, LC Scheme, in-House Scheme, DDC. Serials process and circulation processes", "Access tools in Library resources: Library catalogues, Indexes, Abstracts, Current contents information", "Reference sources: types of reference sources and services. Web resources and online resources", "Overview of Databases, Online search strategies for information retrieval. Referencing and citation styles for information reporting. Concept of plagiarism", "Learning skills and research skills, ICT skillsets: types of learning and information policies"]'::jsonb
 where course_code = 'GSP 111' and department = 'Mechatronic Engineering';

update public.course_outlines
   set course_title = 'Advanced Mathematics V', description = '(Description and topics reused from Mathematics''s outline for the same course.) Translation and rotation of axes, plane geometry of lines, circles and other simple curves, lines in space; equations of the plane, space curve. The Gaussian and mean curvatures, the geodesic and geodesic curvature.', topics = '["Translation and rotation of axes, plane geometry of lines, circles and other simple curves, lines in space", "Equations of the plane, space curve", "The Gaussian and mean curvatures, the geodesic and geodesic curvature"]'::jsonb
 where course_code = 'MTH 205' and department = 'Civil Engineering';

update public.course_outlines
   set course_title = 'Statistics for Physical Sciences and Engineering I', description = '(Description and topics reused from Computer Science''s outline for the same course.) Elective. Frequency Distributions. Elements of Probability. Discrete probability distributions: Binomial, Poisson, Geometric and Hyper-geometric. Continuous probability distributions: Normal, Student''s $t$, Chi-square $\chi^2$ and $F$. Combinatorial and moment generating functions.', topics = '["Frequency Distributions", "Elements of Probability", "Discrete probability distributions: Binomial, Poisson, Geometric and Hyper-geometric", "Continuous probability distributions: Normal, Student''s $t$, Chi-square $\\chi^2$ and $F$", "Combinatorial and moment generating functions"]'::jsonb
 where course_code = 'STA 205' and department = 'Agricultural and Bioresources Engineering';

update public.course_outlines
   set course_title = 'Statistics for Physical Sciences and Engineering I', description = '(Description and topics reused from Computer Science''s outline for the same course.) Elective. Frequency Distributions. Elements of Probability. Discrete probability distributions: Binomial, Poisson, Geometric and Hyper-geometric. Continuous probability distributions: Normal, Student''s $t$, Chi-square $\chi^2$ and $F$. Combinatorial and moment generating functions.', topics = '["Frequency Distributions", "Elements of Probability", "Discrete probability distributions: Binomial, Poisson, Geometric and Hyper-geometric", "Continuous probability distributions: Normal, Student''s $t$, Chi-square $\\chi^2$ and $F$", "Combinatorial and moment generating functions"]'::jsonb
 where course_code = 'STA 205' and department = 'Mechatronic Engineering';
