-- =============================================================================
-- Populate course_outlines from a real 54-page Faculty of Agriculture
-- handbook/prospectus the user supplied.
-- =============================================================================
-- FIRST PASS (superseded, see correction below): extracted via 3 parallel
-- passes attributing each course's department by its own code prefix (e.g.
-- CSC421 -> Crop Science). 159 rows were inserted, 9 updated. But this
-- document's actual convention is different: a department's curriculum page
-- legitimately lists OTHER departments' course codes as its own required
-- ancillary/elective courses (e.g. CSC321 appearing as an elective inside
-- Agricultural Economics' own programme structure), and a course's true
-- `department` for this table must be whichever department's curriculum
-- section it physically appears under -- not the subject its own code
-- prefix suggests. The user caught this ("go add those 38 ancillary courses
-- under the right agric department") after noticing courses were missing
-- from Agricultural Economics; a full re-check confirmed the same
-- mis-attribution affected many of the already-inserted rows too (e.g.
-- Agricultural Economics had zero 100-Level rows).
--
-- CORRECTION (applied live): the original 159 first-pass rows (identified
-- precisely via created_at timestamp, matching the original insert count
-- and per-department breakdown exactly) were deleted, and the document was
-- re-extracted with department attributed by page section / "DEPARTMENT OF
-- X" header / dominant "Major Courses" listing, not by code prefix. One
-- known agent error was caught and manually corrected during merge: pages
-- 1-16 were wrongly bulk-tagged "Agricultural Extension" based on a false
-- claim of a department header on page 5 (page 5 was directly re-read and
-- actually shows AEC 554/552/561/562/592 -- Agricultural Economics
-- content); corrected so AEC-coded courses in that block went to
-- Agricultural Economics and only genuinely AEX-coded courses stayed under
-- Agricultural Extension & Rural Development. Department names were also
-- canonicalized to exactly match the app's hardcoded department picker
-- list (lib/core/data/academic_structure.dart), fixing prior mismatches
-- such as "Agricultural Extension" -> "Agricultural Extension & Rural
-- Development", "Food Science and Technology" -> "Food Science &
-- Technology", "Home Science, Nutrition and Dietetics" -> "Home Science &
-- Management".
--
-- The corrected extraction produced 296 raw records, deduplicated by
-- (normalized course_code, department) to 292 unique records (preferring
-- whichever duplicate had the fuller description). Upserted against the
-- live table (matching by course_code + department; update only when the
-- new description was longer than what existed, otherwise insert):
--
--   inserted: 249   updated: 5   skipped (no improvement): 38
--
-- Final department distribution (Faculty of Agriculture, all rows):
--   Agricultural Economics                        62  (now includes 100 Level)
--   Agricultural Extension & Rural Development     25
--   Animal Science                                 71
--   Crop Science                                   86
--   Food Science & Technology                      14
--   Home Science & Management                      54
--   Soil Science                                   37
--   total                                          349
--
-- Applied live via direct psycopg2 upsert script -- this file is the
-- durable record, not a re-runnable script, since it targets specific
-- existing rows by id and contains large free-text descriptions.
-- =============================================================================
