-- =============================================================================
-- Fix: Food Science and Technology was missing almost its entire curriculum
-- past First Year, plus two other departments' Second Year gaps applied.
-- =============================================================================
-- The user checked their own account's Second Year outline directly in the
-- app and found the required ancillary courses missing -- confirmed against
-- the Faculty of Agriculture handbook (book pp.61-63, Food Science and
-- Technology's own Five Year Programme table): the department's ancillary
-- courses had only ever been extracted for First Year (fixed in an earlier
-- commit). Second Year onward was never done.
--
-- Checked all five levels against the book and found:
--   200 Level: 5 major courses existed, 0 ancillary. Inserted 16 (CHM 221/
--     222/232/273, STA 203/204, MCB 201, MEC 101, AGR 201, HND 211/212,
--     COS 101/202, GST 311/312).
--   300 Level: ZERO rows existed at all -- the entire Third Year was
--     missing, majors included. Inserted all 16 courses from both semesters
--     (FST 311/321/323/331/333/322/332/334 majors, plus CED 341/342,
--     BCH 381, MCB 325, AEC 202, CSC 544, GST 211/212 ancillary).
--   400 Level: only SIWES and Technical Writing existed. Inserted the 4
--     missing majors (FST 411/421/423/433) and 4 ancillary courses
--     (BCH 431, ANS 271, MCB 451, MCB 425).
--   500 Level: inserted 3 missing majors (FST 521 Food Packaging
--     Technology, FST 523/525 the two laboratory courses).
--
-- One item transcribed exactly as printed despite looking unusual: the book
-- cites "CSc 544" as a Third-Year ancillary (a 500-level code inside a
-- 300-level table) -- kept as printed rather than silently "corrected",
-- since I have no independent evidence of what the intended code was.
--
-- RESULT: Food Science and Technology now has real coverage at every level
-- (15/21/16/11/9 rows respectively), up from 15/5/0/3/6.
--
-- SEPARATE FIX applied in the same pass: a background agent had earlier
-- found and transcribed Agricultural Extension's and Soil Science's Second
-- Year tables (both were sitting at 1 row, same missing-ancillary pattern
-- as FST) from the same handbook, but that data was never applied -- an
-- urgent department-name audit interrupted the session before it could be.
-- Applied now: 38 rows inserted (19 Agricultural Extension, 19 Soil
-- Science), 1 already-present row skipped. Both departments now show 20
-- rows at 200 Level, up from 1 each.
--
-- STILL THIN, not yet resolved:
--   Agricultural Economics 100 Level (1 row) -- the handbook's First Year
--     table for this department sits on book pages 1-9, which were never
--     among the 88 photographed pages. Needs a new photo, not a re-read.
--   Animal Science 200 Level (6 rows) and Soil Science 300/400/500 Level
--     (4 rows each) -- not yet individually re-checked against the book;
--     may be genuinely thin (smaller elective-heavy years) or may be the
--     same missing-ancillary pattern. Worth a dedicated check.
--   Home Science and Management 500 Level (0 rows) -- confirmed earlier
--     this is NOT a bug: the book states this is a four-year programme,
--     so no 500 Level exists to have courses.
--
-- Applied live via direct psycopg2 scripts -- this file is the durable
-- record, not a re-runnable script.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- THIRD PASS: filled 13 more real descriptions after the user pointed out
-- several FST courses still showed no "About this course" content.
-- -----------------------------------------------------------------------------
-- Re-scanned the handbook's own FST COURSE DESCRIPTION section (book
-- pp.67-72, correcting an earlier page-range estimate of pp.61-63 which was
-- actually FST's structure tables, not its descriptions). Found and applied
-- real prose for 13 of the 24 rows still blank: FST 321, 322, 331, 332,
-- 333, 334, 411, 421, 423, 433, 521, 523, 525.
--
-- Confirmed genuinely absent from this handbook (swept all 88 pages, not
-- just FST's own section): CHM 221, CHM 222, CHM 232, CHM 273, CED 341,
-- CED 342, TED 222, TED 154, MEC 101, AGR 201, BIO 151. These are service
-- courses owned by other faculties (Physical Sciences, Education,
-- Engineering, the entrepreneurship centre) -- this Agriculture handbook
-- was never going to carry their syllabi. They need those departments' own
-- source material, not another pass over this book.
--
-- Also checked whether Pure and Industrial Chemistry's own course_outlines
-- entries could supply CHM 221/222/232/273 by cross-reference, per the
-- user's suggestion -- they don't: that department uses entirely different
-- course numbers for its 200-level organic/analytical chemistry (CHM 371,
-- 372, 373, 324), not 221/222/232/273. No cross-reference match exists.
-- -----------------------------------------------------------------------------

-- -----------------------------------------------------------------------------
-- FOURTH PASS: 5 more courses filled from documents already on hand.
-- -----------------------------------------------------------------------------
-- The user photographed the Faculty of Engineering handbook's "Combined
-- Honours Degree / Course Description" section (book p.214, right after the
-- individual department chapters end) and sent it directly -- it carries
-- CHM 221, 222, 232 and 273's real descriptions. Applied app-wide: 12 rows
-- filled across every department that had these codes blank, not just FST.
--
-- Also found MEC 101 "Technical Drawing" could be filled by cross-reference
-- after all: MEE 181 "Technical Drawing I" (Mechanical Engineering, from
-- the earlier handbook) is the same course under Engineering's own real
-- prefix. Filled MEC 101 from it.
--
-- CONFIRMED, database-wide (not just Agriculture), that CED 341/342, AGR
-- 201, BIO 151, and TED 154/222 have NO description anywhere in
-- course_outlines at all, across any department, in any handbook processed
-- so far -- Agriculture, Physical Sciences, Social Sciences, or either
-- Engineering handbook. These need their own owning-unit source documents:
-- CED (Centre for Entrepreneurship Development, not a faculty), Biological
-- Sciences (BIO 151), and Education/Vocational Technical Education
-- (TED 154/222) -- none of which have been uploaded yet.
-- -----------------------------------------------------------------------------
