-- =============================================================================
-- University of Nigeria, Nsukka — Faculty of Social Sciences —
-- Public Administration and Local Government
-- Course outlines transcribed from the Faculty of Social Sciences course
-- handbook (scanned copy), covering the "Revised Four-Year Standard
-- Undergraduate Programme in Public Administration": all four years, both
-- semesters, including required ancillary, general-studies and elective
-- courses. The source document itself titles the department simply "Public
-- Administration"; the department string used below matches this app's own
-- list, "Public Administration and Local Government".
-- =============================================================================
-- Run in the Supabase SQL Editor. Safe to run more than once: existing rows
-- for this department are removed first, so it updates rather than duplicates.
--
-- SEMESTERS: the handbook explicitly labels every course "FIRST SEMESTER" or
-- "SECOND SEMESTER" in its programme-structure tables, so those stated values
-- are used directly — no guessing was needed here.
--
-- PUB 170 ("Introduction to Public Policy") has a real description printed
-- in the source but its placement in the programme-structure table could not
-- be confidently located (the table itself only clearly lists five 100-Level
-- second-semester majors); it is filed under 100 Level second semester,
-- adjacent to where its description appears in print, but this placement is
-- a judgment call, not a confirmed reading — flagging it here for correction
-- if it belongs elsewhere.
--
-- Two course-description headings had a title that differed from the
-- structure table: PUB 241 is titled "Introduction to Cost and Management
-- Accounting" in the structure table but "Introduction to Financial
-- Accounting I" on its own description page — the description heading's
-- title is used since it is the more specific source.
--
-- ANCILLARY/GSP/ELECTIVE COURSES FROM OTHER DEPARTMENTS: courses such as
-- COS 101/304, PHIL 101, SOC 101/102, PSY 101/102, ECO 101/102, EDU 102,
-- FSS 201/202, GSP 1xx/2xx and CED 341/342 appear in the Public
-- Administration timetable but their own descriptions are not printed in
-- this section of the document, so they carry real code/title/units only,
-- description left blank pending a verified source elsewhere in this app.
-- =============================================================================

delete from public.course_outlines
 where institution = 'University of Nigeria, Nsukka'
   and department = 'Public Administration and Local Government';

insert into public.course_outlines
  (course_code, course_title, institution, faculty, department, level,
   semester, credit_units, description, topics, contributor_name)
values
  ('PUB 101', 'Introduction to Public Administration I', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'first', 2, 'This course focuses on the nature and scope of Public Administration. It examines the scientific, organizational and bureaucratic approaches to the study of Public Administration as well as the basic principles of administration, power and efficiency in administrative situations.', '["This course focuses on the nature and scope of Public Administration", "It examines the scientific, organizational and bureaucratic approaches to the study of Public Administration", "As well as the basic principles of administration, power and efficiency in administrative situations"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 103', 'Elements of Political Science I', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'first', 2, 'This course introduces students to the nature of politics. It emphasizes the issues of Political discourse and practice. It also introduces students to the basic concepts of political science that includes state, sovereignty, class, power, authority, legitimacy, democracy, separation of powers, checks and balances, rule of law and violence.', '["This course introduces students to the nature of politics. It emphasizes the issues of Political discourse and practice", "It also introduces students to the basic concepts of political science that includes state, sovereignty, class, power, authority, legitimacy", "Democracy, separation of powers, checks and balances, rule of law and violence"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 105', 'Elementary Mathematics for Public Administration I', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'first', 2, 'This course is designed to expose students to elementary mathematics in the context of Public Administration. At the end of the course the students are expected to know how some basic mathematics are applied for efficient and effective administration. Mathematics is used in Public Administration for comparisons, evaluations, projection, report presentation, analysis.', '["This course is designed to expose students to elementary mathematics in the context of Public Administration", "At the end of the course the students are expected to know how some basic mathematics are applied for efficient and effective administration", "Mathematics is used in Public Administration for comparisons, evaluations, projection, report presentation, analysis"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 102', 'Introduction to Public Administration II', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'second', 2, 'It is expected that at the end of this course, students will be able to discuss the relationship between Public Administration and other disciplines especially in the social science. Other areas of focus include the processes of public administration, power, authority, legitimacy, and the use of sanction, in public administration.', '["It is expected that at the end of this course, students will be able to discuss the relationship between Public Administration and other disciplines especially in the social science", "Other areas of focus include the processes of public administration, power, authority, legitimacy", "The use of sanction, in public administration"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 104', 'Elements of Political Science II', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'second', 2, 'This course provides an understanding of the major issues of political science which includes the philosophical approach, the historical approach, the power methods, the behavioral approach, the systems approach, the game theory, the decision-making approach, the communications/cybernetics approach, and the centre-periphery approach. It will discuss the relationships between political science and other disciplines (Public Administration, Economics, Sociology, Psychology, Religion, Philosophy and Law). The course will also examine the classification of political systems (Liberal democratic system, mobilization political system and transitional political system). Finally, the modern political structures such as executive, legislature and judiciary.', '["This course provides an understanding of the major issues of political science which includes the philosophical approach, the historical approach, the power methods, the behavioral approach, the systems approach, the game theory, the decision-making approach, the communications/cybernetics approach, and the centre-periphery approach", "It will discuss the relationships between political science and other disciplines (Public Administration, Economics, Sociology, Psychology, Religion, Philosophy and Law)", "The course will also examine the classification of political systems (Liberal democratic system, mobilization political system and transitional political system)", "Finally, the modern political structures such as executive, legislature and judiciary"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 106', 'Elementary Mathematics for Public Administration II', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'second', 2, 'This course is designed to expose the students to basic mathematics that are useful for project appraisal and decision making in Public Administration. They are also useful for the selection of items method analysis. They include: Statistics, Sets: the decisions making on the areas of finance figures and volume. Matrices and other tools; Admission to find the areas of plane figures and volume. This will include Hero''s formula, surface area and volume.', '["This course is designed to expose the students to basic mathematics that are useful for project appraisal and decision making in Public Administration", "They are also useful for the selection of items method analysis. They include: Statistics, Sets: the decisions making on the areas of finance figures and volume", "Matrices and other tools; Admission to find the areas of plane figures and volume", "This will include Hero''s formula, surface area and volume"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 120', 'Principles of Management', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'second', 3, 'This course seeks to acquaint students with the nature of management concepts and functions as well as validity. It comprises a brief review of management principles like planning, organizing, controlling, etc. The problems of implementing management principles also form part of the area of focus.', '["This course seeks to acquaint students with the nature of management concepts and functions as well as validity", "It comprises a brief review of management principles like planning, organizing, controlling, etc", "The problems of implementing management principles also form part of the area of focus"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 122', 'Introduction to Organisations', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'second', 2, 'This course is designed to expose students to the concepts and basic elements of organizations. Important organisational principles and work and organisational patterns are also covered by the course.', '["This course is designed to expose students to the concepts and basic elements of organizations", "Important organisational principles and work and organisational patterns are also covered by the course"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 170', 'Introduction to Public Policy', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'second', 2, 'This course introduces the study of public policy and its importance in modern and complex society. It differentiates between public and private policies, as well as policies and decisions. Furthermore, it examines a wide range of topics such as how issues are placed on the agenda; who makes policy, how institutions function and interact and what constraints opportunities for improved policy making.', '["This course introduces the study of public policy and its importance in modern and complex society", "It differentiates between public and private policies, as well as policies and decisions", "It examines a wide range of topics such as how issues are placed on the agenda; who makes policy, how institutions function and interact and what constraints opportunities for improved policy making"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 220', 'Administration and Environment', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '200 Level', 'second', 2, 'This course will examine anti-bureaucratic concepts in Nigeria Public Administration; the political environment of Nigeria colonial and Pre-colonial and Post-colonial era as well as Socio-political economic environment of Public Administration in first, second, as well as third Republic in Nigeria. This also emphasizes environment administration through a critical discussion of the ecology of administration, the politics of administration and varieties of these in different ecological systems.', '["This course will examine anti-bureaucratic concepts in Nigeria Public Administration", "The political environment of Nigeria colonial and Pre-colonial and Post-colonial era as well as Socio-political economic environment of Public Administration in first, second, as well as third Republic in Nigeria", "This also emphasizes environment administration through a critical discussion of the ecology of administration, the politics of administration and varieties of these in different ecological systems"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 221', 'Nigeria Public Administration', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '200 Level', 'first', 2, 'This course exposes students to the peculiarities of Public Administration in Nigeria. It traces the historical roots of Nigerian Public Administration and analyses the processes of Administration in Nigeria. Crucial issues in Nigerian Public Administration are part of its focus.', '["This course exposes students to the peculiarities of Public Administration in Nigeria", "It traces the historical roots of Nigerian Public Administration and analyses the processes of Administration in Nigeria", "Crucial issues in Nigerian Public Administration are part of its focus"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 223', 'Introduction to Business Communication', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '200 Level', 'first', 2, 'Rudiments of communication: communication defined, elements of communication, principles of communication; oral, written and non-verbal communication, language defined, non-verbal communication: listening, oral and written communication, functions and settings of communication: functions of communication, communication setting, communication process, corporate and public communications, commercial communication method and letter writing.', '["Rudiments of communication: communication defined, elements of communication, principles of communication", "Oral, written and non-verbal communication, language defined, non-verbal communication: listening, oral and written communication", "Functions and settings of communication: functions of communication, communication setting, communication process", "Corporate and public communications, commercial communication method and letter writing"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 241', 'Introduction to Financial Accounting I', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '200 Level', 'first', 2, 'This course examines the nature and scope of accounting: the role of accountants; the accounting function and its relationship with the information systems of organizations; It also examines accounting procedure and system; double entry book-keeping systems, balance, accruals, prepayments and adjustments; classifications of expenditure between capital and revenue. Methods of recording accounting data: manual and mechanical.', '["This course examines the nature and scope of accounting: the role of accountants", "The accounting function and its relationship with the information systems of organizations", "It also examines accounting procedure and system; double entry book-keeping systems, balance, accruals, prepayments and adjustments", "Classifications of expenditure between capital and revenue. Methods of recording accounting data: manual and mechanical"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 251', 'Introduction to Human Resource Management', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '200 Level', 'first', 2, 'This course examines the importance of the human factor in organizations. It focuses on issues such as public and private sector recruitment process, promotions, discipline, training, motivation, line and staff relationships and performance appraisal.', '["This course examines the importance of the human factor in organizations", "It focuses on issues such as public and private sector recruitment process, promotions, discipline, training", "Motivation, line and staff relationships and performance appraisal"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 240', 'Introduction to Public Financial Administration', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '200 Level', 'second', 2, 'This course examines the theory of Public Finance, the nature of the public sector, the theory of public revenue and expenditure, Instruments of taxation, Management of public debts, finance and Audit Acts, Financial Institutions, the budget process.', '["This course examines the theory of Public Finance, the nature of the public sector, the theory of public revenue and expenditure", "Instruments of taxation, Management of public debts", "Finance and Audit Acts, Financial Institutions, the budget process"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 242', 'Introduction to Financial Accounting II', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '200 Level', 'second', 2, 'This course focuses on Manufacturing, trading and profit and loss accounts and balance sheet of company/business organization; accounting treatment of control accounts and bank reconciliations, receipts and payment accounts. Methods of correction of errors, incomplete records and single entry book keeping.', '["This course focuses on Manufacturing, trading and profit and loss accounts and balance sheet of company/business organization", "Accounting treatment of control accounts and bank reconciliations, receipts and payment accounts", "Methods of correction of errors, incomplete records and single entry book keeping"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 262', 'Nigerian Legal System', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '200 Level', 'second', 2, 'This course examines the idea of a legal system and its importance in modern society. It examines the nature of law in general with respect to traditional and modern laws. It also discusses the sources of Nigerian Law among others. This course examines the court system, outline of civil and criminal procedures, the role of judicial officers and their appointment and tenure. It also focuses on the legal profession, as conflicts and resolution of conflicts.', '["This course examines the idea of a legal system and its importance in modern society", "It examines the nature of law in general with respect to traditional and modern laws. It also discusses the sources of Nigerian Law among others", "This course examines the court system, outline of civil and criminal procedures, the role of judicial officers and their appointment and tenure", "It also focuses on the legal profession, as conflicts and resolution of conflicts"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 301', 'Theories of Development', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '300 Level', 'first', 2, 'This course examines the major theories of development as they apply and explain third world underdevelopment. It is a conglomeration of theories drawn from a variety of social science disciplines and approaches. Efforts will be made to address emerging development issues and paradigms in Nigeria.', '["This course examines the major theories of development as they apply and explain third world underdevelopment", "It is a conglomeration of theories drawn from a variety of social science disciplines and approaches", "Efforts will be made to address emerging development issues and paradigms in Nigeria"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 321', 'Project Management', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '300 Level', 'first', 2, 'The central purpose of this course is to examine the relevance of methods and techniques of project planning and execution. It develops a foundation of concepts and solutions that supports the planning, scheduling, controlling, resource allocation and performance activities required for successful completion of development projects.', '["The central purpose of this course is to examine the relevance of methods and techniques of project planning and execution", "It develops a foundation of concepts and solutions that supports the planning, scheduling, controlling, resource allocation and performance activities required for successful completion of development projects"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 323', 'Urban Administration', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '300 Level', 'first', 2, 'This course discusses the history of the contemporary planning movement, the scope and goals of comprehensive planning; community decision-making processes, problems of urbanization and their implications for public policy and administration.', '["This course discusses the history of the contemporary planning movement, the scope and goals of comprehensive planning", "Community decision-making processes, problems of urbanization and their implications for public policy and administration"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 325', 'Traditional Administrative System in Nigeria', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '300 Level', 'first', 2, 'This course discusses the early history of Nigeria, culture in detail, migration and formation of centralized institutions. Hausa state, Kanem-Bornu, Yoruba states, Benin etc. and administration in those states. Formation of acephalous groups east and west of the Niger delta, north and south of the Benue; administration within these groups.', '["This course discusses the early history of Nigeria, culture in detail, migration and formation of centralized institutions", "Hausa state, Kanem-Bornu, Yoruba states, Benin etc. and administration in those states", "Formation of acephalous groups east and west of the Niger delta, north and south of the Benue; administration within these groups"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 351', 'Principles of Public Sector Industrial Relation', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '300 Level', 'first', 2, 'The aim of this course is to get students acquainted with the concepts and principles of public sector industrial relations. It focuses on the historical antecedents of labour and industrial relations as well as their associated problems in Nigerian public enterprises.', '["The aim of this course is to get students acquainted with the concepts and principles of public sector industrial relations", "It focuses on the historical antecedents of labour and industrial relations as well as their associated problems in Nigerian public enterprises"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 361', 'Administrative Law', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '300 Level', 'first', 2, 'This course examines the classification of government powers, the concepts of delegated legislation and the rule-making powers of administrative agencies as well as the parliamentary and judicial review of administrative actions, and the legal liability of government.', '["This course examines the classification of government powers, the concepts of delegated legislation and the rule-making powers of administrative agencies", "As well as the parliamentary and judicial review of administrative actions, and the legal liability of government"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 381', 'Research Methods', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '300 Level', 'first', 3, 'This course introduces students to the research process, beginning with the conceptual and theoretical knowledge to the execution of research projects. By examining the practical steps involved in research execution from the statement of problem to bibliographic citation methods.', '["This course introduces students to the research process, beginning with the conceptual and theoretical knowledge to the execution of research projects", "By examining the practical steps involved in research execution from the statement of problem to bibliographic citation methods"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 302', 'Organization and Administrative Theory', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '300 Level', 'second', 2, 'This course focuses on origins, structure and management of organizations, formal and informal organizations, the impact on informal norms in formal organization; Organization theories; co-ordination, efficiency, retrenchment and growth, motivation, leadership.', '["This course focuses on origins, structure and management of organizations, formal and informal organizations, the impact on informal norms in formal organization", "Organization theories; co-ordination, efficiency, retrenchment and growth, motivation, leadership"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 330', 'Inter-Governmental Relations in Nigeria', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '300 Level', 'second', 2, 'This course focuses on the character of inter-governmental relations in a federal system of government. Issues examined include the dynamics of such relations; types of inter-government relation; problems and solutions in inter-governmental relations management; inter-governmental fiscal relations (fiscal federalism) problems of controlling lower tiers of government particularly the local government.', '["This course focuses on the character of inter-governmental relations in a federal system of government", "Issues examined include the dynamics of such relations; types of inter-government relation; problems and solutions in inter-governmental relations management", "Inter-governmental fiscal relations (fiscal federalism) problems of controlling lower tiers of government particularly the local government"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 340', 'Auditing for Public Administrators', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '300 Level', 'second', 2, 'This course focuses on principles of auditing, internal control and internal check; audit programme, verification of Balance Sheet items; audit queries and reports, rights, duties, and liabilities of auditors and investigations/audit reports of federal and state government case studies.', '["This course focuses on principles of auditing, internal control and internal check; audit programme, verification of Balance Sheet items", "Audit queries and reports, rights, duties, and liabilities of auditors", "Investigations/audit reports of federal and state government case studies"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 342', 'Government Accounting', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '300 Level', 'second', 2, 'This course introduces government accounts and focuses on issues such as authorization to incur expenditure; account; government budgets and revenue accounting. It includes preparation of Federation, Consolidated Revenue Fund, Development and Contingency Accounts. Universities and Hospital Accounts, Abstract Accounts for local Governments and other agencies accounts as well.', '["This course introduces government accounts and focuses on issues such as authorization to incur expenditure; account; government budgets and revenue accounting", "It includes preparation of Federation, Consolidated Revenue Fund, Development and Contingency Accounts", "Universities and Hospital Accounts, Abstract Accounts for local Governments and other agencies accounts"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 352', 'Personnel Administration', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '300 Level', 'second', 2, 'This course examines issues bordering on personnel management concepts and principles of personnel management approaches, line and staff organization structure, personnel policies, employment procedures and processes. It also focuses on manpower planning and development, theories and application of motivation in personnel management.', '["This course examines issues bordering on personnel management concepts and principles of personnel management approaches, line and staff organization structure, personnel policies, employment procedures and processes", "It also focuses on manpower planning and development, theories and application of motivation in personnel management"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 412', 'Management Problems in the Local Government System in Nigeria', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '400 Level', 'second', 2, 'A study of various management problems in the local government - leadership, manpower, effectiveness, and responsibility to the local government, urbanization, impact of the various reforms on the identifiable management problems.', '["A study of various management problems in the local government - leadership, manpower, effectiveness, and responsibility to the local government", "Urbanization, impact of the various reforms on the identifiable management problems"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 420', 'Comparative Public Administration', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '300 Level', 'second', 2, 'This course exposes students to public administration processes in selected developed and developing countries. A comparative study of levels, shapes and methods of control of the public service in selected countries constitute its area of focus.', '["This course exposes students to public administration processes in selected developed and developing countries", "A comparative study of levels, shapes and methods of control of the public service in selected countries constitute its area of focus"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 421', 'Development Administration', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '400 Level', 'first', 3, 'This course introduces students to the concept of Development Administration. It discusses the main ideas/philosophies of development administration. Other areas of focus include the role of bureaucrats in development administration; politics and problems of development administration.', '["This course introduces students to the concept of Development Administration", "It discusses the main ideas/philosophies of development administration", "Other areas of focus include the role of bureaucrats in development administration; politics and problems of development administration"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 423', 'Public Enterprises Management', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '400 Level', 'first', 3, 'This course aims at imparting the students with the knowledge of the aims and classifications of public enterprises in Nigeria. It also analyses government policies on public enterprises with emphasis on membership of boards, staffing, and finance of public enterprises.', '["This course aims at imparting the students with the knowledge of the aims and classifications of public enterprises in Nigeria", "It also analyses government policies on public enterprises with emphasis on membership of boards, staffing, and finance of public enterprises"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 424', 'Social Service and Welfare Administration in Nigeria', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '400 Level', 'second', 2, 'This course examines the nature and development of social policy in the context of changing social conditions and of the impact upon family and group organization of welfare policies and social services in Nigeria. Other major topics taken up are groups in special needs, criminology, policies and problems in education, social policy, health services, and social services in general in their organizational context with particular reference to evaluating their effectives.', '["This course examines the nature and development of social policy in the context of changing social conditions and of the impact upon family and group organization of welfare policies and social services in Nigeria", "Other major topics taken up are groups in special needs, criminology, policies and problems in education, social policy, health services", "Social services in general in their organizational context with particular reference to evaluating their effectiveness"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 426', 'Administration and Technology', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '400 Level', 'second', 2, 'The concepts of administration and technology will be operationalized. Other areas that will be studied include the problems of technological transfer and administration, models of development economics in transition and their historical experience in relation with development policies.', '["The concepts of administration and technology will be operationalized", "Other areas that will be studied include the problems of technological transfer and administration", "Models of development economics in transition and their historical experience in relation with development policies"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 431', 'Democratic Studies', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '400 Level', 'first', 3, 'Political Theories of Democracy; Analysis of Processes and institutions of democracy; democracy and democratic dynamics in Nigeria; electoral participation and procedures in Nigeria; Trends, problems and prospects; human rights and democracy; national/ global context of political development; developing techniques for the empowerment of constituencies; parameters which constrain collective institutions and the state.', '["Political Theories of Democracy; Analysis of Processes and institutions of democracy; democracy and democratic dynamics in Nigeria", "Electoral participation and procedures in Nigeria; Trends, problems and prospects", "Human rights and democracy; national/global context of political development", "Developing techniques for the empowerment of constituencies; parameters which constrain collective institutions and the state"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 441', 'Public Financial Management', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '400 Level', 'first', 3, 'The course focuses on the processes and activities of how government Federal, State and Local Governments generate revenue utilize it for the attainment of stated objectives. It also focuses on the concept of fiscal federalism, tax revenue control issues, review of country experiences in revenue allocation under the Nigerian federal structure, resource control issues, review of country experiences in revenue allocation, etc.', '["The course focuses on the processes and activities of how government Federal, State and Local Governments generate revenue utilize it for the attainment of stated objectives", "It also focuses on the concept of fiscal federalism, tax revenue control issues", "Review of country experiences in revenue allocation under the Nigerian federal structure, resource control issues, etc"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 442', 'Public Administration Ethics', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '400 Level', 'second', 2, 'This course examines the place of ethics in Public Administration. It analyses the nature and significance of ethics, classical ethical theories of Plato, Aristotle, Epicurus, the stoics etc. Modern ethics and the philosophical analysis of behaviour are areas of focus. In addition, attention will be focused on ethical codes, civil general order (GO) and contemporary ethical problems in Public Administration and Financial Administration.', '["This course examines the place of ethics in Public Administration. It analyses the nature and significance of ethics, classical ethical theories of Plato, Aristotle, Epicurus, the stoics etc", "Modern ethics and the philosophical analysis of behaviour are areas of focus", "Attention will be focused on ethical codes, civil general order (GO) and contemporary ethical problems in Public Administration and Financial Administration"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 443', 'Public Sector Budgeting', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '400 Level', 'first', 2, 'This course examines the general purpose of budgeting and types of budgets, Comparative public sector budgetary systems: Nigeria, U.K., U.S.A. or Russia, General aspects of public expenditure, causes of increasing government expenditure, fiscal policy, and its element public debt and economic policy, Obstacle to effective revenue mobilization and management planning, programming, budgeting system.', '["This course examines the general purpose of budgeting and types of budgets, Comparative public sector budgetary systems: Nigeria, U.K., U.S.A. or Russia", "General aspects of public expenditure, causes of increasing government expenditure, fiscal policy, and its element public debt and economic policy", "Obstacle to effective revenue mobilization and management planning, programming, budgeting system"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 450', 'Demographic Perspective in Public Administration', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '400 Level', 'second', 2, 'This course deals with population factors and their implications for public administration. It emphasizes how population growth, migration and other population factors impact on the administrative process. It further emphasizes the impact of demographic dynamics on policy making and its implementation.', '["This course deals with population factors and their implications for public administration", "It emphasizes how population growth, migration and other population factors impact on the administrative process", "It further emphasizes the impact of demographic dynamics on policy making and its implementation"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 451', 'Manpower Planning and Development', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '400 Level', 'first', 3, 'Manpower planning and development issues are central to this course. The place of training, recruitment, selection and promotion, in human resources planning will be fully involved. In this course, essential elements related to the processes and challenges of matching people with the required positions in organisations will be stressed.', '["Manpower planning and development issues are central to this course", "The place of training, recruitment, selection and promotion, in human resources planning will be fully involved", "Essential elements related to the processes and challenges of matching people with the required positions in organisations will be stressed"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 452', 'Information and Communication Management', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '400 Level', 'second', 2, 'This course focuses on information communication system in an organization. It discusses issues such as report writing, preparation of council and committee minutes, letter writing etc. Appropriate techniques for modern information gathering, storage and retrieval are also to be discussed.', '["This course focuses on information communication system in an organization", "It discusses issues such as report writing, preparation of council and committee minutes, letter writing etc", "Appropriate techniques for modern information gathering, storage and retrieval are also to be discussed"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 471', 'Public Policy Analysis', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '400 Level', 'first', 3, 'This course deals with nature and Complexity of public Policy Making; Implementation and Evaluation, Basic Concepts like Policy, Policy Arena, the Policy Cycle, are defined and illustrated. Formal and Informal ways of Generating Policy. Theories of Decision-making, General Economic and Social Development Policy, Health, Sanitation and Welfare Policy; Housing Policy, Defence and Foreign Policy; Education Policy, Agriculture and Rural Development Policy.', '["This course deals with nature and Complexity of public Policy Making; Implementation and Evaluation, Basic Concepts like Policy, Policy Arena, the Policy Cycle, are defined and illustrated", "Formal and Informal ways of Generating Policy. Theories of Decision-making", "General Economic and Social Development Policy, Health, Sanitation and Welfare Policy", "Housing Policy, Defence and Foreign Policy; Education Policy, Agriculture and Rural Development Policy"]'::jsonb, 'Department of Public Administration handbook'),
  ('PUB 490', 'Project', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '400 Level', 'second', 6, 'This focuses on developing students'' skill in writing, analysing and presenting research reports based on an extensive research of a specific subject matter or topic in relevant areas such as administration, management, public policies, development, etc. Students are expected to present a research - based report of not less than 40 pages at the end of session.', '["This focuses on developing students'' skill in writing, analysing and presenting research reports based on an extensive research of a specific subject matter or topic in relevant areas such as administration, management, public policies, development, etc", "Students are expected to present a research - based report of not less than 40 pages at the end of session"]'::jsonb, 'Department of Public Administration handbook'),
  -- Required ancillary / general studies / elective courses from other departments — real code/title/units from the timetable, description left blank pending a verified source.
  ('COS 101', 'Introduction to Computer Science', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'first', 2, 'Concepts of hardware and software; basic subsystems of a digital computer; characteristics of a digital computer; devices/media; types/classes of computer emphasising the PC; history of computers and their generations. Problem-solving: algorithm, flowchart, pseudocode, program/data, running a program. Programming: introduction to Java/BASIC programming language syntax and programming. Booting and shutdown; types of operating system; user interface; managing information, computer malware (virus, etc); computer network; internet and web usage, e-mail, instant messaging, etc. Office applications; use of a statistical package and a database management system.', '["Concepts of hardware and software","basic subsystems of a digital computer","characteristics of a digital computer","devices/media","types/classes of computer emphasising the PC","history of computers and their generations","Problem-solving: algorithm, flowchart, pseudocode, program/data, running a program","Programming: introduction to Java/BASIC programming language syntax and programming","Booting and shutdown","types of operating system","user interface","managing information, computer malware (virus, etc)","computer network","internet and web usage, e-mail, instant messaging, etc","Office applications","use of a statistical package and a database management system"]'::jsonb, 'Department of Computer Science course outline'),
  ('PHIL 101', 'Introduction to Philosophy', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'first', 2, 'The nature and the principal branches of Philosophy: philosophical problems of other disciplines; introduction to African Philosophical Thought, Philosophical method; illustrations from the history of philosophy.', '["The nature and the principal branches of Philosophy", "Philosophical problems of other disciplines", "Introduction to African Philosophical Thought, Philosophical method", "Illustrations from the history of philosophy"]'::jsonb, 'Department of Philosophy handbook'),
  ('SOC 101', 'Introduction to Sociology I', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Social Sciences course handbook'),
  ('PSY 101', 'Introduction to Psychology I', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'first', 2, 'The Science of Psychology: History of Psychology Research methods in Psychology Fields of Psychology and other Disciplines. Biological Basis of Human Development.', '["The Science of Psychology: History of Psychology", "Research methods in Psychology", "Fields of Psychology and other Disciplines", "Biological Basis of Human Development"]'::jsonb, 'Department of Psychology handbook'),
  ('ECO 101', 'Principles of Economics', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'first', 2, 'Nature and significance of Economics; The methodology of economics; Economic tools of analysis; Theories of demand and supply; Elementary analysis; Dynamic theory of price; Elements of price theory; Production theory: Output, cost, law of diminishing returns; Market structure: Perfect competition, monopoly, oligopoly etc; Elementary theory of welfare economics; Determinants for and pricing of productive factors; Interest rate and profit.', '["Nature and significance of Economics", "The methodology of economics", "Economic tools of analysis", "Theories of demand and supply", "Elementary analysis", "Dynamic theory of price", "Elements of price theory", "Production theory: Output, cost, law of diminishing returns", "Market structure: Perfect competition, monopoly, oligopoly etc", "Elementary theory of welfare economics", "Determinants for and pricing of productive factors", "Interest rate and profit"]'::jsonb, 'Department of Economics handbook'),
  ('GSP 101', 'The Use of English I', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'first', 2, 'Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, The English Language and the Nigerian society, World English, Levels and Varieties of English — formal, informal, standard, etc., English in Literature and the Media.

Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes, English Language Register, diatypes and dialects.

Listening skill - The listening skill discussed as a receptive and reciprocal activity, Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening.

Reading Skill - The concept of reading as a linguistic organization and a vehicle of communication. Reading Problems, Levels of Reading, Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies (Scanning, Skimming, Phrase reading, Intensive & Extensive reading, Exploiting the topic sentence for main ideas), Reading for details, Reading for evaluation and inference, Reading with questions - SQ3R, PR3, Methods for understanding difficult words in a reading text, Literature reading for study, analysis and comment.

Speaking & Communication Skills - Nature, Process & Development, Principles of Public Speech Making and Social Interaction, The Speech Sounds of English and their Articulation, Phonetic Transcription and Practical Speech Work.

Study Techniques - Choosing study centers and discussion groups, Note-taking during lectures, and from audio-visual equipment, Note-making techniques during private reading and literature search, Summary & Transcoding Techniques, Retrieving information from notes, The dictionary as a study guide.

Basic Research Methods & Term Paper Writing - Research – meaning & nature, Types & Methodology; Data in the Research Process, The Research Report, Process and Techniques, Documentation in Research Reports: Process, Types and Methods, Abbreviations in Research Reports, The term paper as a miniature research report, Practical term paper writing.

Course Evaluation & Grading - Students must attend at least 75% of the lectures to qualify for examination in the course.', '["Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, World English, Levels and Varieties of English", "Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes", "Listening skill - Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening", "Reading Skill - Reading Problems, Levels and Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies, Reading for evaluation and inference", "Speaking & Communication Skills - Principles of Public Speech Making and Social Interaction, Phonetic Transcription and Practical Speech Work", "Study Techniques - Note-taking, Note-making, Summary & Transcoding Techniques", "Basic Research Methods & Term Paper Writing - The Research Report, Documentation, Abbreviations, practical term paper writing"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('GSP 105', 'Natural Science I', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Social Sciences course handbook'),
  ('GSP 111', 'Use of Library & Study Skills', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'first', 2, 'Overview of Library: concepts, history, types and functions. Uses in academic libraries; organization of university library and library users. Library processes and procedures. Acquisition process, Cataloging and classification, LC Scheme, in-House Scheme, DDC. Serials process and circulation processes. Access tools in Library resources: Library catalogues, Indexes, Abstracts, Current contents information in the library. Reference sources: types of reference sources and services. Web resources and online resources. Overview of Databases, Online search strategies for information retrieval. Referencing and citation styles for information reporting. Concept of plagiarism. Learning skills and research skills, ICT skillsets: types of learning and information policies.', '["Overview of Library: concepts, history, types and functions. Uses in academic libraries; organization of university library and library users", "Library processes and procedures. Acquisition process, Cataloging and classification, LC Scheme, in-House Scheme, DDC. Serials process and circulation processes", "Access tools in Library resources: Library catalogues, Indexes, Abstracts, Current contents information", "Reference sources: types of reference sources and services. Web resources and online resources", "Overview of Databases, Online search strategies for information retrieval. Referencing and citation styles for information reporting. Concept of plagiarism", "Learning skills and research skills, ICT skillsets: types of learning and information policies"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('GSP 102', 'The Use of English II', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'second', 2, 'Part A: Basic Grammar: Introduction. The concept of grammar and its place in language teaching and learning. Parts of speech and their functions (treated in detail). Closed and open class items in parts of speech, Nominalization, Grammatical Structures: the phrase, the clause and the sentence. Elementary Clause Analysis, Sentence Types, Elements and Patterns. Agreement (Grammatical agreement, Notional agreement, Proximity agreement) Agreement with the correlatives. Direct and Reported Speech, Error typology identification and correction.

Part B: Varieties of writing. Introduction (The Meaning, Nature and Purpose of Writing, Writing Types or Genres and their Characteristics). The paragraph as the basic unit of an essay (Types, Development of the Paragraph, Methods of Paragraph Development, The thesis statement). Point of view and style in writing. Qualities of a good piece of writing: Form, Diction and Content in writing. The Mechanics of Writing: punctuation, spelling and capitalization.

Part C: Writing Genres - Planning and choosing your theme. Deciding your genre. Choosing and developing your plot. Point of view, setting and characterization. Using the language that works. Essay Writing — Narration, Description, Exposition and Argumentation. Technical Writing: Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes, own story for practice, Computer-linked writing, types, style, language, and process.', '["Part A: Basic Grammar - The concept of grammar, Parts of speech, Grammatical Structures, Sentence Types, Agreement, Direct and Reported Speech, Error typology", "Part B: Varieties of writing - Meaning, Nature and Purpose of Writing, the paragraph as the basic unit of an essay, the thesis statement, Qualities of a good piece of writing, Mechanics of Writing", "Part C: Writing Genres - Planning and choosing your theme, plot, point of view, setting and characterization", "Essay Writing - Narration, Description, Exposition and Argumentation", "Technical Writing - Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('GSP 106', 'Natural Sciences II', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Social Sciences course handbook'),
  ('ECO 102', 'Principles of Economics II', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'second', 2, 'Elementary principles of macroeconomics and microeconomics; National income determination; The circular flow of income; Injections, withdrawals and the multiplier; Income determination; consumption, saving and investment functions; Nature and features of money; The banking system and the supply of money; Money supply and price level; International trade; Exchange rate and comparative advantage; Foreign trade and domestic economy; Economic growth; Elementary notion of economic planning; Introduction to Marxist economic theory.', '["Elementary principles of macroeconomics and microeconomics", "National income determination", "The circular flow of income; Injections, withdrawals and the multiplier", "Income determination; consumption, saving and investment functions", "Nature and features of money", "The banking system and the supply of money", "Money supply and price level", "International trade; Exchange rate and comparative advantage", "Foreign trade and domestic economy", "Economic growth", "Elementary notion of economic planning", "Introduction to Marxist economic theory"]'::jsonb, 'Department of Economics handbook'),
  ('PSY 102', 'Introduction to Psychology II', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'second', 2, 'Sensation and Perception. Mind versus body, learning and memory. Motivation and Emotion. Personality. Assessing individual Differences. Problems of adjustment in behaviour.', '["Sensation and Perception. Mind versus body, learning and memory", "Motivation and Emotion", "Personality. Assessing individual Differences", "Problems of adjustment in behaviour"]'::jsonb, 'Department of Psychology handbook'),
  ('SOC 102', 'Introduction to Sociology II', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Social Sciences course handbook'),
  ('EDU 102', 'Introduction to Education', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '100 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Social Sciences course handbook'),
  ('FSS 201', 'Introduction to Statistical Methods for the Social Sciences I', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Social Sciences course handbook'),
  ('GSP 201', 'Basic Concepts and Theories of Peace and Conflict', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Social Sciences course handbook'),
  ('GSP 207', 'Logic, Philosophy and Human Existence', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Social Sciences course handbook'),
  ('FSS 202', 'Introduction to Statistical Methods for the Social Sciences II', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Social Sciences course handbook'),
  ('GSP 202', 'Issues in Peace and Conflict Resolution Studies', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Social Sciences course handbook'),
  ('GSP 208', 'Nigerian Peoples and Culture', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Social Sciences course handbook'),
  ('CED 341', 'Introduction to the Study of Entrepreneurship', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '300 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Social Sciences course handbook'),
  ('COS 304', 'Computer Application Systems', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '300 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Social Sciences course handbook'),
  ('CED 342', 'Business Development and Management', 'University of Nigeria, Nsukka', 'Faculty of Social Sciences', 'Public Administration and Local Government', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Social Sciences course handbook')
;
