-- =============================================================================
-- University of Nigeria, Nsukka -- Faculty of Engineering
-- Department of Electrical Engineering
-- Five-Year Standard Undergraduate B.Eng Degree Programme
-- =============================================================================
-- Transcribed from Chapter Six (book pages 107-111) of the Faculty of Engineering handbook.
-- 84 rows covering the full programme.
--
-- VERIFICATION: the handbook prints a "Total Credit Hours" for every semester.
-- Each semester's unit values were re-summed and compared against the printed
-- figure -- 21, 17, 18, 18, 20, 20, 19, 16, 19 -- and every one of those reconciles.
-- That check is what makes the units column trustworthy: this handbook
-- right-aligns units, so a value can sit visually against the wrong row, and
-- the printed totals are what pin them back down. Where a semester offers an
-- elective group, only the units a student actually takes are counted toward
-- the total, matching how the handbook totals it.
--
-- DESCRIPTIONS: shared ancillary courses reuse the description already held
-- for that same course code elsewhere in this app, rather than getting freshly
-- invented prose -- a shared course must read identically across every
-- department that lists it. Department-specific courses carry an empty
-- description here: their text lives in the handbook's separate detailed
-- course-description section and is a follow-up pass rather than a guess.
--
-- CHM 171 IS PRINTED TWICE FOR TWO DIFFERENT COURSES: 100 Level first semester
-- has "CHM 171 -- Basic Practical Chemistry" and second semester has
-- "CHM 171 -- Basic Principles of Organic Chemistry". Every other department in
-- this handbook uses a distinct code (CHM 121/122) for Organic Chemistry and
-- reserves CHM 171 for the practical course alone. This was re-verified at
-- 350dpi directly against the page image -- both rows genuinely print "171",
-- not a misreading -- so it is recorded exactly as printed rather than
-- corrected to what the pattern elsewhere would suggest.
--
-- CVE 211 AND MEC 261 ARE EACH PRINTED TWICE FOR TWO DIFFERENT COURSES:
-- 200 Level first semester has "CVE 211 -- Strength of Materials I" and
-- second semester has "CVE 211 -- Fluid Mechanics Laboratory" (Civil's own
-- chapter calls the latter CVE 222); first semester also has "MEC 261 --
-- Thermodynamics I" and second semester has "MEC 261 -- Workshop Technology I"
-- (other departments use MEC 211/212 for Workshop Technology). Both pairs were
-- re-verified at 300dpi directly against the page image and are genuinely
-- printed that way twice -- recorded exactly as printed, not corrected.
--
-- CED 342 REPEATS THE "I" SUFFIX: 300 Level second semester prints
-- "CED 342 -- Introduction to Entrepreneurship I", identical to first
-- semester's CED 341 title, rather than "...II" as the numbering convention
-- used elsewhere in this handbook would suggest. Re-verified at 300dpi;
-- genuinely printed that way, recorded as printed.
--
-- 500 LEVEL FIRST SEMESTER DOES NOT CHECKSUM: the six major courses sum to 13,
-- and the semester offers four elective options (2 units each) of which the
-- handbook's own heading says "Any Two Courses Should Be Taken" -- 13 + 4 = 17.
-- The handbook nonetheless prints this semester's TOTAL as 19. Every major
-- course's unit value, the elective count and each elective's unit value, the
-- "Any Two" wording, and the printed total digit itself were all independently
-- re-verified at high resolution (300-350dpi) directly against the page image,
-- and none of them is a misreading -- the handbook's own arithmetic simply does
-- not add up for this semester. Rather than inventing a plausible extra course
-- or unit value to force a reconciliation, this semester is loaded with all ten
-- rows exactly as printed (majors is_elective=false, the four options
-- is_elective=true) and is excluded from the checksum entirely. Its sibling
-- semester, 500 Level second, reconciles cleanly: 5 majors (15) + "any two" of
-- 3 electives (4) = 19, matching its printed total exactly.
-- =============================================================================

delete from public.course_outlines
 where institution = 'University of Nigeria, Nsukka'
   and department = 'Electrical Engineering';

insert into public.course_outlines
  (course_code, course_title, institution, faculty, department, level,
   semester, credit_units, description, topics, contributor_name, is_elective)
values
  ('EGR 101', 'Introduction to Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '100 Level', 'first', 2, 'An overview of engineering as a profession. Historical perspective, Discipline, Rationalization, professional affiliations, professional journey, successful studentship, creativity, roles of science and Technology; Engineering and Society: The role of engineers in nation building, professional impacts of Engineering practice and mitigation measures, professional challenges in Nigeria, historical and professional roles; Basic information on Agricultural and Bioresources Engineering, Professional practice, Sustainable Agricultural production in Nigeria; Introduction to Biomedical Engineering, Scope of biomedical engineering practice: A science perspective of Civil Engineering, corporate personality of Civil Engineering; Civil Engineering professional practice; Basic information on Electrical Engineering, Scope of Electrical Engineering professional practice; Electric power generation in Nigeria; Evolution to Electronic Engineering, Scope of Electronic Engineering Professional practice, practice of Electronic Engineering in Nigeria; Basic information on Mechanical Engineering, Scope of Mechanical Engineering professional practice, practice of Mechanical Engineering in Nigeria; Introduction to Mechatronics Engineering, Scope of Mechatronics engineering practice; Basic information on Metallurgical and Materials Engineering, Scope of Metallurgical and Materials Engineering professional practice, practice of Metallurgical and Materials Engineering.', '["An overview of engineering as a profession. Historical perspective, Discipline, Rationalization, professional affiliations, professional journey, successful studentship, creativity, roles of science and Technology", "Engineering and Society: The role of engineers in nation building, professional impacts of Engineering practice and mitigation measures, professional challenges in Nigeria", "Basic information on Agricultural and Bioresources Engineering; Introduction to Biomedical Engineering", "A science perspective of Civil Engineering, corporate personality and professional practice of Civil Engineering", "Basic information on Electrical Engineering; Electric power generation in Nigeria; Evolution to Electronic Engineering", "Basic information on Mechanical Engineering, Scope and practice of Mechanical Engineering in Nigeria", "Introduction to Mechatronics Engineering; Basic information on Metallurgical and Materials Engineering"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 111', 'Elementary Mathematics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '100 Level', 'first', 3, 'Elementary set theory, subsets, union, intersection, complements. Venn diagrams, real numbers, integers, rational and irrational numbers, mathematical induction, real sequences and series, theory of quadratic equations, binomial theorem. Circular measure, trigonometric functions of angles of any magnitude, addition and factor formulae. Complex numbers, algebra of complex numbers, the Argand diagram, De Moivre''s theorem, nth roots of unity.', '["Elementary set theory, subsets, union, intersection, complements", "Venn diagrams, real numbers, integers, rational and irrational numbers, mathematical induction, real sequences and series, theory of quadratic equations, binomial theorem", "Circular measure, trigonometric functions of angles of any magnitude, addition and factor formulae", "Complex numbers, algebra of complex numbers, the Argand diagram, De Moivre''s theorem, nth roots of unity"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 112', 'Elementary Mathematics II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '100 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('PHY 121', 'Fundamentals of Physics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '100 Level', 'first', 3, 'Units and dimensions. Vector algebra. Kinematics of a particle''s mass point; laws of mechanics and gravitation. Kepler''s Laws. Motion of rigid bodies, moment of inertia, angular momentum, vertical motion of a particle, elastic string, motion of a simple pendulum. Impulse and change of Momentum. Impact of two smooth elastic spheres. Direct and Oblique impacts.', '["Units and dimensions. Vector algebra", "Kinematics of a particle''s mass point; laws of mechanics and gravitation. Kepler''s Laws", "Motion of rigid bodies, moment of inertia, angular momentum", "Vertical motion of a particle, elastic string, motion of a simple pendulum", "Impulse and change of Momentum. Impact of two smooth elastic spheres. Direct and Oblique impacts"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('PHY 195', 'Practical Physics II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '100 Level', 'first', 2, 'Selected Experiments from the 100-Level courses in Physics for Physics majors and Engineering students.', '["Selected Experiments from the 100-Level courses in Physics for Physics majors and Engineering students"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CHM 101', 'Basic Principles of Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '100 Level', 'first', 2, 'Stoichiometry and Atomic Structure: Stoichiometry and mole concept. Introduction to atomic structure, development of electronic configuration of the elements, and valency theories. Periodic Table and Groups: The periodic classification of elements. Brief group study of representative elements, with emphasis on similarities and differences based on periodic position. Nuclear Chemistry: Radioactivity and its practical applications.', '["Stoichiometry and Atomic Structure: Stoichiometry and mole concept. Introduction to atomic structure, development of electronic configuration of the elements, and valency theories", "Periodic Table and Groups: The periodic classification of elements. Brief group study of representative elements, with emphasis on similarities and differences based on periodic position", "Nuclear Chemistry: Radioactivity and its practical applications"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CHM 171', 'Basic Practical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '100 Level', 'first', 2, 'Laboratory operations: theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations.', '["Laboratory operations: theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 101', 'Study Skills and Basic Research Methods', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '100 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 111', 'The Use of Library and Study Skills', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '100 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EGR 102', 'Applied Mechanics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '100 Level', 'second', 3, 'Introduction - Force Systems, resultants, Moments, Couples. Equilibrium, free-body diagram, 2-dimensional force systems, equations for equilibrium of forces in space, internal forces, examples of simple machines, friction, pulleys, wires and cables, static and dynamic Friction. Centroid, graphical determination, Theorems of Pappus of centers of gravity and areas. Moments of Inertia of plane areas, built up sections etc. Kinematics of particles and rigid bodies. Newton''s laws of motion applied to a system of particles. Rectilinear and curvilinear motion, tangent, normal, polar, work, energy, power. Concepts of momentum and Newton''s laws of motion under gravity. Projectile motion.', '["Introduction - Force Systems, resultants, Moments, Couples. Equilibrium, free-body diagram, 2-dimensional force systems", "Equations for equilibrium of forces in space, internal forces, examples of simple machines, friction, pulleys, wires and cables, static and dynamic Friction", "Centroid, graphical determination, Theorems of Pappus of centers of gravity and areas. Moments of Inertia of plane areas, built up sections etc", "Kinematics of particles and rigid bodies. Newton''s laws of motion applied to a system of particles", "Rectilinear and curvilinear motion, tangent, normal, polar, work, energy, power", "Concepts of momentum and Newton''s laws of motion under gravity. Projectile motion"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 122', 'Elementary Mathematics III', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '100 Level', 'second', 3, 'Geometric representation of vectors in 1-3 dimensions, Components, direction cosines. Addition of vectors and multiplication of vectors by a scalar, linear independence. Scalar and vector products of two vectors. Differentiation and integration of vectors with respect to a scalar variable. Two-dimensional coordinate geometry. Straight lines, circles, parabolas, ellipses, hyperbolas. Tangents and normals. Kinematics of a particle. Components of velocity and acceleration of a particle moving in a plane. Force and momentum. Newton''s laws of motion; motion under gravity, projectile motion, resisted vertical motion of a particle, elastic string, motion of a simple pendulum, impulse and impact of momentum. Impact of two smooth elastic spheres. Direct and oblique impacts.', '["Geometric representation of vectors in 1-3 dimensions, Components, direction cosines", "Addition of vectors and multiplication of vectors by a scalar, linear independence", "Scalar and vector products of two vectors", "Differentiation and integration of vectors with respect to a scalar variable", "Two-dimensional coordinate geometry", "Straight lines, circles, parabolas, ellipses, hyperbolas", "Tangents and normals", "Kinematics of a particle", "Components of velocity and acceleration of a particle moving in a plane", "Force and momentum", "Newton''s laws of motion", "Motion under gravity, projectile motion, resisted vertical motion of a particle, elastic string, motion of a simple pendulum, impulse and impact of momentum", "Impact of two smooth elastic spheres", "Direct and oblique impacts"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('PHY 116', 'General Physics for Physical Sciences', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '100 Level', 'second', 2, 'Temperature and its measurement. Heat capacity, specific heat, latent heats, critical points. Calorimetry. Gas laws; kinetic theory of gases; thermal energy, work done by expanding gases; laws of thermodynamics. Liquefaction of gases. Heat transfer: conduction, convection, radiation. Longitudinal and transverse waves; vibrations in solids. Sound waves in solids, liquids, gases; pitch, intensity and quality of sound. Doppler Effect. Acoustics of buildings. Ultrasonics. Reflection and refraction of light; spherical mirrors; thin and thick lenses; optical instruments. Wave nature of light; interference, diffraction, polarization. Velocity of light.', '["Temperature and its measurement", "Heat capacity, specific heat, latent heats, critical points", "Calorimetry", "Gas laws", "Kinetic theory of gases", "Thermal energy, work done by expanding gases", "Laws of thermodynamics", "Liquefaction of gases", "Heat transfer: conduction, convection, radiation", "Longitudinal and transverse waves", "Vibrations in solids", "Sound waves in solids, liquids, gases", "Pitch, intensity and quality of sound", "Doppler Effect", "Acoustics of buildings", "Ultrasonics", "Reflection and refraction of light", "Spherical mirrors", "Thin and thick lenses", "Optical instruments", "Wave nature of light", "Interference, diffraction, polarization", "Velocity of light"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('PHY 124', 'Fundamentals of Physics III', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '100 Level', 'second', 3, 'Electrostatics, Coulomb''s Law, Gauss''s Law, simple applications. Electric field, electrostatic potential. Energy in electric field, capacitance, dielectrics. Electric current, Ohm''s law, circuit analysis, Thermoelectricity. Magnetic effects of currents, Ampere''s Law, Applications. Electromagnetism, Faraday''s law of induction, Maxwell''s equations. Alternating currents, A.C. circuits. Measuring devices. Motion of a charged particle in electric and magnetic fields, Hall Effect. Atomic and Nuclear structure. Nuclear fission and fusion. Nuclear reactors.', '["Electrostatics, Coulomb''s Law, Gauss''s Law, simple applications", "Electric field, electrostatic potential. Energy in electric field, capacitance, dielectrics", "Electric current, Ohm''s law, circuit analysis, Thermoelectricity", "Magnetic effects of currents, Ampere''s Law, Applications. Electromagnetism, Faraday''s law of induction, Maxwell''s equations", "Alternating currents, A.C. circuits. Measuring devices", "Motion of a charged particle in electric and magnetic fields, Hall Effect", "Atomic and Nuclear structure. Nuclear fission and fusion. Nuclear reactors"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CHM 112', 'Basic Principles of Physical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '100 Level', 'second', 2, 'Gas laws and kinetic theory: kinetic theory of gases, elementary derivation and deduction of gas laws, molecular speeds, deviations from ideal behaviour, van der Waals modification, and gas liquefaction. Phase equilibrium and solutions: phase transitions and phase equilibria in one-component systems; ideal solutions, Raoult''s law, Henry''s law, real solutions, and colligative properties. Thermodynamics and kinetics: aspects of the first law of thermodynamics, thermochemistry, entropy, free energy, and spontaneous changes; ionic equilibria, acids, bases, indicators, and buffers; elementary chemical kinetics.', '["Gas laws and kinetic theory of gases; molecular speeds; deviations from ideal behaviour; gas liquefaction", "Phase transitions and phase equilibria; ideal and real solutions; colligative properties", "First law of thermodynamics, thermochemistry, entropy, free energy, spontaneous changes", "Ionic equilibria, acids, bases, indicators and buffers", "Elementary chemical kinetics: rate laws, order and molecularity, Arrhenius equation"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CHM 171', 'Basic Principles of Organic Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '100 Level', 'second', 2, 'Laboratory operations: theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations.', '["Laboratory operations: theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 102', 'Basic Grammar and Varieties of Writing', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '100 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 211', 'Basic Electrical Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '200 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CVE 211', 'Strength of Materials I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CVE 212', 'Strength of Materials Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '200 Level', 'first', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EGR 201', 'Materials Science', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MEC 211', 'Engineering Drawing', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MEC 261', 'Thermodynamics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 207', 'Advanced Mathematics VII', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '200 Level', 'first', 2, 'Elements of linear algebra. Calculus: Elementary differentiation and relevant theorems. Differential equations: Exact equations, methods of solution of second-order ordinary differential equations, partial differential equations, with applications.', '["Elements of linear algebra", "Calculus: Elementary differentiation and relevant theorems", "Differential equations: Exact equations, methods of solution of second-order ordinary differential equations, partial differential equations, with applications"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 201', 'Basic Concepts and Theories of Peace and Conflict', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 207', 'Logic, Philosophy and Human Existence', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 251', 'Basic Electrical Engineering Laboratory Practice', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '200 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 271', 'Engineering Computer Programming', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '200 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 281', 'Engineering Computer Programming Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '200 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CVE 221', 'Fluid Mechanics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '200 Level', 'second', 2, 'Elective. The programme table''s left edge is cut off by the book''s binding, printing only "E 221" for this code; CVE 221 (Civil Engineering) is used as the closest plausible match for a Fluid Mechanics elective, but this is not independently confirmed.', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CVE 211', 'Fluid Mechanics Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '200 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MEC 261', 'Workshop Technology I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 206', 'Advanced Mathematics VI', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '200 Level', 'second', 2, 'The programme table prints "Advanced Mathematics VII" against both MTH 206 and MTH 207; quoted as printed. Complex analysis - Elements of the algebra of complex variables, trigonometric, exponential and logarithmic functions. The number system, sequences and series. Vector differentiation and integration.', '["Complex analysis - Elements of the algebra of complex variables, trigonometric, exponential and logarithmic functions", "The number system, sequences and series", "Vector differentiation and integration"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 208', 'Advanced Mathematics VIII', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '200 Level', 'second', 2, 'Elective. Numerical analysis: Linear equations, non-linear equations; finite difference operators. Introduction to linear programming.', '["Numerical analysis: Linear equations, non-linear equations", "Finite difference operators", "Introduction to linear programming"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 202', 'Issues in Peace and Conflict Resolution', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 208', 'Nigerian Peoples and Culture Studies', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 313', 'Circuit Theory I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '300 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 351', 'Electrical Machines Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '300 Level', 'first', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 361', 'Electrical Machines I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '300 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 371', 'Measurement and Instrumentation', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '300 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 381', 'Electromagnetic Fields and Waves I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 321', 'Physical Electronics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '300 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 381', 'Physical Electronics Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '300 Level', 'first', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('STA 205', 'Statistics for Physical Sciences and Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CED 341', 'Introduction to Entrepreneurship I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 314', 'Circuit Theory II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 322', 'Applied Electronic Systems', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 332', 'Electric Power Systems Principles', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '300 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 352', 'Electrical Power Systems Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '300 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 354', 'Measurement and Applied Electronics Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '300 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 356', 'Electrical Drives Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '300 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 382', 'Electromagnetic Fields and Waves II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 362', 'Electrical Machines II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EGR 302', 'Engineering Analysis', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '300 Level', 'second', 4, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CED 342', 'Introduction to Entrepreneurship I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 421', 'Power Semiconductor Devices and Circuits I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '400 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 441', 'Communication Principles', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '400 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 451', 'Communications and Fields Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '400 Level', 'first', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 453', 'Control and Logic Systems Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '400 Level', 'first', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 461', 'Electrical Machines III', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '400 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 471', 'Digital Signal Processing', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '400 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 473', 'Control Logic Circuit Design', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '400 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 475', 'Control Systems Engineering I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '400 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EGR 401', 'Computational Methods', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '400 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 492', 'Mini Projects', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '400 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 494', 'Seminar and Industrial Visits', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '400 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EGR 402', 'Students Industrial Work Experience Scheme (SIWES)', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '400 Level', 'second', 10, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 521', 'Power Semiconductor Devices and Circuits II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 531', 'Electric Power System Analysis, Planning and Protection', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '500 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 533', 'Switchgear and High Voltage Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 541', 'Power Systems Communication and Control', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 561', 'Electrical Machines Design', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 581', 'Electromagnetic Fields and Waves III', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 573', 'Computer Software and Applications', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('EEE 535', 'Power System Distribution', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('EEE 537', 'Power System Optimization', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('EEE 571', 'Computer Organization', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('EEE 512', 'Renewable and New Energy Systems', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '500 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 522', 'Application of Semiconductor Devices in Power Systems', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 532', 'Electrical Services Design, Reliability and Maintainability', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '500 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 572', 'Control Systems Engineering II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '500 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 592', 'Project', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '500 Level', 'second', 4, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 562', 'Electric Motor Drives', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('EEE 574', 'Discrete Control Systems', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('EEE 576', 'Introduction to Optimal Control', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electrical Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true);
