-- =============================================================================
-- University of Nigeria, Nsukka -- Faculty of Engineering
-- Department of Electronic Engineering
-- Five-Year Standard Undergraduate B.Eng Degree Programme
-- =============================================================================
-- Transcribed from Chapter Seven (book pages 129-135) of the Faculty of Engineering handbook.
-- 94 rows covering the full programme.
--
-- VERIFICATION: the handbook prints a "Total Credit Hours" for every semester.
-- Each semester's unit values were re-summed and compared against the printed
-- figure -- 20, 17, 19, 18, 22, 21, 22, 15, 16, 19 -- and every one of those reconciles.
-- That check is what makes the units column trustworthy: this handbook
-- right-aligns units, so a value can sit visually against the wrong row, and
-- the printed totals are what pin them back down. Where a semester offers an
-- elective group, only the units a student actually takes are counted toward
-- the total, matching how the handbook totals it.
--
-- DESCRIPTIONS: shared ancillary courses reuse the description already held
-- for that same course code elsewhere in this app, rather than getting freshly
-- invented prose -- a shared course must read identically across every
-- department that lists it. Department-specific courses carry an empty
-- description here: their text lives in the handbook's separate detailed
-- course-description section and is a follow-up pass rather than a guess.
--
-- DEPARTMENT NAME: this handbook chapter's own heading reads "DEPARTMENT OF
-- ELECTRONIC ENGINEERING" (Chapter Seven), matching the ECE course-code
-- prefix used throughout. The current UNN Faculty of Engineering website
-- lists this department as "Electronic and Computer Engineering"; the name
-- stored here follows the handbook chapter itself, consistent with how every
-- other department in this handbook is named after its own chapter heading.
--
-- MTH 121 IS PAIRED WITH "ELEMENTARY MATHEMATICS III" IN FIRST SEMESTER: every
-- other chapter in this handbook uses MTH 121 for Elementary Mathematics II
-- and teaches "III" the following semester (as MTH 122 or MTH 113). This
-- chapter's own First Year table prints MTH 121 = "Elementary Mathematics
-- III" in semester one and MTH 112 = "Elementary Mathematics II" in semester
-- two -- Math III taught before Math II by the chapter's own sequencing.
-- Re-verified directly against the page image at 300dpi; recorded exactly as
-- printed rather than reordered to match the other chapters' convention.
--
-- PHY 107 = 2 UNITS HERE, NOT 3: Civil and Electrical Engineering's chapters
-- both print PHY 107 "Fundamentals of Physics I" as 3 units; this chapter
-- prints it as 2, and the semester's own printed total of 20 only reconciles
-- with 2. Recorded as printed -- a genuine cross-chapter inconsistency, not
-- a transcription error.
--
-- EEE 361's UNIT VALUE IS PHYSICALLY SMUDGED IN THE SOURCE PHOTOGRAPH: at
-- 300 Level first semester, an ink mark obscures the printed digit next to
-- "EEE 361 -- Electrical Machines I". It is stored here as 3 units, the only
-- value consistent with the semester's printed total of 22 (12 units from the
-- five ECE majors + 1 for EEE 351 + 2 for STA 203 + 2 for ECE 371 + 2 for
-- CED 341 leaves exactly 3 for EEE 361), and matching the unit value this
-- same course carries in the Civil and Electrical Engineering chapters.
--
-- FIFTH-YEAR ELECTIVES: second semester's own footnote reads "Two courses
-- from any area(s) of specialization (Communications, Control, Digital and
-- Computer, Opto-electronics, Instrumentation) may be chosen from the
-- elective courses" and the handbook folds that straight into a flat
-- "Electives -- 6" line in its own total (5 majors = 13, + 6 = 19). All
-- elective options legible in the source are stored as is_elective = true;
-- the Instrumentation group's list was cut off after its first entry
-- (ECE 562) by the edge of the photographed page, so only that one option is
-- recorded for that group -- nothing was extrapolated to fill the gap.
-- =============================================================================

delete from public.course_outlines
 where institution = 'University of Nigeria, Nsukka'
   and department = 'Electronic Engineering';

insert into public.course_outlines
  (course_code, course_title, institution, faculty, department, level,
   semester, credit_units, description, topics, contributor_name, is_elective)
values
  ('EGR 101', 'Introduction to Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '100 Level', 'first', 2, 'An overview of engineering as a profession. Historical perspective, Discipline, Rationalization, professional affiliations, professional journey, successful studentship, creativity, roles of science and Technology; Engineering and Society: The role of engineers in nation building, professional impacts of Engineering practice and mitigation measures, professional challenges in Nigeria, historical and professional roles; Basic information on Agricultural and Bioresources Engineering, Professional practice, Sustainable Agricultural production in Nigeria; Introduction to Biomedical Engineering, Scope of biomedical engineering practice: A science perspective of Civil Engineering, corporate personality of Civil Engineering; Civil Engineering professional practice; Basic information on Electrical Engineering, Scope of Electrical Engineering professional practice; Electric power generation in Nigeria; Evolution to Electronic Engineering, Scope of Electronic Engineering Professional practice, practice of Electronic Engineering in Nigeria; Basic information on Mechanical Engineering, Scope of Mechanical Engineering professional practice, practice of Mechanical Engineering in Nigeria; Introduction to Mechatronics Engineering, Scope of Mechatronics engineering practice; Basic information on Metallurgical and Materials Engineering, Scope of Metallurgical and Materials Engineering professional practice, practice of Metallurgical and Materials Engineering.', '["An overview of engineering as a profession. Historical perspective, Discipline, Rationalization, professional affiliations, professional journey, successful studentship, creativity, roles of science and Technology", "Engineering and Society: The role of engineers in nation building, professional impacts of Engineering practice and mitigation measures, professional challenges in Nigeria", "Basic information on Agricultural and Bioresources Engineering; Introduction to Biomedical Engineering", "A science perspective of Civil Engineering, corporate personality and professional practice of Civil Engineering", "Basic information on Electrical Engineering; Electric power generation in Nigeria; Evolution to Electronic Engineering", "Basic information on Mechanical Engineering, Scope and practice of Mechanical Engineering in Nigeria", "Introduction to Mechatronics Engineering; Basic information on Metallurgical and Materials Engineering"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 111', 'Elementary Mathematics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '100 Level', 'first', 3, 'Elementary set theory, subsets, union, intersection, complements. Venn diagrams, real numbers, integers, rational and irrational numbers, mathematical induction, real sequences and series, theory of quadratic equations, binomial theorem. Circular measure, trigonometric functions of angles of any magnitude, addition and factor formulae. Complex numbers, algebra of complex numbers, the Argand diagram, De Moivre''s theorem, nth roots of unity.', '["Elementary set theory, subsets, union, intersection, complements", "Venn diagrams, real numbers, integers, rational and irrational numbers, mathematical induction, real sequences and series, theory of quadratic equations, binomial theorem", "Circular measure, trigonometric functions of angles of any magnitude, addition and factor formulae", "Complex numbers, algebra of complex numbers, the Argand diagram, De Moivre''s theorem, nth roots of unity"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 121', 'Elementary Mathematics III', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '100 Level', 'first', 3, 'Functions of a real variable, graphs, limits and continuity. The derivative as limit of rate of change. Techniques of differentiation. Curve sketching, integration as an inverse of differentiation. Methods of integration, definite integrals. Application of integration to areas and volumes.', '["Functions of a real variable, graphs, limits and continuity", "The derivative as limit of rate of change", "Techniques of differentiation", "Curve sketching, integration as an inverse of differentiation", "Methods of integration, definite integrals", "Application of integration to areas and volumes"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CHM 101', 'Basic Principles of Chemistry I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '100 Level', 'first', 2, 'Stoichiometry and Atomic Structure: Stoichiometry and mole concept. Introduction to atomic structure, development of electronic configuration of the elements, and valency theories. Periodic Table and Groups: The periodic classification of elements. Brief group study of representative elements, with emphasis on similarities and differences based on periodic position. Nuclear Chemistry: Radioactivity and its practical applications.', '["Stoichiometry and Atomic Structure: Stoichiometry and mole concept. Introduction to atomic structure, development of electronic configuration of the elements, and valency theories", "Periodic Table and Groups: The periodic classification of elements. Brief group study of representative elements, with emphasis on similarities and differences based on periodic position", "Nuclear Chemistry: Radioactivity and its practical applications"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CHM 171', 'Basic Practical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '100 Level', 'first', 2, 'Laboratory operations: theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations.', '["Laboratory operations: theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('PHY 107', 'Fundamentals of Physics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '100 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('PHY 192', 'Practical Physics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '100 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 101', 'The Use of English I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '100 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 111', 'Use of Library Studies', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '100 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EGR 102', 'Applied Mechanics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '100 Level', 'second', 3, 'Introduction - Force Systems, resultants, Moments, Couples. Equilibrium, free-body diagram, 2-dimensional force systems, equations for equilibrium of forces in space, internal forces, examples of simple machines, friction, pulleys, wires and cables, static and dynamic Friction. Centroid, graphical determination, Theorems of Pappus of centers of gravity and areas. Moments of Inertia of plane areas, built up sections etc. Kinematics of particles and rigid bodies. Newton''s laws of motion applied to a system of particles. Rectilinear and curvilinear motion, tangent, normal, polar, work, energy, power. Concepts of momentum and Newton''s laws of motion under gravity. Projectile motion.', '["Introduction - Force Systems, resultants, Moments, Couples. Equilibrium, free-body diagram, 2-dimensional force systems", "Equations for equilibrium of forces in space, internal forces, examples of simple machines, friction, pulleys, wires and cables, static and dynamic Friction", "Centroid, graphical determination, Theorems of Pappus of centers of gravity and areas. Moments of Inertia of plane areas, built up sections etc", "Kinematics of particles and rigid bodies. Newton''s laws of motion applied to a system of particles", "Rectilinear and curvilinear motion, tangent, normal, polar, work, energy, power", "Concepts of momentum and Newton''s laws of motion under gravity. Projectile motion"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 112', 'Elementary Mathematics II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '100 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CHM 112', 'Basic Principles of Chemistry II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '100 Level', 'second', 2, 'Gas laws and kinetic theory: kinetic theory of gases, elementary derivation and deduction of gas laws, molecular speeds, deviations from ideal behaviour, van der Waals modification, and gas liquefaction. Phase equilibrium and solutions: phase transitions and phase equilibria in one-component systems; ideal solutions, Raoult''s law, Henry''s law, real solutions, and colligative properties. Thermodynamics and kinetics: aspects of the first law of thermodynamics, thermochemistry, entropy, free energy, and spontaneous changes; ionic equilibria, acids, bases, indicators, and buffers; elementary chemical kinetics.', '["Gas laws and kinetic theory of gases; molecular speeds; deviations from ideal behaviour; gas liquefaction", "Phase transitions and phase equilibria; ideal and real solutions; colligative properties", "First law of thermodynamics, thermochemistry, entropy, free energy, spontaneous changes", "Ionic equilibria, acids, bases, indicators and buffers", "Elementary chemical kinetics: rate laws, order and molecularity, Arrhenius equation"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CHM 122', 'Basic Principles of Chemistry III', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '100 Level', 'second', 2, 'Structure and classification: historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, homologous series, elemental analysis, molecular formulas, and structural isomerism. Bonding and reactivity: isolation and purification methods, functional group concepts, resonance, and aromaticity. Functional groups: saturated and unsaturated hydrocarbons, cyclic hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, and aromatic compounds. Stereochemistry and lipids: introduction to oils, fats, and stereoisomerism.', '["Historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, structural isomerism", "Isolation and purification methods; functional group concepts; resonance and aromaticity", "Saturated and unsaturated hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, aromatic compounds", "Introduction to oils, fats, and stereoisomerism"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('PHY 105', 'Gen. Physics for Physical Sciences II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '100 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('PHY 109', 'Fundamentals of Physics III', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '100 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 102', 'The Use of English II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '100 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EGR 201', 'Materials Science I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EGR 203', 'Materials Science Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '200 Level', 'first', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CVE 211', 'Strength of Materials', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CVE 213', 'Strength of Materials Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '200 Level', 'first', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 211', 'Basic Electrical Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '200 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MEC 211', 'Engineering Drawing I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MEC 261', 'Engineering Thermodynamics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 206', 'Advanced Mathematics VI', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '200 Level', 'first', 2, 'The programme table prints "Advanced Mathematics VII" against both MTH 206 and MTH 207; quoted as printed. Complex analysis - Elements of the algebra of complex variables, trigonometric, exponential and logarithmic functions. The number system, sequences and series. Vector differentiation and integration.', '["Complex analysis - Elements of the algebra of complex variables, trigonometric, exponential and logarithmic functions", "The number system, sequences and series", "Vector differentiation and integration"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 201', 'Basic Concepts & Theories of Peace & Conflicts', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 207', 'Humanities I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 272', 'Engineering Computer Programming', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '200 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 262', 'Engineering Computer Programming Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '200 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CVE 222', 'Fluid Mechanics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CVE 224', 'Fluid Mechanics Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '200 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MEC 212', 'Workshop Technology I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 252', 'Basic Electrical Engineering Laboratory/Practice', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '200 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 208', 'Advanced Mathematics VIII', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '200 Level', 'second', 2, 'Elective. Numerical analysis: Linear equations, non-linear equations; finite difference operators. Introduction to linear programming.', '["Numerical analysis: Linear equations, non-linear equations", "Finite difference operators", "Introduction to linear programming"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 207', 'Advanced Mathematics VII', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '200 Level', 'second', 2, 'Elements of linear algebra. Calculus: Elementary differentiation and relevant theorems. Differential equations: Exact equations, methods of solution of second-order ordinary differential equations, partial differential equations, with applications.', '["Elements of linear algebra", "Calculus: Elementary differentiation and relevant theorems", "Differential equations: Exact equations, methods of solution of second-order ordinary differential equations, partial differential equations, with applications"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 202', 'Issues in Peace & Conflict Resolution Studies', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 208', 'Humanities II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 311', 'Circuit Theory I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '300 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 321', 'Physical Electronics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '300 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 331', 'Electromagnetic Fields and Waves I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 361', 'Measurements and Instrumentation', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '300 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 363', 'Physical Electronics Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '300 Level', 'first', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 351', 'Electrical Machines Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '300 Level', 'first', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 361', 'Electrical Machines I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '300 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('STA 203', 'Statistics For Physical Sciences and Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '300 Level', 'first', 2, 'Initial steps in planning of biological experiments. Methods of data collection, presentation and analysis. Measures of central tendency and dispersion. Frequency distributions. Elementary probability. Discrete and continuous distributions: Binomial, Poisson, Normal and exponential distributions. Interval estimation.', '["Initial steps in planning of biological experiments", "Methods of data collection, presentation and analysis", "Measures of central tendency and dispersion", "Frequency distributions", "Elementary probability", "Discrete and continuous distributions: Binomial, Poisson, Normal and exponential distributions", "Interval estimation"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 371', 'System Programming', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CED 341', 'Introduction to Entrepreneurship', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 312', 'Circuit Theory II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '300 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 322', 'Applied Electronics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '300 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 332', 'Electromagnetic Fields and Waves II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '300 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 362', 'Applied Electronics Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '300 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 364', 'Measurements and Instrumentation Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '300 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 332', 'Electrical Power Systems Principles', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '300 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 352', 'Electrical Power Systems Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '300 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EGR 302', 'Engineering Analysis', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '300 Level', 'second', 4, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CED 342', 'Entrepreneurship', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 421', 'Applied Electronics II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '400 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 441', 'Communication Principles', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '400 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 451', 'Control Theory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '400 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 471', 'Digital Electronics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '400 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 473', 'Digital Logic Theory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '400 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 461', 'Communication & Fields Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '400 Level', 'first', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 463', 'Control Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '400 Level', 'first', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 465', 'Applied Electronics and Digital Logic Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '400 Level', 'first', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 443', 'Data Communication & Networking Fundamentals', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '400 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EGR 401', 'Computational Methods', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '400 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 482', 'Seminars', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '400 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 494', 'Technical Writing', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '400 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EGR 402', 'Students Industrial Work Experience Scheme (SIWES)', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '400 Level', 'second', 10, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 511', 'Digital Systems Design', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 521', 'Industrial Electronics Design', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 541', 'Communication Systems', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 551', 'Control Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 571', 'Microprocessing Systems', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 573', 'Software Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 512', 'Reliability Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 524', 'Solid State Electronics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 542', 'Telecommunication Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 574', 'Digital Signal Processing', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 592', 'Project', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'second', 4, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 540', 'Introduction to Radar and Navigation Systems', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('ECE 544', 'Microwave Communication System Design', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('ECE 546', 'Communications Networks', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('ECE 548', 'Television and Radio', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('ECE 549', 'Electroacoustics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('ECE 552', 'Advance Control Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('ECE 554', 'Process Control', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('ECE 556', 'Linear Systems Theory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('ECE 572', 'Computer Systems Design', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('ECE 576', 'Microprocessor System Design', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('ECE 578', 'Artificial Intelligence And Robotics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('ECE 570', 'Database Management Systems', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('ECE 526', 'Optical Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('ECE 528', 'Medical Electronics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('ECE 562', 'Automation', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Electronic Engineering', '500 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', true);
