-- =============================================================================
-- University of Nigeria, Nsukka - Faculty of Science
-- Pure and Industrial Chemistry
-- Course outlines transcribed from the departmental course handbook.
-- =============================================================================
-- Run in the Supabase SQL Editor. Safe to run more than once: existing rows
-- for these courses are removed first, so it updates rather than duplicates.
--
-- NOTE ON SEMESTERS: the handbook does not state which semester each course
-- runs in. The values below follow the usual Nigerian convention that an odd
-- final digit is first semester and an even one is second. Correct any that
-- differ at UNN by editing the semester column in the Table Editor.
--
-- NOTE ON DUAL CODES: the handbook lists two courses under a pair of codes
-- (CHM 403 / CHM 423 and CHM 422 / CHM 424). Each is stored once under the
-- first code, with the alternative noted in its description. CHM 482 / 483
-- are Colour Chemistry I and II and are stored as two separate courses; the
-- handbook gives them a shared description.
-- =============================================================================

delete from public.course_outlines
 where institution = 'University of Nigeria, Nsukka'
   and department = 'Pure and Industrial Chemistry';

insert into public.course_outlines
  (course_code, course_title, institution, faculty, department, level,
   semester, credit_units, description, topics, contributor_name)
values
  ('CHM 101', 'Basic Principles I of Inorganic Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '100 Level', 'first', 2, 'Stoichiometry and Atomic Structure: Stoichiometry and mole concept. Introduction to atomic structure, development of electronic configuration of the elements, and valency theories. Periodic Table and Groups: The periodic classification of elements. Brief group study of representative elements, with emphasis on similarities and differences based on periodic position. Nuclear Chemistry: Radioactivity and its practical applications.', '["Stoichiometry and Atomic Structure: Stoichiometry and mole concept. Introduction to atomic structure, development of electronic configuration of the elements, and valency theories", "Periodic Table and Groups: The periodic classification of elements. Brief group study of representative elements, with emphasis on similarities and differences based on periodic position", "Nuclear Chemistry: Radioactivity and its practical applications"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 112', 'Basic Principles of Physical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '100 Level', 'second', 2, 'Gas Laws and Kinetic Theory: Kinetic theory of gases, elementary derivation and deduction of gas laws, molecular speeds, deviations from ideal behaviour, van der Waals modification, and gas liquefaction. Phase Equilibrium and Solutions: Phase transitions and phase equilibria in one-component systems. Ideal solutions, Raoult''s law, Henry''s law, real solutions, and colligative properties -- vapour pressure lowering, boiling point elevation, freezing point lowering, osmotic pressure. Thermodynamics and Kinetics: Aspects of the first law of thermodynamics, thermochemistry, entropy, free energy, and spontaneous changes. Ionic equilibria, acids, bases, indicators, and buffers. Elementary chemical kinetics, factors affecting reaction rates, rate laws, order and molecularity, zero and first order reactions, Arrhenius equation, and collision and transition state theories.', '["Gas Laws and Kinetic Theory: Kinetic theory of gases, elementary derivation and deduction of gas laws, molecular speeds, deviations from ideal behaviour, van der Waals modification, and gas liquefaction", "Phase Equilibrium and Solutions: Phase transitions and phase equilibria in one-component systems. Ideal solutions, Raoult''s law, Henry''s law, real solutions, and colligative properties -- vapour pressure lowering, boiling point elevation, freezing point lowering, osmotic pressure", "Thermodynamics and Kinetics: Aspects of the first law of thermodynamics, thermochemistry, entropy, free energy, and spontaneous changes. Ionic equilibria, acids, bases, indicators, and buffers. Elementary chemical kinetics, factors affecting reaction rates, rate laws, order and molecularity, zero and first order reactions, Arrhenius equation, and collision and transition state theories"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 122', 'Basic Principles of Organic Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '100 Level', 'second', 2, 'Structure and Classification: Historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, homologous series, elemental analysis, molecular formulas, and structural isomerism. Bonding and Reactivity: Isolation and purification methods, functional group concepts, resonance, and aromaticity. Electronic theory in organic chemistry. Functional Groups: Brief study of saturated and unsaturated hydrocarbons, cyclic hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, and aromatic compounds. Comparison of phenols and aryl halides. Stereochemistry and Lipids: Introduction to oils, fats, and stereoisomerism.', '["Structure and Classification: Historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, homologous series, elemental analysis, molecular formulas, and structural isomerism", "Bonding and Reactivity: Isolation and purification methods, functional group concepts, resonance, and aromaticity. Electronic theory in organic chemistry", "Functional Groups: Brief study of saturated and unsaturated hydrocarbons, cyclic hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, and aromatic compounds. Comparison of phenols and aryl halides", "Stereochemistry and Lipids: Introduction to oils, fats, and stereoisomerism"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 152', 'Introduction to Industrial Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '100 Level', 'second', 2, 'Chemical Process Industry: Major characteristics and scale of operations in the chemical process industry, major sectors, producing countries, and processing raw materials into end products. Calculations and Energy: Stoichiometry, material and energy balance fundamentals, energy sources, types, and utilization. Environment: Environmental pollution profiles and control strategies for major chemical industries.', '["Chemical Process Industry: Major characteristics and scale of operations in the chemical process industry, major sectors, producing countries, and processing raw materials into end products", "Calculations and Energy: Stoichiometry, material and energy balance fundamentals, energy sources, types, and utilization", "Environment: Environmental pollution profiles and control strategies for major chemical industries"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 171', 'Basic Practical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '100 Level', 'first', 2, 'Laboratory Operations: Theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations.', '["Laboratory Operations: Theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 201', 'General Inorganic Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '200 Level', 'first', 2, 'Periodic Trends: Ionization potential, electron affinity, and electronegativity. Chemical Bonding: Electrostatic and non-electrostatic valence forces, non-valence cohesive forces. Coordination Compounds: Introduction to complexes, focusing on colour, magnetic properties, and practical applications.

Prerequisite: CHM 101, or a pass in Chemistry at H.S.C. / G.C.E. A-Level', '["Periodic Trends: Ionization potential, electron affinity, and electronegativity", "Chemical Bonding: Electrostatic and non-electrostatic valence forces, non-valence cohesive forces", "Coordination Compounds: Introduction to complexes, focusing on colour, magnetic properties, and practical applications"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 211', 'General Physical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '200 Level', 'first', 2, 'Gases and Thermodynamics: Molecular collisions in gases, virial equation, critical phenomena, and reduced properties. Chemical thermodynamics, detailed treatment of the first law of thermodynamics, and the Carnot cycle. Chemical Kinetics: Integrated rate equations for second and third order reactions, reaction mechanisms, rate laws, and the effect of temperature on reaction rates.

Prerequisite: CHM 112', '["Gases and Thermodynamics: Molecular collisions in gases, virial equation, critical phenomena, and reduced properties. Chemical thermodynamics, detailed treatment of the first law of thermodynamics, and the Carnot cycle", "Chemical Kinetics: Integrated rate equations for second and third order reactions, reaction mechanisms, rate laws, and the effect of temperature on reaction rates"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 324', 'Organic Chemistry III', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '300 Level', 'second', 2, 'Polyfunctional Compounds: Study of polyfunctional organic compounds selected from dicarboxylic acids, dicarbonyl compounds, keto- and hydroxy-acids, and $\alpha,\beta$-unsaturated carbonyl compounds, including addition reactions. Biomolecules and Heterocycles: Amino acids and proteins. Heterocyclic compounds containing one heteroatom.

Prerequisite: CHM 221 and CHM 222', '["Polyfunctional Compounds: Study of polyfunctional organic compounds selected from dicarboxylic acids, dicarbonyl compounds, keto- and hydroxy-acids, and $\\alpha,\\beta$-unsaturated carbonyl compounds, including addition reactions", "Biomolecules and Heterocycles: Amino acids and proteins. Heterocyclic compounds containing one heteroatom"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 352', 'Chemical Process Technology I', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '300 Level', 'second', 2, 'Process Flow and Fluid Transport: Calculations, block diagrams, flowsheets, material and energy balances for industrial processes, process selection, and development studies. Pressure loss in pipes, fluid transport and measurement, pumps, compressors, and agitation. Heat Transfer and Operations: Heat transfer via conduction, convection, and radiation; heat exchanger types. Operations including humidification, drying, and single and multiple-effect evaporation.

Prerequisite: CHM 251', '["Process Flow and Fluid Transport: Calculations, block diagrams, flowsheets, material and energy balances for industrial processes, process selection, and development studies. Pressure loss in pipes, fluid transport and measurement, pumps, compressors, and agitation", "Heat Transfer and Operations: Heat transfer via conduction, convection, and radiation; heat exchanger types. Operations including humidification, drying, and single and multiple-effect evaporation"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 371', 'Practical Inorganic Chemistry II', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '300 Level', 'first', 2, 'Analytical Methods: Quantitative analysis of ores, alloys, and other materials using ion-exchange chromatography and solvent extraction. Coordination Complexes: Characteristics of complexes formed between transition metals and organic ligands.', '["Analytical Methods: Quantitative analysis of ores, alloys, and other materials using ion-exchange chromatography and solvent extraction", "Coordination Complexes: Characteristics of complexes formed between transition metals and organic ligands"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 372', 'Practical Physical Chemistry II', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '300 Level', 'second', 2, 'Experiments: Selected experiments in electrochemistry, reaction kinetics, phase equilibria, calorimetry, colorimetry, potentiometry, refractive index measurements, and molecular refractivity. Materials and Heat Transfer: Adsorption studies on activated carbons, heat transfer coefficients in condensers, batch sedimentation, and sieve analysis.', '["Experiments: Selected experiments in electrochemistry, reaction kinetics, phase equilibria, calorimetry, colorimetry, potentiometry, refractive index measurements, and molecular refractivity", "Materials and Heat Transfer: Adsorption studies on activated carbons, heat transfer coefficients in condensers, batch sedimentation, and sieve analysis"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 373', 'Practical Organic Chemistry II', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '300 Level', 'first', 2, 'Synthesis and Analysis: Multistage organic synthesis, qualitative and quantitative analysis of organic mixtures and compounds.', '["Synthesis and Analysis: Multistage organic synthesis, qualitative and quantitative analysis of organic mixtures and compounds"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 374', 'Applied Spectroscopy', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '300 Level', 'second', 2, 'Instrumentation and Theory: Introduction to principles and practical operations of Infrared (IR), Ultraviolet-Visible (UV-Vis), Nuclear Magnetic Resonance (NMR), and Mass Spectrometry (MS).', '["Instrumentation and Theory: Introduction to principles and practical operations of Infrared (IR), Ultraviolet-Visible (UV-Vis), Nuclear Magnetic Resonance (NMR), and Mass Spectrometry (MS)"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 381', 'Chemical Industry and the Environment', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '300 Level', 'first', 2, 'Pollution and Waste: Elementary atmospheric cycles, pollution source types, domestic waste composition, waste disposal, and resource recovery from waste materials. Industrial Impact and Safety: Manufacturing by-product pollution, environmental impact of chemical products such as DDT, detergents, plastics and antibiotics, water treatment chemistry and analysis, detection and monitoring of toxic agents using instrumentation, and chemical industry safety protocols.', '["Pollution and Waste: Elementary atmospheric cycles, pollution source types, domestic waste composition, waste disposal, and resource recovery from waste materials", "Industrial Impact and Safety: Manufacturing by-product pollution, environmental impact of chemical products such as DDT, detergents, plastics and antibiotics, water treatment chemistry and analysis, detection and monitoring of toxic agents using instrumentation, and chemical industry safety protocols"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 382', 'Polymer Chemistry I', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '300 Level', 'second', 2, 'Polymer Fundamentals: Classification of polymers, addition and condensation polymerization reactions, and polymerization practice. Molecular weight distribution and measurement methods. Properties and Structure: Bonding in polymers, solution properties, bulk properties of amorphous and crystalline polymers, rheology, mechanical, thermal, electrical, chemical, and optical properties. Structure-property relationships, survey of important commercial polymers, and polymer testing methods.', '["Polymer Fundamentals: Classification of polymers, addition and condensation polymerization reactions, and polymerization practice. Molecular weight distribution and measurement methods", "Properties and Structure: Bonding in polymers, solution properties, bulk properties of amorphous and crystalline polymers, rheology, mechanical, thermal, electrical, chemical, and optical properties. Structure-property relationships, survey of important commercial polymers, and polymer testing methods"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 401', 'Advanced Inorganic Chemistry I', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Organometallics: Organometallic compounds -- preparation, properties, and applications of organometallic compounds of alkali, alkali earth, and non-benzenoid metal complexes.

Prerequisite: CHM 301 and CHM 302', '["Organometallics: Organometallic compounds -- preparation, properties, and applications of organometallic compounds of alkali, alkali earth, and non-benzenoid metal complexes"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 402', 'Advanced Inorganic Chemistry II', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'second', 2, 'Coordination Chemistry: Coordination chemistry, bonding theories, electronic spectra, magnetic properties, isomerism, formation and stability constants of transition metal complexes, and complexation kinetics and mechanisms. Inorganic Families: Metal carbonyls -- preparation, reactions, structure, bonding; carboxylate ions, carbonyl hydrides, halides, lanthanides, actinides, and boron hydrides. Non-Aqueous Solvents: Non-aqueous solvents, solvent classification, solute-solvent interactions, oxyhalide solvents, protonic solvents, liquid halides, and fused salts.

Prerequisite: CHM 301 and CHM 302', '["Coordination Chemistry: Coordination chemistry, bonding theories, electronic spectra, magnetic properties, isomerism, formation and stability constants of transition metal complexes, and complexation kinetics and mechanisms", "Inorganic Families: Metal carbonyls -- preparation, reactions, structure, bonding; carboxylate ions, carbonyl hydrides, halides, lanthanides, actinides, and boron hydrides", "Non-Aqueous Solvents: Non-aqueous solvents, solvent classification, solute-solvent interactions, oxyhalide solvents, protonic solvents, liquid halides, and fused salts"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 403', 'Modern Synthetic Methods in Organic Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Synthetic Reactions: Comprehensive study of modern organic synthesis applications -- reduction, oxidation, halogenation, alkylation, acylation of active methylene compounds, and alkylation of aromatic systems. Named Reactions: Michael, Claisen-Schmidt, Knoevenagel, Mannich, Perkin, Stobbe, Darzens, and Wittig reactions. Synthesis of organometallic compounds. Note: also listed in the handbook as CHM 423.

Prerequisite: CHM 321 and CHM 322', '["Synthetic Reactions: Comprehensive study of modern organic synthesis applications -- reduction, oxidation, halogenation, alkylation, acylation of active methylene compounds, and alkylation of aromatic systems", "Named Reactions: Michael, Claisen-Schmidt, Knoevenagel, Mannich, Perkin, Stobbe, Darzens, and Wittig reactions. Synthesis of organometallic compounds", "Note: also listed in the handbook as CHM 423"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 411', 'Advanced Physical Chemistry I', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Statistical Thermodynamics: Microstates, randomness, Boltzmann statistics, partition functions, and relationships to thermodynamic quantities $E$, $H$, $G$ and $S$. Heat capacity of gases, liquids, and solids; calculation of equilibrium constants. Introduction to Fermi-Dirac and Bose-Einstein statistics. Electrochemistry: Detailed treatment of Debye-Huckel theory and the Debye-Huckel-Onsager equation.

Prerequisite: CHM 311', '["Statistical Thermodynamics: Microstates, randomness, Boltzmann statistics, partition functions, and relationships to thermodynamic quantities $E$, $H$, $G$ and $S$. Heat capacity of gases, liquids, and solids; calculation of equilibrium constants. Introduction to Fermi-Dirac and Bose-Einstein statistics", "Electrochemistry: Detailed treatment of Debye-Huckel theory and the Debye-Huckel-Onsager equation"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 412', 'Advanced Physical Chemistry II', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'second', 2, 'Quantum Mechanics and Spectroscopy: Approximation methods, self-consistent field theory of many-electron atoms, hybridization theory of resonance, quantum mechanics of molecules -- the $\mathrm{H_2^+}$ ion. Molecular Orbital and Valence Bond theories. Light Interaction: Light-matter interactions, frequency, shape, and intensity of absorption bands across microwave, UV-Visible, and Raman spectroscopy. Chemical Kinetics: Theories of reaction rates -- collision theory and absolute reaction rate theory.

Prerequisite: CHM 312', '["Quantum Mechanics and Spectroscopy: Approximation methods, self-consistent field theory of many-electron atoms, hybridization theory of resonance, quantum mechanics of molecules -- the $\\mathrm{H_2^+}$ ion. Molecular Orbital and Valence Bond theories", "Light Interaction: Light-matter interactions, frequency, shape, and intensity of absorption bands across microwave, UV-Visible, and Raman spectroscopy", "Chemical Kinetics: Theories of reaction rates -- collision theory and absolute reaction rate theory"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 421', 'Advanced Organic Chemistry I', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Stereochemistry and Mechanisms: Stereochemistry of cyclic compounds, allenes, and spiranes; optical activity of diphenyls; conformational analysis. Neighbouring Group Participation (NGP), reactions in acyclic, cyclic and fused systems, molecular rearrangements, and reactive intermediates -- carbenes, nitrenes, benzynes. Spectroscopic Identification: Application of UV, IR, NMR, and Mass spectra in structural elucidation.

Prerequisite: CHM 321 and CHM 322', '["Stereochemistry and Mechanisms: Stereochemistry of cyclic compounds, allenes, and spiranes; optical activity of diphenyls; conformational analysis. Neighbouring Group Participation (NGP), reactions in acyclic, cyclic and fused systems, molecular rearrangements, and reactive intermediates -- carbenes, nitrenes, benzynes", "Spectroscopic Identification: Application of UV, IR, NMR, and Mass spectra in structural elucidation"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 422', 'Chemistry of Natural Products', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'second', 2, 'Natural Products Chemistry: General methods of isolation, purification, structural determination, and synthesis of terpenoids, steroids, alkaloids, lipids, antibiotics, flavonoids, prostaglandins, and chlorophyll. Heterocycles and Applications: Heterocyclic compounds with multiple heteroatoms, natural products of pharmaceutical importance, natural dyes, vitamins, and drugs. Note: also listed in the handbook as CHM 424.

Prerequisite: CHM 321 and CHM 322', '["Natural Products Chemistry: General methods of isolation, purification, structural determination, and synthesis of terpenoids, steroids, alkaloids, lipids, antibiotics, flavonoids, prostaglandins, and chlorophyll", "Heterocycles and Applications: Heterocyclic compounds with multiple heteroatoms, natural products of pharmaceutical importance, natural dyes, vitamins, and drugs", "Note: also listed in the handbook as CHM 424"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 431', 'Modern Analytic Techniques', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Spectrophotometry: Principles and applications of colorimetry, spectrophotometry, and the Beer-Lambert law for multicomponent solution mixtures. Analytical Instrumentation: Fluorescence methods, chromatographic theory and techniques, and flame methods -- Atomic Absorption Spectrometry and Flame Photometry.

Prerequisite: CHM 231', '["Spectrophotometry: Principles and applications of colorimetry, spectrophotometry, and the Beer-Lambert law for multicomponent solution mixtures", "Analytical Instrumentation: Fluorescence methods, chromatographic theory and techniques, and flame methods -- Atomic Absorption Spectrometry and Flame Photometry"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 451', 'Chemical Process Technique II', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Reactor Design: Chemical reaction theory, main reactor types and application fields, batch reactor data interpretation, single ideal reactor design, and multiple reaction design. Operational Variables: Temperature and pressure effects, heterogeneous reactors, fluidized bed reactors, reactor selection, similarity principles, scale-up methods, solid diffusion, and interphase mass transfer.

Prerequisite: CHM 351', '["Reactor Design: Chemical reaction theory, main reactor types and application fields, batch reactor data interpretation, single ideal reactor design, and multiple reaction design", "Operational Variables: Temperature and pressure effects, heterogeneous reactors, fluidized bed reactors, reactor selection, similarity principles, scale-up methods, solid diffusion, and interphase mass transfer"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 452', 'Chemical Process Technology III', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'second', 2, 'Unit Operations: Fluid transportation, size reduction, mixing, filtration, centrifugation, gas absorption, distillation, adsorption, ion-exchange, leaching, and liquid-liquid extraction. Process Dynamics: Objectives of process control loops, measuring devices, controllers, final control elements, computer network analysis, and process optimization.

Prerequisite: CHM 352', '["Unit Operations: Fluid transportation, size reduction, mixing, filtration, centrifugation, gas absorption, distillation, adsorption, ion-exchange, leaching, and liquid-liquid extraction", "Process Dynamics: Objectives of process control loops, measuring devices, controllers, final control elements, computer network analysis, and process optimization"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 454', 'Polymer Chemistry and Technology', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'second', 2, 'Compounding and Processing: Role of plasticizers, fillers, colorants, photo and heat stabilizers, and flame retardants. Polymer fabrication -- injection, extrusion, compression, and transfer molding; processing effects on structure and performance. Coatings and Paints: Paint technology -- paint types, formulation, manufacture, testing, components such as binders, pigments, solvents and additives, substrates, application methods, durability, film defects, and remedies.

Prerequisite: CHM 382', '["Compounding and Processing: Role of plasticizers, fillers, colorants, photo and heat stabilizers, and flame retardants. Polymer fabrication -- injection, extrusion, compression, and transfer molding; processing effects on structure and performance", "Coatings and Paints: Paint technology -- paint types, formulation, manufacture, testing, components such as binders, pigments, solvents and additives, substrates, application methods, durability, film defects, and remedies"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 461', 'Seminar', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Presentation of a paper on an approved topic at a departmental colloquium. Assessed on student presentation and understanding of underlying chemical principles.', '["Presentation of a paper on an approved topic at a departmental colloquium", "Assessed on student presentation and understanding of underlying chemical principles"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 481', 'Chemistry of Petroleum and Coal Products', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Fossil Fuels: Origin, composition, and classification of coal, petroleum, and natural gas. Coal carbonization, liquefaction, gasification, and chemical by-products. Refining: Petroleum refining, natural gas processing, and petrochemical raw materials.

Prerequisite: CHM 381', '["Fossil Fuels: Origin, composition, and classification of coal, petroleum, and natural gas. Coal carbonization, liquefaction, gasification, and chemical by-products", "Refining: Petroleum refining, natural gas processing, and petrochemical raw materials"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 482', 'Colour Chemistry and Technology I', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'second', 2, 'Dyes and Pigments: Relationship between colour and chemical structure, colour measurement, chemistry, classification and manufacture of dyes and pigments. Dyeing and Applications: Dyeing natural and synthetic fibres, reactive dyes, local dye extraction, food, drug and cosmetic colorants, photography dyes, paper dyes, fastness properties, photometric quality control, and coloration industry operations.', '["Dyes and Pigments: Relationship between colour and chemical structure, colour measurement, chemistry, classification and manufacture of dyes and pigments", "Dyeing and Applications: Dyeing natural and synthetic fibres, reactive dyes, local dye extraction, food, drug and cosmetic colorants, photography dyes, paper dyes, fastness properties, photometric quality control, and coloration industry operations"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 483', 'Colour Chemistry and Technology II', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Dyes and Pigments: Relationship between colour and chemical structure, colour measurement, chemistry, classification and manufacture of dyes and pigments. Dyeing and Applications: Dyeing natural and synthetic fibres, reactive dyes, local dye extraction, food, drug and cosmetic colorants, photography dyes, paper dyes, fastness properties, photometric quality control, and coloration industry operations.

Prerequisite: CHM 482', '["Dyes and Pigments: Relationship between colour and chemical structure, colour measurement, chemistry, classification and manufacture of dyes and pigments", "Dyeing and Applications: Dyeing natural and synthetic fibres, reactive dyes, local dye extraction, food, drug and cosmetic colorants, photography dyes, paper dyes, fastness properties, photometric quality control, and coloration industry operations"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 484', 'Extraction and Physical Metallurgy', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'second', 2, 'Ores, ore dressing, agglomeration, thermodynamic principles of extraction processes, extraction procedures, metallic liquids, solidification, and phase diagrams.', '["Ores, ore dressing, agglomeration, thermodynamic principles of extraction processes, extraction procedures, metallic liquids, solidification, and phase diagrams"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 485', 'Cement and Fertilizer Industries', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Cement: Types of cement, cement chemistry, raw materials, and manufacturing processes. Fertilizers: Types of fertilizers, raw materials, and production methods.', '["Cement: Types of cement, cement chemistry, raw materials, and manufacturing processes", "Fertilizers: Types of fertilizers, raw materials, and production methods"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 486', 'Pulp and Paper Industries', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'second', 2, 'Physical and chemical properties of wood, wood preparation for pulping, mechanical and chemical pulping processes, bleaching, paper additives, beating and refining, and paper-making operations.', '["Physical and chemical properties of wood, wood preparation for pulping, mechanical and chemical pulping processes, bleaching, paper additives, beating and refining, and paper-making operations"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 487', 'Pharmaceutical Industry', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Synthesis of drugs, drug design, Structure-Activity Relationships (SAR), quality control, and local sourcing of raw materials for drugs and cosmetics.', '["Synthesis of drugs, drug design, Structure-Activity Relationships (SAR), quality control, and local sourcing of raw materials for drugs and cosmetics"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 488', 'Sugar and Fermentation Industries', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'second', 2, 'Manufacture of cane and beet sugar, utilization of sugar by-products for alcohol production, mechanisms of alcohol fermentation from carbohydrates and saccharine materials, and related products.', '["Manufacture of cane and beet sugar, utilization of sugar by-products for alcohol production, mechanisms of alcohol fermentation from carbohydrates and saccharine materials, and related products"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 489', 'Oils, Fats, Detergents and Chloroalkali Industries', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Oils and Fats: Sources, physical and chemical properties, extraction, purification, and hydrogenation. Soaps and Detergents: Manufacture of soaps and synthetic detergents. Chloro-Alkali Industry: Industrial production of chlorine, sodium hydroxide, sodium carbonate, and potassium hydroxide, along with their industrial uses.', '["Oils and Fats: Sources, physical and chemical properties, extraction, purification, and hydrogenation", "Soaps and Detergents: Manufacture of soaps and synthetic detergents", "Chloro-Alkali Industry: Industrial production of chlorine, sodium hydroxide, sodium carbonate, and potassium hydroxide, along with their industrial uses"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 492', 'Research Project', 'University of Nigeria, Nsukka', 'Faculty of Science', 'Pure and Industrial Chemistry', '400 Level', 'second', 6, 'Supervised original laboratory research work on an approved topic, culminating in a written project report.', '["Supervised original laboratory research work on an approved topic, culminating in a written project report"]'::jsonb, 'Department of Chemistry handbook');
