-- =============================================================================
-- University of Nigeria, Nsukka — Faculty of Biological Sciences
-- Zoology and Environmental Biology
-- Course outlines transcribed from the departmental course catalogue.
-- =============================================================================
-- Run in the Supabase SQL Editor. Safe to run more than once: existing rows
-- for these courses are removed first, so it updates rather than duplicates.
--
-- NOTES ON THE SOURCE:
-- * The catalogue's own course lists mislabel Laboratory Techniques as
--   "ZEB 305" in one table but "ZEB 303" everywhere else, including its own
--   course description heading — ZEB 303 is used here as the description
--   section is internally authoritative.
-- * A description headed "ZEB 481 Animal Genetics and Molecular Biology"
--   sits beside a separate, also-genuine "ZEB 481: Seminar" description.
--   Every course-list table in the catalogue (five independent variants)
--   uses ZEB 461 for Animal Genetics and Molecular Biology and ZEB 481 for
--   Seminar, so that description is filed under ZEB 461 here as the evident
--   correct code, and ZEB 481 keeps the Seminar description.
-- * ZEB 201, 202, 276 and 490 (Research Project) appear in the course lists
--   with a title and credit load but no descriptive text in the catalogue,
--   so their description/topics are left blank rather than invented.
-- * A few printed prerequisite codes (e.g. "ZEB 321" under MCB, "ZEB 281"
--   under ZEB 468, "ZEB 274" under ZEB 471) do not match any other course
--   code in the catalogue; they are quoted verbatim rather than corrected.
--
-- This file also carries the required ancillary and general-studies courses
-- a Zoology and Environmental Biology student actually sits each semester
-- (BIO, CHM, MTH, PHY, GSP, COS, CED, STA, SSC, plus BCH 201/202, MCB
-- 102/201 and PSB 102/211/221/241/313), scoped to department = 'Zoology and
-- Environmental Biology' so they appear on this department's own timetable
-- — independent rows from any same-code row filed under its own home
-- department. Descriptions are reused, unedited, from this app's
-- Biochemistry/Microbiology/Plant Science/Mathematics/Physics/Chemistry
-- outlines where the code, level, semester and subject genuinely match; the
-- catalogue's own "PHY 101" is used elsewhere in the Biological Sciences
-- catalogue only as "PHY 191", so it is filed here as PHY 191. Where no
-- verified description exists anywhere (BIO, GSP, COS, CED, STA, SSC), only
-- code/title/units/level/semester are given. Ancillary lists follow only the
-- catalogue's own standalone Standard Four-Year Programme table, not its
-- Three-Year direct-entry or combined-honours variants.
-- =============================================================================

delete from public.course_outlines
 where institution = 'University of Nigeria, Nsukka'
   and department = 'Zoology and Environmental Biology';

insert into public.course_outlines
  (course_code, course_title, institution, faculty, department, level,
   semester, credit_units, description, topics, contributor_name)
values
  ('ZEB 102', 'Introductory Zoology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '100 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 172', 'Introductory Environmental Biology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '100 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 122', 'Parasitology for Medical Students', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '100 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 201', 'General Invertebrate Zoology I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 202', 'General Invertebrate Zoology II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 272', 'Environmental Health Biology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'second', 2, 'Health implication of xenobiotics and environmental agents; global overview; common environmental hazards (sources and causes); industrial, laboratory and field hazards and safety practices; municipal solid waste health implication; health implications of pesticides, herbicides, nematicides, etc; radiation ecology; climatic change and environmental health; effect of environmental laws, institutions and organisations involved — operations rescue, emergency services, prevention of industrial hazards, post-hazard, laboratory safety, etc. Pollution and pollution control, formulation of control policies; systems of control and administration (national and international), national and international processes of enforcement and institutions/organisations, civil liberty, polluter pay principles; economic tools, agencies, compliance assessment, etc.', '["Health implications of xenobiotics and environmental agents; common environmental hazards", "Industrial, laboratory and field hazards and safety practices", "Municipal solid waste health implications; health implications of pesticides, herbicides, nematicides", "Radiation ecology; climatic change and environmental health", "Environmental laws, institutions and organisations; emergency services; prevention of industrial hazards; laboratory safety", "Pollution and pollution control; formulation of control policies (national and international)", "Polluter pay principles; economic tools, agencies and compliance assessment"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 276', 'Ecotoxicology and Environmental Safety', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 301', 'Chordate Zoology I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '300 Level', 'first', 2, 'General characteristics, organisation, comparative morphology and anatomy, classification, range of form, origin, evolution and phylogenetic relationships, distribution and general biology of protochordate, Pisces and Amphibia illustrated with selected examples.', '["General characteristics, organisation, comparative morphology and anatomy of protochordate, Pisces and Amphibia", "Classification, range of form, origin, evolution and phylogenetic relationships", "Distribution and general biology illustrated with selected examples"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 303', 'Laboratory Techniques', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '300 Level', 'first', 2, 'Principles of laboratory safety and precautions; laboratory wears (coats, boots, gloves, etc); handling of chemical spills, electrical accidents, animal care (housing, feeding, etc); micro techniques, microphotography, biological illustration. Histological and physiological techniques, entomological, parasitological, fisheries and environmental biology techniques, preparation of skeletons and other teaching aids.', '["Principles of laboratory safety and precautions; laboratory wear", "Handling of chemical spills and electrical accidents; animal care (housing, feeding)", "Micro techniques, microphotography and biological illustration", "Histological and physiological techniques", "Entomological, parasitological, fisheries and environmental biology techniques", "Preparation of skeletons and other teaching aids"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 311', 'Basic Animal Physiology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '300 Level', 'first', 2, 'Principles of physiology as illustrated by cells, tissues, organs, and whole organisms. Functional interrelationships of different organs and organ systems in vertebrates. Metabolic processes: co-ordination and control of metabolism, growth, reproduction and contraception.

Pre-requisite: BIO 152', '["Principles of physiology illustrated by cells, tissues, organs and whole organisms", "Functional interrelationships of organs and organ systems in vertebrates", "Metabolic processes: co-ordination and control of metabolism, growth, reproduction and contraception"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 313', 'Animal Histology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '300 Level', 'first', 2, 'The detailed structure of tissues and organs of vertebrates, and the relation of these structures to function. Histological and histochemical techniques.

Pre-requisite: BIO 152', '["Detailed structure of tissues and organs of vertebrates and their relation to function", "Histological and histochemical techniques"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 321', 'Basic Parasitology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '300 Level', 'first', 2, 'Types of parasites; the ecology of animal parasites; life histories, modes of transmission and epidemiology. A review of important viral, rickettsial and spirochaetal infections of man and animals: protozoal, helminth and arthropod diseases of man and animals — pathogenicity, prevention and control. Economic importance of parasites with special reference to Nigeria and West Africa. Effects of climatic change on animal parasites and parasitism.

Pre-requisites: ZEB 201 and ZEB 202', '["Types of parasites; ecology of animal parasites; life histories, modes of transmission and epidemiology", "Review of viral, rickettsial and spirochaetal infections of man and animals", "Protozoal, helminth and arthropod diseases: pathogenicity, prevention and control", "Economic importance of parasites in Nigeria and West Africa", "Effects of climatic change on animal parasites and parasitism"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 331', 'Basic Entomology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '300 Level', 'first', 2, 'An introductory course to the study of the main groups of insects, ticks, and related arthropods of human welfare and economics, especially in the Ethiopian faunal region with emphasis on the fields of agriculture, medicine and commerce. Basic classification leading to recognition and identification, patterns of life history, bionomics of suitable species. Economic importance and the general principles and methods of arthropod pest control. Effects of climatic change on tropical insects ecology and biodiversity.

Pre-requisites: ZEB 202, BIO 151 to BIO 154 or their equivalents', '["Main groups of insects, ticks and related arthropods of economic and medical importance", "Basic classification, recognition and identification; patterns of life history and bionomics", "Economic importance and general principles and methods of arthropod pest control", "Effects of climatic change on tropical insect ecology and biodiversity"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 341', 'Basic Fisheries', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '300 Level', 'first', 2, 'Classification, morphology and life history of important freshwater and marine fish of West Africa with emphasis on Nigerian species. Adaptation of fish to aquatic life. Traditional fishing crafts, gear and methods. Fundamental principles of fishery management and production; fish culture practices in Nigeria — aims and types. Importance of fishery products. Effects of climatic change on tropical finfish ecology, distribution and abundance.', '["Classification, morphology and life history of freshwater and marine fish of West Africa", "Adaptation of fish to aquatic life", "Traditional fishing crafts, gear and methods", "Fundamental principles of fishery management and production; fish culture practices in Nigeria", "Effects of climatic change on tropical finfish ecology, distribution and abundance"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 351', 'Climatic Change and Animal Biodiversity', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '300 Level', 'first', 2, 'What is weather and climate. Climatic change in temperature, precipitation, humidity, evaporation, carbon budget, greenhouse gases, etc. Climatic change and ecosystem. History of climatic change and animal extinction; impact of climatic changes on animal (invertebrate and vertebrate) biodiversity; techniques in the study of climatic change and animal biodiversity; adaptation and management options to climatic change — water management, vegetation management, waste management, etc.', '["Weather and climate; climatic change in temperature, precipitation, humidity, evaporation, carbon budget", "Climatic change and ecosystem; history of climatic change and animal extinction", "Impact of climatic change on invertebrate and vertebrate biodiversity", "Techniques in the study of climatic change and animal biodiversity", "Adaptation and management options: water, vegetation and waste management"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 361', 'Basic Animal Molecular Biology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '300 Level', 'first', 2, 'Gross structure and function of cells and cellular organelles. Biological membrane phenomena; nuclear and cytoplasmic relationships; structure of DNA and RNA. Chromosome structure; DNA synthesis, transcription, translation; genetic code and protein synthesis. Techniques in molecular biology. Effects of climatic change on characterisation, breeding and conservation of animal genetic resources.', '["Gross structure and function of cells and cellular organelles", "Biological membrane phenomena; nuclear and cytoplasmic relationships", "Structure of DNA and RNA; chromosome structure", "DNA synthesis, transcription, translation; genetic code and protein synthesis", "Techniques in molecular biology", "Effects of climatic change on characterisation, breeding and conservation of animal genetic resources"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 363', 'Basic Animal Biotechnology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '300 Level', 'first', 2, 'Meaning of biotechnology; history of biotechnology; products from modern animal biotechnology. Types of biotechnology. Review of: cell structure, life molecules, chromosome structure, DNA replication and genomes, RNA and protein synthesis, mutation in animals and its consequences. Recombinant DNA technology and DNA cloning, vectors, identification of clones. Genetically modified organisms (GMO). Genomics and bioinformatics. Climatic change and genetically modified organisms.', '["Meaning, history and types of biotechnology; products from modern animal biotechnology", "Review of cell structure, life molecules, chromosome structure, DNA replication and genomes", "RNA and protein synthesis; mutation in animals and its consequences", "Recombinant DNA technology and DNA cloning, vectors, identification of clones", "Genetically modified organisms (GMO); genomics and bioinformatics", "Climatic change and genetically modified organisms"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 371', 'Ecosystem Monitoring and Management', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '300 Level', 'first', 2, 'Principles of biological monitoring, biological indicators of environmental change; vertebrates and invertebrates as biological monitors and their roles in predicting changes. Applications of comparative physiology, anatomy and biochemistry in biomonitoring. Biomonitoring as an assessment tool in remediation programmes; use of biological data in assessing compliance with environmental policies, regulations and standards. Case studies, etc. Principles of biotechnology, application of biotechnology principles in pollution and clean-up. Enzymes in waste management, sewage treatment, bioremediation, biodeterioration, biotechnology products in environmental management, etc.', '["Principles of biological monitoring; biological indicators of environmental change", "Vertebrates and invertebrates as biological monitors", "Applications of comparative physiology, anatomy and biochemistry in biomonitoring", "Biomonitoring as an assessment tool in remediation programmes; compliance with environmental policies", "Principles of biotechnology applied to pollution and clean-up", "Enzymes in waste management, sewage treatment, bioremediation and biodeterioration"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 392', 'Students'' Industrial Work Experience Scheme (Field Work)', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '300 Level', 'second', 6, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 394', 'SIWES Report', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '300 Level', 'second', 6, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 396', 'SIWES Seminar', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '300 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 401', 'Chordate Zoology II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'first', 2, 'General characteristics, organisation, comparative morphology and anatomy, classification, range of form, origin, evolution and phylogenetic relationships, distribution and general biology of the Reptilia, Aves and Mammalia illustrated with selected examples.

Pre-requisite: ZEB 301', '["General characteristics, organisation, comparative morphology and anatomy of Reptilia, Aves and Mammalia", "Classification, range of form, origin, evolution and phylogenetic relationships", "Distribution and general biology illustrated with selected examples"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 403', 'Systematic Zoology and Evolution', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'first', 2, 'A study of the principles of the collection, preservation, identification and classification of animals. The theories and mechanism of evolution with special emphasis on the genetic basis for evolution. Human evolution with special reference to early African origins.

Pre-requisites: ZEB 201, 202, 301, 401', '["Principles of the collection, preservation, identification and classification of animals", "Theories and mechanism of evolution, with emphasis on the genetic basis for evolution", "Human evolution with special reference to early African origins"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 405', 'Mammalogy', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'first', 2, 'An introduction to the principles of mammalogy stressing the ecology of African mammals with particular reference to West Africa. Types, distribution, biology as well as role of wild animals in the economy of the continent.

Pre-requisites: ZEB 301, 302 (as printed in the catalogue)', '["Principles of mammalogy; ecology of African mammals, with reference to West Africa", "Types, distribution and biology of mammals", "Role of wild animals in the economy of the continent"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 411', 'Animal Developmental Biology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'first', 2, 'Comparative study of animal development and morphogenesis; differences in developmental biology; techniques of and inference from experimental embryology, etc.

Pre-requisites: ZEB 311, ZEB 313, BIO 151', '["Comparative study of animal development and morphogenesis", "Differences in developmental biology", "Techniques of and inference from experimental embryology"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 413', 'Animal Physiology I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'first', 2, 'Important concepts in physiology. Membrane physiology and maintenance of steady state in animal cells; metabolic rate and body size. Principles of gaseous exchange: aquatic and terrestrial respiration — respiratory adaptations and their physiological basis. Comparative account of animal nutrition. Haemodynamics. Comparative treatment of animal hearts and circulatory mechanisms. Homoeostasis — regulation of body fluid composition; detoxification mechanisms and nitrogenous excretion. Neuromuscular physiology. Sensory and hormonal integrative mechanisms. Growth and reproduction in animals.

Pre-requisites: ZEB 311, ZEB 313', '["Membrane physiology and maintenance of steady state in animal cells; metabolic rate and body size", "Principles of gaseous exchange: aquatic and terrestrial respiration", "Comparative account of animal nutrition; haemodynamics; circulatory mechanisms", "Homoeostasis: regulation of body fluid composition; detoxification and nitrogenous excretion", "Neuromuscular physiology; sensory and hormonal integrative mechanisms", "Growth and reproduction in animals"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 421', 'Animal Parasitology I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'first', 2, 'The ecological basis and nature, origin and features of parasitism; kinds and habitats of parasites; concepts and definition of hosts; ecology and geographical distribution of animal parasites. A review of important viral, rickettsial and spirochaetal infections of man and animals. Survey of parasitic protozoa: classification, biology and life cycles; transmission, epidemiology, pathogenic mechanism, treatment and control. A comprehensive review of parasitic worms and nematodes: classification, functional morphology and life cycles, geographical distribution, epidemiology, pathogenesis, treatment and control. Medical entomology: disease causing arthropoda (including myiasis) — classification, habitats, life cycles, transmission and control. Arthropods as intermediate hosts and vectors of parasites. Insecticide and insecticide resistance.

Pre-requisite: ZEB 321', '["Ecological basis, nature, origin and features of parasitism", "Ecology and geographical distribution of animal parasites", "Review of viral, rickettsial and spirochaetal infections of man and animals", "Survey of parasitic protozoa: classification, biology, life cycles, transmission and control", "Parasitic worms and nematodes: classification, functional morphology, epidemiology and control", "Medical entomology: disease-causing arthropoda, classification, habitats, transmission and control", "Arthropods as intermediate hosts and vectors; insecticide and insecticide resistance"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 431', 'Entomology I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'first', 2, 'A comprehensive study of the taxonomy and bionomics of major insect orders with particular reference to tropical/subtropical species of agricultural, medical and veterinary importance. Pest management, etc.

Pre-requisites: ZEB 201, 202', '["Taxonomy and bionomics of major insect orders", "Tropical/subtropical species of agricultural, medical and veterinary importance", "Pest management"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 441', 'Fisheries Biology I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'first', 2, 'Morphology and anatomy of fish, classification of major fish groups with particular reference to the tropical region. Fish biology — food and feeding habits, age and growth, reproduction and life history studies; fisheries ecology and productivity; fish behaviour, parasites, population dynamics and stock assessment studies.', '["Morphology and anatomy of fish; classification of major fish groups in the tropical region", "Food and feeding habits, age and growth, reproduction and life history studies", "Fisheries ecology and productivity", "Fish behaviour, parasites, population dynamics and stock assessment studies"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 443', 'Hydrobiology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'first', 2, 'Principles of aquatic biology with particular reference to limnology. Water as an environment for life. The marine, brackish water/estuarine environments, colonisation and succession. Procedures and techniques in the estimation of aquatic productivity at primary and secondary levels. Production processes of invertebrates that facilitate management of fish stocks, distribution, adaptations and inter-relationships. Trophic relations, energy flow and consequent applied implications in terms of production and utilisation: man''s influence on aquatic communities, pollution. Hydrobiology research techniques.', '["Principles of aquatic biology with particular reference to limnology", "Marine, brackish water/estuarine environments; colonisation and succession", "Procedures and techniques in estimating aquatic productivity", "Production processes of invertebrates facilitating management of fish stocks", "Trophic relations, energy flow and applied implications for production and utilisation", "Man''s influence on aquatic communities and pollution; hydrobiology research techniques"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 453', 'Wildlife Management, Conservation and Park Management', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'first', 2, 'Factors which threaten natural communities and/or species, including landscape alteration, pollution, industrial accidents, introduction of exotic species and the collection of animals for zoos, the pet trade, research and hunting. The preservation of endangered communities and species; the management of natural communities; wildlife preserves, public education and legislation. Effects of climatic change on tropical wildlife (mammals, reptiles and birds) ecology and biodiversity.

Pre-requisites: ZEB 201, 202, 301, 401', '["Factors threatening natural communities and species: landscape alteration, pollution, industrial accidents, exotic species", "Collection of animals for zoos, the pet trade, research and hunting", "Preservation of endangered communities and species; management of natural communities", "Wildlife preserves, public education and legislation", "Effects of climatic change on tropical wildlife ecology and biodiversity"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 455', 'Wastes and Waste Management', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'first', 2, 'Sources and characterisation of wastes (physical, chemical and biological, etc). Municipal waste management. Strategies of waste management and control (re-cycling, feedstock, landfills, etc). Techno-economic and socio-political aspects of waste management; organisms associated with waste management. Problems and prospects of waste management in Nigeria. Transboundary movement of wastes; transboundary control; harmful wastes acts; institutions and commissions, etc.', '["Sources and characterisation of wastes: physical, chemical and biological", "Municipal waste management; strategies of waste management and control", "Techno-economic and socio-political aspects of waste management", "Organisms associated with waste management", "Problems and prospects of waste management in Nigeria", "Transboundary movement and control of wastes; harmful wastes acts; institutions and commissions"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 461', 'Animal Genetics and Molecular Biology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'first', 2, 'Structural organisation of chromosomes of prokaryotes and eukaryotes. Advances of the eukaryotic chromosomes over the prokaryotic types. Evolution of the eukaryotic chromosome type. The cell division cycle; mitosis and meiosis. Techniques in animal cytogenetics and karyotyping. Physical and chemical properties of nucleic acids. Gene expression and control; mutation and mutagenesis; transformation; modern trends in molecular genetics, etc.

Pre-requisites: BIO 351, 352; ZEB 361', '["Structural organisation of chromosomes of prokaryotes and eukaryotes", "Evolution of the eukaryotic chromosome type", "The cell division cycle: mitosis and meiosis", "Techniques in animal cytogenetics and karyotyping", "Physical and chemical properties of nucleic acids", "Gene expression and control; mutation and mutagenesis; transformation; modern trends in molecular genetics"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 463', 'Advanced Animal Biotechnology I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'first', 2, 'Animal protein biotechnology and products. Animals in biotechnology research. Clones; creating Dolly, limits of cloning, future of cloning. Transgenic animals; transgenic techniques, improving agro-aquaculture products with transgenics, transgenic animals as bioreactors, knock-out — a special case of transgenics. Antibodies production in animal models; monoclonal antibodies, egg as antibody factories. DNA fingerprinting and forensic biotechnology. Molecular genetics of aquatic animals. Biomass and bioprocessing. Environmental animal biotechnology and bioremediation.', '["Animal protein biotechnology and products; animals in biotechnology research", "Cloning: creating Dolly, limits and future of cloning", "Transgenic animals and techniques; transgenic animals as bioreactors; knock-out animals", "Antibody production in animal models; monoclonal antibodies", "DNA fingerprinting and forensic biotechnology", "Molecular genetics of aquatic animals; biomass and bioprocessing", "Environmental animal biotechnology and bioremediation"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 402', 'Ethology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'second', 2, 'Principles of animal behaviour. Neurophysiological anatomy, stimuli, reflexes and biological rhythms. Instinct, learning, conflict behaviour. Propagative and other aspects of behaviour as shown by invertebrates and vertebrates including man.

Pre-requisites: ZEB 301, 202, 301, 401 (as printed in the catalogue)', '["Principles of animal behaviour", "Neurophysiological anatomy, stimuli, reflexes and biological rhythms", "Instinct, learning and conflict behaviour", "Propagative and other aspects of behaviour in invertebrates, vertebrates and man"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 404', 'Small Animal Production', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'second', 2, 'Biology of small animals (invertebrates and vertebrates). Ecology of small animals, parasites and diseases of small animals; breeding and rearing of small animals, population dynamics of small animals; limitations of small animal production — energy and increased labour requirements, diseases, predators; legal and administrative restrictions; production systems of small animals, e.g. insects (termites, maggots, drosophila, honey bee), molluscs (freshwater and land snails, mussels), rodents (giant rats, grass cutters, guinea pigs), small mammals (rabbits, musk deer, other small ruminants), reptiles, etc.', '["Biology and ecology of small animals: invertebrates and vertebrates", "Parasites and diseases; breeding and rearing; population dynamics", "Limitations of small animal production: energy, labour, diseases, predators, legal restrictions", "Production systems: insects, molluscs, rodents, small mammals, reptiles"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 412', 'Animal Physiology II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'second', 2, 'Physiological adjustments to the environment: temperature, heat, pressure, chemicals, etc; animal rhythms. Life and regulatory mechanisms: ecto- and endo-therms, etc. Dormancy phenomena in animals. Physiological adjustments to diving, high altitudes and exercise, endogenous and exogenous factors in reproductive strategies; physiology of specialised effectors — electric organs, visual, auditory phenomena, balance.', '["Physiological adjustments to environment: temperature, heat, pressure, chemicals; animal rhythms", "Life and regulatory mechanisms: ecto- and endo-therms; dormancy phenomena", "Physiological adjustments to diving, high altitudes and exercise", "Endogenous and exogenous factors in reproductive strategies", "Physiology of specialised effectors: electric organs, visual and auditory phenomena, balance"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 422', 'Animal Parasitology II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'second', 2, 'Physiology of animal parasites: nutrition, host finding mechanisms, physiology of the infectious process (e.g. excystment, hatching, exsheathment), physiology of host-parasite relationship, host nutrition and parasite physiology. Biochemistry of animal parasites: oxygen relations, carbon dioxide utilisation, energy metabolism, active transport, phosphorylation. Reproductive physiology and biochemistry. Immunology of animal parasites: non-specific mechanisms of immunity, innate immunity, specific immunological responses, immunoglobulin, complement and other factors; antigens and the process of antibody production, serological aspects of the antigen-antibody reaction, cross reactions. Delayed-type hypersensitivity. Hypersensitivity mediated by antibodies. Cell-mediated immunity. Immunodiagnosis. Antiallergy and its relation to parasitic diseases. Epidemiology and public health parasitology: epidemiological methods. Health-related aspects of community development: water supply, sanitation and disposal of waste matter. Epidemiology and control of water and food borne infections. Epidemiology and the control of zoonoses. Administrative and cultural aspects of communicable disease control. Parasitic population models and the control of parasitic diseases.', '["Physiology of animal parasites: nutrition, host finding, infectious process, host-parasite relationship", "Biochemistry of animal parasites: oxygen relations, energy metabolism, active transport, phosphorylation", "Reproductive physiology and biochemistry of parasites", "Immunology of animal parasites: innate and specific immune responses, antibody production", "Hypersensitivity, cell-mediated immunity and immunodiagnosis", "Epidemiology and public health parasitology; water supply, sanitation and waste disposal", "Epidemiology and control of water and food borne infections and zoonoses", "Parasitic population models and the control of parasitic diseases"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 432', 'Entomology II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'second', 2, 'Insect integument — composition, structure and physiology. Muscular and nervous systems, sense organs, alimentary system, respiratory and circulatory systems, excretory organs, reproductive systems, embryonic and post-embryonic developments. Physiology of moulting. Hormones and pheromones. Mode of action of pesticides.', '["Insect integument: composition, structure and physiology", "Muscular, nervous, alimentary, respiratory, circulatory, excretory and reproductive systems", "Embryonic and post-embryonic development; physiology of moulting", "Hormones and pheromones; mode of action of pesticides"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 442', 'Fisheries Biology II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'second', 2, 'Fishing gear and methods; distribution and abundance of major marine and freshwater fisheries, fisheries management, aquaculture and fish farming practices/management; fish handling, preservation and processing techniques, distribution, marketing; fishermen''s co-operatives.', '["Fishing gear and methods", "Distribution and abundance of major marine and freshwater fisheries", "Fisheries management; aquaculture and fish farming practices", "Fish handling, preservation and processing techniques; distribution and marketing", "Fishermen''s co-operatives"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 452', 'Animal Ecology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'second', 2, 'In-depth studies of the relationships of animals to their environment, especially as they affect their distribution and abundance, population structures, community metabolism; zoogeography, evolutionary and genetic ecology; biological control; environmental threats to man and animals; game reserves and game cropping.', '["Relationships of animals to their environment: distribution, abundance and population structures", "Community metabolism; zoogeography, evolutionary and genetic ecology", "Biological control; environmental threats to man and animals", "Game reserves and game cropping"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 454', 'Animal Biodiversity, Management and Prospecting', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'second', 2, 'Introduction to animal biodiversity; principles of biodiversity and methods of conservation evaluation; numerical diversity measures; extent of animal diversity, evaluation, animal diversity measurements, techniques (multivariate and graphical); diversity indices, temporal and spatial variability. Biodiversity differences in terrestrial and aquatic ecosystems; wetlands, etc.', '["Introduction to animal biodiversity; principles and methods of conservation evaluation", "Numerical diversity measures; techniques (multivariate and graphical)", "Diversity indices, temporal and spatial variability", "Biodiversity differences in terrestrial and aquatic ecosystems, including wetlands"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 462', 'Animal Molecular Biology and Bioinformatics', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'second', 2, 'Significance of human genetics; problems in experimentation and data collection; Mendelian genetics; deviations from Mendelian ratios; cell division; nature of chromosomes; gene; DNA; protein synthesis; mutations; human karyotype (basis for autosomal sex linked inheritances). Pedigree analysis; inherited haemoglobinopathy, e.g. sickle cell anaemia; inherited enzyme defects — PKU, albinism, etc; human ABO systems. Genetic counselling, etc. Introduction to bioinformatics, internet studies — world wide web, HTML and URL, search engines, PubMed and information retrieval, MeSH vocabulary; sequence information sources — EMBL nucleotide sequence database, GenBank overview, Entrez, LotusLink, UniGene; protein information sources, sequence and phylogeny analysis, etc. Genome, nucleotides and polynucleotide, base pairing, DNA, RNA, genetic code, homology, protein synthesis.

Pre-requisites: BIO 351, 352; ZEB 361', '["Significance of human genetics; Mendelian genetics and deviations from Mendelian ratios", "Cell division; nature of chromosomes, genes, DNA and protein synthesis; mutations", "Human karyotype; pedigree analysis; inherited disorders (sickle cell anaemia, PKU, albinism); genetic counselling", "Introduction to bioinformatics: internet studies, search engines, PubMed, MeSH vocabulary", "Sequence information sources: EMBL, GenBank, Entrez, UniGene; sequence and phylogeny analysis", "Genome, nucleotides, base pairing, genetic code, homology and protein synthesis"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 464', 'Advanced Animal Biotechnology II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'second', 2, 'Advances in medical biotechnology; biomarkers for disease detection, vaccines and therapeutic antibodies, detecting genetic diseases, gene therapy. Cell and tissue transplanting; tissue engineering, stem cell technologies and cloning, embryonic stem cell and therapeutic cloning. Human genomic project. Gene banks. Animal biotechnology regulations; inspections, EPA, food and drugs administration, legislation and regulations, patents, ethical issues in biotechnology. Biotechnology and nature.', '["Advances in medical biotechnology: biomarkers, vaccines, therapeutic antibodies, genetic disease detection, gene therapy", "Cell and tissue transplanting; tissue engineering; stem cell technologies and cloning", "Human genomic project; gene banks", "Animal biotechnology regulations: inspections, legislation, patents and ethical issues"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 468', 'Population Genetics', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'second', 2, 'The population; diversity and sample; Mendelian and quantitative genetics; gene and genotype frequencies and Hardy-Weinberg equilibrium; factors affecting genetic frequencies and natural populations. Ecological genetics, coefficients of natural/artificial selection. Gene polymorphism, population growth and limitations; genetics in animal breeding; cross programmes to investigate quantitative characters, etc.

Pre-requisites: ZEB 281 and BIO 351 (as printed in the catalogue)', '["The population: diversity and sample; Mendelian and quantitative genetics", "Gene and genotype frequencies and Hardy-Weinberg equilibrium", "Factors affecting genetic frequencies and natural populations", "Ecological genetics; coefficients of natural/artificial selection", "Gene polymorphism, population growth and limitations", "Genetics in animal breeding; cross programmes to investigate quantitative characters"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 471', 'Environmental Biology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'first', 2, 'Ecosystem management, fundamentals of environmental education, ecosystems (urban, estuarine, freshwaters, aerial, land, etc) and components, watershed approach to sustainable management and development, major environmental problems (global warming and climatic change, water quality, etc). Effect of chemical industries/development projects on animal life forms and environmental quality, elements and techniques of environmental monitoring and remote sensing, etc.

Pre-requisites: ZEB 172, 274 and 371 (as printed in the catalogue)', '["Ecosystem management; fundamentals of environmental education", "Ecosystems: urban, estuarine, freshwater, aerial and land, and their components", "Watershed approach to sustainable management and development", "Major environmental problems: global warming, climatic change, water quality", "Effect of chemical industries and development projects on animal life forms and environmental quality", "Elements and techniques of environmental monitoring and remote sensing"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 472', 'Environmental Impact Assessment', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'second', 2, 'Animal population estimation techniques in various habitats, principles of environmental impact assessment; the use of animal population data in environmental impact assessment (EIA), environmental impact assessment scoping, etc. Techniques of environmental impact assessment (EIA), elements of EIA, environmental impact statements (EIS), environmental auditing (EA) and modelling, case studies, remediation and appraisals, predictive value of animal population data, application of biodiversity indices in environmental studies and management, etc. Legislative frameworks (national and international), etc.', '["Animal population estimation techniques in various habitats", "Principles of environmental impact assessment (EIA); use of animal population data in EIA", "Techniques and elements of EIA; environmental impact statements (EIS)", "Environmental auditing (EA) and modelling; case studies; remediation and appraisals", "Application of biodiversity indices in environmental studies and management", "Legislative frameworks: national and international"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 481', 'Seminar', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'first', 2, 'Literature research/review on a selected topic under staff guidance, written up and presented in class and finally submitted as a write-up.', '["Literature research/review on a selected topic under staff guidance", "Presentation in class and submission of a final write-up"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 490', 'Research Project', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '400 Level', 'second', 6, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BIO 151', 'General Biology I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '100 Level', 'first', 3, 'Elective.', '[]'::jsonb, 'Department of Computer Science course outline'),
  ('CHM 101', 'Basic Principles of Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '100 Level', 'first', 2, 'Stoichiometry and atomic structure: stoichiometry and mole concept. Introduction to atomic structure, development of electronic configuration of the elements, and valency theories. Periodic table and groups: the periodic classification of elements. Brief group study of representative elements, with emphasis on similarities and differences based on periodic position. Nuclear chemistry: radioactivity and its practical applications.', '["Stoichiometry and mole concept; introduction to atomic structure and valency theories", "Periodic classification of elements; brief group study of representative elements", "Nuclear chemistry: radioactivity and its practical applications"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 171', 'Basic Practical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '100 Level', 'first', 2, 'Laboratory operations: theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations.', '["Laboratory operations: theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MTH 111', 'General Mathematics I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '100 Level', 'first', 3, 'Elementary set theory, subsets, union, intersection, complements. Venn diagrams, real numbers, integers, rational and irrational numbers, mathematical induction, real sequences and series, theory of quadratic equations, binomial theorem. Circular measure, trigonometric functions of angles of any magnitude, addition and factor formulae. Complex numbers, algebra of complex numbers, the Argand diagram, De Moivre''s theorem, nth roots of unity.', '["Elementary set theory, subsets, union, intersection, complements", "Venn diagrams, real numbers, integers, rational and irrational numbers, mathematical induction, real sequences and series, theory of quadratic equations, binomial theorem", "Circular measure, trigonometric functions of angles of any magnitude, addition and factor formulae", "Complex numbers, algebra of complex numbers, the Argand diagram, De Moivre''s theorem, nth roots of unity"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('PHY 111', 'General Physics for Life Sciences I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '100 Level', 'first', 2, 'Units and dimension. Scalars and vectors. Linear and circular motion, velocity, acceleration. Laws of mechanics and gravitation; simple applications. Conservation of energy, momentum. Work and power. Simple harmonic motion, simple pendulum. Moment of inertia, angular momentum; centrifugal and centripetal forces; centrifuges. Elasticity, Hooke''s Law, Young''s modulus. Fluids, pressure, surface tension, velocity, osmosis; blood pressure and its measurement.', '["Units and dimension; scalars and vectors", "Linear and circular motion, velocity, acceleration", "Laws of mechanics and gravitation; conservation of energy and momentum", "Work and power; simple harmonic motion, simple pendulum", "Moment of inertia, angular momentum; centrifugal and centripetal forces; centrifuges", "Elasticity, Hooke''s Law, Young''s modulus", "Fluids: pressure, surface tension, velocity, osmosis; blood pressure and its measurement"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('PHY 191', 'Practical Physics', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '100 Level', 'first', 2, 'Selected experiments from the 100-Level courses in Physics for service courses.', '["Selected experiments from the 100-Level courses in Physics for service courses"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('GSP 101', 'The Use of English I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '100 Level', 'first', 2, 'Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, The English Language and the Nigerian society, World English, Levels and Varieties of English — formal, informal, standard, etc., English in Literature and the Media.

Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes, English Language Register, diatypes and dialects.

Listening skill - The listening skill discussed as a receptive and reciprocal activity, Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening.

Reading Skill - The concept of reading as a linguistic organization and a vehicle of communication. Reading Problems, Levels of Reading, Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies (Scanning, Skimming, Phrase reading, Intensive & Extensive reading, Exploiting the topic sentence for main ideas), Reading for details, Reading for evaluation and inference, Reading with questions - SQ3R, PR3, Methods for understanding difficult words in a reading text, Literature reading for study, analysis and comment.

Speaking & Communication Skills - Nature, Process & Development, Principles of Public Speech Making and Social Interaction, The Speech Sounds of English and their Articulation, Phonetic Transcription and Practical Speech Work.

Study Techniques - Choosing study centers and discussion groups, Note-taking during lectures, and from audio-visual equipment, Note-making techniques during private reading and literature search, Summary & Transcoding Techniques, Retrieving information from notes, The dictionary as a study guide.

Basic Research Methods & Term Paper Writing - Research – meaning & nature, Types & Methodology; Data in the Research Process, The Research Report, Process and Techniques, Documentation in Research Reports: Process, Types and Methods, Abbreviations in Research Reports, The term paper as a miniature research report, Practical term paper writing.

Course Evaluation & Grading - Students must attend at least 75% of the lectures to qualify for examination in the course.', '["Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, World English, Levels and Varieties of English", "Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes", "Listening skill - Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening", "Reading Skill - Reading Problems, Levels and Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies, Reading for evaluation and inference", "Speaking & Communication Skills - Principles of Public Speech Making and Social Interaction, Phonetic Transcription and Practical Speech Work", "Study Techniques - Note-taking, Note-making, Summary & Transcoding Techniques", "Basic Research Methods & Term Paper Writing - The Research Report, Documentation, Abbreviations, practical term paper writing"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('GSP 111', 'The Use of the Library', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '100 Level', 'first', 2, 'Overview of Library: concepts, history, types and functions. Uses in academic libraries; organization of university library and library users. Library processes and procedures. Acquisition process, Cataloging and classification, LC Scheme, in-House Scheme, DDC. Serials process and circulation processes. Access tools in Library resources: Library catalogues, Indexes, Abstracts, Current contents information in the library. Reference sources: types of reference sources and services. Web resources and online resources. Overview of Databases, Online search strategies for information retrieval. Referencing and citation styles for information reporting. Concept of plagiarism. Learning skills and research skills, ICT skillsets: types of learning and information policies.', '["Overview of Library: concepts, history, types and functions. Uses in academic libraries; organization of university library and library users", "Library processes and procedures. Acquisition process, Cataloging and classification, LC Scheme, in-House Scheme, DDC. Serials process and circulation processes", "Access tools in Library resources: Library catalogues, Indexes, Abstracts, Current contents information", "Reference sources: types of reference sources and services. Web resources and online resources", "Overview of Databases, Online search strategies for information retrieval. Referencing and citation styles for information reporting. Concept of plagiarism", "Learning skills and research skills, ICT skillsets: types of learning and information policies"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('BIO 152', 'General Biology II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '100 Level', 'second', 3, 'Elective.', '[]'::jsonb, 'Department of Statistics undergraduate course module'),
  ('BIO 154', 'General Biology Practical', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '100 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 112', 'Basic Principles of Physical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '100 Level', 'second', 2, 'Gas laws and kinetic theory: kinetic theory of gases, elementary derivation and deduction of gas laws, molecular speeds, deviations from ideal behaviour, van der Waals modification, and gas liquefaction. Phase equilibrium and solutions: phase transitions and phase equilibria in one-component systems; ideal solutions, Raoult''s law, Henry''s law, real solutions, and colligative properties. Thermodynamics and kinetics: aspects of the first law of thermodynamics, thermochemistry, entropy, free energy, and spontaneous changes; ionic equilibria, acids, bases, indicators, and buffers; elementary chemical kinetics.', '["Gas laws and kinetic theory of gases; molecular speeds; deviations from ideal behaviour; gas liquefaction", "Phase transitions and phase equilibria; ideal and real solutions; colligative properties", "First law of thermodynamics, thermochemistry, entropy, free energy, spontaneous changes", "Ionic equilibria, acids, bases, indicators and buffers", "Elementary chemical kinetics: rate laws, order and molecularity, Arrhenius equation"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 122', 'Basic Principles of Organic Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '100 Level', 'second', 2, 'Structure and classification: historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, homologous series, elemental analysis, molecular formulas, and structural isomerism. Bonding and reactivity: isolation and purification methods, functional group concepts, resonance, and aromaticity. Functional groups: saturated and unsaturated hydrocarbons, cyclic hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, and aromatic compounds. Stereochemistry and lipids: introduction to oils, fats, and stereoisomerism.', '["Historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, structural isomerism", "Isolation and purification methods; functional group concepts; resonance and aromaticity", "Saturated and unsaturated hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, aromatic compounds", "Introduction to oils, fats, and stereoisomerism"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('PHY 112', 'General Physics for Life Sciences II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '100 Level', 'second', 2, 'Concepts of heat, temperature: measurement of temperature, clinical thermometer. Heat capacity, specific heat, latent heat, calorimetry. Gas laws; kinetic theory of gases. Thermal energy, isothermal and adiabatic changes. Conduction, convection; radiation. Sound waves; intensity, pitch and quality of sound. Propagation of sound in solids, liquids and gases. Doppler effect. The ear. Reflection and refraction of light; plane and spherical mirrors, thin lenses; optical instruments. The eye, defects of vision and their corrections. Wave nature of light, interference, diffraction: velocity of light.', '["Concepts of heat and temperature: measurement, clinical thermometer, heat capacity, calorimetry", "Gas laws; kinetic theory of gases; thermal energy, isothermal and adiabatic changes", "Conduction, convection and radiation", "Sound waves: intensity, pitch, quality; propagation in solids, liquids and gases; Doppler effect; the ear", "Reflection and refraction of light: mirrors, thin lenses, optical instruments", "The eye, defects of vision and their corrections", "Wave nature of light: interference, diffraction, velocity of light"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('GSP 102', 'The Use of English II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '100 Level', 'second', 2, 'Part A: Basic Grammar: Introduction. The concept of grammar and its place in language teaching and learning. Parts of speech and their functions (treated in detail). Closed and open class items in parts of speech, Nominalization, Grammatical Structures: the phrase, the clause and the sentence. Elementary Clause Analysis, Sentence Types, Elements and Patterns. Agreement (Grammatical agreement, Notional agreement, Proximity agreement) Agreement with the correlatives. Direct and Reported Speech, Error typology identification and correction.

Part B: Varieties of writing. Introduction (The Meaning, Nature and Purpose of Writing, Writing Types or Genres and their Characteristics). The paragraph as the basic unit of an essay (Types, Development of the Paragraph, Methods of Paragraph Development, The thesis statement). Point of view and style in writing. Qualities of a good piece of writing: Form, Diction and Content in writing. The Mechanics of Writing: punctuation, spelling and capitalization.

Part C: Writing Genres - Planning and choosing your theme. Deciding your genre. Choosing and developing your plot. Point of view, setting and characterization. Using the language that works. Essay Writing — Narration, Description, Exposition and Argumentation. Technical Writing: Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes, own story for practice, Computer-linked writing, types, style, language, and process.', '["Part A: Basic Grammar - The concept of grammar, Parts of speech, Grammatical Structures, Sentence Types, Agreement, Direct and Reported Speech, Error typology", "Part B: Varieties of writing - Meaning, Nature and Purpose of Writing, the paragraph as the basic unit of an essay, the thesis statement, Qualities of a good piece of writing, Mechanics of Writing", "Part C: Writing Genres - Planning and choosing your theme, plot, point of view, setting and characterization", "Essay Writing - Narration, Description, Exposition and Argumentation", "Technical Writing - Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MCB 102', 'Introductory Microbiology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '100 Level', 'second', 2, 'Elective. History of development of Microbiology. Scope of Microbiology. Growth and nutrition of microorganisms. Laboratory cultivation of microorganisms and measurement of growth. See the Microbiology outline for the full description.', '["See MCB 102 in the Microbiology course outline for the full syllabus"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('PSB 102', 'General Plant Biotechnology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '100 Level', 'second', 2, 'Elective. Definition, origin and history of plant biotechnology. Basic terminologies used in biotechnology. See the Plant Science and Biotechnology outline for the full description.', '["See PSB 102 in the Plant Science and Biotechnology course outline for the full syllabus"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BIO 351', 'General Genetics', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 201', 'General Biochemistry I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'first', 3, 'The cell environment: water and solutes — the unique properties of water, H-bonds, electrostatic interactions, Van der Waals attraction; alkalinity and acidity, pH and pK and their influence on cellular activities; physiological buffers. Cell macromolecules: structure, properties and functions of carbohydrates, lipids, proteins and nucleic acids. Cell structure and function: structure and function of major cell organelles; differences between prokaryotic and eukaryotic cells; biological membranes — organisation, architecture, properties and functions; the cytoplasm — mitochondria, peroxisomes, endoplasmic reticulum, Golgi complex, ribosomes, lysosomes, endosome; the nucleus — the nuclear envelope, chromatin, chromosomes, nucleolus, etc.', '["The cell environment: water and solutes, H-bonds, electrostatic interactions, Van der Waals attraction", "Alkalinity and acidity, pH and pK and their influence on cellular activities", "Physiological buffers", "Structure, properties and functions of carbohydrates, lipids, proteins and nucleic acids", "Structure and function of major cell organelles; differences between prokaryotic and eukaryotic cells", "Biological membranes: organisation, architecture, properties and functions", "The cytoplasm: mitochondria, peroxisomes, endoplasmic reticulum, Golgi complex, ribosomes, lysosomes, endosome", "The nucleus: nuclear envelope, chromatin, chromosomes, nucleolus"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('COS 101', 'Introduction to Computer Science', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'first', 2, 'Concepts of hardware and software; basic subsystems of a digital computer; characteristics of a digital computer; devices/media; types/classes of computer emphasising the PC; history of computers and their generations. Problem-solving: algorithm, flowchart, pseudocode, program/data, running a program. Programming: introduction to Java/BASIC programming language syntax and programming. Booting and shutdown; types of operating system; user interface; managing information, computer malware (virus, etc); computer network; internet and web usage, e-mail, instant messaging, etc. Office applications; use of a statistical package and a database management system.', '["Concepts of hardware and software","basic subsystems of a digital computer","characteristics of a digital computer","devices/media","types/classes of computer emphasising the PC","history of computers and their generations","Problem-solving: algorithm, flowchart, pseudocode, program/data, running a program","Programming: introduction to Java/BASIC programming language syntax and programming","Booting and shutdown","types of operating system","user interface","managing information, computer malware (virus, etc)","computer network","internet and web usage, e-mail, instant messaging, etc","Office applications","use of a statistical package and a database management system"]'::jsonb, 'Department of Computer Science course outline'),
  ('STA 203', 'Statistics for Agricultural and Biological Sciences I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'first', 2, 'Initial steps in planning of biological experiments. Methods of data collection, presentation and analysis. Measures of central tendency and dispersion. Frequency distributions. Elementary probability. Discrete and continuous distributions: Binomial, Poisson, Normal and exponential distributions. Interval estimation.', '["Initial steps in planning of biological experiments", "Methods of data collection, presentation and analysis", "Measures of central tendency and dispersion", "Frequency distributions", "Elementary probability", "Discrete and continuous distributions: Binomial, Poisson, Normal and exponential distributions", "Interval estimation"]'::jsonb, 'Department of Statistics handbook'),
  ('CHM 221', 'General Organic Chemistry I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CED 341', 'Introduction to Entrepreneurship', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('GSP 201', 'Basic Concepts and Theory of Peace', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('GSP 207', 'Logic, Philosophy and Human Existence', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('PSB 211', 'Phycology and Bryology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'first', 2, 'Elective. Structure, reproduction, adaptation, life cycle and economic importance of the algae and bryophytes. See the Plant Science and Biotechnology outline for the full description.', '["See PSB 211 in the Plant Science and Biotechnology course outline for the full syllabus"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('PSB 221', 'General Plant Anatomy', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'first', 2, 'Elective. The origin of the primary body of plants; structures, organisation and functions of plant cells, tissues and tissue systems. See the Plant Science and Biotechnology outline for the full description.', '["See PSB 221 in the Plant Science and Biotechnology course outline for the full syllabus"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('PSB 241', 'General Mycology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'first', 2, 'Elective. A general account of the origin, affinities, distribution and economic importance of fungi. See the Plant Science and Biotechnology outline for the full description.', '["See PSB 241 in the Plant Science and Biotechnology course outline for the full syllabus"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 201', 'General Microbiology I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'first', 3, 'Elective. General review of the nature and biology of protozoa, fungi, algae, bacteria, archaea and viruses. See the Microbiology outline for the full description.', '["See MCB 201 in the Microbiology course outline for the full syllabus"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('SSC 2XX', 'Principles of Soil Science', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'first', 2, 'Elective, exact course number not printed legibly in the catalogue.', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BIO 352', 'Cytogenetics', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BIO 362', 'Basic Principles of Ecology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 202', 'General Biochemistry II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'second', 3, 'Enzymes: introduction to biological catalysts, nature, functions and classification of enzymes, factors affecting enzyme action. Energy metabolism: introductory bioenergetics/energy-rich compounds, carbohydrate metabolism — glycolysis and pentose phosphate pathway, the Krebs cycle and the glyoxylate cycle, electron transport and oxidative phosphorylation. Separation of macromolecules: chromatographic methods — thin layer chromatography, gel filtration, ion exchange chromatography, affinity chromatography; electrophoretic methods — nucleic acid gel electrophoresis, electrophoretic sizing of protein, isoelectric focusing.', '["Introduction to biological catalysts: nature, functions and classification of enzymes; factors affecting enzyme action", "Introductory bioenergetics/energy-rich compounds", "Carbohydrate metabolism: glycolysis and pentose phosphate pathway", "The Krebs cycle and the glyoxylate cycle", "Electron transport and oxidative phosphorylation", "Chromatographic methods: thin layer, gel filtration, ion exchange, affinity chromatography", "Electrophoretic methods: nucleic acid gel electrophoresis, protein sizing, isoelectric focusing"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('COS 304', 'Computer Applications', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('STA 204', 'Statistics for Agricultural and Biological Sciences II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '200 Level', 'second', 2, 'Tests of significance. Student $t$ test and $\chi^2$ test. Two sample test and paired comparison. Regression and correlation. Analysis of variance: one way, two way with no interaction. Latin square analysis. Multiple range tests. Analysis of covariance. Simple analysis of direct assays.', '["Tests of significance", "Student $t$ test and $\\chi^2$ test", "Two sample test and paired comparison", "Regression and correlation", "Analysis of variance: one way, two way with no interaction", "Latin square analysis", "Multiple range tests", "Analysis of covariance", "Simple analysis of direct assays"]'::jsonb, 'Department of Statistics handbook'),
  ('PSB 313', 'Morphology and Taxonomy of Angiosperms', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Zoology and Environmental Biology', '300 Level', 'first', 2, 'Elective. General morphology of Angiosperms: root, stem, leaf and shoot modifications; ontogeny and morphological interpretation of flowers. See the Plant Science and Biotechnology outline (listed there as "Morphology and Phytosystematics of Higher Plants") for the full description.', '["See PSB 313 in the Plant Science and Biotechnology course outline for the full syllabus"]'::jsonb, 'Faculty of Biological Sciences course catalogue');
