-- =============================================================================
-- University of Nigeria, Nsukka -- Faculty of Engineering
-- Department of Mechatronic Engineering
-- Five-Year Standard Undergraduate B.Eng Degree Programme
-- =============================================================================
-- Transcribed from Chapter Nine (book pages 173-177) of the Faculty of Engineering handbook.
-- 93 rows covering all ten semesters of the programme.
--
-- VERIFICATION: the handbook prints a "Total Credit Hours" for every semester.
-- Each semester's unit values were re-summed and compared against the printed
-- figure -- 21, 17, 21, 19, 22, 19, 22, 15, 22, 20 -- and every one reconciles.
-- That check is what makes the units column trustworthy: this handbook
-- right-aligns units, so a value can sit visually against the wrong row, and
-- the printed totals are what pin them back down. Where a semester offers an
-- elective group, only the units a student actually takes are counted toward
-- the total, matching how the handbook totals it.
--
-- DESCRIPTIONS: shared ancillary courses reuse the description already held
-- for that same course code elsewhere in this app, rather than getting freshly
-- invented prose -- a shared course must read identically across every
-- department that lists it. Department-specific courses carry an empty
-- description here: their text lives in the handbook's separate detailed
-- course-description section and is a follow-up pass rather than a guess.
--
-- FIFTH-YEAR ELECTIVES: both fifth-year semesters print an elective block
-- headed "Electives (Choose only one)". All options are stored with
-- is_elective = true so the app can show them as choices rather than as
-- required load, and each semester's checksum counts only the single 2-unit
-- elective a student actually takes -- which is exactly how the handbook
-- arrives at its own printed totals of 22 and 20.
--
-- NOTE ON CROSS-CHAPTER DISAGREEMENTS: this handbook is not internally
-- consistent about some shared codes, so each department records what its own
-- chapter prints. This chapter has GSP 101 = "Study Skills and Basic Research
-- Methods" and PHY 195 = "Practical Physics I", while the Metallurgical and
-- Materials chapter prints GSP 101 = "The Use of English I" and PHY 195 =
-- "Practical Physics II". This chapter also has MTH 207 = "Advanced
-- Mathematics VII" and MTH 206 = "Advanced Mathematics VI"; the Metallurgical
-- chapter swaps those two titles. These are the handbook contradicting itself,
-- not transcription errors.
-- =============================================================================

delete from public.course_outlines
 where institution = 'University of Nigeria, Nsukka'
   and department = 'Mechatronic Engineering';

insert into public.course_outlines
  (course_code, course_title, institution, faculty, department, level,
   semester, credit_units, description, topics, contributor_name, is_elective)
values
  ('EGR 101', 'Introduction to Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '100 Level', 'first', 2, 'An overview of engineering as a profession. Historical perspective, Discipline, Rationalization, professional affiliations, professional journey, successful studentship, creativity, roles of science and Technology; Engineering and Society: The role of engineers in nation building, professional impacts of Engineering practice and mitigation measures, professional challenges in Nigeria, historical and professional roles; Basic information on Agricultural and Bioresources Engineering, Professional practice, Sustainable Agricultural production in Nigeria; Introduction to Biomedical Engineering, Scope of biomedical engineering practice: A science perspective of Civil Engineering, corporate personality of Civil Engineering; Civil Engineering professional practice; Basic information on Electrical Engineering, Scope of Electrical Engineering professional practice; Electric power generation in Nigeria; Evolution to Electronic Engineering, Scope of Electronic Engineering Professional practice, practice of Electronic Engineering in Nigeria; Basic information on Mechanical Engineering, Scope of Mechanical Engineering professional practice, practice of Mechanical Engineering in Nigeria; Introduction to Mechatronics Engineering, Scope of Mechatronics engineering practice; Basic information on Metallurgical and Materials Engineering, Scope of Metallurgical and Materials Engineering professional practice, practice of Metallurgical and Materials Engineering.', '["An overview of engineering as a profession. Historical perspective, Discipline, Rationalization, professional affiliations, professional journey, successful studentship, creativity, roles of science and Technology", "Engineering and Society: The role of engineers in nation building, professional impacts of Engineering practice and mitigation measures, professional challenges in Nigeria", "Basic information on Agricultural and Bioresources Engineering; Introduction to Biomedical Engineering", "A science perspective of Civil Engineering, corporate personality and professional practice of Civil Engineering", "Basic information on Electrical Engineering; Electric power generation in Nigeria; Evolution to Electronic Engineering", "Basic information on Mechanical Engineering, Scope and practice of Mechanical Engineering in Nigeria", "Introduction to Mechatronics Engineering; Basic information on Metallurgical and Materials Engineering"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CHM 101', 'Basic Principles of Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '100 Level', 'first', 2, 'Stoichiometry and Atomic Structure: Stoichiometry and mole concept. Introduction to atomic structure, development of electronic configuration of the elements, and valency theories. Periodic Table and Groups: The periodic classification of elements. Brief group study of representative elements, with emphasis on similarities and differences based on periodic position. Nuclear Chemistry: Radioactivity and its practical applications.', '["Stoichiometry and Atomic Structure: Stoichiometry and mole concept. Introduction to atomic structure, development of electronic configuration of the elements, and valency theories", "Periodic Table and Groups: The periodic classification of elements. Brief group study of representative elements, with emphasis on similarities and differences based on periodic position", "Nuclear Chemistry: Radioactivity and its practical applications"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CHM 171', 'Basic Practical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '100 Level', 'first', 2, 'Laboratory operations: theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations.', '["Laboratory operations: theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 111', 'Elementary Mathematics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '100 Level', 'first', 3, 'Elementary set theory, subsets, union, intersection, complements. Venn diagrams, real numbers, integers, rational and irrational numbers, mathematical induction, real sequences and series, theory of quadratic equations, binomial theorem. Circular measure, trigonometric functions of angles of any magnitude, addition and factor formulae. Complex numbers, algebra of complex numbers, the Argand diagram, De Moivre''s theorem, nth roots of unity.', '["Elementary set theory, subsets, union, intersection, complements", "Venn diagrams, real numbers, integers, rational and irrational numbers, mathematical induction, real sequences and series, theory of quadratic equations, binomial theorem", "Circular measure, trigonometric functions of angles of any magnitude, addition and factor formulae", "Complex numbers, algebra of complex numbers, the Argand diagram, De Moivre''s theorem, nth roots of unity"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 121', 'Elementary Mathematics II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '100 Level', 'first', 3, 'Functions of a real variable, graphs, limits and continuity. The derivative as limit of rate of change. Techniques of differentiation. Curve sketching, integration as an inverse of differentiation. Methods of integration, definite integrals. Application of integration to areas and volumes.', '["Functions of a real variable, graphs, limits and continuity", "The derivative as limit of rate of change", "Techniques of differentiation", "Curve sketching, integration as an inverse of differentiation", "Methods of integration, definite integrals", "Application of integration to areas and volumes"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('PHY 121', 'Fundamentals of Physics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '100 Level', 'first', 3, 'Units and dimensions. Vector algebra. Kinematics of a particle''s mass point; laws of mechanics and gravitation. Kepler''s Laws. Motion of rigid bodies, moment of inertia, angular momentum, vertical motion of a particle, elastic string, motion of a simple pendulum. Impulse and change of Momentum. Impact of two smooth elastic spheres. Direct and Oblique impacts.', '["Units and dimensions. Vector algebra", "Kinematics of a particle''s mass point; laws of mechanics and gravitation. Kepler''s Laws", "Motion of rigid bodies, moment of inertia, angular momentum", "Vertical motion of a particle, elastic string, motion of a simple pendulum", "Impulse and change of Momentum. Impact of two smooth elastic spheres. Direct and Oblique impacts"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('PHY 195', 'Practical Physics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '100 Level', 'first', 2, 'Selected Experiments from the 100-Level courses in Physics for Physics majors and Engineering students.', '["Selected Experiments from the 100-Level courses in Physics for Physics majors and Engineering students"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 101', 'Study Skills and Basic Research Methods', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '100 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 111', 'The Use of Library and Study Skills', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '100 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EGR 102', 'Applied Mechanics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '100 Level', 'second', 3, 'Introduction - Force Systems, resultants, Moments, Couples. Equilibrium, free-body diagram, 2-dimensional force systems, equations for equilibrium of forces in space, internal forces, examples of simple machines, friction, pulleys, wires and cables, static and dynamic Friction. Centroid, graphical determination, Theorems of Pappus of centers of gravity and areas. Moments of Inertia of plane areas, built up sections etc. Kinematics of particles and rigid bodies. Newton''s laws of motion applied to a system of particles. Rectilinear and curvilinear motion, tangent, normal, polar, work, energy, power. Concepts of momentum and Newton''s laws of motion under gravity. Projectile motion.', '["Introduction - Force Systems, resultants, Moments, Couples. Equilibrium, free-body diagram, 2-dimensional force systems", "Equations for equilibrium of forces in space, internal forces, examples of simple machines, friction, pulleys, wires and cables, static and dynamic Friction", "Centroid, graphical determination, Theorems of Pappus of centers of gravity and areas. Moments of Inertia of plane areas, built up sections etc", "Kinematics of particles and rigid bodies. Newton''s laws of motion applied to a system of particles", "Rectilinear and curvilinear motion, tangent, normal, polar, work, energy, power", "Concepts of momentum and Newton''s laws of motion under gravity. Projectile motion"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 122', 'Elementary Mathematics III', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '100 Level', 'second', 3, 'Geometric representation of vectors in 1-3 dimensions, Components, direction cosines. Addition of vectors and multiplication of vectors by a scalar, linear independence. Scalar and vector products of two vectors. Differentiation and integration of vectors with respect to a scalar variable. Two-dimensional coordinate geometry. Straight lines, circles, parabolas, ellipses, hyperbolas. Tangents and normals. Kinematics of a particle. Components of velocity and acceleration of a particle moving in a plane. Force and momentum. Newton''s laws of motion; motion under gravity, projectile motion, resisted vertical motion of a particle, elastic string, motion of a simple pendulum, impulse and impact of momentum. Impact of two smooth elastic spheres. Direct and oblique impacts.', '["Geometric representation of vectors in 1-3 dimensions, Components, direction cosines", "Addition of vectors and multiplication of vectors by a scalar, linear independence", "Scalar and vector products of two vectors", "Differentiation and integration of vectors with respect to a scalar variable", "Two-dimensional coordinate geometry", "Straight lines, circles, parabolas, ellipses, hyperbolas", "Tangents and normals", "Kinematics of a particle", "Components of velocity and acceleration of a particle moving in a plane", "Force and momentum", "Newton''s laws of motion", "Motion under gravity, projectile motion, resisted vertical motion of a particle, elastic string, motion of a simple pendulum, impulse and impact of momentum", "Impact of two smooth elastic spheres", "Direct and oblique impacts"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('PHY 116', 'General Physics for Physical Sciences II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '100 Level', 'second', 2, 'Temperature and its measurement. Heat capacity, specific heat, latent heats, critical points. Calorimetry. Gas laws; kinetic theory of gases; thermal energy, work done by expanding gases; laws of thermodynamics. Liquefaction of gases. Heat transfer: conduction, convection, radiation. Longitudinal and transverse waves; vibrations in solids. Sound waves in solids, liquids, gases; pitch, intensity and quality of sound. Doppler Effect. Acoustics of buildings. Ultrasonics. Reflection and refraction of light; spherical mirrors; thin and thick lenses; optical instruments. Wave nature of light; interference, diffraction, polarization. Velocity of light.', '["Temperature and its measurement", "Heat capacity, specific heat, latent heats, critical points", "Calorimetry", "Gas laws", "Kinetic theory of gases", "Thermal energy, work done by expanding gases", "Laws of thermodynamics", "Liquefaction of gases", "Heat transfer: conduction, convection, radiation", "Longitudinal and transverse waves", "Vibrations in solids", "Sound waves in solids, liquids, gases", "Pitch, intensity and quality of sound", "Doppler Effect", "Acoustics of buildings", "Ultrasonics", "Reflection and refraction of light", "Spherical mirrors", "Thin and thick lenses", "Optical instruments", "Wave nature of light", "Interference, diffraction, polarization", "Velocity of light"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('PHY 124', 'Fundamentals of Physics III', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '100 Level', 'second', 3, 'Electrostatics, Coulomb''s Law, Gauss''s Law, simple applications. Electric field, electrostatic potential. Energy in electric field, capacitance, dielectrics. Electric current, Ohm''s law, circuit analysis, Thermoelectricity. Magnetic effects of currents, Ampere''s Law, Applications. Electromagnetism, Faraday''s law of induction, Maxwell''s equations. Alternating currents, A.C. circuits. Measuring devices. Motion of a charged particle in electric and magnetic fields, Hall Effect. Atomic and Nuclear structure. Nuclear fission and fusion. Nuclear reactors.', '["Electrostatics, Coulomb''s Law, Gauss''s Law, simple applications", "Electric field, electrostatic potential. Energy in electric field, capacitance, dielectrics", "Electric current, Ohm''s law, circuit analysis, Thermoelectricity", "Magnetic effects of currents, Ampere''s Law, Applications. Electromagnetism, Faraday''s law of induction, Maxwell''s equations", "Alternating currents, A.C. circuits. Measuring devices", "Motion of a charged particle in electric and magnetic fields, Hall Effect", "Atomic and Nuclear structure. Nuclear fission and fusion. Nuclear reactors"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CHM 112', 'Basic Principles of Physical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '100 Level', 'second', 2, 'Gas laws and kinetic theory: kinetic theory of gases, elementary derivation and deduction of gas laws, molecular speeds, deviations from ideal behaviour, van der Waals modification, and gas liquefaction. Phase equilibrium and solutions: phase transitions and phase equilibria in one-component systems; ideal solutions, Raoult''s law, Henry''s law, real solutions, and colligative properties. Thermodynamics and kinetics: aspects of the first law of thermodynamics, thermochemistry, entropy, free energy, and spontaneous changes; ionic equilibria, acids, bases, indicators, and buffers; elementary chemical kinetics.', '["Gas laws and kinetic theory of gases; molecular speeds; deviations from ideal behaviour; gas liquefaction", "Phase transitions and phase equilibria; ideal and real solutions; colligative properties", "First law of thermodynamics, thermochemistry, entropy, free energy, spontaneous changes", "Ionic equilibria, acids, bases, indicators and buffers", "Elementary chemical kinetics: rate laws, order and molecularity, Arrhenius equation"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CHM 122', 'Basic Principles of Organic Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '100 Level', 'second', 2, 'Structure and classification: historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, homologous series, elemental analysis, molecular formulas, and structural isomerism. Bonding and reactivity: isolation and purification methods, functional group concepts, resonance, and aromaticity. Functional groups: saturated and unsaturated hydrocarbons, cyclic hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, and aromatic compounds. Stereochemistry and lipids: introduction to oils, fats, and stereoisomerism.', '["Historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, structural isomerism", "Isolation and purification methods; functional group concepts; resonance and aromaticity", "Saturated and unsaturated hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, aromatic compounds", "Introduction to oils, fats, and stereoisomerism"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 102', 'Basic Grammar and Varieties of Writing', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '100 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 201', 'Introduction to Mechatronic Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CVE 211', 'Strength of Materials I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CVE 213', 'Strength of Materials Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'first', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 211', 'Basic Electrical Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EGR 201', 'Material Science', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EGR 213', 'Material Science Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'first', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MEC 211', 'Engineering Drawing I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MEC 261', 'Thermodynamics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 207', 'Advanced Mathematics VII', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'first', 2, 'Elements of linear algebra. Calculus: Elementary differentiation and relevant theorems. Differential equations: Exact equations, methods of solution of second-order ordinary differential equations, partial differential equations, with applications.', '["Elements of linear algebra", "Calculus: Elementary differentiation and relevant theorems", "Differential equations: Exact equations, methods of solution of second-order ordinary differential equations, partial differential equations, with applications"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 201', 'Basic Concepts and Theories of Peace and Conflicts', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 207', 'Logic, Philosophy and Human Existence', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 202', 'Basic Mechatronics Engineering Lab I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CVE 222', 'Fluid Mechanics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CVE 224', 'Fluid Mechanics Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 272', 'Engineering Computer Programming', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 282', 'Engineering Computer Programming Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 252', 'Basic Electrical Engineering Laboratory/Practice', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MEC 212', 'Workshop Technology I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 206', 'Advanced Mathematics VI', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'second', 2, 'The programme table prints "Advanced Mathematics VII" against both MTH 206 and MTH 207; quoted as printed. Complex analysis - Elements of the algebra of complex variables, trigonometric, exponential and logarithmic functions. The number system, sequences and series. Vector differentiation and integration.', '["Complex analysis - Elements of the algebra of complex variables, trigonometric, exponential and logarithmic functions", "The number system, sequences and series", "Vector differentiation and integration"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 208', 'Advanced Mathematics VIII', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'second', 2, 'Elective. Numerical analysis: Linear equations, non-linear equations; finite difference operators. Introduction to linear programming.', '["Numerical analysis: Linear equations, non-linear equations", "Finite difference operators", "Introduction to linear programming"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 202', 'Issues in Peace and Conflict Resolution', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 208', 'Nigerian Peoples and Culture Studies', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 311', 'Circuit Theory I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '300 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 331', 'Electromagnetic Fields and Waves I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 361', 'Electrical Machines I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '300 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 311', 'Electronics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '300 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 321', 'Mechatronic Engineering Design', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '300 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 351', 'Computer Software Engineering I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MEC 351', 'Mechanics of Fluids', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CED 341', 'Introduction to Entrepreneurship', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('STA 205', 'Statistics for Physical Sciences and Engineering I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 302', 'Technical Report Writing', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '300 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 326', 'Manufacturing Technology', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 332', 'Signals and Systems', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 342', 'Computer Hardware Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 344', 'Measurement and Instrumentation', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 362', 'Virtual Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 364', 'Fluidics Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CED 342', 'Business Development and Management', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EGR 302', 'Engineering Analysis', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '300 Level', 'second', 4, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 401', 'Heat and Mass Transfer', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '400 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 411', 'Electronics II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '400 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 421', 'Computer Aided Manufacturing', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '400 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 431', 'Control Engineering I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '400 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 433', 'Digital Systems and PLCs', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '400 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 441', 'Sensors and Actuators', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '400 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 461', 'Computer Aided Design/Computer Aided Manufacturing/Computer Numerical Control Machines (CAD/CAM/CNC) Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '400 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 491', 'Group Project', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '400 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EGR 401', 'Computational Methods', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '400 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 482', 'Seminar', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '400 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 484', 'Special Topics in Mechatronic Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '400 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EGR 402', 'Students'' Industrial Work Experience Scheme (SIWES)', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '400 Level', 'second', 10, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 511', 'Introduction to Robotics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 513', 'Process Automation', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 517', 'Automation and Robotics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 521', 'Vibrations', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 531', 'Control Engineering II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 533', 'Microcomputers and Microprocessor Systems', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 541', 'Digital Signal Processing', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 561', 'Partial Automation Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 503', 'Tribology', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('MCT 505', 'Fluid Power Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('MCT 515', 'Mobile Robotics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('MCT 523', 'Micro-Fabrication Technology', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('MCT 535', 'Control Engineering III', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('MCT 543', 'Machine Vision', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('MCT 502', 'Engineering Management and Law', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 514', 'Micro Electromechanical Systems and Very Large Scale Integration (MEMS and VLSI)', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 516', 'Power Electronics and Drives', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 552', 'Computer Software Engineering II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 554', 'Systems Modeling and Simulation', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 562', 'Full Automation Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 592', 'Project', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'second', 6, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MCT 504', 'Renewable Energy Resources', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('MCT 522', 'Lean Production Management and Industrial Logistics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('MCT 532', 'Microcontrollers and Embedded Systems', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('MCT 556', 'Computer-Aided Product Modeling', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechatronic Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true);
