-- COS 201 (Computer Programming I -- Java) CBT practice questions.
-- Grounded in the UNN Computer Science Department's own textbook,
-- "Computer Programming" by A.O. Ezugwu, O.E. Oguike, G.H. Ugwuishiwu,
-- M.N. Agu, G.E. Okereke et al. This is the same textbook the department's
-- own course description for this course (filed as COS 261 in Computer
-- Science's own outline, COS 201 everywhere else it is cross-listed) is
-- drawn from.
--
-- SCOPE, CHECKED AGAINST THE OFFICIAL SYLLABUS: COS 261/COS 201's own
-- course_outlines entry lists: problem solving methods and algorithm
-- development; designing/coding/debugging/documenting with good style; an
-- IDE; the JVM; writing a Java program, packages, simple programs; data
-- types; control constructs; classes; keyboard input; file I/O (byte
-- streams, character streams, buffered streams); writing text files; the
-- File class; standard streams. This bank is scoped to exactly that --
-- batch 1 covers Chapters 1-3 of the book (Introduction to Computer
-- Programming, Introduction to Problem Solving, Control Structures); batch
-- 2 covers the Standard Input/Output section of Chapter 5 (Program
-- Development Practices) and Chapter 7 (Java Classes, Objects and
-- Methods). Data Structures (the book's Chapter 4 -- arrays, autoboxing,
-- stacks, queues, linked lists, trees) was deliberately EXCLUDED after an
-- initial draft included it by mistake: Data Structures is COS 232, a
-- separate course in this department's own outline, not part of COS 261/
-- COS 201. The book's later chapters on Object-Oriented Programming proper,
-- String Processing, Searching & Sorting, Java Graphics Programming, and
-- OO Design with UML are likewise out of this course's syllabus and are
-- not drawn from here.
--
-- 131 questions covering: Java development tools (javac/java/javap/
-- javah/javadoc/jdb), core language features, variables and primitive data
-- types, statements and tokens, relational operators, OOP fundamentals
-- introduced in Chapter 1 (encapsulation/inheritance/polymorphism/message
-- passing/garbage collection), algorithm development (stepwise
-- refinement), control structures (if/switch/for/while/do-while/break/
-- continue) including code-tracing questions with independently hand-
-- verified output, standard input/output (the Scanner class and its
-- next-family methods, System.out/PrintStream, and the InputStreamReader/
-- BufferedReader chain for reading a line of keyboard input, all read
-- directly from the book's own worked examples), and classes/objects/
-- methods (instance variables, set/get methods, this, object creation with
-- new, default null initial values, UML class-diagram compartments, and
-- method parameter matching), grounded in the book's own Account class
-- worked example.
--
-- COS 201 is cross-listed at different levels across departments in this
-- app (200 Level for Mathematics/Physics/Statistics, 300 Level for
-- Chemistry/Geology/Crop Science); this bank is filed at 200 Level to match
-- Computer Science's own numbering (COS 261) for the same course.
--
-- Conventions matching the rest of this project's CBT banks: no LaTeX
-- (this is a programming course, not a math one -- Java code is shown as
-- plain text); every code-tracing question's expected output was hand
-- traced and cross-checked; distractors are plausible and of comparable
-- length to the correct answer; correct answers are spread across
-- positions rather than clustered.
--
-- cbt_questions has no course_code column, so the paper is identified by
-- subject_name. faculty lists every faculty whose course_outlines actually
-- require this course (Physical Sciences, Agriculture) so it is not hidden
-- from students outside whichever single faculty happened to author it.

delete from public.cbt_questions where subject_id = 'cos-201-java-programming';

insert into public.cbt_questions
  (subject_id, subject_name, institution, faculty, department, level,
   question, options, correct_index, explanation, topic, is_general,
   semester, units)
values
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which Java development tool is used to compile a .java source file into bytecode?', '["java", "javac", "javap", "javadoc"]'::jsonb, 1, 'javac is the Java compiler; it translates a .java source file into a .class file containing bytecode. java is the interpreter that runs the compiled bytecode.', 'Java Development Environment', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which Java Development Kit tool is the interpreter that runs a compiled Java program?', '["javac", "java", "javah", "jdb"]'::jsonb, 1, 'java is the Java interpreter/launcher: it loads a .class file and lets the JVM execute its bytecode. javac only compiles; it does not run programs.', 'Java Development Environment', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What is the file extension produced when a .java source file is successfully compiled?', '[".java", ".class", ".jar", ".exe"]'::jsonb, 1, 'The compiler (javac) produces a .class file containing bytecode. The .java file is the source; .class is what the JVM actually interprets and runs.', 'Java Development Environment', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which Java tool is a disassembler that reports the methods and variables inside a compiled class file?', '["Javap", "Javah", "Javadoc", "Jdb"]'::jsonb, 0, 'Javap is the Java disassembler: given a class file, it reports the class''s members (methods and variables). Javah produces C header files, Javadoc generates HTML API documentation, and Jdb is the Java debugger.', 'Java Development Environment', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which Java tool generates API documentation in HTML from a program''s source comments?', '["Javac", "Javap", "Javadoc", "Jdb"]'::jsonb, 2, 'Javadoc is the documentation tool: it scans specially formatted comments in the source and produces HTML API documentation that can be viewed in a browser.', 'Java Development Environment', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which Java tool is used specifically for debugging a running Java program?', '["Jdb", "Javac", "Javap", "Javah"]'::jsonb, 0, 'Jdb is the Java debugger, used to step through and inspect a running program to locate bugs.', 'Java Development Environment', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'A key feature of Java is that compiled bytecode can run unmodified on any platform that has a JVM. What is this feature usually called?', '["Multithreading", "Write once, run anywhere", "Garbage collection", "Dynamic linking"]'::jsonb, 1, 'This is Java''s "Write once and Run anywhere" feature: since the .class file contains portable bytecode interpreted by the JVM, the same compiled program runs on any platform with a compatible JVM, without recompilation.', 'Features of Java', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Java eliminates explicit pointers and does not support multiple inheritance of classes. This is usually cited as an example of which feature of Java?', '["Distributed", "Familiar, Simple and Small", "Multithreaded", "Dynamic and Extensible"]'::jsonb, 1, 'Java being small and simple is attributed to design choices such as eliminating pointers, header files, operator overloading, and multiple inheritance, which keep the language easier to learn and use safely.', 'Features of Java', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'A Java program capable of managing and executing multiple tasks at the same time is demonstrating which feature of the language?', '["Distributed", "Multithreaded", "High performance", "Familiar and Simple"]'::jsonb, 1, 'Multithreading is Java''s facility for managing multiple tasks (threads) simultaneously, letting two or more tasks begin execution at essentially the same time -- useful in graphical and interactive applications.', 'Features of Java', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Java''s ability to open, access, and update remote objects over a network is described in the textbook as which feature?', '["Distributed", "Dynamic and Extensible", "High performance", "Multithreaded"]'::jsonb, 0, 'The Distributed feature of Java lets applications open and access remote objects on a network and update data at remote locations, without users of such applications experiencing time-dependent errors.', 'Features of Java', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In Java, what is a variable, at its most basic level?', '["A keyword reserved by the compiler", "A memory location given a name so it can be easily referred to and used in a program", "A method that returns a value", "A comment describing what a program does"]'::jsonb, 1, 'A variable is a named memory location. The programmer only needs to remember the name; the compiler keeps track of exactly where in memory that value is stored.', 'Variables', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which of these Java primitive data types is used to hold a single alphanumeric character?', '["int", "boolean", "char", "double"]'::jsonb, 2, 'char holds a single character. int, short, byte and long hold whole numbers; float and double hold real (decimal) numbers; boolean holds only true or false.', 'Data Types', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'byte, short, int and long are all Java primitive types used to store which kind of value?', '["Integer (whole) numbers", "Real (floating-point) numbers", "Logical values", "Single characters"]'::jsonb, 0, 'byte, short, int and long are all integer types -- they hold whole numbers. float and double hold real numbers, boolean holds logical values, and char holds single characters.', 'Data Types', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which Java primitive type is a collection of purely logical values -- true and false only?', '["char", "boolean", "int", "float"]'::jsonb, 1, 'boolean is Java''s logical type: a boolean variable can only ever hold true or false, nothing else.', 'Data Types', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'float and double are Java primitive types used to represent which kind of number?', '["Integer numbers only", "Real (decimal/floating-point) numbers", "Single characters", "Boolean values"]'::jsonb, 1, 'float and double are the real-number types in Java -- they hold numbers with a fractional/decimal part, unlike byte/short/int/long which only hold whole numbers.', 'Data Types', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Given the declaration `double bValue = 24.5;`, what does this statement do?', '["It declares an int variable named bValue and assigns it 24", "It declares a double variable named bValue and assigns it the real value 24.5", "It declares a variable named double with value bValue", "It is a syntax error because doubles cannot hold 24.5"]'::jsonb, 1, 'This is a standard declaration statement: `double` is the type, `bValue` is the variable name, and `= 24.5` initializes it to the real number 24.5.', 'Variables', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In Java, which of the following is classified as an expression statement?', '["A class declaration", "An if statement header", "aValue = 8933; (an assignment)", "A package declaration"]'::jsonb, 2, 'Expression statements are formed by terminating certain expressions with a semicolon: assignment expressions, any use of ++ or --, method invocations, and object creation expressions. `aValue = 8933;` is an assignment expression statement.', 'Statements', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', '`Bicycle myBike = new Bicycle();` is an example of which kind of Java statement?', '["A declaration statement only", "An object creation expression statement", "A control flow statement", "A comment"]'::jsonb, 1, 'Using `new` to construct an object and terminating it with a semicolon makes this an object creation expression statement -- one of the four kinds of expression statement described in the text (assignment, ++/--, method invocation, object creation).', 'Statements', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'According to the textbook, a Java program is fundamentally built up from which smallest indivisible units, recognized directly by the compiler?', '["Statements", "Tokens", "Classes", "Packages"]'::jsonb, 1, 'Tokens are described as the smallest indivisible things in a program that the compiler recognizes when building up expressions and statements -- examples include literals and identifiers.', 'Tokens in Java', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', '`aValue++;` is an example of which kind of Java statement?', '["A declaration statement", "An expression statement using the increment operator", "A control flow statement", "An object creation statement"]'::jsonb, 1, 'Any use of the increment (++) or decrement (--) operator, terminated with a semicolon, forms an expression statement -- here it is an increment statement.', 'Statements', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which Java relational operator tests whether two operands are equal?', '["=", "==", "!=", "<="]'::jsonb, 1, '== is the equivalence (equal-to) relational operator. A single = is the assignment operator, not a comparison. != tests nonequivalence, and <= tests less-than-or-equal.', 'Relational Operators', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Relational operators in Java evaluate the relationship between two operands and always produce a result of which type?', '["int", "boolean", "char", "String"]'::jsonb, 1, 'Relational operators (<, >, <=, >=, ==, !=) always produce a boolean result -- true or false -- describing the relationship between the two operand values.', 'Relational Operators', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'With the exception of == and !=, Java''s relational operators work with all primitive types except which one?', '["int", "double", "boolean", "char"]'::jsonb, 2, 'Relational operators such as <, >, <=, and >= work with all primitive types except boolean, since ''greater than'' or ''less than'' is not meaningful for true/false values; only == and != apply to boolean.', 'Relational Operators', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Given `int aValue = 30, bValue = 45;`, what is the value of the boolean expression `(aValue + 40) < (bValue * 2)`?', '["true", "false", "70", "90"]'::jsonb, 0, 'aValue + 40 = 30 + 40 = 70. bValue * 2 = 45 * 2 = 90. Since 70 < 90 is a true relationship, the expression evaluates to true.', 'Relational Operators', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Given `boolean fValue = false, tValue = false;` followed by `tValue = tValue | false;`, what is the resulting value of tValue?', '["true", "false", "0", "A compile-time error"]'::jsonb, 1, 'The logical OR of false and false is false, so tValue remains false after this statement.', 'Boolean Assignment Statement', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In Java, which statement below is a valid char assignment statement, given `char grade = '' '';` was already declared?', '["grade = \"A\";", "grade = ''A'';", "grade = A;", "grade == ''A'';"]'::jsonb, 1, 'A char literal in Java is written with single quotes, so `grade = ''A'';` correctly assigns the character A to the char variable grade. Double quotes denote a String literal, not a char, and would not compile here.', 'Char Assignment Statement', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In Java''s object-oriented programming model, what best describes an object?', '["A block of comments in the source code", "A software construct that has state and behavior, modelled on real-world things", "A reserved keyword of the language", "A file extension used for compiled programs"]'::jsonb, 1, 'Objects are software constructs with state (data) and behavior (methods), used to model real-world or conceptual things -- for example, a car can be modelled as an object with state (speed, fuel amount) and behavior (accelerate, brake).', 'Object Oriented Programming', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which OOP characteristic refers to the capability to hide data and instructions inside an object?', '["Inheritance", "Encapsulation", "Polymorphism", "Message Passing"]'::jsonb, 1, 'Encapsulation is the ability to hide an object''s data and instructions (its implementation) from the outside, exposing only what other objects need to interact with it.', 'Object Oriented Programming', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which OOP characteristic gives the ability to create one object from another, reusing its features?', '["Encapsulation", "Inheritance", "Garbage Collection", "Polymorphism"]'::jsonb, 1, 'Inheritance is the mechanism by which a new class (object type) can be created from an existing one, inheriting its features and allowing extension or specialization.', 'Object Oriented Programming', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Objects communicating with each other by invoking each other''s methods is described in the textbook as which OOP characteristic?', '["Message Passing", "Garbage Collection", "Polymorphism", "Inheritance"]'::jsonb, 0, 'Message Passing is the way objects communicate with each other, typically by one object invoking a method on another.', 'Object Oriented Programming', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which OOP feature automatically manages memory by destroying objects that are no longer in use by the program?', '["Polymorphism", "Encapsulation", "Garbage Collection", "Inheritance"]'::jsonb, 2, 'Garbage Collection is Java''s automatic memory-management feature: it identifies objects no longer referenced/used by the program and reclaims their memory automatically.', 'Object Oriented Programming', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which of the following is listed in the textbook as a genuine drawback of object-oriented programming, rather than a benefit?', '["Re-usability", "Code Sharing", "Increased program size, due to larger memory and disk space requirements", "Rapid Modeling"]'::jsonb, 2, 'Size is cited as a drawback of OOP: object-oriented programs tend to be larger than programs written in other paradigms, consuming more memory and disk space. Re-usability, Code Sharing, and Rapid Modeling are listed as benefits.', 'Object Oriented Programming', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which of the following is listed as a benefit, rather than a drawback, of object-oriented programming?', '["Greater effort required in the planning phase", "Larger program size", "Re-usability of previously developed and tested code", "Slower coding in the execution phase"]'::jsonb, 2, 'Re-usability is a benefit: because a program is written using previously developed code, you save on both testing and coding time. Effort and size are listed among OOP''s drawbacks.', 'Object Oriented Programming', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In the top-down, stepwise-refinement approach to algorithm development, what is the general strategy for handling a complex problem?', '["Write all the code first, then design the algorithm afterwards", "Break the problem down into a small number of major steps, then refine each major step into smaller, more detailed steps", "Skip algorithm design entirely and go straight to testing", "Solve the problem only using a single, unbroken block of code with no distinct steps"]'::jsonb, 1, 'Stepwise refinement outlines the major steps needed to solve a problem first, then refines each of those steps into smaller, more detailed sub-steps until each is simple enough to translate directly into code.', 'Algorithm Development', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'According to the textbook, what does an algorithm represent?', '["The exact syntax of a particular programming language", "A sequence of steps that solves a particular problem", "A type of computer hardware", "A file used only for storing program output"]'::jsonb, 1, 'An algorithm is the set of steps developed to solve a particular problem; different algorithms can be developed by different people to solve the same problem, provided each set of steps produces the same correct result.', 'Algorithm Development', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Two different programmers can develop two different algorithms for the same problem. What must be true of both algorithms for each to be considered correct?', '["They must use exactly the same variable names", "They must both solve the same problem, producing the same correct results", "They must be written in the same programming language", "They must have exactly the same number of steps"]'::jsonb, 1, 'Different algorithms can solve the same problem in different ways (different steps, different order), but for both to be considered valid solutions to the same problem, each must correctly solve it and produce the same correct results.', 'Algorithm Development', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Consider this pseudocode fragment: `Set count = 0` followed by a loop that does `Read a pair, X, Y` and `Set count = count + 1` until `count = n`. What does this fragment do?', '["It reads exactly one pair of values, X and Y, regardless of n", "It repeatedly reads pairs of values (X, Y) and counts how many pairs have been read, stopping once n pairs have been read", "It sorts n values in ascending order", "It deletes n values from a file"]'::jsonb, 1, 'count starts at 0 and increases by 1 each time a pair (X, Y) is read; the loop repeats reading pairs and incrementing count until count equals n, so it reads exactly n pairs, one at a time, and tracks how many have been read.', 'Algorithm Development', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Consider the Java code:
int n = 5;
double sumFact = 0;
for (int i = 1; i <= n; i++) {
    double fact = 1;
    for (int j = 1; j <= i; j++) fact *= j;
    sumFact += fact;
}
System.out.println(sumFact);
What value is printed?', '["15.0", "120.0", "153.0", "5913.0"]'::jsonb, 2, 'For each i from 1 to 5, the inner loop computes i! (fact), and the outer loop accumulates sumFact += fact -- so the program computes 1! + 2! + 3! + 4! + 5! = 1+2+6+24+120 = 153.', 'Problem Solving with Java', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'A Java program declares `Scanner sc = new Scanner(System.in);` and then calls `n = sc.nextInt();`. What is the purpose of this code?', '["To print n to the screen", "To read an integer value typed by the user at the console and store it in n", "To declare n as a String variable", "To close the input stream"]'::jsonb, 1, 'java.util.Scanner wrapped around System.in reads console input. sc.nextInt() specifically reads the next token from that input as an int, which is then stored in the variable n.', 'Problem Solving with Java', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In Java control structures, what is a ''selection structure'' used for?', '["To repeat a block of statements a fixed number of times", "To choose between two or more alternative courses of action based on a condition", "To declare the data type of a variable", "To import a package into a program"]'::jsonb, 1, 'Selection structures (if, if-else, switch) let a program choose among alternative paths of execution depending on whether a condition is true or false.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What is the output of the following Java code?
int x = 5;
if (x > 10) {
    System.out.println("A");
} else {
    System.out.println("B");
}', '["A", "B", "Nothing is printed", "A compile-time error occurs"]'::jsonb, 1, 'x is 5, and the condition x > 10 is false, so control goes to the else branch, printing B.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In a Java switch statement, what happens if a matching case''s block does not end with a `break` statement?', '["The program terminates immediately", "Execution falls through and continues into the statements of the next case, until a break or the end of the switch is reached", "A compile-time error always occurs", "The switch statement is simply skipped entirely"]'::jsonb, 1, 'Without a break, Java switch statements exhibit ''fall-through'': execution continues into the following case''s statements regardless of whether that case''s value matches, until a break is hit or the switch block ends.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What does the following code print?
int day = 3;
switch (day) {
    case 1: System.out.println("Mon"); break;
    case 2: System.out.println("Tue"); break;
    case 3: System.out.println("Wed"); break;
    default: System.out.println("Other");
}', '["Mon", "Tue", "Wed", "Other"]'::jsonb, 2, 'day equals 3, which matches `case 3:`, printing "Wed" and then breaking out of the switch.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'A `for` loop in Java is generally best suited for which kind of repetition?', '["Repetition where the exact number of iterations is known or countable in advance", "Repetition that must always execute the loop body at least once, regardless of the condition", "Repetition that never terminates", "Repetition that can only run backward from a starting index"]'::jsonb, 0, 'The for loop''s header (initialization; condition; update) is designed for counter-controlled repetition, where the number of iterations is known or can be computed in advance -- e.g. looping from i=0 to i<n.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What is the output of the following loop?
int sum = 0;
for (int i = 1; i <= 5; i++) {
    sum += i;
}
System.out.println(sum);', '["10", "15", "5", "20"]'::jsonb, 1, 'The loop adds 1+2+3+4+5 = 15 to sum, so 15 is printed.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What is the key difference between a `while` loop and a `do-while` loop in Java?', '["A while loop tests its condition before executing the loop body; a do-while loop executes the body once before testing the condition", "A do-while loop can never terminate", "A while loop always runs exactly once", "There is no difference; they are interchangeable in every case"]'::jsonb, 0, 'while checks its condition first, so if the condition is false on the first check, the body never executes. do-while executes the body first and checks the condition afterward, guaranteeing at least one execution of the body.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What is the output of the following code?
int count = 0;
do {
    System.out.print(count + " ");
    count++;
} while (count < 3);', '["0 1 2 ", "0 1 2 3 ", "1 2 3 ", "Nothing, because count starts at 0"]'::jsonb, 0, 'The do-while body runs first with count=0, printing 0, then count becomes 1. It repeats while count < 3: printing 1 (count becomes 2), printing 2 (count becomes 3), then the condition count < 3 is false and it stops. Output: 0 1 2.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In a Java `for` loop `for (int i = 0; i < 5; i++) { ... }`, how many times does the loop body execute?', '["4", "5", "6", "Infinite"]'::jsonb, 1, 'i starts at 0 and the loop continues while i < 5, so i takes the values 0,1,2,3,4 -- exactly 5 iterations -- before i becomes 5 and the condition fails.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What does the `break` statement do when executed inside a loop in Java?', '["It skips the current iteration only and continues with the next iteration", "It immediately terminates the loop entirely, and execution resumes at the statement after the loop", "It restarts the loop from the beginning", "It pauses the program until user input is given"]'::jsonb, 1, 'break immediately exits the innermost enclosing loop (or switch) entirely; control passes to the first statement after the loop, skipping any remaining iterations.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What does the `continue` statement do when executed inside a loop in Java?', '["It terminates the loop immediately, like break", "It skips the rest of the current iteration''s body and moves on to the loop''s next iteration/condition check", "It ends the entire program", "It has no effect inside loops"]'::jsonb, 1, 'continue skips any remaining statements in the current pass through the loop body and jumps directly to the loop''s update/condition check, proceeding to the next iteration rather than exiting the loop.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What is the output of this code?
for (int i = 1; i <= 5; i++) {
    if (i == 3) continue;
    System.out.print(i + " ");
}', '["1 2 3 4 5 ", "1 2 4 5 ", "1 2 3 4 ", "3 "]'::jsonb, 1, 'When i equals 3, continue skips the print statement for that iteration only, so 3 is never printed, but the loop still runs through i=1,2,4,5, printing each of the others: 1 2 4 5.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which control structure in Java repeats a block of code as long as a given boolean condition remains true, checking that condition before each execution of the body?', '["do-while", "while", "switch", "if-else"]'::jsonb, 1, 'A while loop evaluates its condition before every execution of the loop body; if the condition is false at the very start, the body may never execute at all.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What is wrong with using an unstructured ''goto''-like jump in modern structured programming, as contrasted with Java''s structured control constructs (if, switch, for, while, do-while)?', '["Nothing is wrong with it; it is preferred in Java", "It tends to make program flow harder to follow and reason about, which is why Java deliberately omits a goto statement in favour of structured constructs", "It executes faster than any loop", "It is required for every Java method"]'::jsonb, 1, 'Java is described as eliminating goto-style statements as part of keeping the language simple; structured control constructs (selection and iteration) make a program''s flow of control easier to follow, test, and reason about than unrestricted jumps.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which Java class in java.util is designed as a convenient wrapper around System.in, providing methods to read conventional data types (like int, double, and whole lines of text) directly from the keyboard?', '["BufferedReader", "Scanner", "PrintStream", "File"]'::jsonb, 1, 'The Scanner class (java.util.Scanner) wraps around System.in and provides methods such as next, nextInt, nextDouble, and nextBoolean to read typed data conveniently from the keyboard, without the programmer having to parse raw bytes.', 'Standard Input/Output', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which Scanner method is used to read the next token of input as an int value?', '["next()", "nextInt()", "nextLine()", "nextByte()"]'::jsonb, 1, 'nextInt() reads the next token from the Scanner''s input source and returns it as an int. next() returns a String, and nextByte() returns a byte, not an int.', 'Standard Input/Output', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which Scanner method reads the next token of input specifically as a String?', '["next()", "nextInt()", "nextDouble()", "nextBoolean()"]'::jsonb, 0, 'next() is the Scanner method that reads the next whitespace-delimited token and returns it as a String, rather than converting it to a numeric or boolean type.', 'Standard Input/Output', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which Scanner method would you use to read a value into a variable declared as `double`?', '["nextInt()", "nextDouble()", "nextFloat()", "nextLong()"]'::jsonb, 1, 'nextDouble() reads the next token and parses it as a double. nextFloat() would parse it as a float instead -- a different (narrower) primitive type, so it is not the correct match for a double variable.', 'Standard Input/Output', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which Scanner method would you use to read a value into a variable declared as `boolean`?', '["nextBoolean()", "next()", "nextByte()", "nextShort()"]'::jsonb, 0, 'nextBoolean() reads the next token and interprets it as a boolean value (true or false). The other listed methods return String, byte, and short respectively.', 'Standard Input/Output', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Before a Scanner object can be used to read from the keyboard, which of the following must be done first?', '["Import the java.util.Scanner class and create a Scanner object, typically wrapping System.in", "Nothing; Scanner is a built-in keyword, not a class", "Declare the program''s main method as private", "Import java.io.File and create a File object"]'::jsonb, 0, 'To use the Scanner class, the program must first import java.util.Scanner, then create a Scanner object (for example, `Scanner input = new Scanner(System.in);`) before calling any of its next-family methods to read input.', 'Standard Input/Output', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In `Scanner input = new Scanner(System.in);`, what is the role of System.in?', '["It is the source of input passed to the Scanner -- the standard input stream, normally the keyboard", "It is a method that prints text to the screen", "It is a class used only for reading files, not the keyboard", "It has no effect; it is only a comment"]'::jsonb, 0, 'System.in represents the standard input stream (normally connected to the keyboard). Passing it into the Scanner constructor tells the Scanner where to read its input from.', 'Standard Input/Output', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What is java.util.Scanner''s next() method''s return type for a value read from the keyboard, out of these choices, when nextInt() is NOT used?', '["int", "String", "double", "boolean"]'::jsonb, 1, 'Calling next() (without a following type name) always returns a String -- the plain next token of input, unconverted. The typed variants (nextInt, nextDouble, nextBoolean, etc.) exist precisely to hand back a converted primitive instead.', 'Standard Input/Output', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'System.out.println("Hello") is used to display output to the console. Which class does the object `System.out` behave as an instance of, according to the textbook?', '["Scanner", "PrintStream", "BufferedReader", "File"]'::jsonb, 1, 'System.out is defined as an object of PrintStream, a class that specifies a standard output stream that is open and ready to accept output data to the console, file, or any other output destination.', 'Standard Input/Output', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which of the following best describes what `System.out.println()` and `System.out.print()` have in common?', '["Both are methods of PrintStream used to write output through System.out", "Both read data from the keyboard", "print() writes to a file while println() writes to the screen", "They are unrelated methods from different classes"]'::jsonb, 0, 'Both println() and print() are methods of PrintStream, and System.out is accessed as an object of PrintStream, so both output methods are invoked through System.out. The difference between them is that println() adds a newline afterward and print() does not.', 'Standard Input/Output', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Consider this code:
import java.io.InputStreamReader;
import java.io.BufferedReader;
import java.io.IOException;
...
BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
String username = br.readLine();
What does br.readLine() do?', '["It reads a single character typed by the user", "It reads and returns one full line of text typed by the user, as a String", "It writes a line of text to the console", "It closes the input stream immediately"]'::jsonb, 1, 'BufferedReader''s readLine() method reads characters from the wrapped stream until it reaches a line terminator, and returns everything read as a single String -- a full line of input.', 'Standard Input/Output', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In the code `BufferedReader br = new BufferedReader(new InputStreamReader(System.in));`, why is System.in first wrapped in an InputStreamReader before being wrapped in a BufferedReader?', '["InputStreamReader converts the raw byte stream (System.in) into a character stream, which BufferedReader can then read efficiently line by line", "It is unnecessary; BufferedReader can wrap System.in directly with no InputStreamReader", "InputStreamReader deletes the input after reading it once", "This wrapping only works for writing files, not reading input"]'::jsonb, 0, 'System.in is a byte stream. InputStreamReader is a bridge that converts a byte stream into a character stream, and BufferedReader then wraps that character stream to read efficiently (e.g. a full line at a time via readLine()) -- exactly the byte-stream-to-character-stream-to-buffered-stream chain the textbook illustrates.', 'Standard Input/Output', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Why might a program using `BufferedReader.readLine()` need to catch or declare an IOException, unlike a program that only uses Scanner''s methods?', '["readLine() can throw a checked IOException, which the compiler requires the program to handle or declare, whereas the Scanner methods used in the textbook''s examples do not require this", "IOException only ever occurs when using Scanner, never BufferedReader", "Java forbids reading any input at all without an IOException handler", "IOException is thrown only when writing output, never when reading input"]'::jsonb, 0, 'readLine() is declared to throw IOException, a checked exception, so calling code must either catch it (e.g. in a try-catch block) or declare that it throws it -- this is why the textbook''s BufferedReader example wraps the read in a try block with a catch(IOException e) clause.', 'Standard Input/Output', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In Java, what is an instance variable?', '["A variable declared inside a method body only, existing just for that method call", "A variable declared in a class, outside any method, representing data that belongs to each object created from that class", "A keyword used to declare a class as public", "A method that returns no value"]'::jsonb, 1, 'An instance variable is declared within a class (but outside any method); each object (instance) of that class gets its own copy of the instance variable to hold its own state.', 'Classes, Objects and Methods', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Consider the class:
public class Account {
    private String name;
    public void setName(String name) {
        this.name = name;
    }
    public String getName() {
        return name;
    }
}
What is the purpose of the `this.name = name;` statement inside setName?', '["It assigns the method parameter''s value to the object''s own instance variable name, distinguishing the instance variable from the same-named parameter", "It creates a brand-new object called this", "It deletes the instance variable name", "It is a syntax error because this cannot be used with name"]'::jsonb, 0, 'Because the parameter is also named `name`, `this.name` explicitly refers to the current object''s instance variable, distinguishing it from the local parameter `name`. The statement copies the parameter''s value into the object''s own field.', 'Classes, Objects and Methods', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In the Account class example (private String name; with setName and getName methods), what is a ''get'' method conventionally used for?', '["To set/change the value of an instance variable", "To retrieve and return the current value of an instance variable to the caller", "To create a brand new object", "To delete an object from memory"]'::jsonb, 1, 'A get method (like getName()) is used to retrieve and return the current value of an instance variable to whoever called it, without allowing direct outside access to the variable itself.', 'Classes, Objects and Methods', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In the Account class example, what is a ''set'' method conventionally used for?', '["To retrieve the current value of an instance variable", "To assign or update the value of an instance variable, typically validating or processing the incoming value first", "To declare the class as public", "To print the class name to the console"]'::jsonb, 1, 'A set method (like setName(String name)) is used to assign a new value to an instance variable, taking the desired value in as a parameter.', 'Classes, Objects and Methods', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Given `private String name;` as an instance variable that is never explicitly initialized in the constructor, what value does it hold by default when an Account object is first created?', '["An empty string \"\"", "null", "0", "It causes a compile-time error"]'::jsonb, 1, 'Instance variables that are reference types (like String) and are not explicitly initialized default to null -- this is the ''default initial value'' the textbook specifically calls out, since a program that calls getName() before setName() has been called will see null.', 'Classes, Objects and Methods', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Consider:
Account myAccount = new Account();
What does the `new` keyword do in this statement?', '["It declares a variable named new", "It creates (instantiates) a new Account object in memory and returns a reference to it, which is assigned to myAccount", "It deletes the Account class", "It only compiles the Account class without creating an object"]'::jsonb, 1, 'The `new` keyword allocates memory for a new object of the specified class (here, Account), invokes its constructor, and returns a reference to the newly created object -- that reference is what gets stored in myAccount.', 'Classes, Objects and Methods', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Given the Account class from the textbook''s example, what would `myAccount.setName("Ada");` followed by `System.out.println(myAccount.getName());` print?', '["null", "Ada", "name", "An error, because setName has no return value"]'::jsonb, 1, 'setName("Ada") stores "Ada" into the object''s instance variable name via this.name = name. getName() then returns that stored value, so "Ada" is what gets printed.', 'Classes, Objects and Methods', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In a UML class diagram as described in the textbook, which compartment of the diagram lists the class''s attributes (instance variables)?', '["The top compartment", "The middle compartment", "The bottom compartment", "UML class diagrams do not show attributes"]'::jsonb, 1, 'A UML class diagram is divided into three compartments: the top holds the class''s name (centred, boldface), the middle lists the class''s attributes, and the bottom lists the class''s operations (methods).', 'Classes, Objects and Methods', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In a UML class diagram as described in the textbook, which compartment lists the class''s operations (methods)?', '["The top compartment", "The middle compartment", "The bottom compartment", "Methods are never shown in a class diagram"]'::jsonb, 2, 'The bottom compartment of a UML class diagram lists the class''s operations/methods, while the middle compartment lists its attributes and the top compartment holds the class name.', 'Classes, Objects and Methods', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'When a method call passes an argument to a method with parameters, what must be true of the number and types of the arguments, according to the textbook''s discussion of setName''s parameter?', '["The number of arguments in the call must match the number of parameters, and each argument''s type must be consistent with its corresponding parameter''s type", "Arguments never need to match parameter types, Java converts everything automatically", "Only the number of arguments matters; types are irrelevant", "Only the types matter; the number of arguments can differ freely"]'::jsonb, 0, 'A method call''s arguments must match the method''s parameter list in both count and type-compatibility: the number of arguments in the call must match the number of parameters in the method declaration, and each argument''s type must be consistent with the corresponding parameter''s declared type.', 'Classes, Objects and Methods', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'The textbook lists five major types of literals in Java. Which of the following is NOT one of them?', '["Integer literals", "Floating point literals", "Pointer literals", "Boolean literals"]'::jsonb, 2, 'The five types of literal the textbook lists are integer, floating point, character, string, and boolean literals. Java has no ''pointer literal'' -- Java deliberately does not expose raw pointers to the programmer.', 'Literals', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which of these is an example of a Java character literal, as opposed to a String literal?', '["\"A\"", "''A''", "A", "[A]"]'::jsonb, 1, 'A character literal is written with single quotes, e.g. ''A''. Double quotes ("A") denote a String literal instead -- a different type, even though it might contain a single character.', 'Literals', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', '3.5 and 345.6 are examples of which kind of Java literal?', '["Integer literals", "Floating point literals", "Character literals", "Boolean literals"]'::jsonb, 1, 'Values written with a decimal point, such as 3.5 and 345.6, are floating point literals -- they represent real numbers rather than whole numbers.', 'Literals', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'true and false are examples of which kind of Java literal?', '["Integer literals", "String literals", "Boolean literals", "Character literals"]'::jsonb, 2, 'true and false are the only two boolean literals in Java, representing the two possible logical values.', 'Literals', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', '34, 56, 12 and 9 are examples of which kind of Java literal?', '["Integer literals", "Floating point literals", "Boolean literals", "String literals"]'::jsonb, 0, 'Whole numbers with no decimal point, such as 34, 56, 12 and 9, are integer literals.', 'Literals', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'According to the textbook''s rules for Java identifiers, which of these is an INVALID identifier?', '["a_Value", "aValue", "2ndValue", "Thisisalongname"]'::jsonb, 2, 'Java identifiers must not start with a digit. 2ndValue begins with ''2'', so it is invalid; the other three are all legal (letters/underscore start, followed by allowed characters).', 'Identifiers', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which characters, besides letters, are Java identifiers permitted to contain, according to the textbook?', '["Only spaces", "Digits, the underscore, and the dollar sign", "Only punctuation marks", "Any character at all, including operators like + and -"]'::jsonb, 1, 'The textbook states Java identifiers can have alphabets, digits, and the underscore and dollar sign characters (e.g. a_Value, aValue) -- but they must not start with a digit.', 'Identifiers', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What are Java identifiers used for, according to the textbook?', '["Only for naming variables, and nothing else", "For naming classes, methods, variables, objects, labels, packages and interfaces in a program", "Only for writing comments", "Only for naming packages, never variables or classes"]'::jsonb, 1, 'Identifiers are programmer-defined words used broadly throughout a program: for naming classes, methods, variables, objects, labels, packages and interfaces.', 'Identifiers', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which of the following is good identifier-naming practice, per the textbook''s guidance?', '["Identifiers should be as cryptic and short as possible, regardless of meaning", "An identifier must be meaningful, easily understandable, and descriptive", "Identifiers must always be exactly one character long", "Identifiers should never describe what they represent"]'::jsonb, 1, 'The textbook specifically states that an identifier must be meaningful, easily understandable and descriptive -- good naming makes code easier to read and maintain.', 'Identifiers', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'According to the textbook, approximately how many reserved keywords does the Java language have?', '["10", "50", "500", "5"]'::jsonb, 1, 'The textbook states Java has reserved 50 words as keywords -- these have specific meaning to the language and cannot be used as identifiers (variable, class, or method names).', 'Keywords', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which of the following is a reserved Java keyword, and therefore cannot be used as a variable name?', '["myVariable", "abstract", "counter", "total_sum"]'::jsonb, 1, 'abstract is one of Java''s reserved keywords (used to declare abstract classes/methods) and has specific meaning to the compiler, so it cannot be used as an identifier. The other three are all ordinary, legal identifier names.', 'Keywords', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which of the following is NOT a Java keyword?', '["static", "package", "printnl", "private"]'::jsonb, 2, 'printnl is not a real Java keyword or method (the correct output method is println, spelled differently). static, package, and private are all genuine reserved Java keywords.', 'Keywords', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Why can''t a Java keyword such as ''class'' or ''if'' be used as the name of a variable?', '["Keywords are reserved words with specific meaning to the language, so using one as an identifier would create ambiguity the compiler cannot resolve", "There is no actual restriction; any keyword can be freely reused as a variable name", "Keywords can be used as variable names only inside comments", "Only uppercase keywords are reserved; lowercase ones are free to reuse"]'::jsonb, 0, 'Keywords are reserved specifically because they already carry a fixed meaning in the Java language''s grammar; allowing them to double as identifiers would make programs ambiguous or impossible for the compiler to parse correctly.', 'Keywords', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which of these words is a Java keyword used to declare that a variable''s value cannot be changed after initialization?', '["static", "final", "void", "import"]'::jsonb, 1, 'final is the Java keyword used to declare constants and prevent reassignment (also used to prevent method overriding or class extension). static, void and import all have different, unrelated meanings.', 'Keywords', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'According to the textbook''s classification, which of the following is an Integer Arithmetic Operator?', '["%", "&&", "||", "!"]'::jsonb, 0, 'The remainder/modulus operator % is listed among the Integer Arithmetic Operators (+, -, *, /, %), which operate on data types classified as integer. &&, || and ! are Boolean Arithmetic Operators instead.', 'Operators', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which of the following operators is listed by the textbook among the Real Arithmetic Operators, usable on floating-point data types?', '["%", "/", "&", "|"]'::jsonb, 1, 'The Real Arithmetic Operators the textbook lists are +, -, *, and / -- notably NOT %, which is grouped only with the Integer Arithmetic Operators in this textbook''s classification.', 'Operators', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which of these operators is classified by the textbook as a Boolean Arithmetic Operator?', '["+", "%", "&&", "/"]'::jsonb, 2, 'The Boolean Arithmetic Operators the textbook lists are |, ||, &, && and !, used to operate on the boolean data type. +, % and / are arithmetic operators for numeric types instead.', 'Operators', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'According to the textbook, an operator that takes only one operand (such as !) is classified as what kind of operator?', '["A binary operator", "A unary operator", "A ternary operator", "A relational operator"]'::jsonb, 1, 'An operator taking only a single operand -- the textbook''s example is the logical NOT, ! -- is called a unary operator. Operators taking two operands, like + or &&, are called binary operators.', 'Operators', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'According to the textbook, an operator such as + or && that takes two operands is classified as what kind of operator?', '["A unary operator", "A binary operator", "A postfix operator", "A literal operator"]'::jsonb, 1, 'Operators that act on two operands -- such as +, -, *, /, %, |, ||, & and && -- are described as binary operators, in contrast to unary operators like ! which act on only one operand.', 'Operators', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What does the modulus (%) operator return when applied to two integers, e.g. `17 % 5`?', '["The quotient of the division (3)", "The remainder of the division (2)", "The sum of the two numbers (22)", "The product of the two numbers (85)"]'::jsonb, 1, 'The % operator returns the remainder left over after integer division. 17 divided by 5 gives a quotient of 3 with remainder 2 (since 5*3=15 and 17-15=2), so 17 % 5 evaluates to 2.', 'Operators', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What is the value of `23 % 4` in Java?', '["5", "3", "1", "0"]'::jsonb, 1, '23 divided by 4 gives a quotient of 5, since 4*5=20; the remainder is 23-20=3. So 23 % 4 evaluates to 3.', 'Operators', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What is the result of the integer division `17 / 5` in Java (both operands are int)?', '["3.4", "3", "2", "4"]'::jsonb, 1, 'When both operands of / are integers, Java performs integer division, discarding any fractional part: 17 / 5 evaluates to 3 (not 3.4, which would only occur if at least one operand were a floating-point type).', 'Operators', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Given `boolean fValue = false, tValue = false;` then `fValue = fValue & tValue;`, what is the resulting value of fValue?', '["true", "false", "0", "A compile-time error"]'::jsonb, 1, 'The logical AND of false and false is false, so fValue remains false after this assignment.', 'Boolean Assignment Statement', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Given `double cValue = 34.76, dValue = 87.4;`, what does the expression `cValue + dValue == cValue` evaluate to?', '["true", "false", "122.16", "A compile-time error"]'::jsonb, 1, 'cValue + dValue = 34.76 + 87.4 = 122.16, which is not equal to cValue (34.76) alone, so the equality comparison cValue + dValue == cValue evaluates to false.', 'Relational Operators', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which of the following best distinguishes an algorithm from a Java program that implements it?', '["An algorithm is the language-independent sequence of steps that solves a problem; a program is one specific implementation of that algorithm in a particular language such as Java", "There is no difference between the two terms", "An algorithm can only exist after the program has already been written and tested", "A program always contains fewer steps than its algorithm"]'::jsonb, 0, 'An algorithm is the abstract sequence of steps that solves a problem, independent of any programming language; a Java program is a concrete realization of that algorithm''s steps as compilable, executable Java code.', 'Algorithm Development', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In the top-down design approach, after outlining a problem''s major steps as big rectangles in a diagram, what is the next stage of refinement typically called?', '["Concatenating each of the major steps into a single rectangle", "Refining each major step into smaller, more detailed sub-steps", "Deleting the major steps and starting over from scratch", "Converting the whole algorithm directly into machine code with no further design"]'::jsonb, 1, 'After outlining the major steps, each one is refined into smaller, more detailed steps -- for instance, main step 1 might be refined into sub-steps 1.1, 1.2, 1.3, and so on -- continuing until each step is simple enough to code directly.', 'Algorithm Development', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Human Computer Interface (HCI) design, as described in the textbook''s discussion of problem solving, is primarily concerned with what?', '["Choosing an appropriate interface for good interaction between the user and the program during execution, aiming for user-friendliness", "Optimizing a program''s memory usage only", "Selecting which programming language to use for a project", "Writing comments for other programmers to read"]'::jsonb, 0, 'HCI design concerns choosing an appropriate interface between the user and the program during execution, with the goal of making the program user-friendly -- it involves the use of input and output statements and, where relevant, graphical user interfaces.', 'Algorithm Development', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Program Structure Design, as described in the textbook, focuses on the choice of which programming construct or control structure to use. What is the stated aim of this design consideration?', '["To transfer control from one part of the program to another in a logical, orderly manner, making the program easy to read, write, and debug", "To make the program as long and complex as possible", "To avoid using any control structures at all", "To ensure the program never uses variables"]'::jsonb, 0, 'Program Structure Design is about choosing the relevant control structure to transfer control between parts of a program logically and in order, with the explicit aim of making the program easy to read, easy to write, and easy to debug -- which is also why the textbook says the goto statement must be avoided.', 'Algorithm Development', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Why does the textbook advise against using a goto-style statement when designing a program''s structure?', '["Because it makes a program difficult to read, write, understand and debug", "Because Java requires every program to use at least one goto", "Because goto statements execute more slowly than any loop", "Because goto only works with floating-point variables"]'::jsonb, 0, 'The textbook states that the use of a goto statement must be avoided because it makes a program difficult to read, write, understand, and debug -- structured control constructs are preferred for exactly this reason.', 'Algorithm Development', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Consider this Java switch statement, adapted from the textbook''s own letter-grade example:
int score = 90;
int selector = score / 10;
char Grade;
switch (selector) {
    case 10:
    case 9:
    case 8:
    case 7: Grade = ''A''; break;
    case 6: Grade = ''B''; break;
    case 5: Grade = ''C''; break;
    case 4: Grade = ''D''; break;
    default: Grade = ''F''; break;
}
What value does Grade end up holding?', '["''A''", "''B''", "''F''", "''C''"]'::jsonb, 0, 'selector = 90 / 10 = 9 (integer division). Execution jumps to case 9, which has no statements of its own, so it falls through case 8 (also empty) into case 7''s action, setting Grade = ''A'', then breaking. This is exactly the fall-through behaviour the textbook''s own grading example demonstrates.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Using the same switch statement (cases 10,9,8,7 fall through to Grade=''A''; case 6 sets ''B''; case 5 sets ''C''; case 4 sets ''D''; default sets ''F''), if score = 39, what value does Grade end up holding?', '["''D''", "''F''", "''C''", "''A''"]'::jsonb, 1, 'selector = 39 / 10 = 3 (integer division truncates). There is no case labelled 3 among 10,9,8,7,6,5,4, so execution goes to the default branch, setting Grade = ''F''.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Using the same switch statement, if score = 65, what value does Grade end up holding?', '["''A''", "''B''", "''C''", "''F''"]'::jsonb, 1, 'selector = 65 / 10 = 6 (integer division). This matches case 6 exactly, which sets Grade = ''B'' and then breaks -- no fall-through occurs here since case 6 has its own break.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In the textbook''s switch statement rules, what kind of values can the case labels (value_1, ..., value_N) contain?', '["Only constant expressions -- they cannot contain variables", "Any variable or expression, including ones that change at runtime", "Only String values, never numbers", "Only boolean expressions"]'::jsonb, 0, 'The textbook explicitly states that switch case values cannot contain variables -- only constant expressions are allowed as case labels.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'According to the textbook''s semantics for the while loop, what happens if the loop-continuation-condition evaluates to False the very first time it is tested?', '["The loop body executes exactly once before the loop ends", "The loop body is skipped entirely, and execution goes straight to the statement(s) following the while loop", "The program crashes", "The condition is tested a second time automatically before deciding"]'::jsonb, 1, 'Per the textbook''s stated semantics, if the loop-continuation-condition is tested and found False, the loop body is not executed at all -- the statement(s), if any, immediately following the while loop''s tail are executed instead.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Consider a while loop implementing division by repeated subtraction:
int num1 = 17, num2 = 5, quotient = 0;
while (num1 > num2) {
    num1 -= num2;
    quotient += 1;
}
What are the final values of quotient and num1 after this loop finishes?', '["quotient = 3, num1 = 2", "quotient = 3, num1 = 17", "quotient = 4, num1 = -3", "quotient = 2, num1 = 7"]'::jsonb, 0, 'Iteration 1: 17>5 true, num1=12, quotient=1. Iteration 2: 12>5 true, num1=7, quotient=2. Iteration 3: 7>5 true, num1=2, quotient=3. Iteration 4: 2>5 false, loop stops. Final: quotient=3 (the number of times 5 was subtracted), num1=2 (the remainder) -- this is exactly the repeated-subtraction division technique the textbook''s own while-loop example demonstrates.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In the same repeated-subtraction while loop pattern, with `int num1 = 20, num2 = 6, quotient = 0;`, what are the final values of quotient and num1?', '["quotient = 3, num1 = 2", "quotient = 4, num1 = -4", "quotient = 3, num1 = 6", "quotient = 2, num1 = 8"]'::jsonb, 0, 'Iteration 1: 20>6 true, num1=14, quotient=1. Iteration 2: 14>6 true, num1=8, quotient=2. Iteration 3: 8>6 true, num1=2, quotient=3. Iteration 4: 2>6 false, stop. Final: quotient=3, num1=2 -- matching 20 = 6*3 + 2.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What is the output of the following code?
int x = 7;
String result = (x > 5) ? "High" : "Low";
System.out.println(result);', '["High", "Low", "true", "7"]'::jsonb, 0, 'The conditional (ternary) expression `boolean-expression ? expression1 : expression2` evaluates expression1 if the boolean-expression is true. Since x > 5 (7 > 5) is true, result is assigned "High", which is what gets printed.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What is the output of the following code?
int score = 3;
String result = (score > 5) ? "Pass" : "Fail";
System.out.println(result);', '["Pass", "Fail", "3", "false"]'::jsonb, 1, 'score > 5 (3 > 5) is false, so the conditional expression evaluates to its second operand, "Fail", which is assigned to result and printed.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What is the output of this nested loop?
for (int i = 1; i <= 2; i++) {
    for (int j = 1; j <= 3; j++) {
        System.out.print(i * j + " ");
    }
}', '["1 2 3 2 4 6 ", "1 2 3 4 5 6 ", "2 4 6 1 2 3 ", "1 4 2 6 3 6 "]'::jsonb, 0, 'For i=1: j=1,2,3 gives products 1,2,3. For i=2: j=1,2,3 gives products 2,4,6. Printed in order: 1 2 3 2 4 6.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What is the output of the following code?
int total = 0;
for (int i = 1; i <= 4; i++) {
    if (i % 2 == 0) {
        total += i;
    }
}
System.out.println(total);', '["4", "6", "10", "2"]'::jsonb, 1, 'i takes values 1,2,3,4. i % 2 == 0 is true for i=2 and i=4 only, so total = 2 + 4 = 6.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What is the output of this code?
int n = 4;
while (n > 0) {
    System.out.print(n + " ");
    n--;
}', '["4 3 2 1 ", "4 3 2 1 0 ", "0 1 2 3 4 ", "3 2 1 0 "]'::jsonb, 0, 'The loop starts at n=4 (4>0 true, prints 4, n becomes 3), continues printing 3, 2, 1 (each time n>0 is true before decrementing), and stops once n becomes 0 (0>0 is false) -- so it prints 4 3 2 1 and never prints 0.', 'Control Structures', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which Scanner method would correctly read a value into a variable declared `long total;`?', '["nextInt()", "nextLong()", "nextShort()", "next()"]'::jsonb, 1, 'nextLong() reads the next token and parses it specifically as a long value, matching the declared type of the variable. Using nextInt() to fill a long would compile (via widening) only if you also cast/assign appropriately, but nextLong() is the correct, direct match.', 'Standard Input/Output', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Which Scanner method would correctly read a value into a variable declared `byte flag;`?', '["nextByte()", "nextInt()", "next()", "nextBoolean()"]'::jsonb, 0, 'nextByte() reads the next token and parses it as a byte, matching the byte-typed variable directly, per the textbook''s Scanner method table.', 'Standard Input/Output', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'According to the textbook, what must be done before a program can use any of Scanner''s methods (like nextInt or next)?', '["Import the class using `import java.util.Scanner;`, then create a Scanner object (e.g. wrapping System.in)", "Nothing at all is required; Scanner methods work without any setup", "The program must be run without a main method", "Only System.out needs to be imported"]'::jsonb, 0, 'The textbook''s own summary of ''how do we make use of the Scanner class'' lists: import the class using java.util.Scanner, create a scanner object, and finally use the scanner object to read input.', 'Standard Input/Output', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Why does the textbook say the System.in package ''cannot be readily used as it is, without some form of modification'' for reading input?', '["Because System.in on its own only provides a raw byte stream, so it must be wrapped (e.g. by a Scanner or a Reader) before typed or line-based data can be conveniently read from it", "Because System.in does not exist in Java", "Because System.in can only write output, never read input", "Because only File objects can be used for input in Java"]'::jsonb, 0, 'System.in is a raw InputStream. To read from many different sources conveniently and to obtain typed data (ints, whole lines, etc.), it has to be wrapped -- for example, in a Scanner, or in an InputStreamReader chained into a BufferedReader.', 'Standard Input/Output', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What is System.out, according to the textbook''s description in the Standard Output section?', '["A method that reads keyboard input", "An object of PrintStream that specifies a standard output stream, open and ready to accept output data to the console, a file, or other destinations", "A keyword reserved for declaring classes", "A type of loop construct"]'::jsonb, 1, 'System.out is defined as an object of PrintStream -- a standard output stream that is open and ready for writing output, whose actual destination (console, file, etc.) depends on the host environment.', 'Standard Input/Output', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'print() and println() are both methods available through System.out because System.out is an object of which class?', '["Scanner", "BufferedReader", "PrintStream", "InputStreamReader"]'::jsonb, 2, 'print() and println() are methods of PrintStream, and since System.out is defined as a PrintStream object, both methods are accessible through it.', 'Standard Input/Output', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Consider:
try {
    BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
    System.out.println("enter the username");
    String username = br.readLine();
    System.out.println("Hello " + username + " Welcome to Abuja");
} catch(IOException e) {
    System.out.println("entered wrong value");
}
If the user types ''China'' and presses Enter, what is printed?', '["enter the username\nHello China Welcome to Abuja", "entered wrong value", "Hello  Welcome to Abuja", "China"]'::jsonb, 0, 'The program first prints the prompt "enter the username", then reads the line "China" into username via readLine(), and finally prints "Hello China Welcome to Abuja" -- matching the textbook''s own worked BufferedReader/InputStreamReader example.', 'Standard Input/Output', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In the chain `new BufferedReader(new InputStreamReader(System.in))`, which class is the innermost, directly wrapping the raw System.in byte stream?', '["BufferedReader", "InputStreamReader", "Scanner", "PrintStream"]'::jsonb, 1, 'InputStreamReader is constructed directly around System.in in this chain, converting the raw byte stream into a character stream. BufferedReader is then constructed around that InputStreamReader to add efficient, line-based reading via readLine().', 'Standard Input/Output', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In the textbook''s Account class example, `private String name;` is declared as an instance variable. Why is it declared `private` rather than `public`?', '["So that no method anywhere, including the class''s own methods, can ever access it", "So that it cannot be accessed directly from outside the class -- other classes must use the class''s own public methods (like getName/setName) to read or modify it", "private has no real effect in Java and is purely decorative", "So that it is automatically initialized to a random value"]'::jsonb, 1, 'Declaring an instance variable private restricts direct access to it from outside the class, enforcing that other code must go through the class''s own public methods (such as getName and setName) to read or update it -- a core encapsulation practice.', 'Classes, Objects and Methods', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In the Account class, `public void setName(String name)` and `public String getName()` are declared `public`. What does this allow?', '["These methods can be called from outside the class, by any code that holds a reference to an Account object", "These methods can only ever be called from inside the Account class itself", "public methods cannot take parameters", "public methods cannot return a value"]'::jsonb, 0, 'Declaring a method public makes it part of the class''s externally accessible interface -- other code (such as the AccountTest class in the textbook''s example) can call setName and getName on an Account object it holds a reference to.', 'Classes, Objects and Methods', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'Consider:
Account myAccount = new Account();
System.out.println(myAccount.getName());
What is printed, given that setName was never called on myAccount?', '["An empty string", "null", "0", "A compile-time error, because getName has no argument"]'::jsonb, 1, 'The instance variable name is never explicitly initialized, so it holds its default value for a reference type, which is null. getName() simply returns that default, so null is printed.', 'Classes, Objects and Methods', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'In the textbook''s AccountTest class, `Scanner input = new Scanner(System.in);` is created, then `String theName = input.nextLine();` reads user input, and finally `myAccount.setName(theName);` is called. What is the overall effect of these three lines?', '["They read a line of text typed by the user and store it as the name inside the myAccount object", "They create a brand-new Account class from scratch", "They delete the existing value of myAccount''s name", "They print the Account class''s source code to the screen"]'::jsonb, 0, 'A Scanner is created to read keyboard input, nextLine() reads a full line of text typed by the user into theName, and setName(theName) then stores that value inside myAccount''s private name instance variable.', 'Classes, Objects and Methods', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'What is the relationship between a class and an object in Java, as illustrated by Account and myAccount in the textbook''s example?', '["A class and an object are exactly the same thing, just different names for it", "A class (like Account) is a blueprint/template; an object (like myAccount) is a specific instance created from that blueprint using new", "An object can exist without any class ever being defined", "A class can only ever have one object created from it, ever"]'::jsonb, 1, 'Account is the class -- the template describing what data (name) and behaviour (setName/getName) every Account will have. myAccount is one specific object (instance) of that class, created using the new keyword; a program can create many separate Account objects from the same class.', 'Classes, Objects and Methods', false, 'first', 2),
  ('cos-201-java-programming', 'COS 201: Computer Programming I (Java)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences, Faculty of Agriculture', 'Computer Science', '200 Level', 'If a class Account has two objects created from it, `Account accA = new Account(); Account accB = new Account();`, and accA.setName("Ada") is called but accB.setName is never called, what does accB.getName() return?', '["\"Ada\"", "null", "\"accB\"", "An exception is always thrown"]'::jsonb, 1, 'Each object has its own independent copy of the instance variable name. Setting accA''s name to "Ada" has no effect on accB''s own name, which remains at its uninitialized default value, null.', 'Classes, Objects and Methods', false, 'first', 2);
