-- Additional PHY 122 CBT questions: mirror/reflection problems mined from
-- a short supplementary set (14 questions), appended to the existing
-- 82-question bank. Does not touch prior rows.
--
-- All numeric answers independently verified with sympy using the mirror
-- equation 1/do + 1/di = 1/f (concave f>0, convex f<0; real di>0, virtual
-- di<0; m = -di/do), not trusted from the source's own printed options.

insert into public.cbt_questions
  (subject_id, subject_name, institution, faculty, department, level,
   question, options, correct_index, explanation, topic, is_general,
   semester, units)
values
  ('phy-122-heat-waves-optics', 'PHY 122: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'What is the nature of the image produced by a convex mirror, irrespective of the position of the object from the mirror?', '["Virtual, erect and diminished", "Virtual, erect and magnified", "Virtual, inverted and diminished", "Real, inverted and diminished"]'::jsonb, 0, 'A convex mirror always diverges reflected rays, so the image is always virtual (formed behind the mirror), erect, and diminished, regardless of how far the object is.', 'Reflection, refraction, mirrors and lenses', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 122: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A man stands $50 \, \text{cm}$ from a concave mirror with a radius of curvature of $10 \, \text{cm}$. Find the position of the image and the magnification.', '["$5.56 \\, \\text{cm}$, $0.11$", "$6.65 \\, \\text{cm}$, $0.12$", "$7.55 \\, \\text{cm}$, $0.13$", "$7.80 \\, \\text{cm}$, $0.14$"]'::jsonb, 0, 'Focal length $f = R/2 = 5 \, \text{cm}$. From $\dfrac{1}{d_o} + \dfrac{1}{d_i} = \dfrac{1}{f}$: $\dfrac{1}{d_i} = \dfrac{1}{5} - \dfrac{1}{50}$, giving $d_i = 5.56 \, \text{cm}$. The magnification is $m = -d_i/d_o = -5.56/50 = -0.11$ (magnitude $0.11$).', 'Reflection, refraction, mirrors and lenses', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 122: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Where must an object be placed with respect to a convex mirror of focal length $30 \, \text{cm}$, in order to obtain an image one-third as far behind the mirror as the object is in front of it?', '["$60.00 \\, \\text{cm}$", "$50.00 \\, \\text{cm}$", "$65.00 \\, \\text{cm}$", "$55.00 \\, \\text{cm}$"]'::jsonb, 0, 'For a convex mirror $f = -30 \, \text{cm}$, and the virtual image distance is $d_i = -d_o/3$. Substituting into $\dfrac{1}{d_o} + \dfrac{1}{d_i} = \dfrac{1}{f}$ gives $\dfrac{1}{d_o} - \dfrac{3}{d_o} = -\dfrac{1}{30}$, i.e. $-\dfrac{2}{d_o} = -\dfrac{1}{30}$, so $d_o = 60 \, \text{cm}$.', 'Reflection, refraction, mirrors and lenses', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 122: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'An object $5 \, \text{cm}$ high is placed $20 \, \text{cm}$ in front of a concave mirror so that it produces an image $60 \, \text{cm}$ from the mirror. Find the height of this image.', '["$15.00 \\, \\text{cm}$", "$16.00 \\, \\text{cm}$", "$17.00 \\, \\text{cm}$", "$18.00 \\, \\text{cm}$"]'::jsonb, 0, 'The magnification is $m = -d_i/d_o = -60/20 = -3$. The image height is $h_i = m \cdot h_o = -3 \times 5 = -15 \, \text{cm}$, so the image is $15 \, \text{cm}$ high (inverted).', 'Reflection, refraction, mirrors and lenses', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 122: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'An object $5 \, \text{cm}$ in height is placed $10 \, \text{cm}$ from a curved mirror and produces a virtual, upright image of height $6.5 \, \text{cm}$. Where is the image located, and what type of mirror is this?', '["$-13.00 \\, \\text{cm}$, concave mirror", "$-14.00 \\, \\text{cm}$, concave mirror", "$-13.00 \\, \\text{cm}$, convex mirror", "$-14.00 \\, \\text{cm}$, convex mirror"]'::jsonb, 0, 'Since the image is upright, the magnification is positive: $m = h_i/h_o = 6.5/5 = 1.3$. Then $d_i = -m \cdot d_o = -1.3 \times 10 = -13.00 \, \text{cm}$ (virtual, behind the mirror). A magnification greater than $1$ for an upright virtual image only occurs when the object is inside the focal length of a concave mirror.', 'Reflection, refraction, mirrors and lenses', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 122: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Light rays strike a plane mirror at an angle of $35°$ measured from the normal to the surface. Find the angle between the incident and reflected rays.', '["$70°$", "$60°$", "$80°$", "$50°$"]'::jsonb, 0, 'By the law of reflection, the angle of reflection equals the angle of incidence, both measured from the normal. The angle between the incident and reflected rays is therefore $2 \times 35° = 70°$.', 'Reflection, refraction, mirrors and lenses', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 122: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'When an object is placed between the principal focus of a concave mirror and the mirror itself, the image formed is:', '["Virtual, erect and magnified", "Real, erect and magnified", "Virtual, inverted and magnified", "Virtual, erect and diminished"]'::jsonb, 0, 'For an object inside the focal length of a concave mirror, the reflected rays diverge and appear to come from behind the mirror, producing a virtual, erect, magnified image.', 'Reflection, refraction, mirrors and lenses', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 122: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Which of the following is TRUE about the essential parameters of curved mirrors?', '["The principal axis is the line through the pole and centre of curvature, dividing the mirror into two symmetric halves", "The pole is the centre of the sphere from which the mirror is cut", "The radius of curvature is the distance from the principal focus to the pole of the mirror", "A real image cannot be received on a screen, whereas a virtual image can"]'::jsonb, 0, 'The pole is a point on the mirror''s surface, not the centre of the sphere (that''s the centre of curvature); the radius of curvature is twice the focal length, measured from the centre of curvature to the pole; and it is real images (not virtual ones) that can be received on a screen. The principal axis correctly divides the mirror into two symmetric halves.', 'Reflection, refraction, mirrors and lenses', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 122: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'An object is placed in front of a convex mirror of focal length $15 \, \text{cm}$. If the (virtual) image forms $10 \, \text{cm}$ from the mirror, calculate the object distance.', '["$30.00 \\, \\text{cm}$", "$25.00 \\, \\text{cm}$", "$35.00 \\, \\text{cm}$", "$40.00 \\, \\text{cm}$"]'::jsonb, 0, 'For a convex mirror $f = -15 \, \text{cm}$, and the image is virtual so $d_i = -10 \, \text{cm}$. From $\dfrac{1}{d_o} = \dfrac{1}{f} - \dfrac{1}{d_i} = -\dfrac{1}{15} - \left(-\dfrac{1}{10}\right) = \dfrac{1}{30}$, so $d_o = 30.00 \, \text{cm}$.', 'Reflection, refraction, mirrors and lenses', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 122: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'An object is placed at infinity in front of a concave mirror. Where will the image be formed, and what is its nature?', '["At the principal focus; real, diminished and inverted", "At the centre of curvature; real, magnified and inverted", "At the principal focus; virtual, diminished and erect", "At the centre of curvature; real, diminished and inverted"]'::jsonb, 0, 'As the object distance goes to infinity, $1/d_o \to 0$, so $d_i \to f$: the image forms at the principal focus. Rays from a very distant object converge to essentially a point there, giving a real, greatly diminished, inverted image.', 'Reflection, refraction, mirrors and lenses', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 122: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Which of the following best distinguishes opaque, transparent and translucent materials?', '["Opaque materials block all light; transparent materials let light pass through clearly (e.g. glass, water); translucent materials let some light through but scatter it (e.g. frosted glass, tissue paper)", "Opaque materials let all light through; transparent materials block all light; translucent materials reflect all light", "All three material types transmit light equally, differing only in colour", "Opaque materials only exist as liquids, transparent materials only as gases, and translucent materials only as solids"]'::jsonb, 0, 'Opaque materials (e.g. wood, metal) block light entirely; transparent materials (e.g. clear glass, water) transmit light with little scattering so objects behind them can be seen clearly; translucent materials (e.g. frosted glass, wax paper) transmit some light but scatter it, so objects behind them appear blurred.', 'Reflection, refraction, mirrors and lenses', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 122: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'What is the key distinguishing feature between a real image and a virtual image?', '["A real image is formed by actually converging light rays and can be captured on a screen; a virtual image is formed where rays only appear to diverge from, and cannot be captured on a screen", "A real image is always larger than the object; a virtual image is always smaller", "A real image only forms in convex mirrors; a virtual image only forms in concave mirrors", "There is no physical difference; the terms are interchangeable"]'::jsonb, 0, 'A real image forms where reflected (or refracted) light rays actually converge and cross, so it can be projected onto a screen. A virtual image forms where rays only appear to diverge from when traced backward -- no light actually passes through that point, so it cannot be captured on a screen (only seen by looking into the mirror).', 'Reflection, refraction, mirrors and lenses', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 122: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Why is the principal focus of a convex mirror described as a ''virtual focus''?', '["Because parallel rays striking a convex mirror diverge after reflection, and only appear to originate from a point behind the mirror rather than actually passing through it", "Because a convex mirror has no focal point at all", "Because the focus of a convex mirror can be reached by real light rays, unlike a concave mirror", "Because the term is simply a historical naming convention with no physical basis"]'::jsonb, 0, 'In a convex mirror, incoming parallel rays reflect outward (diverging). No real light ever actually meets behind the mirror; the reflected rays only appear to diverge from a common point behind the mirror when traced backward, which is why that point is called a virtual focus.', 'Reflection, refraction, mirrors and lenses', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 122: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A distant object is brought towards a concave spherical mirror, from infinity down to very close to the mirror. How do the size and nature of its image change?', '["The image starts small, real and inverted at the focus; grows while remaining real and inverted as the object passes the centre of curvature and approaches the focus; then, once the object is inside the focal length, the image becomes virtual, erect and magnified", "The image stays exactly the same size and nature throughout, since concave mirrors always produce identical images", "The image is virtual and diminished the entire time, only becoming real when the object touches the mirror", "The image disappears entirely once the object passes the centre of curvature"]'::jsonb, 0, 'With the object at infinity the image is a tiny, real, inverted point at the focus. As the object moves inward past the centre of curvature toward the focus, the real, inverted image grows steadily larger and moves farther from the mirror. Once the object crosses inside the focal length, no real image can form; instead a virtual, erect, magnified image appears behind the mirror.', 'Reflection, refraction, mirrors and lenses', false, 'second', 3);
