-- =============================================================================
-- University of Nigeria, Nsukka -- Faculty of Engineering
-- Department of Agricultural and Bioresources Engineering
-- Five-Year Standard Undergraduate B.Eng Degree Programme (Revised 2017)
-- =============================================================================
-- SOURCE: this file supersedes the earlier photo-transcribed version. It is
-- rebuilt from the official "Revised Five-Year Standard Undergraduate
-- Academic Programme in Agricultural & Bioresources Engineering" (2017,
-- Senate-approved 3 July 2017), a 28-page PDF with a real text layer,
-- published at:
-- https://engineering.unn.edu.ng/wp-content/uploads/sites/4/2023/05/ABE-Revised-UG-Programme-pdf.pdf
-- 110 rows.
--
-- VERIFICATION: every semester in Years 1-4 (and every option in Year 5)
-- was checksummed against this PDF's own printed "Total:" line before being
-- accepted. The one exception is documented below.
--
-- HOW THE TABLES WERE READ: this PDF's underlying text stream does not
-- follow visual reading order for its two-box-per-page layout -- a page's
-- "Major Courses" list can appear in the extracted text AFTER the "Required
-- Ancillary Courses" list that visually follows it, and a naive linear
-- extraction merges one semester's leftover elective row into the next
-- semester's major-course block. Every semester below was reconstructed
-- from each word's actual page coordinates (not raw text order) before
-- being checksummed, specifically for Third Year second semester, Fourth
-- Year, and all four Fifth-Year option tables.
--
-- A GENUINE ARITHMETIC ERROR, CONFIRMED IN TWO INDEPENDENT SOURCES: Fourth
-- Year first semester prints "Total: 20", but its nine listed courses
-- (2,2,2,2,2,2,2,3,2) sum to 19. This exact same mismatch was already
-- independently documented in the photo-transcribed handbook version of this
-- file, and this clean, non-photographed, real-text official PDF prints the
-- identical wrong total against the identical nine values -- confirming this
-- is a genuine error in the university's own curriculum document, carried
-- over from one revision to the next, not a scanning or transcription
-- artifact. The nine values are recorded exactly as printed.
--
-- FIFTH YEAR -- FOUR OPTIONS: final-year students take one of four
-- specialization options (Power Systems/Machinery/Mechatronics; Soil/Water/
-- Aquacultural; Food and Bioprocess; Structures and Environmental), each
-- with its own First and Second Semester course lists and printed totals.
-- Courses are stored once each (de-duplicated across options that share a
-- code) with is_elective = true throughout, since nothing at 500 Level is
-- taken by every student the way a Year 1-4 course is -- and each row's
-- description states which option(s) it belongs to. Each option's own two
-- semesters were checksummed separately against that option's own printed
-- totals (19 and 18 for all four options) rather than against a merged
-- de-duplicated total, matching how the source itself totals each option.
--
-- THIS FIXES A REAL GAP IN THE PRIOR VERSION: the photo-transcribed file
-- could not read Option Two's second semester past its first two rows
-- because the source photograph was cropped mid-table, so ABE 522 was
-- stored with credit_units = 0 (this project's "not yet known" sentinel)
-- and ABE 526 was omitted entirely. Both now carry their real values (2
-- units each) read directly from this PDF's clean text.
--
-- ELECTIVE / SERVICE COURSES: ABE 304 (300 Level second semester) and
-- ABE 412 (400 Level second semester) are printed as service courses taught
-- by this department for the Faculty of Agriculture, not part of the ABE
-- degree's own required load -- both are flagged is_elective = true and
-- excluded from their semester's checksum, matching how the source's own
-- printed totals treat them.
--
-- DESCRIPTIONS: ABE-prefixed courses use the descriptions printed in this
-- same PDF's own "COURSES DESCRIPTION" section. Shared ancillary courses
-- (EGR/MTH/PHY/CHM/GSP/CVE/EEE/MEC/STA/CED courses) reuse the description
-- already held for that code elsewhere in this app; SSC 211, ANS 271,
-- CSC 332 and AGE 301 are taught by other departments not yet carrying
-- their own outline in this app, so they are stored with real code/title/
-- units and a blank description rather than an invented one.
-- =============================================================================

delete from public.course_outlines
 where institution = 'University of Nigeria, Nsukka'
   and department = 'Agricultural and Bioresources Engineering';

insert into public.course_outlines
  (course_code, course_title, institution, faculty, department, level,
   semester, credit_units, description, topics, contributor_name, is_elective)
values
  ('EGR 101', 'Introduction to Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '100 Level', 'first', 2, 'An overview of engineering as a profession. Historical perspective, Discipline, Rationalization, professional affiliations, professional journey, successful studentship, creativity, roles of science and Technology; Engineering and Society: The role of engineers in nation building, professional impacts of Engineering practice and mitigation measures, professional challenges in Nigeria, historical and professional roles; Basic information on Agricultural and Bioresources Engineering, Professional practice, Sustainable Agricultural production in Nigeria; Introduction to Biomedical Engineering, Scope of biomedical engineering practice: A science perspective of Civil Engineering, corporate personality of Civil Engineering; Civil Engineering professional practice; Basic information on Electrical Engineering, Scope of Electrical Engineering professional practice; Electric power generation in Nigeria; Evolution to Electronic Engineering, Scope of Electronic Engineering Professional practice, practice of Electronic Engineering in Nigeria; Basic information on Mechanical Engineering, Scope of Mechanical Engineering professional practice, practice of Mechanical Engineering in Nigeria; Introduction to Mechatronics Engineering, Scope of Mechatronics engineering practice; Basic information on Metallurgical and Materials Engineering, Scope of Metallurgical and Materials Engineering professional practice, practice of Metallurgical and Materials Engineering.', '["An overview of engineering as a profession. Historical perspective, Discipline, Rationalization, professional affiliations, professional journey, successful studentship, creativity, roles of science and Technology", "Engineering and Society: The role of engineers in nation building, professional impacts of Engineering practice and mitigation measures, professional challenges in Nigeria", "Basic information on Agricultural and Bioresources Engineering; Introduction to Biomedical Engineering", "A science perspective of Civil Engineering, corporate personality and professional practice of Civil Engineering", "Basic information on Electrical Engineering; Electric power generation in Nigeria; Evolution to Electronic Engineering", "Basic information on Mechanical Engineering, Scope and practice of Mechanical Engineering in Nigeria", "Introduction to Mechatronics Engineering; Basic information on Metallurgical and Materials Engineering"]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('MTH 111', 'Elementary Mathematics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '100 Level', 'first', 3, 'Elementary set theory, subsets, union, intersection, complements. Venn diagrams, real numbers, integers, rational and irrational numbers, mathematical induction, real sequences and series, theory of quadratic equations, binomial theorem. Circular measure, trigonometric functions of angles of any magnitude, addition and factor formulae. Complex numbers, algebra of complex numbers, the Argand diagram, De Moivre''s theorem, nth roots of unity.', '["Elementary set theory, subsets, union, intersection, complements", "Venn diagrams, real numbers, integers, rational and irrational numbers, mathematical induction, real sequences and series, theory of quadratic equations, binomial theorem", "Circular measure, trigonometric functions of angles of any magnitude, addition and factor formulae", "Complex numbers, algebra of complex numbers, the Argand diagram, De Moivre''s theorem, nth roots of unity"]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('MTH 121', 'Elementary Mathematics II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '100 Level', 'first', 3, 'Functions of a real variable, graphs, limits and continuity. The derivative as limit of rate of change. Techniques of differentiation. Curve sketching, integration as an inverse of differentiation. Methods of integration, definite integrals. Application of integration to areas and volumes.', '["Functions of a real variable, graphs, limits and continuity", "The derivative as limit of rate of change", "Techniques of differentiation", "Curve sketching, integration as an inverse of differentiation", "Methods of integration, definite integrals", "Application of integration to areas and volumes"]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('PHY 121', 'Fundamentals of Physics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '100 Level', 'first', 3, 'Units and dimensions. Vector algebra. Kinematics of a particle''s mass point; laws of mechanics and gravitation. Kepler''s Laws. Motion of rigid bodies, moment of inertia, angular momentum, vertical motion of a particle, elastic string, motion of a simple pendulum. Impulse and change of Momentum. Impact of two smooth elastic spheres. Direct and Oblique impacts.', '["Units and dimensions. Vector algebra", "Kinematics of a particle''s mass point; laws of mechanics and gravitation. Kepler''s Laws", "Motion of rigid bodies, moment of inertia, angular momentum", "Vertical motion of a particle, elastic string, motion of a simple pendulum", "Impulse and change of Momentum. Impact of two smooth elastic spheres. Direct and Oblique impacts"]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('PHY 195', 'Practical Physics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '100 Level', 'first', 2, 'Selected Experiments from the 100-Level courses in Physics for Physics majors and Engineering students.', '["Selected Experiments from the 100-Level courses in Physics for Physics majors and Engineering students"]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('CHM 101', 'Basic Principles of Inorganic Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '100 Level', 'first', 2, 'Stoichiometry and Atomic Structure: Stoichiometry and mole concept. Introduction to atomic structure, development of electronic configuration of the elements, and valency theories. Periodic Table and Groups: The periodic classification of elements. Brief group study of representative elements, with emphasis on similarities and differences based on periodic position. Nuclear Chemistry: Radioactivity and its practical applications.', '["Stoichiometry and Atomic Structure: Stoichiometry and mole concept. Introduction to atomic structure, development of electronic configuration of the elements, and valency theories", "Periodic Table and Groups: The periodic classification of elements. Brief group study of representative elements, with emphasis on similarities and differences based on periodic position", "Nuclear Chemistry: Radioactivity and its practical applications"]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('CHM 171', 'Basic Practical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '100 Level', 'first', 2, 'Laboratory operations: theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations.', '["Laboratory operations: theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations"]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('GSP 101', 'Study Skills and Basic Research Methods', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '100 Level', 'first', 2, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('EGR 102', 'Applied Mechanics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '100 Level', 'second', 3, 'Introduction - Force Systems, resultants, Moments, Couples. Equilibrium, free-body diagram, 2-dimensional force systems, equations for equilibrium of forces in space, internal forces, examples of simple machines, friction, pulleys, wires and cables, static and dynamic Friction. Centroid, graphical determination, Theorems of Pappus of centers of gravity and areas. Moments of Inertia of plane areas, built up sections etc. Kinematics of particles and rigid bodies. Newton''s laws of motion applied to a system of particles. Rectilinear and curvilinear motion, tangent, normal, polar, work, energy, power. Concepts of momentum and Newton''s laws of motion under gravity. Projectile motion.', '["Introduction - Force Systems, resultants, Moments, Couples. Equilibrium, free-body diagram, 2-dimensional force systems", "Equations for equilibrium of forces in space, internal forces, examples of simple machines, friction, pulleys, wires and cables, static and dynamic Friction", "Centroid, graphical determination, Theorems of Pappus of centers of gravity and areas. Moments of Inertia of plane areas, built up sections etc", "Kinematics of particles and rigid bodies. Newton''s laws of motion applied to a system of particles", "Rectilinear and curvilinear motion, tangent, normal, polar, work, energy, power", "Concepts of momentum and Newton''s laws of motion under gravity. Projectile motion"]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('MTH 122', 'Elementary Mathematics III', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '100 Level', 'second', 3, 'Geometric representation of vectors in 1-3 dimensions, Components, direction cosines. Addition of vectors and multiplication of vectors by a scalar, linear independence. Scalar and vector products of two vectors. Differentiation and integration of vectors with respect to a scalar variable. Two-dimensional coordinate geometry. Straight lines, circles, parabolas, ellipses, hyperbolas. Tangents and normals. Kinematics of a particle. Components of velocity and acceleration of a particle moving in a plane. Force and momentum. Newton''s laws of motion; motion under gravity, projectile motion, resisted vertical motion of a particle, elastic string, motion of a simple pendulum, impulse and impact of momentum. Impact of two smooth elastic spheres. Direct and oblique impacts.', '["Geometric representation of vectors in 1-3 dimensions, Components, direction cosines", "Addition of vectors and multiplication of vectors by a scalar, linear independence", "Scalar and vector products of two vectors", "Differentiation and integration of vectors with respect to a scalar variable", "Two-dimensional coordinate geometry", "Straight lines, circles, parabolas, ellipses, hyperbolas", "Tangents and normals", "Kinematics of a particle", "Components of velocity and acceleration of a particle moving in a plane", "Force and momentum", "Newton''s laws of motion", "Motion under gravity, projectile motion, resisted vertical motion of a particle, elastic string, motion of a simple pendulum, impulse and impact of momentum", "Impact of two smooth elastic spheres", "Direct and oblique impacts"]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('PHY 116', 'General Physics for Physical Sciences II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '100 Level', 'second', 2, 'Temperature and its measurement. Heat capacity, specific heat, latent heats, critical points. Calorimetry. Gas laws; kinetic theory of gases; thermal energy, work done by expanding gases; laws of thermodynamics. Liquefaction of gases. Heat transfer: conduction, convection, radiation. Longitudinal and transverse waves; vibrations in solids. Sound waves in solids, liquids, gases; pitch, intensity and quality of sound. Doppler Effect. Acoustics of buildings. Ultrasonics. Reflection and refraction of light; spherical mirrors; thin and thick lenses; optical instruments. Wave nature of light; interference, diffraction, polarization. Velocity of light.', '["Temperature and its measurement", "Heat capacity, specific heat, latent heats, critical points", "Calorimetry", "Gas laws", "Kinetic theory of gases", "Thermal energy, work done by expanding gases", "Laws of thermodynamics", "Liquefaction of gases", "Heat transfer: conduction, convection, radiation", "Longitudinal and transverse waves", "Vibrations in solids", "Sound waves in solids, liquids, gases", "Pitch, intensity and quality of sound", "Doppler Effect", "Acoustics of buildings", "Ultrasonics", "Reflection and refraction of light", "Spherical mirrors", "Thin and thick lenses", "Optical instruments", "Wave nature of light", "Interference, diffraction, polarization", "Velocity of light"]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('PHY 124', 'Fundamentals of Physics III', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '100 Level', 'second', 3, 'Electrostatics, Coulomb''s Law, Gauss''s Law, simple applications. Electric field, electrostatic potential. Energy in electric field, capacitance, dielectrics. Electric current, Ohm''s law, circuit analysis, Thermoelectricity. Magnetic effects of currents, Ampere''s Law, Applications. Electromagnetism, Faraday''s law of induction, Maxwell''s equations. Alternating currents, A.C. circuits. Measuring devices. Motion of a charged particle in electric and magnetic fields, Hall Effect. Atomic and Nuclear structure. Nuclear fission and fusion. Nuclear reactors.', '["Electrostatics, Coulomb''s Law, Gauss''s Law, simple applications", "Electric field, electrostatic potential. Energy in electric field, capacitance, dielectrics", "Electric current, Ohm''s law, circuit analysis, Thermoelectricity", "Magnetic effects of currents, Ampere''s Law, Applications. Electromagnetism, Faraday''s law of induction, Maxwell''s equations", "Alternating currents, A.C. circuits. Measuring devices", "Motion of a charged particle in electric and magnetic fields, Hall Effect", "Atomic and Nuclear structure. Nuclear fission and fusion. Nuclear reactors"]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('CHM 112', 'Basic Principles of Physical Chemistry II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '100 Level', 'second', 2, 'Gas laws and kinetic theory: kinetic theory of gases, elementary derivation and deduction of gas laws, molecular speeds, deviations from ideal behaviour, van der Waals modification, and gas liquefaction. Phase equilibrium and solutions: phase transitions and phase equilibria in one-component systems; ideal solutions, Raoult''s law, Henry''s law, real solutions, and colligative properties. Thermodynamics and kinetics: aspects of the first law of thermodynamics, thermochemistry, entropy, free energy, and spontaneous changes; ionic equilibria, acids, bases, indicators, and buffers; elementary chemical kinetics.', '["Gas laws and kinetic theory of gases; molecular speeds; deviations from ideal behaviour; gas liquefaction", "Phase transitions and phase equilibria; ideal and real solutions; colligative properties", "First law of thermodynamics, thermochemistry, entropy, free energy, spontaneous changes", "Ionic equilibria, acids, bases, indicators and buffers", "Elementary chemical kinetics: rate laws, order and molecularity, Arrhenius equation"]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('CHM 122', 'Basic Principles of Organic Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '100 Level', 'second', 2, 'Structure and classification: historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, homologous series, elemental analysis, molecular formulas, and structural isomerism. Bonding and reactivity: isolation and purification methods, functional group concepts, resonance, and aromaticity. Functional groups: saturated and unsaturated hydrocarbons, cyclic hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, and aromatic compounds. Stereochemistry and lipids: introduction to oils, fats, and stereoisomerism.', '["Historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, structural isomerism", "Isolation and purification methods; functional group concepts; resonance and aromaticity", "Saturated and unsaturated hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, aromatic compounds", "Introduction to oils, fats, and stereoisomerism"]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('GSP 102', 'Basic Grammar and Varieties of Writing', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '100 Level', 'second', 2, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 201', 'Introduction to Agricultural and Bioresources Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '200 Level', 'first', 1, 'The human need for food, fiber and timber and the role of engineering in their production, processing, storage/preservation and transportation. Concept of Agriculture as crops and livestock production and of Bioresources as including Aquaculture and Forestry, among others. Definition of Agricultural and Bioresources Engineering and its unique position in the engineering professions. The specialty areas of Agricultural and Bioresources Engineering; their general introduction.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('EGR 201', 'Materials Science', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('EGR 202', 'Materials Science Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '200 Level', 'first', 1, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('CVE 211', 'Strength of Materials I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('CVE 212', 'Strength of Materials Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '200 Level', 'first', 1, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('EEE 211', 'Basic Electrical Engineering I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '200 Level', 'first', 3, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('MEC 211', 'Engineering Drawing', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('MEC 261', 'Thermodynamics and Heat Engines', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('MTH 207', 'Advanced Mathematics VII', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '200 Level', 'first', 2, 'Elements of linear algebra. Calculus: Elementary differentiation and relevant theorems. Differential equations: Exact equations, methods of solution of second-order ordinary differential equations, partial differential equations, with applications.', '["Elements of linear algebra", "Calculus: Elementary differentiation and relevant theorems", "Differential equations: Exact equations, methods of solution of second-order ordinary differential equations, partial differential equations, with applications"]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('GSP 201', 'Peace Studies and Conflict Resolution I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('GSP 207', 'Humanities I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 252', 'Computer Applications in Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '200 Level', 'second', 3, 'Concept of structured programming. Procedures and functions in FORTRAN. Declarations, I/O and file operations. Using a Windows-based FORTRAN software in finding solutions to equations, interpolations/extrapolations, calculus, numerical derivatives and integrals, matrix operations, differential equations, least square approximations, and sorting of data. Introduction to CSharp (C#) programming language. C# syntax: loops, conditions, arrays and strings. Object oriented programming. Object oriented concepts. Sample projects.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 254', 'The Internet and Information Technology', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '200 Level', 'second', 2, 'Introduction to the PC and the internet including a brief history; Formatting and partitioning of hard drives of the PC; Installing operating systems and basic software like Windows, Microsoft Office, Drivers, Antivirus, etc; Managing the computer and removable devices against virus attacks; Using soft and hard back-ups for works being done inside the PC as a precursor to crashing and other possible problems with computers while working; Introduction to cloud computing; Data and word processing with Microsoft Excel and Word; Introduction to Computer Aided Design (CAD); Accessing the internet and navigating the web; E-mailing operations; Use of the internet for information searching and research; Downloading documents on the internet', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('CVE 221', 'Fluid Mechanics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '200 Level', 'second', 2, 'Elective. The programme table''s left edge is cut off by the book''s binding, printing only "E 221" for this code; CVE 221 (Civil Engineering) is used as the closest plausible match for a Fluid Mechanics elective, but this is not independently confirmed.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('CVE 222', 'Fluid Mechanics Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '200 Level', 'second', 1, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('EEE 251', 'Basic Electrical Engineering Laboratory/Practice', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '200 Level', 'second', 1, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('MEC 212', 'Workshop Technology', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '200 Level', 'second', 2, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('MTH 206', 'Advanced Mathematics IV', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '200 Level', 'second', 2, 'The programme table prints "Advanced Mathematics VII" against both MTH 206 and MTH 207; quoted as printed. Complex analysis - Elements of the algebra of complex variables, trigonometric, exponential and logarithmic functions. The number system, sequences and series. Vector differentiation and integration.', '["Complex analysis - Elements of the algebra of complex variables, trigonometric, exponential and logarithmic functions", "The number system, sequences and series", "Vector differentiation and integration"]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('MTH 208', 'Advanced Mathematics VIII', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '200 Level', 'second', 2, 'Elective. Numerical analysis: Linear equations, non-linear equations; finite difference operators. Introduction to linear programming.', '["Numerical analysis: Linear equations, non-linear equations", "Finite difference operators", "Introduction to linear programming"]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('GSP 202', 'Peace Studies and Conflict Resolution II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '200 Level', 'second', 2, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('GSP 208', 'Humanities II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '200 Level', 'second', 2, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 301', 'Introduction to Technical Writing and Presentation', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'first', 1, 'Principles of effective communication, professional use of the English language. Principles of technical writing. Oral presentation of technical ideas. Using Reference software such as EndNote and Mendeley for managing bibliography; Using relevant software for plagiarism management such Ithenticate, CrossRef, etc.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 321', 'Applied Hydraulics in ABE', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'first', 2, 'Review of fluid statics, kinematics and dynamics. Flow in closed conduits: continuity, momentum and energy equations and their applications for single pipelines. Head losses in transitions and fittings, and in non-circular pipes. Empirical friction-loss formulae. Pumps. Flow in open channels: continuity, momentum and energy equations and their applications. The Darcy-Weisbach and Manning equations. Energy grade line. Specific energy. Water- surface profiles. The hydraulic jump. Description and comparison of different types of hydraulic systems; hydraulic filters; Valves: direction and pressure control valves; electro hydraulics and electro-hydraulic control systems. Hydraulic pumps: displacement, open and closed center systems, vane, piston and gear pump assemblies, pump failures, system contamination, filter operation. Types of cylinders: double and single acting cylinders, balanced and unbalanced cylinders, master slave cylinders and operations, vane type cylinders; Hydraulic motors: hydraulic pump and motor control operation; Hydraulic plumbing selection, hydraulic hose routing and selections; Hydraulic test equipment: pressure gauge, flow meter, test port placement and usage. Hydraulic safety procedures accident management', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 323', 'Applied Soil Mechanics in ABE', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'first', 2, 'Soil physical properties, crop growth, crop yield, crop physical properties and land management; soil mechanics laboratory practicals and measurement of physical, permeability, compaction and shear strength properties of agricultural soils. Phase relationships, shear strength, consolidation, settlement and compaction. Site investigations.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 331', 'Engineering Properties of Biomaterials', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'first', 2, 'The importance, scope and application of biometry to the solution of engineering problems in agricultural and food industry. Physical characteristics; criteria for describing shape and size; determination of volume, density, porosity, surface area. Mechanical properties; texture and quality of food materials; mechanical damage of food materials. Biological systems and some basic concepts of rheology; time dependent and characterization of biomaterials. Newtonian and non-newtonian fluids and viscometry. Thermal properties. Aerodynamic properties. Physicochemical properties, electrical/dielectric properties, colorimetric properties of biomaterials.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 341', 'Environmental Control in Agricultural & Bioresources Structures', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'first', 2, 'Animal and crop thermal environment interaction and application of principles of heat and mass transfer in the control of temperature, humidity and radiant heat load in animal and crop production/storage buildings as well as family houses. Topics to be covered include psychrometry heat and vapour transmission, ventilation, evaporative cooling, homeothermic systems and homeothermic mechanism. Response of animal to changes in environmental temperatures. Animal heat production. Heat and mass transfer in animals. Comfort indices. Radiant heat load and production. Plant physiological processes. Environmental factors affecting plant growth. Greenhouses. Environmental control in crop storage structures.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('CED 341', 'Introduction to Entrepreneurship', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('CVE 351', 'Engineering Surveys I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'first', 3, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('MEC 341', 'Mechanics of Machines', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('STA 205', 'Statistics for Physical Sciences and Engineering I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('SSC 211', 'Principles of Soil Science', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 302', 'Basic Agricultural and Bioresources Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'second', 1, 'Basics of Agricultural and Bioresources Engineering. Application of practical-problems solving skills. Identification of various tractors, implements, forestry machinery and aquacultural equipment. Tractor driving and test. Introduction to field operations in agricultural and bioresources engineering.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 312', 'Mechanics of Soil-Machine Interaction', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'second', 2, 'Shearing resistance of soils. Active and passive resistance of cohesive and cohesionless soils. Stability of slopes and foundation. Consolidation and settlement. Application of classical soil, mechanics. Drainage of agricultural soils, Traction and trafficability curves. Soil compaction: causes, effects on soil structure. Control measures, Soil – Machine dynamics, Models for 2D and 3D analysis of soil- machine interaction.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 314', 'Engineering Drawing and Design', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'second', 1, 'Parts and components assembly. Detailed drawing of machine, building and/or engineering system components. Sketching and use of design features, symbols, screws, fasteners, couplings, clutches, gears, etc. Building/Machine/Engineering-system component design. Presentation of design portfolio.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 322', 'Water Quality, Epidemiology and Environmental Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'second', 2, 'Overview of freshwater geochemistry. Primary production and nutrient cycles in rivers and lakes. Water pollutants and their sources. The health, environmental and socio- economic impacts of Water pollution. Epidemiological concept and definition. Water- borne diseases. Food-borne diseases. Air-borne diseases. Air pollution sources and effects. Origin and fate of air pollutants. Air pollution meteorology and atmospheric dispersion.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 324', 'Climatology and Meteorology in ABE', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'second', 1, 'The tropics: Atmospheric circulation in the tropics. Sunshine, Radiation, Temperature and humidity. Clouds, condensation and rainfall. Climate and climate change. Crop yield and Weather. Weather forecasting. Seasonality of tropical hydro-meteorological phenomena. Meteorology and agricultural/ bioresources production in the tropics.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 326', 'Environmental Hydrology', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'second', 2, 'Definition of hydrology and applications to environmental problems. Watershed concepts. The hydrological cycle and its component processes. The hydrologic budget and water balance equation. Precipitation, Vegetative-canopy Interception, Evaporation, Evapo- transpiration, Infiltration, Unsaturated Flow, Rainfall Excess, Abstractions and Direct Runoff. Overland flow; Surface runoff; and Flow Routing. Runoff Hydrographs. Groundwater Flow. Measurement of Hydrologic variables and their common Units of Measurement. Hydrologic Data Sources. Rainfall intensity-duration-frequency analysis. Design storms. Design rainfall hyetographs. Empirical methods of estimating design runoff volume, peak flow, and design hydrograph - the Curve Number method, rational method, and Dimensionless Hydrograph method. Design flow simulation.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 332', 'Introduction to Food Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'second', 1, 'Definitions; Introduction to food preservation processes; fermentation, packaging concepts; food properties; chemical and physical changes food undergoes during processing; food safety and quality; Introduction to fluid flow in food processing, energy and controls.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('EGR 301', 'Engineering Analysis', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'second', 4, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('CED 342', 'Business Development and Management', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ANS 271', 'Principles of Animal Production', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('CSC 332', 'Introduction to Crop Science', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 304', 'Introduction to Farm Machinery and Mechanization', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '300 Level', 'second', 2, '(A service course offered to Faculty of Agriculture) Introductory treatment of topics in farm power and machinery, electric power and processing, farm buildings and storage structures, and soil and water engineering to provide an understanding of the role of agricultural engineering in the mechanization of the agricultural industry and familiarize the agricultural student with basic agricultural engineering principles and technology.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 411', 'Agricultural and Bioresources Power and Machinery', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '400 Level', 'first', 2, 'Power sources for agriculture and forestry. Selection and management of farm tractors and equipment. Force analysis and power measurement on tillage tools. Field performance evaluation of food- and forest crop production equipment. Adjustment, maintenance and repair of tractors and equipment. Practical exposure to the adjustment, operation and maintenance of tractors, farm machinery, forest machinery, and aquacultural equipment and gadgets as applicable in Nigeria. Introduction to field and laboratory measurement devices and equipment', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 413', 'Land Clearing and Development', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '400 Level', 'first', 2, 'Land resources and Land use Act in relation to Nigerian agriculture and forestry. Vegetation types. Objectives, methods and equipment for land clearing and development. Machinery selection, mechanics of operation. Land reclamation. Earth moving machinery and earth moving mechanics. Economic analysis of land clearing operations.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 421', 'Hydraulic Structures', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '400 Level', 'first', 2, 'Introduction to dams and artificial wetlands. Reservoir hydraulics, spillways and high pressure outlets. Discharge measurement structures. Weirs – sharp-crested, broad-crested. The Parshall Flume. Gates. Culverts. Water level and velocity control structures. Flow- dividing structures. Flow intake structures. Riprap protection and silt control devices.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 423', 'Principles of Irrigation and Drainage Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '400 Level', 'first', 2, 'Crop water requirements in agriculture and forestry. Methods of irrigation. Principles of furrow, basin and sprinkler irrigation. Frequency and amount of irrigation. Irrigation water scheduling. Evaluating irrigation systems and practices. Principles and methods land drainage. Effect of crops, surface drainage, and sub-surface drainage.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 431', 'Principles of Plant and Animal Products Handling, Processing & Storage', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '400 Level', 'first', 2, 'Properties and characteristics of plant/animal products and biomaterials, Heat transfer and heat exchangers Cleaning, sorting and grading. Handling methods and machines. Processing techniques. Crop storage. Crop drying. Psychrometry and psychometric charts. Postharvest losses.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 441', 'Environmental Impact Assessment in ABE', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '400 Level', 'first', 2, 'Definition and concept of EIA. Socio-economic impacts definition. Scoping and baseline studies. Physical parameters for the soils, hydrological, water quality, and ecological components of an EIA. Impacts from direct manipulation or utilization. Impacts from projects not directly associated with manipulation and utilization. Hydrological impacts of construction projects - roads, land clearing/development/dams, etc. Impacts prediction, mitigation and monitoring. Mitigation measures relating to urban runoff and flood protection. International conventions on nature conservation. Evaluation of ecosystems. Restoration and compensation.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 451', 'Decision Support and Data Acquisition Systems', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '400 Level', 'first', 2, 'Systems Concepts. Geographic information systems (GIS) applications. Global positioning systems (GPS) applications. Simulation modeling applications. Expert systems applications. Introductory Bioinformatics. Introduction to Geoinformatics. Introduction to Hydroinformatics. Data logging and Telemetry. Remote sensing applications. Digital elevation mapping (DEM) applications. Monitoring instrumentation and microcomputer controls.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('EGR 401', 'Computational Methods', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '400 Level', 'first', 3, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('AGE 301', 'Basic Farm Management and Production Economics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '400 Level', 'first', 2, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 482', 'Special Problems in Agricultural and Bioresources Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '400 Level', 'second', 3, 'Each student will select and undertake a detailed study of any problem in agricultural and bioresources engineering of relevance to Nigeria under the guidance of an academic staff. A term paper will be submitted at the end of the study, which may be part of the literature review and research proposal for the student’s final-year project.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 484', 'Seminar', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '400 Level', 'second', 2, 'Based on the student’s thoroughly researched project proposal topic, the student is required to present a technically sound seminar which is preparatory to embarking on the final-year project, if approved.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('EGR 402', 'Students Industrial Work Experience Scheme (SIWES)', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '400 Level', 'second', 10, '', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', false),
  ('ABE 412', 'Agricultural Engineering Practicals', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '400 Level', 'second', 2, '(A service Laboratory & Field course Offered to Faculty of Agriculture) Practical exposure to the adjustment, operation and maintenance of tractors, farm machinery and other equipment and gadgets as applicable in Nigerian agriculture.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 501', 'Climate Change Adaptation in ABE', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 1, 'Common to all four Fifth-Year options. Definition of climate change; causes of climate change; indicators/evidence of climate change; General effects of climate change. Impacts on rainfall amounts, distribution and intensity; consequences of sea level rise; water logging of agricultural lands, flooding, etc. Impacts on agricultural and bioresources production systems. Impacts on engineering infrastructure; - transportation, energy, water, communications, waste management, etc. Definitions of and relationships between coping, vulnerability and adaptation. Methods of Vulnerability Assessment. Types of adaptation measures. Instruments for improved climate resilience: Technical Standards; Environmental Impact Assessment and Strategic Environment Assessment; Framework for the assessment and management of flood risks; Climate “proofing”. Technical adaptation: Identifying technologies for adaptation already in use elsewhere; Identifying opportunities for dual-use infrastructure; Mitigation and adaptation interactions. Smart buildings; Smart grid and intelligent networks; Dual water delivery and waste systems. Regulatory and policy issues: Design codes and standards; Adapting regulation for probabilistic scenarios; Planning for adaptation at the systems level; Expectation management: what standards of service are reasonable? Planning for a resilient agricultural and bioresources production system.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 511', 'Agricultural and Bioresources Mechanization', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 2, 'Common to all four Fifth-Year options. Nature and objectives of agricultural and forest mechanization. Factors affecting mechanization in the tropics. Analysis of production systems. Agricultural/forest mechanization as a strategy for rural development. Impact on food, fibre and timber production and on infrastructural development. Linkages with rural industrialization. Mechanization of fishing and aquacultural operations. Selected case studies.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 513', 'Power Sources for Agriculture and Forestry', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 2, 'Fifth-year Option One (Power Systems, Machinery and Mechatronics). Human-powered tools and machines. Draft animal power. Engines. Tractors for Agriculture and forestry. Two-wheel tractors. Two-axle tractors.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 515', 'Agricultural and Forest Machinery', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 3, 'Fifth-year Option One (Power Systems, Machinery and Mechatronics). Tillage Machinery. Seeders and planters. Fertilizer distributors. Pest control equipment. Harvesters and Threshers. Specialized machines and equipment for forage crops, root crops, fruits and vegetables, tropical crops and orchards. Greenhouse and forest cultivation equipment. Forest machines - portable chain saws, portable brush saws, winches, hitches, mobile and self-propelled machinery, portable brush-cutters and grass trimmers.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 517', 'Safety, Ergonomics and Health Issues in ABE', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 1, 'Fifth-year Option One (Power Systems, Machinery and Mechatronics). Care and protection against pesticide spills and poisoning. Safety issues in machinery operation. Work science and the human physiology. Physical training and professional skills requirements for safe and healthy operation of motorized machinery. Gender issues and considerations in design and operation of machinery.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 521', 'Soil and Water Conservation', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 2, 'Common to all four Fifth-Year options. Types of erosion. Soil erosion by water. Universal soil loss equation. RUSLE. Control of soil erosion by water. Wind erosion and its control. Desertification and control measures. Earth dams and farm ponds.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 523', 'Design of Irrigation Systems', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 3, 'Fifth-year Option Two (Soil, Water Resources and Aquacultural Engineering). Distribution of water on the farm –surface ditches, underground pipes, portable pipes. Review of irrigation water application methods. Design of surface irrigation systems – graded border design, furrow irrigation design, evaluation of existing systems. Sprinkler irrigation systems and components. Sprinkler system design and layout for intermittent- move systems and for center-pivot sysems. Special sprinkler applications. Microirrigation systems layout and components. Emitters; discharge capacity and water distribution. Microirrigation system design.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 525', 'Aquacultural Engineering I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 2, 'Fifth-year Option Two (Soil, Water Resources and Aquacultural Engineering); Option Four (Structures and Environmental Engineering). Aquacultural systems and their environmental requirements. System types. Ponds, raceways, net pens and cages, tanks and re-circulating systems. Primary constraints in aquacultural systems: properties of water, oxygen as a constraint. Environmental needs of aquatic organisms. Materials for aquacultural facilities: considerations in materials selection; weight of water, corrosion, bio-fouling, ozone as a constraint. Materials for system components; tanks, raceways, waterproof lining, screen mesh, nets, ozone unit. Advantages and disadvantages of masonry, metals, plastics, rubber compounds, and wood materials. Design of aquacultural facilities: pond types, pond photosynthesis, diurnial limits. Productive systems and polyculture, pH limits, Nitrogen control.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 527', 'Design of Drainage Systems', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 2, 'Fifth-year Option Two (Soil, Water Resources and Aquacultural Engineering). The need and design considerations for land drainage. Surface drainage and land forming. Subsurface drainage design. Drainage accessories – pipes and envelope materials. Loads on conduits. Drainage pumping. Construction and installation of drains. Maintenance of drains. Drainage applications in land reclamation and improvement.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 529', 'Integrated Water Resources Development and Management', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 2, 'Fifth-year Option Two (Soil, Water Resources and Aquacultural Engineering). What is Integrated Water Resources Management? Why IWRM? Key issues in water management. Water management principles. Water use, impacts and benefits. Implementing IWRM. Basic functions for water resources management. Water management objectives as a way of performing the functions. Institutional arrangements for performing the functions. Stepwise approach to conduct the functions. Water management objectives in water allocation. Water resources system analysis. Water permits. Planning for pollution control. Monitoring of water resources. Monitoring of water use. Monitoring of pollution and water quality. Information management process. Information management tools. Information management outputs. Preparing for basin planning. Basin planning process. Implementation of the basin plan.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 531', 'Processing of Agricultural and Bioresources Products', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 2, 'Fifth-year Option One (Power Systems, Machinery and Mechatronics); Option Three (Food and Bioprocess Engineering). Unit operations in processing; cleaning, sorting, grading and separation: Principles, techniques and machines; comminution. Particle size analysis. Heat treatment. Evaporation, Dehydration and drying. Psychometry. Properties of air-water-vapor mixtures. Processing techniques for Nigerian food/fibre/forest crops and aquatic products. Process control in biomaterial processing size reduction equipment, mixing and emulsification', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 533', 'Storage of Agricultural and Bioresources Products', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 3, 'Fifth-year Option Three (Food and Bioprocess Engineering). Storage types and environment. Economics of produce storage, deterioration of produce in storage; behavior of fresh produce in storage, importance of asepsis; extrinsic parameters of produce deterioration and their control. Special storage techniques. Unique aspects and problems of food/fibre and biomaterials storage in the humid tropics. Rational design of grain storage structures. Environmental control in storage structures. Evaporative cooling. Psychrometric charts and its application in storage.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 535', 'Solar Energy Application in Bioprocess Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 2, 'Fifth-year Option Three (Food and Bioprocess Engineering). Fundamentals of solar radiation. Solar heating and cooling. Heat transfer. Solar energy conversion efficiency. Principles of solar collections. Solar heat storage and applications in drying, preservation and storage systems for tropical food/fibre/forest crops, and for aquatic products. Design of solar dryers.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 537', 'Food Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 3, 'Fifth-year Option Three (Food and Bioprocess Engineering). Definitions. Heat and mass transfer. Insulation. Heat exchanger design and application. Heat and cold preservation of foods. Food packaging principles. Food safety, and quality control. Principles and design of food processing equipment. Food product development. Sensory evaluation. Food wastes management. Process control.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 539', 'Fermentation Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 2, 'Fifth-year Option Three (Food and Bioprocess Engineering). Fundamentals of fermentation processes, modes of fermentation, and the principle of upstream operation. Physical and chemical factors that affect fermentation processes. Different types of fermenters. Brewing, bioreactor design and control; microbial kinetics. Unitary operations for solid-liquid separation, concentration, and drying of fermented foods. Potential application of a biorefinery concept to add value to food industry wastes. Fermentation for biofuels and biobased chemicals.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 541', 'Farmstead Planning and Design', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 3, 'Fifth-year Option Four (Structures and Environmental Engineering). Farm and Farmstead types. Planning factors. Planning considerations, Farmstead layout and the concept of zone planning. Orientation and spacing of farm buildings. Functional design of family, poultry, pig, dairy and beef cattle, goats and sheep and micro-livestock housing. Building material – timber, concrete, metals, organic materials.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 543', 'Bio-Environmental Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 2, 'Fifth-year Option Two (Soil, Water Resources and Aquacultural Engineering); Option Four (Structures and Environmental Engineering). Sources and collection of agricultural and bioresources liquid wastes including animal waste, slaughter house and food processing waste. Liquid waste characteristics. Pollution potential of liquid waste. Unit operations for agricultural liquid waste treatment – screening, communition, sedimentation and floatation. Biological treatment processes – aerobic, anaerobic and facultative systems. Biological treatment of liquid waste. Suspended culture systems – CMR, activated sludge, UASB, waste stabilization ponds and lagoons, constructed wetlands. Attached film systems – trickling filter and RBC. Waste stabilization system design. Disinfection. Sludge treatment. Bio and phyto- remediation. Sources and control of air pollution.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 545', 'Agricultural and Bioresources Structures Design', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 3, 'Fifth-year Option Two (Soil, Water Resources and Aquacultural Engineering); Option Four (Structures and Environmental Engineering). Review of structural analysis. Design principles and design procedures. Design codes. Analyses of action (load estimation). Characteristic strength and characteristic action. Partial safety factor for materials and load. Design of concrete beams, columns, slabs, and footings. Design of steel and timber beams, columns and connections. Applications in agricultural buildings and structures. Design of storage structures (silos and cribs).', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 547', 'Agricultural Solid Waste Management', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 2, 'Fifth-year Option Four (Structures and Environmental Engineering). Sources and types of solid waste – crop residues, municipal and agro-industrial solid waste. Physical and chemical composition of agricultural solid waste. Solid waste generation. Solid waste collection. Estimation of and factors affecting generating rate. On-site handling, storage and processing. Processing techniques – mechanical size alteration, mechanical component separation, magnetic and electro-mechanical separation drying and de-watering. Land-filling with solid waste. Design, operation and maintenance of landfills. Material recovery systems for agricultural solid wastes. Recovery of Biological and thermal conversion products – composting (aerobic conversion), combustion, gasification and pyrolysis.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 551', 'Precision Agriculture and Information Technology', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 2, 'Fifth-year Option One (Power Systems, Machinery and Mechatronics). Definition of precision agriculture. Electronic monitoring and control of field machines. Integrated control of tractors and their associated implements. Precision agriculture based on the NAVSTAR Global Positioning System. Sensors and automatic navigation of field machines. Machine vision concepts and cameras. Recognition of crop and soil features for applications to vehicle guidance and site-specific treatments.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 553', 'Mechatronics and Power Machinery Systems Automation', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 2, 'Fifth-year Option One (Power Systems, Machinery and Mechatronics). Introducing mechatronics: philosophy, examples of mechatronic systems, embedded systems, traditional and mechatronics designs, modeling systems, connected systems, measurement systems, control systems, programmable logic controller; Sensors and actuators; Agricultural automation and control; Agricultural vehicle robots; Mechanization, sensing and control in crop and animal production', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 555', 'Electrification and Renewable Energy', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'first', 2, 'Fifth-year Option One (Power Systems, Machinery and Mechatronics); Option Three (Food and Bioprocess Engineering); Option Four (Structures and Environmental Engineering). Electrical codes, tariffs and regulations. Generation and transmission of electricity. Testing procedure. Power factor correction. Selection and use of electric motors. Transformers. Energy conversion. Applications and use of electricity in agricultural and bioresources engineering. Electrical load assessment. Electrical distribution systems in farmsteads. Natural energy sources and their characteristics. Wind energy. Types of wind machines. Water power. Water turbines, water wheels, mechanical and electrical components. Solar energy. Solar photovoltaics; solar cells and modules. Biomass energy.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 512', 'Principles of Agro-Industrial Management', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'second', 2, 'Fifth-year Option One (Power Systems, Machinery and Mechatronics); Option Three (Food and Bioprocess Engineering). Principles of management. Feasibility and establishment of Agro-industries. Management of cottage industries for agricultural products. Selected management case studies in plant and equipment. Industrial group and organisational behaviour, motivation, industrial law, legislation on wages, trade marks and patents. Law of contract and sale of goods. Industrial safety and liability for injuries. Industrial relations. Trade unions, employer associations and role of state.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 514', 'Agric & Bioresources Power and Machinery Syst Management', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'second', 1, 'Fifth-year Option One (Power Systems, Machinery and Mechatronics). Integrated approach to machinery usage and agricultural/bioresources production sequence. Equipment selection. Scheduling of operation, seasonally factor. Machinery management Model. Machinery ownership and financing. Gross margin-analysis. Optimization of machinery -input combinations. Management of farm/forestry enterprises. Cost analysis of agricultural/forest machinery, Maintenance and Replacement. Case studies.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 516', 'Design of Agricultural and Forest Machinery', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'second', 3, 'Fifth-year Option One (Power Systems, Machinery and Mechatronics). Machine design processes and procedures. Materials of construction, strength properties, stress analysis, costing. Design of machine elements. Machine fabrication. Typical design of low cost agricultural/forest machinery development and commercial manufacture in Nigeria.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 518', 'Forest Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'second', 2, 'Fifth-year Option One (Power Systems, Machinery and Mechatronics). Forest stand establishment. Site preparation. Planting. Forest stand maintenance. Clearing and thinning of young stands. Pruning. Fertilization. Fire protection. Soil restoration. Forest roads. Tree harvesting, processing techniques, handlings and maneuvers. Tree felling, felling process, felling tools. Mechanical tree fellers. De- limbing, topping, bucking. Debarking. Wood comminution. Timber transportation; log extraction, skidding, winch skidding, grapple skidding, forwarding, locomotion. Special logging systems.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 522', 'Design of Soil and Water Conservation Structures', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'second', 2, 'Fifth-year Option Two (Soil, Water Resources and Aquacultural Engineering). Review of relevant hydraulic theories. Design of vegetated waterways. Terracing: functions and classification. Terrace system planning and design. Conservation structures permanent and temporary structures, functional requirements and design features. Function, limitations and design features of drop spillways, chutes, formless flume, pipe spillways and culverts. Irrigation and drainage structures. Earth embankments and farm ponds. Floods: types and methods of control. Flood routing.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 524', 'Rural Water Supply and Sanitation', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'second', 2, 'Fifth-year Option Two (Soil, Water Resources and Aquacultural Engineering); Option Four (Structures and Environmental Engineering). Water requirements. Water quality standards. Water-borne diseases. Biochemical oxygen demand. Portable water impurities. Sources and treatment methods of water for rural homes. Water lifting devices. Transportation and distribution systems. Pipe sizes. Waste disposal in rural communities. Collection, septic tanks. Digestion ponds and family privies.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 526', 'Aquacultural Engineering II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'second', 2, 'Fifth-year Option Two (Soil, Water Resources and Aquacultural Engineering). Raceways design densities and loadings. Raceway length. Fish growth. Design principles and considerations for raceways. Site selection for net pens. Net pen design and construction. Biomass loading of tanks. Labour requirements. Tank shapes and sizes. Water inlet and outlet. Equipment and controls in aquacultural systems: feeding equipment; hand feeding, automatic feeders, demand feeders. Harvest equipment types. Monitoring equipment, sensors, monitoring and control systems. Aquacultural wastes handling: effluent regulations; materials to remove. Methods to remove ammonia. Methods to remove solids. Methods to dispose of solids. Methods to remove dissolved and colloidal organic matter. Methods to remove carbon dioxide.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 528', 'Watershed Management', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'second', 2, 'Fifth-year Option Two (Soil, Water Resources and Aquacultural Engineering). Watershed rainfall-runoff processes. Derivation of the St. Venant equations and solution of their kinematic approximation. Watershed hydrologic models, types and characterization. Watershed erosion and sediment yield models. Model application to planning and management of watershed changes and development. Watershed management for water harvesting, flood control, soil erosion and sediment yield control. Reservoir design, sedimentation and useful life.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 532', 'Biomaterial Handling and Transportation Equipment', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'second', 2, 'Fifth-year Option One (Power Systems, Machinery and Mechatronics); Option Three (Food and Bioprocess Engineering). Definitions; design of material handling machines; methods of reducing handling damages. Transportation equipment. Powered farm vehicles for field use. Mono- wheelers, tri- wheelers, four-wheel carriers, multi-wheel carriers, crawler-type carriers. Motor trucks, subcompact trucks, farm trucks. Trailers used with walking tractors; used with four-wheel tractors; used for transporting Combine Harvesters and heavy equipment. Trailers with hydraulic tippers. Grain trailers. Loaders and forklifts. Monorails.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 534', 'Biomass Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'second', 2, 'Fifth-year Option Three (Food and Bioprocess Engineering). Biomass resources and principles of utilization. Energy crops and their production. Biomass feed stocks and environmental considerations. Anaerobic digestion of biomass: feedstock, technology and products. Biomass pretreatment techniques: steam explosion technology, briquetting, torrefaction and other densification technologies. Treatment of Municipal solid wastes: principles and processes. Bioethanol: fermentation and distillation technologies. Octane number and octane number improvers. Transesterification of biomass: feedstocks, technology and products. Cetane number. Combustion technologies. Gasification technology. Gasification reactors. Pyrolysis. Charcoal production.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 536', 'Packaging and Containerization Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'second', 2, 'Fifth-year Option Three (Food and Bioprocess Engineering). Purposes of packaging food and biomaterials. Packaging types: boxes, cartons, bags, bins, prepacks, paper wrapping and padding, plastic film bags, bio-degradables etc. Packaging systems. Marketing requirements for packaging. Storage environmental requirements. Types of packing configuration. Protection against shock, vibration and static compression of packaged biomaterials. Apportionment, convenience and labeling of cartons. Palletization. Canning technology. Aseptic processing and packaging. Modified atmosphere packaging and applications. Maximum allowable load concepts and containerization design.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 538', 'Post Harvest Technology', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'second', 2, 'Fifth-year Option Three (Food and Bioprocess Engineering). Definitions; biology of fresh produce; effect of postharvest factors on post-harvest life; maturation and maturity indices; harvesting; pre-cooling operations; packing and packaging of fresh produce; transport systems; postharvest losses; postharvest technology of seeds; postharvest handling of perishable crops; postharvest packaging systems', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 542', 'Environmental Systems Management in ABE', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'second', 2, 'Fifth-year Option Two (Soil, Water Resources and Aquacultural Engineering); Option Four (Structures and Environmental Engineering). Definition of ecosystems. Biological control of the environment. Concept of productivity. Production and decomposition in nature. Homeostasis of the ecosystem. Food chains, food webs and trophic levels. Ecosystem energetics. Biogeochemical cycles and recycle pathways. Nutrient cycling in the tropics. Primary goods and services provided by various ecosystems: Agro-ecosystem, Forest ecosystem, Freshwater ecosystem, Grassland ecosystem and Coastal ecosystem. Management trade-offs among various ecosystem goods and services. Taking stocks of ecosystem conditions and changing capacity. Ecosystem balancing.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 544', 'Applied Biotechnology in Agricultural Waste Utilization', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'second', 3, 'Fifth-year Option Four (Structures and Environmental Engineering). Fermentation processes. Anaerobic fermentation of liquid waste. Bio-reactor operating parameters. Classification and types of anaerobic reactors. Reactor performance indices. Anaerobic reactor kinetics. Biogas collection and utilization. Microbial fuel cells. Re-use of agricultural waste – animal feed, single cell protein production, fish production, composting, land application, industrial uses.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 546', 'Agric and Bioresources Engineering Contracts and Specification', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'second', 2, 'Common to all four Fifth-Year options. Engineering economy (Review of interest and depreciation estimation). Legal and professional relations in Agricultural and Bioresources engineering contracts. Estimation of Investment cost – Bill of Engineering Measurement (BEM). Recurrent costs – interest, depreciation, repairs and maintenance, insurance and taxes, machinery/equipment operating costs. Economic comparison of alternative projects. Management organizational forms – personal management, partial or general/whole contract, turn-key projects. Public procurement procedure – bid types (force account, LCB and ICB), bill preparation and bidding requirements, advertising, tendering, bid opening, bid evaluation. Contracts, work schedule, Stores management. Causes and avoidance of cost overrun. Project supervision. Contract and labour laws.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 548', 'Rural Roads and Farm Transportation', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'second', 3, 'Fifth-year Option Four (Structures and Environmental Engineering). Rural roads selection. Review of surveying. Road design. Inventorization. Routine and recurrent maintenance. Farm transport systems – standards and specifications. Farm transportation equipment and design.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true),
  ('ABE 592', 'Final Year Project', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Agricultural and Bioresources Engineering', '500 Level', 'second', 6, 'Common to all four Fifth-Year options. Supervised individual student project undertaken in research, development, design and/or construction and testing, to deepen knowledge, strengthen practical experience and encourage creativity and independent work. The student submits a written report for grading in content, and also makes an oral presentation before a panel of examiners for assessment in technical presentation.', '[]'::jsonb, 'UNN Faculty of Engineering official website (ABE Revised UG Programme, 2017)', true);
