-- =============================================================================
-- University of Nigeria, Nsukka -- Faculty of Arts
-- Department of Fine and Applied Arts
-- =============================================================================
-- Transcribed from the department's own official website. 239 rows.
--
-- 100-200 Level are core courses common to every student. At 300/400 Level,
-- the department splits into nine specialization options (Art Education,
-- Painting, Sculpture, Visual Communication Design, Textile Design, Fashion
-- Design, Ceramics, Art History) -- a student takes exactly one option, not
-- all nine, so every 300/400 Level course here is stored with
-- is_elective = true and a description naming which option it belongs to.
-- Course codes are reused across options (e.g. FAA 301 "Draughtsmanship I" is
-- common core reading within each option's own first semester, and FAA 385
-- "African Art I" appears in most options) -- this is exactly how the
-- department's own website lists them, not a transcription artifact.
--
-- The department's site publishes the course list but not per-course
-- syllabus descriptions or topic breakdowns, so no invented syllabus text is
-- added here.
-- =============================================================================

delete from public.course_outlines
 where institution = 'University of Nigeria, Nsukka'
   and department = 'Fine and Applied Arts';

insert into public.course_outlines
  (course_code, course_title, institution, faculty, department, level,
   semester, credit_units, description, topics, contributor_name, is_elective)
values
  ('FAA 101', 'Basic Drawing I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '100 Level', 'first', 3, '', '[]'::jsonb, 'Department official website', false),
  ('FAA 103', 'Two Dimensional Design I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '100 Level', 'first', 3, '', '[]'::jsonb, 'Department official website', false),
  ('FAA 105', 'Three Dimensional Design I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '100 Level', 'first', 3, '', '[]'::jsonb, 'Department official website', false),
  ('FAA 181', 'Art Appreciation', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '100 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('FAA 183', 'History of Nigerian Art', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '100 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('PHI 101', 'Introduction to Philosophy', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '100 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSP 101', 'The Use of English I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '100 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('FAA 102', 'Basic Drawing II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '100 Level', 'second', 3, '', '[]'::jsonb, 'Department official website', false),
  ('FAA 104', 'Two Dimensional Design II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '100 Level', 'second', 3, '', '[]'::jsonb, 'Department official website', false),
  ('FAA 106', 'Three Dimensional Design II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '100 Level', 'second', 3, '', '[]'::jsonb, 'Department official website', false),
  ('FAA 122', 'Basic Photography', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '100 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('FAA 180', 'Art and Society', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '100 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('THA 102', 'Practical Participation Orientation', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '100 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSP 102', 'The Use of English II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '100 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('FAA 201', 'Still-Life Drawing', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('FAA 203', 'Art and Environment', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('FAA 231', 'Introduction to Painting', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('FAA 241', 'Sculpture Processes: Modelling and Casting I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('FAA 281', 'Historical Survey of Western and Oriental Art I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('COS 101', 'Introduction to Computer Science', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('CED 341', 'Introduction to Entrepreneurship', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSP 105', 'Natural Science I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSP 201', 'Social Science I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('FAA 202', 'Figure Drawing', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('FAA 212', 'Orientation to Art Education', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('FAA 222', 'Visual Communication Design I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('FAA 262', 'Textile Design I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('FAA 272', 'Ceramics: Throwing and Modelling', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('FAA 282', 'Historical Survey of Western and Oriental Art II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('COS 304', 'Computer Application II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('CED 342', 'Business Development and Management', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSP 106', 'Natural Science II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSP 202', 'Social Science II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('FAA 301', 'Draughtsmanship I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Art Education option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 311', 'Curriculum and Methodology in Art Education', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 3, 'Art Education option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 313', 'Teaching Practice in Art I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Art Education option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 315', 'Approaches to Art Teaching', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Art Education option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 385', 'African Art I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Art Education option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 303', 'Research Techniques in Fine/Applied Arts', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Art Education option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 392', 'Project I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'second', 4, 'Art Education option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 394', 'SIWES', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'second', 15, 'Art Education option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 301', 'Draughtsmanship I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 303', 'Research Techniques in Fine and Applied Arts', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 305', 'Introduction to Mural Painting', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 331', 'Oil/Water-Based and Other Media Exploration', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 333', 'Landscape and Still-Life Painting', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 335', 'Painting Theory I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 337', 'Life Painting', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 339', 'Narrative Painting and Nigerian Painting Styles/Techniques', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 3, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 385', 'African Art I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 321', 'Print Making I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 392', 'Project I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'second', 4, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 394', 'SIWES', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'second', 15, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 301', 'Draughtsmanship I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 303', 'Research Techniques in Fine/Applied Arts', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 341', 'Sculpture Processes: Modelling and Casting II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 343', 'Sculpture Theory I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 345', 'Exploration of African Sculpture Ideas, Forms and Materials', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 3, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 347', 'Utility Wood Sculpture', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 3, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 349', 'Outdoor Sculpture Project', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 3, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 385', 'African Art I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 392', 'Project I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'second', 4, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 394', 'SIWES', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'second', 15, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 301', 'Draughtsmanship I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 303', 'Research Techniques in Fine/Applied Arts', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 321', 'Printmaking I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 323', 'Creative Photography', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 3, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 325', 'Computer Graphics I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 3, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 327', 'Visual Communication Design and Multimedia Visual Production', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 3, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 329', 'Visual Communication Design Theory I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 385', 'African Art I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 392', 'Project I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'second', 4, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 394', 'SIWES', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'second', 15, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 301', 'Draughtsmanship I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 303', 'Research Techniques in Fine/Applied Arts', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 353', 'History of Costumes I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 361', 'Textile Design II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 3, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 363', 'Computer Aided Design I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 3, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 365', 'Textile Theory I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 367', 'Woven Structures and Fibres I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 3, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 385', 'African Art I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 392', 'Project I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'second', 4, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 394', 'SIWES', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'second', 15, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 301', 'Draughtsmanship I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 303', 'Research Techniques in Fine/Applied Arts', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 351', 'Clothing Construction I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 3, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 353', 'History of Costumes I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 355', 'Fashion Design Illustration I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 361', 'Textile Design II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 3, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 363', 'Computer Aided Design I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 3, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 365', 'Textile Theory I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 385', 'African Art I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 392', 'Project I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'second', 4, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 394', 'SIWES', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'second', 15, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 301', 'Draughtsmanship I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 303', 'Research Techniques in Fine/Applied Arts', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 370', 'Ceramics Theory I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 371', 'Ceramic Throwing I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 3, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 373', 'Special Ceramics', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 375', 'Exploration of Ceramic Ideas, Forms and Materials', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 377', 'Ceramic Modelling I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 3, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 379', 'Industrial Ceramic Design I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 3, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 385', 'African Art I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 392', 'Project I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'second', 4, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 394', 'SIWES', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'second', 15, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 301', 'Draughtsmanship', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 303', 'Research Techniques in Fine and Applied Arts', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 381', 'Historical Survey of Western and Oriental Art III', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 3, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 383', 'Aspects of Western Art', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 3, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 385', 'African Art I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 2, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 387', 'Pre-Columbian and Oceanic Art and Culture', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 3, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 389', 'Study of Indigenous African Art and Architecture Forms', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'first', 3, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 392', 'Project I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'second', 4, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 394', 'SIWES', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '300 Level', 'second', 15, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 401', 'Advanced Drawing I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 431', 'Advanced Oil Painting', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 433', 'Portrait Painting', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 435', 'Advanced Landscape Painting', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 437', 'Abstract and Conceptual Painting', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 439', 'Advanced Water Colour Painting', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 480', 'Fine Art Criticism I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 487', 'African Art II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 402', 'Advanced Drawing II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 404', 'Professional Practices in Fine and Applied Arts', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 430', 'Advanced Painting and Colour Language', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 432', 'Advanced Life Painting', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 434', 'Human Image and Metaphor', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 436', 'Mixed Media Painting', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 438', 'Painting Theory II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 485', 'Modern African Art', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 484', 'African Architecture', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 492', 'Project II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 4, 'Painting option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 401', 'Advanced Drawing I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 441', 'Sculpture Processes: Modelling and Casting III', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 443', 'Sculpture Process: Carving II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 445', 'Sculpture Theory II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 447', 'Special Sculpture Project', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 449', 'Space Organisation', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 480', 'Fine Art Criticism I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 487', 'African Art II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 402', 'Advanced Drawing II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 404', 'Professional Practices in Fine and Applied Arts', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 442', 'Sculpture: Mixed Media', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 3, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 444', 'Advanced Exploration of African Sculpture Ideas, Forms and Materials', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 3, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 446', 'Living Sculpture', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 485', 'Modern African Art I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 484', 'African Architecture', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 492', 'Project II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 4, 'Sculpture option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 401', 'Advanced Drawing I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 421', 'Printmaking II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 423', 'Typographic Design', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 425', 'Computer Graphics II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 427', 'Visual Communication Design III', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 429', 'Visual Communication Design Theory II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 480', 'Fine Art Criticism I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 487', 'African Art II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 402', 'Advanced Drawing II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 404', 'Professional Practices in Fine and Applied Arts', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 422', 'Illustration, Editorial and Advertising Design', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 3, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 424', 'Product Design I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 3, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 426', 'Colour and Design', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 484', 'African Architecture', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 485', 'Modern African Art', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 492', 'Project II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 4, 'Visual Communication Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 401', 'Advanced Drawing I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 421', 'Print Making II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 459', 'History of Costumes II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 461', 'Textile Design III', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 463', 'Woven Structures and Fibres II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 465', 'Textile Design Theory II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 467', 'Computer Aided Design II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 480', 'Fine Art Criticism I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 487', 'African Art II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 402', 'Advanced Drawing II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 404', 'Professional Practices in Fine and Applied Arts', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 462', 'Advanced Exploration of African Textile Ideas, Forms and Materials', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 3, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 464', 'Woven Structures and Fibres III', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 3, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 484', 'African Architecture', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 485', 'Modern African Art', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 492', 'Project II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 4, 'Textile Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 401', 'Advanced Drawing II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 451', 'Clothing Construction II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 457', 'Pattern Drafting and Studio Practice I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 455', 'Fashion Design Illustration II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 459', 'History of Costumes II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 465', 'Textile Theory II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 467', 'Computer Aided Design II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 480', 'Fine Art Criticism I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 487', 'African Art II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 402', 'Advanced Drawing II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 404', 'Professional Practices in Fine and Applied Arts', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 458', 'Pattern Drafting and Studio Practice II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 3, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 454', 'Advanced Exploration of African Fashion Design Ideas, Forms and Materials', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 3, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 484', 'African Architecture', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 485', 'Modern African Art', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 492', 'Project II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 4, 'Fashion Design option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 401', 'Advanced Drawing I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 470', 'Ceramics Theory II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 471', 'Ceramic Throwing II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 473', 'Kiln Design and Firing', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 477', 'Ceramic Modelling II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 479', 'Industrial Ceramic Design II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 480', 'Fine Art Criticism I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 487', 'African Art II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 402', 'Advanced Drawing II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 404', 'Professional Practices in Fine/Applied Arts', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 472', 'Architectural Ceramics', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 474', 'Mixed Media Ceramics', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 475', 'Advanced Exploration of African Ceramic Ideas, Forms and Materials', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 3, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 484', 'African Architecture', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 485', 'Modern African Art', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 492', 'Project II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 4, 'Ceramics option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 401', 'Advanced Drawing I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Art Education option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 411', 'Advanced Studies in Art Education', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Art Education option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 413', 'Teaching Practice in Art II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Art Education option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 415', 'Special Readings in Indigenous Art Forms and Materials', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Art Education option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 480', 'Fine Art Criticism I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Art Education option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 487', 'African Art II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Art Education option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 402', 'Advanced Drawing II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Art Education option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 412', 'Curriculum and Instruction for Art Education', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 3, 'Art Education option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 484', 'African Architecture', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Art Education option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 485', 'Modern African Art', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Art Education option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 492', 'Project II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 4, 'Art Education option.', '[]'::jsonb, 'Department official website', true),
  ('EDU 211', 'Educational Psychology I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Art Education option.', '[]'::jsonb, 'Department official website', true),
  ('EDU 224', 'Educational Technology', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Art Education option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 401', 'Advanced Drawing I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 481', 'Special Readings in Art History I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 480', 'Fine Art Criticism I', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 484', 'Advanced Field Exploration of African Art and Architecture Forms', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 487', 'African Art II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 2, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 488', 'Modern Western Art', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 489', 'Problems in African Art History', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'first', 3, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 402', 'Advanced Drawing II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 404', 'Professional Practices in Fine and Applied Arts', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 483', 'Fine Art Criticism II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 482', 'Special Readings in Art History II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 3, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 484', 'African Architecture', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 485', 'Modern African Art', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 2, 'Art History option.', '[]'::jsonb, 'Department official website', true),
  ('FAA 492', 'Project II', 'University of Nigeria, Nsukka', 'Faculty of Arts', 'Fine and Applied Arts', '400 Level', 'second', 4, 'Art History option.', '[]'::jsonb, 'Department official website', true);
