-- Additional questions for the CBT subject formerly labelled PHY122, now
-- displayed as PHY104 (subject_id kept as phy-122-heat-waves-optics
-- internally -- unchanged on purpose, so existing entitlements/local
-- progress/free-trial flags keyed on it are not broken by the rename;
-- only subject_name was updated to show PHY104).
--
-- 62 questions transcribed and independently SOLVED (not copied
-- from an answer key -- this source booklet, a real Continuous
-- Assessment practice set the user supplied, has no worked solutions or
-- answer key printed, just blank answer boxes) from a 19-page scan,
-- across 3 parallel passes covering pages 1-7, 8-13, 14-19. Topics:
-- Harmonic Motion and Vibrations, Wave Motion, Sound Waves, Geometrical
-- Optics, Wave Theory of Light.
--
-- QA: zero structural errors, zero meta-references, zero middle-dot
-- characters, zero bare-slash-in-math (checked with a stricter digit/
-- digit pattern after the unit-abbreviation false positives like "m/s"
-- were ruled out), zero overlap with the existing 106-question bank.
-- 8 questions were dropped across the 3 passes where the computed
-- physics answer didn't cleanly match any of the 4 given options even
-- after a recheck (rather than force-picking a wrong option). One
-- question's answer was corrected after re-checking the physics myself:
-- a "2nd harmonic of a closed pipe" question had been answered as
-- 2*f1 -- but a pipe closed at one end only supports ODD harmonics
-- (f1, 3f1, 5f1...), so 2*f1 isn't a real mode of that pipe at all; the
-- correct 2nd resonant harmonic is 3*f1, corrected to match.

insert into public.cbt_questions
  (subject_id, subject_name, institution, faculty, department, level,
   question, options, correct_index, explanation, topic, is_general,
   semester, units)
values
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Which of the following is a necessary condition for a motion to be simple harmonic?', '["Acceleration is constant", "Acceleration is proportional to velocity", "Acceleration is proportional to displacement", "Acceleration is independent of velocity and displacement"]'::jsonb, 2, 'Simple harmonic motion is defined by the equation $a = -\omega^2 x$, meaning the acceleration is always directly proportional to the displacement from the equilibrium position (and directed toward it). This proportionality between acceleration and displacement is the defining necessary condition for SHM.', 'Simple Harmonic Motion — Definition', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A simple harmonic motion has a displacement $y$ which is a function of time $(t)$ and is given by $y = 2\sin(0.4t + 0.5)$; all terms are in SI units. Find the period of the motion.', '["$1.23$ secs", "$16.24$ secs", "$20.56$ secs", "$15.7$ secs"]'::jsonb, 3, 'Comparing $y = 2\sin(0.4t + 0.5)$ with $y = A\sin(\omega t + \phi)$ gives angular frequency $\omega = 0.4\text{ rad/s}$. The period is $T = \frac{2\pi}{\omega} = \frac{2\pi}{0.4} = 15.7$ secs.', 'Simple Harmonic Motion — Period', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Find the time for one revolution (period) and the radius of the circle of a conical pendulum if the string that is 100 cm long makes an angle $30^{\circ}$ with the vertical.', '["$2.31$ s", "$1.67$ s", "$1.87$ s", "$1.43$ s"]'::jsonb, 2, 'For a conical pendulum, the period is $T = 2\pi\sqrt{\frac{L\cos\theta}{g}}$. With $L = 1\text{ m}$, $\theta = 30^{\circ}$ (so $\cos\theta = 0.866$) and $g = 9.8\text{ m/s}^2$, $T = 2\pi\sqrt{\frac{0.866}{9.8}} = 2\pi\sqrt{0.0884} = 2\pi(0.297) \approx 1.87$ s.', 'Conical Pendulum — Period', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Which of the following is the effect of damping in oscillatory motions?', '["resonance", "decreasing amplitude", "increasing period", "decreasing wavelength"]'::jsonb, 1, 'Damping removes energy from an oscillating system (through friction, air resistance, or similar resistive forces), so the amplitude of the oscillation steadily decreases over time while the frequency stays approximately the same for light damping.', 'Damped Oscillations', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A body is suspended by a thread of length 100 cm. The body is pulled sideways until it makes an angle $30^{\circ}$ with the vertical and then released. Calculate the maximum velocity of the body. (Take $g = 10\text{ m/s}^2$)', '["$1.64$ m/s", "$3.16$ m/s", "$2.00$ m/s", "$4.00$ m/s"]'::jsonb, 0, 'Using energy conservation, the maximum speed at the lowest point is $v_{max} = \sqrt{2gL(1-\cos\theta)}$. With $L = 1\text{ m}$, $g = 10\text{ m/s}^2$ and $\cos 30^{\circ} = 0.866$: $v_{max} = \sqrt{2(10)(1)(0.134)} = \sqrt{2.68} \approx 1.64$ m/s.', 'Pendulum — Energy Conservation', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'The average life of a Nigerian is 56 years. Find the number of times the human heart beats in the life of a Nigerian if the heart beats once in 0.8 seconds.', '["$20.4 \\times 10^{9}$", "$2.2 \\times 10^{9}$", "$2.5 \\times 10^{9}$", "$6.1 \\times 10^{9}$"]'::jsonb, 1, 'The total lifetime in seconds is $56 \times 365 \times 24 \times 3600 = 1.766 \times 10^{9}\text{ s}$. Dividing by the 0.8 s period per beat gives the number of beats: $\frac{1.766 \times 10^{9}}{0.8} \approx 2.2 \times 10^{9}$ beats.', 'Period and Frequency — Applied Problem', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A simple pendulum of length L cm makes 60 oscillations in 2 minutes. The frequency and period of the oscillation respectively, are:', '["$2.0$ Hz; $0.5$ s", "$2.0$ Hz; $2.0$ s", "$0.5$ Hz; $2.0$ s", "$6.0$ Hz; $0.5$ s"]'::jsonb, 2, 'The total time is $2$ minutes $= 120$ s for $60$ oscillations, so the frequency is $f = \frac{60}{120} = 0.5\text{ Hz}$. The period is the reciprocal, $T = \frac{1}{f} = 2.0$ s.', 'Simple Pendulum — Frequency and Period', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A body driven by an external periodic force is said to be at resonance only if', '["the magnitude of the external force is maximum", "the amplitude of oscillation is maximum", "the frequency of the external force is maximum", "the natural frequency of the body is maximum"]'::jsonb, 1, 'Resonance occurs when the driving frequency matches the natural frequency of the system, which causes energy to be transferred most efficiently into the oscillator so that its amplitude of oscillation becomes maximum.', 'Resonance', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Which of the following motions is not simple harmonic in nature?', '["a loaded test tube oscillating in water", "a child oscillating on a spring bed", "two boys playing a see-saw", "the earth revolving around the sun"]'::jsonb, 3, 'A loaded test tube bobbing in water and a mass on a spring both have a restoring force proportional to displacement, so they are simple harmonic. The earth''s revolution around the sun is uniform circular motion at constant speed along a near-fixed orbit, not a back-and-forth oscillation with a linear restoring force, so it is not simple harmonic.', 'Identifying Simple Harmonic Motion', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A small grasshopper of mass 5 g caught in a spider''s web oscillates with simple harmonic motion. If the web has a force constant of 0.1 N/m, find the period of oscillation of the grasshopper.', '["$6.3$ s", "$2.0$ s", "$0.5$ s", "$1.4$ s"]'::jsonb, 3, 'For a mass-spring system, $T = 2\pi\sqrt{\frac{m}{k}}$. With $m = 5\text{ g} = 0.005\text{ kg}$ and $k = 0.1\text{ N/m}$: $T = 2\pi\sqrt{\frac{0.005}{0.1}} = 2\pi\sqrt{0.05} = 2\pi(0.2236) \approx 1.4$ s.', 'Mass-Spring System — Period', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'The needle of a sewing machine oscillates up and down through a piece of cloth stretched midway between two points that are 10 cm apart. The needle makes 100 oscillations in 10 seconds. The amplitude of oscillation of the needle is', '["$10.0$ cm", "$5.0$ cm", "$20.0$ cm", "$0.5$ cm"]'::jsonb, 1, 'The needle oscillates between two points 10 cm apart, with the cloth positioned at the midpoint (the equilibrium position). The amplitude is the distance from the equilibrium position to either extreme, which is half the total span: $\frac{10}{2} = 5.0$ cm.', 'Simple Harmonic Motion — Amplitude', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A progressive wave is given by: $y = 3.0\sin(200\pi t + 0.4\pi x)$. What is the amplitude of the wave?', '["$5$ m", "$0.4$ m", "$200$ m", "$3.0$ m"]'::jsonb, 3, 'Comparing $y = 3.0\sin(200\pi t + 0.4\pi x)$ with the general progressive wave equation $y = A\sin(\omega t + kx)$, the amplitude is simply the coefficient in front of the sine function: $A = 3.0$ m.', 'Progressive Wave Equation — Amplitude', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Which of the following has the longest wavelength and the lowest frequency?', '["Radio waves", "Microwaves", "X-rays", "Gamma-rays"]'::jsonb, 0, 'Across the electromagnetic spectrum, wavelength and frequency are inversely related by $c = f\lambda$. Radio waves sit at the low-frequency, long-wavelength end of the spectrum, well below microwaves, X-rays, and gamma-rays, which have progressively shorter wavelengths and higher frequencies.', 'Electromagnetic Spectrum', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A travelling wave has a wavelength of 20 cm and travels with a speed $200\text{ cm/s}$, what is the frequency of the wave?', '["$100$ Hz", "$200$ Hz", "$500$ Hz", "$10$ Hz"]'::jsonb, 3, 'The wave speed relates to frequency and wavelength by $v = f\lambda$, so $f = \frac{v}{\lambda}$. Converting to consistent units, $v = 2\text{ m/s}$ and $\lambda = 0.2\text{ m}$, giving $f = \frac{2}{0.2} = 10$ Hz.', 'Wave Speed, Frequency and Wavelength', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'The followings are properties of electromagnetic radiation except', '["It can show interference and diffraction", "It is unaffected by electric and magnetic fields", "It is propagated by constant electric and magnetic fields oscillating parallel to each other", "It may be polarized"]'::jsonb, 2, 'Electromagnetic waves genuinely show interference, diffraction, and polarization, and their straight-line propagation is not deflected by external static electric or magnetic fields. However, the oscillating electric and magnetic field components of an EM wave are mutually perpendicular to each other (and to the direction of propagation), not parallel, making that statement the false one.', 'Electromagnetic Wave Properties', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Which of the following is true about all electromagnetic waves?', '["they are visible to the human eye", "they carry the same amount of energy", "they travel with the same speed in a vacuum", "they are transverse or longitudinal in nature"]'::jsonb, 2, 'All electromagnetic waves, regardless of frequency or wavelength, travel through a vacuum at the same speed, the speed of light $c \approx 3 \times 10^{8}\text{ m/s}$. They are not all visible, they carry different energies (energy depends on frequency via $E = hf$), and they are always transverse, never longitudinal.', 'Electromagnetic Waves — Properties', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Which of the following does not originate from superposition of waves?', '["Interference", "Doppler effect", "beating", "standing wave"]'::jsonb, 1, 'Interference, beating, and standing waves all arise from the superposition (addition) of two or more overlapping waves. The Doppler effect, in contrast, is a change in observed frequency caused by relative motion between a source and an observer, and does not involve superposition of waves at all.', 'Wave Superposition', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Which of the following is correct about sound and light waves?', '["Sound is both transverse and longitudinal while light is only transverse in nature", "light is electromagnetic and longitudinal while sound is mechanical and transverse", "light is electromagnetic and transverse while sound is mechanical and longitudinal", "sound can travel through a vacuum while light cannot."]'::jsonb, 2, 'Light is an electromagnetic wave, requiring no medium, and its oscillations are always transverse to the direction of travel. Sound is a mechanical wave that requires a material medium, and it propagates through compressions and rarefactions, making it a longitudinal wave.', 'Sound vs Light Wave Properties', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'The wavelength of visible light ranges from 400 nm to 700 nm. The wavelength of radio wave is therefore', '["shorter than 400 nm", "longer than 700 nm", "shorter than 700 nm", "500 nm"]'::jsonb, 1, 'On the electromagnetic spectrum, radio waves lie beyond the red end of the visible range, having much lower frequency and correspondingly much longer wavelength than any visible light, so radio wave wavelengths are longer than the 700 nm upper bound of visible light.', 'Electromagnetic Spectrum — Wavelength Ordering', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'All of the above are conditions for obtaining a stationary wave except', '["The two sources have the same frequency", "The progressive waves from the two sources travel in the same direction", "Amplitudes of the waves are the same", "The progressive waves from the two sources travel in opposite directions"]'::jsonb, 1, 'A stationary (standing) wave forms when two waves of equal frequency and equal amplitude travel through the same medium in opposite directions and superpose. Traveling in the same direction is therefore not a condition for a stationary wave, so this is the exception.', 'Conditions for Stationary Waves', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A progressive wave with a wavelength of 30 cm is propagating through an elastic medium. If two points are 15 cm apart on the path of the wave, what is the phase difference between the two points?', '["$\\frac{\\pi}{4}$", "$\\frac{\\pi}{2}$", "$\\pi$", "$2\\pi$"]'::jsonb, 2, 'The phase difference is given by $\Delta\phi = \frac{2\pi}{\lambda}\Delta x$. Substituting $\lambda = 30\text{ cm}$ and $\Delta x = 15\text{ cm}$ gives $\Delta\phi = \frac{2\pi}{30}\times 15 = \pi$.', 'Phase Difference of a Wave', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A wave packet has a dispersion relation of the form: $\omega = 2k^2$. Calculate the group velocity of the wave packet if the angular wave number is $5\text{ m}^{-1}$.', '["20.0 m/s", "10.0 m/s", "2.0 m/s", "5.0 m/s"]'::jsonb, 0, 'The group velocity is $v_g = \frac{d\omega}{dk} = 4k$. Substituting $k = 5\text{ m}^{-1}$ gives $v_g = 4\times 5 = 20.0\text{ m/s}$.', 'Group Velocity of a Wave Packet', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A wave pulse on the surface of a still water completes four cycles before hitting an obstacle placed 12 m away from the source of the pulse 10 seconds later. The wavelength of the wave pulse described above is', '["1.2 m", "12.0 m", "3.0 m", "4.0 m"]'::jsonb, 2, 'The pulse travels 12 m while completing 4 full cycles, so each wavelength spans $\frac{12}{4} = 3.0\text{ m}$.', 'Wave Pulse Properties', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A wave pulse on the surface of a still water completes four cycles before hitting an obstacle placed 12 m away from the source of the pulse 10 seconds later. The period of the wave pulse described above is', '["10.0 s", "2.5 s", "0.4 s", "40.0 s"]'::jsonb, 1, 'The period is the total time divided by the number of cycles completed: $T = \frac{10\text{ s}}{4} = 2.5\text{ s}$.', 'Wave Pulse Properties', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A wave pulse on the surface of a still water completes four cycles before hitting an obstacle placed 12 m away from the source of the pulse 10 seconds later. The speed of the wave pulse described above is', '["120.0 m/s", "2.5 m/s", "48.0 m/s", "1.2 m/s"]'::jsonb, 3, 'The speed is the total distance divided by the total time: $v = \frac{12\text{ m}}{10\text{ s}} = 1.2\text{ m/s}$. This is consistent with $v = f\lambda = \frac{3.0\text{ m}}{2.5\text{ s}} = 1.2\text{ m/s}$.', 'Wave Pulse Properties', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A rod of metal of Young''s modulus $2.6\times 10^{11}\text{ Nm}^{-2}$ and density $8.17\times 10^{3}\text{ kgm}^{-3}$ is clamped at its mid-point and excited so that it vibrates longitudinally in its fundamental mode at a frequency of 5640 Hz. Calculate the speed of sound in the metal rod', '["5640 m/s", "5657 m/s", "4557 m/s", "3456 m/s"]'::jsonb, 0, 'The speed of sound in a solid rod is $v = \sqrt{\frac{E}{\rho}}$. Substituting $E = 2.6\times 10^{11}\text{ Nm}^{-2}$ and $\rho = 8.17\times 10^{3}\text{ kgm}^{-3}$ gives $v = \sqrt{3.182\times 10^{7}} \approx 5640\text{ m/s}$.', 'Speed of Sound in a Solid Rod', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Two tuning forks of frequencies 540 Hz and 520 Hz are sounded together in a musical context. Find the frequency of the beats produced', '["540 Hz", "520 Hz", "20 Hz", "1060 Hz"]'::jsonb, 2, 'The beat frequency equals the difference between the two frequencies: $f_{beat} = |540 - 520| = 20\text{ Hz}$.', 'Beats', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Two strings in a piano are 50 cm and 52 cm long, respectively. If the strings are played together to produce their fundamental notes in a music contest, find the frequency of the beats produced if the speed of sound in the strings is $400\text{ ms}^{-1}$', '["415 Hz", "400 Hz", "385 Hz", "15 Hz"]'::jsonb, 3, 'The fundamental frequency of a string fixed at both ends is $f = \frac{v}{2L}$. For the 50 cm string, $f_1 = \frac{400}{2\times 0.50} = 400\text{ Hz}$; for the 52 cm string, $f_2 = \frac{400}{2\times 0.52} \approx 384.6\text{ Hz}$. The beat frequency is $f_1 - f_2 \approx 15\text{ Hz}$.', 'Beats Between Two Strings', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Calculate the sound level of a cannon shot that has intensity of $10^{-7}\text{ Wm}^{-2}$ if the threshold of hearing at the same frequency is $10^{-12}\text{ Wm}^{-2}$.', '["7 dB", "12 dB", "50 dB", "70 dB"]'::jsonb, 2, 'Sound level is $\beta = 10\log_{10}\left(\frac{I}{I_0}\right)$. Substituting $I = 10^{-7}\text{ Wm}^{-2}$ and $I_0 = 10^{-12}\text{ Wm}^{-2}$ gives $\beta = 10\log_{10}(10^{5}) = 10\times 5 = 50\text{ dB}$.', 'Sound Intensity Level', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'In a resonance tube experiment using a tuning fork of frequency 300 Hz, the positions of first and second resonance are 40 cm apart. Calculate the speed of sound in air', '["800 m/s", "400 m/s", "360 m/s", "240 m/s"]'::jsonb, 3, 'The separation between successive resonance positions in a resonance tube equals half a wavelength, so $\lambda = 2\times 40\text{ cm} = 80\text{ cm} = 0.8\text{ m}$. The speed of sound is $v = f\lambda = 300\times 0.8 = 240\text{ m/s}$.', 'Resonance Tube Experiment', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'The frequency of a Road Safety''s car sound wave is 400 Hz. Calculate the frequency received by a stationary observer if the car approaches the observer at a speed of $80\text{ ms}^{-1}$ (Speed of sound in air = $330\text{ ms}^{-1}$)', '["5200 Hz", "528 Hz", "500 Hz", "529 Hz"]'::jsonb, 1, 'For a moving source approaching a stationary observer, $f'' = f\left(\frac{v}{v - v_s}\right)$. Substituting $f = 400\text{ Hz}$, $v = 330\text{ ms}^{-1}$, and $v_s = 80\text{ ms}^{-1}$ gives $f'' = 400\times\frac{330}{250} = 528\text{ Hz}$.', 'Doppler Effect', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'If the speed of sound in air at $10^{\circ}\text{C}$ is 337 m/s, what is the wavelength of a 1.5 kHz sound wave?', '["224.7 m", "0.0225 m", "505.5 m", "0.225 m"]'::jsonb, 3, 'The wavelength is $\lambda = \frac{v}{f} = \frac{337}{1500} \approx 0.2247\text{ m}$, which rounds to $0.225\text{ m}$.', 'Wavelength from Speed and Frequency', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A trumpet is 0.33 m long and open at both ends. Calculate the frequency of the fundamental note if the end corrections are assumed negligible (Speed of sound in air is $330\text{ ms}^{-1}$)', '["750 Hz", "250 Hz", "300 Hz", "500 Hz"]'::jsonb, 3, 'For a pipe open at both ends, the fundamental frequency is $f = \frac{v}{2L}$. Substituting $v = 330\text{ m/s}$ and $L = 0.33\text{ m}$ gives $f = \frac{330}{2\times 0.33} = 500\text{ Hz}$.', 'Fundamental Frequency of an Open Pipe', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Which of the following is a practical application of echo?', '["determination of the speed of sound in air", "determination of the density of a medium", "determination of the size of an obstacle", "determination of the refractive index of a medium"]'::jsonb, 0, 'An echo forms when sound reflects off a distant surface and returns to the source. By measuring the time taken for the echo to return over a known distance, the speed of sound in air can be determined using $v = \frac{2d}{t}$, which is a classic practical application of echoes.', 'Practical Application of Echo', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A drunk physics student blows air into an empty beer bottle of height 30 cm. Given that the speed of sound in air is 340 m/s, calculate the frequency of the $2^{nd}$ harmonic.', '["283 Hz", "850 Hz", "566 Hz", "1133 Hz"]'::jsonb, 1, 'A bottle blown across its opening behaves as a pipe closed at one end, with fundamental frequency $f_1 = \frac{v}{4L} = \frac{340}{4\times 0.30} \approx 283.3\text{ Hz}$. A closed pipe only supports odd-numbered harmonics of the fundamental ($f_1, 3f_1, 5f_1, \ldots$), so the frequency actually one step above the fundamental -- its second resonant harmonic -- is $3f_1 \approx 850\text{ Hz}$, not $2f_1$, since $2f_1$ is not a mode this pipe can produce at all.', 'Harmonics in a Closed Pipe', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A police siren sounding a note of frequency 200 Hz approaches a stationary observer with a speed of $50\text{ m/s}$. If the speed of sound in air is $400\text{ m/s}$, calculate the frequency of the note detected by the observer.', '["229 Hz", "200 Hz", "400 Hz", "800 Hz"]'::jsonb, 0, 'For a moving source approaching a stationary observer, $f'' = f\left(\frac{v}{v - v_s}\right)$. Substituting $f = 200\text{ Hz}$, $v = 400\text{ m/s}$, and $v_s = 50\text{ m/s}$ gives $f'' = 200\times\frac{400}{350} \approx 229\text{ Hz}$.', 'Doppler Effect', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Which of the following is a design practice to minimize reverberation in record studios?', '["Polishing the walls", "Reducing the number of windows and doors", "Padding the walls", "Illuminating the room"]'::jsonb, 2, 'Reverberation is caused by repeated reflection of sound off hard, reflective surfaces. Padding the walls with soft, absorptive material reduces reflected sound energy and therefore minimizes reverberation, unlike polishing (which increases reflection) or the other unrelated options.', 'Reverberation Control', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'The threshold of hearing is $1.0\times 10^{-12}\text{ W/m}^2$. If the sound level of a gunshot fired 500 m away from an observer is 0 dB, then, the intensity of the sound at that point is', '["$1.0\\times 10^{-12}\\text{ W/m}^2$", "$1.0\\times 10^{12}\\text{ W/m}^2$", "$0.0\\text{ W/m}^2$", "$10.0\\times 10^{-10}\\text{ W/m}^2$"]'::jsonb, 0, 'A sound level of 0 dB is defined as the point where $\beta = 10\log_{10}\left(\frac{I}{I_0}\right) = 0$, which means $I = I_0$. Since the threshold of hearing is $I_0 = 1.0\times 10^{-12}\text{ W/m}^2$, the intensity at that point is $1.0\times 10^{-12}\text{ W/m}^2$.', 'Sound Intensity Level', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'The speed of sound wave (v) in a stretched string varies with the tension (T). If the tension in a certain string is doubled, the speed of sound in the string would be', '["doubled", "reduced by half", "increase by a factor of $\\sqrt{2}$", "decrease by a factor of $\\sqrt{2}$"]'::jsonb, 2, 'The speed of a wave on a stretched string is $v = \sqrt{\frac{T}{\mu}}$. Doubling the tension gives $v'' = \sqrt{\frac{2T}{\mu}} = \sqrt{2}\, v$, so the speed increases by a factor of $\sqrt{2}$.', 'Speed of Wave on a String', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A boy made a pinhole camera out of a cardboard box that is 60cm long. What would be the height of the image of a man that is 1.5m tall standing 10m in front of the pinhole?', '["60cm", "10cm", "9 cm", "15cm"]'::jsonb, 2, 'For a pinhole camera the image height scales with the ratio of image distance to object distance: $h_i = h_o \times \frac{v}{u} = 1.5\text{m} \times \frac{0.6\text{m}}{10\text{m}} = 0.09\text{m} = 9\text{ cm}$.', 'Pinhole Camera Image Scaling', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'White light can be dispersed through a triangular glass prism because', '["different colours are contained inside the prism", "different colours travel with different speeds in the prism", "different colours posses the same wavelength", "the frequency of light changes in the prism"]'::jsonb, 1, 'Dispersion occurs because the refractive index of glass depends on wavelength, so each colour travels at a different speed $v = \frac{c}{n}$ inside the prism, causing them to refract by different amounts and separate.', 'Dispersion of Light in a Prism', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'An object is paced in front of a converging lens and gives a real image five times the size of the object. When the object is moved 6cm along the axis of the lens, a real image twice the size of the object is obtained. Find the focal length of the lens', '["10 cm", "20 cm", "30 cm", "40 cm"]'::jsonb, 1, 'Using $\frac{1}{v}+\frac{1}{u}=\frac{1}{f}$ with magnification $m=\frac{v}{u}$: for $m_1=5$, $u_1=\frac{6f}{5}$; for $m_2=2$, $u_2=\frac{3f}{2}$. The object shift is $u_2-u_1=\frac{3f}{2}-\frac{6f}{5}=\frac{3f}{10}=6\text{cm}$, giving $f=20\text{ cm}$.', 'Thin Lens Equation and Magnification', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'When a graph of 1/v is plotted against 1/u for a curved mirror, the resulting intercept yields', '["object distance", "focal length", "magnification", "image distance"]'::jsonb, 1, 'The mirror equation $\frac{1}{v}=-\frac{1}{u}+\frac{1}{f}$ is a straight line of slope $-1$ whose intercept on either axis equals $\frac{1}{f}$, so the intercept is used to determine the focal length.', 'Mirror Equation Graphical Method', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'If the refractive indices from air to glass and from air to water are respectively 1.50 and 1.33, calculate the critical angle for a water-glass surface', '["47.5°", "41.0°", "62.5°", "72.8°"]'::jsonb, 2, 'Light travelling from the denser glass into water totally internally reflects when $\sin\theta_c=\frac{n_{water}}{n_{glass}}=\frac{1.33}{1.50}=0.887$, giving $\theta_c=\arcsin(0.887)\approx 62.5°$.', 'Critical Angle Between Two Media', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'When a lady stands 2m in front of a large concave mirror of focal length 5m, her image would be', '["real and inverted", "real and erect", "virtual and erect", "virtual and inverted"]'::jsonb, 2, 'With $u=2\text{m} < f=5\text{m}$, using $\frac{1}{v}=\frac{1}{f}-\frac{1}{u}=\frac{1}{5}-\frac{1}{2}=-\frac{3}{10}$ gives $v=-3.33\text{m}$ (behind the mirror), so the image is virtual, and the magnification $m=-\frac{v}{u}=+1.67$ is positive, meaning it is also erect.', 'Concave Mirror Image Formation', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'The distance of distinct vision of a short sighted student is 10 m. The focal length and type of the corrective lens he requires to view an object placed 20m away are', '["20m: convex lens", "20m: concave lens", "10m: convex lens", "10m: concave lens"]'::jsonb, 1, 'A short-sighted eye has a far point of 10m, so a diverging lens must form a virtual image of the distant object at that far point: $\frac{1}{f}=\frac{1}{v}-\frac{1}{u}=\frac{1}{-10}-\frac{1}{-20}=-0.05$, giving $f=-20\text{m}$, i.e. a 20m concave (diverging) lens.', 'Corrective Lens for Short Sight', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A picture of height 3cm is to be enlarged to 15cm by projecting it onto a screen placed 200cm away from the projecting lens. The focal length of the lens would be', '["1.33 cm", "33.3 cm", "40.00 cm", "3.33 cm"]'::jsonb, 1, 'The magnification is $m=\frac{15}{3}=5=\frac{v}{u}$ with $v=200\text{cm}$, so $u=\frac{200}{5}=40\text{cm}$. Then $\frac{1}{f}=\frac{1}{v}+\frac{1}{u}=\frac{1}{200}+\frac{1}{40}=0.03$, giving $f=33.3\text{ cm}$.', 'Projector Lens Magnification', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Mirage is an optical illusion that results from', '["diffraction of light", "superposition of light", "interference of light", "total internal reflection of light"]'::jsonb, 3, 'A mirage forms because layers of air near a hot surface have progressively lower refractive index, bending light rays until they undergo total internal reflection, which the eye interprets as a reflective surface such as water.', 'Mirage and Total Internal Reflection', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'For a ray of light in air incident at an angle of 42° on the boundary with water, determine the angle of refraction if the refractive index of air to water is 0.75', '["30°", "30.17°", "32°", "30.4°"]'::jsonb, 1, 'Using Snell''s law $\sin\theta_r = 0.75 \times \sin\theta_i = 0.75\times\sin(42°)=0.75\times0.669=0.502$, so $\theta_r=\arcsin(0.502)\approx 30.17°$.', 'Snell''s Law of Refraction', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A plastic bucket of depth 50cm is filled to the brim with petrol. If the bottom of the bucket appears to be displaced by 10cm when viewed through the petrol, what is the refractive index of petrol?', '["1.33", "1.50", "5.00", "1.25"]'::jsonb, 3, 'The apparent depth is $50-10=40\text{cm}$, and the refractive index is $n=\frac{\text{real depth}}{\text{apparent depth}}=\frac{50}{40}=1.25$.', 'Apparent Depth and Refractive Index', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A thin lens is made of glass of refractive index 1.50cm with radii of curvature 20cm and 25cm respectively. Determine its focal length', '["20cm", "22cm", "21cm", "23cm"]'::jsonb, 1, 'Using the lensmaker''s equation $\frac{1}{f}=(n-1)\left(\frac{1}{R_1}-\frac{1}{R_2}\right)=(0.5)\left(\frac{1}{20}-\frac{1}{-25}\right)=0.5\times0.09=0.045$, giving $f\approx 22\text{ cm}$.', 'Lensmaker''s Equation', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'In long sightedness the blurred vision is as a result of image formation', '["behind the retina", "on the retina", "in front of the retina", "on the cornea"]'::jsonb, 0, 'Long-sightedness (hyperopia) occurs because the eyeball is too short or the lens too weak, so light converges to a focus behind the retina, producing a blurred image on the retina itself.', 'Long Sightedness (Hyperopia)', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'An engineer designed a television camera with lens diameter of 10 cm and a focal length of 20 cm. The f-number of the camera is', '["0.5", "2.0", "0.25", "4.0"]'::jsonb, 1, 'The f-number is defined as $N=\frac{f}{D}=\frac{20\text{cm}}{10\text{cm}}=2.0$.', 'f-number of a Camera Lens', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A beam of light travelling in air suddenly strikes a glass window with angle of incidence of 35°. If part of the beam is reflected off the surface of the glass window, the angle between the incident and reflected beam is', '["35°", "17.5°", "70°", "90°"]'::jsonb, 2, 'By the law of reflection the reflected ray makes the same angle, $35°$, with the normal as the incident ray, so the angle between the incident and reflected beams, measured across the normal, is $2\times35°=70°$.', 'Law of Reflection', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'In crystal growth laboratories, X-ray is often used in the study of crystal structure because', '["X-ray is very energetic", "X-ray has high amplitude", "wavelength of X-ray is of order of inter-atomic spacing", "X-ray travels with seed of light"]'::jsonb, 2, 'X-rays are used to probe crystal structure because their wavelength (of order $0.1\text{ nm}$) is comparable to the spacing between atoms in a crystal lattice, allowing them to diffract off the atomic planes.', 'X-ray Diffraction in Crystals', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Calculate the maximum number of orders visible with a diffraction grating of 500 lines per millimeter using monochromatic light of wavelength 600 nm', '["2", "4", "6", "8"]'::jsonb, 2, 'The grating spacing is $d=\frac{1\text{mm}}{500}=2000\text{nm}$. The highest order satisfies $\sin\theta \le 1$, so $m_{max}=\frac{d}{\lambda}=\frac{2000}{600}=3.33$, meaning orders $m=1,2,3$ are visible on each side of the central maximum, giving 6 visible orders in total.', 'Diffraction Grating Maximum Order', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Which of the following cannot be explained by the wave theory of light?', '["wave front", "photoelectric effect", "Diffraction of light", "interference of light"]'::jsonb, 1, 'The photoelectric effect requires light to be treated as discrete photons whose energy $E=hf$ ejects electrons above a threshold frequency; this cannot be accounted for by the classical wave theory of light, unlike diffraction and interference.', 'Limits of Wave Theory of Light', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'To obtain a diffraction pattern with a monochromatic light, the size of the aperture must be', '["order of wavelength of light", "Order of wavelength of obstacle", "Order in ranges of micrometer", "Order in ranges of nanometer"]'::jsonb, 0, 'Noticeable diffraction occurs only when the aperture or obstacle size is comparable to (of the same order as) the wavelength of the light being used; much larger apertures produce negligible diffraction spreading.', 'Condition for Observable Diffraction', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A monochromatic light of wavelength 5800A° is incident normally on a sit of diameter 0.20 mm. A diffraction pattern is observed on a screen placed 2 m away from the slit. Find the distance of the first dark fringe on either side of the central bright fringe', '["2.2 mm", "5.8 mm", "8.6 mm", "7.2 mm"]'::jsonb, 1, 'For single-slit diffraction the first minimum satisfies $a\sin\theta=\lambda$, so $\sin\theta=\frac{580\times10^{-9}}{0.20\times10^{-3}}=2.9\times10^{-3}$. The fringe distance is $y=L\sin\theta=2\text{m}\times2.9\times10^{-3}=5.8\times10^{-3}\text{m}=5.8\text{ mm}$.', 'Single-Slit Diffraction Minima', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Wave theory of light is credited to', '["Newton", "Einstein", "Huygens", "Copernicus"]'::jsonb, 2, 'The wave theory of light, including the principle used to construct wavefronts and explain propagation, is credited to Christiaan Huygens, in contrast to Newton''s corpuscular theory of light.', 'History of Wave Theory of Light', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'A beam of unpolarized light is incident on a polaroid with its transmission axis rotated clockwise by 30°. The ratio of transmitted to incident intensity is', '["0.50", "0.87", "3.00", "2.00"]'::jsonb, 0, 'For unpolarized light passing through a single polarizer, exactly half of the intensity is transmitted regardless of the orientation of the transmission axis, since Malus''s law only governs a second polarizer acting on already-polarized light: $\frac{I}{I_0}=0.50$.', 'Polarization of Unpolarized Light', false, 'second', 3),
  ('phy-122-heat-waves-optics', 'PHY 104: Fundamentals of Physics II (Heat, Waves and Optics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'Reflected light from the surface of a still water body appears to be fully polarized when the angle of incidence is 53°. The refractive index of water therefore is', '["0.75", "1.52", "2.55", "1.33"]'::jsonb, 3, 'Full polarization of reflected light occurs at Brewster''s angle, where $n=\tan\theta_B=\tan(53°)\approx1.33$.', 'Brewster''s Angle and Polarization', false, 'second', 3);
