-- =============================================================================
-- University of Nigeria, Nsukka -- Faculty of Agriculture
-- Department of Crop Science -- five-year B.Agric degree programme
-- =============================================================================
-- SOURCE: the department's own official page,
--   https://cropscience.unn.edu.ng/course-modules/
-- This is real HTML text published by the department, not a photographed
-- handbook page, so the course codes, titles and units are read directly
-- rather than transcribed from an image.
--
-- VERIFICATION: the page prints a "Total" for each semester. Every one of the
-- 10 totals was recomputed from the individual unit values and matches:
-- 16, 15, 17, 23, 17, 20, 15, 16, 18, 18.
--
-- FIFTH YEAR: the programme splits into three options -- Crop Production, Crop
-- Protection and Horticulture. A student follows one of them. The rows below
-- are the UNION of the three option tables, de-duplicated by course code, with
-- every fifth-year row flagged is_elective = true and its description naming
-- which options list it. Inserting all three tables verbatim would have
-- produced the same course code three times over.
--
-- KNOWN ERRORS IN THE SOURCE PAGE (transcribed faithfully, never silently
-- "corrected", and each one called out in the affected row's description):
--   * the Horticulture table lists CSC 531 titled "Field Crops", duplicating
--     CSC 521, where the other two options title CSC 531 "Plant Protection";
--   * the Crop Protection table lists "ANS 541 Soil Physic" -- an Animal
--     Science code -- where the others list "SSC 541 Soil Physics";
--   * the Crop Protection table puts "Soil and Plant Analysis" under SSC 563,
--     which is Soil Fertility everywhere else on the same page;
--   * the final-year project appears as CSC 552, CSC 592 and CSC 572 in three
--     different places on the page;
--   * CSC 512 is 1 unit in every option table but 2 units in the description
--     section; the tables are used, since they are what the totals reconcile
--     against;
--   * first year first semester prints the code as "MTH III" rather than
--     "MTH 111".
-- The page also describes CSC 551 and CSC 561, which appear in no option
-- table; they are therefore not loaded as programme courses.
-- =============================================================================

delete from public.course_outlines
 where institution = 'University of Nigeria, Nsukka'
   and department = 'Crop Science';

insert into public.course_outlines
  (course_code, course_title, institution, faculty, department, level,
   semester, credit_units, description, topics, contributor_name, is_elective)
values
  ('AGR 101', 'Biomathematics', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '100 Level', 'first', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('CHM 101', 'Basic Principles of Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '100 Level', 'first', 2, 'Stoichiometry and Atomic Structure: Stoichiometry and mole concept. Introduction to atomic structure, development of electronic configuration of the elements, and valency theories. Periodic Table and Groups: The periodic classification of elements. Brief group study of representative elements, with emphasis on similarities and differences based on periodic position. Nuclear Chemistry: Radioactivity and its practical applications.', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('CHM 171', 'Basic Practical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '100 Level', 'first', 2, 'Laboratory operations: theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations.', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('BIO 151', 'General Biology I', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '100 Level', 'first', 3, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('MTH 111', 'General Mathematics', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '100 Level', 'first', 3, 'Elementary set theory, subsets, union, intersection, complements. Venn diagrams, real numbers, integers, rational and irrational numbers, mathematical induction, real sequences and series, theory of quadratic equations, binomial theorem. Circular measure, trigonometric functions of angles of any magnitude, addition and factor formulae. Complex numbers, algebra of complex numbers, the Argand diagram, De Moivre''s theorem, nth roots of unity. The source page prints this code as "MTH III" (three capital letter I characters); it is recorded here as MTH 111, the code that title corresponds to.', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('GSP 101', 'Communication in English I', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '100 Level', 'first', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('GSP 111', 'Use of Library and Study Skills', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '100 Level', 'first', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('AGR 102', 'Agric. Physics', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '100 Level', 'second', 4, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('CHM 112', 'Basic Principles of Chemistry II', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '100 Level', 'second', 2, 'Gas laws and kinetic theory: kinetic theory of gases, elementary derivation and deduction of gas laws, molecular speeds, deviations from ideal behaviour, van der Waals modification, and gas liquefaction. Phase equilibrium and solutions: phase transitions and phase equilibria in one-component systems; ideal solutions, Raoult''s law, Henry''s law, real solutions, and colligative properties. Thermodynamics and kinetics: aspects of the first law of thermodynamics, thermochemistry, entropy, free energy, and spontaneous changes; ionic equilibria, acids, bases, indicators, and buffers; elementary chemical kinetics.', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('CHM 122', 'Basic Principles of Organic Chemistry III', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '100 Level', 'second', 2, 'Structure and classification: historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, homologous series, elemental analysis, molecular formulas, and structural isomerism. Bonding and reactivity: isolation and purification methods, functional group concepts, resonance, and aromaticity. Functional groups: saturated and unsaturated hydrocarbons, cyclic hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, and aromatic compounds. Stereochemistry and lipids: introduction to oils, fats, and stereoisomerism.', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('BIO 152', 'General Biology II', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '100 Level', 'second', 3, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('BIO 153', 'General Biology (Practical)', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '100 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('GSP 102', 'Communication in English II', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '100 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('CSC 211', 'Principles of Forestry', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '200 Level', 'first', 2, 'Renewable natural resources - availability, distribution and potential. The important forest trees and wildlife (with emphasis on Nigerian species). Classification, morphology and distribution of important forestry trees. Forest and game reserves in Nigeria. Silviculture and afforestation characteristics of major timber and their uses. Felling and log transportation.', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('CSC 221', 'Crop Anatomy, Taxonomy and Physiology', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '200 Level', 'first', 2, 'Origin and introduction to the taxonomy of cultivated plants with particular reference to tropical crops. Cell biology. Pollination, seed dormancy and seed germination. Morphology and reproduction of important tropical crops. Quantitative aspects of plant crop growth. Nutritional and environmental influences on crop growth, development and yield. Regulation of growth and development, biosynthesis, storage and mobilization of harvestable reserves in crops.', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('AGR 201', 'General Agriculture', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '200 Level', 'first', 3, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('COS 101', 'Introduction to Computer Science', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '200 Level', 'first', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('SSC 211', 'Principles of Soil Science', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '200 Level', 'first', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('ANS 241', 'Nutrition, Anatomy and Physiology of Farm Animals', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '200 Level', 'first', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('GSP 201', 'Basic Concepts and Theory of Peace', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '200 Level', 'first', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('GSP 207', 'Humanities I', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '200 Level', 'first', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('CSC 222', 'Principles of Crop Production', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '200 Level', 'second', 2, 'Fundamental principles and problems of crop production. The importance of crop rotation, cultural practices, water and soil conservation, irrigation and drainage. Maintenance of soil fertility. Pests, diseases and weed control in crop production. Principles and methods of crop harvesting; crop processing and storage. Specific cultural requirements and practices in the production of field, forage and plantation crops.', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('FST 102', 'Introduction to Food Science and Technology', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '200 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('AEC 202', 'Principles of Agricultural Economics', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '200 Level', 'second', 4, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('ANS 222', 'Introduction to Agricultural Biochemistry', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '200 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('ANS 274', 'Principles of Animal Production', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '200 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('SSC 242', 'Climatology and Biogeography', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '200 Level', 'second', 3, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('ANS 272', 'Introduction to Fisheries and Wildlife Management', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '200 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('HND 102', 'Introduction to Home Science, Nutrition and Dietetics', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '200 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('GSP 202', 'Issues in Peace and Conflict Resolution Studies', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '200 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('GSP 208', 'Humanities II', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '200 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('CSC 321', 'Arable Crop Production', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '300 Level', 'first', 2, 'Origin, distribution, soil and climatic requirements of cereals, legumes, root crops, fibre crops, vegetables and other important annual crops in Nigeria. Improved varieties. Production practices, harvesting, utilization, processing, storage and economic aspects of some selected arable crops.', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('CSC 331', 'Principles of Crop Protection', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '300 Level', 'first', 2, 'Concept of disease in agriculture caused by micro-organisms such as fungi, bacteria and viruses. Economic importance of crop disease. Classification and identification of pathogenic fungi, bacteria and viruses. Symptoms and methods of disease control - chemical, cultural and biological. Definition of pest. Insect pests and nematodes. Introduction of arthropods in agriculture, their biology, classification and economic importance. Effects of weeds and the principles and methods of weed control. Introduction to parasitism and parasitic organisms in agriculture.', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('COS 201', 'Computer Programming I', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '300 Level', 'first', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('AEC 301', 'Basic Farm Management and Production Economics', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '300 Level', 'first', 3, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('AEX 311', 'Introduction to Agric. Extension and Rural Sociology', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '300 Level', 'first', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('ANS 371', 'Non-ruminant Animal Production', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '300 Level', 'first', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('CED 341', 'Introduction to Entrepreneurship I', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '300 Level', 'first', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('SSC 321', 'Paedology', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '300 Level', 'first', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('CSC 322', 'Crop Genetics and Breeding', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '300 Level', 'second', 2, 'Definition and historical development of the science of genetics; cell structure and components; chromosomes, structure, number and variations, linkage and crossing-over, mutation and genes in population. Multiple alleles, mitosis and meiosis. Principles of Mendelian genetics. Theory of evolution. Gene actions and interactions. Qualitative inheritance, linkage and cytoplasmic inheritance. Objectives and general principles of crop breeding. Breeding methods for crop improvement. Selection methods in in-breeders and out-breeders; compatibility, male sterility, heterosis. Polyploidy in crop breeding, development, multiplication and distribution of improved varieties.', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('CSC 342', 'Permanent Crop Production', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '300 Level', 'second', 2, 'Origin, distribution, soil and climatic requirements of some important permanent crops such as cocoa, oil palm, rubber, coffee, coconut, mango, sugar cane, banana, plantains, citrus, kola and cashew. Production practices, improvement, harvesting, utilization, processing, storage and economic aspects of some selected permanent and perennial crops.', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('AGR 302', 'Agricultural Statistics and Data Processing', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '300 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('AEX 312', 'Extension Teaching Methods', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '300 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('ANS 322', 'Agricultural Biochemistry and Methods', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '300 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('ANS 332', 'Animal Genetics and Breeding', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '300 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('SSC 362', 'Soil Chemistry and Microbiology', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '300 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('ANS 372', 'Ruminant Animal Production', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '300 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('CED 342', 'Introduction to Entrepreneurship II', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '300 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('ABE 306', 'Introduction to Farm Machinery', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '300 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('CSC 421', 'Crop Production Techniques', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '400 Level', 'first', 4, 'Crops covered are legumes, cereals, roots, tubers and horticultural crops. Layout of plots, nursery bed construction; ridge and mound construction with hoes. Direct planting, rice nursery management and transplanting. Manures, fertilization, weeding, use and care of spray equipment. Estimation of yield of grains and cereals, dry matter content, starch, protein and oil content. Field management of vegetable gardens, fruit trees and plantation crops. Harvesting and handling of produce.', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('CSC 431', 'Crop Protection and Pest Control', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '400 Level', 'first', 2, 'Field identification of crop diseases and pests. Collection and classification of crop pathogens and pests. Pest control techniques - chemical, cultural, biological and others.', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('AGR 401', 'Agricultural Products Storage', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '400 Level', 'first', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('SSC 431', 'Farm Design, Survey and Land Use Planning', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '400 Level', 'first', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('SSC 441', 'Agric. Meteorology, Irrigation and Drainage', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '400 Level', 'first', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('ANS 471', 'Animal Husbandry Techniques', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '400 Level', 'first', 3, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('AGR 402', 'Farm Work Project and Report Writing', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '400 Level', 'second', 6, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('AEX 412', 'Extension Practices', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '400 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('AEC 422', 'Farm Management and Accounting Practice', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '400 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('SSC 462', 'Soil Fertility, Soil and Water Management', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '400 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('ABE 412', 'Agricultural Engineering Practical', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '400 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('FVM 433', 'Animal Health and Management', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '400 Level', 'second', 2, '', '[]'::jsonb, 'UNN Department of Crop Science official website', false),
  ('CSC 511', 'Field Experimentation and Data Analysis', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '500 Level', 'first', 2, 'Design and management of experiments with crops. Randomized block, factorial and split plot designs; confounding; simple linear regressions. Data processing from commonly used designs and data interpretation. Fifth-year option course. Listed by all three options (Crop Production, Crop Protection, Horticulture).', '[]'::jsonb, 'UNN Department of Crop Science official website', true),
  ('CSC 521', 'Field Crops', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '500 Level', 'first', 2, 'Classification of cereals and legumes. Centre of origin, history and importance, climatic and soil requirements, rotation and cropping sequences. Cultural operations: planting, management, harvesting, handling and storage of major cereals and legumes including rice, maize, guinea corn, millet, cowpea and groundnuts. Classification of roots and tubers, and of oil, drug and fibre crops, with their cultural operations. Pests and diseases of these crops and their control. Fifth-year option course. Listed by all three options.', '[]'::jsonb, 'UNN Department of Crop Science official website', true),
  ('CSC 531', 'Plant Protection', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '500 Level', 'first', 2, 'The concept and importance of crop protection against diseases. General classification of disease causal organisms and types of plant diseases. Principles of disease control including eradication, protection, exclusion and immunization. Pests: general introduction to major plant pests including insects, nematodes, birds and rodents; pests of major importance in Nigerian agriculture; survey of pest control techniques. Weeds: economic importance of weeds in tropical crop production; weed biology; methods of weed control. Fifth-year option course. Listed by the Crop Production and Crop Protection options. The Horticulture option table also lists code CSC 531 but titles it "Field Crops", duplicating CSC 521 - an inconsistency in the source page.', '[]'::jsonb, 'UNN Department of Crop Science official website', true),
  ('CSC 541', 'Vegetable Crops', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '500 Level', 'first', 2, 'Origin and classification of vegetable crops. Vegetable seeds - structure and functions of parts; seed viability, vigour, dormancy and methods of breaking seed dormancy. Types of vegetable growing. Factors affecting vegetable growing and distribution. Land preparation, nursery practices, manures, fertilizers and pesticides used in vegetable production. Vegetable seed production. Harvesting, processing and storage of vegetable crops. Crop rotation in vegetable growing. Fifth-year option course. Listed by all three options (the Horticulture table shortens the title to "Vegetable").', '[]'::jsonb, 'UNN Department of Crop Science official website', true),
  ('CSC 533', 'Economic Entomology', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '500 Level', 'first', 2, 'General classification of insects of economic importance. Life cycle and food habits of insects as basis of control measures. Problems of insects on growing crops and in storage. Insects as vectors of certain viral, bacterial and fungal diseases. Methods of insect pest control. Use of insecticides, methods of application and handling, phytotoxicity and mammalian toxicity. Economic considerations. Fifth-year option course. Listed by the Crop Production and Crop Protection options.', '[]'::jsonb, 'UNN Department of Crop Science official website', true),
  ('CSC 543', 'Plant Propagation', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '500 Level', 'first', 2, 'Sexual propagation: media for seed propagation; seed germination requirements; seed storage and longevity; seed certification and quality control; quarantine regulations. Vegetative propagation: anatomical and physiological aspects of grafting and rooting; clones, sports and chimera; root-stock and scion interactions; role of the environment on vegetative propagation; growth regulators in plant propagation; budwood certification and maintenance of clonal gardens. Fifth-year option course. Listed by the Horticulture option only.', '[]'::jsonb, 'UNN Department of Crop Science official website', true),
  ('SSC 531', 'Soil Survey and Land Use Planning', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '500 Level', 'first', 2, 'Fifth-year option course. Listed by all three options.', '[]'::jsonb, 'UNN Department of Crop Science official website', true),
  ('SSC 541', 'Soil Physics', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '500 Level', 'first', 2, 'Fifth-year option course. Listed by the Crop Production and Horticulture options. The Crop Protection option lists the same slot as "ANS 541 Soil Physic", an Animal Science code - an inconsistency in the source page.', '[]'::jsonb, 'UNN Department of Crop Science official website', true),
  ('SSC 561', 'Soil Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '500 Level', 'first', 2, 'Fifth-year option course. Listed by all three options.', '[]'::jsonb, 'UNN Department of Crop Science official website', true),
  ('SSC 562', 'Soil and Plant Analysis', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '500 Level', 'first', 2, 'Fifth-year option course. Listed by the Crop Production and Horticulture options. The Crop Protection option gives this slot as SSC 563, which elsewhere is Soil Fertility - an inconsistency in the source page.', '[]'::jsonb, 'UNN Department of Crop Science official website', true),
  ('CSC 512', 'Plant Nutrition', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '500 Level', 'second', 1, 'The nutrient requirements of crops; influence of soil conditions and cation relationships on nutrient availability and uptake; movement and utilization of the major and micro-nutrients by crops; manures, fertilizers and limes; nutrient deficiency symptoms in crops and their remedies. Crop responses to nutrient application. The role of legumes. Plant sampling and sample preparation. Analysis of plant samples for major elements and the interpretation of data. Fifth-year option course. Listed by all three options. The course-description section gives this as 2 units while every option table gives 1 unit; the tables are used because they are what the printed 18-unit totals reconcile against.', '[]'::jsonb, 'UNN Department of Crop Science official website', true),
  ('CSC 522', 'Forage and Fodder Crops', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '500 Level', 'second', 2, 'Fifth-year option course. Listed by all three options.', '[]'::jsonb, 'UNN Department of Crop Science official website', true),
  ('CSC 524', 'Plant Breeding and Genetics', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '500 Level', 'second', 2, 'Genetic principles as basis of plant breeding. Survey of objectives, methods and techniques of plant breeding. Germplasm bank. Reproductive systems in plants and their role in plant breeding. Application of breeding methods to the improvement of self-pollinated, cross-pollinated and sexually reproduced crops. Development and maintenance of breeding stock, multiplication and distribution of improved crop varieties. Breeding for pest and disease control. Fifth-year option course. Listed by all three options.', '[]'::jsonb, 'UNN Department of Crop Science official website', true),
  ('CSC 534', 'Weed Science', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '500 Level', 'second', 2, 'Biology of weeds. Principles and methods of weed control. Classification, chemistry, selectivity, formulation, application and mode of action of herbicides. Herbicide-environment interaction. Safety factors in the use of herbicides. Fifth-year option course. Listed by all three options.', '[]'::jsonb, 'UNN Department of Crop Science official website', true),
  ('CSC 542', 'Plantation Crops', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '500 Level', 'second', 2, 'Origin, distribution and importance of tropical plantation crops. Climatic and soil requirements, cultural operations, methods of propagation, nursery practices, plantation management, harvesting, processing and storage of major plantation crops including oil palm, rubber, cocoa, coffee, kola, cashew, banana/plantain, sugar cane, tea and sisal hemp. Fifth-year option course. Listed by all three options.', '[]'::jsonb, 'UNN Department of Crop Science official website', true),
  ('CSC 544', 'Post Harvest Physiology and Product Storage', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '500 Level', 'second', 2, 'Storage life of harvested fruits, vegetables and flowers. Tropical environment in relation to maturity, ripeness and senescence including climacteric. Physical and chemical indices of quality in fruit and vegetable crops. Controlled environment for transit and long-term storage. Fifth-year option course. Listed by all three options.', '[]'::jsonb, 'UNN Department of Crop Science official website', true),
  ('CSC 552', 'Special Project', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '500 Level', 'second', 4, 'Fifth-year option course. The Crop Production option gives the project as CSC 552; the Crop Protection and Horticulture tables give CSC 592 and the course-description section gives CSC 572. All three refer to the same 4-unit final-year project - the source page is inconsistent about its code.', '[]'::jsonb, 'UNN Department of Crop Science official website', true),
  ('SSC 542', 'Principles of Irrigation and Drainage', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '500 Level', 'second', 2, 'Fifth-year option course. Listed by all three options.', '[]'::jsonb, 'UNN Department of Crop Science official website', true),
  ('SSC 563', 'Soil Fertility', 'University of Nigeria, Nsukka', 'Faculty of Agriculture', 'Crop Science', '500 Level', 'second', 1, 'Fifth-year option course. Listed by all three options.', '[]'::jsonb, 'UNN Department of Crop Science official website', true);
