-- =============================================================================
-- University of Nigeria, Nsukka — Faculty of Biological Sciences — Microbiology
-- Course outlines transcribed from the departmental course catalogue.
-- =============================================================================
-- Run in the Supabase SQL Editor. Safe to run more than once: existing rows
-- for these courses are removed first, so it updates rather than duplicates.
--
-- NOTE: the catalogue's own MCB 411 prerequisite text reads "MCB 321", a code
-- that does not otherwise appear anywhere in the document — quoted verbatim
-- rather than silently corrected.
--
-- This file also carries the required ancillary and general-studies courses
-- a Microbiology student actually sits each semester (BIO, CHM, MTH, PHY,
-- GSP, COS, STA, CED, BOT 242, plus BCH 201/202/351/353/381/301/354/471 and
-- ZEB 321), scoped to department = 'Microbiology' so they appear on a
-- Microbiology student's own timetable — independent rows from any
-- same-code row filed under its own home department. Descriptions are
-- reused, unedited, from this app's Biochemistry/Zoology/Mathematics/
-- Physics/Chemistry outlines where the code, level, semester and subject
-- genuinely match; the catalogue's own "PHY 195" is used elsewhere in the
-- Biological Sciences catalogue only as "PHY 191", so it is filed here as
-- PHY 191. Where no verified description exists anywhere (BIO, GSP, COS,
-- CED, STA, BOT 242, CHM 221/232), only code/title/units/level/semester are
-- given. Ancillary lists follow only the catalogue's own Standard Four-Year
-- Programme table, not its Three-Year direct-entry variant, for the same
-- reason combined-honours tracks were excluded from the major-course files.
-- =============================================================================

delete from public.course_outlines
 where institution = 'University of Nigeria, Nsukka'
   and department = 'Microbiology';

insert into public.course_outlines
  (course_code, course_title, institution, faculty, department, level,
   semester, credit_units, description, topics, contributor_name)
values
  ('MCB 102', 'Introductory Microbiology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '100 Level', 'second', 2, 'History of development of Microbiology. Scope of Microbiology. Growth and nutrition of microorganisms. Laboratory cultivation of microorganisms and measurement of growth. Microbial metabolism and biochemistry. Control of growth of microorganisms. General characteristics, classification and economic importance of bacteriophages, fungi, algae and protozoa. Role of microorganisms in medicine, agriculture and industry.', '["History of development and scope of Microbiology", "Growth and nutrition of microorganisms", "Laboratory cultivation of microorganisms and measurement of growth", "Microbial metabolism and biochemistry", "Control of growth of microorganisms", "General characteristics, classification and economic importance of bacteriophages, fungi, algae and protozoa", "Role of microorganisms in medicine, agriculture and industry"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 201', 'General Microbiology I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '200 Level', 'first', 3, 'General review of the nature and biology of protozoa, fungi, algae, bacteria, archaea and viruses. General characteristics, growth and reproduction of microorganisms. Microbiology methods and instrumentation. Sterilisation and disinfection. Microorganisms in various environments: soil, water, food, etc. Industrial use of microorganisms. Pathogenic role of microorganisms.

Pre-requisite: MCB 102', '["Nature and biology of protozoa, fungi, algae, bacteria, archaea and viruses", "General characteristics, growth and reproduction of microorganisms", "Microbiology methods and instrumentation", "Sterilisation and disinfection", "Microorganisms in various environments: soil, water, food", "Industrial use of microorganisms", "Pathogenic role of microorganisms"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 202', 'General Microbiology II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '200 Level', 'second', 3, 'Review of the structure and organisation of prokaryotic and eukaryotic cells. Principles and methodology of numerical taxonomy. Application of molecular biology in classification of microorganisms. Systematic classification of bacteria, fungi, protozoa and viruses. Physiology, ecology and laboratory identification of important species of microorganisms. Elemental cycles (carbon, nitrogen and phosphorus).

Pre-requisite: MCB 102', '["Structure and organisation of prokaryotic and eukaryotic cells", "Principles and methodology of numerical taxonomy", "Application of molecular biology in classification of microorganisms", "Systematic classification of bacteria, fungi, protozoa and viruses", "Physiology, ecology and laboratory identification of important species of microorganisms", "Elemental cycles: carbon, nitrogen and phosphorus"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 212', 'Environmental Microbiology I (Sewage, Water & Air Pollution)', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '200 Level', 'second', 2, 'Air microbiology: sources of air pollution; indices of air pollution; physical and microbiological properties of air in different environments. Microorganisms and other organisms important in aquatic systems: ecology of microorganisms in fresh water and marine ecosystems; self-purification, treatment and management of water; microbiological and chemical examination of water. Microbiology of sewage: methods of sewage treatment and disposal. Disease transmission by water and microbial risk assessment.', '["Air microbiology: sources and indices of air pollution", "Physical and microbiological properties of air in different environments", "Ecology of microorganisms in fresh water and marine ecosystems", "Self-purification, treatment and management of water", "Microbiological and chemical examination of water", "Microbiology of sewage: treatment and disposal methods", "Disease transmission by water and microbial risk assessment"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 301', 'Microbial Physiology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '300 Level', 'first', 2, 'Microbial cell: structure and functions. Microbial growth and nutrition. Microbial growth process: growth modes and factors affecting cell growth. Death of microorganisms. Microbial photosynthesis. Transport of molecules across the cell membrane, including facilitated diffusion, mechanosensitive channels, ATP-driven ion motive pumps, ATP-driven cassette transporter family, phosphotransferase system. Microbial stress responses including osmotic stress and osmotolerance, oxidative stress, pH stress and acid tolerance, thermal stress and heat shock response. Morphogenesis. Modification of enzyme activity. Mechanisms of regulation.

Pre-requisite: MCB 201 & 202', '["Microbial cell: structure and functions", "Microbial growth and nutrition; growth modes and factors affecting cell growth", "Death of microorganisms; microbial photosynthesis", "Transport of molecules across the cell membrane: facilitated diffusion, ion pumps, cassette transporters, phosphotransferase system", "Microbial stress responses: osmotic, oxidative, pH and thermal stress", "Morphogenesis; modification of enzyme activity; mechanisms of regulation"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 302', 'Microbial Metabolism', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '300 Level', 'second', 2, 'Catabolism: the Embden-Meyerhof-Parnas (EMP) pathway; the pentose pathway (PP); hexose monophosphate pathway; the Entner-Duodoroff (ED) pathway; the phosphoketolase (PK) pathway or Warburg-Dickens pathway; the tricarboxylic acid cycle. Energy production: substrate-level phosphorylation; oxidative phosphorylation. Respiration: aerobic; nitrate; sulfate and carbonate. Fermentation balances: alcohol, lactic, mixed acid, butanediol and butyric. Lipid metabolism. Anabolism: glyoxylate cycle and glucogenesis.

Pre-requisite: MCB 201 & BCH 202', '["Catabolism: EMP pathway, pentose pathway, ED pathway, phosphoketolase pathway, tricarboxylic acid cycle", "Energy production: substrate-level and oxidative phosphorylation", "Respiration: aerobic, nitrate, sulfate and carbonate", "Fermentation balances: alcohol, lactic, mixed acid, butanediol and butyric", "Lipid metabolism", "Anabolism: glyoxylate cycle and glucogenesis"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 304', 'Microbial Genetics', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '300 Level', 'second', 2, 'Concept and scope of microbial genetics. DNA as genetic material and molecular basis of inheritance. A review of the chemistry of DNA and RNA. Gene expression: transcription, translation and regulation (examples with the lac operon, trp operon, lambda lytic and lysogenic cycles). Mutation and mutagenesis. Types of mutants and their use in scientific studies. Genetic interaction amongst microorganisms: recombination; complementation; conjugation; transduction; transformation; insertion sequences.

Pre-requisite: MCB 201 & 202', '["Concept and scope of microbial genetics", "DNA as genetic material and molecular basis of inheritance", "Gene expression: transcription, translation and regulation (lac operon, trp operon, lambda cycles)", "Mutation and mutagenesis; types of mutants and their use in scientific studies", "Genetic interaction amongst microorganisms: recombination, complementation, conjugation, transduction, transformation, insertion sequences"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 313', 'Environmental Microbiology and Climate Change', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '300 Level', 'first', 2, 'Nature of the soil and distribution of soil microorganisms. Methods used in determining the types and numbers of microorganisms in the soil. Biodegradation of organic matters, starch, pectins, cellulose, etc. Microbial mineralisation/conversion of minerals (S, K, Fe, P, etc) and pesticides. Nitrogen fixation. Mycorrhizae and other plant-microorganism associations in the soil. Nature and forms of soil pollution. Microbiological control and management of soil pollution.

Pre-requisite: MCB 201 & 202', '["Nature of the soil and distribution of soil microorganisms", "Methods for determining types and numbers of microorganisms in the soil", "Biodegradation of organic matters, starch, pectins, cellulose", "Microbial mineralisation/conversion of minerals and pesticides", "Nitrogen fixation; mycorrhizae and other plant-microorganism associations in the soil", "Nature and forms of soil pollution and its microbiological control and management"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 315', 'Petroleum Microbiology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '300 Level', 'first', 2, 'Historical developments in petroleum microbiology. Genesis of fossil fuels with emphasis on microbiological influence. Microbial indicators in oil prospecting. Microbiology of oil drilling and corrosion of pipes and equipment. Acid mine drainage; effects of oil spills on microbial ecology of seas and soils. Biodegradation and bioremediation of petroleum products and environmental aspects of oil shale oxidation. Structures and recalcitrance of byproducts of the petroleum industry including plastics, waxes, sprays, paints and oils; microbial processes for recovering and upgrading petroleum.

Pre-requisite: MCB 201 & 202', '["Historical developments in petroleum microbiology; genesis of fossil fuels", "Microbial indicators in oil prospecting", "Microbiology of oil drilling and corrosion of pipes and equipment", "Acid mine drainage; effects of oil spills on microbial ecology of seas and soils", "Biodegradation and bioremediation of petroleum products; oil shale oxidation", "Recalcitrance of petroleum industry byproducts; microbial processes for recovering and upgrading petroleum"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 325', 'Food Microbiology I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '300 Level', 'first', 2, 'Microbial groups important in food and dairy products. Use of microorganisms in production/processing of foods such as garri, foo-foo, bread, cheese, single-cell protein, mushroom fungi, vitamins, beer, wine, palm wine, vinegar, burukutu, etc.

Pre-requisite: MCB 201 & 202', '["Microbial groups important in food and dairy products", "Use of microorganisms in production/processing of foods: garri, foo-foo, bread, cheese", "Single-cell protein and mushroom fungi", "Fermented products: beer, wine, palm wine, vinegar, burukutu"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 331', 'Pathogenic Bacteriology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '300 Level', 'first', 2, 'History of pathogenic bacteriology. Host-parasite relationships. Mechanisms of bacterial pathogenicity and virulence factors of pathogenic bacteria. Normal flora of human tissues and organ systems and their role in health and disease. Pathogenesis, epidemiology, treatment, prevention and control of diseases caused by various bacteria.

Pre-requisite: MCB 201 & 202', '["History of pathogenic bacteriology; host-parasite relationships", "Mechanisms of bacterial pathogenicity and virulence factors", "Normal flora of human tissues and organ systems and their role in health and disease", "Pathogenesis, epidemiology, treatment, prevention and control of bacterial diseases"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 333', 'Diagnostic Microbiology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '300 Level', 'first', 1, 'Laboratory techniques for the systematic isolation, characterisation and identification of aetiologic agents (bacteria, fungi and protozoan parasites) of disease from specimens commonly encountered in clinical microbiology labs (respiratory, genitourinary, faecal and blood).

Pre-requisite: MCB 201 & 202', '["Laboratory techniques for systematic isolation, characterisation and identification of disease-causing agents", "Bacteria, fungi and protozoan parasites as aetiologic agents", "Specimen types: respiratory, genitourinary, faecal and blood"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 335', 'Pathogenic Mycology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '300 Level', 'first', 2, 'General classification of fungi. Morphological and important physiological characteristics of dermatophytes and fungi causing subcutaneous and deep mycoses. Clinical features and epidemiology of mycotic infections. Pathogenic actinomycetes. Identification of common laboratory contaminants. Collection of clinical materials, isolation and identification of pathogenic fungi.

Pre-requisite: MCB 201 & 202', '["General classification of fungi", "Morphological and physiological characteristics of dermatophytes and fungi causing subcutaneous and deep mycoses", "Clinical features and epidemiology of mycotic infections", "Pathogenic actinomycetes; identification of common laboratory contaminants", "Collection of clinical materials; isolation and identification of pathogenic fungi"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 334', 'Immunology and Immunochemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '300 Level', 'second', 3, 'Basic concept of immunology. Innate and adaptive immunity. Ontogeny of cells of the immune system. Structure of antigens and antigenic determinants. Cellular response. Genetics of response to antigenic stimulation. Structure, genetics and classification of antibodies. Mechanism and theories of antibody formation. Antigen and antibody interactions. Role of lymphoid tissues and thymus in immune response. Hypersensitivity, immunopathology, autoimmunity, tumour and transplantation immunology.

Pre-requisite: MCB 201 & BCH 201', '["Basic concepts of immunology: innate and adaptive immunity", "Ontogeny of cells of the immune system", "Structure of antigens and antigenic determinants; cellular response", "Structure, genetics and classification of antibodies; theories of antibody formation", "Antigen-antibody interactions; role of lymphoid tissues and thymus", "Hypersensitivity, immunopathology, autoimmunity, tumour and transplantation immunology"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 352', 'Students'' Industrial Work Experience Scheme (Field Work)', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '300 Level', 'second', 6, 'Industrial attachment in Medical/Public Health/Industrial establishments. Students are visited periodically in their different places of work and their performance monitored through their supervisors.', '["Industrial attachment in Medical, Public Health and Industrial establishments", "Periodic visits and performance monitoring by supervisors"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 354', 'SIWES Report', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '300 Level', 'second', 3, 'Students keep records of their field work experiences in log books which are submitted on their return to the Department.', '["Students keep records of field work experiences in log books submitted to the Department"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 356', 'SIWES Seminar', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '300 Level', 'second', 6, 'Students are expected to give oral presentations of the projects conducted during their industrial work experience. These presentations are evaluated by a panel of internal examiners and grades awarded.', '["Oral presentations of projects conducted during industrial work experience", "Evaluation by a panel of internal examiners"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 401', 'Analytical Microbiology and Quality Control', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '400 Level', 'first', 3, 'Use of microorganisms in quantitative and qualitative analysis of industrial products; foods, antibiotics and other pharmaceuticals, etc. Selecting test organisms and determination of their assay-responses. Preparation of test samples, assay procedures and interpretation of results. Determination of microbiological quality of foods and beverages and other industrial products. Sanitation of industrial plants and equipment. Microbiological standards and specifications.

Pre-requisite: MCB 201 & BCH 201', '["Use of microorganisms in quantitative and qualitative analysis of industrial products", "Selecting test organisms and determining assay-responses", "Preparation of test samples, assay procedures and interpretation of results", "Determination of microbiological quality of foods, beverages and industrial products", "Sanitation of industrial plants and equipment", "Microbiological standards and specifications"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 403', 'Molecular Biology and Genetic Engineering', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '400 Level', 'first', 2, 'Overview of DNA replication. Review of gene expression (transcription, translation and regulation). Principles of recombinant DNA technology: restriction enzymes, vectors and creation of DNA libraries. Molecular techniques for studying gene expression: Southern, northern and western blotting. Microorganisms as tools: microbial enzymes, transformation, cloning and expression techniques. Human gene cloning, stem cell technologies and tissue engineering. DNA fingerprinting and forensic analysis. Genomics and bioinformatics. Ethical considerations in genetic engineering.

Pre-requisite: MCB 201 & BCH 201', '["Overview of DNA replication and review of gene expression", "Principles of recombinant DNA technology: restriction enzymes, vectors, DNA libraries", "Molecular techniques for studying gene expression: Southern, northern and western blotting", "Microorganisms as tools: microbial enzymes, transformation, cloning and expression techniques", "Human gene cloning, stem cell technologies and tissue engineering", "DNA fingerprinting and forensic analysis; genomics and bioinformatics", "Ethical considerations in genetic engineering"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 411', 'Microbial Ecology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '400 Level', 'first', 3, 'Microbes and ecological theory. Physiological, morphological and genetic adaptations of microorganisms to their environment and microbial interactions. Microorganisms in ecosystems. Microbial bioconversions. Impact of selected pollutants and xenobiotics in soil and water environments on microbial communities, systems and ecology. Microbial ecology in health and disease situations.

Pre-requisite: MCB 321 (as printed in the catalogue)', '["Microbes and ecological theory", "Physiological, morphological and genetic adaptations of microorganisms to their environment", "Microbial interactions and microorganisms in ecosystems", "Microbial bioconversions", "Impact of pollutants and xenobiotics on microbial communities, systems and ecology", "Microbial ecology in health and disease situations"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 423', 'Industrial Microbiology and Biotechnology I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '400 Level', 'first', 2, 'Microorganisms of industrial importance and their major characteristics. Sources, isolation and screening for industrial microorganisms. Strain development, culture collection and maintenance. Formulation and preparation of media for industrial cultivation of microorganisms. Design and operation. Sterilisation of bioreactors, media and gases. Cell cultivation: culture systems (batch, repeated batch, fed-batch and continuous cultivation of microorganisms). Kinetics of microbial growth, substrate utilisation, product formation in batch cultures. Bio-process monitoring and control. Bioreactors. Scale-up of fermentation processes.

Pre-requisite: MCB 201 & 302', '["Microorganisms of industrial importance and their major characteristics", "Sources, isolation and screening for industrial microorganisms", "Strain development, culture collection and maintenance", "Formulation and preparation of media for industrial cultivation", "Sterilisation of bioreactors, media and gases", "Culture systems: batch, repeated batch, fed-batch and continuous cultivation", "Kinetics of microbial growth, substrate utilisation and product formation", "Bio-process monitoring and control; bioreactors; scale-up of fermentation processes"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 425', 'Food Microbiology II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '400 Level', 'first', 2, 'Microbial contamination and spoilage of foods including carbohydrates and protein rich foods, fruits and vegetables. Microbial food borne infections and "food poisoning". Principles and methods used in food preservation. Microbiological food standards and quality control. Hazard analysis in the food industries. Rumen microbiology.

Pre-requisite: MCB 201 & 202', '["Microbial contamination and spoilage of foods: carbohydrate and protein rich foods, fruits and vegetables", "Microbial food borne infections and food poisoning", "Principles and methods used in food preservation", "Microbiological food standards and quality control", "Hazard analysis in the food industries", "Rumen microbiology"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 431', 'Virology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '400 Level', 'first', 3, 'Nature of viruses: chemical composition and structure of the virion. Characteristics and classification of viruses. Replication, cultivation, assay and analysis of viruses using cell culture, embryonated eggs and laboratory animals. Assay of infectivity using plaque assay. Purification and separation of virions. Interactions among viruses: recombination, reassortment, complementation, genetic reactivation, genomic masking and phenotypic mixing. Interference and interaction. Interactions between viruses and hosts: persistent infections, viral cytopathic effects (CPE), cell transformation and oncogenesis. Pathogenesis and pathology of virus infections: infections of the skin, respiratory tract, alimentary canal, nervous system, liver, systemic infections, and generalised infections with rashes. Immunity and immunopathology of viral infections.

Pre-requisite: MCB 201 & BCH 201', '["Nature of viruses: chemical composition and structure of the virion", "Characteristics and classification of viruses", "Replication, cultivation, assay and analysis of viruses", "Assay of infectivity using plaque assay; purification and separation of virions", "Interactions among viruses: recombination, reassortment, complementation, genetic reactivation", "Interactions between viruses and hosts: persistent infections, CPE, cell transformation and oncogenesis", "Pathogenesis and pathology of virus infections in various organ systems", "Immunity and immunopathology of viral infections"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 481', 'Seminar in Microbiology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '400 Level', 'first', 3, 'Under the supervision of a staff member, the student is expected to select a seminar topic for study, using library methods. The emphasis will be on recent advances in the chosen field. The course is expected to give the student the opportunity for independent thought and expression. The work is finally presented to staff and students and also written up.', '["Selection of a seminar topic under staff supervision, using library methods", "Emphasis on recent advances in the chosen field", "Opportunity for independent thought and expression", "Final presentation to staff and students and written write-up"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 412', 'Environmental Impact Assessment', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '400 Level', 'second', 2, 'Historical background of environmental impact assessment (EIA). Overview of the different stages of the actual EIA process. Factors involved in evaluating the effects of a proposed action upon various aspects of the environment. Sources and examination of data for environmental evaluation of government or private action. Physical and chemical factors that control impacts on biological or cultural resources. Impact evaluation procedures for complying with environmental protection agencies'' acts and guidelines. Risk assessment.

Pre-requisite: MCB 201', '["Historical background of environmental impact assessment (EIA)", "Stages of the EIA process", "Factors involved in evaluating the effects of a proposed action on the environment", "Sources and examination of data for environmental evaluation", "Physical and chemical factors controlling impacts on biological or cultural resources", "Impact evaluation procedures and compliance with environmental protection guidelines; risk assessment"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 424', 'Industrial Microbiology and Biotechnology II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '400 Level', 'second', 2, 'Overproduction of metabolites by microorganisms. Industrial production of specific fermentation products (bio-ethanol, organic acids, antibiotics, vaccines, steroids, amino acids, vitamins, microbial enzymes including enzyme purification, immobilisation and applications), microbial insecticides, and bio-fertilisers. Microbial transformation. Down-stream processes. Unit operations in recovery and purification of microbial products. Introduction to fermentation economics.

Pre-requisite: MCB 201 & 302', '["Overproduction of metabolites by microorganisms", "Industrial production of fermentation products: bio-ethanol, organic acids, antibiotics, vaccines, steroids, amino acids, vitamins", "Microbial enzymes: purification, immobilisation and applications", "Microbial insecticides and bio-fertilisers", "Microbial transformation and down-stream processes", "Unit operations in recovery and purification of microbial products", "Introduction to fermentation economics"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 432', 'Principles of Epidemiology and Public Health', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '400 Level', 'second', 3, 'Infection and disease: signs, symptoms and syndromes. Methods of epidemiology: descriptive, analytical, statistical applications and experimental methods. Morbidity and mortality rates. Epidemiological reporting. Sources and reservoirs of infection. Zoonoses. Principal modes of transfer of infectious diseases. The importance and practices of immunisation. Public services: role of government, voluntary and international agencies.

Pre-requisite: MCB 201, 202 & 331', '["Infection and disease: signs, symptoms and syndromes", "Methods of epidemiology: descriptive, analytical, statistical and experimental methods", "Morbidity and mortality rates; epidemiological reporting", "Sources and reservoirs of infection; zoonoses", "Principal modes of transfer of infectious diseases", "Importance and practices of immunisation", "Public services: role of government, voluntary and international agencies"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 434', 'Pharmaceutical Microbiology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '400 Level', 'second', 3, 'The chemistry of synthetic chemotherapeutic agents and antibiotics. The mechanism, action and assay of antimicrobial agents. Concepts of antibiotic sensitivity and resistance related particularly to microbial physiology. Sterilisation in hospitals, industry, etc. Medical and non-medical uses of antibiotics.

Pre-requisite: MCB 201, 202 & BCH 201', '["Chemistry of synthetic chemotherapeutic agents and antibiotics", "Mechanism, action and assay of antimicrobial agents", "Concepts of antibiotic sensitivity and resistance", "Sterilisation in hospitals and industry", "Medical and non-medical uses of antibiotics"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 492', 'Project', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '400 Level', 'second', 6, 'Each student is expected to carry out a fairly detailed research investigation under the supervision of a staff member in any special area in Microbiology, write it up as a project report and be examined for his/her knowledge of the work before a panel of external and internal examiners in an oral examination.

Pre-requisite: MCB 331', '["Detailed research investigation under staff supervision in a special area of Microbiology", "Write-up as a project report", "Oral examination before a panel of external and internal examiners"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BIO 151', 'General Biology I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '100 Level', 'first', 3, 'Elective.', '[]'::jsonb, 'Department of Computer Science course outline'),
  ('MTH 111', 'Elementary Mathematics I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '100 Level', 'first', 3, 'Elementary set theory, subsets, union, intersection, complements. Venn diagrams, real numbers, integers, rational and irrational numbers, mathematical induction, real sequences and series, theory of quadratic equations, binomial theorem. Circular measure, trigonometric functions of angles of any magnitude, addition and factor formulae. Complex numbers, algebra of complex numbers, the Argand diagram, De Moivre''s theorem, nth roots of unity.', '["Elementary set theory, subsets, union, intersection, complements", "Venn diagrams, real numbers, integers, rational and irrational numbers, mathematical induction, real sequences and series, theory of quadratic equations, binomial theorem", "Circular measure, trigonometric functions of angles of any magnitude, addition and factor formulae", "Complex numbers, algebra of complex numbers, the Argand diagram, De Moivre''s theorem, nth roots of unity"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MTH 121', 'Elementary Mathematics II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '100 Level', 'first', 3, 'Functions of a real variable, graphs, limits and continuity. The derivative as limit of rate of change. Techniques of differentiation. Curve sketching, integration as an inverse of differentiation. Methods of integration, definite integrals. Application of integration to areas and volumes.', '["Functions of a real variable, graphs, limits and continuity", "The derivative as limit of rate of change", "Techniques of differentiation", "Curve sketching, integration as an inverse of differentiation", "Methods of integration, definite integrals", "Application of integration to areas and volumes"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 101', 'Basic Principles of Inorganic Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '100 Level', 'first', 2, 'Stoichiometry and atomic structure: stoichiometry and mole concept. Introduction to atomic structure, development of electronic configuration of the elements, and valency theories. Periodic table and groups: the periodic classification of elements. Brief group study of representative elements, with emphasis on similarities and differences based on periodic position. Nuclear chemistry: radioactivity and its practical applications.', '["Stoichiometry and mole concept; introduction to atomic structure and valency theories", "Periodic classification of elements; brief group study of representative elements", "Nuclear chemistry: radioactivity and its practical applications"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 171', 'Basic Practical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '100 Level', 'first', 2, 'Laboratory operations: theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations.', '["Laboratory operations: theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('PHY 111', 'General Physics for Life Sciences I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '100 Level', 'first', 2, 'Units and dimension. Scalars and vectors. Linear and circular motion, velocity, acceleration. Laws of mechanics and gravitation; simple applications. Conservation of energy, momentum. Work and power. Simple harmonic motion, simple pendulum. Moment of inertia, angular momentum; centrifugal and centripetal forces; centrifuges. Elasticity, Hooke''s Law, Young''s modulus. Fluids, pressure, surface tension, velocity, osmosis; blood pressure and its measurement.', '["Units and dimension; scalars and vectors", "Linear and circular motion, velocity, acceleration", "Laws of mechanics and gravitation; conservation of energy and momentum", "Work and power; simple harmonic motion, simple pendulum", "Moment of inertia, angular momentum; centrifugal and centripetal forces; centrifuges", "Elasticity, Hooke''s Law, Young''s modulus", "Fluids: pressure, surface tension, velocity, osmosis; blood pressure and its measurement"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('PHY 191', 'Practical Physics I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '100 Level', 'first', 2, 'Selected experiments from the 100-Level courses in Physics for service courses.', '["Selected experiments from the 100-Level courses in Physics for service courses"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('GSP 101', 'The Use of English I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '100 Level', 'first', 2, 'Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, The English Language and the Nigerian society, World English, Levels and Varieties of English — formal, informal, standard, etc., English in Literature and the Media.

Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes, English Language Register, diatypes and dialects.

Listening skill - The listening skill discussed as a receptive and reciprocal activity, Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening.

Reading Skill - The concept of reading as a linguistic organization and a vehicle of communication. Reading Problems, Levels of Reading, Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies (Scanning, Skimming, Phrase reading, Intensive & Extensive reading, Exploiting the topic sentence for main ideas), Reading for details, Reading for evaluation and inference, Reading with questions - SQ3R, PR3, Methods for understanding difficult words in a reading text, Literature reading for study, analysis and comment.

Speaking & Communication Skills - Nature, Process & Development, Principles of Public Speech Making and Social Interaction, The Speech Sounds of English and their Articulation, Phonetic Transcription and Practical Speech Work.

Study Techniques - Choosing study centers and discussion groups, Note-taking during lectures, and from audio-visual equipment, Note-making techniques during private reading and literature search, Summary & Transcoding Techniques, Retrieving information from notes, The dictionary as a study guide.

Basic Research Methods & Term Paper Writing - Research – meaning & nature, Types & Methodology; Data in the Research Process, The Research Report, Process and Techniques, Documentation in Research Reports: Process, Types and Methods, Abbreviations in Research Reports, The term paper as a miniature research report, Practical term paper writing.

Course Evaluation & Grading - Students must attend at least 75% of the lectures to qualify for examination in the course.', '["Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, World English, Levels and Varieties of English", "Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes", "Listening skill - Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening", "Reading Skill - Reading Problems, Levels and Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies, Reading for evaluation and inference", "Speaking & Communication Skills - Principles of Public Speech Making and Social Interaction, Phonetic Transcription and Practical Speech Work", "Study Techniques - Note-taking, Note-making, Summary & Transcoding Techniques", "Basic Research Methods & Term Paper Writing - The Research Report, Documentation, Abbreviations, practical term paper writing"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('GSP 201', 'Concepts and Theories of Peace and Conflict Resolution', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '100 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BIO 152', 'General Biology II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '100 Level', 'second', 3, 'Elective.', '[]'::jsonb, 'Department of Statistics undergraduate course module'),
  ('BIO 154', 'General Biology Practical', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '100 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 112', 'Basic Principles of Physical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '100 Level', 'second', 2, 'Gas laws and kinetic theory: kinetic theory of gases, elementary derivation and deduction of gas laws, molecular speeds, deviations from ideal behaviour, van der Waals modification, and gas liquefaction. Phase equilibrium and solutions: phase transitions and phase equilibria in one-component systems; ideal solutions, Raoult''s law, Henry''s law, real solutions, and colligative properties. Thermodynamics and kinetics: aspects of the first law of thermodynamics, thermochemistry, entropy, free energy, and spontaneous changes; ionic equilibria, acids, bases, indicators, and buffers; elementary chemical kinetics.', '["Gas laws and kinetic theory of gases; molecular speeds; deviations from ideal behaviour; gas liquefaction", "Phase transitions and phase equilibria; ideal and real solutions; colligative properties", "First law of thermodynamics, thermochemistry, entropy, free energy, spontaneous changes", "Ionic equilibria, acids, bases, indicators and buffers", "Elementary chemical kinetics: rate laws, order and molecularity, Arrhenius equation"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 122', 'Basic Principles of Organic Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '100 Level', 'second', 2, 'Structure and classification: historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, homologous series, elemental analysis, molecular formulas, and structural isomerism. Bonding and reactivity: isolation and purification methods, functional group concepts, resonance, and aromaticity. Functional groups: saturated and unsaturated hydrocarbons, cyclic hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, and aromatic compounds. Stereochemistry and lipids: introduction to oils, fats, and stereoisomerism.', '["Historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, structural isomerism", "Isolation and purification methods; functional group concepts; resonance and aromaticity", "Saturated and unsaturated hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, aromatic compounds", "Introduction to oils, fats, and stereoisomerism"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('PHY 112', 'General Physics for Life Sciences II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '100 Level', 'second', 2, 'Concepts of heat, temperature: measurement of temperature, clinical thermometer. Heat capacity, specific heat, latent heat, calorimetry. Gas laws; kinetic theory of gases. Thermal energy, isothermal and adiabatic changes. Conduction, convection; radiation. Sound waves; intensity, pitch and quality of sound. Propagation of sound in solids, liquids and gases. Doppler effect. The ear. Reflection and refraction of light; plane and spherical mirrors, thin lenses; optical instruments. The eye, defects of vision and their corrections. Wave nature of light, interference, diffraction: velocity of light.', '["Concepts of heat and temperature: measurement, clinical thermometer, heat capacity, calorimetry", "Gas laws; kinetic theory of gases; thermal energy, isothermal and adiabatic changes", "Conduction, convection and radiation", "Sound waves: intensity, pitch, quality; propagation in solids, liquids and gases; Doppler effect; the ear", "Reflection and refraction of light: mirrors, thin lenses, optical instruments", "The eye, defects of vision and their corrections", "Wave nature of light: interference, diffraction, velocity of light"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('PHY 114', 'General Physics for Life Sciences III', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '100 Level', 'second', 2, 'Electric charge, Coulomb''s Law, electric field, electrostatic potential. Energy in electric field, capacitors. Dielectrics. Electric current, potential difference and electromotive force. Ohm''s Law: potentiometer, metre bridge, Wheatstone bridge. Magnetic effects of currents; permanent magnetism, earth''s magnetic field. Faraday''s Law of induction, generators and electric motor. Alternating currents; Maxwell''s equations. Structure of the atom. Radioactivity, X-rays, applications in life sciences. Nuclear energy.', '["Electric charge, Coulomb''s Law, electric field, electrostatic potential", "Energy in electric field, capacitors; dielectrics", "Electric current, potential difference and electromotive force; Ohm''s Law", "Magnetic effects of currents; permanent magnetism, earth''s magnetic field", "Faraday''s Law of induction, generators and electric motor; alternating currents; Maxwell''s equations", "Structure of the atom; radioactivity, X-rays, applications in life sciences; nuclear energy"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('GSP 102', 'The Use of English II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '100 Level', 'second', 2, 'Part A: Basic Grammar: Introduction. The concept of grammar and its place in language teaching and learning. Parts of speech and their functions (treated in detail). Closed and open class items in parts of speech, Nominalization, Grammatical Structures: the phrase, the clause and the sentence. Elementary Clause Analysis, Sentence Types, Elements and Patterns. Agreement (Grammatical agreement, Notional agreement, Proximity agreement) Agreement with the correlatives. Direct and Reported Speech, Error typology identification and correction.

Part B: Varieties of writing. Introduction (The Meaning, Nature and Purpose of Writing, Writing Types or Genres and their Characteristics). The paragraph as the basic unit of an essay (Types, Development of the Paragraph, Methods of Paragraph Development, The thesis statement). Point of view and style in writing. Qualities of a good piece of writing: Form, Diction and Content in writing. The Mechanics of Writing: punctuation, spelling and capitalization.

Part C: Writing Genres - Planning and choosing your theme. Deciding your genre. Choosing and developing your plot. Point of view, setting and characterization. Using the language that works. Essay Writing — Narration, Description, Exposition and Argumentation. Technical Writing: Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes, own story for practice, Computer-linked writing, types, style, language, and process.', '["Part A: Basic Grammar - The concept of grammar, Parts of speech, Grammatical Structures, Sentence Types, Agreement, Direct and Reported Speech, Error typology", "Part B: Varieties of writing - Meaning, Nature and Purpose of Writing, the paragraph as the basic unit of an essay, the thesis statement, Qualities of a good piece of writing, Mechanics of Writing", "Part C: Writing Genres - Planning and choosing your theme, plot, point of view, setting and characterization", "Essay Writing - Narration, Description, Exposition and Argumentation", "Technical Writing - Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('GSP 202', 'Issues in Peace and Conflict Resolution', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '100 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 201', 'General Biochemistry I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '200 Level', 'first', 3, 'The cell environment: water and solutes — the unique properties of water, H-bonds, electrostatic interactions, Van der Waals attraction; alkalinity and acidity, pH and pK and their influence on cellular activities; physiological buffers. Cell macromolecules: structure, properties and functions of carbohydrates, lipids, proteins and nucleic acids. Cell structure and function: structure and function of major cell organelles; differences between prokaryotic and eukaryotic cells; biological membranes — organisation, architecture, properties and functions; the cytoplasm — mitochondria, peroxisomes, endoplasmic reticulum, Golgi complex, ribosomes, lysosomes, endosome; the nucleus — the nuclear envelope, chromatin, chromosomes, nucleolus, etc.', '["The cell environment: water and solutes, H-bonds, electrostatic interactions, Van der Waals attraction", "Alkalinity and acidity, pH and pK and their influence on cellular activities", "Physiological buffers", "Structure, properties and functions of carbohydrates, lipids, proteins and nucleic acids", "Structure and function of major cell organelles; differences between prokaryotic and eukaryotic cells", "Biological membranes: organisation, architecture, properties and functions", "The cytoplasm: mitochondria, peroxisomes, endoplasmic reticulum, Golgi complex, ribosomes, lysosomes, endosome", "The nucleus: nuclear envelope, chromatin, chromosomes, nucleolus"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BIO 351', 'General Genetics', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CED 341', 'Introduction to Entrepreneurship', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 201', 'General Inorganic Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '200 Level', 'first', 2, 'Periodic trends: ionization potential, electron affinity, and electronegativity. Chemical bonding: electrostatic and non-electrostatic valence forces, non-valence cohesive forces. Coordination compounds: introduction to complexes, focusing on colour, magnetic properties, and practical applications.

Prerequisite: CHM 101, or a pass in Chemistry at H.S.C./G.C.E. A-Level', '["Periodic trends: ionization potential, electron affinity, and electronegativity", "Chemical bonding: electrostatic and non-electrostatic valence forces, non-valence cohesive forces", "Coordination compounds: complexes, colour, magnetic properties and practical applications"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 211', 'General Physical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '200 Level', 'first', 2, 'Gases and thermodynamics: molecular collisions in gases, virial equation, critical phenomena, and reduced properties; chemical thermodynamics, detailed treatment of the first law of thermodynamics, and the Carnot cycle. Chemical kinetics: integrated rate equations for second and third order reactions, reaction mechanisms, rate laws, and the effect of temperature on reaction rates.

Prerequisite: CHM 112', '["Molecular collisions in gases, virial equation, critical phenomena, reduced properties", "Chemical thermodynamics: first law of thermodynamics; the Carnot cycle", "Integrated rate equations for second and third order reactions; reaction mechanisms and rate laws", "Effect of temperature on reaction rates"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 221', 'General Organic Chemistry I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('COS 101', 'Introduction to Computer Science', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '200 Level', 'first', 2, 'Concepts of hardware and software; basic subsystems of a digital computer; characteristics of a digital computer; devices/media; types/classes of computer emphasising the PC; history of computers and their generations. Problem-solving: algorithm, flowchart, pseudocode, program/data, running a program. Programming: introduction to Java/BASIC programming language syntax and programming. Booting and shutdown; types of operating system; user interface; managing information, computer malware (virus, etc); computer network; internet and web usage, e-mail, instant messaging, etc. Office applications; use of a statistical package and a database management system.', '["Concepts of hardware and software","basic subsystems of a digital computer","characteristics of a digital computer","devices/media","types/classes of computer emphasising the PC","history of computers and their generations","Problem-solving: algorithm, flowchart, pseudocode, program/data, running a program","Programming: introduction to Java/BASIC programming language syntax and programming","Booting and shutdown","types of operating system","user interface","managing information, computer malware (virus, etc)","computer network","internet and web usage, e-mail, instant messaging, etc","Office applications","use of a statistical package and a database management system"]'::jsonb, 'Department of Computer Science course outline'),
  ('STA 203', 'Statistics for Agriculture and Biological Sciences I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '200 Level', 'first', 2, 'Initial steps in planning of biological experiments. Methods of data collection, presentation and analysis. Measures of central tendency and dispersion. Frequency distributions. Elementary probability. Discrete and continuous distributions: Binomial, Poisson, Normal and exponential distributions. Interval estimation.', '["Initial steps in planning of biological experiments", "Methods of data collection, presentation and analysis", "Measures of central tendency and dispersion", "Frequency distributions", "Elementary probability", "Discrete and continuous distributions: Binomial, Poisson, Normal and exponential distributions", "Interval estimation"]'::jsonb, 'Department of Statistics handbook'),
  ('GSP 207', 'Humanities I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 202', 'General Biochemistry II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '200 Level', 'second', 3, 'Enzymes: introduction to biological catalysts, nature, functions and classification of enzymes, factors affecting enzyme action. Energy metabolism: introductory bioenergetics/energy-rich compounds, carbohydrate metabolism — glycolysis and pentose phosphate pathway, the Krebs cycle and the glyoxylate cycle, electron transport and oxidative phosphorylation. Separation of macromolecules: chromatographic methods — thin layer chromatography, gel filtration, ion exchange chromatography, affinity chromatography; electrophoretic methods — nucleic acid gel electrophoresis, electrophoretic sizing of protein, isoelectric focusing.', '["Introduction to biological catalysts: nature, functions and classification of enzymes; factors affecting enzyme action", "Introductory bioenergetics/energy-rich compounds", "Carbohydrate metabolism: glycolysis and pentose phosphate pathway", "The Krebs cycle and the glyoxylate cycle", "Electron transport and oxidative phosphorylation", "Chromatographic methods: thin layer, gel filtration, ion exchange, affinity chromatography", "Electrophoretic methods: nucleic acid gel electrophoresis, protein sizing, isoelectric focusing"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CED 342', 'Business Development and Management', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 232', 'Analytical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('COS 304', 'Computer Applications', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('STA 204', 'Statistics for Agriculture and Biological Sciences II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '200 Level', 'second', 2, 'Tests of significance. Student $t$ test and $\chi^2$ test. Two sample test and paired comparison. Regression and correlation. Analysis of variance: one way, two way with no interaction. Latin square analysis. Multiple range tests. Analysis of covariance. Simple analysis of direct assays.', '["Tests of significance", "Student $t$ test and $\\chi^2$ test", "Two sample test and paired comparison", "Regression and correlation", "Analysis of variance: one way, two way with no interaction", "Latin square analysis", "Multiple range tests", "Analysis of covariance", "Simple analysis of direct assays"]'::jsonb, 'Department of Statistics handbook'),
  ('BOT 242', 'Mycology I (Introductory Mycology)', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('GSP 208', 'Humanities II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 351', 'Primary Metabolic Pathways I – Metabolism of Carbohydrates', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '300 Level', 'first', 1, 'Degradation and digestion of carbohydrates — sugars, storage polysaccharides and cell walls; reactions of sugars; glycogenolysis; glycolysis; tricarboxylic acid cycle; the glyoxylate pathway; the pentose phosphate pathway; Cori cycle and Calvin pathway; gluconeogenesis and glycogenesis; disorders of carbohydrate metabolism.', '["Degradation and digestion of carbohydrates: sugars, storage polysaccharides and cell walls", "Reactions of sugars", "Glycogenolysis and glycolysis", "Tricarboxylic acid cycle and the glyoxylate pathway", "The pentose phosphate pathway", "Cori cycle and Calvin pathway", "Gluconeogenesis and glycogenesis", "Disorders of carbohydrate metabolism"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 353', 'Primary Metabolic Pathways III – Metabolism of Amino Acids and Proteins', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '300 Level', 'first', 2, 'Amino acids as building blocks of proteins: covalent backbone of proteins, amino acid composition; protein isolation — fractionation, purification and characterisation; biological functions of proteins; oxidative degradation of amino acids and metabolism of the carbon units; biosynthesis of amino acids and some derivatives; the urea cycle; metabolism of inorganic nitrogen; disorders of amino acid metabolism.', '["Amino acids as building blocks of proteins: covalent backbone, amino acid composition", "Protein isolation: fractionation, purification and characterisation", "Biological functions of proteins", "Oxidative degradation of amino acids and metabolism of the carbon units", "Biosynthesis of amino acids and some derivatives", "The urea cycle and metabolism of inorganic nitrogen", "Disorders of amino acid metabolism"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 381', 'Techniques in Biochemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '300 Level', 'first', 2, 'Principles of instrumentation: centrifugation, cell fractionation technique and instrumentation, application of centrifugation. Chromatography: planar chromatography (paper and thin-layer), column chromatography, ion-exchange and gel exclusion chromatography, gas chromatography and high performance liquid chromatography, affinity chromatography and immunoadsorption. Electrophoresis: theory of electrophoresis, methods of electrophoresis — polyacrylamide gel electrophoresis (PAGE), nucleic acid sequencing gels, agarose gel electrophoresis, pulsed field electrophoresis, isoelectric focusing, 2-dimensional electrophoresis of protein, capillary electrophoresis, immunoelectrophoresis, instrumentation and analysis of electrophoresis results. Spectroscopy: UV-visible absorption spectrophotometry, fluorescence spectrophotometry, nuclear magnetic resonance spectrophotometry and mass spectrometry. Radioisotope techniques: overview of radioactivity, detection and measurement of radioactivity, application of radioactivity and safety issues. Molecular technique: hybridisation techniques, polymerase chain reaction. Immunochemical techniques: immunochemical and immunoblotting. Use of computers in research: bioinformatics.', '["Principles of instrumentation: centrifugation, cell fractionation technique and instrumentation", "Chromatography: planar, column, ion-exchange, gel exclusion, gas, HPLC, affinity and immunoadsorption", "Electrophoresis: theory and methods — PAGE, agarose gel, pulsed field, isoelectric focusing, capillary electrophoresis", "Spectroscopy: UV-visible, fluorescence, NMR and mass spectrometry", "Radioisotope techniques: detection, measurement, application and safety of radioactivity", "Molecular technique: hybridisation techniques, polymerase chain reaction", "Immunochemical techniques: immunochemical and immunoblotting", "Use of computers in research: bioinformatics"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 471', 'Industrial Biochemistry and Biotechnology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '300 Level', 'first', 3, 'Elective. Overview and definition of biotechnology; biotechnology and the developing world; overview of microbial physiology and genetics. Substrates for biotechnology, biological fuel generation, genetics and biotechnology, bioprocess/fermentation biotechnology, enzyme technology, biotechnology and medicine, environmental biotechnology, food and beverage biotechnology, biotechnology in agriculture and forestry, protection of biotechnological inventions, safety issues and biotechnology and society. See the Biochemistry outline for the full description.', '["See BCH 471 in the Biochemistry course outline for the full syllabus"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 301', 'Enzymology and Protein Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '300 Level', 'first', 3, 'Elective. Protein structure and function, functional classification of proteins, catalytic properties of enzymes and the Michaelis-Menten equation. See the Biochemistry outline for the full description.', '["See BCH 301 in the Biochemistry course outline for the full syllabus"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 354', 'Primary Metabolic Pathways IV – Metabolism of Nucleic Acid', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '300 Level', 'first', 2, 'Elective. Genome organisation; biosynthesis of proteins; metabolism, structure, properties and functions of nucleosides and nucleotides; metabolism of purine and pyrimidine; abnormalities in nucleic acid metabolism, xeroderma pigmentosum and skin cancer.', '["Genome organisation", "Biosynthesis of proteins", "Metabolism, structure, properties and functions of nucleosides and nucleotides", "Metabolism of purine and pyrimidine", "Abnormalities in nucleic acid metabolism: xeroderma pigmentosum and skin cancer"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('ZEB 321', 'Basic Parasitology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Microbiology', '300 Level', 'first', 2, 'Elective. Types of parasites; the ecology of animal parasites; life histories, modes of transmission and epidemiology. See the Zoology and Environmental Biology outline for the full description.', '["See ZEB 321 in the Zoology and Environmental Biology course outline for the full syllabus"]'::jsonb, 'Faculty of Biological Sciences course catalogue');
