-- =============================================================================
-- University of Nigeria, Nsukka — Faculty of Engineering — Mechanical Engineering
-- Course outlines transcribed from the department's own course handbook
-- (scanned copy), covering the Five-Year Undergraduate Programme: all five
-- years, both semesters, including required ancillary and general-studies
-- courses. The handbook also prints a parallel "Four-Year Undergraduate
-- Programme" (for direct-entry students); it is not transcribed separately
-- since every course in it duplicates a course already captured in the
-- five-year table below — direct-entry students simply start at Year 2.
-- =============================================================================
-- Run in the Supabase SQL Editor. Safe to run more than once: existing rows
-- for this department are removed first, so it updates rather than duplicates.
--
-- SEMESTERS: the handbook explicitly labels every course "First Semester" or
-- "Second Semester" in its programme-structure tables, so those stated values
-- are used directly — no guessing was needed here.
--
-- Unlike the Social Sciences handbook transcribed earlier for this app, this
-- document prints full real descriptions for its required-ancillary 1XX
-- courses too (EGR 101/102, MTH 111/121/122, CHM 101/112/122/171, PHY
-- 116/121/124/195, GSP 101/102/111) since Mechanical Engineering's own
-- handbook includes the shared first-year engineering syllabus in full — so
-- those are transcribed with real content here rather than left blank.
--
-- GAPS: one photographed page (covering the tail of MEE 581 and the start of
-- MEE 582) came out with heavy motion blur and could not be transcribed;
-- MEE 582's description here starts mid-sentence as a result, and MEE 569
-- (Direct Energy Conversion Principles), MEE 572 (Thermal Engineering and
-- Advanced Heat Transfer), MEE 581 (Quality Assurance and Reliability) and
-- MEE 532 (Theory of Elasticity) carry real code/title/units from the
-- programme-structure table but no description, since their description text
-- was not found on any legible page. MEE 402 (Written Technical
-- Communication)'s description was cut off mid-sentence by a page break and
-- is transcribed only up to that point.
--
-- ANCILLARY COURSES FROM OTHER ENGINEERING DEPARTMENTS: CVE 211/213/222/224
-- (Civil Engineering), EEE 211/252/312 (Electrical Engineering), and
-- EGR 201/203/302/401/402 and STA 205, CED 341/342 (general engineering /
-- statistics / entrepreneurship service courses) appear in the timetable but
-- their own descriptions are not printed in this Mechanical Engineering
-- document, so they carry real code/title/units only, description left blank
-- pending a verified source elsewhere in this app (e.g. once Civil or
-- Electrical Engineering's own outlines are added).
-- =============================================================================

delete from public.course_outlines
 where institution = 'University of Nigeria, Nsukka'
   and department = 'Mechanical Engineering';

insert into public.course_outlines
  (course_code, course_title, institution, faculty, department, level,
   semester, credit_units, description, topics, contributor_name)
values
  ('EGR 101', 'Introduction to Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '100 Level', 'first', 2, 'An overview of engineering as a profession. Historical perspective, Discipline, Rationalization, professional affiliations, professional journey, successful studentship, creativity, roles of science and Technology; Engineering and Society: The role of engineers in nation building, professional impacts of Engineering practice and mitigation measures, professional challenges in Nigeria, historical and professional roles; Basic information on Agricultural and Bioresources Engineering, Professional practice, Sustainable Agricultural production in Nigeria; Introduction to Biomedical Engineering, Scope of biomedical engineering practice: A science perspective of Civil Engineering, corporate personality of Civil Engineering; Civil Engineering professional practice; Basic information on Electrical Engineering, Scope of Electrical Engineering professional practice; Electric power generation in Nigeria; Evolution to Electronic Engineering, Scope of Electronic Engineering Professional practice, practice of Electronic Engineering in Nigeria; Basic information on Mechanical Engineering, Scope of Mechanical Engineering professional practice, practice of Mechanical Engineering in Nigeria; Introduction to Mechatronics Engineering, Scope of Mechatronics engineering practice; Basic information on Metallurgical and Materials Engineering, Scope of Metallurgical and Materials Engineering professional practice, practice of Metallurgical and Materials Engineering.', '["An overview of engineering as a profession. Historical perspective, Discipline, Rationalization, professional affiliations, professional journey, successful studentship, creativity, roles of science and Technology", "Engineering and Society: The role of engineers in nation building, professional impacts of Engineering practice and mitigation measures, professional challenges in Nigeria", "Basic information on Agricultural and Bioresources Engineering; Introduction to Biomedical Engineering", "A science perspective of Civil Engineering, corporate personality and professional practice of Civil Engineering", "Basic information on Electrical Engineering; Electric power generation in Nigeria; Evolution to Electronic Engineering", "Basic information on Mechanical Engineering, Scope and practice of Mechanical Engineering in Nigeria", "Introduction to Mechatronics Engineering; Basic information on Metallurgical and Materials Engineering"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MTH 111', 'General Mathematics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '100 Level', 'first', 3, 'Elementary sets Theory; Subsets, Union, Intersection, Complements. Venn diagrams. Real Numbers, Integers, Rational and Irrational numbers. Mathematical inductions, Real sequences and Series. Theory of quadratic equation, Binomial Theorem. Complex numbers, Algebra of complex numbers. The Argand diagram, De Moivre''s Theorem, nth roots of Unity. Circular measure, Trigonometric functions of angles of any magnitude, addition and factor formulae.', '["Elementary sets Theory; Subsets, Union, Intersection, Complements. Venn diagrams", "Real Numbers, Integers, Rational and Irrational numbers", "Mathematical inductions, Real sequences and Series", "Theory of quadratic equation, Binomial Theorem", "Complex numbers, Algebra of complex numbers. The Argand diagram, De Moivre''s Theorem, nth roots of Unity", "Circular measure, Trigonometric functions of angles of any magnitude, addition and factor formulae"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('CHM 101', 'Basic Principles of Chemistry I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '100 Level', 'first', 2, 'An introduction to atomic structure. Development of configuration of the elements. Stoichiometry and mole concept. Electronic Theory of Valency. Chemical bonding. The periodic classification of the elements. General trend in the periodic Table, with emphasis on similarities and differences, based on the position of the element in the periodic Table. Radioactivity and its applications. Structure of Solids.', '["An introduction to atomic structure. Development of configuration of the elements", "Stoichiometry and mole concept. Electronic Theory of Valency. Chemical bonding", "The periodic classification of the elements. General trend in the periodic Table, with emphasis on similarities and differences, based on the position of the element in the periodic Table", "Radioactivity and its applications. Structure of Solids"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('CHM 171', 'Basic Practical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '100 Level', 'first', 2, 'The Theory and practice of simple volumetric and qualitative analysis. Simple organic preparations. Reactions of functional groups and physical determinations.', '["The Theory and practice of simple volumetric and qualitative analysis", "Simple organic preparations", "Reactions of functional groups and physical determinations"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('PHY 121', 'Fundamentals of Physics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '100 Level', 'first', 3, 'Units and dimensions. Vector algebra. Kinematics of a particle''s mass point; laws of mechanics and gravitation. Kepler''s Laws. Motion of rigid bodies, moment of inertia, angular momentum, vertical motion of a particle, elastic string, motion of a simple pendulum. Impulse and change of Momentum. Impact of two smooth elastic spheres. Direct and Oblique impacts.', '["Units and dimensions. Vector algebra", "Kinematics of a particle''s mass point; laws of mechanics and gravitation. Kepler''s Laws", "Motion of rigid bodies, moment of inertia, angular momentum", "Vertical motion of a particle, elastic string, motion of a simple pendulum", "Impulse and change of Momentum. Impact of two smooth elastic spheres. Direct and Oblique impacts"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('PHY 195', 'Practical Physics II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '100 Level', 'first', 2, 'Selected Experiments from the 100-Level courses in Physics for Physics majors and Engineering students.', '["Selected Experiments from the 100-Level courses in Physics for Physics majors and Engineering students"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('GSP 101', 'Use of English I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '100 Level', 'first', 2, 'Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, The English Language and the Nigerian society, World English, Levels and Varieties of English — formal, informal, standard, etc., English in Literature and the Media.

Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes, English Language Register, diatypes and dialects.

Listening skill - The listening skill discussed as a receptive and reciprocal activity, Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening.

Reading Skill - The concept of reading as a linguistic organization and a vehicle of communication. Reading Problems, Levels of Reading, Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies (Scanning, Skimming, Phrase reading, Intensive & Extensive reading, Exploiting the topic sentence for main ideas), Reading for details, Reading for evaluation and inference, Reading with questions - SQ3R, PR3, Methods for understanding difficult words in a reading text, Literature reading for study, analysis and comment.

Speaking & Communication Skills - Nature, Process & Development, Principles of Public Speech Making and Social Interaction, The Speech Sounds of English and their Articulation, Phonetic Transcription and Practical Speech Work.

Study Techniques - Choosing study centers and discussion groups, Note-taking during lectures, and from audio-visual equipment, Note-making techniques during private reading and literature search, Summary & Transcoding Techniques, Retrieving information from notes, The dictionary as a study guide.

Basic Research Methods & Term Paper Writing - Research – meaning & nature, Types & Methodology; Data in the Research Process, The Research Report, Process and Techniques, Documentation in Research Reports: Process, Types and Methods, Abbreviations in Research Reports, The term paper as a miniature research report, Practical term paper writing.

Course Evaluation & Grading - Students must attend at least 75% of the lectures to qualify for examination in the course.', '["Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, World English, Levels and Varieties of English", "Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes", "Listening skill - Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening", "Reading Skill - Reading Problems, Levels and Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies, Reading for evaluation and inference", "Speaking & Communication Skills - Principles of Public Speech Making and Social Interaction, Phonetic Transcription and Practical Speech Work", "Study Techniques - Note-taking, Note-making, Summary & Transcoding Techniques", "Basic Research Methods & Term Paper Writing - The Research Report, Documentation, Abbreviations, practical term paper writing"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('GSP 111', 'The Use of Library and Study Skills', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '100 Level', 'first', 2, 'Overview of Library: concepts, history, types and functions. Uses in academic libraries; organization of university library and library users. Library processes and procedures. Acquisition process, Cataloging and classification, LC Scheme, in-House Scheme, DDC. Serials process and circulation processes. Access tools in Library resources: Library catalogues, Indexes, Abstracts, Current contents information in the library. Reference sources: types of reference sources and services. Web resources and online resources. Overview of Databases, Online search strategies for information retrieval. Referencing and citation styles for information reporting. Concept of plagiarism. Learning skills and research skills, ICT skillsets: types of learning and information policies.', '["Overview of Library: concepts, history, types and functions. Uses in academic libraries; organization of university library and library users", "Library processes and procedures. Acquisition process, Cataloging and classification, LC Scheme, in-House Scheme, DDC. Serials process and circulation processes", "Access tools in Library resources: Library catalogues, Indexes, Abstracts, Current contents information", "Reference sources: types of reference sources and services. Web resources and online resources", "Overview of Databases, Online search strategies for information retrieval. Referencing and citation styles for information reporting. Concept of plagiarism", "Learning skills and research skills, ICT skillsets: types of learning and information policies"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('CHM 112', 'Basic Principles of Chemistry II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '100 Level', 'second', 2, 'Fundamental Chemical Principles. The gas laws, Kinetic theory of gases. Colligative properties of dilute solutions. Raoult''s law, Henry''s law and Molar weight determination. Thermochemistry, Chemical equilibrium, law of Mass action. Reaction rate and Chemical energetics. Electrochemistry, Ionic equilibrium. Theory of acids, Bases and Indicators. Phase equilibrium study of one and Two component Systems.', '["Fundamental Chemical Principles. The gas laws, Kinetic theory of gases", "Colligative properties of dilute solutions. Raoult''s law, Henry''s law and Molar weight determination", "Thermochemistry, Chemical equilibrium, law of Mass action. Reaction rate and Chemical energetics", "Electrochemistry, Ionic equilibrium. Theory of acids, Bases and Indicators", "Phase equilibrium study of one and Two component Systems"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('CHM 122', 'Basic Principles of Organic Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '100 Level', 'second', 2, '', '[]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('EGR 102', 'Applied Mechanics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '100 Level', 'second', 3, 'Introduction - Force Systems, resultants, Moments, Couples. Equilibrium, free-body diagram, 2-dimensional force systems, equations for equilibrium of forces in space, internal forces, examples of simple machines, friction, pulleys, wires and cables, static and dynamic Friction. Centroid, graphical determination, Theorems of Pappus of centers of gravity and areas. Moments of Inertia of plane areas, built up sections etc. Kinematics of particles and rigid bodies. Newton''s laws of motion applied to a system of particles. Rectilinear and curvilinear motion, tangent, normal, polar, work, energy, power. Concepts of momentum and Newton''s laws of motion under gravity. Projectile motion.', '["Introduction - Force Systems, resultants, Moments, Couples. Equilibrium, free-body diagram, 2-dimensional force systems", "Equations for equilibrium of forces in space, internal forces, examples of simple machines, friction, pulleys, wires and cables, static and dynamic Friction", "Centroid, graphical determination, Theorems of Pappus of centers of gravity and areas. Moments of Inertia of plane areas, built up sections etc", "Kinematics of particles and rigid bodies. Newton''s laws of motion applied to a system of particles", "Rectilinear and curvilinear motion, tangent, normal, polar, work, energy, power", "Concepts of momentum and Newton''s laws of motion under gravity. Projectile motion"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MTH 122', 'Elementary Mathematics III', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '100 Level', 'second', 3, 'Function of a real variable, graphs, limits and continuity. The derivative as limits of rate of change. Differentiation, Techniques of Differentiation. Curve sketching, Integration. Definite integrals. Application of Integration to areas and volumes.', '["Function of a real variable, graphs, limits and continuity", "The derivative as limits of rate of change", "Differentiation, Techniques of Differentiation. Curve sketching", "Integration. Definite integrals. Application of Integration to areas and volumes"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('PHY 116', 'General Physics for Physical Science II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '100 Level', 'second', 2, 'Heat and temperature. Calorimetry. Laws of thermodynamics. Change of state-Critical point. Heat transfer: conduction, convection and radiation. Blackbody radiation. Wave motions, longitudinal and transverse waves. Superposition of waves, interference and diffraction. Propagation of waves in material media, vibrations in solids, sound wave. Wave theory of light, polarization of light and lenses, propagation of light, reflection, refraction, mirrors and lenses, thin lens combination, optical instruments. Doppler Effect.', '["Heat and temperature. Calorimetry. Laws of thermodynamics. Change of state-Critical point", "Heat transfer: conduction, convection and radiation. Blackbody radiation", "Wave motions, longitudinal and transverse waves. Superposition of waves, interference and diffraction", "Propagation of waves in material media, vibrations in solids, sound wave", "Wave theory of light, polarization of light and lenses, reflection, refraction, mirrors and lenses, thin lens combination, optical instruments. Doppler Effect"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('PHY 124', 'Fundamentals of Physics III', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '100 Level', 'second', 3, 'Electrostatics, Coulomb''s Law, Gauss''s Law, simple applications. Electric field, electrostatic potential. Energy in electric field, capacitance, dielectrics. Electric current, Ohm''s law, circuit analysis, Thermoelectricity. Magnetic effects of currents, Ampere''s Law, Applications. Electromagnetism, Faraday''s law of induction, Maxwell''s equations. Alternating currents, A.C. circuits. Measuring devices. Motion of a charged particle in electric and magnetic fields, Hall Effect. Atomic and Nuclear structure. Nuclear fission and fusion. Nuclear reactors.', '["Electrostatics, Coulomb''s Law, Gauss''s Law, simple applications", "Electric field, electrostatic potential. Energy in electric field, capacitance, dielectrics", "Electric current, Ohm''s law, circuit analysis, Thermoelectricity", "Magnetic effects of currents, Ampere''s Law, Applications. Electromagnetism, Faraday''s law of induction, Maxwell''s equations", "Alternating currents, A.C. circuits. Measuring devices", "Motion of a charged particle in electric and magnetic fields, Hall Effect", "Atomic and Nuclear structure. Nuclear fission and fusion. Nuclear reactors"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('GSP 102', 'Communication in English II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '100 Level', 'second', 3, 'Part A: Basic Grammar: Introduction. The concept of grammar and its place in language teaching and learning. Parts of speech and their functions (treated in detail). Closed and open class items in parts of speech, Nominalization, Grammatical Structures: the phrase, the clause and the sentence. Elementary Clause Analysis, Sentence Types, Elements and Patterns. Agreement (Grammatical agreement, Notional agreement, Proximity agreement) Agreement with the correlatives. Direct and Reported Speech, Error typology identification and correction.

Part B: Varieties of writing. Introduction (The Meaning, Nature and Purpose of Writing, Writing Types or Genres and their Characteristics). The paragraph as the basic unit of an essay (Types, Development of the Paragraph, Methods of Paragraph Development, The thesis statement). Point of view and style in writing. Qualities of a good piece of writing: Form, Diction and Content in writing. The Mechanics of Writing: punctuation, spelling and capitalization.

Part C: Writing Genres - Planning and choosing your theme. Deciding your genre. Choosing and developing your plot. Point of view, setting and characterization. Using the language that works. Essay Writing — Narration, Description, Exposition and Argumentation. Technical Writing: Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes, own story for practice, Computer-linked writing, types, style, language, and process.', '["Part A: Basic Grammar - The concept of grammar, Parts of speech, Grammatical Structures, Sentence Types, Agreement, Direct and Reported Speech, Error typology", "Part B: Varieties of writing - Meaning, Nature and Purpose of Writing, the paragraph as the basic unit of an essay, the thesis statement, Qualities of a good piece of writing, Mechanics of Writing", "Part C: Writing Genres - Planning and choosing your theme, plot, point of view, setting and characterization", "Essay Writing - Narration, Description, Exposition and Argumentation", "Technical Writing - Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 211', 'Engineering Drawing I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '200 Level', 'first', 2, 'Constructions. Lettering and dimensioning. First and third angle orthogonal projections. Isometric projection, sections, plans and elevations. Machine drawing: Line work shaping, milling, grinding, turning, metal spinning, Hand tools, gas and arc welding, casting, forming and soldering. Foundry practice.', '["Constructions. Lettering and dimensioning. First and third angle orthogonal projections", "Isometric projection, sections, plans and elevations", "Machine drawing: Line work shaping, milling, grinding, turning, metal spinning", "Hand tools, gas and arc welding, casting, forming and soldering. Foundry practice"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 261', 'Engineering Thermodynamics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '200 Level', 'first', 2, 'Basic concepts, definitions and laws. Properties of pure substances: the P-v-T diagram, various charts and diagrams. The ideal gas, specific heat, thermal properties, processes. The first law of thermodynamics - heat and work relations, applications to open and closed systems. The steady flow energy equation (Bernoulli''s equation) and applications. Second law of thermodynamics, cycle analysis and efficiencies.', '["Basic concepts, definitions and laws. Properties of pure substances: the P-v-T diagram, various charts and diagrams", "The ideal gas, specific heat, thermal properties, processes", "The first law of thermodynamics - heat and work relations, applications to open and closed systems", "The steady flow energy equation (Bernoulli''s equation) and applications", "Second law of thermodynamics, cycle analysis and efficiencies"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MTH 207', 'Advanced Mathematics VII', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '200 Level', 'first', 2, 'Elements of linear algebra. Calculus: Elementary differentiation and relevant theorems. Differential equations: Exact equations, methods of solution of second-order ordinary differential equations, partial differential equations, with applications.', '["Elements of linear algebra", "Calculus: Elementary differentiation and relevant theorems", "Differential equations: Exact equations, methods of solution of second-order ordinary differential equations, partial differential equations, with applications"]'::jsonb, 'Department of Mathematics handbook'),
  ('GSP 201', 'The Social Sciences', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering course handbook'),
  ('GSP 207', 'Logic, Philosophy and Human Existence', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering course handbook'),
  ('MEE 202', 'Computing and Programming for Mechanical Engineers', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '200 Level', 'second', 3, 'Binary, octal, hexadecimal number systems. Basic logic components, AND, OR, NOT, NOR, NAND gates. Operations on binary numbers and logic gates. Methods of running programs on computers: interactive programming, batch processing, time-sharing. Introduction of computer languages – C++, Java, Python, etc. Data types: integers, reals, strings, etc. Basic program structure, loops, branching, subroutines. Data input/output structures in various languages. Basic program design: flow charts. Introduction to matrix-based engineering computation software tools (Scilab, Matlab, GNU Octave, python, etc.). Basic language elements: variables types and naming conventions, constants and continuation lines, elementary mathematical functions, pre-defined variables, dynamic type of variables. Working with matrices; creating matrices, special matrices, accessing matrix elements, elementary matrix operations, higher-level linear algebra operations. Implementing conditional statements. Functions: defining functions, debugging functions. Graphics: creating 2D plots, contour plots, 3D surface plots, modifying plot titles, axes and legends, exporting plots in vector and bitmap formats.', '["Binary, octal, hexadecimal number systems. Basic logic components and gates. Operations on binary numbers and logic gates", "Methods of running programs on computers: interactive programming, batch processing, time-sharing", "Introduction of computer languages – C++, Java, Python, etc. Data types, basic program structure, loops, branching, subroutines", "Introduction to matrix-based engineering computation software tools (Scilab, Matlab, GNU Octave, python, etc.)", "Basic language elements: variables, constants, elementary mathematical functions, dynamic type of variables", "Working with matrices; matrix operations, higher-level linear algebra operations. Implementing conditional statements. Functions", "Graphics: creating 2D plots, contour plots, 3D surface plots, exporting plots in vector and bitmap formats"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 204', 'Computing and Programming Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '200 Level', 'second', 1, 'Programming exercises in Python and Scilab: Matrix operations, looping and branching operations. Functions exercises in Python and Scilab. Graphics exercises in Python and Scilab: 2D plots, contour plots, 3D surface plots, plot export. Capstone project.', '["Programming exercises in Python and Scilab: Matrix operations, looping and branching operations", "Functions exercises in Python and Scilab", "Graphics exercises in Python and Scilab: 2D plots, contour plots, 3D surface plots, plot export", "Capstone project"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 212', 'Workshop Technology', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '200 Level', 'second', 2, 'Part A (Practical): Use of measuring instruments: Calipers, micrometers, gauges, etc. Test practice with wood planers, saws, sanders, and pattern making. Machine shop: Lathe work shaping, milling, grinding, turning, metal spinning, Hand tools, gas and arc welding, casting, forming and soldering. Foundry practice.

Part B (Theoretical): Industrial safety and accident prevention, ergonomics, inventory. Casting processes: Metal forming processes: hot-working and cold-working processes (forging, press and rod, spinning etc.). Metal joining processes: welding, brazing and soldering. Sheet metal work. Material removal processes, machine tools, classification, design theory of metal cutting. Tool wear and cutting forces. Introduction to CNC machines.', '["Part A (Practical): Use of measuring instruments; test practice with wood planers, saws, sanders, and pattern making", "Machine shop: Lathe work shaping, milling, grinding, turning, metal spinning, hand tools, gas and arc welding, casting, forming and soldering. Foundry practice", "Part B (Theoretical): Industrial safety and accident prevention, ergonomics, inventory", "Casting processes: Metal forming processes: hot-working and cold-working processes", "Metal joining processes: welding, brazing and soldering. Sheet metal work", "Material removal processes, machine tools, classification, design theory of metal cutting. Tool wear and cutting forces. Introduction to CNC machines"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('CVE 222', 'Fluid Mechanics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering course handbook'),
  ('CVE 224', 'Fluid Mechanics Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '200 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering course handbook'),
  ('EEE 252', 'Basic Electrical Engineering Lab/Practice', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '200 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering course handbook'),
  ('MTH 206', 'Advanced Mathematics VI', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '200 Level', 'second', 2, 'Complex analysis - Elements of the algebra of complex variables, trigonometric, exponential and logarithmic functions. The number system, sequences and series. Vector differentiation and integration.', '["Complex analysis - Elements of the algebra of complex variables, trigonometric, exponential and logarithmic functions", "The number system, sequences and series", "Vector differentiation and integration"]'::jsonb, 'Department of Mathematics handbook'),
  ('MTH 208', 'Advanced Mathematics VIII', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '200 Level', 'second', 2, 'Numerical analysis: Linear equations, non-linear equations; finite difference operators. Introduction to linear programming.', '["Numerical analysis: Linear equations, non-linear equations", "Finite difference operators", "Introduction to linear programming"]'::jsonb, 'Department of Mathematics handbook'),
  ('GSP 202', 'Issues in Peace and Conflict Resolution Studies', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering course handbook'),
  ('GSP 208', 'Nigerian Peoples and Culture', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering course handbook'),
  ('MEE 311', 'Manufacturing Processes', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '300 Level', 'first', 2, 'History of machining and machine tools: Lathes, drill press, cutters and grinders. Tool geometry/signature and chip formation. Fixturing and operations, gear manufacturing; thread manufacturing. Kinematic geometry of cutting processes. Machining Productivity; Machining time and Material removal rate; Machine tools drives, Turning and boring operations, drilling, milling, planing, shaping and grinding processes; Abrasive machining: Grinding, Slotting and broaching, honing and lapping, and super-finishing. Non-traditional Processes. Machine tool installation, testing and maintenance.', '["History of machining and machine tools: Lathes, drill press, cutters and grinders", "Tool geometry/signature and chip formation. Fixturing and operations, gear manufacturing, thread manufacturing", "Kinematic geometry of cutting processes. Machining Productivity; Machining time and Material removal rate", "Machine tools drives, Turning and boring operations, drilling, milling, planing, shaping and grinding processes", "Abrasive machining: Grinding, Slotting and broaching, honing and lapping, and super-finishing. Non-traditional Processes", "Machine tool installation, testing and maintenance"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 313', 'Mechanical Engineering Design I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '300 Level', 'first', 3, 'Principles of Design. Selection of Materials. Design and composition of cast, forged and welding bearings and structures; design of plastic parts. Precautions for manufacture. Simple stress analysis. Use of threaded and non-threaded fasteners. Elastic deformation of machine parts. Design of screws. Strength under combined load. Failure theories; Repeated loading. Shaft design. Flexible mechanical elements: Couplings, clutches and brakes. Mechanical springs. Anti-friction rolling contact bearings.

Prerequisite: CVE 211', '["Principles of Design. Selection of Materials", "Design and composition of cast, forged and welding bearings and structures; design of plastic parts. Precautions for manufacture", "Simple stress analysis. Use of threaded and non-threaded fasteners. Elastic deformation of machine parts. Design of screws", "Strength under combined load. Failure theories; Repeated loading. Shaft design", "Flexible mechanical elements: Couplings, clutches and brakes. Mechanical springs. Anti-friction rolling contact bearings"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 315', 'Workshop Practice', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '300 Level', 'first', 1, 'Machine operation practice: Turning operation, gear cutting, boring (using lathe machines), drilling, shaping and slotting using the shaper. Vertical and horizontal milling with the miller. Grinding of tooled and flat surfaces.

Prerequisite: MEE 212', '["Machine operation practice: Turning operation, gear cutting, boring (using lathe machines)", "Drilling, shaping and slotting using the shaper", "Vertical and horizontal milling with the miller", "Grinding of tooled and flat surfaces"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 321', 'Thermo-Fluids Laboratory I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '300 Level', 'first', 1, 'Basic measurements: Viscosity, velocity and transport measurements, pressure gauge calibration. Hydrostatic force on a submerged surface (centre of pressure). Laminar-turbulent transition in a pipe flow. Bernoulli''s equation. Flow meters. Software demonstrations of hydraulics and pipe flow. CFD demonstrations.

Prerequisite: CVE 224', '["Basic measurements: Viscosity, velocity and transport measurements, pressure gauge calibration", "Hydrostatic force on a submerged surface (centre of pressure)", "Laminar-turbulent transition in a pipe flow. Bernoulli''s equation. Flow meters", "Software demonstrations of hydraulics and pipe flow. CFD demonstrations"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 323', 'Mechanics of Machines Laboratory I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '300 Level', 'first', 1, 'Analysis, instant centres, images. Kinematics of mechanisms: Graphical and analytical methods for position, velocity and acceleration analysis. Gears, tooth geometry, involutometry, gear types, gear trains. Cams: displacement diagram, layout, operative mechanisms.

Prerequisite: EGR 102', '["Analysis, instant centres, images. Kinematics of mechanisms: Graphical and analytical methods for position, velocity and acceleration analysis", "Gears, tooth geometry, involutometry, gear types, gear trains", "Cams: displacement diagram, layout, operative mechanisms"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 341', 'Mechanics of Machines I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '300 Level', 'first', 2, 'Simple Mechanisms; Kinematics of mechanisms; Loci, graphical...

Prerequisite: EGR 102', '["Simple Mechanisms; Kinematics of mechanisms; Loci, graphical analysis"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 343', 'Measurement and Instrumentation', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '300 Level', 'first', 2, 'Measurement principles and basic definitions: Standards Accuracy and error analysis, measurement statistics. Instrument systems: sensing devices, transmitting devices, transducing devices. Typical systems and devices for measuring quantities such as temperature, pressure, flow, force, displacement, velocity, acceleration, strain, torque, work, energy. Analog methods of measurement. Digital measurement systems. Introduction to Arduino and Digital applications. Dynamics of measurement. Data presentation and interpretation of a curve fitting. Term projects on design and implementation of a measurement and control device.', '["Measurement principles and basic definitions: Standards Accuracy and error analysis, measurement statistics", "Instrument systems: sensing devices, transmitting devices, transducing devices", "Typical systems and devices for measuring quantities such as temperature, pressure, flow, force, displacement, velocity, acceleration, strain, torque, work, energy", "Analog methods of measurement. Digital measurement systems. Introduction to Arduino and Digital applications", "Dynamics of measurement. Data presentation and interpretation of a curve fitting", "Term projects on design and implementation of a measurement and control device"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 351', 'Mechanics of Fluids', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '300 Level', 'first', 2, 'Kinematics of fluid motion; velocity, acceleration, rotation and continuum. Control volume analysis: mass and energy equations. The Euler and Bernoulli''s equations. Differential analysis: Laminar and turbulent flow. Incompressible flow between parallel plates and inside circular tube. Laminar and turbulent flow in pipes. Fluid Energy losses in pipe flow. Frictional and Minor Losses. Pressure measurement processes and flow rate.

Prerequisite: CVE 224', '["Kinematics of fluid motion; velocity, acceleration, rotation and continuum", "Control volume analysis: mass and energy equations. The Euler and Bernoulli''s equations", "Differential analysis: Laminar and turbulent flow", "Incompressible flow between parallel plates and inside circular tube. Laminar and turbulent flow in pipes", "Fluid Energy losses in pipe flow. Frictional and Minor Losses. Pressure measurement processes and flow rate"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('CED 341', 'Introduction to Entrepreneurship I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering course handbook'),
  ('STA 205', 'Statistics for Physical Sciences and Engineering I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '300 Level', 'first', 2, 'Frequency Distributions. Elements of Probability. Discrete probability distributions: Binomial, Poisson, Geometric and Hyper-geometric. Continuous probability distributions: Normal, Student''s $t$, Chi-square $\chi^2$ and $F$. Combinatorial and moment generating functions.', '["Frequency Distributions", "Elements of Probability", "Discrete probability distributions: Binomial, Poisson, Geometric and Hyper-geometric", "Continuous probability distributions: Normal, Student''s $t$, Chi-square $\\chi^2$ and $F$", "Combinatorial and moment generating functions"]'::jsonb, 'Department of Statistics handbook'),
  ('MEE 312', 'Computer-Aided Design and Manufacture', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '300 Level', 'second', 2, 'Introduction to Computer Aided Design (CAD). Basic data structuring technique. Computer graphics. Geometric transformation techniques. Mathematical basis for surface modeling, curves, surfaces and solids. Principles of solid modeling and application. CAD software. Introduction to CAM: Relation between production volume and flexibility. Various manufacturing systems. Type of automation and benefits of soft and flexible automation. Automation in Material Handling and Assembly. CNC Machines: Introduction, classification, design and control features including interpolations. Numerical control and NC Part-Programming. Introduction to Robotics: Definitions, motivation, historical development. Basic structure, classification, workspace, drives, controls, sensors, grippers, specifications.

Prerequisites: MEE 211, MEE 212', '["Introduction to Computer Aided Design (CAD). Basic data structuring technique. Computer graphics. Geometric transformation techniques", "Mathematical basis for surface modeling, curves, surfaces and solids. Principles of solid modeling and application. CAD software", "Introduction to CAM: Relation between production volume and flexibility. Various manufacturing systems. Type of automation", "Automation in Material Handling and Assembly. CNC Machines: Introduction, classification, design and control features including interpolations", "Numerical control and NC Part-Programming", "Introduction to Robotics: Definitions, motivation, historical development, Basic structure, classification, workspace, drives, controls, sensors, grippers, specifications"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 314', 'Engineering Drawing II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '300 Level', 'second', 2, 'Part A: Projection of lines and laminae; auxiliary views and mixed projection. Advanced descriptive geometry: geometric constructions and developments. Preparation of detailed working drawings for production; semi-detailed drawings, conventional presentation methods. Machine drawing: Assembly drawing of machines, devices and installation layout; itemization and part listing.

Part B: Computer aided drawing practice (using the AutoCAD software or related software). Introduction to AutoCAD, New drawing setup. Specifying coordinates. Working with layers. Managing object properties. Controlling precision. 2D geometric drawing and viewing, selecting and editing 2D objects. Creating and editing hatches. Text creation and editing. Dimensioning. Plotting and printing.

Prerequisite: MEE 211', '["Part A: Projection of lines and laminae; auxiliary views and mixed projection. Advanced descriptive geometry", "Preparation of detailed working drawings for production. Machine drawing: Assembly drawing of machines, devices and installation layout", "Part B: Computer aided drawing practice using AutoCAD - drawing setup, coordinates, layers, object properties", "2D geometric drawing and viewing, editing hatches, text creation, dimensioning, plotting and printing"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 322', 'Mechanics of Materials Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '300 Level', 'second', 1, 'Uncertainty analysis, statistical analysis. Tensile test of ductile and brittle materials using the Universal Testing Machine. Poisson''s ratio. Torsion Testing. Bending. Modulus of Elasticity. Principal stresses and strains (Strain gauge applications). Beam deflection test. Column buckling test. FEA demonstrations.

Prerequisite: EGR 202', '["Uncertainty analysis, statistical analysis. Tensile test of ductile and brittle materials using the Universal Testing Machine", "Poisson''s ratio. Torsion Testing. Bending. Modulus of Elasticity", "Principal stresses and strains (Strain gauge applications)", "Beam deflection test. Column buckling test. FEA demonstrations"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 324', 'CAD/CAM Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '300 Level', 'second', 1, 'Introduction to SolidWorks. Basic SolidWorks functions. Advanced SolidWorks functions. Manual CNC programming, control and codes (using G-codes). Advanced CAD/CAM for CNC (milling and turning). Group project assignment.

Prerequisite: MEE 212', '["Introduction to SolidWorks. Basic SolidWorks functions. Advanced SolidWorks functions", "Manual CNC programming, control and codes (using G-codes)", "Advanced CAD/CAM for CNC (milling and turning)", "Group project assignment"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 332', 'Mechanics of Materials I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '300 Level', 'second', 3, 'The concept of stress. Axially loaded members. Bending of beams. Hooke''s law. Normal, shear and combined stresses, three dimensional stress and strain. Thick and thin-walled pressure vessels. Deflection under axial load and torsion. Statically determinate and indeterminate structures.

Prerequisite: CVE 211', '["The concept of stress. Axially loaded members. Bending of beams", "Hooke''s law. Normal, shear and combined stresses, three dimensional stress and strain", "Thick and thin-walled pressure vessels. Deflection under axial load and torsion", "Statically determinate and indeterminate structures"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 372', 'Heat and Mass Transfer I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '300 Level', 'second', 2, 'Introduction to heat transfer mechanisms and processes. Conduction heat transfer: Fourier''s law of conduction, energy equations of conduction, steady state 1-D conduction, boundary conditions, thermal analysis of conduction, composite bodies, thermal insulation and insulation economics, extended surfaces. Radiation heat transfer: generation, emission, absorption, reflection and transmission. Real/theoretical radiation properties of surfaces and materials, special surfaces: black body, gray and selective surfaces, thermal radiation exchange between two-body systems and cavity, thermal radiation exchange between black body and gray surfaces: electrical analogy of thermal radiation exchange.

Prerequisites: MEE 261, MTH 207', '["Introduction to heat transfer mechanisms and processes", "Conduction heat transfer: Fourier''s law of conduction, energy equations of conduction, steady state 1-D conduction, boundary conditions", "Thermal analysis of conduction, composite bodies, thermal insulation and insulation economics, extended surfaces", "Radiation heat transfer: generation, emission, absorption, reflection and transmission", "Real/theoretical radiation properties of surfaces and materials, special surfaces: black body, gray and selective surfaces", "Thermal radiation exchange between two-body systems and cavity, and between black body and gray surfaces: electrical analogy of thermal radiation exchange"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('CED 342', 'Introduction to Entrepreneurship II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering course handbook'),
  ('EEE 312', 'Electrical Engineering II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '300 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering course handbook'),
  ('EGR 302', 'Engineering Analysis', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '300 Level', 'second', 4, '', '[]'::jsonb, 'Faculty of Engineering course handbook'),
  ('MEE 413', 'Mechanical Engineering Design II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '400 Level', 'first', 3, 'Journal bearings. Applications of Hertz''s contact theory applied to Spherical Elastic materials. Hydrodynamic lubrication, applied to journal bearings. Gears, Power transmission systems, gear and gear trains. Fluid power system design. Design of cylinders, pipes and pressure vessels, plate/round flywheel. Nomenclature. Design, packaging and shells.

Prerequisite: MEE 313', '["Journal bearings. Applications of Hertz''s contact theory applied to Spherical Elastic materials", "Hydrodynamic lubrication, applied to journal bearings", "Gears, Power transmission systems, gear and gear trains", "Fluid power system design. Design of cylinders, pipes and pressure vessels, plate/round flywheel"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 421', 'Thermo-Fluids Laboratory II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '400 Level', 'first', 1, 'Wind tunnel jet and drag. Capital pump performance measurement. Turbine tests. Internal combustion engine tests. Gas turbine performance test. Throttling calorimeter experiments. Manual demonstrations test. Boiler tests. Pipeline network software tools (EPANET).

Prerequisite: MEE 321', '["Wind tunnel jet and drag. Capital pump performance measurement. Turbine tests", "Internal combustion engine tests. Gas turbine performance test", "Throttling calorimeter experiments. Manual demonstrations test", "Boiler tests. Pipeline network software tools (EPANET)"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 423', 'Mechanics of Machines Laboratory II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '400 Level', 'first', 1, 'The slider crank experiment. Four bar mechanism. Hookes joints. Disc and cam follower experiment. Whitworth quick return mechanism. Slotted link, Scotch yoke, Geneva stop and Oldham coupling.

Prerequisite: MEE 323', '["The slider crank experiment. Four bar mechanism. Hookes joints", "Disc and cam follower experiment. Whitworth quick return mechanism", "Slotted link, Scotch yoke, Geneva stop and Oldham coupling"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 425', 'Heat Transfer Laboratory I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '400 Level', 'first', 1, 'Conduction heat transfer through metal bars (thermal conductivity). Transient (convection) heat transfer. Forced convection heat transfer. Natural convection heat transfer. Radiation heat transfer test. Double pipe heat exchanger tests.

Prerequisite: MEE 372', '["Conduction heat transfer through metal bars (thermal conductivity)", "Transient (convection) heat transfer. Forced convection heat transfer. Natural convection heat transfer", "Radiation heat transfer test. Double pipe heat exchanger tests"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 441', 'Mechanics of Machines II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '400 Level', 'first', 2, 'Force analysis of mechanisms, fluctuation of kinetic energy and inertial effects. Complete static and dynamic balancing. Flexible shaft couplings; Belt, rope and chain drives. The flywheel and mechanical governors. Brakes and dynamometers. Balancing of multi-cylinder engines. Balancing of machinery.

Prerequisite: MEE 341', '["Force analysis of mechanisms, fluctuation of kinetic energy and inertial effects", "Complete static and dynamic balancing", "Flexible shaft couplings; Belt, rope and chain drives. The flywheel and mechanical governors", "Brakes and dynamometers. Balancing of multi-cylinder engines. Balancing of machinery"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 443', 'Automatic Control', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '400 Level', 'first', 3, 'Linear feedback control theory with emphasis on mechanical systems. Transient and frequency response. Stability. System performance criteria, compensation methods. Analysis of hydraulic, pneumatic, mental components and systems.

Prerequisite: EGR 301', '["Linear feedback control theory with emphasis on mechanical systems", "Transient and frequency response. Stability", "System performance criteria, compensation methods", "Analysis of hydraulic, pneumatic, mental components and systems"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 451', 'Applied Fluid Mechanics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '400 Level', 'first', 2, 'Dimensional analysis and similitude. Introduction to Turbomachinery: characteristic curve for axial-flow and centrifugal pumps/fans, blowers, impulse and reaction turbines. Pump Selection and Application. Pipeline Systems (Series and Parallel). Open Channel Flow.

Prerequisite: MEE 351', '["Dimensional analysis and similitude", "Introduction to Turbomachinery: characteristic curve for axial-flow and centrifugal pumps/fans, blowers, impulse and reaction turbines", "Pump Selection and Application", "Pipeline Systems (Series and Parallel). Open Channel Flow"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 461', 'Engineering Thermodynamics III', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '400 Level', 'first', 2, 'Multistage reciprocating compressors. Rotary compressors centrifugal and axial-flow; stagnation properties. Simple gas turbine plant. The steam power plant. Combustion of fuels; chemistry of common hydrocarbon fuels, combustion with efficiency of excess air. Thermo-chemistry: Hess'' Law of Heat Summation, Heats of combustion and reaction; ideal adiabatic flame temperature. Reciprocating internal combustion engines. Thermodynamics of reacting systems: first law and second law analysis of reacting systems. Chemical equilibrium and Dissociation. Introduction to phase and chemical equilibrium.

Prerequisite: MEE 361', '["Multistage reciprocating compressors. Rotary compressors centrifugal and axial-flow; stagnation properties", "Simple gas turbine plant. The steam power plant", "Combustion of fuels; chemistry of common hydrocarbon fuels, combustion with efficiency of excess air", "Thermo-chemistry: Hess'' Law of Heat Summation, Heats of combustion and reaction; ideal adiabatic flame temperature", "Reciprocating internal combustion engines", "Thermodynamics of reacting systems: first law and second law analysis. Chemical equilibrium and Dissociation. Introduction to phase and chemical equilibrium"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 471', 'Heat and Mass Transfer II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '400 Level', 'first', 2, 'Convection heat transfer: Newton''s law of cooling, energy equation of convection, continuity and momentum equations and their roles in convection heat transfer analysis, convection heat transfer in laminar and turbulent flows. Internal and external flows, heat transfer coefficients, dimensional analysis and dimensionless groups in convection heat transfer, convection heat transfer correlations, heat exchanger analysis and design, combined modes of heat transfer.

Mass transfer: mechanisms of mass transfer: Fick''s law of mass diffusion, general diffusion law, rate equations, comparison of Fick''s and Fourier''s laws, equations of mass transfer in stationary systems, similarities between conduction and mass transfer in stationary systems, mass transfer coefficients, electrical analogy of mass transfer, equimolar counter diffusion, drying and humidification of solids and gases, types of dryers, evaporation, mass transfer correlations in convective systems.

Prerequisite: MEE 372', '["Convection heat transfer: Newton''s law of cooling, energy equation of convection, continuity and momentum equations", "Convection heat transfer in laminar and turbulent flows, internal and external flows, heat transfer coefficients", "Dimensional analysis and dimensionless groups in convection heat transfer, convection heat transfer correlations, heat exchanger analysis and design", "Mass transfer: mechanisms of mass transfer, Fick''s law of mass diffusion, general diffusion law, rate equations, comparison of Fick''s and Fourier''s laws", "Equations of mass transfer in stationary systems, mass transfer coefficients, electrical analogy of mass transfer", "Drying and humidification of solids and gases, types of dryers, evaporation, mass transfer correlations in convective systems"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 481', 'Technology Development Policy', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '400 Level', 'first', 2, 'Industrialization and economic development of developing and developed countries. Sources of funds for financial investment, development control and monetary/economics aspect of technology, industrial effect of productivity and standard of living, and economic development. Techniques for increasing productivity. Definition of management techniques, work study and its advantages. Basic procedure for method study, use of charts and models, factory floor levels, examples of method study. Basic procedure for work measurement, time study, Rate fixing/incentive, sampling methods, wage administration.

Prerequisite: MEE 373', '["Industrialization and economic development of developing and developed countries", "Sources of funds for financial investment, development control and monetary/economics aspect of technology", "Industrial effect of productivity and standard of living, and economic development. Techniques for increasing productivity", "Definition of management techniques, work study and its advantages. Basic procedure for method study, use of charts and models", "Basic procedure for work measurement, time study, Rate fixing/incentive, sampling methods, wage administration"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('EGR 401', 'Computational Methods', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '400 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering course handbook'),
  ('MEE 402', 'Written Technical Communication', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '400 Level', 'second', 2, 'Real processing tools for technical report writing.

Prerequisites: GSP 101, GSP 102', '["Real processing tools for technical report writing"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 404', 'Seminar Presentation Skills', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '400 Level', 'second', 1, 'During the early weeks of the first semester of the final year, students undertaking from the SIWES programmes are required to present a seminar on technical experiences gained during the SIWES. During the semester, each student is also expected to prepare a technical report of his/her SIWES experience within technical writing guidelines. Reports must be reviewed by each student based on the guidelines provided in the Written Technical Communication course.', '["During the early weeks of the first semester of the final year, students are required to present a seminar on technical experiences gained during the SIWES", "Each student is also expected to prepare a technical report of his/her SIWES experience within technical writing guidelines", "Reports must be reviewed by each student based on the guidelines provided in the Written Technical Communication course"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 412', 'Computer Aided Design Practice', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '400 Level', 'second', 2, 'This is a course in modern computer-aided design engineering with practice on advanced modeling and application of solid CAD tools. Advanced modeling techniques and design of machine parts, mechanical products, will be sequentially used to work on the design work of the assembly. The machine products expected to be handled in this practical exercise, will be worked on term based on the reports containing all the drawings and associated computational work to be presented to the Department.

Prerequisite: MEE 324', '["This is a course in modern computer-aided design engineering with practice on advanced modeling and application of solid CAD tools", "Advanced modeling techniques and design of machine parts, mechanical products, will be sequentially used to work on the design work of the assembly", "The machine products expected to be handled in this practical exercise will be worked on and reported as term-based drawings and computational work presented to the Department"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('EGR 402', 'SIWES', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '400 Level', 'second', 10, '', '[]'::jsonb, 'Faculty of Engineering course handbook'),
  ('MEE 511', 'Applied Design', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'first', 3, 'Scientific Design Methodology. An appreciation of the process of engineering design, and of components involved in mechanical/machine design. Processes, materials, methods of manufacture/methods of construction, and manufacturing constraints, environmental factors and management/related fields required at the design of mechanical parts. Reports submitted by students should consider the manufacture, effects, and interruptions on design; design constraints.

Prerequisite: MEE 413', '["Scientific Design Methodology. An appreciation of the process of engineering design, and of components involved in mechanical/machine design", "Processes, materials, methods of manufacture/construction, and manufacturing constraints", "Environmental factors and management/related fields required at the design of mechanical parts", "Reports submitted by students should consider the manufacture, effects, and interruptions on design; design constraints"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 531', 'Mechanics of Materials II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'first', 3, 'Strain energy, principle of virtual work. Castigliano''s theorem. Bending of thick walls, thick-walled, indeterminate beams. Plastic hinges. Columns – stability of elastic mechanical systems. Long straight columns effect of end conditions. Eccentric loading. The secant formula. Empirical formulae for intermediate and short columns: Impact loading.

Prerequisite: MEE 332', '["Strain energy, principle of virtual work. Castigliano''s theorem", "Bending of thick walls, thick-walled, indeterminate beams. Plastic hinges", "Columns – stability of elastic mechanical systems. Long straight columns effect of end conditions. Eccentric loading", "The secant formula. Empirical formulae for intermediate and short columns: Impact loading"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 551', 'Fluid Dynamics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'first', 3, '', '[]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 561', 'Engineering Thermodynamics IV', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'first', 3, '', '[]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 555', 'Aerospace Engineering Fundamentals', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'first', 3, 'Classification of aerospace vehicles, parts of aircraft; standard atmosphere. 1-D Compressible flow around aerodynamic conservation equations, viscosity and speed of sound. Airfoils, wing aerodynamics: geometric and nomenclature, lift, drag characteristics, aerofoils, aircraft structures, materials, loads, cabin, etc. high-lift devices. Aircraft structural components and elements. Aircraft propulsion: propellers, jet propulsion, gas turbojets, propulsion cycles basics, types of jet engines (Turbojet, Turbofan, Ducted Fan & Ramjet). Diffusers & Nozzles. Aircraft propulsion engine selection. Flight mechanics: performance, stability and control.

Prerequisite: MEE 451', '["Classification of aerospace vehicles, parts of aircraft; standard atmosphere", "1-D Compressible flow around aerodynamic conservation equations, viscosity and speed of sound", "Airfoils, wing aerodynamics: geometric and nomenclature, lift, drag characteristics", "Aircraft structures, materials, loads, cabin, high-lift devices. Aircraft structural components and elements", "Aircraft propulsion: propellers, jet propulsion, gas turbojets, propulsion cycles basics, types of jet engines (Turbojet, Turbofan, Ducted Fan & Ramjet). Diffusers & Nozzles", "Aircraft propulsion engine selection. Flight mechanics: performance, stability and control"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 557', 'Fluid Power Transmission Systems', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'first', 3, 'Properties of hydraulic fluids. Dynamic flow analysis, Hydraulic and pneumatic, and fluids systems and components; characteristics of flow and pressure control valves, actuators, position motors, pumps, hydro-valves, and hydro-based systems: transmission systems, Filtration and control of hydraulic systems. Seals and packing. System design and circuit analysis. Introduction to pneumatic-hydro systems. Control components and design procedures.

Prerequisite: MEE 451', '["Properties of hydraulic fluids. Dynamic flow analysis, Hydraulic and pneumatic fluids systems and components", "Characteristics of flow and pressure control valves, actuators, position motors, pumps, hydro-valves", "Transmission systems, Filtration and control of hydraulic systems. Seals and packing", "System design and circuit analysis. Introduction to pneumatic-hydro systems. Control components and design procedures"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 563', 'Automotive Engineering Fundamentals', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'first', 3, 'Power Cycle Thermodynamics. Basics of Otto and Diesel cycle. Power Plants for Automobiles, Elements of Diesel and Petrol Engines, Engine Performance curves. Power Components and Electronic Controls. Diesel and gas turbine Propulsion, Lubrications and Wear, Engine Modeling, Engine Vibrations and Balance, Fuels and Combustion, Engine Exhaust Emissions: Air pollution, control measures and Emission norms. Engine Manufacturing.

Prerequisite: MEE 461', '["Power Cycle Thermodynamics. Basics of Otto and Diesel cycle", "Power Plants for Automobiles, Elements of Diesel and Petrol Engines, Engine Performance curves", "Power Components and Electronic Controls. Diesel and gas turbine Propulsion, Lubrications and Wear", "Engine Modeling, Engine Vibrations and Balance, Fuels and Combustion", "Engine Exhaust Emissions: Air pollution, control measures and Emission norms. Engine Manufacturing"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 565', 'Fundamentals of Nuclear Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'first', 3, 'Introduction to nuclear engineering. Biological effects of radiation. Radiation protection and reactor safeguards, radiation hazards and biological health, physics, shield design, nuclear reactors, and radiation transformation. Neutron balance. Neutron reactor theory. Water moderated hot fuel reactors. Common nuclear reactors, moderators. Reactor fuels/moderate reactors, properties, reprocessing and waste disposal, and reactor design.

Prerequisite: MEE 461', '["Introduction to nuclear engineering. Biological effects of radiation", "Radiation protection and reactor safeguards, radiation hazards and biological health", "Physics, shield design, nuclear reactors, and radiation transformation. Neutron balance. Neutron reactor theory", "Water moderated hot fuel reactors. Common nuclear reactors, moderators", "Reactor fuels/moderate reactors, properties, reprocessing and waste disposal, and reactor design"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 569', 'Direct Energy Conversion Principles', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'first', 3, '', '[]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 572', 'Thermal Engineering and Advanced Heat Transfer', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'first', 3, '', '[]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 513', 'Manufacturing and Tools Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'first', 3, 'Manufacturing and processes and material considerations. Cutting techniques. Solidification and heat flow theory. Metal forming: forging, milling, extrusion, forging techniques. Metal casting: casting design process, mold design, defect formation, design consideration, forming techniques. Machining theory and practice. Heat treatment and surface hardening. Different manufacturing: (1) Numerical control (2) 3D printing. Composites: Design and Polymer, Ceramic, Metal and composite, plastic mould design, fabrication. Tool engineering: principles, design methods for tools and mold and functional grouping. Fundamental aspects of function tool design and control, machine tool techniques.

Prerequisites: MEE 311, MEE 312', '["Manufacturing and processes and material considerations. Cutting techniques. Solidification and heat flow theory", "Metal forming: forging, milling, extrusion, forging techniques", "Metal casting: casting design process, mold design, defect formation, design consideration, forming techniques", "Machining theory and practice. Heat treatment and surface hardening", "Different manufacturing: Numerical control, 3D printing. Composites: Design and Polymer, Ceramic, Metal and composite, plastic mould design, fabrication", "Tool engineering: principles, design methods for tools and mold and functional grouping. Fundamental aspects of function tool design and control, machine tool techniques"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 515', 'Design of Welded and Cast Structures', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'first', 3, 'Review of elastic, plastic, and creep behaviour of materials and applications of low-cycle and multi-axial stress states. Welding and casting processes. Design of structures with adequate industrial welding processes. Material and process selection, codes and specifications, casting equipment. Laboratory experience in the production and evaluation of weldments and castings.

Prerequisite: MEE 512', '["Review of elastic, plastic, and creep behaviour of materials and applications of low-cycle and multi-axial stress states", "Welding and casting processes. Design of structures with adequate industrial welding processes", "Material and process selection, codes and specifications, casting equipment", "Laboratory experience in the production and evaluation of weldments and castings"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 533', 'Engineering Metallurgy', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'first', 3, 'Alloy classification. Theory of phase and shells. Thermal structures in metals or steel processing. Effect of elasticity. Equilibrium and metastability. Iron carbon system in equilibrium with ferrite and cementite. Simple problems. Crack mechanisms, stress/failure, approach to failure mechanics. Other stiffness method, the finite element method for structures. Metallurgy: modern techniques of welding and applications. Weldability of industrial materials. Destructive and non-destructive testing of materials, ultrasonic and X-ray test. Evaluation of the relevant factors in materials selection: technical and economic considerations. Materials for structural, high-temperature, cryogenic, electrical, electronic and nuclear applications. Corrosion and failure economics of recycling. Current status and future prospects of important engineering materials.

Prerequisite: MEE 332', '["Alloy classification. Theory of phase and shells. Thermal structures in metals or steel processing", "Equilibrium and metastability. Iron carbon system in equilibrium with ferrite and cementite", "Crack mechanisms, stress/failure, approach to failure mechanics. Finite element method for structures", "Metallurgy: modern techniques of welding and applications. Weldability of industrial materials", "Destructive and non-destructive testing of materials, ultrasonic and X-ray test", "Materials for structural, high-temperature, cryogenic, electrical, electronic and nuclear applications. Corrosion and failure economics of recycling"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 541', 'Systems Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'first', 3, 'System modeling: Modeling of systems by algebraic, differential, ordinary differential equations, hybrid and digital categorizes. System simulations using models. Feedback and control systems. System optimization using differential calculus, variational calculus, linear programming and dynamic programming; system behaviour: categories of systems, behaviour illustrated by the study of selected mechanical, electrical, hydraulic, industrial, transportation, economic, biological and social systems. System control: Description, analysis: Estimation of input output. Utility and value analysis. Multiple attributes and preferences. Production functions and copyright analysis. Economics: Estimation of public system.

Prerequisite: MEE 443', '["System modeling: Modeling of systems by algebraic, differential, ordinary differential equations, hybrid and digital categorizes", "System simulations using models. Feedback and control systems", "System optimization using differential calculus, variational calculus, linear programming and dynamic programming", "System behaviour: categories of systems illustrated by selected mechanical, electrical, hydraulic, industrial, transportation, economic, biological and social systems", "System control: Description, analysis: Estimation of input output. Utility and value analysis. Multiple attributes and preferences"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 543', 'Vibrations and Control', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'first', 3, 'Free and forced vibrations of single degree of freedom systems, Damped vibrations. Vibration isolation and force-speed. Two and multiple-degrees-of-freedom systems. Elasto-mechanical analogue. Linear systems of the first order. Response to standard inputs. The closed loop control system. Block diagram algebra. Stability analysis. Electrical systems. Dynamics of Machinery: Kinematic and dynamic analysis and synthesis of mechanisms and machines. Design and analysis considerations in reciprocating and rotating machinery. Vibrations of systems with more than one degree of freedom. Vibration and shock isolation. Experimental investigation of dynamic systems.

Prerequisite: MEE 443', '["Free and forced vibrations of single degree of freedom systems, Damped vibrations. Vibration isolation and force-speed", "Two and multiple-degrees-of-freedom systems. Elasto-mechanical analogue", "Linear systems of the first order. Response to standard inputs. The closed loop control system. Block diagram algebra. Stability analysis", "Dynamics of Machinery: Kinematic and dynamic analysis and synthesis of mechanisms and machines", "Design and analysis considerations in reciprocating and rotating machinery. Vibrations of systems with more than one degree of freedom", "Vibration and shock isolation. Experimental investigation of dynamic systems"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 545', 'Mechatronics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'first', 3, 'Introduction to Digital Control Systems: Analog control systems and digital control systems. Control system design and analysis. Modeling of dynamic systems: Response characteristics of a control system. Hardware (microprocessors) and software for implementing a digital controller. Design, analysis and construction of digital control systems by MATLAB/Simulink.

Electronic Control Systems in Mechanical Engineering: Robotics and automation. Mechatronic applications: structural controls, home automation, robotics, motor control, data and image sensors, sensors used in control systems, system drives, hydraulic systems, DC motors, stepping motors, AC motors. Feedback and control devices. Interfacing devices. Data acquisition. Analog and digital converting. Encoders, decoders, digital vs analog conversions. Mechatronic system design for pneumatic, and fluids systems and components; characteristics of flow and pressure control valves, actuators, position motors, pumps, hydro-valves, and hydro-based systems: transmission systems, Filtration and control of hydraulic systems. Seals and packing. System design and circuit analysis. Introduction to pneumatic-hydro systems. Control components and design procedures.

Prerequisites: MEE 343, EEE 317, MEE 443', '["Introduction to Digital Control Systems: Analog and digital control systems. Control system design and analysis", "Modeling of dynamic systems: Response characteristics of a control system. Hardware and software for implementing a digital controller", "Design, analysis and construction of digital control systems by MATLAB/Simulink", "Electronic Control Systems in Mechanical Engineering: Robotics and automation. Mechatronic applications: structural controls, home automation, robotics, motor control", "Data and image sensors, sensors used in control systems, system drives, hydraulic systems, DC motors, stepping motors, AC motors", "Feedback and control devices. Interfacing devices. Data acquisition. Analog and digital converting. Encoders, decoders"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 547', 'Automobile Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'first', 3, 'Introduction to automobile. Vehicle Performance Characteristics and Requirements. Power train. Transmission and Drive units. Exhaust System. Braking and Suspension Systems. Chassis and Body Design. Steering systems, Electrical and Lighting Systems, Safety and Comfort Features. Wheel and Tyre. NVH Considerations in Vehicle Design. Vehicle Ride and Handling Evaluation.

Prerequisite: MEE 451', '["Introduction to automobile. Vehicle Performance Characteristics and Requirements", "Power train. Transmission and Drive units. Exhaust System", "Braking and Suspension Systems. Chassis and Body Design", "Steering systems, Electrical and Lighting Systems, Safety and Comfort Features", "Wheel and Tyre. NVH Considerations in Vehicle Design. Vehicle Ride and Handling Evaluation"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 581', 'Quality Assurance and Reliability', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'first', 3, '', '[]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 534', 'Materials for Engineering Applications', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'second', 3, 'Metallic and non-metallic composite, structure, composition, mechanical and thermal properties. The modification of properties through changes in microstructure (Heat treatment). Welding.

Prerequisite: EGR 201', '["Metallic and non-metallic composite, structure, composition, mechanical and thermal properties", "The modification of properties through changes in microstructure (Heat treatment)", "Welding"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 582', 'Engineering Law', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'second', 2, '...Duties, Damages and Other Remedies. Restatements/miscellaneous of Contract Assessment and Facilities, Exemptions, clauses, safety and Risk, Health and Safety. Duties of Employers towards their employees.

Note: the opening portion of this description (before "Duties, Damages...") was on a page photographed with heavy motion blur and could not be transcribed.', '["Duties, Damages and Other Remedies. Restatements/miscellaneous of Contract Assessment and Facilities, Exemptions clauses", "Safety and Risk, Health and Safety. Duties of Employers towards their employees"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 584', 'Engineering Management', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'second', 2, 'General principles of management and appraisal techniques. Design and organization theory: designs, proposal, management, ethics and public relations, wages and salary administration. Production and operations management. Training and workforce development. The manager and public relations/networking: objectives, setting, planning, organizing and controlling, motivation and appraisals of results.', '["General principles of management and appraisal techniques", "Design and organization theory: designs, proposal, management, ethics and public relations, wages and salary administration", "Production and operations management. Training and workforce development", "The manager and public relations/networking: objectives, setting, planning, organizing and controlling, motivation and appraisals of results"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 586', 'Engineering Economy', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'second', 3, 'Economics: basic setting in Engineering. Engineering costs and cost estimation. Fixed and variable costs, incremental and non-incremental costs, life-cycle costs, etc, and information models, estimating benefits, cash flow diagrams, interest and Equivalence. Comparing cash flows: time value of money, simple interest, compound interest. Methods for evaluating capital projects: Present worth analysis, Annual cash flow analysis, Rate of return analysis, Future worth analysis, Benefit/Cost ratio analysis. Payback period. Sensitivity and Breakeven analysis. Comparison of alternatives and decision analysis. Uncertainty (Risk) analysis. Taxes, tariffs and duties. Depreciation and Replacement analysis. Inflation and price change. Minimum attractive rate of return (MARR). Public Sector economic analysis. Elements of Accounting for Engineering Economy.', '["Economics: basic setting in Engineering. Engineering costs and cost estimation", "Fixed and variable costs, incremental and non-incremental costs, life-cycle costs, cash flow diagrams, interest and Equivalence", "Comparing cash flows: time value of money, simple interest, compound interest", "Methods for evaluating capital projects: Present worth analysis, Annual cash flow analysis, Rate of return analysis, Future worth analysis, Benefit/Cost ratio analysis", "Payback period. Sensitivity and Breakeven analysis. Comparison of alternatives and decision analysis. Uncertainty (Risk) analysis", "Taxes, tariffs and duties. Depreciation and Replacement analysis. Inflation and price change. Minimum attractive rate of return (MARR). Public Sector economic analysis"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 592', 'B.Eng. Project', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'second', 6, 'Final Year Projects are assigned at the beginning of each academic year. Each final year student chooses a project supervisor in consultation with the Final Year Project Coordinator. The process is not entirely interactive, but the coordinator ensures that there is fair distribution of students amongst the lecturers. The student and their supervisor decide the final topic. The topic should come from any of the fields of mechanics of solids and fluids, materials science, machine design, heat power, heat transfer, production techniques, industrial engineering and management. Each student presents at least two seminars as part of his final year project, usually at the beginning and ending of the second semester. Each student is required to submit a report of his findings and undergo an oral examination. A panel of lecturers scores all seminars.', '["Final Year Projects are assigned at the beginning of each academic year. Each final year student chooses a project supervisor in consultation with the Final Year Project Coordinator", "The student and their supervisor decide the final topic, from any of the fields of mechanics of solids and fluids, materials science, machine design, heat power, heat transfer, production techniques, industrial engineering and management", "Each student presents at least two seminars as part of his final year project, at the beginning and ending of the second semester", "Each student is required to submit a report of his findings and undergo an oral examination before a panel of lecturers"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 552', 'Computational Fluid Dynamics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'second', 3, 'Introduction to Computational Fluid Dynamics (CFD) and CFD software (OpenFOAM, ANSYS Fluent, COMSOL, StarCD, etc.) Defining a CFD problem: Creating and inspecting Geometry and Mesh. Elements: properties of fluids and conservation laws, Navier-Stokes equations and similarity. Analysis and Boundary Conditions: physical, practical conditions. Turbulence: Sources and introduction, discretization, Solution Procedure. Post Processing – analysis of results. Validation and Verification.

Prerequisites: EGR 401, MEE 451', '["Introduction to Computational Fluid Dynamics (CFD) and CFD software (OpenFOAM, ANSYS Fluent, COMSOL, StarCD, etc.)", "Defining a CFD problem: Creating and inspecting Geometry and Mesh", "Elements: properties of fluids and conservation laws, Navier-Stokes equations and similarity", "Analysis and Boundary Conditions: physical, practical conditions. Turbulence: Sources and introduction, discretization, Solution Procedure", "Post Processing – analysis of results. Validation and Verification"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 562', 'Refrigeration and Air-Conditioning', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'second', 3, 'Fundamentals of vapor compression refrigeration, analysis of refrigeration cycles and equipment. Refrigerants and their properties. Absorption refrigeration systems. Low temperature refrigeration Applications. Elements and Design of Refrigeration and air conditioning, cooling load calculation. Psychrometric processes involved in air conditioning. Production of atmospheric and thermal air treatments for the human body. Heat sources and climatic and psychrometric processes, Evaluation of cooling and heating loads. Schedule of information supply, hot and refrigerated. Chilled water and condenser water piping. Steam heating and heating systems. Air-conditioning controls. Humidification and air-conditioning systems. Cooling towers.

Prerequisite: MEE 461', '["Fundamentals of vapor compression refrigeration, analysis of refrigeration cycles and equipment. Refrigerants and their properties", "Absorption refrigeration systems. Low temperature refrigeration Applications", "Elements and Design of Refrigeration and air conditioning, cooling load calculation. Psychrometric processes involved in air conditioning", "Heat sources and climatic and psychrometric processes, Evaluation of cooling and heating loads", "Chilled water and condenser water piping. Steam heating and heating systems. Air-conditioning controls", "Humidification and air-conditioning systems. Cooling towers"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 568', 'Power Plant Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'second', 3, 'Introduction to Power Plants: energy system considerations. Fundamentals of combustion processes of solid, liquid and gaseous fuels. Steam power plants: Fundamental cycle, Diesel and gas turbine cycle, auxiliary power station equipment. Steam and gas plant power operations. Hydroelectric, geothermal and other alternative energy stations. Combined power plants, Fuels and Combustion. Engine Exhaust Emissions: Air pollution, control measures and Emission norms. Engine Manufacturing.

Prerequisite: MEE 461', '["Introduction to Power Plants: energy system considerations", "Fundamentals of combustion processes of solid, liquid and gaseous fuels", "Steam power plants: Fundamental cycle, Diesel and gas turbine cycle, auxiliary power station equipment", "Steam and gas plant power operations. Hydroelectric, geothermal and other alternative energy stations", "Combined power plants, Fuels and Combustion. Engine Exhaust Emissions: Air pollution, control measures and Emission norms"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 512', 'Design of Pressure Vessels', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'second', 3, 'Overview of pressure vessels. Overview of pressure vessel design codes (e.g. the ASME Section VIII). Design philosophy. Structural design criteria. Stress/failure theories. Load categories. Failure modes. Stress categories and limits. Design of cylinder shells with heads and covers, nozzles and openings. Design of vessel supports. Bolted flange connections. Use of pressure vessel design software. New trends in pressure vessel design.

Prerequisite: MEE 332', '["Overview of pressure vessels. Overview of pressure vessel design codes (e.g. the ASME Section VIII). Design philosophy", "Structural design criteria. Stress/failure theories. Load categories. Failure modes. Stress categories and limits", "Design of cylinder shells with heads and covers, nozzles and openings. Design of vessel supports. Bolted flange connections", "Use of pressure vessel design software. New trends in pressure vessel design"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 532', 'Theory of Elasticity', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'second', 3, '', '[]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 536', 'Introduction to Composite Materials', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '500 Level', 'second', 3, 'Introduction. Fibers and Matrices. Micromechanics, Mechanics of Composite Materials. Anisotropy and Laminate Theory. Micromechanics and Interface: Strength and Fracture, Damage Response. Fabrication Techniques. Composite Design.

Prerequisites: EGR 201, MEE 332', '["Introduction. Fibers and Matrices. Micromechanics, Mechanics of Composite Materials", "Anisotropy and Laminate Theory", "Micromechanics and Interface: Strength and Fracture, Damage Response", "Fabrication Techniques. Composite Design"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MEE 181', 'Technical Drawing I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '100 Level', 'first', 3, 'Use of drawing instruments. Lettering and dimensioning. Geometrical constructions: Tangency, Conic sections and loci. First and Third Angle Orthographic Projections.', '["Use of drawing instruments. Lettering and dimensioning", "Geometrical constructions: Tangency, Conic sections and loci", "First and Third Angle Orthographic Projections"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('EGR 201', 'Materials Science', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering course handbook'),
  ('EGR 203', 'Materials Science Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '200 Level', 'first', 1, '', '[]'::jsonb, 'Faculty of Engineering course handbook'),
  ('CVE 211', 'Strength of Materials I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering course handbook'),
  ('CVE 213', 'Strength of Materials Laboratory I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '200 Level', 'first', 1, '', '[]'::jsonb, 'Faculty of Engineering course handbook'),
  ('EEE 211', 'Basic Electrical Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Mechanical Engineering', '200 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering course handbook')
;
