-- =============================================================================
-- University of Nigeria, Nsukka -- Faculty of Environmental Studies
-- Department of Geoinformatics and Surveying
-- =============================================================================
-- Transcribed from the department's own official website (course code,
-- title, credit unit, level and semester for each course). 104 rows.
--
-- The department's site publishes the course list but not per-course
-- syllabus descriptions or topic breakdowns, so description and topics are
-- left empty here rather than invented.
--
-- Five-year standard programme. The source page notes a SIWES placement at 400 Level, Second Semester but prints no course code or unit value for it, so that row is omitted here rather than inventing a code.
-- =============================================================================

delete from public.course_outlines
 where institution = 'University of Nigeria, Nsukka'
   and department = 'Geoinformatics and Surveying';

insert into public.course_outlines
  (course_code, course_title, institution, faculty, department, level,
   semester, credit_units, description, topics, contributor_name, is_elective)
values
  ('GSV 101', 'Introduction to Geoinformatics and Surveying I', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '100 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('COS 101', 'Introduction to Computer Science', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '100 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('MTH 111', 'Elementary Mathematics I', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '100 Level', 'first', 3, '', '[]'::jsonb, 'Department official website', false),
  ('MTH 121', 'Elementary Mathematics II', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '100 Level', 'first', 3, '', '[]'::jsonb, 'Department official website', false),
  ('PHY 115', 'General Physics for Physical Science I', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '100 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('PHY 191', 'Practical Physics', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '100 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSP 101', 'Use of English I', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '100 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSP 111', 'The Use of Library', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '100 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 102', 'Introduction to Geoinformatics and Surveying II', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '100 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 114', 'Geoinformatics and Surveying Practical', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '100 Level', 'second', 1, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 162', 'Computer Application to Geoinformatics and Surveying', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '100 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('URP 102', 'Nature of Environmental Sciences', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '100 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('PHY 105', 'General Physics for Physical Sciences II', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '100 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('PHY 106', 'General Physics for Physical Sciences III', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '100 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('MTH 122', 'Elementary Mathematics III', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '100 Level', 'second', 3, '', '[]'::jsonb, 'Department official website', false),
  ('GSP 102', 'Use of English II', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '100 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSP 104', 'Social Sciences II', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '100 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 211', 'Local Control Surveys', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 215', 'Field Surveying Practical I', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'first', 1, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 213', 'Electromagnetic Radiations for Geoinformatics and Surveying', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 251', 'Fundamental Cartographic Techniques', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('COS 201', 'Computer Programming', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('MTH 203', 'Advanced Mathematics III', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('STA 205', 'Statistics for Physical Science and Engineering I', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('PHY 242', 'Geometric Optics', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSP 207', 'Humanities I', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSP 201', 'Basic Concepts and Theories of Peace and Conflicts', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 201', 'Basic Land Surveying I', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 214', 'Topographic Ground Surveys', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 216', 'Field Surveying Practical II', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'second', 1, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 232', 'Fundamental Photogrammetry', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 234', 'Photogrammetry Practical I', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'second', 1, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 252', 'Methods of Cartographic Data Presentation in Geoinformatics and Surveying II', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 262', 'Computer Applications in Geoinformatics and Surveying II', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('MTH 204', 'Advanced Mathematics IV', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('URP 112', 'Urban and Regional Planning', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'second', 3, '', '[]'::jsonb, 'Department official website', false),
  ('STA 206', 'Statistics for Physical Science and Engineering II', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSP 208', 'Humanities II', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSP 202', 'Issues in Peace and Conflict Resolution Studies', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 202', 'Basic Land Surveying II', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 311', 'Cadastral Ground Surveys', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 317', 'Field Surveying Practical III', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'first', 1, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 313', 'Electronics for Geoinformatics and Surveying I', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 321', 'Geometric Geodesy', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 333', 'Remote Sensing I', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 361', 'Adjustment Computation I', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 371', 'Geospatial Database Design and Development I', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('CED 341', 'Introduction to Entrepreneurship', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 315', 'Electromagnetic Radiation for Geoinformatics and Surveying II', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 351', 'Graphic Designs in Map Making', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('LAW 335', 'Principles of Land Law', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('HPE 111', 'Basic Skill of Swimming and Water Safety', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('ESM 261', 'Introduction to Valuation II', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('ESM 201', 'Principles of Property Valuation', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 312', 'Engineering Ground Surveys', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 314', 'Mining Surveying and Special Surveys', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 332', 'Analogue Photogrammetry', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 334', 'Practical Photogrammetry II', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'second', 1, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 322', 'Potential Theory as Applied to Geodesy', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 342', 'Hydraulics for Surveyors', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 362', 'Applied Mathematical Methods', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 372', 'GIS Practical I', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'second', 1, '', '[]'::jsonb, 'Department official website', false),
  ('CED 342', 'Business Development and Management', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 316', 'Surveying Applications in Oil Industry', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('ESM 262', 'Introduction to Valuation III', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '300 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 421', 'Geodetic Surveying', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '400 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 423', 'Geodetic Astronomy', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '400 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 425', 'Practical Geodetic Astronomy', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '400 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 431', 'Analytical Photogrammetry', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '400 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 441', 'Hydrographic Surveying I', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '400 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 443', 'Practical Hydrographic Surveying', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '400 Level', 'first', 1, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 461', 'Adjustment Computation II', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '400 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 471', 'GIS Design and Development II', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '400 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 473', 'GIS Practical II', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '400 Level', 'first', 1, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 481', 'Research Methods in Geoinformatics and Surveying', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '400 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('LAW 335', 'Principles of Land Law', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '400 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 315', 'Electromagnetic Radiations in Geoinformatics and Surveying', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '400 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 451', 'Cartographic Techniques in Geoinformatics and Surveying', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '400 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('HPE 111', 'Basic Skill of Swimming and Water Safety', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '400 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GEO 371', 'Principles of Geophysics', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '400 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 511', 'Survey Laws and Regulations', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 521', 'Physical Geodesy', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 531', 'Aerotriangulation and Digital Photogrammetry', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 535', 'Practical Photogrammetry III', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'first', 1, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 541', 'Hydrographic Surveying II', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 571', 'Geospatial Database Analysis and Presentation I', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 523', 'Navigation', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 543', 'Laws of the Sea', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 551', 'Small Scale Cartography', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('ACC 101', 'Elements of Account I', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('PHY 371', 'Meteorology', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('PHY 473', 'Physics of the Earth''s Interior', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('MAN 301', 'Elements of Management', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('BF 221', 'Principles of Insurance', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('URP 531', 'Environmental Impact Assessment', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'first', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 512', 'Professional Practices in Geoinformatics and Surveying', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 522', 'Space Geodesy II', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 532', 'Remote Sensing II', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 514', 'Cadastre and Land Information Management', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 572', 'Geospatial Database Analysis and Presentation II', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 592', 'Project', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'second', 4, '', '[]'::jsonb, 'Department official website', false),
  ('GSV 542', 'Marine Survey', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('PHY 472', 'Agronomy', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false),
  ('BF 312', 'Banking Laws and Regulation', 'University of Nigeria, Nsukka', 'Faculty of Environmental Studies', 'Geoinformatics and Surveying', '500 Level', 'second', 2, '', '[]'::jsonb, 'Department official website', false);
