-- =============================================================================
-- University of Nigeria, Nsukka - Faculty of Physical Sciences
-- Pure and Industrial Chemistry
-- Course outlines transcribed from the departmental course handbook.
-- =============================================================================
-- Run in the Supabase SQL Editor. Safe to run more than once: existing rows
-- for these courses are removed first, so it updates rather than duplicates.
--
-- NOTE ON SEMESTERS: the handbook does not state which semester each course
-- runs in. The values below follow the usual Nigerian convention that an odd
-- final digit is first semester and an even one is second. Correct any that
-- differ at UNN by editing the semester column in the Table Editor.
--
-- NOTE ON DUAL CODES: the handbook lists two courses under a pair of codes
-- (CHM 403 / CHM 423 and CHM 422 / CHM 424). Each is stored once under the
-- first code, with the alternative noted in its description. CHM 482 / 483
-- are Colour Chemistry I and II and are stored as two separate courses; the
-- handbook gives them a shared description.
--
-- This file also carries the required ancillary, general-studies and elective
-- courses a Pure and Industrial Chemistry student actually sits each semester, scoped to
-- this department so they appear on the student's own timetable — independent
-- rows from any same-code row filed under its own home department.
-- Source for the programme structure: UNN's published Pure and Industrial Chemistry Undergraduate Programme PDF
-- Descriptions are reused, unedited, from this app's sibling UNN outline files
-- wherever the course code already exists there; courses with no verified
-- description anywhere (GSP, COS, BIO, ECO, engineering and language codes)
-- carry code/title/units/level/semester only, rather than an invented syllabus.
-- Electives are flagged by an "Elective." prefix on the description, since this
-- file's column list predates the is_elective column.
-- Only the Four-Year Standard Programme is followed, not the Three-Year
-- direct-entry or combined-honours variants.
-- =============================================================================

delete from public.course_outlines
 where institution = 'University of Nigeria, Nsukka'
   and department = 'Pure and Industrial Chemistry';

insert into public.course_outlines
  (course_code, course_title, institution, faculty, department, level,
   semester, credit_units, description, topics, contributor_name)
values
  ('CHM 101', 'Basic Principles I of Inorganic Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '100 Level', 'first', 2, 'Stoichiometry and Atomic Structure: Stoichiometry and mole concept. Introduction to atomic structure, development of electronic configuration of the elements, and valency theories. Periodic Table and Groups: The periodic classification of elements. Brief group study of representative elements, with emphasis on similarities and differences based on periodic position. Nuclear Chemistry: Radioactivity and its practical applications.', '["Stoichiometry and Atomic Structure: Stoichiometry and mole concept. Introduction to atomic structure, development of electronic configuration of the elements, and valency theories", "Periodic Table and Groups: The periodic classification of elements. Brief group study of representative elements, with emphasis on similarities and differences based on periodic position", "Nuclear Chemistry: Radioactivity and its practical applications"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 112', 'Basic Principles of Physical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '100 Level', 'second', 2, 'Gas Laws and Kinetic Theory: Kinetic theory of gases, elementary derivation and deduction of gas laws, molecular speeds, deviations from ideal behaviour, van der Waals modification, and gas liquefaction. Phase Equilibrium and Solutions: Phase transitions and phase equilibria in one-component systems. Ideal solutions, Raoult''s law, Henry''s law, real solutions, and colligative properties -- vapour pressure lowering, boiling point elevation, freezing point lowering, osmotic pressure. Thermodynamics and Kinetics: Aspects of the first law of thermodynamics, thermochemistry, entropy, free energy, and spontaneous changes. Ionic equilibria, acids, bases, indicators, and buffers. Elementary chemical kinetics, factors affecting reaction rates, rate laws, order and molecularity, zero and first order reactions, Arrhenius equation, and collision and transition state theories.', '["Gas Laws and Kinetic Theory: Kinetic theory of gases, elementary derivation and deduction of gas laws, molecular speeds, deviations from ideal behaviour, van der Waals modification, and gas liquefaction", "Phase Equilibrium and Solutions: Phase transitions and phase equilibria in one-component systems. Ideal solutions, Raoult''s law, Henry''s law, real solutions, and colligative properties -- vapour pressure lowering, boiling point elevation, freezing point lowering, osmotic pressure", "Thermodynamics and Kinetics: Aspects of the first law of thermodynamics, thermochemistry, entropy, free energy, and spontaneous changes. Ionic equilibria, acids, bases, indicators, and buffers. Elementary chemical kinetics, factors affecting reaction rates, rate laws, order and molecularity, zero and first order reactions, Arrhenius equation, and collision and transition state theories"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 122', 'Basic Principles of Organic Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '100 Level', 'second', 2, 'Structure and Classification: Historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, homologous series, elemental analysis, molecular formulas, and structural isomerism. Bonding and Reactivity: Isolation and purification methods, functional group concepts, resonance, and aromaticity. Electronic theory in organic chemistry. Functional Groups: Brief study of saturated and unsaturated hydrocarbons, cyclic hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, and aromatic compounds. Comparison of phenols and aryl halides. Stereochemistry and Lipids: Introduction to oils, fats, and stereoisomerism.', '["Structure and Classification: Historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, homologous series, elemental analysis, molecular formulas, and structural isomerism", "Bonding and Reactivity: Isolation and purification methods, functional group concepts, resonance, and aromaticity. Electronic theory in organic chemistry", "Functional Groups: Brief study of saturated and unsaturated hydrocarbons, cyclic hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, and aromatic compounds. Comparison of phenols and aryl halides", "Stereochemistry and Lipids: Introduction to oils, fats, and stereoisomerism"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 152', 'Introduction to Industrial Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '100 Level', 'second', 2, 'Chemical Process Industry: Major characteristics and scale of operations in the chemical process industry, major sectors, producing countries, and processing raw materials into end products. Calculations and Energy: Stoichiometry, material and energy balance fundamentals, energy sources, types, and utilization. Environment: Environmental pollution profiles and control strategies for major chemical industries.', '["Chemical Process Industry: Major characteristics and scale of operations in the chemical process industry, major sectors, producing countries, and processing raw materials into end products", "Calculations and Energy: Stoichiometry, material and energy balance fundamentals, energy sources, types, and utilization", "Environment: Environmental pollution profiles and control strategies for major chemical industries"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 171', 'Basic Practical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '100 Level', 'first', 2, 'Laboratory Operations: Theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations.', '["Laboratory Operations: Theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 201', 'General Inorganic Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '200 Level', 'first', 2, 'Periodic Trends: Ionization potential, electron affinity, and electronegativity. Chemical Bonding: Electrostatic and non-electrostatic valence forces, non-valence cohesive forces. Coordination Compounds: Introduction to complexes, focusing on colour, magnetic properties, and practical applications.

Prerequisite: CHM 101, or a pass in Chemistry at H.S.C. / G.C.E. A-Level', '["Periodic Trends: Ionization potential, electron affinity, and electronegativity", "Chemical Bonding: Electrostatic and non-electrostatic valence forces, non-valence cohesive forces", "Coordination Compounds: Introduction to complexes, focusing on colour, magnetic properties, and practical applications"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 211', 'General Physical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '200 Level', 'first', 2, 'Gases and Thermodynamics: Molecular collisions in gases, virial equation, critical phenomena, and reduced properties. Chemical thermodynamics, detailed treatment of the first law of thermodynamics, and the Carnot cycle. Chemical Kinetics: Integrated rate equations for second and third order reactions, reaction mechanisms, rate laws, and the effect of temperature on reaction rates.

Prerequisite: CHM 112', '["Gases and Thermodynamics: Molecular collisions in gases, virial equation, critical phenomena, and reduced properties. Chemical thermodynamics, detailed treatment of the first law of thermodynamics, and the Carnot cycle", "Chemical Kinetics: Integrated rate equations for second and third order reactions, reaction mechanisms, rate laws, and the effect of temperature on reaction rates"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 324', 'Organic Chemistry III', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'second', 2, 'Polyfunctional Compounds: Study of polyfunctional organic compounds selected from dicarboxylic acids, dicarbonyl compounds, keto- and hydroxy-acids, and $\alpha,\beta$-unsaturated carbonyl compounds, including addition reactions. Biomolecules and Heterocycles: Amino acids and proteins. Heterocyclic compounds containing one heteroatom.

Prerequisite: CHM 221 and CHM 222', '["Polyfunctional Compounds: Study of polyfunctional organic compounds selected from dicarboxylic acids, dicarbonyl compounds, keto- and hydroxy-acids, and $\\alpha,\\beta$-unsaturated carbonyl compounds, including addition reactions", "Biomolecules and Heterocycles: Amino acids and proteins. Heterocyclic compounds containing one heteroatom"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 352', 'Chemical Process Technology I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'second', 2, 'Process Flow and Fluid Transport: Calculations, block diagrams, flowsheets, material and energy balances for industrial processes, process selection, and development studies. Pressure loss in pipes, fluid transport and measurement, pumps, compressors, and agitation. Heat Transfer and Operations: Heat transfer via conduction, convection, and radiation; heat exchanger types. Operations including humidification, drying, and single and multiple-effect evaporation.

Prerequisite: CHM 251', '["Process Flow and Fluid Transport: Calculations, block diagrams, flowsheets, material and energy balances for industrial processes, process selection, and development studies. Pressure loss in pipes, fluid transport and measurement, pumps, compressors, and agitation", "Heat Transfer and Operations: Heat transfer via conduction, convection, and radiation; heat exchanger types. Operations including humidification, drying, and single and multiple-effect evaporation"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 371', 'Practical Inorganic Chemistry II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'first', 2, 'Analytical Methods: Quantitative analysis of ores, alloys, and other materials using ion-exchange chromatography and solvent extraction. Coordination Complexes: Characteristics of complexes formed between transition metals and organic ligands.', '["Analytical Methods: Quantitative analysis of ores, alloys, and other materials using ion-exchange chromatography and solvent extraction", "Coordination Complexes: Characteristics of complexes formed between transition metals and organic ligands"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 372', 'Practical Physical Chemistry II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'second', 2, 'Experiments: Selected experiments in electrochemistry, reaction kinetics, phase equilibria, calorimetry, colorimetry, potentiometry, refractive index measurements, and molecular refractivity. Materials and Heat Transfer: Adsorption studies on activated carbons, heat transfer coefficients in condensers, batch sedimentation, and sieve analysis.', '["Experiments: Selected experiments in electrochemistry, reaction kinetics, phase equilibria, calorimetry, colorimetry, potentiometry, refractive index measurements, and molecular refractivity", "Materials and Heat Transfer: Adsorption studies on activated carbons, heat transfer coefficients in condensers, batch sedimentation, and sieve analysis"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 373', 'Practical Organic Chemistry II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'first', 2, 'Synthesis and Analysis: Multistage organic synthesis, qualitative and quantitative analysis of organic mixtures and compounds.', '["Synthesis and Analysis: Multistage organic synthesis, qualitative and quantitative analysis of organic mixtures and compounds"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 374', 'Applied Spectroscopy', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'second', 2, 'Instrumentation and Theory: Introduction to principles and practical operations of Infrared (IR), Ultraviolet-Visible (UV-Vis), Nuclear Magnetic Resonance (NMR), and Mass Spectrometry (MS).', '["Instrumentation and Theory: Introduction to principles and practical operations of Infrared (IR), Ultraviolet-Visible (UV-Vis), Nuclear Magnetic Resonance (NMR), and Mass Spectrometry (MS)"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 381', 'Chemical Industry and the Environment', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'first', 2, 'Pollution and Waste: Elementary atmospheric cycles, pollution source types, domestic waste composition, waste disposal, and resource recovery from waste materials. Industrial Impact and Safety: Manufacturing by-product pollution, environmental impact of chemical products such as DDT, detergents, plastics and antibiotics, water treatment chemistry and analysis, detection and monitoring of toxic agents using instrumentation, and chemical industry safety protocols.', '["Pollution and Waste: Elementary atmospheric cycles, pollution source types, domestic waste composition, waste disposal, and resource recovery from waste materials", "Industrial Impact and Safety: Manufacturing by-product pollution, environmental impact of chemical products such as DDT, detergents, plastics and antibiotics, water treatment chemistry and analysis, detection and monitoring of toxic agents using instrumentation, and chemical industry safety protocols"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 382', 'Polymer Chemistry I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'second', 2, 'Polymer Fundamentals: Classification of polymers, addition and condensation polymerization reactions, and polymerization practice. Molecular weight distribution and measurement methods. Properties and Structure: Bonding in polymers, solution properties, bulk properties of amorphous and crystalline polymers, rheology, mechanical, thermal, electrical, chemical, and optical properties. Structure-property relationships, survey of important commercial polymers, and polymer testing methods.', '["Polymer Fundamentals: Classification of polymers, addition and condensation polymerization reactions, and polymerization practice. Molecular weight distribution and measurement methods", "Properties and Structure: Bonding in polymers, solution properties, bulk properties of amorphous and crystalline polymers, rheology, mechanical, thermal, electrical, chemical, and optical properties. Structure-property relationships, survey of important commercial polymers, and polymer testing methods"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 401', 'Advanced Inorganic Chemistry I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Organometallics: Organometallic compounds -- preparation, properties, and applications of organometallic compounds of alkali, alkali earth, and non-benzenoid metal complexes.

Prerequisite: CHM 301 and CHM 302', '["Organometallics: Organometallic compounds -- preparation, properties, and applications of organometallic compounds of alkali, alkali earth, and non-benzenoid metal complexes"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 402', 'Advanced Inorganic Chemistry II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'second', 2, 'Coordination Chemistry: Coordination chemistry, bonding theories, electronic spectra, magnetic properties, isomerism, formation and stability constants of transition metal complexes, and complexation kinetics and mechanisms. Inorganic Families: Metal carbonyls -- preparation, reactions, structure, bonding; carboxylate ions, carbonyl hydrides, halides, lanthanides, actinides, and boron hydrides. Non-Aqueous Solvents: Non-aqueous solvents, solvent classification, solute-solvent interactions, oxyhalide solvents, protonic solvents, liquid halides, and fused salts.

Prerequisite: CHM 301 and CHM 302', '["Coordination Chemistry: Coordination chemistry, bonding theories, electronic spectra, magnetic properties, isomerism, formation and stability constants of transition metal complexes, and complexation kinetics and mechanisms", "Inorganic Families: Metal carbonyls -- preparation, reactions, structure, bonding; carboxylate ions, carbonyl hydrides, halides, lanthanides, actinides, and boron hydrides", "Non-Aqueous Solvents: Non-aqueous solvents, solvent classification, solute-solvent interactions, oxyhalide solvents, protonic solvents, liquid halides, and fused salts"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 403', 'Modern Synthetic Methods in Organic Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Synthetic Reactions: Comprehensive study of modern organic synthesis applications -- reduction, oxidation, halogenation, alkylation, acylation of active methylene compounds, and alkylation of aromatic systems. Named Reactions: Michael, Claisen-Schmidt, Knoevenagel, Mannich, Perkin, Stobbe, Darzens, and Wittig reactions. Synthesis of organometallic compounds. Note: also listed in the handbook as CHM 423.

Prerequisite: CHM 321 and CHM 322', '["Synthetic Reactions: Comprehensive study of modern organic synthesis applications -- reduction, oxidation, halogenation, alkylation, acylation of active methylene compounds, and alkylation of aromatic systems", "Named Reactions: Michael, Claisen-Schmidt, Knoevenagel, Mannich, Perkin, Stobbe, Darzens, and Wittig reactions. Synthesis of organometallic compounds", "Note: also listed in the handbook as CHM 423"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 411', 'Advanced Physical Chemistry I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Statistical Thermodynamics: Microstates, randomness, Boltzmann statistics, partition functions, and relationships to thermodynamic quantities $E$, $H$, $G$ and $S$. Heat capacity of gases, liquids, and solids; calculation of equilibrium constants. Introduction to Fermi-Dirac and Bose-Einstein statistics. Electrochemistry: Detailed treatment of Debye-Huckel theory and the Debye-Huckel-Onsager equation.

Prerequisite: CHM 311', '["Statistical Thermodynamics: Microstates, randomness, Boltzmann statistics, partition functions, and relationships to thermodynamic quantities $E$, $H$, $G$ and $S$. Heat capacity of gases, liquids, and solids; calculation of equilibrium constants. Introduction to Fermi-Dirac and Bose-Einstein statistics", "Electrochemistry: Detailed treatment of Debye-Huckel theory and the Debye-Huckel-Onsager equation"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 412', 'Advanced Physical Chemistry II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'second', 2, 'Quantum Mechanics and Spectroscopy: Approximation methods, self-consistent field theory of many-electron atoms, hybridization theory of resonance, quantum mechanics of molecules -- the $\mathrm{H_2^+}$ ion. Molecular Orbital and Valence Bond theories. Light Interaction: Light-matter interactions, frequency, shape, and intensity of absorption bands across microwave, UV-Visible, and Raman spectroscopy. Chemical Kinetics: Theories of reaction rates -- collision theory and absolute reaction rate theory.

Prerequisite: CHM 312', '["Quantum Mechanics and Spectroscopy: Approximation methods, self-consistent field theory of many-electron atoms, hybridization theory of resonance, quantum mechanics of molecules -- the $\\mathrm{H_2^+}$ ion. Molecular Orbital and Valence Bond theories", "Light Interaction: Light-matter interactions, frequency, shape, and intensity of absorption bands across microwave, UV-Visible, and Raman spectroscopy", "Chemical Kinetics: Theories of reaction rates -- collision theory and absolute reaction rate theory"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 421', 'Advanced Organic Chemistry I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Stereochemistry and Mechanisms: Stereochemistry of cyclic compounds, allenes, and spiranes; optical activity of diphenyls; conformational analysis. Neighbouring Group Participation (NGP), reactions in acyclic, cyclic and fused systems, molecular rearrangements, and reactive intermediates -- carbenes, nitrenes, benzynes. Spectroscopic Identification: Application of UV, IR, NMR, and Mass spectra in structural elucidation.

Prerequisite: CHM 321 and CHM 322', '["Stereochemistry and Mechanisms: Stereochemistry of cyclic compounds, allenes, and spiranes; optical activity of diphenyls; conformational analysis. Neighbouring Group Participation (NGP), reactions in acyclic, cyclic and fused systems, molecular rearrangements, and reactive intermediates -- carbenes, nitrenes, benzynes", "Spectroscopic Identification: Application of UV, IR, NMR, and Mass spectra in structural elucidation"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 422', 'Chemistry of Natural Products', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'second', 2, 'Natural Products Chemistry: General methods of isolation, purification, structural determination, and synthesis of terpenoids, steroids, alkaloids, lipids, antibiotics, flavonoids, prostaglandins, and chlorophyll. Heterocycles and Applications: Heterocyclic compounds with multiple heteroatoms, natural products of pharmaceutical importance, natural dyes, vitamins, and drugs. Note: also listed in the handbook as CHM 424.

Prerequisite: CHM 321 and CHM 322', '["Natural Products Chemistry: General methods of isolation, purification, structural determination, and synthesis of terpenoids, steroids, alkaloids, lipids, antibiotics, flavonoids, prostaglandins, and chlorophyll", "Heterocycles and Applications: Heterocyclic compounds with multiple heteroatoms, natural products of pharmaceutical importance, natural dyes, vitamins, and drugs", "Note: also listed in the handbook as CHM 424"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 431', 'Modern Analytic Techniques', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Spectrophotometry: Principles and applications of colorimetry, spectrophotometry, and the Beer-Lambert law for multicomponent solution mixtures. Analytical Instrumentation: Fluorescence methods, chromatographic theory and techniques, and flame methods -- Atomic Absorption Spectrometry and Flame Photometry.

Prerequisite: CHM 231', '["Spectrophotometry: Principles and applications of colorimetry, spectrophotometry, and the Beer-Lambert law for multicomponent solution mixtures", "Analytical Instrumentation: Fluorescence methods, chromatographic theory and techniques, and flame methods -- Atomic Absorption Spectrometry and Flame Photometry"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 451', 'Chemical Process Technique II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Reactor Design: Chemical reaction theory, main reactor types and application fields, batch reactor data interpretation, single ideal reactor design, and multiple reaction design. Operational Variables: Temperature and pressure effects, heterogeneous reactors, fluidized bed reactors, reactor selection, similarity principles, scale-up methods, solid diffusion, and interphase mass transfer.

Prerequisite: CHM 351', '["Reactor Design: Chemical reaction theory, main reactor types and application fields, batch reactor data interpretation, single ideal reactor design, and multiple reaction design", "Operational Variables: Temperature and pressure effects, heterogeneous reactors, fluidized bed reactors, reactor selection, similarity principles, scale-up methods, solid diffusion, and interphase mass transfer"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 452', 'Chemical Process Technology III', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'second', 2, 'Unit Operations: Fluid transportation, size reduction, mixing, filtration, centrifugation, gas absorption, distillation, adsorption, ion-exchange, leaching, and liquid-liquid extraction. Process Dynamics: Objectives of process control loops, measuring devices, controllers, final control elements, computer network analysis, and process optimization.

Prerequisite: CHM 352', '["Unit Operations: Fluid transportation, size reduction, mixing, filtration, centrifugation, gas absorption, distillation, adsorption, ion-exchange, leaching, and liquid-liquid extraction", "Process Dynamics: Objectives of process control loops, measuring devices, controllers, final control elements, computer network analysis, and process optimization"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 454', 'Polymer Chemistry and Technology', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'second', 2, 'Compounding and Processing: Role of plasticizers, fillers, colorants, photo and heat stabilizers, and flame retardants. Polymer fabrication -- injection, extrusion, compression, and transfer molding; processing effects on structure and performance. Coatings and Paints: Paint technology -- paint types, formulation, manufacture, testing, components such as binders, pigments, solvents and additives, substrates, application methods, durability, film defects, and remedies.

Prerequisite: CHM 382', '["Compounding and Processing: Role of plasticizers, fillers, colorants, photo and heat stabilizers, and flame retardants. Polymer fabrication -- injection, extrusion, compression, and transfer molding; processing effects on structure and performance", "Coatings and Paints: Paint technology -- paint types, formulation, manufacture, testing, components such as binders, pigments, solvents and additives, substrates, application methods, durability, film defects, and remedies"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 461', 'Seminar', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Presentation of a paper on an approved topic at a departmental colloquium. Assessed on student presentation and understanding of underlying chemical principles.', '["Presentation of a paper on an approved topic at a departmental colloquium", "Assessed on student presentation and understanding of underlying chemical principles"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 481', 'Chemistry of Petroleum and Coal Products', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Fossil Fuels: Origin, composition, and classification of coal, petroleum, and natural gas. Coal carbonization, liquefaction, gasification, and chemical by-products. Refining: Petroleum refining, natural gas processing, and petrochemical raw materials.

Prerequisite: CHM 381', '["Fossil Fuels: Origin, composition, and classification of coal, petroleum, and natural gas. Coal carbonization, liquefaction, gasification, and chemical by-products", "Refining: Petroleum refining, natural gas processing, and petrochemical raw materials"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 482', 'Colour Chemistry and Technology I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'second', 2, 'Dyes and Pigments: Relationship between colour and chemical structure, colour measurement, chemistry, classification and manufacture of dyes and pigments. Dyeing and Applications: Dyeing natural and synthetic fibres, reactive dyes, local dye extraction, food, drug and cosmetic colorants, photography dyes, paper dyes, fastness properties, photometric quality control, and coloration industry operations.', '["Dyes and Pigments: Relationship between colour and chemical structure, colour measurement, chemistry, classification and manufacture of dyes and pigments", "Dyeing and Applications: Dyeing natural and synthetic fibres, reactive dyes, local dye extraction, food, drug and cosmetic colorants, photography dyes, paper dyes, fastness properties, photometric quality control, and coloration industry operations"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 483', 'Colour Chemistry and Technology II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Dyes and Pigments: Relationship between colour and chemical structure, colour measurement, chemistry, classification and manufacture of dyes and pigments. Dyeing and Applications: Dyeing natural and synthetic fibres, reactive dyes, local dye extraction, food, drug and cosmetic colorants, photography dyes, paper dyes, fastness properties, photometric quality control, and coloration industry operations.

Prerequisite: CHM 482', '["Dyes and Pigments: Relationship between colour and chemical structure, colour measurement, chemistry, classification and manufacture of dyes and pigments", "Dyeing and Applications: Dyeing natural and synthetic fibres, reactive dyes, local dye extraction, food, drug and cosmetic colorants, photography dyes, paper dyes, fastness properties, photometric quality control, and coloration industry operations"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 484', 'Extraction and Physical Metallurgy', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'second', 2, 'Ores, ore dressing, agglomeration, thermodynamic principles of extraction processes, extraction procedures, metallic liquids, solidification, and phase diagrams.', '["Ores, ore dressing, agglomeration, thermodynamic principles of extraction processes, extraction procedures, metallic liquids, solidification, and phase diagrams"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 485', 'Cement and Fertilizer Industries', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Cement: Types of cement, cement chemistry, raw materials, and manufacturing processes. Fertilizers: Types of fertilizers, raw materials, and production methods.', '["Cement: Types of cement, cement chemistry, raw materials, and manufacturing processes", "Fertilizers: Types of fertilizers, raw materials, and production methods"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 486', 'Pulp and Paper Industries', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'second', 2, 'Physical and chemical properties of wood, wood preparation for pulping, mechanical and chemical pulping processes, bleaching, paper additives, beating and refining, and paper-making operations.', '["Physical and chemical properties of wood, wood preparation for pulping, mechanical and chemical pulping processes, bleaching, paper additives, beating and refining, and paper-making operations"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 487', 'Pharmaceutical Industry', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Synthesis of drugs, drug design, Structure-Activity Relationships (SAR), quality control, and local sourcing of raw materials for drugs and cosmetics.', '["Synthesis of drugs, drug design, Structure-Activity Relationships (SAR), quality control, and local sourcing of raw materials for drugs and cosmetics"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 488', 'Sugar and Fermentation Industries', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'second', 2, 'Manufacture of cane and beet sugar, utilization of sugar by-products for alcohol production, mechanisms of alcohol fermentation from carbohydrates and saccharine materials, and related products.', '["Manufacture of cane and beet sugar, utilization of sugar by-products for alcohol production, mechanisms of alcohol fermentation from carbohydrates and saccharine materials, and related products"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 489', 'Oils, Fats, Detergents and Chloroalkali Industries', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Oils and Fats: Sources, physical and chemical properties, extraction, purification, and hydrogenation. Soaps and Detergents: Manufacture of soaps and synthetic detergents. Chloro-Alkali Industry: Industrial production of chlorine, sodium hydroxide, sodium carbonate, and potassium hydroxide, along with their industrial uses.', '["Oils and Fats: Sources, physical and chemical properties, extraction, purification, and hydrogenation", "Soaps and Detergents: Manufacture of soaps and synthetic detergents", "Chloro-Alkali Industry: Industrial production of chlorine, sodium hydroxide, sodium carbonate, and potassium hydroxide, along with their industrial uses"]'::jsonb, 'Department of Chemistry handbook'),
  ('CHM 492', 'Research Project', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'second', 6, 'Supervised original laboratory research work on an approved topic, culminating in a written project report.', '["Supervised original laboratory research work on an approved topic, culminating in a written project report"]'::jsonb, 'Department of Chemistry handbook'),
  ('BIO 151', 'General Biology I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '100 Level', 'first', 3, 'Elective.', '[]'::jsonb, 'Department of Computer Science course outline'),
  ('MTH 111', 'Elementary Mathematics I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '100 Level', 'first', 3, 'Elementary Set theory, subsets, union, intersection, complements. Venn diagrams, Real numbers, integers, rational and irrational numbers, mathematical induction, real sequences and series, theory of quadratic equations, binomial theorem. Circular measure, trigonometric functions of angles of any magnitude, addition and factor formulae. Complex numbers, algebra of complex numbers, the Argand Diagram, De Moivre''s theorem, $n$th roots of unity.', '["Elementary Set theory, subsets, union, intersection, complements", "Venn diagrams, Real numbers, integers, rational and irrational numbers, mathematical induction, real sequences and series, theory of quadratic equations, binomial theorem", "Circular measure, trigonometric functions of angles of any magnitude, addition and factor formulae", "Complex numbers, algebra of complex numbers, the Argand Diagram, De Moivre''s theorem, $n$th roots of unity"]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('MTH 121', 'Elementary Mathematics II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '100 Level', 'first', 3, 'Functions of a real variable, graphs, limits and continuity. The derivative as limit of rate of change. Techniques of differentiation. Curve sketching, integration as an inverse of differentiation. Methods of integration, definite integrals. Application of integration to areas and volumes.', '["Functions of a real variable, graphs, limits and continuity", "The derivative as limit of rate of change", "Techniques of differentiation", "Curve sketching, integration as an inverse of differentiation", "Methods of integration, definite integrals", "Application of integration to areas and volumes"]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('PHY 115', 'General Physics for Physical Sciences I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '100 Level', 'first', 2, 'Units and dimensions. Elements of vector algebra. Kinematics, linear and circular motion. Laws of mechanics and gravitation, simple applications, motion of planets. Conservation laws, energy, momentum; work and power. Rigid bodies, moment of inertia. Angular momentum. Simple harmonic motion, simple and compound pendulums, damped and forced vibrations. Elasticity, moduli of elasticity, bending moments, fluid mechanics.', '["Units and dimensions", "Elements of vector algebra", "Kinematics, linear and circular motion", "Laws of mechanics and gravitation, simple applications, motion of planets", "Conservation laws, energy, momentum", "Work and power", "Rigid bodies, moment of inertia", "Angular momentum", "Simple harmonic motion, simple and compound pendulums, damped and forced vibrations", "Elasticity, moduli of elasticity, bending moments, fluid mechanics"]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('PHY 191', 'Practical Physics I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '100 Level', 'first', 2, 'Selected experiments from the 100-Level courses in Physics for service courses.', '["Selected experiments from the 100-Level courses in Physics for service courses"]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('GSP 101', 'Communication in English I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '100 Level', 'first', 2, 'Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, The English Language and the Nigerian society, World English, Levels and Varieties of English — formal, informal, standard, etc., English in Literature and the Media.

Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes, English Language Register, diatypes and dialects.

Listening skill - The listening skill discussed as a receptive and reciprocal activity, Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening.

Reading Skill - The concept of reading as a linguistic organization and a vehicle of communication. Reading Problems, Levels of Reading, Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies (Scanning, Skimming, Phrase reading, Intensive & Extensive reading, Exploiting the topic sentence for main ideas), Reading for details, Reading for evaluation and inference, Reading with questions - SQ3R, PR3, Methods for understanding difficult words in a reading text, Literature reading for study, analysis and comment.

Speaking & Communication Skills - Nature, Process & Development, Principles of Public Speech Making and Social Interaction, The Speech Sounds of English and their Articulation, Phonetic Transcription and Practical Speech Work.

Study Techniques - Choosing study centers and discussion groups, Note-taking during lectures, and from audio-visual equipment, Note-making techniques during private reading and literature search, Summary & Transcoding Techniques, Retrieving information from notes, The dictionary as a study guide.

Basic Research Methods & Term Paper Writing - Research – meaning & nature, Types & Methodology; Data in the Research Process, The Research Report, Process and Techniques, Documentation in Research Reports: Process, Types and Methods, Abbreviations in Research Reports, The term paper as a miniature research report, Practical term paper writing.

Course Evaluation & Grading - Students must attend at least 75% of the lectures to qualify for examination in the course.', '["Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, World English, Levels and Varieties of English", "Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes", "Listening skill - Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening", "Reading Skill - Reading Problems, Levels and Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies, Reading for evaluation and inference", "Speaking & Communication Skills - Principles of Public Speech Making and Social Interaction, Phonetic Transcription and Practical Speech Work", "Study Techniques - Note-taking, Note-making, Summary & Transcoding Techniques", "Basic Research Methods & Term Paper Writing - The Research Report, Documentation, Abbreviations, practical term paper writing"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('GSP 111', 'The Use of Library and Study Skills', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '100 Level', 'first', 2, 'Overview of Library: concepts, history, types and functions. Uses in academic libraries; organization of university library and library users. Library processes and procedures. Acquisition process, Cataloging and classification, LC Scheme, in-House Scheme, DDC. Serials process and circulation processes. Access tools in Library resources: Library catalogues, Indexes, Abstracts, Current contents information in the library. Reference sources: types of reference sources and services. Web resources and online resources. Overview of Databases, Online search strategies for information retrieval. Referencing and citation styles for information reporting. Concept of plagiarism. Learning skills and research skills, ICT skillsets: types of learning and information policies.', '["Overview of Library: concepts, history, types and functions. Uses in academic libraries; organization of university library and library users", "Library processes and procedures. Acquisition process, Cataloging and classification, LC Scheme, in-House Scheme, DDC. Serials process and circulation processes", "Access tools in Library resources: Library catalogues, Indexes, Abstracts, Current contents information", "Reference sources: types of reference sources and services. Web resources and online resources", "Overview of Databases, Online search strategies for information retrieval. Referencing and citation styles for information reporting. Concept of plagiarism", "Learning skills and research skills, ICT skillsets: types of learning and information policies"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('BIO 152', 'General Biology II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '100 Level', 'second', 3, 'Elective.', '[]'::jsonb, 'Department of Statistics undergraduate course module'),
  ('PHY 118', 'General Physics for Physical Sciences III', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '100 Level', 'second', 2, 'Electrostatics; Coulomb''s law, electric field, Gauss''s law, electrostatic potential, fields due to simple charge distributions. Energy in electric fields, capacitance. Dielectrics, polarization. Electric current, Ohm''s law. Elements of circuit theory. Thermoelectric effect. Magnetic effects of current. Ampere''s law, fields due to simple circuits. Permanent magnetism, Earth''s magnetic field; ferromagnetism, moving coil instruments. Faraday''s law of induction; generators, electric motors. Alternating current. Maxwell''s equations. Elements of atomic and nuclear physics.', '["Electrostatics", "Coulomb''s law, electric field, Gauss''s law, electrostatic potential, fields due to simple charge distributions", "Energy in electric fields, capacitance", "Dielectrics, polarization", "Electric current, Ohm''s law", "Elements of circuit theory", "Thermoelectric effect", "Magnetic effects of current", "Ampere''s law, fields due to simple circuits", "Permanent magnetism, Earth''s magnetic field", "Ferromagnetism, moving coil instruments", "Faraday''s law of induction", "Generators, electric motors", "Alternating current", "Maxwell''s equations", "Elements of atomic and nuclear physics"]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('GSP 102', 'Communication in English II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '100 Level', 'second', 2, 'Part A: Basic Grammar: Introduction. The concept of grammar and its place in language teaching and learning. Parts of speech and their functions (treated in detail). Closed and open class items in parts of speech, Nominalization, Grammatical Structures: the phrase, the clause and the sentence. Elementary Clause Analysis, Sentence Types, Elements and Patterns. Agreement (Grammatical agreement, Notional agreement, Proximity agreement) Agreement with the correlatives. Direct and Reported Speech, Error typology identification and correction.

Part B: Varieties of writing. Introduction (The Meaning, Nature and Purpose of Writing, Writing Types or Genres and their Characteristics). The paragraph as the basic unit of an essay (Types, Development of the Paragraph, Methods of Paragraph Development, The thesis statement). Point of view and style in writing. Qualities of a good piece of writing: Form, Diction and Content in writing. The Mechanics of Writing: punctuation, spelling and capitalization.

Part C: Writing Genres - Planning and choosing your theme. Deciding your genre. Choosing and developing your plot. Point of view, setting and characterization. Using the language that works. Essay Writing — Narration, Description, Exposition and Argumentation. Technical Writing: Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes, own story for practice, Computer-linked writing, types, style, language, and process.', '["Part A: Basic Grammar - The concept of grammar, Parts of speech, Grammatical Structures, Sentence Types, Agreement, Direct and Reported Speech, Error typology", "Part B: Varieties of writing - Meaning, Nature and Purpose of Writing, the paragraph as the basic unit of an essay, the thesis statement, Qualities of a good piece of writing, Mechanics of Writing", "Part C: Writing Genres - Planning and choosing your theme, plot, point of view, setting and characterization", "Essay Writing - Narration, Description, Exposition and Argumentation", "Technical Writing - Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('ECO 102', 'Basic Principles of Economics II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '100 Level', 'second', 2, 'Elementary principles of macroeconomics and microeconomics; National income determination; The circular flow of income; Injections, withdrawals and the multiplier; Income determination; consumption, saving and investment functions; Nature and features of money; The banking system and the supply of money; Money supply and price level; International trade; Exchange rate and comparative advantage; Foreign trade and domestic economy; Economic growth; Elementary notion of economic planning; Introduction to Marxist economic theory.', '["Elementary principles of macroeconomics and microeconomics", "National income determination", "The circular flow of income; Injections, withdrawals and the multiplier", "Income determination; consumption, saving and investment functions", "Nature and features of money", "The banking system and the supply of money", "Money supply and price level", "International trade; Exchange rate and comparative advantage", "Foreign trade and domestic economy", "Economic growth", "Elementary notion of economic planning", "Introduction to Marxist economic theory"]'::jsonb, 'Department of Economics handbook'),
  ('MTH 207', 'Advanced Mathematics VII', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '200 Level', 'first', 2, 'Elements of linear algebra. Calculus: Elementary differentiation and relevant theorems. Differential equations: Exact equations, methods of solution of second-order ordinary differential equations, partial differential equations, with applications.', '["Elements of linear algebra", "Calculus: Elementary differentiation and relevant theorems", "Differential equations: Exact equations, methods of solution of second-order ordinary differential equations, partial differential equations, with applications"]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('PHY 251', 'Electromagnetism', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '200 Level', 'first', 2, 'Electrostatics. Gauss'' Law. Fields of charge distribution, methods of images. Dielectrics, Polarization. Electric current, current density. D.C. network theory. Ampere''s Law, magnetic fields of simple circuits. Faraday''s law of induction, self and mutual inductances, inductively coupled circuits. Transients in capacitive and inductive circuits. A.C. circuit analysis. Magnetization and hysteresis. Permanent magnetism - Diamagnetism, Paramagnetism and ferromagnetism. Lorentz force. Hall Effect. Maxwell''s equation - electromagnetic waves.

Prerequisite: PHY 118 or PHY 124', '["Electrostatics", "Gauss'' Law", "Fields of charge distribution, methods of images", "Dielectrics, Polarization", "Electric current, current density", "D.C", "Network theory", "Ampere''s Law, magnetic fields of simple circuits", "Faraday''s law of induction, self and mutual inductances, inductively coupled circuits", "Transients in capacitive and inductive circuits", "A.C", "Circuit analysis", "Magnetization and hysteresis", "Permanent magnetism - Diamagnetism, Paramagnetism and ferromagnetism", "Lorentz force", "Hall Effect", "Maxwell''s equation - electromagnetic waves"]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('COS 101', 'Introduction to Computer Science', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '200 Level', 'first', 2, 'Concepts of hardware and software; basic subsystems of a digital computer; characteristics of a digital computer; devices/media; types/classes of computer emphasising the PC; history of computers and their generations. Problem-solving: algorithm, flowchart, pseudocode, program/data, running a program. Programming: introduction to Java/BASIC programming language syntax and programming. Booting and shutdown; types of operating system; user interface; managing information, computer malware (virus, etc); computer network; internet and web usage, e-mail, instant messaging, etc. Office applications; use of a statistical package and a database management system.', '["Concepts of hardware and software","basic subsystems of a digital computer","characteristics of a digital computer","devices/media","types/classes of computer emphasising the PC","history of computers and their generations","Problem-solving: algorithm, flowchart, pseudocode, program/data, running a program","Programming: introduction to Java/BASIC programming language syntax and programming","Booting and shutdown","types of operating system","user interface","managing information, computer malware (virus, etc)","computer network","internet and web usage, e-mail, instant messaging, etc","Office applications","use of a statistical package and a database management system"]'::jsonb, 'Department of Computer Science course outline'),
  ('GSP 207', 'Logic, Philosophy and Human Existence', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('GSP 201', 'Basic Concepts and Theory of Peace', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('ECO 101', 'Principles of Economics I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '200 Level', 'first', 2, 'Elective.', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('GLG 103', 'Basic and Applied Geology for Environmental, Physical and Social Sciences', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '200 Level', 'first', 3, 'Elective. The earth and the solar system; internal structures and physics of the earth; important minerals and major rock types; geologic time-scale and geochronology; elements of earth history; relationship between geomorphic and structural features; weathering and erosion, gullying, landslide, floods, desert advance, and environmental pollution, and their control; outlines of the geology and mineral resources of Nigeria.', '["The earth and the solar system", "Internal structures and physics of the earth", "Important minerals and major rock types", "Geologic time-scale and geochronology", "Elements of earth history", "Relationship between geomorphic and structural features", "Weathering and erosion, gullying, landslide, floods, desert advance, and environmental pollution, and their control", "Outlines of the geology and mineral resources of Nigeria"]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('STA 203', 'Statistics for Physical Sciences and Engineering I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '200 Level', 'first', 2, 'Elective. Initial steps in planning of biological experiments. Methods of data collection, presentation and analysis. Measures of central tendency and dispersion. Frequency distributions. Elementary probability. Discrete and continuous distributions: Binomial, Poisson, Normal and exponential distributions. Interval estimation.', '["Initial steps in planning of biological experiments", "Methods of data collection, presentation and analysis", "Measures of central tendency and dispersion", "Frequency distributions", "Elementary probability", "Discrete and continuous distributions: Binomial, Poisson, Normal and exponential distributions", "Interval estimation"]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('MTH 206', 'Advanced Mathematics VII', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '200 Level', 'second', 2, 'The programme table prints "Advanced Mathematics VII" against both MTH 206 and MTH 207; quoted as printed. Complex analysis - Elements of the algebra of complex variables, trigonometric, exponential and logarithmic functions. The number system, sequences and series. Vector differentiation and integration.', '["Complex analysis - Elements of the algebra of complex variables, trigonometric, exponential and logarithmic functions", "The number system, sequences and series", "Vector differentiation and integration"]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('GSP 208', 'Nigerian People and Culture', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('GSP 202', 'Issues in Peace and Conflict Resolution Studies', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('BCH 201', 'General Biochemistry I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '200 Level', 'second', 2, 'Elective. The cell environment: water and solutes — the unique properties of water, H-bonds, electrostatic interactions, Van der Waals attraction; alkalinity and acidity, pH and pK and their influence on cellular activities; physiological buffers. Cell macromolecules: structure, properties and functions of carbohydrates, lipids, proteins and nucleic acids. Cell structure and function: structure and function of major cell organelles; differences between prokaryotic and eukaryotic cells; biological membranes — organisation, architecture, properties and functions; the cytoplasm — mitochondria, peroxisomes, endoplasmic reticulum, Golgi complex, ribosomes, lysosomes, endosome; the nucleus — the nuclear envelope, chromatin, chromosomes, nucleolus, etc.', '["The cell environment: water and solutes, H-bonds, electrostatic interactions, Van der Waals attraction", "Alkalinity and acidity, pH and pK and their influence on cellular activities", "Physiological buffers", "Structure, properties and functions of carbohydrates, lipids, proteins and nucleic acids", "Structure and function of major cell organelles; differences between prokaryotic and eukaryotic cells", "Biological membranes: organisation, architecture, properties and functions", "The cytoplasm: mitochondria, peroxisomes, endoplasmic reticulum, Golgi complex, ribosomes, lysosomes, endosome", "The nucleus: nuclear envelope, chromatin, chromosomes, nucleolus"]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('MTH 208', 'Advanced Mathematics VIII', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '200 Level', 'second', 2, 'Elective. Numerical analysis: Linear equations, non-linear equations; finite difference operators. Introduction to linear programming.', '["Numerical analysis: Linear equations, non-linear equations", "Finite difference operators", "Introduction to linear programming"]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('PHM 241', 'Pharmacognosy I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '200 Level', 'second', 1, 'Elective.', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('PHY 262', 'Introduction to Atomic and Nuclear Physics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '200 Level', 'second', 3, 'Elective. Experimental tests of inadequacies of classical physics, concept of quanta wave-particle duality. From Bohr hypothesis to foundation of quantum mechanics. Concept of spin - Pauli''s exclusion principle. Introduction to atomic and molecular spectra. X-rays. Lasers. Radioactivity - Structure of nuclei. Nuclear fission and fusion. Nuclear reactors. Feasibility of fusion power; Detectors. Accelerators.', '["Experimental tests of inadequacies of classical physics, concept of quanta wave-particle duality", "From Bohr hypothesis to foundation of quantum mechanics", "Concept of spin - Pauli''s exclusion principle", "Introduction to atomic and molecular spectra", "X-rays", "Lasers", "Radioactivity - Structure of nuclei", "Nuclear fission and fusion", "Nuclear reactors", "Feasibility of fusion power", "Detectors", "Accelerators"]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('PHY 292', 'Practical Physics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '200 Level', 'second', 2, 'Elective. Selected experiments from the 200-Level Physics Courses.

Prerequisite: PHY 195 and PHY 196', '["Selected experiments from the 200-Level Physics Courses"]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('STA 206', 'Statistics for Physical Sciences and Engineering II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '200 Level', 'second', 1, 'Elective. Estimation: point and interval. Test of significance. Regression and correlation. Analysis of variance: one-way and two-way with no interaction.', '["Estimation: point and interval", "Test of significance", "Regression and correlation", "Analysis of variance: one-way and two-way with no interaction"]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('CED 341', 'Introduction to Entrepreneurship', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'first', 2, '', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('COS 201', 'Computer Programming I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'first', 2, 'Printed in this table as "Computer Programming 11"; every other appearance of COS 201 in this document titles it Computer Programming I, used here.', '[]'::jsonb, 'Faculty of Physical Sciences course catalogue (2014/2015)'),
  ('MCB 321', 'Environmental Microbiology', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'first', 2, 'Elective.', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('PHY 351', 'Electronics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'first', 2, 'Elective. Electronic device characteristics, equivalent circuit; various types of amplifiers, frequency and phase response, distortion, feedback oscillators. Semi-conductor theory and devices, characteristics; Lasers and Masers; four terminal network; equivalent circuits. Communication systems; modulation, a.m., f.m., single side band; demodulation. Elements of logic circuitry. Analog to digital conversion. Computers.

Prerequisite: PHY 251', '["Electronic device characteristics, equivalent circuit", "Various types of amplifiers, frequency and phase response, distortion, feedback oscillators", "Semi-conductor theory and devices, characteristics", "Lasers and Masers", "Four terminal network", "Equivalent circuits", "Communication systems", "Modulation, a.m., f.m., single side band", "Demodulation", "Elements of logic circuitry", "Analog to digital conversion", "Computers"]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('PHY 361', 'Quantum Mechanics I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'first', 3, 'Elective.', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('BCH 311', 'Biological Macromolecules', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'first', 2, 'Elective. Structure, composition and function of biological membranes including homoeoviscous adaptation; isolation, characterisation and classification of membranes; chemistry and biosynthesis of membrane; molecular organisation of membrane components; natural and artificial membrane bilayer — fluid mosaic model; membrane transport systems — active versus passive transport systems; transport of sugars and amino acids and ionophores.', '["Structure, composition and function of biological membranes, including homoeoviscous adaptation", "Isolation, characterisation and classification of membranes", "Chemistry and biosynthesis of membrane", "Molecular organisation of membrane components", "Natural and artificial membrane bilayer: fluid mosaic model", "Membrane transport systems: active versus passive transport", "Transport of sugars and amino acids and ionophores"]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('PHM 341', 'Pharmacognosy II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'first', 3, 'Elective.', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('GER 101', 'Elementary German I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'first', 2, 'Elective.', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('FRE 101', 'Elementary French I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'first', 2, 'Elective.', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('RUS 101', 'Elementary Russian I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'first', 2, 'Elective.', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('CED 342', 'Business Development and Management', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'second', 2, '', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('PHY 352', 'Electronics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'second', 2, 'Elective.', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('PHY 362', 'Quantum Mechanics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'second', 3, 'Elective. Wave-particle duality. Fundamental postulates of quantum mechanics, Heisenberg''s uncertainty principle, statistical interpretation of wave functions. Correspondence principle: Hamilton-Jacobi equations, Schrodinger''s equation, application to one dimensional time independent problems. Central force problems, angular momentum and radial quantum numbers of hydrogen like atoms. Introduction to scattering theory.', '["Wave-particle duality", "Fundamental postulates of quantum mechanics, Heisenberg''s uncertainty principle, statistical interpretation of wave functions", "Correspondence principle: Hamilton-Jacobi equations, Schrodinger''s equation, application to one dimensional time independent problems", "Central force problems, angular momentum and radial quantum numbers of hydrogen like atoms", "Introduction to scattering theory"]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('PHM 344', 'Phytoevaluation', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'second', 2, 'Elective.', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('GER 102', 'Elementary German II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'second', 2, 'Elective.', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('FRE 102', 'Elementary French II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'second', 2, 'Elective.', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('RUS 102', 'Elementary Russian II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '300 Level', 'second', 2, 'Elective.', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('ME 481', 'Technology Development Policy', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, '', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('MCB 452', 'Industrial Microbiology', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Elective.', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme'),
  ('PHM 441', 'Physiochemical Analysis', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Pure and Industrial Chemistry', '400 Level', 'first', 2, 'Elective.', '[]'::jsonb, 'Department of Pure and Industrial Chemistry undergraduate programme');
