-- =============================================================================
-- University of Nigeria, Nsukka — Faculty of Biological Sciences — Biochemistry
-- Course outlines transcribed from the departmental course catalogue.
-- =============================================================================
-- Run in the Supabase SQL Editor. Safe to run more than once: existing rows
-- for these courses are removed first, so it updates rather than duplicates.
--
-- NOTE: BCH 411 (Biosynthesis of Macromolecules), BCH 482 (Advanced
-- Biochemical Methods), BCH 491 (Special Topics/Seminar in Biochemistry) and
-- BCH 390 (SIWES) appear in the catalogue's course lists with a title and
-- credit load but no descriptive text, so their description/topics are left
-- blank here rather than invented.
--
-- This file also carries the required ancillary and general-studies courses
-- a Biochemistry student actually sits each semester (BIO, CHM, MTH, PHY,
-- GSP, COS, STA, CED, plus MCB 201/202 and MCB 334), scoped to department =
-- 'Biochemistry' so they show up on a Biochemistry student's own timetable —
-- a second, independent row from any same-code row filed under its own
-- home department. Descriptions are reused, unedited, from this app's
-- Mathematics/Physics/Chemistry/Microbiology outlines where the course code,
-- level, semester and subject genuinely match; where no verified description
-- exists anywhere (BIO, GSP, COS, CED, the Agric/Biological-Sciences STA
-- variants, and several CHM codes the Chemistry outline doesn't cover), only
-- code/title/units/level/semester are given. The catalogue's own document
-- prints "MCB 341" for the Year-3 immunology ancillary; every Microbiology
-- table names that course MCB 334, so MCB 334 is used here. CHM 374 is
-- listed as 4 units in this catalogue versus 2 in the Chemistry department's
-- own handbook — the Biochemistry-facing credit load (4) is kept.
-- =============================================================================

delete from public.course_outlines
 where institution = 'University of Nigeria, Nsukka'
   and department = 'Biochemistry';

insert into public.course_outlines
  (course_code, course_title, institution, faculty, department, level,
   semester, credit_units, description, topics, contributor_name)
values
  ('BCH 201', 'General Biochemistry I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '200 Level', 'first', 3, 'The cell environment: water and solutes — the unique properties of water, H-bonds, electrostatic interactions, Van der Waals attraction; alkalinity and acidity, pH and pK and their influence on cellular activities; physiological buffers. Cell macromolecules: structure, properties and functions of carbohydrates, lipids, proteins and nucleic acids. Cell structure and function: structure and function of major cell organelles; differences between prokaryotic and eukaryotic cells; biological membranes — organisation, architecture, properties and functions; the cytoplasm — mitochondria, peroxisomes, endoplasmic reticulum, Golgi complex, ribosomes, lysosomes, endosome; the nucleus — the nuclear envelope, chromatin, chromosomes, nucleolus, etc.', '["The cell environment: water and solutes, H-bonds, electrostatic interactions, Van der Waals attraction", "Alkalinity and acidity, pH and pK and their influence on cellular activities", "Physiological buffers", "Structure, properties and functions of carbohydrates, lipids, proteins and nucleic acids", "Structure and function of major cell organelles; differences between prokaryotic and eukaryotic cells", "Biological membranes: organisation, architecture, properties and functions", "The cytoplasm: mitochondria, peroxisomes, endoplasmic reticulum, Golgi complex, ribosomes, lysosomes, endosome", "The nucleus: nuclear envelope, chromatin, chromosomes, nucleolus"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 301', 'Enzymology and Protein Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'first', 3, 'Protein structure and function: amino acids and the primary structure of proteins; levels of protein structure (primary, secondary, tertiary and quaternary); haemoglobinopathies. Functional classification of proteins: fibrous proteins and globular proteins, properties and functions; protein sequence analysis; protein folding diseases, molten globules, prions; isolation and purification of protein; ligand binding, oxygen-binding proteins — allosterism, cooperativity, oxygen-binding curves, the Bohr effect, Hill plots, Adair equation. Catalytic properties: enzymes; principles of enzyme action; activation energy; acid-base catalysis; enzyme active sites; classification and nomenclature of enzymes; the Michaelis-Menten equation; estimation of kinetic parameters — Km, Vmax; enzyme inhibition and activation; roles of co-factors and co-enzymes in catalysis; zymogen activation — the pancreatic enzymes and coagulation factors.', '["Amino acids and the primary structure of proteins; levels of protein structure", "Haemoglobinopathies", "Fibrous and globular proteins: properties and functions", "Protein sequence analysis, protein folding diseases, molten globules, prions", "Isolation and purification of protein", "Ligand binding and oxygen-binding proteins: allosterism, cooperativity, the Bohr effect, Hill plots, Adair equation", "Principles of enzyme action, activation energy, acid-base catalysis", "Enzyme active sites, classification and nomenclature of enzymes", "The Michaelis-Menten equation and estimation of kinetic parameters (Km, Vmax)", "Enzyme inhibition and activation", "Roles of co-factors and co-enzymes in catalysis", "Zymogen activation: pancreatic enzymes and coagulation factors"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 311', 'Membrane Biochemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'first', 1, 'Structure, composition and function of biological membranes including homoeoviscous adaptation; isolation, characterisation and classification of membranes; chemistry and biosynthesis of membrane; molecular organisation of membrane components; natural and artificial membrane bilayer — fluid mosaic model; membrane transport systems — active versus passive transport systems; transport of sugars and amino acids and ionophores.', '["Structure, composition and function of biological membranes, including homoeoviscous adaptation", "Isolation, characterisation and classification of membranes", "Chemistry and biosynthesis of membrane", "Molecular organisation of membrane components", "Natural and artificial membrane bilayer: fluid mosaic model", "Membrane transport systems: active versus passive transport", "Transport of sugars and amino acids and ionophores"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 341', 'Food Biochemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'first', 1, 'An introduction to the theory and application of physical and chemical methods of determining the constituents of food; food processing, preservation and storage of traditional foods — roots and stem tubers, fruit and fruit drinks, seeds and grains, green vegetables; food poisoning and intoxication, prevention and cure.', '["Theory and application of physical and chemical methods of determining the constituents of food", "Food processing, preservation and storage of traditional foods: roots and stem tubers, fruit and fruit drinks, seeds and grains, green vegetables", "Food poisoning and intoxication, prevention and cure"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 351', 'Primary Metabolic Pathways I – Metabolism of Carbohydrates', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'first', 1, 'Degradation and digestion of carbohydrates — sugars, storage polysaccharides and cell walls; reactions of sugars; glycogenolysis; glycolysis; tricarboxylic acid cycle; the glyoxylate pathway; the pentose phosphate pathway; Cori cycle and Calvin pathway; gluconeogenesis and glycogenesis; disorders of carbohydrate metabolism.', '["Degradation and digestion of carbohydrates: sugars, storage polysaccharides and cell walls", "Reactions of sugars", "Glycogenolysis and glycolysis", "Tricarboxylic acid cycle and the glyoxylate pathway", "The pentose phosphate pathway", "Cori cycle and Calvin pathway", "Gluconeogenesis and glycogenesis", "Disorders of carbohydrate metabolism"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 353', 'Primary Metabolic Pathways III – Metabolism of Amino Acids and Proteins', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'first', 2, 'Amino acids as building blocks of proteins: covalent backbone of proteins, amino acid composition; protein isolation — fractionation, purification and characterisation; biological functions of proteins; oxidative degradation of amino acids and metabolism of the carbon units; biosynthesis of amino acids and some derivatives; the urea cycle; metabolism of inorganic nitrogen; disorders of amino acid metabolism.', '["Amino acids as building blocks of proteins: covalent backbone, amino acid composition", "Protein isolation: fractionation, purification and characterisation", "Biological functions of proteins", "Oxidative degradation of amino acids and metabolism of the carbon units", "Biosynthesis of amino acids and some derivatives", "The urea cycle and metabolism of inorganic nitrogen", "Disorders of amino acid metabolism"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 381', 'Techniques in Biochemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'first', 2, 'Principles of instrumentation: centrifugation, cell fractionation technique and instrumentation, application of centrifugation. Chromatography: planar chromatography (paper and thin-layer), column chromatography, ion-exchange and gel exclusion chromatography, gas chromatography and high performance liquid chromatography, affinity chromatography and immunoadsorption. Electrophoresis: theory of electrophoresis, methods of electrophoresis — polyacrylamide gel electrophoresis (PAGE), nucleic acid sequencing gels, agarose gel electrophoresis, pulsed field electrophoresis, isoelectric focusing, 2-dimensional electrophoresis of protein, capillary electrophoresis, immunoelectrophoresis, instrumentation and analysis of electrophoresis results. Spectroscopy: UV-visible absorption spectrophotometry, fluorescence spectrophotometry, nuclear magnetic resonance spectrophotometry and mass spectrometry. Radioisotope techniques: overview of radioactivity, detection and measurement of radioactivity, application of radioactivity and safety issues. Molecular technique: hybridisation techniques, polymerase chain reaction. Immunochemical techniques: immunochemical and immunoblotting. Use of computers in research: bioinformatics.', '["Principles of instrumentation: centrifugation, cell fractionation technique and instrumentation", "Chromatography: planar, column, ion-exchange, gel exclusion, gas, HPLC, affinity and immunoadsorption", "Electrophoresis: theory and methods — PAGE, agarose gel, pulsed field, isoelectric focusing, capillary electrophoresis", "Spectroscopy: UV-visible, fluorescence, NMR and mass spectrometry", "Radioisotope techniques: detection, measurement, application and safety of radioactivity", "Molecular technique: hybridisation techniques, polymerase chain reaction", "Immunochemical techniques: immunochemical and immunoblotting", "Use of computers in research: bioinformatics"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 390', 'Students Industrial Work Experience', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 401', 'Advanced Enzymology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '400 Level', 'first', 2, 'Steady state enzyme kinetics; kinetics of multisubstrate; regulatory enzymes — molecular models for allosterism, multienzyme complexes; chemical basis of enzyme catalysis; enzyme reaction mechanisms, e.g. ribonuclease, chymotrypsin, lysozyme, LDH, etc; site-directed mutagenesis.', '["Steady state enzyme kinetics; kinetics of multisubstrate reactions", "Regulatory enzymes: molecular models for allosterism, multienzyme complexes", "Chemical basis of enzyme catalysis", "Enzyme reaction mechanisms, e.g. ribonuclease, chymotrypsin, lysozyme, LDH", "Site-directed mutagenesis"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 411', 'Biosynthesis of Macromolecules', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '400 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 421', 'Tissue Biochemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '400 Level', 'first', 2, 'Biochemistry of kidney; biochemistry of liver; biochemistry of muscle; biochemistry of adipose; biochemistry of vision. General metabolism of the brain: neural biochemistry; biochemistry of reproductive tissues. Detoxification and excretion in tissues.', '["Biochemistry of kidney, liver, muscle, adipose and vision", "General metabolism of the brain: neural biochemistry", "Biochemistry of reproductive tissues", "Detoxification and excretion in tissues"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 431', 'Bioinorganic Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '400 Level', 'first', 2, 'The relationship between the physiochemical properties and biological functions of inorganic ions; ligand complexes and their biochemical significance; electrolyte metabolism, nitrogen fixation, sulphur and phosphate cycles.', '["Relationship between the physiochemical properties and biological functions of inorganic ions", "Ligand complexes and their biochemical significance", "Electrolyte metabolism", "Nitrogen fixation, sulphur and phosphate cycles"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 471', 'Industrial Biochemistry and Biotechnology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '400 Level', 'first', 3, 'Overview and definition of biotechnology; biotechnology and the developing world; overview of microbial physiology and genetics. Substrates for biotechnology: a biomass strategy, natural raw materials, raw materials and the future of biotechnology. Biological fuel generation: photosynthesis, sources of biomass, microbial recovery of petroleum. Genetics and biotechnology: industrial genetics, protoplast and cell fusion technology, genetic engineering. Bioprocess/fermentation biotechnology: principles of microbial growth, the bioreactor and media design for fermentation, scaling up, down-stream processing. Enzyme technology: industrial production of enzymes, immobilisation of enzymes. Biotechnology and medicine: pharmaceuticals and biopharmaceuticals, antibiotics, vaccines and monoclonal antibodies, gene therapy. Environmental biotechnology: microbial ecology, landfill technology and composting, bioremediation, monitoring of pollutants, environmental sustainability and cleaner technology. Food and beverage biotechnology: enzymes and food processing, production of sweeteners and other microbial-derived food. Biotechnology in agricultural and forestry industries: plant biotechnology, forestry biotechnology, biological control, animal biotechnology. Protection of biotechnological inventions: licensing, trade secrets and patents. Safety issues in biotechnology: release of modified organisms, pathogenicity of organisms, ethical and safety issues. Biotechnology and society: public perception, ethical and moral issues.', '["Overview of biotechnology and the developing world; microbial physiology and genetics", "Substrates for biotechnology: biomass strategy, natural raw materials", "Biological fuel generation: photosynthesis, biomass, microbial recovery of petroleum", "Genetics and biotechnology: industrial genetics, protoplast and cell fusion, genetic engineering", "Bioprocess/fermentation biotechnology: microbial growth, bioreactor and media design, scale-up, down-stream processing", "Enzyme technology: industrial production and immobilisation of enzymes", "Biotechnology and medicine: pharmaceuticals, antibiotics, vaccines, monoclonal antibodies, gene therapy", "Environmental biotechnology: microbial ecology, landfill technology, bioremediation, pollutant monitoring", "Food and beverage biotechnology: enzymes in food processing, sweeteners and microbial-derived food", "Biotechnology in agriculture and forestry: plant, forestry and animal biotechnology, biological control", "Protection of biotechnological inventions: licensing, trade secrets and patents", "Safety issues: release of modified organisms, pathogenicity, ethics", "Biotechnology and society: public perception, ethical and moral issues"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 481', 'Biochemical Reasoning', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '400 Level', 'first', 1, 'Introduction to biochemical research and reasoning: choice and statement of research problem, searching the literature and referencing, design and execution of experiment. The art of scientific investigation: recognition and exploitation of chance, precaution and use of hypothesis, imagination and intuition, reason, observation, difficulties and strategy. Analysis of experimental data: errors of measurement, statistical treatment of data, reporting the result of research. Scientific writing: writing a research proposal and application for grant, writing a thesis, writing a conference or journal article/referencing. Research ethics and misconduct: working with animals and human subjects, scientific misconduct — data fabrication and falsification, wrong assignment of authorship credits and misuse of research funds, reporting and handling of misconduct cases. Application of computers in biochemical research.', '["Choice and statement of research problem; searching the literature and referencing", "Design and execution of experiment", "The art of scientific investigation: recognition and exploitation of chance, hypothesis, imagination and intuition", "Analysis of experimental data: errors of measurement, statistical treatment, reporting results", "Scientific writing: research proposals, grant applications, theses, journal articles", "Research ethics and misconduct: data fabrication and falsification, authorship credits, misuse of research funds", "Application of computers in biochemical research"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 491', 'Special Topics/Seminar in Biochemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '400 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 202', 'General Biochemistry II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '200 Level', 'second', 3, 'Enzymes: introduction to biological catalysts, nature, functions and classification of enzymes, factors affecting enzyme action. Energy metabolism: introductory bioenergetics/energy-rich compounds, carbohydrate metabolism — glycolysis and pentose phosphate pathway, the Krebs cycle and the glyoxylate cycle, electron transport and oxidative phosphorylation. Separation of macromolecules: chromatographic methods — thin layer chromatography, gel filtration, ion exchange chromatography, affinity chromatography; electrophoretic methods — nucleic acid gel electrophoresis, electrophoretic sizing of protein, isoelectric focusing.', '["Introduction to biological catalysts: nature, functions and classification of enzymes; factors affecting enzyme action", "Introductory bioenergetics/energy-rich compounds", "Carbohydrate metabolism: glycolysis and pentose phosphate pathway", "The Krebs cycle and the glyoxylate cycle", "Electron transport and oxidative phosphorylation", "Chromatographic methods: thin layer, gel filtration, ion exchange, affinity chromatography", "Electrophoretic methods: nucleic acid gel electrophoresis, protein sizing, isoelectric focusing"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 332', 'Bioenergetics', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'second', 1, 'High energy compounds; complex reactions; chemical potentials and reductions. Electron transport system and oxidative phosphorylation. Regulation of ATP production. Hypotheses/theories of oxidative phosphorylation.', '["High energy compounds; complex reactions; chemical potentials and reductions", "Electron transport system and oxidative phosphorylation", "Regulation of ATP production", "Hypotheses/theories of oxidative phosphorylation"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 342', 'Nutritional Biochemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'second', 1, 'Macromolecules: proteins — protein quality, requirement, deficiency, nitrogen balance; lipids — fatty acids (essential and non-essential); carbohydrates. Dietary reference standards: new terminologies for assessment of nutrient intake — Expected Average Requirement (EAR), Dietary Reference Values (DRV); the vitamins; minerals and trace elements. Measuring food intake: direct and indirect measurement, household food surveys, etc. Nutrition research methodology: design and statistical analysis, in vitro studies, animal models, human studies. Molecular aspects of nutrition: genetic variations in response to nutrients, nutrient regulation of gene expression. Application of nutritional knowledge: nutrition in pregnancy and lactation, diet and coronary heart disease, nutrition of the aged, diet and cancer, nutrition and the immune system. Nutritional disorders: malnutrition, undernutrition and overnutrition; eating disorders — anorexia, bulimia, binge eating; metabolic disorders — diabetes, obesity, arteriosclerosis, etc; food allergy and intolerance. Public health nutrition: nutritional epidemiology, assessment of nutritional status in individuals and populations.', '["Macronutrients: proteins, lipids (fatty acids) and carbohydrates", "Dietary reference standards: EAR, DRV, vitamins, minerals and trace elements", "Measuring food intake: direct and indirect measurement, household food surveys", "Nutrition research methodology: design and statistical analysis, in vitro, animal and human studies", "Molecular aspects of nutrition: genetic variations in response to nutrients, gene expression regulation", "Application of nutritional knowledge: pregnancy and lactation, coronary heart disease, ageing, cancer, immune system", "Nutritional disorders: malnutrition, eating disorders, metabolic disorders, food allergy and intolerance", "Public health nutrition: nutritional epidemiology and assessment of nutritional status"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 352', 'Primary Metabolic Pathways II – Metabolism of Lipids', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'second', 2, 'Classification and functions of lipids — fatty acids, triacylglycerol, glycoglycerols, phospholipids, sphingolipids, waxes and prostaglandins; lipid micelles, monolayers and bilayers, lipoprotein systems. Oxidation and synthesis of fatty acids. Formation of ketone bodies. Integration of lipid metabolism. Cholesterol metabolism; metabolism of steroids.', '["Classification and functions of lipids: fatty acids, triacylglycerol, glycoglycerols, phospholipids, sphingolipids, waxes, prostaglandins", "Lipid micelles, monolayers and bilayers, lipoprotein systems", "Oxidation and synthesis of fatty acids", "Formation of ketone bodies", "Integration of lipid metabolism", "Cholesterol metabolism and metabolism of steroids"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 354', 'Primary Metabolic Pathways IV – Metabolism of Nucleic Acid', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'second', 2, 'Genome organisation; biosynthesis of proteins; metabolism, structure, properties and functions of nucleosides and nucleotides; metabolism of purine and pyrimidine; abnormalities in nucleic acid metabolism, xeroderma pigmentosum and skin cancer.', '["Genome organisation", "Biosynthesis of proteins", "Metabolism, structure, properties and functions of nucleosides and nucleotides", "Metabolism of purine and pyrimidine", "Abnormalities in nucleic acid metabolism: xeroderma pigmentosum and skin cancer"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 412', 'Genetic Engineering (Recombinant DNA Technology)', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '400 Level', 'second', 2, 'DNA manipulation: overview of DNA structure and properties, history of recombinant DNA technology, extraction and synthesis of DNA, polymerase chain reaction. Tools for DNA manipulation: restriction endonucleases and DNA ligase; vectors — cloning vectors, plasmid vectors, phage vectors, cosmid vectors; transfer of foreign DNA into mammalian cells and animals; Southern blotting and related techniques; constructing a DNA library; DNA sequencing; site-specific mutagenesis. Applications of recombinant DNA technology in medicine and agriculture: applications of gene therapy, nuclear transfer technology (cloning), molecular pharming, genetically modified food plants and animals, ethical issues associated with DNA manipulation.', '["DNA manipulation: DNA structure and properties, history of recombinant DNA technology, extraction and synthesis of DNA, PCR", "Tools for DNA manipulation: restriction endonucleases, DNA ligase, cloning/plasmid/phage/cosmid vectors", "Transfer of foreign DNA into mammalian cells and animals", "Southern blotting and related techniques; constructing a DNA library; DNA sequencing; site-specific mutagenesis", "Applications in medicine and agriculture: gene therapy, cloning, molecular pharming, genetically modified organisms", "Ethical issues associated with DNA manipulation"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 422', 'Pharmacological Biochemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '400 Level', 'second', 2, 'Cellular metabolism in infected cells; biochemical aspects of host-parasite relationship; metabolic factors affecting chemotherapeutic agents; theories of the mechanisms of drug efficacy; Nigerian traditional medicinal plants in the management and therapy of common ailments in Nigeria, malaria, sickle cell anaemia, common cold, beriberi, etc; xenobiotic metabolism and excretion; pharmacogenetics; biochemical toxicology.', '["Cellular metabolism in infected cells; biochemical aspects of host-parasite relationship", "Metabolic factors affecting chemotherapeutic agents", "Theories of the mechanisms of drug efficacy", "Nigerian traditional medicinal plants in managing malaria, sickle cell anaemia, common cold, beriberi, etc", "Xenobiotic metabolism and excretion", "Pharmacogenetics", "Biochemical toxicology"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 452', 'Metabolic Regulations', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '400 Level', 'second', 2, 'The relationship of the Krebs cycle to protein, carbohydrate, lipid and nucleic acid metabolism. Integration of metabolic pathways; turn-over rates and metabolic pools. Regulation of enzymes of metabolic pathways: feedback inhibition versus synthesis. Catabolite repression: the lactose operon and arabinose operon. Identification of different regulatory mechanisms in metabolic pathways.', '["Relationship of the Krebs cycle to protein, carbohydrate, lipid and nucleic acid metabolism", "Integration of metabolic pathways; turn-over rates and metabolic pools", "Regulation of enzymes: feedback inhibition versus synthesis", "Catabolite repression: the lactose operon and arabinose operon", "Identification of different regulatory mechanisms in metabolic pathways"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 462', 'Plant Biochemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '400 Level', 'second', 2, 'Organisation of plant cells; alkaloids, flavonoids, photosynthesis; plant hormones — structure-function relationship; metabolism of gibberellins and cytokinin. Biosynthesis of carotenoid pigments. Biochemistry of plant development, the plant cell wall structure, formation and growth in lignin formation. Free amino acids, pyrimidines, purines and nucleosides in plants. Synthesis of growth regulators and herbicides.', '["Organisation of plant cells; alkaloids, flavonoids, photosynthesis", "Plant hormones: structure-function relationship; metabolism of gibberellins and cytokinin", "Biosynthesis of carotenoid pigments", "Biochemistry of plant development; plant cell wall structure, formation and lignin growth", "Free amino acids, pyrimidines, purines and nucleosides in plants", "Synthesis of growth regulators and herbicides"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 482', 'Advanced Biochemical Methods', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '400 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BCH 492', 'Research Project', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '400 Level', 'second', 6, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('BIO 151', 'General Biology I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '100 Level', 'first', 3, 'Elective.', '[]'::jsonb, 'Department of Computer Science course outline'),
  ('CHM 101', 'Basic Principles of Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '100 Level', 'first', 2, 'Stoichiometry and Atomic Structure: Stoichiometry and mole concept. Introduction to atomic structure, development of electronic configuration of the elements, and valency theories. Periodic Table and Groups: The periodic classification of elements. Brief group study of representative elements, with emphasis on similarities and differences based on periodic position. Nuclear Chemistry: Radioactivity and its practical applications.', '["Stoichiometry and Atomic Structure: Stoichiometry and mole concept. Introduction to atomic structure, development of electronic configuration of the elements, and valency theories", "Periodic Table and Groups: The periodic classification of elements. Brief group study of representative elements, with emphasis on similarities and differences based on periodic position", "Nuclear Chemistry: Radioactivity and its practical applications"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MTH 111', 'General Mathematics I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '100 Level', 'first', 3, 'Elementary set theory, subsets, union, intersection, complements. Venn diagrams, real numbers, integers, rational and irrational numbers, mathematical induction, real sequences and series, theory of quadratic equations, binomial theorem. Circular measure, trigonometric functions of angles of any magnitude, addition and factor formulae. Complex numbers, algebra of complex numbers, the Argand diagram, De Moivre''s theorem, nth roots of unity.', '["Elementary set theory, subsets, union, intersection, complements", "Venn diagrams, real numbers, integers, rational and irrational numbers, mathematical induction, real sequences and series, theory of quadratic equations, binomial theorem", "Circular measure, trigonometric functions of angles of any magnitude, addition and factor formulae", "Complex numbers, algebra of complex numbers, the Argand diagram, De Moivre''s theorem, nth roots of unity"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MTH 121', 'General Mathematics II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '100 Level', 'first', 3, 'Functions of a real variable, graphs, limits and continuity. The derivative as limit of rate of change. Techniques of differentiation. Curve sketching, integration as an inverse of differentiation. Methods of integration, definite integrals. Application of integration to areas and volumes.', '["Functions of a real variable, graphs, limits and continuity", "The derivative as limit of rate of change", "Techniques of differentiation", "Curve sketching, integration as an inverse of differentiation", "Methods of integration, definite integrals", "Application of integration to areas and volumes"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 171', 'Basic Practical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '100 Level', 'first', 2, 'Laboratory operations: theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations.', '["Laboratory operations: theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('PHY 111', 'General Physics for Life Sciences I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '100 Level', 'first', 2, 'Units and dimension. Scalars and vectors. Linear and circular motion, velocity, acceleration. Laws of mechanics and gravitation; simple applications. Conservation of energy, momentum. Work and power. Simple harmonic motion, simple pendulum. Moment of inertia, angular momentum; centrifugal and centripetal forces; centrifuges. Elasticity, Hooke''s Law, Young''s modulus. Fluids, pressure, surface tension, velocity, osmosis; blood pressure and its measurement.', '["Units and dimension; scalars and vectors", "Linear and circular motion, velocity, acceleration", "Laws of mechanics and gravitation; conservation of energy and momentum", "Work and power; simple harmonic motion, simple pendulum", "Moment of inertia, angular momentum; centrifugal and centripetal forces; centrifuges", "Elasticity, Hooke''s Law, Young''s modulus", "Fluids: pressure, surface tension, velocity, osmosis; blood pressure and its measurement"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('PHY 191', 'Practical Physics I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '100 Level', 'first', 2, 'Selected experiments from the 100-Level courses in Physics for service courses.', '["Selected experiments from the 100-Level courses in Physics for service courses"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('GSP 101', 'The Use of English I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '100 Level', 'first', 2, 'Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, The English Language and the Nigerian society, World English, Levels and Varieties of English — formal, informal, standard, etc., English in Literature and the Media.

Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes, English Language Register, diatypes and dialects.

Listening skill - The listening skill discussed as a receptive and reciprocal activity, Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening.

Reading Skill - The concept of reading as a linguistic organization and a vehicle of communication. Reading Problems, Levels of Reading, Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies (Scanning, Skimming, Phrase reading, Intensive & Extensive reading, Exploiting the topic sentence for main ideas), Reading for details, Reading for evaluation and inference, Reading with questions - SQ3R, PR3, Methods for understanding difficult words in a reading text, Literature reading for study, analysis and comment.

Speaking & Communication Skills - Nature, Process & Development, Principles of Public Speech Making and Social Interaction, The Speech Sounds of English and their Articulation, Phonetic Transcription and Practical Speech Work.

Study Techniques - Choosing study centers and discussion groups, Note-taking during lectures, and from audio-visual equipment, Note-making techniques during private reading and literature search, Summary & Transcoding Techniques, Retrieving information from notes, The dictionary as a study guide.

Basic Research Methods & Term Paper Writing - Research – meaning & nature, Types & Methodology; Data in the Research Process, The Research Report, Process and Techniques, Documentation in Research Reports: Process, Types and Methods, Abbreviations in Research Reports, The term paper as a miniature research report, Practical term paper writing.

Course Evaluation & Grading - Students must attend at least 75% of the lectures to qualify for examination in the course.', '["Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, World English, Levels and Varieties of English", "Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes", "Listening skill - Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening", "Reading Skill - Reading Problems, Levels and Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies, Reading for evaluation and inference", "Speaking & Communication Skills - Principles of Public Speech Making and Social Interaction, Phonetic Transcription and Practical Speech Work", "Study Techniques - Note-taking, Note-making, Summary & Transcoding Techniques", "Basic Research Methods & Term Paper Writing - The Research Report, Documentation, Abbreviations, practical term paper writing"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('GSP 111', 'The Use of Library and Study Skills', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '100 Level', 'first', 2, 'Overview of Library: concepts, history, types and functions. Uses in academic libraries; organization of university library and library users. Library processes and procedures. Acquisition process, Cataloging and classification, LC Scheme, in-House Scheme, DDC. Serials process and circulation processes. Access tools in Library resources: Library catalogues, Indexes, Abstracts, Current contents information in the library. Reference sources: types of reference sources and services. Web resources and online resources. Overview of Databases, Online search strategies for information retrieval. Referencing and citation styles for information reporting. Concept of plagiarism. Learning skills and research skills, ICT skillsets: types of learning and information policies.', '["Overview of Library: concepts, history, types and functions. Uses in academic libraries; organization of university library and library users", "Library processes and procedures. Acquisition process, Cataloging and classification, LC Scheme, in-House Scheme, DDC. Serials process and circulation processes", "Access tools in Library resources: Library catalogues, Indexes, Abstracts, Current contents information", "Reference sources: types of reference sources and services. Web resources and online resources", "Overview of Databases, Online search strategies for information retrieval. Referencing and citation styles for information reporting. Concept of plagiarism", "Learning skills and research skills, ICT skillsets: types of learning and information policies"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('BIO 152', 'General Biology II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '100 Level', 'second', 3, 'Elective.', '[]'::jsonb, 'Department of Statistics undergraduate course module'),
  ('BIO 154', 'General Biology Practicals', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '100 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('PHY 112', 'General Physics for Life Science II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '100 Level', 'second', 2, 'Concepts of heat, temperature: measurement of temperature, clinical thermometer. Heat capacity, specific heat, latent heat, calorimetry. Gas laws; kinetic theory of gases. Thermal energy, isothermal and adiabatic changes. Conduction, convection; radiation. Sound waves; intensity, pitch and quality of sound. Propagation of sound in solids, liquids and gases. Doppler effect. The ear. Reflection and refraction of light; plane and spherical mirrors, thin lenses; optical instruments. The eye, defects of vision and their corrections. Wave nature of light, interference, diffraction: velocity of light.', '["Concepts of heat and temperature: measurement, clinical thermometer, heat capacity, calorimetry", "Gas laws; kinetic theory of gases; thermal energy, isothermal and adiabatic changes", "Conduction, convection and radiation", "Sound waves: intensity, pitch, quality; propagation in solids, liquids and gases; Doppler effect; the ear", "Reflection and refraction of light: mirrors, thin lenses, optical instruments", "The eye, defects of vision and their corrections", "Wave nature of light: interference, diffraction, velocity of light"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('PHY 114', 'General Physics for Life Science III', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '100 Level', 'second', 2, 'Electric charge, Coulomb''s Law, electric field, electrostatic potential. Energy in electric field, capacitors. Dielectrics. Electric current, potential difference and electromotive force. Ohm''s Law: potentiometer, metre bridge, Wheatstone bridge. Magnetic effects of currents; permanent magnetism, earth''s magnetic field. Faraday''s Law of induction, generators and electric motor. Alternating currents; Maxwell''s equations. Structure of the atom. Radioactivity, X-rays, applications in life sciences. Nuclear energy.', '["Electric charge, Coulomb''s Law, electric field, electrostatic potential", "Energy in electric field, capacitors; dielectrics", "Electric current, potential difference and electromotive force; Ohm''s Law", "Magnetic effects of currents; permanent magnetism, earth''s magnetic field", "Faraday''s Law of induction, generators and electric motor; alternating currents; Maxwell''s equations", "Structure of the atom; radioactivity, X-rays, applications in life sciences; nuclear energy"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 112', 'Basic Principles of Physical Chemistry II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '100 Level', 'second', 2, 'Gas laws and kinetic theory: kinetic theory of gases, elementary derivation and deduction of gas laws, molecular speeds, deviations from ideal behaviour, van der Waals modification, and gas liquefaction. Phase equilibrium and solutions: phase transitions and phase equilibria in one-component systems; ideal solutions, Raoult''s law, Henry''s law, real solutions, and colligative properties. Thermodynamics and kinetics: aspects of the first law of thermodynamics, thermochemistry, entropy, free energy, and spontaneous changes; ionic equilibria, acids, bases, indicators, and buffers; elementary chemical kinetics.', '["Gas laws and kinetic theory of gases; molecular speeds; deviations from ideal behaviour; gas liquefaction", "Phase transitions and phase equilibria; ideal and real solutions; colligative properties", "First law of thermodynamics, thermochemistry, entropy, free energy, spontaneous changes", "Ionic equilibria, acids, bases, indicators and buffers", "Elementary chemical kinetics: rate laws, order and molecularity, Arrhenius equation"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 122', 'Basic Principles of Organic Chemistry III', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '100 Level', 'second', 2, 'Structure and classification: historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, homologous series, elemental analysis, molecular formulas, and structural isomerism. Bonding and reactivity: isolation and purification methods, functional group concepts, resonance, and aromaticity. Functional groups: saturated and unsaturated hydrocarbons, cyclic hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, and aromatic compounds. Stereochemistry and lipids: introduction to oils, fats, and stereoisomerism.', '["Historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, structural isomerism", "Isolation and purification methods; functional group concepts; resonance and aromaticity", "Saturated and unsaturated hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, aromatic compounds", "Introduction to oils, fats, and stereoisomerism"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('GSP 102', 'The Use of English II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '100 Level', 'second', 2, 'Part A: Basic Grammar: Introduction. The concept of grammar and its place in language teaching and learning. Parts of speech and their functions (treated in detail). Closed and open class items in parts of speech, Nominalization, Grammatical Structures: the phrase, the clause and the sentence. Elementary Clause Analysis, Sentence Types, Elements and Patterns. Agreement (Grammatical agreement, Notional agreement, Proximity agreement) Agreement with the correlatives. Direct and Reported Speech, Error typology identification and correction.

Part B: Varieties of writing. Introduction (The Meaning, Nature and Purpose of Writing, Writing Types or Genres and their Characteristics). The paragraph as the basic unit of an essay (Types, Development of the Paragraph, Methods of Paragraph Development, The thesis statement). Point of view and style in writing. Qualities of a good piece of writing: Form, Diction and Content in writing. The Mechanics of Writing: punctuation, spelling and capitalization.

Part C: Writing Genres - Planning and choosing your theme. Deciding your genre. Choosing and developing your plot. Point of view, setting and characterization. Using the language that works. Essay Writing — Narration, Description, Exposition and Argumentation. Technical Writing: Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes, own story for practice, Computer-linked writing, types, style, language, and process.', '["Part A: Basic Grammar - The concept of grammar, Parts of speech, Grammatical Structures, Sentence Types, Agreement, Direct and Reported Speech, Error typology", "Part B: Varieties of writing - Meaning, Nature and Purpose of Writing, the paragraph as the basic unit of an essay, the thesis statement, Qualities of a good piece of writing, Mechanics of Writing", "Part C: Writing Genres - Planning and choosing your theme, plot, point of view, setting and characterization", "Essay Writing - Narration, Description, Exposition and Argumentation", "Technical Writing - Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('CHM 201', 'General Inorganic Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '200 Level', 'first', 2, 'Periodic trends: ionization potential, electron affinity, and electronegativity. Chemical bonding: electrostatic and non-electrostatic valence forces, non-valence cohesive forces. Coordination compounds: introduction to complexes, focusing on colour, magnetic properties, and practical applications.

Prerequisite: CHM 101, or a pass in Chemistry at H.S.C./G.C.E. A-Level', '["Periodic trends: ionization potential, electron affinity, and electronegativity", "Chemical bonding: electrostatic and non-electrostatic valence forces, non-valence cohesive forces", "Coordination compounds: complexes, colour, magnetic properties and practical applications"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 211', 'General Physical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '200 Level', 'first', 2, 'Gases and thermodynamics: molecular collisions in gases, virial equation, critical phenomena, and reduced properties; chemical thermodynamics, detailed treatment of the first law of thermodynamics, and the Carnot cycle. Chemical kinetics: integrated rate equations for second and third order reactions, reaction mechanisms, rate laws, and the effect of temperature on reaction rates.

Prerequisite: CHM 112', '["Molecular collisions in gases, virial equation, critical phenomena, reduced properties", "Chemical thermodynamics: first law of thermodynamics; the Carnot cycle", "Integrated rate equations for second and third order reactions; reaction mechanisms and rate laws", "Effect of temperature on reaction rates"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 221', 'General Organic Chemistry I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 273', 'Practical Organic Chemistry I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('COS 101', 'Introduction to Computer Science', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '200 Level', 'first', 2, 'Concepts of hardware and software; basic subsystems of a digital computer; characteristics of a digital computer; devices/media; types/classes of computer emphasising the PC; history of computers and their generations. Problem-solving: algorithm, flowchart, pseudocode, program/data, running a program. Programming: introduction to Java/BASIC programming language syntax and programming. Booting and shutdown; types of operating system; user interface; managing information, computer malware (virus, etc); computer network; internet and web usage, e-mail, instant messaging, etc. Office applications; use of a statistical package and a database management system.', '["Concepts of hardware and software","basic subsystems of a digital computer","characteristics of a digital computer","devices/media","types/classes of computer emphasising the PC","history of computers and their generations","Problem-solving: algorithm, flowchart, pseudocode, program/data, running a program","Programming: introduction to Java/BASIC programming language syntax and programming","Booting and shutdown","types of operating system","user interface","managing information, computer malware (virus, etc)","computer network","internet and web usage, e-mail, instant messaging, etc","Office applications","use of a statistical package and a database management system"]'::jsonb, 'Department of Computer Science course outline'),
  ('MCB 201', 'General Microbiology I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '200 Level', 'first', 3, 'General review of the nature and biology of protozoa, fungi, algae, bacteria, archaea and viruses. General characteristics, growth and reproduction of microorganisms. Microbiology methods and instrumentation. Sterilisation and disinfection. Microorganisms in various environments: soil, water, food, etc. Industrial use of microorganisms. Pathogenic role of microorganisms.

Pre-requisite: MCB 102', '["Nature and biology of protozoa, fungi, algae, bacteria, archaea and viruses", "General characteristics, growth and reproduction of microorganisms", "Microbiology methods and instrumentation", "Sterilisation and disinfection", "Microorganisms in various environments: soil, water, food", "Industrial use of microorganisms", "Pathogenic role of microorganisms"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('STA 203', 'Statistics for Agricultural and Biology Science I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '200 Level', 'first', 2, 'Initial steps in planning of biological experiments. Methods of data collection, presentation and analysis. Measures of central tendency and dispersion. Frequency distributions. Elementary probability. Discrete and continuous distributions: Binomial, Poisson, Normal and exponential distributions. Interval estimation.', '["Initial steps in planning of biological experiments", "Methods of data collection, presentation and analysis", "Measures of central tendency and dispersion", "Frequency distributions", "Elementary probability", "Discrete and continuous distributions: Binomial, Poisson, Normal and exponential distributions", "Interval estimation"]'::jsonb, 'Department of Statistics handbook'),
  ('GSP 207', 'Logic, Philosophy and Human Existence', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('GSP 201', 'Basic Concepts and Theory of Peace', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('COS 304', 'Computer Applications', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('STA 204', 'Statistics for Agricultural and Biology Sciences II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '200 Level', 'second', 2, 'Tests of significance. Student $t$ test and $\chi^2$ test. Two sample test and paired comparison. Regression and correlation. Analysis of variance: one way, two way with no interaction. Latin square analysis. Multiple range tests. Analysis of covariance. Simple analysis of direct assays.', '["Tests of significance", "Student $t$ test and $\\chi^2$ test", "Two sample test and paired comparison", "Regression and correlation", "Analysis of variance: one way, two way with no interaction", "Latin square analysis", "Multiple range tests", "Analysis of covariance", "Simple analysis of direct assays"]'::jsonb, 'Department of Statistics handbook'),
  ('MCB 202', 'General Microbiology II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '200 Level', 'second', 3, 'Review of the structure and organisation of prokaryotic and eukaryotic cells. Principles and methodology of numerical taxonomy. Application of molecular biology in classification of microorganisms. Systematic classification of bacteria, fungi, protozoa and viruses. Physiology, ecology and laboratory identification of important species of microorganisms. Elemental cycles (carbon, nitrogen and phosphorus).

Pre-requisite: MCB 102', '["Structure and organisation of prokaryotic and eukaryotic cells", "Principles and methodology of numerical taxonomy", "Application of molecular biology in classification of microorganisms", "Systematic classification of bacteria, fungi, protozoa and viruses", "Physiology, ecology and laboratory identification of important species of microorganisms", "Elemental cycles: carbon, nitrogen and phosphorus"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 222', 'General Organic Chemistry II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 274', 'Practical Inorganic Chemistry I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 272', 'Practical Physical Chemistry I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('GSP 208', 'Nigerian Peoples and Culture', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 334', 'Immunology and Immunochemistry', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'first', 3, 'Basic concept of immunology. Innate and adaptive immunity. Ontogeny of cells of the immune system. Structure of antigens and antigenic determinants. Cellular response. Genetics of response to antigenic stimulation. Structure, genetics and classification of antibodies. Mechanism and theories of antibody formation. Antigen and antibody interactions. Role of lymphoid tissues and thymus in immune response. Hypersensitivity, immunopathology, autoimmunity, tumour and transplantation immunology.

Pre-requisite: MCB 201 & BCH 201. Printed in the Biochemistry programme table as "MCB 341"; every Microbiology course list in the catalogue names this course MCB 334, which is used here.', '["Basic concepts of immunology: innate and adaptive immunity", "Ontogeny of cells of the immune system", "Structure of antigens and antigenic determinants; cellular response", "Structure, genetics and classification of antibodies; theories of antibody formation", "Antigen-antibody interactions; role of lymphoid tissues and thymus", "Hypersensitivity, immunopathology, autoimmunity, tumour and transplantation immunology"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 311', 'Physical and Structural Chemistry I', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'first', 2, 'Elective.', '[]'::jsonb, 'Faculty of Physical Sciences course catalogue (2014/2015)'),
  ('BIO 351', 'General Genetics', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CED 341', 'Introduction to Entrepreneurship', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 312', 'Physical and Structural Chemistry II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 313', 'Physical and Structural Chemistry III', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 322', 'Organic Chemistry II', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 323', 'Organic Chemistry III', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CHM 374', 'Applied Spectroscopy', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'second', 4, 'Instrumentation and theory: introduction to principles and practical operations of Infrared (IR), Ultraviolet-Visible (UV-Vis), Nuclear Magnetic Resonance (NMR), and Mass Spectrometry (MS).', '["Instrumentation and theory: principles and practical operations of IR, UV-Vis, NMR and Mass Spectrometry"]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('MCB 312', 'Microbial Genetics/Molecular Biology', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue'),
  ('CED 342', 'Business Development and Management', 'University of Nigeria, Nsukka', 'Faculty of Biological Sciences', 'Biochemistry', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Biological Sciences course catalogue');
