-- =============================================================================
-- University of Nigeria, Nsukka - Faculty of Physical Sciences - Physics and Astronomy
-- Course outlines transcribed from the departmental course handbook.
-- =============================================================================
-- Run in the Supabase SQL Editor. Safe to run more than once: existing rows
-- for these courses are removed first, so it updates rather than duplicates.
--
-- NOTE ON SEMESTERS: the handbook does not state which semester each course
-- runs in. The values below follow the usual Nigerian convention that an odd
-- final digit is first semester and an even one is second. Correct any that
-- differ at UNN by editing the semester column in the Table Editor.
--
-- NOTE ON CREDIT UNITS: the source PDF right-aligns the unit values, so text
-- extraction lifted them into a separate block at the top of each page. They
-- were matched back to their courses by page order. Worth a spot check
-- against the printed handbook.
--
-- This file also carries the required ancillary, general-studies and elective
-- courses a Physics and Astronomy student actually sits each semester, scoped to
-- this department so they appear on the student's own timetable — independent
-- rows from any same-code row filed under its own home department.
-- Source for the programme structure: physicsandastronomy.unn.edu.ng/undergraduate-programmes/
-- Descriptions are reused, unedited, from this app's sibling UNN outline files
-- wherever the course code already exists there; courses with no verified
-- description anywhere (GSP, COS, BIO, ECO, engineering and language codes)
-- carry code/title/units/level/semester only, rather than an invented syllabus.
-- Electives are flagged by an "Elective." prefix on the description, since this
-- file's column list predates the is_elective column.
-- Only the Four-Year Standard Programme is followed, not the Three-Year
-- direct-entry or combined-honours variants.
-- =============================================================================

delete from public.course_outlines
 where institution = 'University of Nigeria, Nsukka'
   and department = 'Physics and Astronomy';

insert into public.course_outlines
  (course_code, course_title, institution, faculty, department, level,
   semester, credit_units, description, topics, contributor_name)
values
  ('PHY 111', 'General Physics for Life Sciences I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'first', 2, 'Units and dimension. Scalars and vectors. Linear and circular motion, velocity, acceleration. Laws of mechanics and gravitation; simple applications. Conservation of energy, momentum. Work and power. Simple harmonic motion, simple pendulum. Moment of inertia, Angular momentum; centrifugal and centripetal forces; centrifuges. Elasticity, Hooke''s Law, Young''s modulus. Fluids, pressure, surface tension, velocity, osmosis; blood pressure and its measurement.', '["Units and dimension", "Scalars and vectors", "Linear and circular motion, velocity, acceleration", "Laws of mechanics and gravitation", "Simple applications", "Conservation of energy, momentum", "Work and power", "Simple harmonic motion, simple pendulum", "Moment of inertia, Angular momentum", "Centrifugal and centripetal forces", "Centrifuges", "Elasticity, Hooke''s Law, Young''s modulus", "Fluids, pressure, surface tension, velocity, osmosis", "Blood pressure and its measurement"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 112', 'General Physics for Life Sciences II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'second', 2, 'Concepts of heat, temperature: measurement of temperature, clinical thermometer. Heat capacity, specific heat, latent heat, calorimetry. Gas laws; kinetic theory of gases. Thermal energy, isothermal and adiabatic changes. Conduction, convection; radiation. Sound waves; intensity, pitch and quality of sound. Propagation of sound in solids, liquids and gases. Doppler Effect. The ear. Reflection and refraction of light; plane and spherical mirrors, thin lenses; optical instruments. The eye, defects of vision and their corrections. Wave nature of light, interference, diffraction: Velocity of light.', '["Concepts of heat, temperature: measurement of temperature, clinical thermometer", "Heat capacity, specific heat, latent heat, calorimetry", "Gas laws", "Kinetic theory of gases", "Thermal energy, isothermal and adiabatic changes", "Conduction, convection", "Radiation", "Sound waves", "Intensity, pitch and quality of sound", "Propagation of sound in solids, liquids and gases", "Doppler Effect", "The ear", "Reflection and refraction of light", "Plane and spherical mirrors, thin lenses", "Optical instruments", "The eye, defects of vision and their corrections", "Wave nature of light, interference, diffraction: Velocity of light"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 114', 'General Physics for Life Sciences III', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'second', 2, 'Electric charge, Coulomb''s Law, electric field, Electrostatic potential. Energy in electric field, capacitors. Dielectrics. Electric current, potential difference and electromotive force. Ohm''s Law: potentiometer, Metre Bridge, Wheatstone bridge. Magnetic effects of currents; permanent magnetism, earth''s magnetic field. Faraday''s Law of induction, generators and electric motor. Alternating currents; Maxwell''s equations. Structure of the atom. Radioactivity, X-rays, applications in life sciences. Nuclear energy.', '["Electric charge, Coulomb''s Law, electric field, Electrostatic potential", "Energy in electric field, capacitors", "Dielectrics", "Electric current, potential difference and electromotive force", "Ohm''s Law: potentiometer, Metre Bridge, Wheatstone bridge", "Magnetic effects of currents", "Permanent magnetism, earth''s magnetic field", "Faraday''s Law of induction, generators and electric motor", "Alternating currents", "Maxwell''s equations", "Structure of the atom", "Radioactivity, X-rays, applications in life sciences", "Nuclear energy"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 115', 'General Physics for Physical Sciences I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'first', 2, 'Units and dimensions. Elements of vector algebra. Kinematics, linear and circular motion. Laws of mechanics and gravitation, simple applications, motion of planets. Conservation laws, energy, momentum; work and power. Rigid bodies, moment of inertia. Angular momentum. Simple harmonic motion, simple and compound pendulums, damped and forced vibrations. Elasticity, moduli of elasticity, bending moments, fluid mechanics.', '["Units and dimensions", "Elements of vector algebra", "Kinematics, linear and circular motion", "Laws of mechanics and gravitation, simple applications, motion of planets", "Conservation laws, energy, momentum", "Work and power", "Rigid bodies, moment of inertia", "Angular momentum", "Simple harmonic motion, simple and compound pendulums, damped and forced vibrations", "Elasticity, moduli of elasticity, bending moments, fluid mechanics"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 116', 'General Physics for Physical Sciences II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'second', 2, 'Temperature and its measurement. Heat capacity, specific heat, latent heats, critical points. Calorimetry. Gas laws; kinetic theory of gases; thermal energy, work done by expanding gases; laws of thermodynamics. Liquefaction of gases. Heat transfer: conduction, convection, radiation. Longitudinal and transverse waves; vibrations in solids. Sound waves in solids, liquids, gases; pitch, intensity and quality of sound. Doppler Effect. Acoustics of buildings. Ultrasonics. Reflection and refraction of light; spherical mirrors; thin and thick lenses; optical instruments. Wave nature of light; interference, diffraction, polarization. Velocity of light.', '["Temperature and its measurement", "Heat capacity, specific heat, latent heats, critical points", "Calorimetry", "Gas laws", "Kinetic theory of gases", "Thermal energy, work done by expanding gases", "Laws of thermodynamics", "Liquefaction of gases", "Heat transfer: conduction, convection, radiation", "Longitudinal and transverse waves", "Vibrations in solids", "Sound waves in solids, liquids, gases", "Pitch, intensity and quality of sound", "Doppler Effect", "Acoustics of buildings", "Ultrasonics", "Reflection and refraction of light", "Spherical mirrors", "Thin and thick lenses", "Optical instruments", "Wave nature of light", "Interference, diffraction, polarization", "Velocity of light"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 118', 'General Physics for Physical Sciences III', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'second', 2, 'Electrostatics; Coulomb''s law, electric field, Gauss''s law, electrostatic potential, fields due to simple charge distributions. Energy in electric fields, capacitance. Dielectrics, polarization. Electric current, Ohm''s law. Elements of circuit theory. Thermoelectric effect. Magnetic effects of current. Ampere''s law, fields due to simple circuits. Permanent magnetism, Earth''s magnetic field; ferromagnetism, moving coil instruments. Faraday''s law of induction; generators, electric motors. Alternating current. Maxwell''s equations. Elements of atomic and nuclear physics.', '["Electrostatics", "Coulomb''s law, electric field, Gauss''s law, electrostatic potential, fields due to simple charge distributions", "Energy in electric fields, capacitance", "Dielectrics, polarization", "Electric current, Ohm''s law", "Elements of circuit theory", "Thermoelectric effect", "Magnetic effects of current", "Ampere''s law, fields due to simple circuits", "Permanent magnetism, Earth''s magnetic field", "Ferromagnetism, moving coil instruments", "Faraday''s law of induction", "Generators, electric motors", "Alternating current", "Maxwell''s equations", "Elements of atomic and nuclear physics"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 121', 'Fundamentals of Physics I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'first', 3, 'Units and dimensions. Vector algebra. Kinematics and dynamics of a mass point; laws of mechanics and gravitation, Kepler''s Laws. Motion of rigid bodies, moment of inertia; angular momentum - conservation laws. Simple Harmonic motion. Elastic properties of solids, moduli of elasticity. Surface tension, viscosity. Fluid mechanics and hydrodynamics. Ideal gas laws. Kinetic theory of gases.', '["Units and dimensions", "Vector algebra", "Kinematics and dynamics of a mass point", "Laws of mechanics and gravitation, Kepler''s Laws", "Motion of rigid bodies, moment of inertia", "Angular momentum - conservation laws", "Simple Harmonic motion", "Elastic properties of solids, moduli of elasticity", "Surface tension, viscosity", "Fluid mechanics and hydrodynamics", "Ideal gas laws", "Kinetic theory of gases"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 122', 'Fundamentals of Physics II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'second', 3, 'Heat and temperature. Calorimetry. Laws of thermodynamics. Change of state - Critical points. Heat transfer; conduction, convection and radiation. Blackbody radiation. Wave motions, longitudinal and transverse waves. Superposition of waves, interference and diffraction. Propagation of waves in material media, vibrations in solids; sound wave. Wave theory of light, polarization of light. Rectilinear propagation of light, reflection, refraction; mirrors and lenses, lens combinations, optical instruments. Doppler Effect.', '["Heat and temperature", "Calorimetry", "Laws of thermodynamics", "Change of state - Critical points", "Heat transfer", "Conduction, convection and radiation", "Blackbody radiation", "Wave motions, longitudinal and transverse waves", "Superposition of waves, interference and diffraction", "Propagation of waves in material media, vibrations in solids", "Sound wave", "Wave theory of light, polarization of light", "Rectilinear propagation of light, reflection, refraction", "Mirrors and lenses, lens combinations, optical instruments", "Doppler Effect"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 124', 'Fundamentals of Physics III', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'second', 3, 'Electrostatics; Coulomb''s Law, Gauss''s Law: simple applications. Electric field, electrostatic potential. Energy in electric field, capacitance. Insulators, conductors, dielectrics; polarization. Electric current. Ohm''s law, circuit analysis. Thermoelectricity. Magnetic effects of currents, Ampere''s law, Applications. Permanent magnetism, Earth''s magnetic field. Faraday''s law of induction. Maxwell''s equations. Alternating currents. A.C. circuits. Measuring devices. Motion of a charged particle in electric and magnetic fields, hall effect. Atomic and Nuclear structure. Nuclear fission and fusion. Nuclear reactors.', '["Electrostatics", "Coulomb''s Law, Gauss''s Law: simple applications", "Electric field, electrostatic potential", "Energy in electric field, capacitance", "Insulators, conductors, dielectrics", "Polarization", "Electric current", "Ohm''s law, circuit analysis", "Thermoelectricity", "Magnetic effects of currents, Ampere''s law, Applications", "Permanent magnetism, Earth''s magnetic field", "Faraday''s law of induction", "Maxwell''s equations", "Alternating currents", "A.C", "Circuits", "Measuring devices", "Motion of a charged particle in electric and magnetic fields, hall effect", "Atomic and Nuclear structure", "Nuclear fission and fusion", "Nuclear reactors"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 191', 'Practical Physics I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'first', 2, 'Selected experiments from the 100-Level courses in Physics for service courses.', '["Selected experiments from the 100-Level courses in Physics for service courses"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 195', 'Practical Physics II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'first', 2, 'Selected experiments from the 100-Level courses in Physics for Physics majors and Engineering students.', '["Selected experiments from the 100-Level courses in Physics for Physics majors and Engineering students"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 196', 'Practical Physics III', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'second', 2, 'Selected experiments from the 100-Level courses in Physics for Physics majors.', '["Selected experiments from the 100-Level courses in Physics for Physics majors"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 211', 'Structure of Matter', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '200 Level', 'first', 3, 'Structure of Solids, basic crystal structures, space lattice. Primitive cells and Brillouin zones, Bragg''s law of reflection for X-rays. Types of crystals, crystal binding and mechanical properties, theory of elasticity. Fluid mechanics, equation of continuity, supersonic flow. Kinetic theory of gases, Maxwell-Boltzmann distribution law; specific heat of gases; thermal conductivity, viscosity and diffusion of gases; gases at low pressures; Van der Waals equation. Brownian motion.

Prerequisite: PHY 121 and PHY 122', '["Structure of Solids, basic crystal structures, space lattice", "Primitive cells and Brillouin zones, Bragg''s law of reflection for X-rays", "Types of crystals, crystal binding and mechanical properties, theory of elasticity", "Fluid mechanics, equation of continuity, supersonic flow", "Kinetic theory of gases, Maxwell-Boltzmann distribution law", "Specific heat of gases", "Thermal conductivity, viscosity and diffusion of gases", "Gases at low pressures", "Van der Waals equation", "Brownian motion"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 221', 'Mechanics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '200 Level', 'first', 2, 'Kinetics and mechanics of many particle systems; angular momentum. Dynamics of rigid bodies, moment of inertia; asymmetrical top gyroscope. Central forces; gravitational potential problem, Kepler''s laws of planetary motion. Inertial frames, Galilean transformations; Coriolis force. Constancy of speed of light. Lorentz transformation, length contraction and time dilation, Einstein''s mass-energy relation.

Prerequisite: PHY 115 and PHY 121', '["Kinetics and mechanics of many particle systems", "Angular momentum", "Dynamics of rigid bodies, moment of inertia", "Asymmetrical top gyroscope", "Central forces", "Gravitational potential problem, Kepler''s laws of planetary motion", "Inertial frames, Galilean transformations", "Coriolis force", "Constancy of speed of light", "Lorentz transformation, length contraction and time dilation, Einstein''s mass-energy relation"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 242', 'Waves', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '200 Level', 'second', 3, 'General properties of wave motion, longitudinal and transverse waves, polarization of transverse waves, progressive and standing waves, interference of waves. Propagation of waves: effect of medium, dispersion, phase and group velocity, attenuation of waves. Wave equations, various solutions; reflection and refraction of waves. Vibrating strings, longitudinal waves in metal bar; free and forced vibrations, resonance. Coupled systems. Fourier analysis. Elastic waves in solids. Interference and diffraction of light, interferometers, diffraction gratings, polarization of light - production and analysis of polarized light.

Prerequisite: PHY 116 or PHY 122', '["General properties of wave motion, longitudinal and transverse waves, polarization of transverse waves, progressive and standing waves, interference of waves", "Propagation of waves: effect of medium, dispersion, phase and group velocity, attenuation of waves", "Wave equations, various solutions", "Reflection and refraction of waves", "Vibrating strings, longitudinal waves in metal bar", "Free and forced vibrations, resonance", "Coupled systems", "Fourier analysis", "Elastic waves in solids", "Interference and diffraction of light, interferometers, diffraction gratings, polarization of light - production and analysis of polarized light"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 243', 'Physical Optics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '200 Level', 'first', 3, 'Interference of light, types of fringes, division of wave front, Fresnel''s biprism, Rayleigh refractometer, division of amplitude, interference in thin films, Newton''s rings, Michelson interferometer, multiple beam interferometer, Fabry-Perot interferometer, interference filters. Diffraction; Fraunhofer diffraction, diffraction at a straight edge and at a circular aperture; zone plate, Cornu''s spiral. Analysis of polarized light, optical activity, phase contrast microscope.

Prerequisite: PHY 116 or PHY 122', '["Interference of light, types of fringes, division of wave front, Fresnel''s biprism, Rayleigh refractometer, division of amplitude, interference in thin films, Newton''s rings, Michelson interferometer, multiple beam interferometer, Fabry-Perot interferometer, interference filters", "Diffraction", "Fraunhofer diffraction, diffraction at a straight edge and at a circular aperture", "Zone plate, Cornu''s spiral", "Analysis of polarized light, optical activity, phase contrast microscope"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 251', 'Electromagnetism', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '200 Level', 'first', 2, 'Electrostatics. Gauss'' Law. Fields of charge distribution, methods of images. Dielectrics, Polarization. Electric current, current density. D.C. network theory. Ampere''s Law, magnetic fields of simple circuits. Faraday''s law of induction, self and mutual inductances, inductively coupled circuits. Transients in capacitive and inductive circuits. A.C. circuit analysis. Magnetization and hysteresis. Permanent magnetism - Diamagnetism, Paramagnetism and ferromagnetism. Lorentz force. Hall Effect. Maxwell''s equation - electromagnetic waves.

Prerequisite: PHY 118 or PHY 124', '["Electrostatics", "Gauss'' Law", "Fields of charge distribution, methods of images", "Dielectrics, Polarization", "Electric current, current density", "D.C", "Network theory", "Ampere''s Law, magnetic fields of simple circuits", "Faraday''s law of induction, self and mutual inductances, inductively coupled circuits", "Transients in capacitive and inductive circuits", "A.C", "Circuit analysis", "Magnetization and hysteresis", "Permanent magnetism - Diamagnetism, Paramagnetism and ferromagnetism", "Lorentz force", "Hall Effect", "Maxwell''s equation - electromagnetic waves"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 262', 'Introduction to Atomic and Nuclear Physics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '200 Level', 'second', 3, 'Experimental tests of inadequacies of classical physics, concept of quanta wave-particle duality. From Bohr hypothesis to foundation of quantum mechanics. Concept of spin - Pauli''s exclusion principle. Introduction to atomic and molecular spectra. X-rays. Lasers. Radioactivity - Structure of nuclei. Nuclear fission and fusion. Nuclear reactors. Feasibility of fusion power; Detectors. Accelerators.', '["Experimental tests of inadequacies of classical physics, concept of quanta wave-particle duality", "From Bohr hypothesis to foundation of quantum mechanics", "Concept of spin - Pauli''s exclusion principle", "Introduction to atomic and molecular spectra", "X-rays", "Lasers", "Radioactivity - Structure of nuclei", "Nuclear fission and fusion", "Nuclear reactors", "Feasibility of fusion power", "Detectors", "Accelerators"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 292', 'Practical Physics IV', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '200 Level', 'second', 2, 'Selected experiments from the 200-Level Physics Courses.

Prerequisite: PHY 195 and PHY 196', '["Selected experiments from the 200-Level Physics Courses"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 301', 'Methods of Theoretical Physics I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'first', 2, 'Rotation and Translations in three dimensional space, coordinate transformations; curvilinear coordinates. Basic properties of matrices and determinants. Cauchy-Riemann relations, Partial Differentiation and double integrals. Power series. Complex variables, Argand diagram, Cauchy''s theorem, residue theorem and contour integration applied to problems in physics. Fourier analysis, Fourier transforms and their applications to problems in Physics.', '["Rotation and Translations in three dimensional space, coordinate transformations", "Curvilinear coordinates", "Basic properties of matrices and determinants", "Cauchy-Riemann relations, Partial Differentiation and double integrals", "Power series", "Complex variables, Argand diagram, Cauchy''s theorem, residue theorem and contour integration applied to problems in physics", "Fourier analysis, Fourier transforms and their applications to problems in Physics"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 302', 'Methods of Theoretical Physics II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'second', 2, 'Dimensional Analysis and applications. First and second order partial differential Equations in Physics. Heat diffusion equation; wave equations. Methods of Solution; Separation of variables, Laplace transform, eigenvalues and eigenfunctions. Special functions: Bessel Functions, Legendre and Hermite Polynomials, Spherical Harmonics, Beta and Gamma Functions and their applications.', '["Dimensional Analysis and applications", "First and second order partial differential Equations in Physics", "Heat diffusion equation", "Wave equations", "Methods of Solution", "Separation of variables, Laplace transform, eigenvalues and eigenfunctions", "Special functions: Bessel Functions, Legendre and Hermite Polynomials, Spherical Harmonics, Beta and Gamma Functions and their applications"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 311', 'Solid State Physics I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'first', 2, 'Crystal structure of solids, space lattices, primitive cells and Brillouin zones; Miller indices, structure factor. Crystal diffraction by X-rays and neutrons, the reciprocal lattice; crystal binding and mechanical properties of solids. Theory of elasticity; lattice vibrations of monatomic and diatomic chains; free electron theory of metals.', '["Crystal structure of solids, space lattices, primitive cells and Brillouin zones", "Miller indices, structure factor", "Crystal diffraction by X-rays and neutrons, the reciprocal lattice", "Crystal binding and mechanical properties of solids", "Theory of elasticity", "Lattice vibrations of monatomic and diatomic chains", "Free electron theory of metals"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 321', 'Relativity Physics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'first', 2, 'Galilean transformations, Michelson-Morley experiment, limitations of classical mechanics. Constancy of velocity of light; Lorentz transformations, time dilation, length contraction, simultaneity of events, relativistic addition of velocities. Doppler Effect. Relativistic kinematics, mass-energy equivalence. Four vectors, relativistic invariance, invariance of Maxwell''s equations.

Prerequisite: PHY 221', '["Galilean transformations, Michelson-Morley experiment, limitations of classical mechanics", "Constancy of velocity of light", "Lorentz transformations, time dilation, length contraction, simultaneity of events, relativistic addition of velocities", "Doppler Effect", "Relativistic kinematics, mass-energy equivalence", "Four vectors, relativistic invariance, invariance of Maxwell''s equations"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 331', 'Thermal Physics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'first', 3, 'First and second laws of thermodynamics and its applications, reversible and irreversible processes, Carnot''s cycle, heat engines, isothermal and adiabatic expansion. Thermodynamic potentials, Maxwell''s relations. Entropy, Third law of thermodynamics. Joule-Kelvin effect, refrigeration. Equation of state of perfect gas; Maxwell-Boltzmann statistics; Partition function; Equipartition theorem. Low temperature Physics. Black body radiation.

Prerequisite: PHY 122', '["First and second laws of thermodynamics and its applications, reversible and irreversible processes, Carnot''s cycle, heat engines, isothermal and adiabatic expansion", "Thermodynamic potentials, Maxwell''s relations", "Entropy, Third law of thermodynamics", "Joule-Kelvin effect, refrigeration", "Equation of state of perfect gas", "Maxwell-Boltzmann statistics", "Partition function", "Equipartition theorem", "Low temperature Physics", "Black body radiation"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 351', 'Electronics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'first', 2, 'Electronic device characteristics, equivalent circuit; various types of amplifiers, frequency and phase response, distortion, feedback oscillators. Semi-conductor theory and devices, characteristics; Lasers and Masers; four terminal network; equivalent circuits. Communication systems; modulation, a.m., f.m., single side band; demodulation. Elements of logic circuitry. Analog to digital conversion. Computers.

Prerequisite: PHY 251', '["Electronic device characteristics, equivalent circuit", "Various types of amplifiers, frequency and phase response, distortion, feedback oscillators", "Semi-conductor theory and devices, characteristics", "Lasers and Masers", "Four terminal network", "Equivalent circuits", "Communication systems", "Modulation, a.m., f.m., single side band", "Demodulation", "Elements of logic circuitry", "Analog to digital conversion", "Computers"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 362', 'Quantum Mechanics I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'second', 3, 'Wave-particle duality. Fundamental postulates of quantum mechanics, Heisenberg''s uncertainty principle, statistical interpretation of wave functions. Correspondence principle: Hamilton-Jacobi equations, Schrodinger''s equation, application to one dimensional time independent problems. Central force problems, angular momentum and radial quantum numbers of hydrogen like atoms. Introduction to scattering theory.', '["Wave-particle duality", "Fundamental postulates of quantum mechanics, Heisenberg''s uncertainty principle, statistical interpretation of wave functions", "Correspondence principle: Hamilton-Jacobi equations, Schrodinger''s equation, application to one dimensional time independent problems", "Central force problems, angular momentum and radial quantum numbers of hydrogen like atoms", "Introduction to scattering theory"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 382', 'An Introduction to Astronomy', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'second', 3, 'Astronomical units of mass, distance and time. Optical and radio-telescopes, observatories in space. Limitations due to nature of electromagnetic waves. Solar system, physics of planets and satellites, formation of planets, origin of the solar system. Stars, distances, brightness, colours, luminosity, stellar types, spectra, stellar masses and dimensions, stellar evolution. Hertzsprung-Russell diagram, exploding stars, supernova, neutron stars, pulsars, black holes. Galaxies, the milky way, classification of galaxies, abnormal galaxies, quasars, isotropy and homogeneity of the universe, models of the universe. Extra terrestrial life.', '["Astronomical units of mass, distance and time", "Optical and radio-telescopes, observatories in space", "Limitations due to nature of electromagnetic waves", "Solar system, physics of planets and satellites, formation of planets, origin of the solar system", "Stars, distances, brightness, colours, luminosity, stellar types, spectra, stellar masses and dimensions, stellar evolution", "Hertzsprung-Russell diagram, exploding stars, supernova, neutron stars, pulsars, black holes", "Galaxies, the milky way, classification of galaxies, abnormal galaxies, quasars, isotropy and homogeneity of the universe, models of the universe", "Extra terrestrial life"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 391', 'Practical Physics V', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'first', 2, 'Selected experiments from the 300-Level Physics Courses.

Prerequisite: PHY 292', '["Selected experiments from the 300-Level Physics Courses"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 392', 'Practical Physics VI', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'second', 2, 'Selected experiments from the 300-Level Physics Courses.

Prerequisite: PHY 391', '["Selected experiments from the 300-Level Physics Courses"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 393', 'Workshop Course I (Mechanical)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'first', 2, 'Safety precautions in mechanical workshop/industries. Units and measurements. Materials and properties of various mechanical hand tools - hand files, hacksaw, drills, etc. Use of machine tools and operations: lathe machines, drilling machine, power hacksaw etc. Welding and fabrication practice. Wood working practice project. Technical drawing: Introduction to technical drawing, geometrical construction, isometric and oblique drawings. Orthographic projections - 1st and 3rd angle projections. Maintenance and repairs of machine tools. Gear and threads.', '["Safety precautions in mechanical workshop/industries", "Units and measurements", "Materials and properties of various mechanical hand tools - hand files, hacksaw, drills, etc", "Use of machine tools and operations: lathe machines, drilling machine, power hacksaw etc", "Welding and fabrication practice", "Wood working practice project", "Technical drawing: Introduction to technical drawing, geometrical construction, isometric and oblique drawings", "Orthographic projections - 1st and 3rd angle projections", "Maintenance and repairs of machine tools", "Gear and threads"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 394', 'Workshop Course II (Electronics)', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'second', 2, 'Safety precautions in electronic workshop/industries. Units and measurements, identification of tools, electronic symbols and electronic components; colour codes in resistors and capacitors; soldering techniques, circuit designs and wiring. Use of test equipment like multimeters, oscilloscopes, signal generators. Design and construction of power supply units, amplifiers, P.S.U. and phase shift oscillator. Production line. Role of computers. Projects.', '["Safety precautions in electronic workshop/industries", "Units and measurements, identification of tools, electronic symbols and electronic components", "Colour codes in resistors and capacitors", "Soldering techniques, circuit designs and wiring", "Use of test equipment like multimeters, oscilloscopes, signal generators", "Design and construction of power supply units, amplifiers, P.S.U", "And phase shift oscillator", "Production line", "Role of computers", "Projects"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 396', 'Measurement and Instrumentation', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'second', 2, 'Measurements, nature, design of experiments, scale. Voltage and current measurements, voltmeters, measurement of A.C. voltage, average peak to peak response and r.m.s detectors, digital alternating current probes. Frequency and time measurements, standards, time signal broadcasts, frequency synthesizer. Signal analysis, digital analysis, digital techniques, Fourier transform methods, signal statistics. Types of sensors; solid state, electrolytic, gaseous, ion, capacitor, magnetic induction, electronic induction and electronic sensors, various types of recorders. Basic principles of design and maintenance of instruments.', '["Measurements, nature, design of experiments, scale", "Voltage and current measurements, voltmeters, measurement of A.C", "Voltage, average peak to peak response and r.m.s detectors, digital alternating current probes", "Frequency and time measurements, standards, time signal broadcasts, frequency synthesizer", "Signal analysis, digital analysis, digital techniques, Fourier transform methods, signal statistics", "Types of sensors", "Solid state, electrolytic, gaseous, ion, capacitor, magnetic induction, electronic induction and electronic sensors, various types of recorders", "Basic principles of design and maintenance of instruments"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 401', 'Computational Physics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'first', 2, 'Use of numerical methods in physics, methods of solving non-linear equations, various methods of numerical integrations, differentiations; numerical solutions of some differential equations using computers, computer programming, use of flow diagrams, programming practice using some problems in physics; Statistical analysis of experimental data. Computer programming in Fortran and C or C++.', '["Use of numerical methods in physics, methods of solving non-linear equations, various methods of numerical integrations, differentiations", "Numerical solutions of some differential equations using computers, computer programming, use of flow diagrams, programming practice using some problems in physics", "Statistical analysis of experimental data", "Computer programming in Fortran and C or C++"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 403', 'General Physics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'first', 2, 'Review of the five integrated themes in Physics, namely: Concepts of space, time and motion; Conservation Principles - Energy, charge, angular momentum etc; Fields - gravitational, magnetic, electrostatic; Waves; and Quanta. Solution of simple problems on the above topics.', '["Review of the five integrated themes in Physics, namely: Concepts of space, time and motion", "Conservation Principles - Energy, charge, angular momentum etc", "Fields - gravitational, magnetic, electrostatic", "Waves", "And Quanta", "Solution of simple problems on the above topics"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 415', 'Science of Materials', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'first', 2, 'General Introduction of materials, Engineering requirements. Mechanical properties of materials, study stress, strain, ductility, hardness, toughness and fatigue. Crystal classes and system; macroscopic, microscopic investigations of materials by electron microscope and x-ray diffraction techniques. Crystal imperfections, vacancies, dislocations, stacking faults and grain boundaries, slip and twisting effect, defects as properties of materials. Single phase and multiphase materials, solid solutions. Binary eutectic and noneutectic mixtures. Ferrous and non-ferrous metals, steel. Polymers, classification, properties, fabrication. Ceramics; structure, composition, forming and shaping, stability of materials.', '["General Introduction of materials, Engineering requirements", "Mechanical properties of materials, study stress, strain, ductility, hardness, toughness and fatigue", "Crystal classes and system", "Macroscopic, microscopic investigations of materials by electron microscope and x-ray diffraction techniques", "Crystal imperfections, vacancies, dislocations, stacking faults and grain boundaries, slip and twisting effect, defects as properties of materials", "Single phase and multiphase materials, solid solutions", "Binary eutectic and noneutectic mixtures", "Ferrous and non-ferrous metals, steel", "Polymers, classification, properties, fabrication", "Ceramics", "Structure, composition, forming and shaping, stability of materials"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 416', 'Solid State Physics II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'second', 2, 'Nearly free electron theory of solids, band theory of solids; metals, insulators and semiconductors, effective mass, Fermi surfaces, electrons and holes in semiconductors, magnetic properties of materials - concepts, diamagnetism, paramagnetism, ferromagnetism, magnetic anisotropy and magnetostriction, superconductivity, electrical and thermal properties. Defects in solids, Lasers and Masers.', '["Nearly free electron theory of solids, band theory of solids", "Metals, insulators and semiconductors, effective mass, Fermi surfaces, electrons and holes in semiconductors, magnetic properties of materials - concepts, diamagnetism, paramagnetism, ferromagnetism, magnetic anisotropy and magnetostriction, superconductivity, electrical and thermal properties", "Defects in solids, Lasers and Masers"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 418', 'Physical Metallurgy', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'second', 2, 'Sources and methods of production of metals and alloys. Effects of heat treatment, irradiation, deformation on the physical properties of metals. Theory of metal alloys. Binary and ternary systems of refracting and rare earth metals. Melting, casting, pressure working and heat treatment of metals, alloys, welding and soldering. Single crystals of metals and alloys; methods of growing, dispersion substructure. Optical and x-ray metallography; ultrasonic examination of metals and alloys. Physical metallurgy of steel. Applications.', '["Sources and methods of production of metals and alloys", "Effects of heat treatment, irradiation, deformation on the physical properties of metals", "Theory of metal alloys", "Binary and ternary systems of refracting and rare earth metals", "Melting, casting, pressure working and heat treatment of metals, alloys, welding and soldering", "Single crystals of metals and alloys", "Methods of growing, dispersion substructure", "Optical and x-ray metallography", "Ultrasonic examination of metals and alloys", "Physical metallurgy of steel", "Applications"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 421', 'Analytical Mechanics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'first', 3, '$N$-particle systems; generalized coordinates; d''Alembert''s principle, Lagrangian formulation; Hamiltonian formulation; Hamilton-Jacobi equations. Canonical transformations, generators, Poisson brackets. Jacobi identity. Continuous systems; classical theory of fields. Small vibrations.

Prerequisite: PHY 221', '["$N$-particle systems", "Generalized coordinates", "D''Alembert''s principle, Lagrangian formulation", "Hamiltonian formulation", "Hamilton-Jacobi equations", "Canonical transformations, generators, Poisson brackets", "Jacobi identity", "Continuous systems", "Classical theory of fields", "Small vibrations"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 438', 'Statistical Physics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'second', 2, 'The perfect classical gas, equation of state; partition function; Maxwell-Boltzmann, Bose-Einstein and Fermi-Dirac Statistics, Einstein-Debye theory of specific heats of solids. Liquefaction of gases; liquid helium, superfluidity, Bose-Einstein condensation, Production of low temperatures. Nuclear demagnetization. Negative temperatures. Gas, Kelvin and magnetic temperature scales. Thermal properties of superconductors, Ordinary and high-temperature superconductors.

Prerequisite: PHY 331', '["The perfect classical gas, equation of state", "Partition function", "Maxwell-Boltzmann, Bose-Einstein and Fermi-Dirac Statistics, Einstein-Debye theory of specific heats of solids", "Liquefaction of gases", "Liquid helium, superfluidity, Bose-Einstein condensation, Production of low temperatures", "Nuclear demagnetization", "Negative temperatures", "Gas, Kelvin and magnetic temperature scales", "Thermal properties of superconductors, Ordinary and high-temperature superconductors"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 441', 'Solar Energy I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'first', 2, 'Development of alternative energy sources - Solar, wind, geothermal and others. Survey of current solar energy activities and applications, solar radiation, radiation measuring instrument. The basic flat plate collector, selective surfaces, antireflective coatings, collector designs, thermal energy storage, high density batteries and fuel cells, solar houses, heat engines, thermal electric power generation, cooling and refrigeration, solar ponds, distillation. Design, performance and economics of solar system. Demonstration projects.', '["Development of alternative energy sources - Solar, wind, geothermal and others", "Survey of current solar energy activities and applications, solar radiation, radiation measuring instrument", "The basic flat plate collector, selective surfaces, antireflective coatings, collector designs, thermal energy storage, high density batteries and fuel cells, solar houses, heat engines, thermal electric power generation, cooling and refrigeration, solar ponds, distillation", "Design, performance and economics of solar system", "Demonstration projects"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 442', 'Solar Energy II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'second', 2, 'Photoconductivity in solids, photo emission, photovoltaic generation of e.m.f, photovoltaic cells. Amorphous photovoltaic cells and energy storage. Design performance and economics of solar photovoltaic systems. Measurements and instrumentation for photovoltaic system. Applications of photovoltaic in industry and agriculture.', '["Photoconductivity in solids, photo emission, photovoltaic generation of e.m.f, photovoltaic cells", "Amorphous photovoltaic cells and energy storage", "Design performance and economics of solar photovoltaic systems", "Measurements and instrumentation for photovoltaic system", "Applications of photovoltaic in industry and agriculture"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 443', 'Biomass Energy', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'first', 2, 'Photosynthesis, Chemical processes and energy storage in plants. Fuel wood, animal waste, manufacture of synthetic fuel, e.g. methanol, from biomass oxidation and hydrolysis of fuels. Wood stoves and burners. Desertification and fuel wood conservation.', '["Photosynthesis, Chemical processes and energy storage in plants", "Fuel wood, animal waste, manufacture of synthetic fuel, e.g", "Methanol, from biomass oxidation and hydrolysis of fuels", "Wood stoves and burners", "Desertification and fuel wood conservation"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 444', 'Fossil Energy', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'second', 2, 'Conventional sources of energy - petroleum and gas, coal, hydroelectric and thermal power stations. Petroleum exploration, mining and refining. Design, operation and economics of conventional fossil energy conversion and conversion systems. Turbines, generators, boilers and internal combustion engines. Energy consumption in industry, transportation, and other sectors.', '["Conventional sources of energy - petroleum and gas, coal, hydroelectric and thermal power stations", "Petroleum exploration, mining and refining", "Design, operation and economics of conventional fossil energy conversion and conversion systems", "Turbines, generators, boilers and internal combustion engines", "Energy consumption in industry, transportation, and other sectors"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 445', 'Nuclear Energy I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'first', 2, 'Nuclear reactions, cross-sections, theory of beta decay. Nuclear fission: properties and relation to nuclear power. Slowing down of neutrons in media, neutron induced chain reactions. Various nuclear models. Nuclear fusion - thermo-nuclear reactions. Nuclear instrumentation. Radiation protection and control. Sources of nuclear materials.', '["Nuclear reactions, cross-sections, theory of beta decay", "Nuclear fission: properties and relation to nuclear power", "Slowing down of neutrons in media, neutron induced chain reactions", "Various nuclear models", "Nuclear fusion - thermo-nuclear reactions", "Nuclear instrumentation", "Radiation protection and control", "Sources of nuclear materials"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 446', 'Nuclear Energy II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'second', 2, 'Basic reactor designs - light and heavy water reactors, molten salt breeder reactors, high temperature gas cooled reactors, power plant thermodynamics, reactor heat generation and removal. Basic plasma physics - magnetohydrodynamic equation.', '["Basic reactor designs - light and heavy water reactors, molten salt breeder reactors, high temperature gas cooled reactors, power plant thermodynamics, reactor heat generation and removal", "Basic plasma physics - magnetohydrodynamic equation"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 451', 'Electromagnetic Theory', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'first', 2, 'Maxwell''s equations, Poynting vector, propagation of electromagnetic waves, polarization, reflection and refraction of electromagnetic waves. Retarded and advanced potentials. Transmission lines, wave guides, resonant cavities. Antenna, antenna arrays. Radiation from moving charges.

Prerequisite: PHY 251', '["Maxwell''s equations, Poynting vector, propagation of electromagnetic waves, polarization, reflection and refraction of electromagnetic waves", "Retarded and advanced potentials", "Transmission lines, wave guides, resonant cavities", "Antenna, antenna arrays", "Radiation from moving charges"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 452', 'Industrial Electronics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'second', 2, 'Operational amplifiers, analog computers. Electronic building blocks, design of digital system. Binary codes, logic gates, logic operations. Digital computers. Solid state devices, Zener diodes, tunnel diodes, solar cells, particle counters. Telecommunications, telephony, telegraphy, telex, telemetry, antenna systems, AM and FM radio transmitters and receivers, television. Electron microscope. Electronic control of industrial processes.', '["Operational amplifiers, analog computers", "Electronic building blocks, design of digital system", "Binary codes, logic gates, logic operations", "Digital computers", "Solid state devices, Zener diodes, tunnel diodes, solar cells, particle counters", "Telecommunications, telephony, telegraphy, telex, telemetry, antenna systems, AM and FM radio transmitters and receivers, television", "Electron microscope", "Electronic control of industrial processes"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 461', 'Quantum Mechanics II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'first', 3, 'State vectors and operators in Quantum mechanics - Schrodinger, Heisenberg and interaction representations. Harmonic oscillator, using creation and annihilation operators. Angular momentum, spin and addition of angular momenta. Time independent and time dependent perturbation theories, application to laser systems. Identical particles and the spin-statistics theorem. Theory of scattering.', '["State vectors and operators in Quantum mechanics - Schrodinger, Heisenberg and interaction representations", "Harmonic oscillator, using creation and annihilation operators", "Angular momentum, spin and addition of angular momenta", "Time independent and time dependent perturbation theories, application to laser systems", "Identical particles and the spin-statistics theorem", "Theory of scattering"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 462', 'Nuclear Physics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'second', 3, 'Nuclear structure, binding, stability, the liquid drop model, the shell model. Nuclear reactions, general features, kinematics of the compound nucleus, Breit-Wigner formula, nuclear fission. Reactor Physics: chain reaction, thermalization of neutrons, moderators, neutron diffusion. Elementary particles classification, symmetry properties, basic interpretations. Particle detectors. High energy accelerators.

Prerequisite: PHY 262', '["Nuclear structure, binding, stability, the liquid drop model, the shell model", "Nuclear reactions, general features, kinematics of the compound nucleus, Breit-Wigner formula, nuclear fission", "Reactor Physics: chain reaction, thermalization of neutrons, moderators, neutron diffusion", "Elementary particles classification, symmetry properties, basic interpretations", "Particle detectors", "High energy accelerators"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 471', 'Meteorology', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'first', 2, 'Earth''s atmosphere; use of fluid dynamics; effect of rotation of the earth. Sources of atmospheric motion energy from the sun, periodic variation of solar energy. Composition of the atmosphere, different layers, effect of composition on absorption of solar energy in the atmosphere. Distribution of temperature, pressure and wind with height; diurnal and seasonal variation of temperature. Cloud formation, physics of clouds. Isotherms, isobars, weather charts. Various weather systems, land and sea breeze, monsoon, dust haze, cyclones, weather forecasting.', '["Earth''s atmosphere", "Use of fluid dynamics", "Effect of rotation of the earth", "Sources of atmospheric motion energy from the sun, periodic variation of solar energy", "Composition of the atmosphere, different layers, effect of composition on absorption of solar energy in the atmosphere", "Distribution of temperature, pressure and wind with height", "Diurnal and seasonal variation of temperature", "Cloud formation, physics of clouds", "Isotherms, isobars, weather charts", "Various weather systems, land and sea breeze, monsoon, dust haze, cyclones, weather forecasting"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 472', 'Aeronomy', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'second', 2, 'Composition of the atmosphere; temperature; ionization. Influence of the sun on the atmosphere. The neutral atmosphere, pressure, density and temperature distribution. Formation of ionized layers, Chapman theory. Propagation of electromagnetic waves in an ionized medium; Experimental techniques for probing the ionosphere. Earth''s magnetic field in space, magnetic variation, ionospheric conductivities and dynamo theory. Trapping of charged particles in the earth''s magnetic field. Magnetic storms. The equatorial ionosphere. Ionospheric irregularities. Elements of airglow and aurora.', '["Composition of the atmosphere", "Temperature", "Ionization", "Influence of the sun on the atmosphere", "The neutral atmosphere, pressure, density and temperature distribution", "Formation of ionized layers, Chapman theory", "Propagation of electromagnetic waves in an ionized medium", "Experimental techniques for probing the ionosphere", "Earth''s magnetic field in space, magnetic variation, ionospheric conductivities and dynamo theory", "Trapping of charged particles in the earth''s magnetic field", "Magnetic storms", "The equatorial ionosphere", "Ionospheric irregularities", "Elements of airglow and aurora"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 473', 'Physics of the Earth''s Interior', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'first', 2, 'Origin, shape, structure and major divisions of the earth. Radioactivity and the ages of rocks. Temperature and temperature gradients, thermal conductivity of the earth; generation of heat in the earth, heat flow through the earth''s surface. Elasticity of the earth and earth tides. The earth''s main magnetic field and distribution in space, secular variation, electrical theory of the earth''s core and origin of the main magnetic field; polar wandering; secular motion of the mean pole. Sea floor spreading, continental drift and plate tectonics.', '["Origin, shape, structure and major divisions of the earth", "Radioactivity and the ages of rocks", "Temperature and temperature gradients, thermal conductivity of the earth", "Generation of heat in the earth, heat flow through the earth''s surface", "Elasticity of the earth and earth tides", "The earth''s main magnetic field and distribution in space, secular variation, electrical theory of the earth''s core and origin of the main magnetic field", "Polar wandering", "Secular motion of the mean pole", "Sea floor spreading, continental drift and plate tectonics"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 475', 'Industrial Geophysics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'first', 2, 'Introduction to seismic; gravitational, magnetic, electrical/electromagnetic; induced polarization, logging and radioactivity methods as applied to prospecting for economic mineral deposits. Applications of geophysics in the solution of civil engineering problems.', '["Introduction to seismic", "Gravitational, magnetic, electrical/electromagnetic", "Induced polarization, logging and radioactivity methods as applied to prospecting for economic mineral deposits", "Applications of geophysics in the solution of civil engineering problems"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 485', 'Galaxies', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'first', 2, 'The Milky Way, stellar and gas content, kinetics and mass distribution, spiral structure, 21 cm line studies of galactic structure, star clusters. Radio emission from galaxies. Morphology and classification of galaxies; general properties of galaxies. Systems of galaxies, interaction between galaxies, magnetic fields. Connection between galaxies and quasi-stellar objects.', '["The Milky Way, stellar and gas content, kinetics and mass distribution, spiral structure, 21 cm line studies of galactic structure, star clusters", "Radio emission from galaxies", "Morphology and classification of galaxies", "General properties of galaxies", "Systems of galaxies, interaction between galaxies, magnetic fields", "Connection between galaxies and quasi-stellar objects"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 486', 'Stellar Structure and Evolution', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'second', 2, 'Physics of the stellar interior, equilibrium equation of stellar structure, continuity of mass, hydrostatic equilibrium, thermal equilibrium, energy production. Energy transport, radiation, conduction, convection, neutrinos; stability against convection. Equations of state; effects of degeneracy, relativity. Opacity. Energy generation, nuclear reactions in stars. Stellar models; solutions of the equation of stellar structure; polytropic, analytic, linear and numerical models. Survey of present knowledge of stellar evolution. Hertzsprung-Russell diagram.', '["Physics of the stellar interior, equilibrium equation of stellar structure, continuity of mass, hydrostatic equilibrium, thermal equilibrium, energy production", "Energy transport, radiation, conduction, convection, neutrinos", "Stability against convection", "Equations of state", "Effects of degeneracy, relativity", "Opacity", "Energy generation, nuclear reactions in stars", "Stellar models", "Solutions of the equation of stellar structure", "Polytropic, analytic, linear and numerical models", "Survey of present knowledge of stellar evolution", "Hertzsprung-Russell diagram"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 487', 'High Energy Astrophysics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'first', 2, 'X-ray, gamma-rays, high energy particles; their interactions with matter, nuclear reactions; spallation, observational techniques. Cosmic ray astrophysics; historical development; definition of rigidity; solar wind; flux freezing; solar modulation; the galaxy; diffusion loss equation for electrons in the galaxy. Synchrotron radiation, Inverse Compton scattering. Supernova, Galactic and extragalactic origin of cosmic rays, observational evidence. Acceleration of cosmic rays; Fermi mechanism; shock waves; super-novae. Shells; neutron stars and pulsars; the origin of the highest energy cosmic rays.', '["X-ray, gamma-rays, high energy particles", "Their interactions with matter, nuclear reactions", "Spallation, observational techniques", "Cosmic ray astrophysics", "Historical development", "Definition of rigidity", "Solar wind", "Flux freezing", "Solar modulation", "The galaxy", "Diffusion loss equation for electrons in the galaxy", "Synchrotron radiation, Inverse Compton scattering", "Supernova, Galactic and extragalactic origin of cosmic rays, observational evidence", "Acceleration of cosmic rays", "Fermi mechanism", "Shock waves", "Super-novae", "Shells", "Neutron stars and pulsars", "The origin of the highest energy cosmic rays"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 488', 'Modern Cosmology', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'second', 2, 'The content of the universe. The cosmological principle; Olber''s paradox; Hubble''s law; theories of gravitation, variation of the constancy of nature with time. The Robertson-Walker line elements, the dynamics of world models. Hubble''s constant, redshift-magnitude relations, source counts, the luminosity-volume tests, angular diameter-redshift tests.', '["The content of the universe", "The cosmological principle", "Olber''s paradox", "Hubble''s law", "Theories of gravitation, variation of the constancy of nature with time", "The Robertson-Walker line elements, the dynamics of world models", "Hubble''s constant, redshift-magnitude relations, source counts, the luminosity-volume tests, angular diameter-redshift tests"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 491', 'Practical Physics VII', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'first', 2, 'Selected experiments from the 400-Level Physics Courses.

Prerequisite: PHY 391 and PHY 392', '["Selected experiments from the 400-Level Physics Courses"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 492', 'Practical Physics VIII', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'second', 2, 'Selected experiments from the 400-Level Physics Courses.

Prerequisite: PHY 491', '["Selected experiments from the 400-Level Physics Courses"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('PHY 494', 'Project Report', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '400 Level', 'second', 4, 'Independent research project and comprehensive technical report under faculty supervision.', '["Independent research project and comprehensive technical report under faculty supervision"]'::jsonb, 'Department of Physics and Astronomy handbook'),
  ('MTH 111', 'General Mathematics I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'first', 3, 'Elementary Set theory, subsets, union, intersection, complements. Venn diagrams, Real numbers, integers, rational and irrational numbers, mathematical induction, real sequences and series, theory of quadratic equations, binomial theorem. Circular measure, trigonometric functions of angles of any magnitude, addition and factor formulae. Complex numbers, algebra of complex numbers, the Argand Diagram, De Moivre''s theorem, $n$th roots of unity.', '["Elementary Set theory, subsets, union, intersection, complements", "Venn diagrams, Real numbers, integers, rational and irrational numbers, mathematical induction, real sequences and series, theory of quadratic equations, binomial theorem", "Circular measure, trigonometric functions of angles of any magnitude, addition and factor formulae", "Complex numbers, algebra of complex numbers, the Argand Diagram, De Moivre''s theorem, $n$th roots of unity"]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('MTH 121', 'General Mathematics II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'first', 3, 'Functions of a real variable, graphs, limits and continuity. The derivative as limit of rate of change. Techniques of differentiation. Curve sketching, integration as an inverse of differentiation. Methods of integration, definite integrals. Application of integration to areas and volumes.', '["Functions of a real variable, graphs, limits and continuity", "The derivative as limit of rate of change", "Techniques of differentiation", "Curve sketching, integration as an inverse of differentiation", "Methods of integration, definite integrals", "Application of integration to areas and volumes"]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('CHM 101', 'Basic Principles of Chemistry I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'first', 2, 'Stoichiometry and Atomic Structure: Stoichiometry and mole concept. Introduction to atomic structure, development of electronic configuration of the elements, and valency theories. Periodic Table and Groups: The periodic classification of elements. Brief group study of representative elements, with emphasis on similarities and differences based on periodic position. Nuclear Chemistry: Radioactivity and its practical applications.', '["Stoichiometry and Atomic Structure: Stoichiometry and mole concept. Introduction to atomic structure, development of electronic configuration of the elements, and valency theories", "Periodic Table and Groups: The periodic classification of elements. Brief group study of representative elements, with emphasis on similarities and differences based on periodic position", "Nuclear Chemistry: Radioactivity and its practical applications"]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('CHM 171', 'Basic Practical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'first', 2, 'Laboratory Operations: Theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations.', '["Laboratory Operations: Theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations"]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('GSP 101', 'Use of English I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'first', 2, 'Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, The English Language and the Nigerian society, World English, Levels and Varieties of English — formal, informal, standard, etc., English in Literature and the Media.

Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes, English Language Register, diatypes and dialects.

Listening skill - The listening skill discussed as a receptive and reciprocal activity, Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening.

Reading Skill - The concept of reading as a linguistic organization and a vehicle of communication. Reading Problems, Levels of Reading, Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies (Scanning, Skimming, Phrase reading, Intensive & Extensive reading, Exploiting the topic sentence for main ideas), Reading for details, Reading for evaluation and inference, Reading with questions - SQ3R, PR3, Methods for understanding difficult words in a reading text, Literature reading for study, analysis and comment.

Speaking & Communication Skills - Nature, Process & Development, Principles of Public Speech Making and Social Interaction, The Speech Sounds of English and their Articulation, Phonetic Transcription and Practical Speech Work.

Study Techniques - Choosing study centers and discussion groups, Note-taking during lectures, and from audio-visual equipment, Note-making techniques during private reading and literature search, Summary & Transcoding Techniques, Retrieving information from notes, The dictionary as a study guide.

Basic Research Methods & Term Paper Writing - Research – meaning & nature, Types & Methodology; Data in the Research Process, The Research Report, Process and Techniques, Documentation in Research Reports: Process, Types and Methods, Abbreviations in Research Reports, The term paper as a miniature research report, Practical term paper writing.

Course Evaluation & Grading - Students must attend at least 75% of the lectures to qualify for examination in the course.', '["Man, Society and Language - The Nature, Characteristics and Functions of Language, Human Communication & Language, World English, Levels and Varieties of English", "Vocabulary of English - Types, Method of Vocabulary Development, Synonyms, Antonyms, Homonyms, Acronyms, Paronyms, Affixation and other morphological processes", "Listening skill - Nature, Types, Purposes and Factors that affect Listening, Strategies and Aids for Effective Listening", "Reading Skill - Reading Problems, Levels and Types of Reading, Causes and Remedies of Reading Failures, Reading Techniques & Strategies, Reading for evaluation and inference", "Speaking & Communication Skills - Principles of Public Speech Making and Social Interaction, Phonetic Transcription and Practical Speech Work", "Study Techniques - Note-taking, Note-making, Summary & Transcoding Techniques", "Basic Research Methods & Term Paper Writing - The Research Report, Documentation, Abbreviations, practical term paper writing"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('GSP 111', 'Use of Library', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'first', 2, 'Overview of Library: concepts, history, types and functions. Uses in academic libraries; organization of university library and library users. Library processes and procedures. Acquisition process, Cataloging and classification, LC Scheme, in-House Scheme, DDC. Serials process and circulation processes. Access tools in Library resources: Library catalogues, Indexes, Abstracts, Current contents information in the library. Reference sources: types of reference sources and services. Web resources and online resources. Overview of Databases, Online search strategies for information retrieval. Referencing and citation styles for information reporting. Concept of plagiarism. Learning skills and research skills, ICT skillsets: types of learning and information policies.', '["Overview of Library: concepts, history, types and functions. Uses in academic libraries; organization of university library and library users", "Library processes and procedures. Acquisition process, Cataloging and classification, LC Scheme, in-House Scheme, DDC. Serials process and circulation processes", "Access tools in Library resources: Library catalogues, Indexes, Abstracts, Current contents information", "Reference sources: types of reference sources and services. Web resources and online resources", "Overview of Databases, Online search strategies for information retrieval. Referencing and citation styles for information reporting. Concept of plagiarism", "Learning skills and research skills, ICT skillsets: types of learning and information policies"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MTH 122', 'General Mathematics III', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'second', 3, 'Geometric representation of vectors in 1-3 dimensions, Components, direction cosines. Addition of vectors and multiplication of vectors by a scalar, linear independence. Scalar and vector products of two vectors. Differentiation and integration of vectors with respect to a scalar variable. Two-dimensional coordinate geometry. Straight lines, circles, parabolas, ellipses, hyperbolas. Tangents and normals. Kinematics of a particle. Components of velocity and acceleration of a particle moving in a plane. Force and momentum. Newton''s laws of motion; motion under gravity, projectile motion, resisted vertical motion of a particle, elastic string, motion of a simple pendulum, impulse and impact of momentum. Impact of two smooth elastic spheres. Direct and oblique impacts.', '["Geometric representation of vectors in 1-3 dimensions, Components, direction cosines", "Addition of vectors and multiplication of vectors by a scalar, linear independence", "Scalar and vector products of two vectors", "Differentiation and integration of vectors with respect to a scalar variable", "Two-dimensional coordinate geometry", "Straight lines, circles, parabolas, ellipses, hyperbolas", "Tangents and normals", "Kinematics of a particle", "Components of velocity and acceleration of a particle moving in a plane", "Force and momentum", "Newton''s laws of motion", "Motion under gravity, projectile motion, resisted vertical motion of a particle, elastic string, motion of a simple pendulum, impulse and impact of momentum", "Impact of two smooth elastic spheres", "Direct and oblique impacts"]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('CHM 112', 'Basic Principles of Chemistry II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'second', 2, 'Gas Laws and Kinetic Theory: Kinetic theory of gases, elementary derivation and deduction of gas laws, molecular speeds, deviations from ideal behaviour, van der Waals modification, and gas liquefaction. Phase Equilibrium and Solutions: Phase transitions and phase equilibria in one-component systems. Ideal solutions, Raoult''s law, Henry''s law, real solutions, and colligative properties -- vapour pressure lowering, boiling point elevation, freezing point lowering, osmotic pressure. Thermodynamics and Kinetics: Aspects of the first law of thermodynamics, thermochemistry, entropy, free energy, and spontaneous changes. Ionic equilibria, acids, bases, indicators, and buffers. Elementary chemical kinetics, factors affecting reaction rates, rate laws, order and molecularity, zero and first order reactions, Arrhenius equation, and collision and transition state theories.', '["Gas Laws and Kinetic Theory: Kinetic theory of gases, elementary derivation and deduction of gas laws, molecular speeds, deviations from ideal behaviour, van der Waals modification, and gas liquefaction", "Phase Equilibrium and Solutions: Phase transitions and phase equilibria in one-component systems. Ideal solutions, Raoult''s law, Henry''s law, real solutions, and colligative properties -- vapour pressure lowering, boiling point elevation, freezing point lowering, osmotic pressure", "Thermodynamics and Kinetics: Aspects of the first law of thermodynamics, thermochemistry, entropy, free energy, and spontaneous changes. Ionic equilibria, acids, bases, indicators, and buffers. Elementary chemical kinetics, factors affecting reaction rates, rate laws, order and molecularity, zero and first order reactions, Arrhenius equation, and collision and transition state theories"]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('CHM 122', 'Basic Principles of Chemistry III', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'second', 2, 'Structure and Classification: Historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, homologous series, elemental analysis, molecular formulas, and structural isomerism. Bonding and Reactivity: Isolation and purification methods, functional group concepts, resonance, and aromaticity. Electronic theory in organic chemistry. Functional Groups: Brief study of saturated and unsaturated hydrocarbons, cyclic hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, and aromatic compounds. Comparison of phenols and aryl halides. Stereochemistry and Lipids: Introduction to oils, fats, and stereoisomerism.', '["Structure and Classification: Historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, homologous series, elemental analysis, molecular formulas, and structural isomerism", "Bonding and Reactivity: Isolation and purification methods, functional group concepts, resonance, and aromaticity. Electronic theory in organic chemistry", "Functional Groups: Brief study of saturated and unsaturated hydrocarbons, cyclic hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, and aromatic compounds. Comparison of phenols and aryl halides", "Stereochemistry and Lipids: Introduction to oils, fats, and stereoisomerism"]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('GSP 102', 'The Use of English II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '100 Level', 'second', 2, 'Part A: Basic Grammar: Introduction. The concept of grammar and its place in language teaching and learning. Parts of speech and their functions (treated in detail). Closed and open class items in parts of speech, Nominalization, Grammatical Structures: the phrase, the clause and the sentence. Elementary Clause Analysis, Sentence Types, Elements and Patterns. Agreement (Grammatical agreement, Notional agreement, Proximity agreement) Agreement with the correlatives. Direct and Reported Speech, Error typology identification and correction.

Part B: Varieties of writing. Introduction (The Meaning, Nature and Purpose of Writing, Writing Types or Genres and their Characteristics). The paragraph as the basic unit of an essay (Types, Development of the Paragraph, Methods of Paragraph Development, The thesis statement). Point of view and style in writing. Qualities of a good piece of writing: Form, Diction and Content in writing. The Mechanics of Writing: punctuation, spelling and capitalization.

Part C: Writing Genres - Planning and choosing your theme. Deciding your genre. Choosing and developing your plot. Point of view, setting and characterization. Using the language that works. Essay Writing — Narration, Description, Exposition and Argumentation. Technical Writing: Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes, own story for practice, Computer-linked writing, types, style, language, and process.', '["Part A: Basic Grammar - The concept of grammar, Parts of speech, Grammatical Structures, Sentence Types, Agreement, Direct and Reported Speech, Error typology", "Part B: Varieties of writing - Meaning, Nature and Purpose of Writing, the paragraph as the basic unit of an essay, the thesis statement, Qualities of a good piece of writing, Mechanics of Writing", "Part C: Writing Genres - Planning and choosing your theme, plot, point of view, setting and characterization", "Essay Writing - Narration, Description, Exposition and Argumentation", "Technical Writing - Letter Writing, Memorandum Writing, Speech Writing, Agenda and Minutes"]'::jsonb, 'Department of Mechanical Engineering handbook'),
  ('MTH 207', 'Advanced Mathematics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '200 Level', 'first', 2, 'Elements of linear algebra. Calculus: Elementary differentiation and relevant theorems. Differential equations: Exact equations, methods of solution of second-order ordinary differential equations, partial differential equations, with applications.', '["Elements of linear algebra", "Calculus: Elementary differentiation and relevant theorems", "Differential equations: Exact equations, methods of solution of second-order ordinary differential equations, partial differential equations, with applications"]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('COS 201', 'Computer Programming I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '200 Level', 'first', 2, 'Printed in this table as "Computer Programming 11"; every other appearance of COS 201 in this document titles it Computer Programming I, used here.', '[]'::jsonb, 'Faculty of Physical Sciences course catalogue (2014/2015)'),
  ('GSP 201', 'Peace Studies and Conflict Resolution I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('GSP 207', 'Humanities I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '200 Level', 'first', 2, '', '[]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('MTH 206', 'Advanced Mathematics VII', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '200 Level', 'second', 2, 'Complex analysis - Elements of the algebra of complex variables, trigonometric, exponential and logarithmic functions. The number system, sequences and series. Vector differentiation and integration.', '["Complex analysis - Elements of the algebra of complex variables, trigonometric, exponential and logarithmic functions", "The number system, sequences and series", "Vector differentiation and integration"]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('MTH 208', 'Advanced Mathematics VIII', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '200 Level', 'second', 2, 'Numerical analysis: Linear equations, non-linear equations; finite difference operators. Introduction to linear programming.', '["Numerical analysis: Linear equations, non-linear equations", "Finite difference operators", "Introduction to linear programming"]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('GSP 202', 'Peace Studies and Conflict Resolution II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('GSP 208', 'Humanities II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '200 Level', 'second', 2, '', '[]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('EE 211', 'Electrical Engineering I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'first', 3, 'Elective.', '[]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('ECE 311', 'Circuit Theory I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'first', 3, 'Elective.', '[]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('ECE 321', 'Physical Electronics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'first', 3, 'Elective.', '[]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('CHM 211', 'General Physical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'first', 2, 'Elective. Gases and Thermodynamics: Molecular collisions in gases, virial equation, critical phenomena, and reduced properties. Chemical thermodynamics, detailed treatment of the first law of thermodynamics, and the Carnot cycle. Chemical Kinetics: Integrated rate equations for second and third order reactions, reaction mechanisms, rate laws, and the effect of temperature on reaction rates.

Prerequisite: CHM 112', '["Gases and Thermodynamics: Molecular collisions in gases, virial equation, critical phenomena, and reduced properties. Chemical thermodynamics, detailed treatment of the first law of thermodynamics, and the Carnot cycle", "Chemical Kinetics: Integrated rate equations for second and third order reactions, reaction mechanisms, rate laws, and the effect of temperature on reaction rates"]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('GLG 211', 'Crystallography', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'first', 2, 'Elective. Formation of crystal; crystalline state; laws of crystallography; space lattice and unit cell symmetry elements, goniometry and stereographic projection; crystallographic projection; crystallographic notations; seven crystal systems and 32 classes of crystal symmetry, crystal defects; twinning and twin laws. Principles of crystal chemistry; physical and determinative properties of minerals; systematics of minerals; silicates; description of common rock-forming minerals. Industrial Mineralogy.', '["Formation of crystal", "Crystalline state", "Laws of crystallography", "Space lattice and unit cell symmetry elements, goniometry and stereographic projection", "Crystallographic projection", "Crystallographic notations", "Seven crystal systems and 32 classes of crystal symmetry, crystal defects", "Twinning and twin laws", "Principles of crystal chemistry", "Physical and determinative properties of minerals", "Systematics of minerals", "Silicates", "Description of common rock-forming minerals", "Industrial Mineralogy"]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('STA 203', 'Statistics for Physical Sciences and Engineering I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'first', 2, 'Elective. Initial steps in planning of biological experiments. Methods of data collection, presentation and analysis. Measures of central tendency and dispersion. Frequency distributions. Elementary probability. Discrete and continuous distributions: Binomial, Poisson, Normal and exponential distributions. Interval estimation.', '["Initial steps in planning of biological experiments", "Methods of data collection, presentation and analysis", "Measures of central tendency and dispersion", "Frequency distributions", "Elementary probability", "Discrete and continuous distributions: Binomial, Poisson, Normal and exponential distributions", "Interval estimation"]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('STA 322', 'Regression Analysis', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'first', 2, 'Elective.', '[]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('COS 202', 'Computer Programming II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'second', 2, 'Elective.', '[]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('EE 251', 'Electrical Engineering Lab', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'second', 1, 'Elective.', '[]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('ECE 312', 'Circuit Theory II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'second', 3, 'Elective.', '[]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('ECE 322', 'Applied Electronics', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'second', 2, 'Elective.', '[]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('CHM 251', 'Chemical Process Principles', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'second', 2, 'Elective.', '[]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('MTH 222', 'Elementary Differential Equations I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'second', 3, 'Elective. First-order ordinary differential equations. Existence and uniqueness of solution. Second-order ordinary differential equations with constant coefficients. General theory of $n$th-order linear ordinary differential equations. The Laplace transform. Solution of initial- and boundary-value problems by Laplace transform method. Simple treatment of partial differential equations in two independent variables. Applications of ordinary and partial differential equations to physical, life and engineering problems.', '["First-order ordinary differential equations", "Existence and uniqueness of solution", "Second-order ordinary differential equations with constant coefficients", "General theory of $n$th-order linear ordinary differential equations", "The Laplace transform", "Solution of initial- and boundary-value problems by Laplace transform method", "Simple treatment of partial differential equations in two independent variables", "Applications of ordinary and partial differential equations to physical, life and engineering problems"]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('MTH 214', 'Mathematical Methods I', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'second', 3, 'Elective.', '[]'::jsonb, 'Department of Physics and Astronomy course module'),
  ('STA 206', 'Statistics for Physical Sciences and Engineering II', 'University of Nigeria, Nsukka', 'Faculty of Physical Sciences', 'Physics and Astronomy', '300 Level', 'second', 2, 'Elective. Estimation: point and interval. Test of significance. Regression and correlation. Analysis of variance: one-way and two-way with no interaction.', '["Estimation: point and interval", "Test of significance", "Regression and correlation", "Analysis of variance: one-way and two-way with no interaction"]'::jsonb, 'Department of Physics and Astronomy course module');
