-- =============================================================================
-- University of Nigeria, Nsukka -- Faculty of Engineering
-- Department of Metallurgical and Materials Engineering
-- Five-Year Standard Undergraduate B.Eng Degree Programme
-- =============================================================================
-- Transcribed from Chapter Ten of the Faculty of Engineering handbook
-- (book pages 194-198). 86 rows: 77 programme courses
-- across all five years plus the 9 fifth-year elective options.
--
-- VERIFICATION: the handbook prints a "Total" for every semester. Each of the
-- ten totals was recomputed from the individual unit values and compared
-- against the printed figure -- 18, 17, 19, 18, 20, 20, 19, 15, 18, 19 -- and
-- all ten reconcile exactly. That checksum is what makes the unit column
-- trustworthy: this handbook right-aligns units so they can visually drift
-- onto the following row, and the totals are what pin them back down.
--
-- FIFTH-YEAR ELECTIVES: the handbook says "Any three (3) courses" are taken in
-- the second semester of fifth year, worth 6 units in total, and lists nine
-- options. They are stored as is_elective = true at 2 units each (6 units over
-- three courses). The handbook does not print titles for these nine codes in
-- the programme table, so they carry a generic title rather than an invented
-- one; the detailed course-description section is a separate follow-up pass.
--
-- DESCRIPTIONS: 18 of the shared ancillary courses (MTH/CHM/PHY/EGR/STA)
-- reuse the description already held for that same course code elsewhere in
-- this app, rather than getting freshly invented prose -- shared courses must
-- read identically across departments. The remaining rows carry an empty
-- description, exactly as the existing Agricultural and Bioresources
-- Engineering outline does for its own ancillary rows; the MME-specific
-- descriptions live in the handbook's detailed-description section and are a
-- follow-up pass rather than being guessed at here.
--
-- NOTE ON GSP 101/102: this chapter prints GSP 101 as "The Use of English I"
-- and GSP 102 as "The Use of English II". The Agricultural and Bioresources
-- Engineering chapter of the same handbook prints GSP 101 as "Study Skills and
-- Basic Research Methods" instead. That is the handbook disagreeing with
-- itself across chapters, not a transcription error; each department's rows
-- record what its own chapter prints.
-- =============================================================================

delete from public.course_outlines
 where institution = 'University of Nigeria, Nsukka'
   and department = 'Metallurgical and Materials Engineering';

insert into public.course_outlines
  (course_code, course_title, institution, faculty, department, level,
   semester, credit_units, description, topics, contributor_name, is_elective)
values
  ('EGR 101', 'Introduction to Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '100 Level', 'first', 2, 'An overview of engineering as a profession. Historical perspective, Discipline, Rationalization, professional affiliations, professional journey, successful studentship, creativity, roles of science and Technology; Engineering and Society: The role of engineers in nation building, professional impacts of Engineering practice and mitigation measures, professional challenges in Nigeria, historical and professional roles; Basic information on Agricultural and Bioresources Engineering, Professional practice, Sustainable Agricultural production in Nigeria; Introduction to Biomedical Engineering, Scope of biomedical engineering practice: A science perspective of Civil Engineering, corporate personality of Civil Engineering; Civil Engineering professional practice; Basic information on Electrical Engineering, Scope of Electrical Engineering professional practice; Electric power generation in Nigeria; Evolution to Electronic Engineering, Scope of Electronic Engineering Professional practice, practice of Electronic Engineering in Nigeria; Basic information on Mechanical Engineering, Scope of Mechanical Engineering professional practice, practice of Mechanical Engineering in Nigeria; Introduction to Mechatronics Engineering, Scope of Mechatronics engineering practice; Basic information on Metallurgical and Materials Engineering, Scope of Metallurgical and Materials Engineering professional practice, practice of Metallurgical and Materials Engineering.', '["An overview of engineering as a profession. Historical perspective, Discipline, Rationalization, professional affiliations, professional journey, successful studentship, creativity, roles of science and Technology", "Engineering and Society: The role of engineers in nation building, professional impacts of Engineering practice and mitigation measures, professional challenges in Nigeria", "Basic information on Agricultural and Bioresources Engineering; Introduction to Biomedical Engineering", "A science perspective of Civil Engineering, corporate personality and professional practice of Civil Engineering", "Basic information on Electrical Engineering; Electric power generation in Nigeria; Evolution to Electronic Engineering", "Basic information on Mechanical Engineering, Scope and practice of Mechanical Engineering in Nigeria", "Introduction to Mechatronics Engineering; Basic information on Metallurgical and Materials Engineering"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 111', 'Elementary Mathematics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '100 Level', 'first', 3, 'Elementary set theory, subsets, union, intersection, complements. Venn diagrams, real numbers, integers, rational and irrational numbers, mathematical induction, real sequences and series, theory of quadratic equations, binomial theorem. Circular measure, trigonometric functions of angles of any magnitude, addition and factor formulae. Complex numbers, algebra of complex numbers, the Argand diagram, De Moivre''s theorem, nth roots of unity.', '["Elementary set theory, subsets, union, intersection, complements", "Venn diagrams, real numbers, integers, rational and irrational numbers, mathematical induction, real sequences and series, theory of quadratic equations, binomial theorem", "Circular measure, trigonometric functions of angles of any magnitude, addition and factor formulae", "Complex numbers, algebra of complex numbers, the Argand diagram, De Moivre''s theorem, nth roots of unity"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 121', 'Elementary Mathematics II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '100 Level', 'first', 3, 'Functions of a real variable, graphs, limits and continuity. The derivative as limit of rate of change. Techniques of differentiation. Curve sketching, integration as an inverse of differentiation. Methods of integration, definite integrals. Application of integration to areas and volumes.', '["Functions of a real variable, graphs, limits and continuity", "The derivative as limit of rate of change", "Techniques of differentiation", "Curve sketching, integration as an inverse of differentiation", "Methods of integration, definite integrals", "Application of integration to areas and volumes"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CHM 101', 'Basic Principles of Inorganic Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '100 Level', 'first', 2, 'Stoichiometry and Atomic Structure: Stoichiometry and mole concept. Introduction to atomic structure, development of electronic configuration of the elements, and valency theories. Periodic Table and Groups: The periodic classification of elements. Brief group study of representative elements, with emphasis on similarities and differences based on periodic position. Nuclear Chemistry: Radioactivity and its practical applications.', '["Stoichiometry and Atomic Structure: Stoichiometry and mole concept. Introduction to atomic structure, development of electronic configuration of the elements, and valency theories", "Periodic Table and Groups: The periodic classification of elements. Brief group study of representative elements, with emphasis on similarities and differences based on periodic position", "Nuclear Chemistry: Radioactivity and its practical applications"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CHM 171', 'Basic Practical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '100 Level', 'first', 2, 'Laboratory operations: theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations.', '["Laboratory operations: theory and practice of simple volumetric and quantitative analysis, simple organic preparations, functional group reactions, and physical chemistry determinations"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('PHY 121', 'Fundamentals of Physics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '100 Level', 'first', 2, 'Units and dimensions. Vector algebra. Kinematics of a particle''s mass point; laws of mechanics and gravitation. Kepler''s Laws. Motion of rigid bodies, moment of inertia, angular momentum, vertical motion of a particle, elastic string, motion of a simple pendulum. Impulse and change of Momentum. Impact of two smooth elastic spheres. Direct and Oblique impacts.', '["Units and dimensions. Vector algebra", "Kinematics of a particle''s mass point; laws of mechanics and gravitation. Kepler''s Laws", "Motion of rigid bodies, moment of inertia, angular momentum", "Vertical motion of a particle, elastic string, motion of a simple pendulum", "Impulse and change of Momentum. Impact of two smooth elastic spheres. Direct and Oblique impacts"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('PHY 195', 'Practical Physics II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '100 Level', 'first', 2, 'Selected Experiments from the 100-Level courses in Physics for Physics majors and Engineering students.', '["Selected Experiments from the 100-Level courses in Physics for Physics majors and Engineering students"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 101', 'The Use of English I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '100 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EGR 102', 'Applied Mechanics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '100 Level', 'second', 3, 'Introduction - Force Systems, resultants, Moments, Couples. Equilibrium, free-body diagram, 2-dimensional force systems, equations for equilibrium of forces in space, internal forces, examples of simple machines, friction, pulleys, wires and cables, static and dynamic Friction. Centroid, graphical determination, Theorems of Pappus of centers of gravity and areas. Moments of Inertia of plane areas, built up sections etc. Kinematics of particles and rigid bodies. Newton''s laws of motion applied to a system of particles. Rectilinear and curvilinear motion, tangent, normal, polar, work, energy, power. Concepts of momentum and Newton''s laws of motion under gravity. Projectile motion.', '["Introduction - Force Systems, resultants, Moments, Couples. Equilibrium, free-body diagram, 2-dimensional force systems", "Equations for equilibrium of forces in space, internal forces, examples of simple machines, friction, pulleys, wires and cables, static and dynamic Friction", "Centroid, graphical determination, Theorems of Pappus of centers of gravity and areas. Moments of Inertia of plane areas, built up sections etc", "Kinematics of particles and rigid bodies. Newton''s laws of motion applied to a system of particles", "Rectilinear and curvilinear motion, tangent, normal, polar, work, energy, power", "Concepts of momentum and Newton''s laws of motion under gravity. Projectile motion"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 122', 'Elementary Mathematics III', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '100 Level', 'second', 3, 'Geometric representation of vectors in 1-3 dimensions, Components, direction cosines. Addition of vectors and multiplication of vectors by a scalar, linear independence. Scalar and vector products of two vectors. Differentiation and integration of vectors with respect to a scalar variable. Two-dimensional coordinate geometry. Straight lines, circles, parabolas, ellipses, hyperbolas. Tangents and normals. Kinematics of a particle. Components of velocity and acceleration of a particle moving in a plane. Force and momentum. Newton''s laws of motion; motion under gravity, projectile motion, resisted vertical motion of a particle, elastic string, motion of a simple pendulum, impulse and impact of momentum. Impact of two smooth elastic spheres. Direct and oblique impacts.', '["Geometric representation of vectors in 1-3 dimensions, Components, direction cosines", "Addition of vectors and multiplication of vectors by a scalar, linear independence", "Scalar and vector products of two vectors", "Differentiation and integration of vectors with respect to a scalar variable", "Two-dimensional coordinate geometry", "Straight lines, circles, parabolas, ellipses, hyperbolas", "Tangents and normals", "Kinematics of a particle", "Components of velocity and acceleration of a particle moving in a plane", "Force and momentum", "Newton''s laws of motion", "Motion under gravity, projectile motion, resisted vertical motion of a particle, elastic string, motion of a simple pendulum, impulse and impact of momentum", "Impact of two smooth elastic spheres", "Direct and oblique impacts"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CHM 112', 'Basic Principles of Physical Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '100 Level', 'second', 2, 'Gas laws and kinetic theory: kinetic theory of gases, elementary derivation and deduction of gas laws, molecular speeds, deviations from ideal behaviour, van der Waals modification, and gas liquefaction. Phase equilibrium and solutions: phase transitions and phase equilibria in one-component systems; ideal solutions, Raoult''s law, Henry''s law, real solutions, and colligative properties. Thermodynamics and kinetics: aspects of the first law of thermodynamics, thermochemistry, entropy, free energy, and spontaneous changes; ionic equilibria, acids, bases, indicators, and buffers; elementary chemical kinetics.', '["Gas laws and kinetic theory of gases; molecular speeds; deviations from ideal behaviour; gas liquefaction", "Phase transitions and phase equilibria; ideal and real solutions; colligative properties", "First law of thermodynamics, thermochemistry, entropy, free energy, spontaneous changes", "Ionic equilibria, acids, bases, indicators and buffers", "Elementary chemical kinetics: rate laws, order and molecularity, Arrhenius equation"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CHM 122', 'Basic Principles of Organic Chemistry', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '100 Level', 'second', 2, 'Structure and classification: historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, homologous series, elemental analysis, molecular formulas, and structural isomerism. Bonding and reactivity: isolation and purification methods, functional group concepts, resonance, and aromaticity. Functional groups: saturated and unsaturated hydrocarbons, cyclic hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, and aromatic compounds. Stereochemistry and lipids: introduction to oils, fats, and stereoisomerism.', '["Historical survey of organic chemistry, IUPAC nomenclature, classification of organic compounds, structural isomerism", "Isolation and purification methods; functional group concepts; resonance and aromaticity", "Saturated and unsaturated hydrocarbons, alcohols, alkyl halides, ethers, aldehydes, ketones, carboxylic acids, amines, aromatic compounds", "Introduction to oils, fats, and stereoisomerism"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('PHY 116', 'General Physics for Physical Sciences II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '100 Level', 'second', 2, 'Temperature and its measurement. Heat capacity, specific heat, latent heats, critical points. Calorimetry. Gas laws; kinetic theory of gases; thermal energy, work done by expanding gases; laws of thermodynamics. Liquefaction of gases. Heat transfer: conduction, convection, radiation. Longitudinal and transverse waves; vibrations in solids. Sound waves in solids, liquids, gases; pitch, intensity and quality of sound. Doppler Effect. Acoustics of buildings. Ultrasonics. Reflection and refraction of light; spherical mirrors; thin and thick lenses; optical instruments. Wave nature of light; interference, diffraction, polarization. Velocity of light.', '["Temperature and its measurement", "Heat capacity, specific heat, latent heats, critical points", "Calorimetry", "Gas laws", "Kinetic theory of gases", "Thermal energy, work done by expanding gases", "Laws of thermodynamics", "Liquefaction of gases", "Heat transfer: conduction, convection, radiation", "Longitudinal and transverse waves", "Vibrations in solids", "Sound waves in solids, liquids, gases", "Pitch, intensity and quality of sound", "Doppler Effect", "Acoustics of buildings", "Ultrasonics", "Reflection and refraction of light", "Spherical mirrors", "Thin and thick lenses", "Optical instruments", "Wave nature of light", "Interference, diffraction, polarization", "Velocity of light"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('PHY 124', 'Fundamentals of Physics III', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '100 Level', 'second', 3, 'Electrostatics, Coulomb''s Law, Gauss''s Law, simple applications. Electric field, electrostatic potential. Energy in electric field, capacitance, dielectrics. Electric current, Ohm''s law, circuit analysis, Thermoelectricity. Magnetic effects of currents, Ampere''s Law, Applications. Electromagnetism, Faraday''s law of induction, Maxwell''s equations. Alternating currents, A.C. circuits. Measuring devices. Motion of a charged particle in electric and magnetic fields, Hall Effect. Atomic and Nuclear structure. Nuclear fission and fusion. Nuclear reactors.', '["Electrostatics, Coulomb''s Law, Gauss''s Law, simple applications", "Electric field, electrostatic potential. Energy in electric field, capacitance, dielectrics", "Electric current, Ohm''s law, circuit analysis, Thermoelectricity", "Magnetic effects of currents, Ampere''s Law, Applications. Electromagnetism, Faraday''s law of induction, Maxwell''s equations", "Alternating currents, A.C. circuits. Measuring devices", "Motion of a charged particle in electric and magnetic fields, Hall Effect", "Atomic and Nuclear structure. Nuclear fission and fusion. Nuclear reactors"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 102', 'The Use of English II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '100 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 201', 'Materials Science', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 213', 'Materials Science Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '200 Level', 'first', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 207', 'Advanced Mathematics VI', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '200 Level', 'first', 2, 'Elements of linear algebra. Calculus: Elementary differentiation and relevant theorems. Differential equations: Exact equations, methods of solution of second-order ordinary differential equations, partial differential equations, with applications.', '["Elements of linear algebra", "Calculus: Elementary differentiation and relevant theorems", "Differential equations: Exact equations, methods of solution of second-order ordinary differential equations, partial differential equations, with applications"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CVE 211', 'Strength of Materials', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 211', 'Basic Electrical Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '200 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MEC 211', 'Engineering Drawing I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MEC 261', 'Engineering Thermodynamics I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CVE 212', 'Strength of Materials Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '200 Level', 'first', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 201', 'Basic Concepts and Theories of Peace and Conflict Resolution', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 207', 'Humanities I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '200 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 206', 'Advanced Mathematics VII', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '200 Level', 'second', 2, 'The programme table prints "Advanced Mathematics VII" against both MTH 206 and MTH 207; quoted as printed. Complex analysis - Elements of the algebra of complex variables, trigonometric, exponential and logarithmic functions. The number system, sequences and series. Vector differentiation and integration.', '["Complex analysis - Elements of the algebra of complex variables, trigonometric, exponential and logarithmic functions", "The number system, sequences and series", "Vector differentiation and integration"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MTH 208', 'Advanced Mathematics VIII', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '200 Level', 'second', 2, 'Elective. Numerical analysis: Linear equations, non-linear equations; finite difference operators. Introduction to linear programming.', '["Numerical analysis: Linear equations, non-linear equations", "Finite difference operators", "Introduction to linear programming"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CVE 221', 'Fluid Mechanics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '200 Level', 'second', 2, 'Elective. The programme table''s left edge is cut off by the book''s binding, printing only "E 221" for this code; CVE 221 (Civil Engineering) is used as the closest plausible match for a Fluid Mechanics elective, but this is not independently confirmed.', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CVE 222', 'Fluid Mechanics Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '200 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MEC 212', 'Workshop Technology I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EEE 251', 'Basic Electrical Engineering Lab/Practice', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '200 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 271', 'Engineering Computer Programming', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '200 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('ECE 281', 'Engineering Computer Programming Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '200 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 202', 'Issues in Peace and Conflict Resolution Studies', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('GSP 208', 'Humanities II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '200 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 301', 'Metallurgical Thermodynamics and Kinetics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 331', 'Physical Metallurgy I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 333', 'Basic Electron Theory of Materials', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 341', 'Mechanical Metallurgy I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 323', 'Corrosion Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '300 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MEC 314', 'Mechanical Engineering Design I', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '300 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('STA 203', 'Statistics for Physical Sciences and Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '300 Level', 'first', 2, 'Initial steps in planning of biological experiments. Methods of data collection, presentation and analysis. Measures of central tendency and dispersion. Frequency distributions. Elementary probability. Discrete and continuous distributions: Binomial, Poisson, Normal and exponential distributions. Interval estimation.', '["Initial steps in planning of biological experiments", "Methods of data collection, presentation and analysis", "Measures of central tendency and dispersion", "Frequency distributions", "Elementary probability", "Discrete and continuous distributions: Binomial, Poisson, Normal and exponential distributions", "Interval estimation"]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MEC 313', 'Workshop Practices', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CED 341', 'Introduction to Entrepreneurship', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '300 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 302', 'X-ray Diffraction and Electro-optical Techniques', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 322', 'Mineral Processing', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 332', 'Structure, Properties and Heat Treatment of Alloys', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 342', 'Metallurgical Furnaces and Principles of Foundry Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '300 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 381', 'Ceramic Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 311', 'Physical Metallurgy Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '300 Level', 'second', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EGR 301', 'Engineering Analysis', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '300 Level', 'second', 4, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MEC 344', 'Measurement and Instrumentation', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('CED 342', 'Business Development and Management', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '300 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 411', 'Corrosion and Chemical Metallurgy Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '400 Level', 'first', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 413', 'Mechanical Metallurgy Laboratory', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '400 Level', 'first', 1, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 421', 'Extraction Metallurgy', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '400 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 431', 'Physical Metallurgy II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '400 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 443', 'Production Metallurgy', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '400 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 451', 'Welding Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '400 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 461', 'Polymer Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '400 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MEC 471', 'Heat and Mass Transfer', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '400 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EGR 401', 'Computational Methods', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '400 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('EGR 402', 'Student Industrial Work Experience Scheme (SIWES)', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '400 Level', 'second', 10, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 491', 'Technical Report Writing', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '400 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MEC 481', 'Technology Development Policy', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '400 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 531', 'Transport Phenomena in Materials Engineering', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 541', 'Theory and Design of Engineering Alloys', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 543', 'Iron and Steel Making', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 551', 'Introduction to Composites', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '500 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 581', 'Nano-science and Nanotechnology', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 561', 'Engineering Materials Selection and Economics', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '500 Level', 'first', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MEC 581', 'Engineering Law', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MEC 583', 'Engineering Management', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '500 Level', 'first', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 524', 'Metallurgical Plant Design', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '500 Level', 'second', 3, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 532', 'Theory of Dislocations', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 542', 'Mechanical Metallurgy II', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MME 592', 'Project', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '500 Level', 'second', 6, '', '[]'::jsonb, 'Faculty of Engineering handbook', false),
  ('MEC 522', 'Elective Course (Mechanical Engineering)', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('MME 538', 'Elective Course', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('MME 546', 'Elective Course', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('MME 552', 'Elective Course', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('MME 556', 'Elective Course', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('MME 574', 'Elective Course', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('MME 582', 'Elective Course', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('MME 521', 'Elective Course', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true),
  ('MME 584', 'Elective Course', 'University of Nigeria, Nsukka', 'Faculty of Engineering', 'Metallurgical and Materials Engineering', '500 Level', 'second', 2, '', '[]'::jsonb, 'Faculty of Engineering handbook', true);
