// Auto-generated: every distinct question/option/explanation field
// from the COS101 bank, verified against the real
// flutter_math_fork renderer via MathText's mixed prose+LaTeX path.
import 'package:eduvora/core/widgets/math_text.dart';
import 'package:flutter/material.dart';
import 'package:flutter_math_fork/flutter_math.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  final List<String> fields = <String>[
    "\"true\"",
    "'Stepwise refinement', as a problem-solving technique in programming, means:",
    "1",
    "10",
    "1010",
    "1010 in binary is read right to left as: 0×1 + 1×2 + 0×4 + 1×8 = 0+2+0+8 = 10. So 1010(base 2) equals 10 in decimal.",
    "1011",
    "11",
    "1101",
    "1110",
    "12",
    "13",
    "13 in decimal splits as 8+4+1 = 2^3+2^2+2^0, giving binary digits 1 (for 8), 1 (for 4), 0 (for 2), 1 (for 1) — that is, 1101 in binary. Checking: 1101(base 2) = 1×8 + 1×4 + 0×2 + 1×1 = 8+4+0+1 = 13.",
    "16",
    "1969",
    "1971",
    "1976",
    "1981",
    "1983",
    "1985",
    "1990",
    "1993",
    "1995",
    "2",
    "20",
    "2001",
    "22",
    "2ndValue",
    "30",
    "32",
    "34",
    "8",
    "9",
    "A CRT (Cathode Ray Tube) monitor and an LCD (Liquid Crystal Display) monitor are both examples of:",
    "A Command-Line Interface (CLI) differs from a Graphical User Interface (GUI) mainly in that a CLI:",
    "A Command-Line Interface requires the user to type precise textual commands to interact with the operating system, whereas a Graphical User Interface lets the user interact visually through windows, icons, menus, and pointers (like a mouse) — generally considered more intuitive for beginners.",
    "A DBMS helps reduce data duplication and inconsistency by centralising related data in a structured way, and it provides controlled, query-based access to that data — advantages that scattered, disconnected data files do not offer.",
    "A Database Management System (DBMS) is best described as software that allows users to:",
    "A Database Management System (DBMS) is software that lets users define the structure of a database, store and organise related data within it, retrieve and update that data, and control who is allowed to access or modify it.",
    "A LAN connects computers and devices within a relatively small, confined geographic area, such as a single office, building, or campus — as opposed to a Wide Area Network (WAN), which spans much larger distances, even entire countries or continents.",
    "A Local Area Network (LAN) is best described as a network that:",
    "A Personal Computer (PC) is best classified, in terms of computer size/power categories, as a:",
    "A Trojan horse is malware that disguises itself as legitimate or desirable software; once a user is tricked into running it, it carries out hidden, harmful actions — unlike a virus or worm, it typically does not self-replicate.",
    "A URL (Uniform Resource Locator), such as https://www.example.com/page.html, is best described as:",
    "A URL is a standardised text address that specifies exactly where a particular resource (such as a webpage, image, or file) can be found on the internet, typically including the protocol, domain name, and path.",
    "A bus is a common pathway (a set of conductors) along which data, memory addresses, or control signals travel between the CPU, memory, and other components inside a computer.",
    "A bus, in computer architecture, refers to:",
    "A class in Java is a template or blueprint: it defines what data members (fields/attributes) and methods (behaviours) objects of that class will possess. Individual objects are then created ('instantiated') from the class.",
    "A cold boot happens when a computer is started from a completely powered-off state: the hardware runs its full Power-On Self-Test (POST) before the operating system is loaded, unlike a warm boot which restarts an already-powered computer.",
    "A computer (or computer system) is an electronic machine operating under the control of instructions stored in its own memory, which can capture/accept data, manipulate the data according to specified rules, produce results, and store the results for future use.",
    "A computer has no independent judgement or initiative: it can only do exactly what it is instructed to do through a program, following the well-known principle 'garbage in, garbage out'. Its recognised characteristics are speed, accuracy, diligence, storage capacity, and versatility — not the ability to decide tasks on its own.",
    "A computer network in which all devices connect to and communicate along one single shared central cable is described as having which topology?",
    "A computer program is a sequence of instructions written to be followed by the CPU in order to perform a specific task. The person who writes the program is called a programmer.",
    "A computer program is best described as:",
    "A computer system is best defined as a machine that operates under the control of instructions stored in its own memory and can:",
    "A computer virus is a type of malware that attaches itself to a legitimate host file or program and spreads by infecting other files whenever the infected program is executed, potentially damaging data or disrupting the system.",
    "A computer's ability to perform a wide variety of different tasks — from word processing to calculations to playing media — is known as its:",
    "A desktop PC, a laptop, and a tablet computer are all examples of which class of computer?",
    "A desktop is always more portable and lighter to carry around than a laptop",
    "A device that allows a user to point, click, and select items on the screen by moving it across a flat surface is called a:",
    "A device that produces high-quality line drawings, engineering diagrams, or large-format graphics by moving a pen (or similar marking tool) across paper is called a:",
    "A diamond (rhombus) shape represents a decision point in a flowchart — the flow branches into two or more paths depending on whether a stated condition is true or false.",
    "A digital computer's basic subsystems are commonly grouped as: an input subsystem (captures data), a processing subsystem (CPU and memory, which computes results), an output subsystem (presents results), and a storage subsystem (retains data/programs).",
    "A drop-down list of commands or options that appears when a user clicks on a heading (such as 'File' or 'Edit') in a GUI application's top bar is called a:",
    "A flowchart is a diagrammatic representation of an algorithm, using standard symbols — for example, ovals for start/end (terminators), rectangles for processing steps, and diamonds for decisions — linked by arrows that show the order in which steps are carried out.",
    "A flowchart represents an algorithm using:",
    "A hard disk is a secondary storage device: it stores data and programs permanently (until deliberately deleted) in large capacities, and is used to hold data even when the computer is switched off — unlike RAM, cache, and registers, which are all primary/internal memory.",
    "A hardware component located physically inside the CPU chip itself",
    "A laptop cannot run any application software that a desktop PC is able to run",
    "A laptop has no processor and simply displays output from a separate desktop machine",
    "A laptop integrates the system unit, screen, keyboard, and battery into one portable unit, while a desktop's components are typically separate and mains-powered",
    "A laptop is a portable microcomputer that combines the processor, memory, screen, keyboard, and a rechargeable battery in a single foldable unit, whereas a desktop PC typically has separate components (system unit, monitor, keyboard) and relies on mains power.",
    "A large, powerful computer used by big organisations (such as banks) to process huge volumes of transactions and serve many users/terminals simultaneously is called a:",
    "A mainframe computer is a large-scale, high-capacity computer used by organisations to process large volumes of data and serve numerous simultaneous users/terminals, such as in banking or airline reservation systems.",
    "A menu is a GUI element that presents a list of selectable commands or options to the user, typically appearing when the user clicks a heading like 'File' or 'Edit' in an application's menu bar.",
    "A microcomputer is a small, relatively low-cost computer built around a microprocessor, designed for use by one person at a time — the Personal Computer (PC) is the most common example of this category.",
    "A microphone is an input device that captures sound waves (such as speech) and converts them into an electrical signal, which the computer's sound hardware then digitises for processing or storage.",
    "A mouse is a pointing input device; moving it across a surface moves an on-screen pointer, and its buttons let the user select or activate items.",
    "A multi-user operating system manages resources so that two or more users can access the computer's processing power and resources simultaneously, typically from separate terminals or connections — common on servers and mainframes.",
    "A plotter is an output device that draws images by moving a pen, or an equivalent marking mechanism, across the surface of paper — commonly used for precise line-art such as architectural or engineering drawings.",
    "A presentation application (such as one used to design and display slides during a talk) is primarily designed to help users:",
    "A presentation application allows the user to create a sequence of slides, typically combining text, images, charts, and other media, designed to be displayed to an audience to support a spoken talk or lecture.",
    "A program in the form in which it is written by the programmer is called source code. For the CPU to follow (execute) the program, the source code must first be transformed into the native machine language of that CPU.",
    "A program is called a systems program if it performs general duties needed for the execution of other programs. Which of these is a systems program?",
    "A proper operating-system shutdown closes running programs, flushes any data still waiting to be written to disk, and safely powers down hardware components — abruptly cutting power instead risks losing unsaved work or corrupting files/the file system.",
    "A proper shutdown lets the operating system close open files and save unsaved data safely, reducing the risk of data loss or file/disk corruption",
    "A proper shutdown physically empties and erases the entire contents of the hard disk",
    "A real-time operating system guarantees that it processes input and produces a response within a strict, predictable, and very short time constraint — essential in applications like industrial control systems, medical equipment, or robotics, where delayed responses could be dangerous.",
    "A real-time operating system is specifically characterised by its ability to:",
    "A rectangle is the standard flowchart symbol for a processing step — an operation such as a calculation, or assigning a value to a variable — as opposed to input/output or a decision.",
    "A rectangle shape in standard flowchart notation is used to represent:",
    "A relational database organises related data into tables, where each row represents a single record and each column represents a specific field/attribute of that record — related tables can then be linked together through common fields.",
    "A ring topology connects each device to exactly two other devices, forming a closed loop; data is typically passed from device to device around the ring until it reaches its destination.",
    "A scanner captures an image of a physical document and converts it into digital data that the computer can process — that makes it an input device. Monitors, plotters, and speakers all present processed results to the user, making them output devices.",
    "A service that lets users compose, send, and receive text messages (often with attachments) over a network, addressed to a specific electronic mailbox address",
    "A single-user, multi-tasking operating system (like most modern desktop operating systems) is used by one person at a time, but allows that person to run multiple programs concurrently, switching between them as needed.",
    "A single-user, single-task operating system allows only one user on the machine at a time and lets that user run only one program at a time — an early, simple category of operating system design.",
    "A spreadsheet application (such as one used to organise numbers into rows and columns and perform calculations) is primarily useful for:",
    "A spreadsheet application organises data into rows and columns (cells) and lets users apply formulas and functions — such as sums, averages, and more complex calculations — automatically across that data, making it especially useful for budgets, calculations, and data analysis.",
    "A statistical package (statistical software), as used in data analysis, is primarily designed to help users:",
    "A statistical package is application software built specifically to help users analyse data using statistical and mathematical techniques — such as computing averages, standard deviations, correlations, or building data models — beyond what a basic spreadsheet easily supports.",
    "A systems program performs general duties in support of other programs — for example, allocating memory space and CPU time, or providing printing services — rather than solving a specific end-user task directly.",
    "A technique used to convert numbers between different number bases",
    "A type of printer driver that translates documents into printable form",
    "A warm boot restarts a computer that is already powered on, typically skipping some of the hardware checks a full cold boot performs, and is commonly triggered through the operating system's own restart command.",
    "A word processor application, such as one used to type, format, and print a letter or an assignment, is an example of which category of software?",
    "A word processor is application software — specifically an office application — designed to help users create, edit, format, and print text documents, distinct from systems software that manages the computer itself.",
    "A worm is a self-replicating malware program that can spread across networks and systems entirely on its own, without needing to attach to a host file or requiring a user to execute an infected program — unlike a classic virus.",
    "According to the officially credited timeline, the first true personal computer to closely resemble what we now think of as a modern portable/personal computer was pioneered by projects such as the Xerox Alto, while the first commercially significant IBM-compatible PC was released by IBM in:",
    "Accuracy — it produces error-free results provided correct data and instructions are given",
    "Alan Turing's 1936 concept of the Turing machine is a theoretical/mathematical model describing computation in the abstract; it laid the foundational theory for what is computable, deeply influencing the later design and theory of real computers.",
    "Alan Turing's theoretical 'Turing machine', described in 1936, is historically significant in computing mainly because it:",
    "An algorithm is a finite, unambiguous, ordered sequence of steps that, when followed, solves a specific problem or accomplishes a specific task — it exists independently of any particular programming language.",
    "An icon is a small graphical symbol used in a graphical user interface to represent a program, file, folder, or function, which the user can select or activate (often by clicking or double-clicking) rather than typing a command.",
    "An operating system designed to allow only one user to work on the computer, running one task/program actively at a time, is classified as:",
    "An operating system that allows many different users, at different terminals, to access the same computer's resources at the same time is classified as a:",
    "An operating system that allows one user to run several different programs seemingly at the same time (e.g. browsing the web while music plays in the background) is classified as:",
    "Arithmetic and Logic Unit (ALU)",
    "BASIC does not support exponentiation as an operator at all",
    "BIOS/bootloader (boot firmware)",
    "Because binary digits (0 and 1) map directly onto simple two-state electronic circuits, such as a transistor being on or off, which are far easier to build reliably than circuitry needing ten distinct states",
    "Because binary numbers always require noticeably fewer digits to write down than the equivalent decimal numbers do",
    "Because the earliest computer designers personally found decimal notation confusing and difficult to read on paper",
    "Binary's two digits (0 and 1) correspond naturally to simple, reliable two-state electronic switching (such as a transistor being on/off, or a voltage being high/low), which is far more practical and less error-prone to build in hardware than circuitry that would need to distinguish ten different reliable states, as decimal would require.",
    "Both CRT and LCD monitors are visual display units (VDUs) — output devices that present the computer's processed results to the user as images on a screen, though they use different underlying display technologies.",
    "Central Processing Unit (CPU)",
    "Coding first, then problem definition, then algorithm design, then testing",
    "Compaq released the first true IBM PC-compatible clone in March 1983, proving that other manufacturers could legally build machines compatible with IBM's PC standard — a landmark moment that opened up the personal computer market to competition.",
    "Computer software is a set of computer programs, and possibly associated data, held in computer storage, such that the processor may execute the programs (and use the data) to perform some specific purpose.",
    "Control Unit (CU)",
    "Control Unit (CU), which only directs and sequences other components",
    "Converting the decimal number 13 to binary gives:",
    "Converting the decimal number 26 to octal (base 8) gives:",
    "Cutting the power abruptly always makes the computer start up noticeably faster next time",
    "DIM",
    "Data first enters the system through an input device, the CPU (control unit and ALU, aided by memory) processes it, and the results are then presented through an output device; storage devices can save data/programs before, during, or after this cycle.",
    "Desktops, laptops, and tablets are all microcomputers — general-purpose computers built around a single microprocessor, intended for use by an individual user, differing mainly in their form factor and portability.",
    "Diligence describes a computer's ability to perform the same repetitive task over and over, for as long as required, without becoming tired, bored, or less accurate — something humans cannot sustain indefinitely.",
    "Diligence — it can perform repetitive tasks without getting tired or losing consistency",
    "Disabling all security software so that the computer runs somewhat faster",
    "Dividing 26 by 8 gives a quotient of 3 with a remainder of 2 (since 3×8=24, and 26−24=2). Reading the remainder then the final quotient gives 32 in octal. Checking: 32(base 8) = 3×8 + 2×1 = 24+2 = 26.",
    "During booting, the small program stored in ROM/firmware that performs initial hardware checks and then locates and loads the operating system is generally known as the:",
    "EDVAC and the Manchester Baby were pioneering first-generation, stored-program computers built in the vacuum-tube era, and their design (including early magnetic core memory concepts) heavily influenced the architecture of computers that followed.",
    "END",
    "Early machines such as EDVAC and the Manchester Baby, which used magnetic core memory and stored-program concepts, belong to which generation of computers?",
    "Email is a service for exchanging digital messages — including text and file attachments — between users over a network, with each message routed to a specific mailbox identified by an email address.",
    "Exponentiation (^) is performed before multiplication, following BASIC's standard order of precedence",
    "First-generation computers used vacuum tubes as their switching components; second-generation computers replaced these with transistors, which were smaller, more reliable, generated less heat, and consumed less power.",
    "Frequently exposing the drive to strong magnetic fields near its casing",
    "GIGO reflects the fact that a computer has no judgement of its own: if it is given incorrect or poor-quality data or instructions, it will faithfully process them and produce incorrect or poor-quality results.",
    "GOTO",
    "Good information-management/security practice includes keeping antivirus software updated so it can detect newer threats, regularly backing up important data in case of infection or failure, and avoiding suspicious downloads, links, or attachments that commonly deliver malware.",
    "HTTP stands for HyperText Transfer Protocol — the standard set of rules that web browsers and web servers use to request and deliver web pages and other resources over the internet.",
    "HTTP, the protocol used to transfer webpages between a web server and a web browser, stands for:",
    "Hard disks contain sensitive mechanical and magnetic components; proper shutdown procedures, avoiding physical shocks or vibration while running, and keeping the drive away from dust, excess heat, and magnetic fields all help protect stored data and extend the disk's working life.",
    "Hardware Terminal Transfer Point",
    "Hardware alone, without any software, is what most users interact with directly",
    "Hardware is a subtype of software, since every physical component is really a program running in the background",
    "Hardware is the physical machine, but on its own it can only follow instructions — those instructions are the software. The two work together: software directs what the hardware should do.",
    "Hardware refers to the physical components of a computer system — the parts you can physically touch, such as the keyboard, monitor, processor chip and storage devices.",
    "High-Traffic Transmission Program",
    "Home Terminal Text Processor",
    "HyperText Transfer Protocol",
    "IF...THEN...ELSE is BASIC's conditional (selection) statement: if the condition is true, the THEN branch runs; if it is false, the ELSE branch runs instead — allowing the program to make a decision.",
    "INPUT",
    "In BASIC's standard operator precedence, when an expression contains both exponentiation (^) and multiplication (*), which operation is performed first?",
    "In BASIC's standard precedence rules, exponentiation (^) has a higher priority than multiplication and division, which in turn have higher priority than addition and subtraction — so exponentiation is evaluated first unless parentheses dictate otherwise.",
    "In BASIC, an IF...THEN...ELSE statement is used to:",
    "In BASIC, the statement used to accept a value typed by the user at the keyboard and store it in a variable is:",
    "In Java inheritance, the class that inherits (Dog, using 'extends') is called the subclass, while the class it inherits from (Animal) is called the superclass. The subclass automatically gains the superclass's accessible fields and methods.",
    "In Java's inheritance model, if class Dog extends class Animal, then Dog is called the ___ and Animal is called the ___.",
    "In Java's object-oriented model, a class is best described as:",
    "In Java, the boolean literals are exactly the lowercase keywords true and false. \"true\" (in quotes) is a String, True is not a recognised keyword (Java is case-sensitive), and 1 is an int, not a boolean.",
    "In Java, which primitive data type would be most appropriate for storing a single true/false value?",
    "In a bus topology, every device is connected to one single shared central cable (the 'bus'), and data sent by one device travels along this shared cable to reach the others.",
    "In a relational database, data is typically organised into structures made up of rows and columns, known as:",
    "In a ring network topology, each device is connected to exactly two neighbouring devices, forming:",
    "In a star network topology, all the devices on the network are connected:",
    "In a star topology, every device connects individually to a central device (like a hub or switch); all communication between devices passes through this central point rather than device-to-device directly.",
    "In a typical domain name such as 'www.unn.edu.ng', the part '.edu' generally indicates that the website belongs to:",
    "In computing, the physical, touchable parts of a computer system (the keyboard, monitor, CPU chip, disk drives, etc.) are collectively called:",
    "In hexadecimal notation, the letter 'C' represents which decimal value?",
    "In hexadecimal, the letters A–F extend the digit set beyond 9: A=10, B=11, C=12, D=13, E=14, F=15. So the hexadecimal digit 'C' represents the decimal value 12.",
    "In problem solving with computers, an algorithm is best defined as:",
    "In standard flowchart notation, an oval (rounded) shape is conventionally used to represent:",
    "In standard flowchart notation, which symbol shape is used to represent a decision (a point where the flow branches based on a condition, e.g. yes/no)?",
    "In the 1's complement method of representing signed binary numbers, the negative of a binary number is obtained by:",
    "In the BASIC programming language, which statement is used to display output to the screen, such as printing the value of a variable?",
    "In the Java programming language, which of these is a valid, legal identifier (variable name)?",
    "In the basic data-flow model of a computer, the correct general order of operation is:",
    "Independent judgement — it can decide on its own what task to perform without any instructions",
    "Input unit, which only accepts data from outside the computer",
    "Instant Messaging (IM) differs from email mainly in that IM is generally designed for:",
    "Instant Messaging is designed for immediate, real-time text conversation between users who are simultaneously online, unlike email, which is typically used for less time-sensitive, asynchronous messages that may not be read immediately.",
    "It does not predate electronic computers",
    "It is a category of application software used to manage office documents",
    "It is a purely decorative cover fitted over the outside of the computer case",
    "It is a type of input device used to type commands directly into the computer",
    "It is the main circuit board that houses/connects the CPU, memory, and other core components via buses and slots",
    "It makes no real difference either way, since both methods stop the computer identically",
    "Java identifiers must start with a letter, underscore, or dollar sign (never a digit), cannot contain characters like a hyphen, and cannot be one of Java's reserved keywords (like 'class'). 'totalSum' satisfies all these rules.",
    "Java's boolean type holds exactly one of two literal values, true or false, making it the correct choice for representing a logical true/false condition.",
    "John Napier invented 'Napier's Bones', a set of numbered rods that could be used to perform multiplication and division mechanically — an important early aid to calculation that came well before electronic computers.",
    "John Napier, a Scottish mathematician, made an important early contribution to computing history by inventing:",
    "Keeping antivirus software installed and updated, backing up important data regularly, and avoiding untrusted downloads/links",
    "Malicious software that attaches itself to legitimate files/programs and can replicate itself by infecting other files when the host program runs is generally known as a computer:",
    "Malware that disguises itself as a legitimate or useful program, but secretly carries out harmful actions once run, is known as a:",
    "Malware that secretly monitors a user's activity (such as keystrokes or browsing habits) and sends that information to a third party without consent is called:",
    "Multiplication is always performed before exponentiation in every expression",
    "Napier's Bones, a manual calculating tool that simplified multiplication and division",
    "None of the above — this is impossible",
    "None — they were never built",
    "One important reason to properly 'safely remove' or 'eject' a USB flash drive before physically unplugging it is to:",
    "One key advantage of using a proper Database Management System (DBMS) over storing related data in many separate, disconnected files is that a DBMS:",
    "Output unit",
    "Output unit, which only presents already-processed results",
    "PRINT",
    "Primary (main) memory temporarily holds the data and instructions the CPU needs while actively processing a task. Unlike secondary storage, most primary memory (RAM) loses its contents when power is removed.",
    "Primary memory (main memory) in a digital computer is used to:",
    "Problem definition/analysis, algorithm/flowchart design, coding (writing the program), then testing and debugging",
    "Pseudocode expresses the logical steps of an algorithm in structured, plain, English-like statements, letting a programmer plan a solution's logic without worrying about the precise syntax rules of a specific programming language.",
    "Pseudocode is best described as:",
    "RAM",
    "RAM (Random Access Memory) is best described as:",
    "RAM is volatile primary memory: the CPU can read from and write to it very quickly while the computer is on, but its contents are lost as soon as power is removed — unlike secondary storage such as a hard disk.",
    "RANDOMIZE is used in BASIC to seed the random-number generator (often using the system clock), so that each time the program runs, its sequence of pseudo-random numbers (generated by functions like RND) differs rather than repeating identically.",
    "REM",
    "ROM (Read-Only Memory) differs from RAM mainly because ROM:",
    "ROM holds data — often firmware or startup instructions — that is written once (or rarely) and is not meant to be altered by normal running programs; crucially, unlike RAM, it is non-volatile, so it retains its contents even when the power is off.",
    "Real-time audio-and-video communication between two or more people at different locations, using computers/devices over a network, is generally called:",
    "Regularly opening email attachments from unknown senders without checking them",
    "Restarting a computer that is already switched on (for example, using a 'Restart' menu option) without turning the power completely off first is known as a:",
    "Secondary storage",
    "Sharing passwords freely with anyone who happens to ask for them",
    "Shutting the computer down abruptly by cutting power while it is still writing data",
    "Shutting the system down properly, avoiding physical shocks/vibration, and keeping it away from dust and extreme heat",
    "Software can be broadly defined as:",
    "Software can be expressed as software = program(s) [+ data] — software is made up of one or more programs, and may optionally include the data those programs work with.",
    "Software is completely independent of hardware and can run without any physical machine",
    "Software provides the instructions that the hardware carries out; the two work together to accomplish tasks",
    "Speed refers to a computer's ability to process enormous numbers of instructions within a very short time, typically measured in operations per second (e.g. millions or billions of instructions per second).",
    "Speed — it performs operations in fractions of a second",
    "Spyware is malicious software that covertly gathers information about a user's activity, such as keystrokes, browsing history, or personal data, and transmits it to a third party without the user's knowledge or consent.",
    "Starting up a computer that is completely powered off, running its full Power-On Self-Test (POST) and loading the operating system from scratch, is known as a:",
    "Stepwise refinement (also called top-down design) is the technique of starting with a broad statement of a problem and progressively breaking it into smaller, more detailed sub-steps, refining each one further until every step is simple and precise enough to be coded directly.",
    "Storage capacity refers to a computer's ability to store vast quantities of data and instructions, which can later be retrieved as needed, in devices such as hard disks and other secondary storage media.",
    "Storing the computer in a very humid, dusty environment for long periods",
    "Supercomputers are the most powerful class of computers, capable of extremely high-speed processing, and are used for computation-intensive tasks like weather forecasting, scientific simulations, and cryptography — well beyond the needs of an individual user.",
    "Systems software (like the operating system, compilers, and device drivers) exists to run and manage the computer itself. A word processor is application software — it exists to help the user accomplish a specific real-world task, such as writing a document.",
    "Teleconferencing (specifically videoconferencing when it includes live video) allows people at different physical locations to communicate in real time over a network using audio, and often video, rather than meeting in person.",
    "Testing first, then coding the program, then finally defining the problem",
    "The '.edu' segment of a domain name is a top-level domain conventionally used to indicate that a website belongs to an educational institution, such as a university.",
    "The 1's complement of a binary number is found by simply inverting every bit: each 0 is changed to a 1, and each 1 is changed to a 0. For example, the 1's complement of 0101 is 1010.",
    "The 2's complement of a binary number is computed by first taking its 1's complement (inverting every bit), and then adding 1 to that result. 2's complement is the standard method computers use to represent negative numbers.",
    "The 2's complement of a binary number is obtained by:",
    "The Apple I, credited as one of the first personal computers created by Steve Wozniak (with Steve Jobs), was introduced in:",
    "The Apple I, designed largely by Steve Wozniak, was introduced by Apple Computer in 1976, marking Apple's entry into the personal computer market.",
    "The Arithmetic and Logic Unit (ALU) is the subsystem responsible for carrying out arithmetic operations (addition, subtraction, multiplication, division) and logical operations (such as AND, OR, and comparisons like greater-than/less-than).",
    "The BASIC function RANDOMIZE is typically used to:",
    "The BIOS (or, on modern systems, UEFI firmware) performs the Power-On Self-Test and then hands control to a bootloader, which locates and loads the operating system into memory — this sequence is what allows the computer to become usable after being switched on.",
    "The Central Processing Unit (CPU) is made up of the Control Unit, which directs operations, and the Arithmetic and Logic Unit, which performs computations — together they form the 'brain' of the computer.",
    "The Control Unit (CU) and the Arithmetic and Logic Unit (ALU), taken together, form the:",
    "The Control Unit (CU) directs the operation of the computer: it fetches instructions from memory, decodes them, and coordinates/directs the ALU, memory, and input/output units to carry each instruction out.",
    "The IBM Personal Computer (IBM PC), released in 1981, is widely credited as the first PC-compatible machine, and it established the hardware/software standard that later 'PC clone' manufacturers (like Compaq in 1983) would follow.",
    "The INPUT statement in BASIC pauses the program, waits for the user to type a value at the keyboard, and stores whatever is typed into the named variable.",
    "The PRINT statement in BASIC is used to display text or the value of a variable/expression on the screen as output.",
    "The abacus is one of the oldest known calculating tools, used by ancient civilisations (including the Chinese) thousands of years before the invention of any electronic computer, making it a foundational milestone in the pre-history of computing.",
    "The abacus, one of the earliest known devices used to aid counting and calculation, originates from ancient civilisations and predates electronic computers by:",
    "The binary number 1010 is equivalent to which decimal value?",
    "The binary number system has a base (radix) of 2, meaning it uses only two digits — 0 and 1 — to represent all values; this maps naturally onto a digital computer's two physical states (on/off, high/low voltage).",
    "The binary number system, used internally by digital computers, is a number system with base:",
    "The characteristic of a computer that describes its ability to perform millions of instructions every second is called:",
    "The fastest and most powerful class of computers, typically used for extremely complex tasks such as weather forecasting and nuclear simulations, is called:",
    "The form in which a program is written by a programmer, before it is transformed into the CPU's native machine language, is called:",
    "The hexadecimal number system has base 16, using sixteen digit symbols: 0 through 9 for the first ten values, and the letters A, B, C, D, E, F to represent the values 10 through 15.",
    "The hexadecimal number system, commonly used as a compact way to represent binary values, uses base:",
    "The motherboard is the main printed circuit board of a computer; the CPU, memory chips, and expansion cards plug into it, and its buses/circuitry allow these components to communicate with each other.",
    "The octal number system has base 8, and it uses exactly eight distinct digit symbols: 0, 1, 2, 3, 4, 5, 6, and 7 — never 8 or 9, since those values would need to be represented using two digits (e.g. 8 in decimal is 10 in octal).",
    "The octal number system uses which base, and which set of digits?",
    "The operating system may still be writing data to a USB flash drive even after a copy appears to finish. Safely ejecting it ensures all pending writes are completed and the connection is closed cleanly, preventing corrupted or lost data.",
    "The oval (or rounded rectangle) is the standard terminator symbol in flowcharting, used to mark the single starting point ('Start') and the ending point(s) ('Stop'/'End') of an algorithm.",
    "The saying 'Garbage In, Garbage Out' (GIGO) in computing means that:",
    "The standard problem-solving process is: first understand and define the problem, then design a solution as an algorithm or flowchart, then translate that design into actual program code, and finally test and debug the program to confirm it works correctly.",
    "The transition from vacuum tubes to transistors marks the boundary between which two generations of computers?",
    "The unit of a digital computer that performs arithmetic operations (like addition and subtraction) and logical operations (like comparisons) is the:",
    "The user interface element that represents a program, file, or function using a small picture, which the user can click or double-click to activate, is called a(n):",
    "The very first PC clone (a non-IBM machine that was compatible with the IBM PC standard) was released by Compaq in:",
    "There is no meaningful order at all; every stage happens simultaneously",
    "There is no real engineering reason behind the choice at all; it was simply an arbitrary early convention",
    "There was never such a transition",
    "They are always performed strictly left to right, regardless of which operator appears",
    "Trojan horse",
    "True",
    "Unlike a human, a computer can repeat the same task thousands of times without a drop in accuracy or the need to rest. This characteristic is called:",
    "Unlike a virus, a computer worm is distinguished mainly by its ability to:",
    "Versatility describes a computer's capability to carry out many different kinds of tasks, simply by running different programs, rather than being limited to a single fixed function.",
    "Which best describes the purpose of the system unit's motherboard?",
    "Which characteristic of computers refers to their ability to hold enormous amounts of data and instructions for later retrieval?",
    "Which input device is specifically designed to convert sound (such as a user's voice) into an electrical/digital signal the computer can process?",
    "Which of the following best describes an email (electronic mail) system?",
    "Which of the following best describes the relationship between hardware and software in a working computer system?",
    "Which of the following correctly orders the typical stages of solving a problem with a computer, from first to last?",
    "Which of the following is NOT one of the widely recognised general characteristics of a digital computer?",
    "Which of the following is a recommended basic practice for managing information and protecting a computer against malware?",
    "Which of the following is a valid Java boolean literal?",
    "Which of the following is an example of application software rather than systems software?",
    "Which of these best matches the four basic functional subsystems commonly identified in a digital computer's architecture?",
    "Which of these is a secondary (auxiliary) storage device rather than a primary memory type?",
    "Which of these is primarily an input device rather than an output device?",
    "Which of these is the best distinguishing feature of a laptop computer compared to a desktop PC?",
    "Which practice best helps in caring for and prolonging the life of a hard disk?",
    "Which relationship correctly describes how software relates to a computer program and its data?",
    "Which subsystem directs and coordinates the operations of the entire computer, fetching instructions from memory and telling other units what to do?",
    "Why do digital computers use the binary number system internally, rather than the decimal system humans normally use?",
    "Why is it recommended to always shut a computer down properly through the operating system's shutdown command, rather than simply cutting off the power?",
    "a blueprint/template that defines the data members (fields) and methods that objects created from it will have",
    "a closed loop (circle) through which data typically travels in one direction around the ring",
    "a commercial business",
    "a compiler that translates source code into machine language",
    "a completely random arrangement with no predictable connection pattern",
    "a database management system",
    "a decision point where the flow branches based on a condition",
    "a device driver that lets the operating system control a printer",
    "a diagram made only of geometric shapes and directional arrows, with no written words at all",
    "a diamond (rhombus)",
    "a few decades",
    "a few years",
    "a finite, well-defined, ordered sequence of steps that solves a specific problem",
    "a general processing step, such as a calculation or an assignment",
    "a government military branch",
    "a hardware component that stores data permanently even when the computer's power is switched off",
    "a loop construct used to repeat a block of statements",
    "a loop counter used to track how many times a loop has repeated",
    "a network protocol used to exchange data between computers",
    "a parallelogram",
    "a payroll application used by a company's accounts department to calculate staff salaries",
    "a personal blog with no organisational affiliation",
    "a physical hardware component located inside the CPU chip itself",
    "a physical input device used to enter commands directly into the computer's memory",
    "a plotter driver",
    "a processing or calculation step performed part-way through the algorithm",
    "a program that allocates memory space and CPU time to other running programs",
    "a random guess at a solution, made without any planning at all",
    "a rectangle",
    "a reserved keyword belonging to a particular programming language",
    "a sequence of instructions to be followed by the CPU to perform a specific task",
    "a set of computer programs (and possibly associated data) held in storage that instructs the computer to perform a specific task",
    "a set of parallel wires/pathways that carry data, addresses, or control signals between components of the computer",
    "a single numeric value stored temporarily while a program is running",
    "a single point-to-point link connecting only two devices in total",
    "a spreadsheet application used to prepare and track a household or business budget",
    "a spreadsheet of numbers only, with no symbols or arrows involved",
    "a systems program that manages files stored on the hard disk",
    "a tree-shaped hierarchy with a single root device at the very top",
    "a type of computer hardware installed inside the system unit",
    "a type of computer virus that spreads through email attachments",
    "a type of input device used to enter commands into a program",
    "a type of malware that secretly monitors a user's activity",
    "a type of printer that transfers ink from a cartridge onto paper",
    "a type of secondary storage medium like a hard disk",
    "a word processor used to write a letter",
    "accuracy",
    "adding 1 to every bit of the original binary number in turn",
    "always execute both branches together, regardless of the condition's value",
    "always requires far more storage space, with no other real benefit",
    "an educational institution",
    "an examination marking program used by a school to grade multiple-choice test scripts",
    "an external data source located outside the algorithm",
    "an informal, English-like way of expressing an algorithm's logic without following the strict syntax rules of any real programming language",
    "an input or output operation such as reading or displaying a value",
    "an office application (application software)",
    "an operating system kernel",
    "an output device for printing documents",
    "an oval",
    "antivirus program",
    "any electronic device that is physically plugged into the computer's ports to expand its capability",
    "backup utility",
    "base 10, using digits 0 through 8",
    "base 16, using digits 0 through 7",
    "base 8, using digits 0 through 7",
    "base 8, using digits 0 through 9",
    "batch processing only",
    "binary code",
    "binary machine code that the processor executes directly without translation",
    "binary, octal, decimal, and hexadecimal",
    "boolean",
    "breaking a complex problem down gradually into smaller and smaller, more manageable sub-steps until each is simple enough to implement directly",
    "browsing pages and resources on the World Wide Web",
    "bus topology",
    "cache memory",
    "can be freely rewritten by any running application at any time, just like RAM",
    "can only ever be used together with a mouse, and never with a keyboard",
    "capacity",
    "capture/accept data, process it according to rules, produce results, and store them for future use",
    "char",
    "class",
    "cold boot",
    "cold boot from a fully powered-off state",
    "compiler",
    "compiling programming source code into machine language",
    "computers can automatically detect and correct wrong data before processing it further",
    "computers physically discard bad data as waste output rather than processing it at all",
    "connects computers and devices within a small, limited geographical area, such as a single building or campus",
    "convert analogue electrical signals into digital signals for the processor only",
    "convert numbers between binary and hexadecimal representations",
    "convert the files stored on it to a different file format",
    "converting a finished program from one programming language into another",
    "converting the binary number directly into its hexadecimal equivalent",
    "converting the number to decimal first and then multiplying it by −1",
    "create a sequence of visual slides — combining text, images, and other media — to support an oral presentation to an audience",
    "creativity",
    "cursor",
    "data",
    "data is placed into storage before any input is ever collected from the user",
    "declare the size of an array before values are stored in it",
    "define, create, maintain, and control access to a structured collection of related data (a database)",
    "design flowchart shapes only, with no data-analysis features at all",
    "digital camera",
    "diligence",
    "directly to a single central device (such as a switch or hub), rather than directly to each other",
    "disk defragmentation of the hard drive",
    "disk formatting of a storage device",
    "dividing the original binary number by 2 and discarding the remainder",
    "eliminates the need for any input devices connected to the computer",
    "embedded computers",
    "embedded operating system only",
    "emotion",
    "ensure that all pending write operations have finished, preventing data corruption or loss",
    "factory reset that erases all user data",
    "fifth generation (AI era)",
    "firewall",
    "firmware",
    "firmware built permanently into a hardware chip",
    "firmware only",
    "first generation (vacuum-tube era)",
    "first generation to second generation",
    "float",
    "flowcharting an algorithm's logic",
    "flowcharts",
    "fourth generation (microprocessor era)",
    "fourth generation to fifth generation",
    "hard disk",
    "hardware",
    "hardware, software, firmware, and middleware",
    "has no practical size limit at all, regardless of distance",
    "has no relationship to the operating system whatsoever, unlike a GUI",
    "helps reduce data duplication/inconsistency and provides controlled, structured access to related data through queries",
    "hibernation",
    "icon",
    "ignore all timing requirements entirely and respond whenever convenient",
    "improve a computer's processing speed by optimising its memory usage",
    "in a single closed loop, with data passing around it and no central device at all",
    "increase the drive's total available storage capacity",
    "input data enters, the CPU processes it using memory, and results are sent to output (with storage available throughout)",
    "input data from a file only, never from the keyboard",
    "input devices used to capture data from the user",
    "input unit, which only captures data entered by the user",
    "input, processing (CPU/memory), output, and storage",
    "int",
    "interface; package",
    "intuition",
    "inverting (flipping) every bit of the original number — every 0 becomes 1 and every 1 becomes 0",
    "is a type of output device used to present processed results to the user",
    "is always faster and easier to learn for a first-time computer user than a GUI is",
    "is always physically larger in storage capacity than the computer's RAM",
    "joystick",
    "kernel",
    "keyboard",
    "keyboard, mouse, monitor, and printer only",
    "laptop",
    "leaving the original binary number completely unchanged throughout",
    "light pen",
    "mainframe computer",
    "mainframes",
    "make the program choose between two alternative sets of actions, depending on whether a stated condition is true or false",
    "makes it completely impossible to ever update the stored data afterward",
    "manage a searchable database of a company's customer records",
    "manage and regulate the electrical power supplied to the computer",
    "manage the settings and configuration of a computer's operating system",
    "menu",
    "menus",
    "mesh topology",
    "method; object",
    "microcomputer",
    "microcomputers",
    "microphone",
    "minicomputer only used by large organisations",
    "minicomputers used only in industrial control rooms",
    "modem",
    "monitor",
    "mouse",
    "multi-user operating system",
    "multi-user, multi-task",
    "near real-time, back-and-forth text conversation between users who are online at the same time",
    "network operating system only",
    "number-base conversion between systems",
    "object code",
    "old, slower computers always produce worse results than newer ones, regardless of the input",
    "only affect printed documents that have already left the printer",
    "only connect separate computers together over a network without doing any computation itself",
    "only display pre-recorded video content without ever accepting new data or instructions",
    "only display static images stored on the computer's hard disk",
    "only ever connects exactly two computers, however far apart they are",
    "only run a single program once every week, regardless of demand",
    "only spoken word descriptions read aloud, with no diagrams of any kind",
    "only store files permanently without ever processing or transforming the data it holds",
    "only the operating system, since every other program is really considered part of the hardware",
    "organising data into a grid of cells and automatically performing calculations, such as sums, averages, and formulas, across that data",
    "output devices used to visually display processed information",
    "output is generated first, then the data is processed, and only afterward is it input",
    "output unit, which only displays or prints results",
    "perform mathematical/statistical computations and analysis on data, such as computing averages, correlations, or running data models",
    "peripheral",
    "permanent, non-volatile storage that keeps data even when the power is off",
    "permanently archive data for years even with the power switched off completely",
    "permanently archiving files, with no communication feature involved at all",
    "permanently delete a variable from the running program",
    "personal digital assistants",
    "physically damage the keys and casing of the computer's keyboard",
    "physically manufacture the computer's hardware components",
    "physically print processed output onto paper for the user to keep",
    "physically repair and replace faulty computer hardware components",
    "playing video files stored on the computer's hard disk",
    "plotter",
    "primary storage devices used to hold data temporarily",
    "printing documents remotely on a printer in another location",
    "process and respond to inputs within a strict, guaranteed, very short time limit, which is critical for tasks like industrial control systems",
    "protocol",
    "provided a formal mathematical model of computation that underlies the theory of what any computer can compute",
    "real-time only",
    "real-time, multi-user",
    "recharge the flash drive's internal battery before storing it",
    "register",
    "registers",
    "removing all the comments from a finished, already-working program",
    "removing the leftmost bit of the original number entirely",
    "requires the user to type text commands, while a GUI lets the user interact using windows, icons, menus, and a pointing device",
    "rigidity",
    "ring topology",
    "run exclusively on supercomputers, never on smaller dedicated devices",
    "scanner",
    "scrollbar",
    "secondary storage unit, which only retains data long-term",
    "seed/reinitialise the random-number generator so a program's sequence of 'random' numbers varies between runs",
    "semi-permanently holds data such as startup instructions, cannot be changed by ordinary programs, and keeps its contents without power",
    "send a document to the printer for a paper copy",
    "sending large physical packages through a postal courier service",
    "single-task operating system",
    "single-user, multi-tasking",
    "single-user, single-task",
    "single-user, single-task only",
    "soft shutdown",
    "software",
    "software = program(s) + data always combined, meaning a program can never exist or run without its own dedicated data",
    "software = program(s) [+ data], meaning software consists of one or more programs, optionally together with associated data",
    "software is only the data files a computer holds, never the instructions that tell it what to do with them",
    "software is unrelated to programs entirely; software refers only to the physical media the programs happen to be stored on",
    "sort an array of numbers into ascending or descending order",
    "source code",
    "spans an entire continent, connecting cities across several countries",
    "speaker",
    "speed",
    "spread and replicate across networks and computers on its own, without needing to attach itself to a host file or needing a user to run an infected program",
    "spreadsheet",
    "spreadsheet macro used to automate repeated calculations",
    "spyware",
    "standardised geometric symbols (such as ovals, rectangles, diamonds) connected by arrows to show the sequence and flow of steps",
    "star topology",
    "storage",
    "storage capacity",
    "subclass; superclass",
    "superclass; subclass",
    "supercomputer",
    "supercomputers",
    "systems software that manages the computer's own hardware",
    "tables",
    "tablet",
    "taking the 1's complement of the number and then adding 1 to the result",
    "taskbar",
    "teleconferencing (videoconferencing)",
    "temporarily hold data and instructions that the CPU is currently working with",
    "the ALU produces finished output directly, with no control unit involvement at all",
    "the final printed output produced once a program has finished running",
    "the first high-level programming language used to write software",
    "the low-level machine code produced automatically after a program has been compiled",
    "the metal casing and internal frame that physically protects the computer's electronic components",
    "the microprocessor used in modern electronic computers",
    "the modern electronic transistor used in second-generation computers",
    "the operating system that manages the computer's hardware resources",
    "the physical wiring and circuitry inside the CPU that carries its electrical signals",
    "the plastic casing that forms the outer shell of the system unit",
    "the quality/correctness of a computer's output depends entirely on the quality/correctness of the input and instructions it was given",
    "the standardised address used to locate a specific resource (such as a webpage) on the internet",
    "the start of the flowchart only, never anything else",
    "the start or end (terminator) of the flowchart",
    "third generation to fourth generation",
    "thousands of years",
    "to every other device individually, with cabling but no central connecting point",
    "total-sum",
    "totalSum",
    "translate text from one human spoken language into another",
    "true",
    "types of printers that produce output on paper",
    "using only wireless satellite links, with no cabling anywhere in the network",
    "versatility",
    "virus",
    "volatile primary memory whose contents are lost when power is removed",
    "warm boot",
    "warm boot (or 'warm reboot')",
    "was a physical PC sold commercially to members of the public",
    "was a type of printer used for high-speed line drawings",
    "was the first hard disk drive installed inside a working computer",
    "web browser used to access pages on the internet",
    "word processor used to type and format documents",
    "writing the entire complex program in one single step with no planning beforehand",
  ];

  testWidgets(
    'every COS101 field renders without a hard failure',
    (WidgetTester tester) async {
      final List<String> broken = <String>[];
      for (final String field in fields) {
        await tester.pumpWidget(
          MaterialApp(home: Scaffold(body: MathText(field))),
        );
        await tester.pumpAndSettle();
        final Object? err = tester.takeException();
        final bool hasMath = MathText.hasMath(field);
        final bool mathWidgetExists = !hasMath || find.byType(Math).evaluate().isNotEmpty;
        if (err != null) {
          // A Math widget existing in the tree despite an exception means
          // the formula parsed and built fine -- the exception is a
          // downstream debug-only layout assertion from this test's bare,
          // unconstrained-width harness (unlike the real app's cards/lists),
          // not a parsing failure. A release build never throws on layout
          // overflow, so that case is a soft pass here.
          if (!mathWidgetExists) {
            broken.add('EXCEPTION (\$err): \$field');
          }
          continue;
        }
        if (!mathWidgetExists) {
          broken.add('FALLBACK (no Math widget rendered): \$field');
        }
      }
      expect(broken, isEmpty, reason: broken.join('X'));
    },
  );
}
