// Auto-generated: every distinct question/option/explanation field
// from the MTH121 bank, verified against the real
// flutter_math_fork renderer via MathText's mixed prose+LaTeX path.
import 'package:eduvora/core/widgets/math_text.dart';
import 'package:flutter/material.dart';
import 'package:flutter_math_fork/flutter_math.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  final List<String> fields = <String>[
    "\$(-1, 1)\$",
    "\$(-4, -8)\$",
    "\$(-4, 8)\$",
    "\$(-\\infty, 2)\$",
    "\$(-\\infty, \\infty)\$",
    "\$(-\\infty,-1)\$",
    "\$(0, 2)\$",
    "\$(1 - x)e^{x} + C\$",
    "\$(1, \\infty)\$",
    "\$(1/2)ln|2x+1| + C\$",
    "\$(1/5)e^{5x} + C\$",
    "\$(2, \\infty)\$",
    "\$(4, -8)\$",
    "\$(4, 8)\$",
    "\$(f \\cdot g)(1) = f(1) \\cdot g(1)\$. Substituting \$x=1\$: \$f(1) = 1^{2} - 4 = -3\$ and \$g(1) = 1 + 2 = 3\$, so \$(f \\cdot g)(1) = -3 \\cdot 3 = -9\$.",
    "\$(f \\cdot g)(2) = f(2) \\cdot g(2)\$. Substituting \$x=2\$: \$f(2) = 2^{2} + 2 = 6\$ and \$g(2) = 2 \\cdot 2 - 1 = 3\$, so \$(f \\cdot g)(2) = 6 \\cdot 3 = 18\$.",
    "\$(f \\cdot g)(3) = f(3) \\cdot g(3)\$. Substituting \$x=3\$: \$f(3) = 2 \\cdot 3 + 1 = 7\$ and \$g(3) = 3^{2} = 9\$, so \$(f \\cdot g)(3) = 7 \\cdot 9 = 63\$.",
    "\$(f \\cdot g)(4) = f(4) \\cdot g(4)\$. Substituting \$x=4\$: \$f(4) = 3 \\cdot 4 = 12\$ and \$g(4) = 4 - 5 = -1\$, so \$(f \\cdot g)(4) = 12 \\cdot -1 = -12\$.",
    "\$(f \\circ g)(-1) = f(g(-1))\$. First find \$g(-1)\$ by substituting \$x=-1\$ into \$g(x) = x + 2\$: \$g(-1) = -1 + 2 = 1\$. Then substitute \$g(-1) = 1\$ into \$f(x) = x^{2} - 1\$: \$f(1) = 1^{2} - 1 = 0\$. So \$(f \\circ g)(-1) = 0\$.",
    "\$(f \\circ g)(1) = f(g(1))\$. First find \$g(1)\$ by substituting \$x=1\$ into \$g(x) = 2 x - 5\$: \$g(1) = 2 \\cdot 1 - 5 = -3\$. Then substitute \$g(1) = -3\$ into \$f(x) = \\left|{x}\\right|\$: \$f(-3) = \\left|{-3}\\right| = 3\$. So \$(f \\circ g)(1) = 3\$.",
    "\$(f \\circ g)(1) = f(g(1))\$. First find \$g(1)\$ by substituting \$x=1\$ into \$g(x) = 3 x - 1\$: \$g(1) = 3 \\cdot 1 - 1 = 2\$. Then substitute \$g(1) = 2\$ into \$f(x) = x^{2}\$: \$f(2) = 2^{2} = 4\$. So \$(f \\circ g)(1) = 4\$.",
    "\$(f \\circ g)(1) = f(g(1))\$. First find \$g(1)\$ by substituting \$x=1\$ into \$g(x) = x^{2} + 3\$: \$g(1) = 1^{2} + 3 = 4\$. Then substitute \$g(1) = 4\$ into \$f(x) = 4 - 2 x\$: \$f(4) = 4 - 2 \\cdot 4 = -4\$. So \$(f \\circ g)(1) = -4\$.",
    "\$(f \\circ g)(2) = f(g(2))\$. First find \$g(2)\$ by substituting \$x=2\$ into \$g(x) = x - 1\$: \$g(2) = 2 - 1 = 1\$. Then substitute \$g(2) = 1\$ into \$f(x) = x^{3}\$: \$f(1) = 1^{3} = 1\$. So \$(f \\circ g)(2) = 1\$.",
    "\$(f \\circ g)(2) = f(g(2))\$. First find \$g(2)\$ by substituting \$x=2\$ into \$g(x) = x^{2} + 1\$: \$g(2) = 2^{2} + 1 = 5\$. Then substitute \$g(2) = 5\$ into \$f(x) = 2 x - 3\$: \$f(5) = 2 \\cdot 5 - 3 = 7\$. So \$(f \\circ g)(2) = 7\$.",
    "\$(f \\circ g)(3) = f(g(3))\$. First find \$g(3)\$ by substituting \$x=3\$ into \$g(x) = x^{2} - 2 x\$: \$g(3) = 3^{2} - 2 \\cdot 3 = 3\$. Then substitute \$g(3) = 3\$ into \$f(x) = 3 x + 4\$: \$f(3) = 3 \\cdot 3 + 4 = 13\$. So \$(f \\circ g)(3) = 13\$.",
    "\$(f \\circ g)(3) = f(g(3))\$. First find \$g(3)\$ by substituting \$x=3\$ into \$g(x) = x^{2}\$: \$g(3) = 3^{2} = 9\$. Then substitute \$g(3) = 9\$ into \$f(x) = 5 - x\$: \$f(9) = 5 - 9 = -4\$. So \$(f \\circ g)(3) = -4\$.",
    "\$(f+g)(1) = f(1) + g(1)\$. Substituting \$x=1\$: \$f(1) = 1^{2} - 4 = -3\$ and \$g(1) = 1 + 2 = 3\$, so \$(f+g)(1) = -3 + 3 = 0\$.",
    "\$(f+g)(2) = f(2) + g(2)\$. Substituting \$x=2\$: \$f(2) = 2^{2} + 2 = 6\$ and \$g(2) = 2 \\cdot 2 - 1 = 3\$, so \$(f+g)(2) = 6 + 3 = 9\$.",
    "\$(f+g)(3) = f(3) + g(3)\$. Substituting \$x=3\$: \$f(3) = 2 \\cdot 3 + 1 = 7\$ and \$g(3) = 3^{2} = 9\$, so \$(f+g)(3) = 7 + 9 = 16\$.",
    "\$(f+g)(4) = f(4) + g(4)\$. Substituting \$x=4\$: \$f(4) = 3 \\cdot 4 = 12\$ and \$g(4) = 4 - 5 = -1\$, so \$(f+g)(4) = 12 + -1 = 11\$.",
    "\$(f/g)(x)\$ requires \$g(x) \\neq 0\$ in addition to both \$f\$ and \$g\$ being defined. \$f\$ requires \$x \\neq 2\$; \$g(x)=\\sqrt{x}\$ requires \$x \\geq 0\$ and, to avoid dividing by \$g(x)=0\$, also \$x \\neq 0\$. Combining these: \$x > 0\$ and \$x \\neq 2\$.",
    "\$(x - 1)e^{x} + C\$",
    "\$(x \\cos(x) + \\sin(x))/x^2\$",
    "\$(x \\cos(x) - \\sin(x))/x^2\$",
    "\$(x+3)^2 + 2\$",
    "\$(x-3)^2 + 2\$",
    "\$(x-3)^2 - 2\$",
    "\$-1 + E\$",
    "\$-1 \\leq \\sin(1/x) \\leq 1\$ for every \$x \\neq 0\$, so multiplying through by \$|x|\$ gives \$-|x| \\leq x\\sin(1/x) \\leq |x|\$. As \$x \\to 0\$, both bounds \$-|x|\$ and \$|x|\$ tend to \$0\$, so by the Sandwich (Squeeze) Theorem, \$\\lim_{x \\to 0} x\\sin(1/x) = 0\$.",
    "\$-1\$",
    "\$-1, 1\$",
    "\$-1, 2\$",
    "\$-1, 3\$",
    "\$-1/(x^2 + 1)\$",
    "\$-1/2\$",
    "\$-1/3\$",
    "\$-1/4\$",
    "\$-1/\\cos(x)^2\$",
    "\$-1/\\sqrt{1 - x^2}\$",
    "\$-1/\\sqrt{3} < x < 1/\\sqrt{3}\$",
    "\$-1/x\$",
    "\$-1/x^2 + C\$",
    "\$-1/x^2\$",
    "\$-11/3\$",
    "\$-12\$",
    "\$-125/6\$",
    "\$-12\\pi\$",
    "\$-15/4\$",
    "\$-2 \\cos(2x + 3)\$",
    "\$-2 \\sin(2x + 1) + C\$",
    "\$-2\$",
    "\$-2, 2\$",
    "\$-2/3\$",
    "\$-22/3\$",
    "\$-24\$",
    "\$-27x^4/4 + 36x^3 - 72x^2 + 64x + C\$",
    "\$-2e^{2x - 1}\$",
    "\$-2x \\cos(x^2)\$",
    "\$-2x^2/(x^4 + 2x^2 + 1) - 2x/(x^4 + 2x^2 + 1) + 2/(x^4 + 2x^2 + 1)\$",
    "\$-3 \\cos(3x - 1)\$",
    "\$-3 \\cos(5x)/5 + C\$",
    "\$-3 \\cos(x) + C\$",
    "\$-3 \\cos(x)\$",
    "\$-3 \\leq x \\leq 3\$",
    "\$-3 \\sin(x) + C\$",
    "\$-3\$",
    "\$-3/4\$",
    "\$-32/3\$",
    "\$-39/2\$",
    "\$-3x^2/(x^3 - 2)\$",
    "\$-4\$",
    "\$-4/3\$",
    "\$-4e^{4x}\$",
    "\$-5/(5x - 1)\$",
    "\$-5/9\$",
    "\$-6\$",
    "\$-64\\pi/3\$",
    "\$-6x/(3x^2 + 5)\$",
    "\$-8\$",
    "\$-8/3\$",
    "\$-81x^2 + 216x - 144 + C\$",
    "\$-81x^4/4 + 108x^3 - 216x^2 + 192x + C\$",
    "\$-81x^5/5 - 135x^4 - 450x^3 - 750x^2 - 625x + C\$",
    "\$-8\\pi\$",
    "\$-9\$",
    "\$-\\cos(5x)/5 + C\$",
    "\$-\\cos(x) + C\$",
    "\$-\\cos(x)\$",
    "\$-\\ln(2)/2\$",
    "\$-\\pi/5\$",
    "\$-\\sin(2x + 1)/2 + C\$",
    "\$-\\sin(2x)/2\$",
    "\$-\\sin(x) + C\$",
    "\$-\\sin(x) + \\cos(x)\$",
    "\$-\\sin(x)\$",
    "\$-\\sin(x)^2\$",
    "\$-\\sqrt{x} + 1\$",
    "\$-\\sqrt{x} - 1\$",
    "\$-\\tan(x) + C\$",
    "\$-\\tan(x)\$",
    "\$-e^{\\sin(x)}\\cos(x)\$",
    "\$-x \\cos(x) + C\$",
    "\$-x \\cos(x) + \\sin(x) + C\$",
    "\$-x \\sin(x) + \\cos(x)\$",
    "\$-x \\sin(x) - \\cos(x) + C\$",
    "\$-x \\sin(x)\$",
    "\$-x^2 \\cos(x)/2 + C\$",
    "\$0\$",
    "\$0, 2\$",
    "\$0, 3\$",
    "\$1 - \\sin(x)\$",
    "\$1 <= x <= 3\$",
    "\$1\$",
    "\$1/(3x^2 + 5)\$",
    "\$1/(5x - 1)\$",
    "\$1/(x + 1)\$",
    "\$1/(x^2 + 1)\$",
    "\$1/(x^2 + 2x + 1)\$",
    "\$1/(x^3 - 2)\$",
    "\$1/2\$",
    "\$1/3\$",
    "\$1/4\$",
    "\$1/5\$",
    "\$1/\\cos(x)\$",
    "\$1/\\sqrt{1 - x^2}\$",
    "\$1/x\$",
    "\$1/x^2 + C\$",
    "\$1/x^2\$",
    "\$10\$",
    "\$11\$",
    "\$11/3\$",
    "\$12\$",
    "\$12/5\$",
    "\$125/6\$",
    "\$128\\pi/3\$",
    "\$128\\pi/5\$",
    "\$128x^4 - 1280x^3 + 4800x^2 - 8000x + 5000\$",
    "\$12\\pi\$",
    "\$12x^2 - 2 + C\$",
    "\$12x^2 - 3\$",
    "\$12x^2 - 6\$",
    "\$12x^3\$",
    "\$12x^4\$",
    "\$13\$",
    "\$137/6\$",
    "\$14\$",
    "\$14/3\$",
    "\$143\$",
    "\$14x^6\$",
    "\$14x^7\$",
    "\$15/2\$",
    "\$15/4\$",
    "\$16\$",
    "\$16/3\$",
    "\$16\\pi\$",
    "\$16\\pi/3\$",
    "\$18\$",
    "\$18\\pi\$",
    "\$19\$",
    "\$19/4\$",
    "\$2 + C\$",
    "\$2 \\cos(2x + 3)\$",
    "\$2\$",
    "\$2/(x^2 + 1)\$",
    "\$2/3\$",
    "\$2/5\$",
    "\$20\$",
    "\$20x^3\$",
    "\$21x^2 - 4x + 1\$",
    "\$21x^3 - 4x^2 + x\$",
    "\$22/3\$",
    "\$24\$",
    "\$243x^5/5 + 405x^4 + 1350x^3 + 2250x^2 + 1875x + C\$",
    "\$24\\pi\$",
    "\$24x\$",
    "\$25\$",
    "\$25/3\$",
    "\$27\$",
    "\$27\\pi\$",
    "\$27x^4/4 - 36x^3 + 72x^2 - 64x + C\$",
    "\$28/3\$",
    "\$2\\pi/3\$",
    "\$2\\pi/5\$",
    "\$2e^{2x - 1}\$",
    "\$2e^{2x}\$",
    "\$2ln|2x+1| + C\$",
    "\$2x + 7 + C\$",
    "\$2x \\cos(x)\$",
    "\$2x \\cos(x^2)\$",
    "\$2x \\sin(x)\$",
    "\$2x\$",
    "\$2x/(x - 2)\$",
    "\$2x/(x^2 + 2x + 1) + 1/(x^2 + 2x + 1)\$",
    "\$2x^2 + 14x + C\$",
    "\$2x^2 + 2x\$",
    "\$2x^3 + C\$",
    "\$2x^3 - 4x\$",
    "\$2x^4 - 2x^2 + C\$",
    "\$2x^5/5 + 10x^3/3 + C\$",
    "\$2x^6 - 6x + C\$",
    "\$2x^7 + 5\$",
    "\$3 \\cos(3x - 1)\$",
    "\$3 \\cos(x) + C\$",
    "\$3 \\cos(x)\$",
    "\$3 \\log(2)/2\$",
    "\$3 \\sin(2x + 1)/2 + C\$",
    "\$3 \\sin(x)\$",
    "\$3\$",
    "\$3/2\$",
    "\$3/4\$",
    "\$3/5\$",
    "\$300\$",
    "\$30x^4 + C\$",
    "\$30x^4\$",
    "\$32/3\$",
    "\$324x^3 + 1620x^2 + 2700x + 1500 + C\$",
    "\$32\\pi/5\$",
    "\$32x^3 - 240x^2 + 600x - 500\$",
    "\$33\$",
    "\$35/3\$",
    "\$36x^2\$",
    "\$38\$",
    "\$39/2\$",
    "\$3x + y = -3\$",
    "\$3x\$",
    "\$3x^2 + 2x\$",
    "\$3x^2 + C\$",
    "\$3x^2\$",
    "\$3x^2/(x^2 - 4x + 4) - 4x/(x^2 - 4x + 4)\$",
    "\$3x^2/(x^3 - 2)\$",
    "\$3x^4 + 6x^2 + 3\$",
    "\$3x^4\$",
    "\$4\$",
    "\$4.5\$",
    "\$4/3\$",
    "\$4/5\$",
    "\$41/2\$",
    "\$42x - 4\$",
    "\$48\$",
    "\$4\\pi\$",
    "\$4e^x\$",
    "\$4e^{2x}\$",
    "\$4e^{4x}\$",
    "\$4x^3 + 10x + C\$",
    "\$4x^3 - 2x + C\$",
    "\$4x^3 - 6x\$",
    "\$5 \\cos(5x) + C\$",
    "\$5\$",
    "\$5/(5x - 1)\$",
    "\$5/3\$",
    "\$5/4\$",
    "\$50\$",
    "\$55/2\$",
    "\$56\$",
    "\$5e^{5x} + C\$",
    "\$5x^4\$",
    "\$5x^5\$",
    "\$6\$",
    "\$600\$",
    "\$63\$",
    "\$64/3\$",
    "\$64\\pi/3\$",
    "\$64x^3 - 480x^2 + 1200x - 1000\$",
    "\$65/2\$",
    "\$6\\pi\$",
    "\$6x + C\$",
    "\$6x\$",
    "\$6x/(3x^2 + 5)\$",
    "\$6x^2/(x^4 + 2x^2 + 1) + 2x/(x^4 + 2x^2 + 1) + 2/(x^4 + 2x^2 + 1)\$",
    "\$6x^5 + 12x^3 + 6x\$",
    "\$6x^5 - 16x^3 + 8x\$",
    "\$6x^5 - 3 + C\$",
    "\$6x^5 - 4\$",
    "\$6x^6 - 4x\$",
    "\$6x^7 + 18x^5 + 18x^3 + 6x\$",
    "\$6x^8 - 28x^6 + 40x^4 - 16x^2\$",
    "\$7\$",
    "\$7x^3 - 2x^2 + x\$",
    "\$8\$",
    "\$8/3\$",
    "\$800\$",
    "\$81\$",
    "\$81x^5/5 + 135x^4 + 450x^3 + 750x^2 + 625x + C\$",
    "\$84x^5\$",
    "\$8\\pi\$",
    "\$8x^3\$",
    "\$9\$",
    "\$900\$",
    "\$9\\pi\$",
    "\$9x^4 - 12x^2 + 4\$",
    "\$A = -1, B = 1\$",
    "\$A = 1, B = -1\$",
    "\$A = 1, B = 1\$",
    "\$A = 5, B = -5\$",
    "\$V = 2\\pi \\int_{0}^{1} x \\cdot x^{3} \\, dx = 2\\pi \\int_{0}^{1} x^{4} \\, dx\$. An antiderivative is \$F(x) = \\dfrac{x^{5}}{5}\$, so \$V = 2\\pi \\left[F(1)-F(0)\\right] = 2\\pi \\left[\\dfrac{1}{5} - 0\\right] = \\dfrac{2\\pi}{5}\$.",
    "\$V = 2\\pi \\int_{0}^{3} x \\cdot x \\, dx = 2\\pi \\int_{0}^{3} x^{2} \\, dx\$. An antiderivative is \$F(x) = \\dfrac{x^{3}}{3}\$, so \$V = 2\\pi \\left[F(3)-F(0)\\right] = 2\\pi \\left[9 - 0\\right] = 18\\pi\$.",
    "\$V = 2\\pi \\int_{0}^{4} x \\cdot \\sqrt{x} \\, dx = 2\\pi \\int_{0}^{4} x^{3/2} \\, dx\$. An antiderivative is \$F(x) = \\dfrac{2}{5}x^{5/2}\$, so \$V = 2\\pi \\left[F(4)-F(0)\\right] = 2\\pi \\left[\\dfrac{2}{5}(32) - 0\\right] = 2\\pi \\cdot \\dfrac{64}{5} = \\dfrac{128\\pi}{5}\$.",
    "\$V = \\pi \\int_{0}^{1} [x^{2}]^2 \\, dx = \\pi \\int_{0}^{1} x^{4} \\, dx\$. An antiderivative of the integrand is \$F(x) = \\frac{x^{5}}{5}\$, so \$V = \\pi \\left[F(1) - F(0)\\right] = \\pi \\left[\\frac{1^{5}}{5} - \\left(\\frac{0^{5}}{5}\\right)\\right] = \\frac{\\pi}{5}\$.",
    "\$V = \\pi \\int_{0}^{3} [2]^2 \\, dx = \\pi \\int_{0}^{3} 4 \\, dx\$. An antiderivative of the integrand is \$F(x) = 4 x\$, so \$V = \\pi \\left[F(3) - F(0)\\right] = \\pi \\left[4 \\cdot 3 - \\left(4 \\cdot 0\\right)\\right] = 12 \\pi\$.",
    "\$V = \\pi \\int_{0}^{4} [\\sqrt{x}]^2 \\, dx = \\pi \\int_{0}^{4} x \\, dx\$. An antiderivative of the integrand is \$F(x) = \\frac{x^{2}}{2}\$, so \$V = \\pi \\left[F(4) - F(0)\\right] = \\pi \\left[\\frac{4^{2}}{2} - \\left(\\frac{0^{2}}{2}\\right)\\right] = 8 \\pi\$.",
    "\$V = \\pi \\int_{0}^{4} [x]^2 \\, dx = \\pi \\int_{0}^{4} x^{2} \\, dx\$. An antiderivative of the integrand is \$F(x) = \\frac{x^{3}}{3}\$, so \$V = \\pi \\left[F(4) - F(0)\\right] = \\pi \\left[\\frac{4^{3}}{3} - \\left(\\frac{0^{3}}{3}\\right)\\right] = \\frac{64 \\pi}{3}\$.",
    "\$\\cos(2x + 3)\$",
    "\$\\cos(2x)\$",
    "\$\\cos(3x - 1)\$",
    "\$\\cos(5x)/5 + C\$",
    "\$\\cos(x) + 1\$",
    "\$\\cos(x) + C\$",
    "\$\\cos(x)\$",
    "\$\\cos(x)/x\$",
    "\$\\cos(x)^2\$",
    "\$\\cos(x)^{-2}\$",
    "\$\\cos(x^2)\$",
    "\$\\cot(x) + C\$",
    "\$\\dfrac{f(x+h)-f(x)}{h} = \\dfrac{1}{h}\\left(\\dfrac{1}{x+h} - \\dfrac{1}{x}\\right) = \\dfrac{1}{h} \\cdot \\dfrac{x - (x+h)}{x(x+h)} = \\dfrac{-h}{h \\cdot x(x+h)} = \\dfrac{-1}{x(x+h)}\$. Letting \$h \\to 0\$ gives \$f'(x) = -\\dfrac{1}{x^{2}}\$.",
    "\$\\infty\$",
    "\$\\infty\$ (does not exist)",
    "\$\\lim_{x \\to 1^-} f(x) = \\lim_{x \\to 1^-}(x+1) = 2\$ and \$\\lim_{x \\to 1^+} f(x) = \\lim_{x \\to 1^+}(4-x) = 3\$. Both one-sided limits exist but are unequal (\$2 \\neq 3\$), so \$\\lim_{x \\to 1} f(x)\$ does not exist. Since both one-sided limits exist but differ, this is a jump discontinuity.",
    "\$\\lim_{x \\to 2^-} [x] = 1\$ (just below 2, the greatest integer is still 1) while \$\\lim_{x \\to 2^+} [x] = 2\$. Both one-sided limits exist but are unequal, so this is a jump discontinuity.",
    "\$\\lim_{x \\to 3} \\dfrac{x^{2}-9}{x-3} = \\lim_{x \\to 3}(x+3) = 6\$, which exists, but the given value \$f(3) = 10 \\neq 6\$. Since the limit exists but does not match the defined function value, this is a removable discontinuity (redefining \$f(3)=6\$ would make \$f\$ continuous there).",
    "\$\\ln(2)\$",
    "\$\\ln(2)/2\$",
    "\$\\pi/3\$",
    "\$\\pi/4\$",
    "\$\\pi/5\$",
    "\$\\sec(x) + C\$",
    "\$\\sec(x)\\tan(x) + C\$",
    "\$\\sin(2)\$",
    "\$\\sin(2x + 1)/2 + C\$",
    "\$\\sin(2x)\$",
    "\$\\sin(3)\$",
    "\$\\sin(x) + C\$",
    "\$\\sin(x) + \\cos(x)\$",
    "\$\\sin(x) - \\cos(x)\$",
    "\$\\sin(x)\$",
    "\$\\sqrt{-x} - 1\$",
    "\$\\sqrt{1 - x^2}\$",
    "\$\\sqrt{x} - 1\$",
    "\$\\tan(x) + C\$",
    "\$\\tan(x)\$",
    "\$e^{2x - 1}\$",
    "\$e^{2x}\$",
    "\$e^{3}\$",
    "\$e^{4x}\$",
    "\$e^{5x} + C\$",
    "\$e^{5x}/x + C\$",
    "\$e^{\\sin(x)}\$",
    "\$e^{\\sin(x)}\\cos(x)\$",
    "\$e^{x^2}\$",
    "\$f''(0)\$ \$= 0\$, so the test fails here",
    "\$f''(x) = -2\$, so \$f''(3) = -2 = -2\$, which is negative, indicating a relative maximum.",
    "\$f''(x) = 2\$, so \$f''(2) = 2 = 2\$, which is positive, indicating a relative minimum.",
    "\$f''(x) = 4 \\left(3 x^{2} - 1\\right)\$. Setting \$f''(x) > 0\$ gives \$\\left(-\\infty, - \\frac{\\sqrt{3}}{3}\\right) \\cup \\left(\\frac{\\sqrt{3}}{3}, \\infty\\right)\$.",
    "\$f''(x) = 6 \\left(x - 2\\right)\$. Setting \$f''(x)=0\$ gives \$x=2\$, where the sign of \$f''(x)\$ changes, so concavity changes there.",
    "\$f''(x) = 6 x\$, so \$f''(-1) = 6 \\left(-1\\right) = -6\$, which is negative, indicating a relative maximum.",
    "\$f''(x) = 6 x\$, so \$f''(1) = 6 \\cdot 1 = 6\$, which is positive, indicating a relative minimum.",
    "\$f'(x) = 2 \\left(x - 2\\right)\$. Solving \$f'(x) > 0\$ shows \$f'(x)\$ is positive for \$x \\in \\left(2, \\infty\\right)\$, so \$f\$ is increasing on \$\\left(2, \\infty\\right)\$.",
    "\$f'(x) = 2 e^{2x}\$ by the chain rule. Differentiating again, \$f''(x) = 2 \\cdot 2 e^{2x} = 4 e^{2x}\$.",
    "\$f'(x) = 2 x - 6\$. Setting \$f'(x) = 0\$: \$2 x - 6 = 0\$, which gives \$x = 3\$.",
    "\$f'(x) = 2x - 4 = 0\$ at \$x=2\$, an interior critical point. Checking \$f\$ at the critical point and both endpoints: \$f(0)=3\$, \$f(2) = 4-8+3=-1\$, \$f(5) = 25-20+3=8\$. The smallest of these is \$f(2) = -1\$, so the absolute minimum on \$[0,5]\$ is \$-1\$.",
    "\$f'(x) = 3 \\left(x - 1\\right) \\left(x + 1\\right)\$. Solving \$f'(x) < 0\$ shows \$f'(x)\$ is negative for \$x \\in \\left(-1, 1\\right)\$, so \$f\$ is decreasing on \$\\left(-1, 1\\right)\$.",
    "\$f'(x) = 3 x^{2} - 12\$. Setting \$f'(x) = 0\$: \$3 x^{2} - 12 = 0\$, which gives \$x = -2, 2\$.",
    "\$f'(x) = 3 x^{2} - 3\$. Setting \$f'(x) = 0\$: \$3 x^{2} - 3 = 0\$, which gives \$x = -1, 1\$.",
    "\$f'(x) = 3x^{2} - 2\$, so \$f''(x) = 6x\$. At \$x=1\$: \$f''(1) = 6(1) = 6\$.",
    "\$f'(x) = 3x^{2} - 3 = 3(x-1)(x+1)\$, so the critical points are \$x=-1\$ and \$x=1\$. For \$x\$ slightly less than \$-1\$, \$f'(x) > 0\$ (increasing); for \$x\$ slightly greater than \$-1\$, \$f'(x) < 0\$ (decreasing). Since \$f'\$ changes from positive to negative, \$x=-1\$ is a relative maximum.",
    "\$f'(x) = 3x^{2} - 6x = 3x(x-2)\$, so \$x=0\$ and \$x=2\$ are critical points. \$f''(x) = 6x - 6\$, so \$f''(2) = 6(2) - 6 = 6 > 0\$, meaning \$x=2\$ is a relative minimum by the second derivative test.",
    "\$f'(x) = 4x^{3} - 6x\$. Differentiating again, \$f''(x) = 12x^{2} - 6\$.",
    "\$f'(x) = 4x^{3} - 8x = 4x(x^{2}-2)\$, so the critical points are \$x=0, \\sqrt{2}, -\\sqrt{2}\$. \$f''(x) = 12x^{2} - 8\$, so \$f''(0) = -8 < 0\$. Since \$f''(0) < 0\$, the second derivative test says \$x=0\$ is a relative maximum.",
    "\$f'(x) = 6 x^{2} - 6 x - 12\$. Setting \$f'(x) = 0\$: \$6 x^{2} - 6 x - 12 = 0\$, which gives \$x = -1, 2\$.",
    "\$f'(x) = 6x^{2} - 6x = 6x(x-1)\$, so \$x=1\$ is a critical point. \$f''(x) = 12x - 6\$, so \$f''(1) = 12(1) - 6 = 6 > 0\$. Since \$f''(1) > 0\$, the second derivative test says \$x=1\$ is a relative minimum.",
    "\$f'(x) = \\cos(x)\$, \$f''(x) = -\\sin(x)\$, and differentiating once more, \$f'''(x) = -\\cos(x)\$.",
    "\$f'(x) = \\dfrac{1}{x}\$. Differentiating \$x^{-1}\$ again gives \$f''(x) = -x^{-2} = -\\dfrac{1}{x^{2}}\$.",
    "\$f'(x) = \\dfrac{d}{dx}[\\ln(u)] = \\dfrac{u'}{u}\$ with \$u = x^{2} + 1\$: \$f'(x) = \\frac{2 x}{x^{2} + 1}\$. At \$x=2\$: \$f'(2) = \\frac{2 \\cdot 2}{2^{2} + 1} = \\frac{4}{5}\$.",
    "\$f'(x) = \\dfrac{d}{dx}[e^u] = e^u \\cdot u'\$ with \$u = 3 x\$: \$f'(x) = 3 e^{3 x}\$. At \$x=0\$: \$f'(0) = 3 e^{3 \\cdot 0} = 3\$.",
    "\$f(-1) = 1\$, \$f'(-1) = -2\$. Using the point-slope form \$y - f(a) = f'(a)(x-a)\$: \$y - 1 = -2(x - -1)\$, which simplifies to \$y = -2x - 1\$.",
    "\$f(1) = 0\$, \$f'(1) = -1\$. Using the point-slope form \$y - f(a) = f'(a)(x-a)\$: \$y - 0 = -1(x - 1)\$, which simplifies to \$y = -1x + 1\$.",
    "\$f(1) = 1\$, \$f'(1) = 3\$. Using the point-slope form \$y - f(a) = f'(a)(x-a)\$: \$y - 1 = 3(x - 1)\$, which simplifies to \$y = 3x - 2\$.",
    "\$f(2)\$ is undefined (division by zero), but \$\\lim_{x \\to 2} \\dfrac{x^{2}-4}{x-2} = \\lim_{x \\to 2} \\dfrac{(x-2)(x+2)}{x-2} = \\lim_{x \\to 2}(x+2) = 4\$, which exists. Since the limit exists even though \$f(2)\$ does not, the discontinuity can be removed by defining \$f(2)=4\$ -- this is a removable discontinuity.",
    "\$f(3) = 9\$, \$f'(3) = 6\$. Using the point-slope form \$y - f(a) = f'(a)(x-a)\$: \$y - 9 = 6(x - 3)\$, which simplifies to \$y = 6x - 9\$.",
    "\$f(x) = \\sqrt{x-1}\$ requires \$x-1 \\geq 0\$, i.e. \$x \\geq 1\$. \$g(x) = \\sqrt{3-x}\$ requires \$3-x \\geq 0\$, i.e. \$x \\leq 3\$. The domain of the sum is the intersection of both: \$1 \\leq x \\leq 3\$.",
    "\$f(x+h) - f(x) = (x+h)^{2} + 2(x+h) - x^{2} - 2x = 2xh + h^{2} + 2h\$, so \$\\dfrac{f(x+h)-f(x)}{h} = 2x + h + 2\$. Letting \$h \\to 0\$ gives \$f'(x) = 2x + 2\$, so \$f'(1) = 2(1) + 2 = 4\$.",
    "\$f(x+h) - f(x) = (x+h)^{2} - 3(x+h) - x^{2} + 3x = 2xh + h^{2} - 3h\$, so \$\\dfrac{f(x+h)-f(x)}{h} = 2x + h - 3\$. Letting \$h \\to 0\$ gives \$f'(x) = 2x - 3\$, so \$f'(2) = 2(2) - 3 = 1\$.",
    "\$f(x+h) = 3(x+h) + 2 = 3x + 3h + 2\$, so \$\\dfrac{f(x+h) - f(x)}{h} = \\dfrac{3h}{h} = 3\$ for every \$h \\neq 0\$. Letting \$h \\to 0\$, \$f'(x) = 3\$ -- a straight line's slope never changes.",
    "\$f^{-1}(x) = (x+3)/2\$",
    "\$f^{-1}(x) = (x-1)/2\$",
    "\$f^{-1}(x) = (x-3)/2\$",
    "\$f^{-1}(x) = 1/x^3\$",
    "\$f^{-1}(x) = 2x + 1\$",
    "\$f^{-1}(x) = 2x - 1\$",
    "\$f^{-1}(x) = 2x-3\$",
    "\$f^{-1}(x) = 3x\$",
    "\$f^{-1}(x) = x/2 - 1\$",
    "\$f^{-1}(x) = x/2 - 3\$",
    "\$f^{-1}(x) = x^3\$",
    "\$f^{-1}(x) = x^{1/3}\$",
    "\$k = 3 \\ln(2)\$",
    "\$k = 4/2\$",
    "\$k = \\ln(2)/2\$",
    "\$k = \\ln(2)/3\$",
    "\$k = \\ln(3)/2\$",
    "\$k = \\ln(3/2)\$",
    "\$k = \\ln(4)\$",
    "\$k = \\ln(4)/2\$",
    "\$ln|2x+1| + C\$",
    "\$ln|\\cos(x)| + C\$",
    "\$ln|\\sec(x)| + C\$",
    "\$ln|\\sin(x)| + C\$",
    "\$ln|x| + C\$",
    "\$t = 1\$",
    "\$t = 16\$",
    "\$t = 2\$",
    "\$t = 3\$",
    "\$t = 32\$",
    "\$t = 4\$",
    "\$t = 8\$",
    "\$v(t) = s'(t) = 2t - 4\$. Setting \$v(t) = 0\$: \$2t - 4 = 0 \\Rightarrow t = 2\$.",
    "\$x + 3y = -1\$",
    "\$x + 4y = 4\$",
    "\$x - 3\$",
    "\$x < -1/\$\$\\sqrt{3}\$ or \$x > 1/\$\$\\sqrt{3}\$",
    "\$x < -5\$",
    "\$x < 3\$ only",
    "\$x <= 3\$",
    "\$x = -1\$",
    "\$x = -3\$",
    "\$x = 0\$",
    "\$x = 3\$",
    "\$x > -1\$",
    "\$x > -5\$",
    "\$x > 0\$",
    "\$x > 0\$ and x not equal to 2",
    "\$x > 1\$",
    "\$x > 2\$",
    "\$x > 3\$ only",
    "\$x > 4\$",
    "\$x >= 0\$",
    "\$x >= 1\$",
    "\$x >= 4\$",
    "\$x \\cdot \\ln(x) + C\$",
    "\$x \\cos(x) - \\sin(x) + C\$",
    "\$x \\geq -1\$",
    "\$x \\geq -1, x \\neq 4\$",
    "\$x \\geq -5\$",
    "\$x \\geq 2\$",
    "\$x \\geq 3\$",
    "\$x \\leq -3\$",
    "\$x \\leq 2\$",
    "\$x \\sin(x) + C\$",
    "\$x \\sin(x) + \\cos(x) + C\$",
    "\$x(x \\cos(x) + 2 \\sin(x))\$",
    "\$x^2 + 7x + C\$",
    "\$x^2 - 3x + 2\$",
    "\$x^2 - 3x\$",
    "\$x^2 \\cos(x)\$",
    "\$x^2 \\sin(x)/2 + C\$",
    "\$x^2\$",
    "\$x^2/(x^2 - 4x + 4) - 4x/(x^2 - 4x + 4)\$",
    "\$x^2/2 - 3x\$",
    "\$x^2e^{x}/2 + C\$",
    "\$x^3 + C\$",
    "\$x^4 + 5x^2 + C\$",
    "\$x^4 - x^2 + C\$",
    "\$x^5\$",
    "\$x^5/5 + 5x^3/3 + C\$",
    "\$x^6 - 3x + C\$",
    "\$x^6 - 4x\$",
    "\$y = -1\$",
    "\$y = -1/5\$",
    "\$y = -1x + 1\$",
    "\$y = -1x\$",
    "\$y = -2x + 1\$",
    "\$y = -2x - 1\$",
    "\$y = -3\$ and \$y = 3\$",
    "\$y = -3x - 2\$",
    "\$y = -3x - 3\$",
    "\$y = -4\$",
    "\$y = -6x - 9\$",
    "\$y = -9\$ and \$y = 9\$",
    "\$y = -x/4 + 1\$",
    "\$y = 0\$",
    "\$y = 0\$ only",
    "\$y = 0x - 1\$",
    "\$y = 1\$",
    "\$y = 1x + 1\$",
    "\$y = 1x + 3\$",
    "\$y = 1x - 2\$",
    "\$y = 2\$",
    "\$y = 2x + 2\$",
    "\$y = 2x - 1\$",
    "\$y = 3\$",
    "\$y = 3\$ only",
    "\$y = 3f(x+2)\$",
    "\$y = 3f(x-2)\$",
    "\$y = 3x + 1\$",
    "\$y = 3x + 3\$",
    "\$y = 3x - 2\$",
    "\$y = 4x - 15/2\$",
    "\$y = 4x - 7\$",
    "\$y = 5\$",
    "\$y = 6x + 4\$",
    "\$y = 6x + 9\$",
    "\$y = 6x - 2\$",
    "\$y = 6x - 9\$",
    "\$y = 9x + 6\$",
    "\$y = f(3x)+2\$",
    "\$y = f(3x+2)\$",
    "\$y' = -\\dfrac{1}{x^{2}}\$, so the tangent's slope at \$(2,\\tfrac{1}{2})\$ is \$y'(2) = -\\dfrac{1}{4}\$. The normal's slope is the negative reciprocal, \$4\$. Point-slope form gives \$y - \\dfrac{1}{2} = 4(x-2)\$, which simplifies to \$y = 4x - \\dfrac{15}{2}\$.",
    "\$y' = 2x - 4\$, so at \$x=3\$ the slope is \$y'(3) = 2(3) - 4 = 2\$.",
    "\$y' = 3x^{2}\$, so the slope of the tangent at \$(-1,0)\$ is \$y'(-1) = 3\$. The normal is perpendicular to the tangent, so its slope is \$-\\dfrac{1}{3}\$. Using point-slope form: \$y - 0 = -\\dfrac{1}{3}(x - (-1))\$, i.e. \$3y = -(x+1)\$, which rearranges to \$x + 3y = -1\$.",
    "\$y' = 6x\$, so the slope at \$(1,4)\$ is \$y'(1) = 6\$. Using the point-slope form \$y - y_0 = m(x - x_0)\$ with \$m=6\$, \$(x_0,y_0)=(1,4)\$: \$y - 4 = 6(x - 1)\$, which simplifies to \$y = 6x - 2\$.",
    "\$y(2) = 200 e^{2k} = 800\$, so \$e^{2k} = 4\$. Taking the natural log: \$2k = \\ln 4\$, so \$k = \\dfrac{\\ln 4}{2}\$.",
    "\$y(2) = y_0 e^{2k} = 3y_0\$, so \$e^{2k}=3\$. Taking the natural log of both sides: \$2k = \\ln 3\$, so \$k = \\dfrac{\\ln 3}{2}\$.",
    "\$y=3 x\$ does not cross the \$x\$-axis between \$x=0\$ and \$x=4\$, so the area is \$\\int_{0}^{4} 3 x \\, dx\$. An antiderivative is \$F(x) = \\frac{3 x^{2}}{2}\$, so the area is \$F(4) - F(0) = \\frac{3 \\cdot 4^{2}}{2} - (\\frac{3 \\cdot 0^{2}}{2}) = 24\$.",
    "\$y=4 - x^{2}\$ does not cross the \$x\$-axis between \$x=-2\$ and \$x=2\$, so the area is \$\\int_{-2}^{2} 4 - x^{2} \\, dx\$. An antiderivative is \$F(x) = - \\frac{x^{3}}{3} + 4 x\$, so the area is \$F(2) - F(-2) = \\frac{2 \\left(12 - 2^{2}\\right)}{3} - (\\frac{\\left(-2\\right) \\left(12 - \\left(-2\\right)^{2}\\right)}{3}) = \\frac{32}{3}\$.",
    "\$y=x^{2}\$ does not cross the \$x\$-axis between \$x=0\$ and \$x=2\$, so the area is \$\\int_{0}^{2} x^{2} \\, dx\$. An antiderivative is \$F(x) = \\frac{x^{3}}{3}\$, so the area is \$F(2) - F(0) = \\frac{2^{3}}{3} - (\\frac{0^{3}}{3}) = \\frac{8}{3}\$.",
    "\$y=x^{3}\$ does not cross the \$x\$-axis between \$x=0\$ and \$x=2\$, so the area is \$\\int_{0}^{2} x^{3} \\, dx\$. An antiderivative is \$F(x) = \\frac{x^{4}}{4}\$, so the area is \$F(2) - F(0) = \\frac{2^{4}}{4} - (\\frac{0^{4}}{4}) = 4\$.",
    "-2xe^(x^2)",
    "0.023 years",
    "15 years",
    "2xe^(x^2)",
    "30 years",
    "60 years",
    "A ball thrown upward has height s(t) = 16t - t^2 (metres, t in seconds). At what time does the ball reach its maximum height (v = 0)?",
    "A curve \$y = f(x)\$ is symmetric about the origin if f(-x) = -f(x) (an odd function). Determine the symmetry of \$y = x^3 - x\$.",
    "A curve is symmetric about the origin if replacing both x by -x and y by -y leaves its equation unchanged. Determine the symmetry of xy = 4.",
    "A curve is symmetric about the y-axis if replacing x by -x leaves its equation unchanged. Determine the symmetry of \$y = x^4 - 3x^2 + 1\$.",
    "A function f is defined by \$f(x) = x+1\$ for \$x<1\$ and \$f(x) = 4-x\$ for x greater than or equal to 1. Classify the discontinuity of f at x = 1.",
    "A function f is defined by \$f(x) = x+1\$ for \$x<1\$ and \$f(x) = 4-x\$ for x greater than or equal to 1. Find \$\\lim_{x \\to 1^+} [f(x)]\$.",
    "A function f is defined by \$f(x) = x+1\$ for \$x<1\$ and \$f(x) = 4-x\$ for x greater than or equal to 1. Find \$\\lim_{x \\to 1^-} [f(x)]\$.",
    "A population grows exponentially and doubles every 3 hours. If it starts at 100, how many are there after 9 hours?",
    "A quantity grows according to y(t) = y0 * e^(kt). If the quantity triples in 2 years, find k (in terms of ln, per year).",
    "A radioactive substance has a half-life of 30 years. If 100 mg is present initially, approximately how much remains after 100 years?",
    "A vertical stretch by factor \$3\$ multiplies the output: \$3f(x)\$. Shifting the graph 2 units to the left replaces \$x\$ with \$x+2\$ inside: \$y = 3f(x+2)\$.",
    "Acceleration is \$a(t) = v'(t) = 6t - 6\$. At \$t=2\$: \$a(2) = 6(2) - 6 = 6\$.",
    "Acceleration is \$a(t) = v'(t) = s''(t) = 6t - 12\$. At \$t=1\$: \$a(1) = 6(1) - 12 = -6\$.",
    "An antiderivative is \$F(x) = - \\frac{x^{3}}{3} + 4 x\$. By the Fundamental Theorem, \$\\int_{-1}^{1} 4 - x^{2} \\, dx = F(1) - F(-1) = (\\frac{1 \\left(12 - 1^{2}\\right)}{3} = \\frac{11}{3}) - (\\frac{\\left(-1\\right) \\left(12 - \\left(-1\\right)^{2}\\right)}{3} = - \\frac{11}{3}) = \\frac{11}{3} - - \\frac{11}{3} = \\frac{22}{3}\$.",
    "An antiderivative is \$F(x) = \\frac{3 x^{2}}{2} - x\$. By the Fundamental Theorem, \$\\int_{1}^{4} 3 x - 1 \\, dx = F(4) - F(1) = (\\frac{4 \\left(-2 + 3 \\cdot 4\\right)}{2} = 20) - (\\frac{1 \\left(-2 + 3 \\cdot 1\\right)}{2} = \\frac{1}{2}) = 20 - \\frac{1}{2} = \\frac{39}{2}\$.",
    "An antiderivative is \$F(x) = \\frac{x^{3}}{3} - 2 x^{2} + 3 x\$. By the Fundamental Theorem, \$\\int_{0}^{3} x^{2} - 4 x + 3 \\, dx = F(3) - F(0) = (\\frac{3 \\left(9 - 6 \\cdot 3 + 3^{2}\\right)}{3} = 0) - (\\frac{0 \\left(9 - 6 \\cdot 0 + 0^{2}\\right)}{3} = 0) = 0 - 0 = 0\$.",
    "An antiderivative is \$F(x) = \\frac{x^{3}}{3}\$. By the Fundamental Theorem, \$\\int_{0}^{2} x^{2} \\, dx = F(2) - F(0) = (\\frac{2^{3}}{3} = \\frac{8}{3}) - (\\frac{0^{3}}{3} = 0) = \\frac{8}{3} - 0 = \\frac{8}{3}\$.",
    "An antiderivative is \$F(x) = \\frac{x^{4}}{4}\$. By the Fundamental Theorem, \$\\int_{0}^{1} x^{3} \\, dx = F(1) - F(0) = (\\frac{1^{4}}{4} = \\frac{1}{4}) - (\\frac{0^{4}}{4} = 0) = \\frac{1}{4} - 0 = \\frac{1}{4}\$.",
    "An antiderivative is \$F(x) = x^{2} + x\$. By the Fundamental Theorem, \$\\int_{-1}^{2} 2 x + 1 \\, dx = F(2) - F(-1) = (2^{2} + 2 = 6) - (\\left(-1\\right)^{2} + -1 = 0) = 6 - 0 = 6\$.",
    "An object's position is s(t) = t^2 - 4t + 3. At what time t is the object momentarily at rest (v = 0)?",
    "Approaching \$x=2\$ from above, \$x \\geq 2\$ applies, so \$f(x) = x^{2} - 1\$ is the relevant branch. The right-hand limit is \$\\lim_{x \\to 2^+} f(x) = 2^{2} - 1 = 3\$.",
    "Approaching \$x=2\$ from below, \$x < 2\$ applies, so \$f(x) = 3 - x\$ is the relevant branch. The left-hand limit is \$\\lim_{x \\to 2^-} f(x) = 3 - 2 = 1\$.",
    "As \$x \\to 0\$ from either side, \$x^{2} \\to 0^{+}\$ (always positive), so \$\\dfrac{1}{x^{2}}\$ grows without bound. Hence \$\\lim_{x \\to 0} \\dfrac{1}{x^{2}} = \\infty\$.",
    "As \$x \\to 0\$, \$x^{4} \\to 0^{+}\$, so \$\\dfrac{1}{x^{4}} \\to \\infty\$ and therefore \$-\\dfrac{1}{x^{4}} \\to -\\infty\$. Hence \$\\lim_{x \\to 0} \\left(-\\dfrac{1}{x^{4}}\\right) = -\\infty\$.",
    "As \$x \\to 0^{+}\$, \$\\dfrac{1}{x} \\to \\infty\$, and as \$x \\to 0^{-}\$, \$\\dfrac{1}{x} \\to -\\infty\$. Neither one-sided limit exists as a finite number, so this cannot be patched by redefining a single point -- it is an essential (infinite) discontinuity.",
    "As \$x \\to 2^{+}\$, \$x-2 \\to 0^{+}\$ (a small positive number), so \$\\dfrac{1}{x-2}\$ grows without bound through positive values. Hence \$\\lim_{x \\to 2^+} \\dfrac{1}{x-2} = \\infty\$.",
    "As \$x \\to 2^{-}\$, \$x-2 \\to 0^{-}\$ (a small negative number), so \$\\dfrac{1}{x-2}\$ decreases without bound through negative values. Hence \$\\lim_{x \\to 2^-} \\dfrac{1}{x-2} = -\\infty\$.",
    "As \$x \\to 3\$ from either side, \$(x-3)^{2} \\to 0^{+}\$ (a square is never negative), so \$\\dfrac{1}{(x-3)^{2}}\$ grows without bound through positive values. Hence \$\\lim_{x \\to 3} \\dfrac{1}{(x-3)^{2}} = \\infty\$.",
    "At \$x=3\$ and just above it, on the interval \$[3, 4)\$, the greatest integer function \$[x]\$ equals \$3\$. So the right-hand limit is \$\\lim_{x \\to 3^+} [x] = 3\$.",
    "At the critical point x = -1 of \$f(x) = x^3 - 3x\$, the Second Derivative Test shows this is a:",
    "At the critical point x = 1 of \$f(x) = x^3 - 3x\$, the Second Derivative Test shows this is a:",
    "At the critical point x = 2 of \$f(x) = x^2 - 4x + 7\$, the Second Derivative Test shows this is a:",
    "At the critical point x = 3 of \$f(x) = -x^2 + 6x - 5\$, the Second Derivative Test shows this is a:",
    "Bacteria in a culture grow exponentially. If the population is 200 at t=0 and 800 at t=2 (hours), find the growth constant k in y(t) = 200 e^(kt).",
    "Between \$x=-1\$ and \$x=1\$, \$y=x + 3\$ lies above \$y=x^{2} - 1\$, so the area is \$\\int_{-1}^{1} [(x + 3) - (x^{2} - 1)] \\, dx = \\int_{-1}^{1} - x^{2} + x + 4 \\, dx\$. An antiderivative is \$F(x) = - \\frac{x^{3}}{3} + \\frac{x^{2}}{2} + 4 x\$, so the area is \$F(1) - F(-1) = \\frac{1 \\left(24 + 3 \\cdot 1 - 2 \\cdot 1^{2}\\right)}{6} - (\\frac{\\left(-1\\right) \\left(24 + 3 \\left(-1\\right) - 2 \\left(-1\\right)^{2}\\right)}{6}) = \\frac{22}{3}\$.",
    "Between \$x=-2\$ and \$x=3\$, \$y=x + 5\$ lies above \$y=x^{2} - 1\$, so the area is \$\\int_{-2}^{3} [(x + 5) - (x^{2} - 1)] \\, dx = \\int_{-2}^{3} - x^{2} + x + 6 \\, dx\$. An antiderivative is \$F(x) = - \\frac{x^{3}}{3} + \\frac{x^{2}}{2} + 6 x\$, so the area is \$F(3) - F(-2) = \\frac{3 \\left(36 + 3 \\cdot 3 - 2 \\cdot 3^{2}\\right)}{6} - (\\frac{\\left(-2\\right) \\left(36 + 3 \\left(-2\\right) - 2 \\left(-2\\right)^{2}\\right)}{6}) = \\frac{125}{6}\$.",
    "Between \$x=-3\$ and \$x=2\$, \$y=6 - x\$ lies above \$y=x^{2}\$, so the area is \$\\int_{-3}^{2} [(6 - x) - (x^{2})] \\, dx = \\int_{-3}^{2} - x^{2} - x + 6 \\, dx\$. An antiderivative is \$F(x) = - \\frac{x^{3}}{3} - \\frac{x^{2}}{2} + 6 x\$, so the area is \$F(2) - F(-3) = \\frac{2 \\left(36 - 3 \\cdot 2 - 2 \\cdot 2^{2}\\right)}{6} - (\\frac{\\left(-3\\right) \\left(36 - 3 \\left(-3\\right) - 2 \\left(-3\\right)^{2}\\right)}{6}) = \\frac{125}{6}\$.",
    "By definition, \$f'(x) = \\lim_{h \\to 0} \\dfrac{f(x+h) - f(x)}{h}\$. Here \$f(x+h) = (x+h)^2 = x^2 + 2xh + h^2\$, so \$\\dfrac{f(x+h)-f(x)}{h} = \\dfrac{2xh + h^2}{h} = 2x + h\$. Letting \$h \\to 0\$ gives \$f'(x) = 2x\$.",
    "By the Chain Rule, \$\\dfrac{d}{dx}[\\ln(u)] = \\dfrac{u'}{u}\$. With \$u = 3 x^{2} + 5\$, \$u' = 6 x\$, giving \$f'(x) = \\dfrac{6 x}{3 x^{2} + 5} = \\frac{6 x}{3 x^{2} + 5}\$.",
    "By the Chain Rule, \$\\dfrac{d}{dx}[\\ln(u)] = \\dfrac{u'}{u}\$. With \$u = 5 x - 1\$, \$u' = 5\$, giving \$f'(x) = \\dfrac{5}{5 x - 1} = \\frac{5}{5 x - 1}\$.",
    "By the Chain Rule, \$\\dfrac{d}{dx}[\\ln(u)] = \\dfrac{u'}{u}\$. With \$u = \\cos{\\left(x \\right)}\$, \$u' = - \\sin{\\left(x \\right)}\$, giving \$f'(x) = \\dfrac{- \\sin{\\left(x \\right)}}{\\cos{\\left(x \\right)}} = - \\tan{\\left(x \\right)}\$.",
    "By the Chain Rule, \$\\dfrac{d}{dx}[\\ln(u)] = \\dfrac{u'}{u}\$. With \$u = x^{3} - 2\$, \$u' = 3 x^{2}\$, giving \$f'(x) = \\dfrac{3 x^{2}}{x^{3} - 2} = \\frac{3 x^{2}}{x^{3} - 2}\$.",
    "By the Chain Rule, \$\\dfrac{d}{dx}[e^u] = e^u \\cdot u'\$. With \$u = 2 x - 1\$, \$u' = 2\$, giving \$f'(x) = e^{2 x - 1} \\cdot 2 = 2 e^{2 x - 1}\$.",
    "By the Chain Rule, \$\\dfrac{d}{dx}[e^u] = e^u \\cdot u'\$. With \$u = 4 x\$, \$u' = 4\$, giving \$f'(x) = e^{4 x} \\cdot 4 = 4 e^{4 x}\$.",
    "By the Chain Rule, \$\\dfrac{d}{dx}[e^u] = e^u \\cdot u'\$. With \$u = \\sin{\\left(x \\right)}\$, \$u' = \\cos{\\left(x \\right)}\$, giving \$f'(x) = e^{\\sin{\\left(x \\right)}} \\cdot \\cos{\\left(x \\right)} = e^{\\sin{\\left(x \\right)}} \\cos{\\left(x \\right)}\$.",
    "By the Chain Rule, \$\\dfrac{d}{dx}[e^u] = e^u \\cdot u'\$. With \$u = x^{2}\$, \$u' = 2 x\$, giving \$f'(x) = e^{x^{2}} \\cdot 2 x = 2 x e^{x^{2}}\$.",
    "By the shell method, revolving about the y-axis gives \$V = 2\\pi \\int_{0}^{2} x \\cdot f(x) \\, dx = 2\\pi \\int_{0}^{2} x \\cdot x^{2} \\, dx = 2\\pi \\int_{0}^{2} x^{3} \\, dx\$. An antiderivative of the integrand is \$F(x) = \\dfrac{x^{4}}{4}\$, so \$V = 2\\pi \\left[F(2)-F(0)\\right] = 2\\pi \\left[\\dfrac{16}{4} - 0\\right] = 2\\pi(4) = 8\\pi\$.",
    "Chain Rule: with \$u = 2 x + 3\$, \$\\dfrac{d}{dx}[\\sin(u)] = \\cos(u) \\cdot u'\$. Here \$u' = 2\$, so \$f'(x) = \\cos(2 x + 3) \\cdot (2) = 2 \\cos{\\left(2 x + 3 \\right)}\$.",
    "Chain Rule: with \$u = 2 x - 5\$, \$\\dfrac{d}{dx}[u^{4}] = 4 u^{3} \\cdot u'\$. Here \$u' = 2\$, so \$f'(x) = 4(2 x - 5)^{3} \\cdot (2) = 64 x^{3} - 480 x^{2} + 1200 x - 1000\$.",
    "Chain Rule: with \$u = 3 x - 1\$, \$\\dfrac{d}{dx}[\\sin(u)] = \\cos(u) \\cdot u'\$. Here \$u' = 3\$, so \$f'(x) = \\cos(3 x - 1) \\cdot (3) = 3 \\cos{\\left(3 x - 1 \\right)}\$.",
    "Chain Rule: with \$u = x^{2} + 1\$, \$\\dfrac{d}{dx}[u^{3}] = 3 u^{2} \\cdot u'\$. Here \$u' = 2 x\$, so \$f'(x) = 3(x^{2} + 1)^{2} \\cdot (2 x) = 6 x^{5} + 12 x^{3} + 6 x\$.",
    "Chain Rule: with \$u = x^{2}\$, \$\\dfrac{d}{dx}[\\sin(u)] = \\cos(u) \\cdot u'\$. Here \$u' = 2 x\$, so \$f'(x) = \\cos(x^{2}) \\cdot (2 x) = 2 x \\cos{\\left(x^{2} \\right)}\$.",
    "Chain Rule: with \$u = x^{3} - 2 x\$, \$\\dfrac{d}{dx}[u^{2}] = 2 u^{1} \\cdot u'\$. Here \$u' = 3 x^{2} - 2\$, so \$f'(x) = 2(x^{3} - 2 x)^{1} \\cdot (3 x^{2} - 2) = 6 x^{5} - 16 x^{3} + 8 x\$.",
    "Classify the discontinuity of \$f(x) = 1/x\$ at x = 0.",
    "Clearing denominators: \$1 = A(x+1) + B(x-1)\$. Setting \$x=-1\$: \$1 = A(0) + B(-2) \\Rightarrow B = -\\dfrac{1}{2}\$.",
    "Clearing denominators: \$1 = A(x+1) + B(x-1)\$. Setting \$x=1\$: \$1 = A(2) + B(0) \\Rightarrow A = \\dfrac{1}{2}\$.",
    "Clearing denominators: \$1 = A(x-1)^{2} + Bx(x-1) + Cx\$. Setting \$x=1\$ eliminates the \$A\$ and \$B\$ terms: \$1 = A(0) + B(0) + C(1) \\Rightarrow C = 1\$.",
    "Clearing denominators: \$3x+1 = A(x+2) + B(x-1)\$. Setting \$x=1\$: \$3(1)+1 = A(3) \\Rightarrow 4 = 3A \\Rightarrow A = \\dfrac{4}{3}\$.",
    "Clearing denominators: \$5 = A(x+3) + B(x-2)\$. Setting \$x=2\$: \$5 = A(5) \\Rightarrow A=1\$. Setting \$x=-3\$: \$5 = B(-5) \\Rightarrow B=-1\$.",
    "Differentiate both sides of \$x^{2} + y^{2} = 25\$ implicitly with respect to \$x\$, treating \$y\$ as a function of \$x\$: \$2 x + 2 y(dy/dx) = 0\$. Solving for \$dy/dx\$: \$dy/dx = - \\frac{x}{y}\$. At \$(3,4)\$: \$dy/dx = - \\frac{3}{4} = - \\frac{3}{4}\$.",
    "Differentiate both sides of \$x^{3} + y^{3} = 9\$ implicitly with respect to \$x\$, treating \$y\$ as a function of \$x\$: \$3 x^{2} + 3 y^{2}(dy/dx) = 0\$. Solving for \$dy/dx\$: \$dy/dx = - \\frac{x^{2}}{y^{2}}\$. At \$(1,2)\$: \$dy/dx = - \\frac{1}{4} = - \\frac{1}{4}\$.",
    "Differentiate term by term: \$\\dfrac{d}{dx}[2 \\cdot x^{7}] = 2 \\cdot 7 x^{6} = 14 x^{6}\$; the derivative of the constant \$5\$ is \$0\$. Summing the terms: \$f'(x) = 14 x^{6}\$.",
    "Differentiate term by term: \$\\dfrac{d}{dx}[3 \\cdot \\sin(x)] = 3 \\cdot \\cos(x)\$. Summing the terms: \$f'(x) = 3 \\cos{\\left(x \\right)}\$.",
    "Differentiate term by term: \$\\dfrac{d}{dx}[3 \\cdot x^{4}] = 3 \\cdot 4 x^{3} = 12 x^{3}\$. Summing the terms: \$f'(x) = 12 x^{3}\$.",
    "Differentiate term by term: \$\\dfrac{d}{dx}[7 \\cdot x^{3}] = 7 \\cdot 3 x^{2} = 21 x^{2}\$; \$\\dfrac{d}{dx}[-2 \\cdot x^{2}] = -2 \\cdot 2 x^{1} = - 4 x\$; \$\\dfrac{d}{dx}[x^{1}] = 1 x^{0} = 1\$. Summing the terms: \$f'(x) = 21 x^{2} - 4 x + 1\$.",
    "Differentiate term by term: \$\\dfrac{d}{dx}[\\cos(x)] = -\\sin(x)\$. Summing the terms: \$f'(x) = - \\sin{\\left(x \\right)}\$.",
    "Differentiate term by term: \$\\dfrac{d}{dx}[\\frac{1}{2} \\cdot x^{2}] = \\frac{1}{2} \\cdot 2 x^{1} = x\$; \$\\dfrac{d}{dx}[-3 \\cdot x^{1}] = -3 \\cdot 1 x^{0} = -3\$. Summing the terms: \$f'(x) = x - 3\$.",
    "Differentiate term by term: \$\\dfrac{d}{dx}[\\sin(x)] = \\cos(x)\$. Summing the terms: \$f'(x) = \\cos{\\left(x \\right)}\$.",
    "Differentiate term by term: \$\\dfrac{d}{dx}[\\sin(x)] = \\cos(x)\$; \$\\dfrac{d}{dx}[\\cos(x)] = -\\sin(x)\$. Summing the terms: \$f'(x) = \\cos{\\left(x \\right)} - \\sin{\\left(x \\right)}\$.",
    "Differentiate term by term: \$\\dfrac{d}{dx}[\\tan{\\left(x \\right)}] = \\tan^{2}{\\left(x \\right)} + 1\$. Summing the terms: \$f'(x) = 1 + \\tan^{2}{\\left(x \\right)}\$.",
    "Differentiate term by term: \$\\dfrac{d}{dx}[x^{5}] = 5 x^{4} = 5 x^{4}\$. Summing the terms: \$f'(x) = 5 x^{4}\$.",
    "Differentiate term by term: \$\\dfrac{d}{dx}[x^{6}] = 6 x^{5} = 6 x^{5}\$; \$\\dfrac{d}{dx}[-4 \\cdot x^{1}] = -4 \\cdot 1 x^{0} = -4\$. Summing the terms: \$f'(x) = 6 x^{5} - 4\$.",
    "Direct substitution gives \$\\frac{0}{0}\$, a \$0/0\$ form. Factor: \$\\dfrac{x^{2} + x - 6}{x - 2} = \\dfrac{\\left(x - 2\\right) \\left(x + 3\\right)}{x - 2}\$, and cancel the common factor to get \$x + 3\$ (valid for \$x \\neq 2\$). Substituting \$x=2\$: \$2 + 3 = 5\$.",
    "Direct substitution gives \$\\frac{0}{0}\$, a \$0/0\$ form. Factor: \$\\dfrac{x^{2} - 1}{x - 1} = \\dfrac{\\left(x - 1\\right) \\left(x + 1\\right)}{x - 1}\$, and cancel the common factor to get \$x + 1\$ (valid for \$x \\neq 1\$). Substituting \$x=1\$: \$1 + 1 = 2\$.",
    "Direct substitution gives \$\\frac{0}{0}\$, a \$0/0\$ form. Factor: \$\\dfrac{x^{2} - 4}{x - 2} = \\dfrac{\\left(x - 2\\right) \\left(x + 2\\right)}{x - 2}\$, and cancel the common factor to get \$x + 2\$ (valid for \$x \\neq 2\$). Substituting \$x=2\$: \$2 + 2 = 4\$.",
    "Direct substitution gives \$\\frac{0}{0}\$, a \$0/0\$ form. Factor: \$\\dfrac{x^{2} - 5 x + 6}{x - 2} = \\dfrac{\\left(x - 3\\right) \\left(x - 2\\right)}{x - 2}\$, and cancel the common factor to get \$x - 3\$ (valid for \$x \\neq 2\$). Substituting \$x=2\$: \$2 - 3 = -1\$.",
    "Direct substitution gives \$\\frac{0}{0}\$, a \$0/0\$ form. Factor: \$\\dfrac{x^{2} - 9}{x - 3} = \\dfrac{\\left(x - 3\\right) \\left(x + 3\\right)}{x - 3}\$, and cancel the common factor to get \$x + 3\$ (valid for \$x \\neq 3\$). Substituting \$x=3\$: \$3 + 3 = 6\$.",
    "Direct substitution gives \$\\frac{0}{0}\$, a \$0/0\$ form. Factor: \$\\dfrac{x^{3} - 8}{x - 2} = \\dfrac{\\left(x - 2\\right) \\left(x^{2} + 2 x + 4\\right)}{x - 2}\$, and cancel the common factor to get \$x^{2} + 2 x + 4\$ (valid for \$x \\neq 2\$). Substituting \$x=2\$: \$2^{2} + 2 \\cdot 2 + 4 = 12\$.",
    "Divide numerator and denominator by \$x^{1}\$, the highest power of \$x\$ present: \$\\dfrac{3 x + 1}{6 x + 5} = \\dfrac{3 + \\frac{1}{x}}{6 + \\frac{5}{x}}\$. As \$x \\to \\infty\$, every term with \$x\$ in the denominator goes to \$0\$, leaving \$\\lim_{x \\to \\infty} \\frac{3 x + 1}{6 x + 5} = \\frac{1}{2}\$.",
    "Divide numerator and denominator by \$x^{2}\$, the highest power of \$x\$ present: \$\\dfrac{x + 3}{x^{2} - 4} = \\dfrac{\\frac{1}{x} + \\frac{3}{x^{2}}}{1 - \\frac{4}{x^{2}}}\$. As \$x \\to \\infty\$, every term with \$x\$ in the denominator goes to \$0\$, leaving \$\\lim_{x \\to \\infty} \\frac{x + 3}{x^{2} - 4} = 0\$.",
    "Divide numerator and denominator by \$x^{2}\$, the highest power of \$x\$ present: \$\\dfrac{x \\left(2 x + 3\\right)}{5 x^{2} - x + 1} = \\dfrac{2 + \\frac{3}{x}}{5 - \\frac{1}{x} + \\frac{1}{x^{2}}}\$. As \$x \\to \\infty\$, every term with \$x\$ in the denominator goes to \$0\$, leaving \$\\lim_{x \\to \\infty} \\frac{2 x^{2} + 3 x}{5 x^{2} - x + 1} = \\frac{2}{5}\$.",
    "Divide numerator and denominator by \$x^{3}\$, the highest power of \$x\$ present: \$\\dfrac{x \\left(4 x^{2} - 1\\right)}{2 x^{3} + 7} = \\dfrac{4 - \\frac{1}{x^{2}}}{2 + \\frac{7}{x^{3}}}\$. As \$x \\to \\infty\$, every term with \$x\$ in the denominator goes to \$0\$, leaving \$\\lim_{x \\to \\infty} \\frac{4 x^{3} - x}{2 x^{3} + 7} = 2\$.",
    "Divide numerator and denominator by \$x^{3}\$, the highest power of \$x\$ present: \$\\dfrac{x^{2} + 1}{x^{3} + 2} = \\dfrac{\\frac{1}{x} + \\frac{1}{x^{3}}}{1 + \\frac{2}{x^{3}}}\$. As \$x \\to \\infty\$, every term with \$x\$ in the denominator goes to \$0\$, leaving \$\\lim_{x \\to \\infty} \\frac{x^{2} + 1}{x^{3} + 2} = 0\$.",
    "Dividing numerator and denominator by \$x\$: \$\\dfrac{3 + 1/x}{1 - 5/x} \\to \\dfrac{3}{1} = 3\$ as \$x \\to \\infty\$. So \$y=3\$ is the horizontal asymptote.",
    "Doubling every 3 hours means after \$9\$ hours there have been \$\\dfrac{9}{3}=3\$ doubling periods. Starting from \$100\$: \$100 \\cdot 2^{3} = 100 \\cdot 8 = 800\$.",
    "E",
    "Evaluate \$\\int_{-1}^{1} 4 - x^2 \\, dx\$.",
    "Evaluate \$\\int_{-1}^{2} 2x + 1 \\, dx\$.",
    "Evaluate \$\\int_{0}^{1} 2x(x^2 + 1)^3 \\, dx\$.",
    "Evaluate \$\\int_{0}^{1} x \\cdot e^x \\, dx\$.",
    "Evaluate \$\\int_{0}^{1} x^3 \\, dx\$.",
    "Evaluate \$\\int_{0}^{2} x/(x^2 + 4) \\, dx\$.",
    "Evaluate \$\\int_{0}^{2} x^2 \\, dx\$.",
    "Evaluate \$\\int_{0}^{3} x^2 - 4x + 3 \\, dx\$.",
    "Evaluate \$\\int_{0}^{pi/2} \\sin(x)^2 \\cos(x) \\, dx\$.",
    "Evaluate \$\\int_{1}^{4} 3x - 1 \\, dx\$.",
    "Evaluate \$\\lim_{x \\to -1} [x^3 - 4x + 1]\$.",
    "Evaluate \$\\lim_{x \\to -2} [(x^2 + 2x)/(x + 5)]\$.",
    "Evaluate \$\\lim_{x \\to 0} [(1 - \\cos(x))/x^2]\$.",
    "Evaluate \$\\lim_{x \\to 0} [(1-cos x)/x]\$.",
    "Evaluate \$\\lim_{x \\to 0} [-1/x^4]\$.",
    "Evaluate \$\\lim_{x \\to 0} [1/x^2]\$.",
    "Evaluate \$\\lim_{x \\to 0} [\\sin(3x)/(5x)]\$.",
    "Evaluate \$\\lim_{x \\to 0} [\\sin(4x)/x]\$.",
    "Evaluate \$\\lim_{x \\to 0} [\\sin(x)/x]\$.",
    "Evaluate \$\\lim_{x \\to 0} [x \\cdot \\sin(1/x)]\$.",
    "Evaluate \$\\lim_{x \\to 1} [(x^2 - 1)/(x + 3)]\$.",
    "Evaluate \$\\lim_{x \\to 1} [(x^2 - 1)/(x - 1)]\$.",
    "Evaluate \$\\lim_{x \\to 2^+} [1/(x-2)]\$.",
    "Evaluate \$\\lim_{x \\to 2^-} [1/(x-2)]\$.",
    "Evaluate \$\\lim_{x \\to 2} [(x^2 + x - 6)/(x - 2)]\$.",
    "Evaluate \$\\lim_{x \\to 2} [(x^2 - 4)/(x - 2)]\$.",
    "Evaluate \$\\lim_{x \\to 2} [(x^2 - 5x + 6)/(x - 2)]\$.",
    "Evaluate \$\\lim_{x \\to 2} [(x^3 - 8)/(x - 2)]\$.",
    "Evaluate \$\\lim_{x \\to 2} [3x^2 - 5x + 7]\$.",
    "Evaluate \$\\lim_{x \\to 3} [(x^2 - 9)/(x - 3)]\$.",
    "Evaluate \$\\lim_{x \\to 3} [1/(x-3)^2]\$.",
    "Evaluate \$\\lim_{x \\to 3} [5x - 7]\$.",
    "Evaluate \$\\lim_{x \\to 4} [(2x + 3)/(x - 1)]\$.",
    "Evaluate \$\\lim_{x \\to \\infty} [(2x^2 + 3x)/(5x^2 - x + 1)]\$.",
    "Evaluate \$\\lim_{x \\to \\infty} [(3x + 1)/(6x + 5)]\$.",
    "Evaluate \$\\lim_{x \\to \\infty} [(4x^3 - x)/(2x^3 + 7)]\$.",
    "Evaluate \$\\lim_{x \\to \\infty} [(x + 3)/(x^2 - 4)]\$.",
    "Evaluate \$\\lim_{x \\to \\infty} [(x^2 + 1)/(x^3 + 2)]\$.",
    "Find \$\\int (3x + 5)^4 \\, dx\$.",
    "Find \$\\int (4 - 3x)^3 \\, dx\$.",
    "Find \$\\int 1/x \\, dx\$.",
    "Find \$\\int 2/(2x+1) \\, dx\$.",
    "Find \$\\int 2x + 7 \\, dx\$.",
    "Find \$\\int 3 \\sin(x) \\, dx\$.",
    "Find \$\\int 3x^2 \\, dx\$.",
    "Find \$\\int 4x^3 - 2x \\, dx\$.",
    "Find \$\\int 6x^5 - 3 \\, dx\$.",
    "Find \$\\int \\cos(2x + 1) \\, dx\$.",
    "Find \$\\int \\cos(x) \\, dx\$.",
    "Find \$\\int \\sec(x)^2 \\, dx\$.",
    "Find \$\\int \\sin(5x) \\, dx\$.",
    "Find \$\\int \\sin(x) \\, dx\$.",
    "Find \$\\int \\tan(x) \\, dx\$.",
    "Find \$\\int e^{5x} \\, dx\$.",
    "Find \$\\int x^4 + 5x^2 \\, dx\$.",
    "Find \$\\lim_{x \\to 0^+} [|x|/x]\$, the right-hand limit as x approaches 0.",
    "Find \$\\lim_{x \\to 0^-} [|x|/x]\$, the left-hand limit as x approaches 0.",
    "Find \$\\lim_{x \\to 3^+} [(x-3)/|x-3|]\$.",
    "Find \$f''(1)\$ for \$f(x) = x^3 - 2x\$.",
    "Find the absolute minimum value of \$f(x) = x^2 - 4x + 3\$ on the closed interval [0,5].",
    "Find the area of the region bounded by \$y = 3x\$, the x-axis, \$x=0\$, and x=4.",
    "Find the area of the region bounded by \$y = 4 - x^2\$, the x-axis, \$x=-2\$, and x=2.",
    "Find the area of the region bounded by \$y = 6 - x\$ and \$y = x^2 between x=-3\$ and x=2.",
    "Find the area of the region bounded by \$y = x + 3\$ and \$y = x^2 - 1 between x=-1\$ and x=1.",
    "Find the area of the region bounded by \$y = x + 5\$ and \$y = x^2 - 1 between x=-2\$ and x=3.",
    "Find the area of the region bounded by \$y = x^2\$, the x-axis, \$x=0\$, and x=2.",
    "Find the area of the region bounded by \$y = x^3\$, the x-axis, \$x=0\$, and x=2.",
    "Find the critical point(s) of \$f(x) = 2x^3 - 3x^2 - 12x + 4\$.",
    "Find the critical point(s) of \$f(x) = x^2 - 6x + 5\$.",
    "Find the critical point(s) of \$f(x) = x^3 - 12x\$.",
    "Find the critical point(s) of \$f(x) = x^3 - 3x + 1\$.",
    "Find the derivative of \$f(x) = (2x + 1)/(x^2 + 1)\$.",
    "Find the derivative of \$f(x) = (2x - 5)^4\$.",
    "Find the derivative of \$f(x) = (\\sin(x))/(x)\$.",
    "Find the derivative of \$f(x) = (x)/(x + 1)\$.",
    "Find the derivative of \$f(x) = (x^2 + 1)^3\$.",
    "Find the derivative of \$f(x) = (x^2)/(x - 2)\$.",
    "Find the derivative of \$f(x) = (x^3 - 2x)^2\$.",
    "Find the derivative of \$f(x) = 2x^7 + 5\$.",
    "Find the derivative of \$f(x) = 3 \\sin(x)\$.",
    "Find the derivative of \$f(x) = 3x^4\$.",
    "Find the derivative of \$f(x) = 7x^3 - 2x^2 + x\$.",
    "Find the derivative of \$f(x) = \\cos(x)\$.",
    "Find the derivative of \$f(x) = \\ln(3x^2 + 5)\$.",
    "Find the derivative of \$f(x) = \\ln(5x - 1)\$.",
    "Find the derivative of \$f(x) = \\ln(\\cos(x))\$.",
    "Find the derivative of \$f(x) = \\ln(x^3 - 2)\$.",
    "Find the derivative of \$f(x) = \\sin(2x + 3)\$.",
    "Find the derivative of \$f(x) = \\sin(3x - 1)\$.",
    "Find the derivative of \$f(x) = \\sin(x) + \\cos(x)\$.",
    "Find the derivative of \$f(x) = \\sin(x) \\cdot \\cos(x)\$.",
    "Find the derivative of \$f(x) = \\sin(x)\$.",
    "Find the derivative of \$f(x) = \\sin(x^2)\$.",
    "Find the derivative of \$f(x) = \\tan(x)\$.",
    "Find the derivative of \$f(x) = a \\cos(x)\$.",
    "Find the derivative of \$f(x) = a \\sin(x)\$.",
    "Find the derivative of \$f(x) = a \\tan(x)\$.",
    "Find the derivative of \$f(x) = e^{2x - 1}\$.",
    "Find the derivative of \$f(x) = e^{4x}\$.",
    "Find the derivative of \$f(x) = e^{\\sin(x)}\$.",
    "Find the derivative of \$f(x) = e^{x^2}\$.",
    "Find the derivative of \$f(x) = x \\cdot \\cos(x)\$.",
    "Find the derivative of \$f(x) = x^2 \\cdot \\sin(x)\$.",
    "Find the derivative of \$f(x) = x^2 \\cdot x + 1\$.",
    "Find the derivative of \$f(x) = x^2/2 - 3x\$.",
    "Find the derivative of \$f(x) = x^5\$.",
    "Find the derivative of \$f(x) = x^6 - 4x\$.",
    "Find the equation of the line normal to the curve \$y = 1/x\$ at the point (2, 1/2).",
    "Find the equation of the line normal to the curve \$y = x^3 + 1\$ at the point (-1,0).",
    "Find the equation of the line tangent to the curve \$y = 3x^2 + 1\$ at the point (1,4).",
    "Find the equation of the tangent line to \$y = x^2 - 3x + 2\$ at x = 1.",
    "Find the equation of the tangent line to \$y = x^2\$ at x = -1.",
    "Find the equation of the tangent line to \$y = x^2\$ at x = 3.",
    "Find the equation of the tangent line to \$y = x^3\$ at x = 1.",
    "Find the horizontal asymptote of the graph of \$y = (2x^2 + 1)/(x^2 - 4)\$.",
    "Find the horizontal asymptote of the graph of \$y = (3x + 1)/(x - 5)\$.",
    "Find the horizontal asymptote of the graph of \$y = (x - 1)/(x + 2)\$.",
    "Find the inverse of the function \$f(x) = (x + 1)/2\$.",
    "Find the inverse of the function \$f(x) = 2x + 3\$.",
    "Find the inverse of the function \$f(x) = x^3\$.",
    "Find the second derivative f''(x) for \$f(x) = x^4 - 3x^2\$.",
    "Find the second derivative of \$f(x) = \\ln(x)\$, for \$x > 0.\$",
    "Find the second derivative of \$f(x) = e^{2x}\$.",
    "Find the slope of the line tangent to the curve \$y = x^3\$ at the point (1,1).",
    "Find the slope of the tangent line to \$y = 2x^2 + 1\$ at x = -1.",
    "Find the slope of the tangent line to \$y = x^2 - 4x + 3\$ at x = 1.",
    "Find the slope of the tangent line to \$y = x^2\$ at x = 3.",
    "Find the slope of the tangent line to \$y = x^3 - 3x\$ at x = 2.",
    "Find the slope of the tangent to the curve \$y = x^2 - 4x + 3\$ at the point (3,0).",
    "Find the third derivative f'''(x) for \$f(x) = \\sin(x)\$.",
    "Find the vertical asymptote of the graph of \$y = (x + 1)/(x - 3)\$.",
    "Find the vertical asymptotes of the graph of \$y = 1/(x^2 - 9)\$.",
    "Find the volume of the solid formed by revolving \$y = 2\$ about the x-axis from x=0 to x=3.",
    "Find the volume of the solid formed by revolving \$y = \\sqrt{x}\$ about the x-axis from x=0 to x=4.",
    "Find the volume of the solid formed by revolving \$y = x\$ about the x-axis from x=0 to x=4.",
    "Find the volume of the solid formed by revolving \$y = x^2\$ about the x-axis from x=0 to x=1.",
    "Find the volume of the solid formed by revolving about the y-axis the region under \$y = \\sqrt{x}\$ from x=0 to x=4.",
    "Find the volume of the solid formed by revolving about the y-axis the region under \$y = x\$ from x=0 to x=3.",
    "Find the volume of the solid formed by revolving about the y-axis the region under \$y = x^2\$ from x=0 to x=2.",
    "Find the volume of the solid formed by revolving about the y-axis the region under \$y = x^3\$ from x=0 to x=1.",
    "Find the x-intercepts of the graph of \$y = x^2 - 5x + 6\$.",
    "Find the y-intercepts of the graph of x^2 + y^2 = 9.",
    "For \$(f \\circ g)(x) = f(g(x))\$ to be defined, \$x\$ must first be in the domain of \$g\$: \$g(x) = \\sqrt{x-1}\$ requires \$x \\geq 1\$. Since \$f(x)=x^{2}\$ accepts any real input, no further restriction is added, so the domain of \$f \\circ g\$ is \$x \\geq 1\$.",
    "For \$(g \\circ f)(x) = g(f(x))\$, \$x\$ must first be in the domain of \$f\$: \$f(x) = \\sqrt{x}\$ requires \$x \\geq 0\$. Since \$g(x)=x-4\$ accepts any real input, no further restriction is added, so the domain of \$g \\circ f\$ is \$x \\geq 0\$.",
    "For \$f(x) = (x^2-25)/(x-5)\$ if \$x \\neq 5\$, and \$f(5)\$\$=10\$, is f continuous at x=5?",
    "For \$f(x) = (x^2-25)/(x-5)\$ if \$x \\neq 5\$, and \$f(5)\$\$=7\$, is f continuous at x=5?",
    "For \$f(x) = 2x^3 - 3x^2 + 2\$, classify the critical point at x = 1.",
    "For \$f(x) = \\frac{1}{\\sqrt{x + 5}}\$ to be defined, the denominator must not be zero: \$\\sqrt{x + 5} \\neq 0\$, which excludes \$x = -5\$. Combining these conditions, the domain is \$\\left(-5, \\infty\\right)\$.",
    "For \$f(x) = \\frac{1}{x - 3}\$ to be defined, the denominator must not be zero: \$x - 3 \\neq 0\$, which excludes \$x = 3\$. Combining these conditions, the domain is \$\\left(-\\infty, 3\\right) \\cup \\left(3, \\infty\\right)\$.",
    "For \$f(x) = \\frac{1}{x^{2} - 4}\$ to be defined, the denominator must not be zero: \$x^{2} - 4 \\neq 0\$, which excludes \$x = -2 \\textrm{ and } x = 2\$. Combining these conditions, the domain is \$\\left(-\\infty, -2\\right) \\cup \\left(-2, 2\\right) \\cup \\left(2, \\infty\\right)\$.",
    "For \$f(x) = \\frac{\\sqrt{x + 1}}{x - 4}\$ to be defined, the denominator must not be zero: \$x - 4 \\neq 0\$, which excludes \$x = 4\$; and the expression under the square root must be non-negative: \$x + 1 \\geq 0\$, which gives \$\\left[-1, \\infty\\right)\$. Combining these conditions, the domain is \$\\left[-1, 4\\right) \\cup \\left(4, \\infty\\right)\$.",
    "For \$f(x) = \\sqrt{9 - x^{2}}\$ to be defined, the expression under the square root must be non-negative: \$9 - x^{2} \\geq 0\$, which gives \$\\left[-3, 3\\right]\$. Combining these conditions, the domain is \$\\left[-3, 3\\right]\$.",
    "For \$f(x) = \\sqrt{x - 2}\$ to be defined, the expression under the square root must be non-negative: \$x - 2 \\geq 0\$, which gives \$\\left[2, \\infty\\right)\$. Combining these conditions, the domain is \$\\left[2, \\infty\\right)\$.",
    "For \$f(x) = x^2 - 4x + 3\$, on which interval is f increasing?",
    "For \$f(x) = x^3 - 3x\$, determine the nature of the critical point at x = -1.",
    "For \$f(x) = x^3 - 3x\$, on which interval is f decreasing?",
    "For \$f(x) = x^3 - 3x^2\$, classify the critical point at x = 2.",
    "For \$f(x) = x^3 - 6x^2 + 9x\$, find the x-coordinate of the point of inflection.",
    "For \$f(x) = x^4 - 2x^2\$, on which interval is f concave up?",
    "For \$f(x) = x^4 - 4x^2\$, the second derivative test is inconclusive or gives a maximum at one of its critical points. What does \$f''(0)\$ indicate about x = 0?",
    "For \$x < 0\$, \$|x| = -x\$, so \$\\dfrac{|x|}{x} = \\dfrac{-x}{x} = -1\$ for every \$x<0\$. Hence \$\\lim_{x \\to 0^-} \\dfrac{|x|}{x} = -1\$.",
    "For \$x < 1\$, \$f(x) = x+1\$, so the left-hand limit uses this branch: \$\\lim_{x \\to 1^-} (x+1) = 1 + 1 = 2\$.",
    "For \$x > 0\$, \$|x| = x\$, so \$\\dfrac{|x|}{x} = \\dfrac{x}{x} = 1\$ for every \$x>0\$. Hence \$\\lim_{x \\to 0^+} \\dfrac{|x|}{x} = 1\$.",
    "For \$x > 3\$, \$x - 3 > 0\$ so \$|x-3| = x-3\$, giving \$\\dfrac{x-3}{|x-3|} = 1\$ for every \$x\$ just above \$3\$. Hence \$\\lim_{x \\to 3^+} \\dfrac{x-3}{|x-3|} = 1\$.",
    "For \$x \\geq 1\$, \$f(x) = 4-x\$, so the right-hand limit uses this branch: \$\\lim_{x \\to 1^+} (4-x) = 4 - 1 = 3\$.",
    "For a rational function, the horizontal asymptote is \$\\lim_{x \\to \\infty} \\dfrac{x-1}{x+2}\$. Dividing numerator and denominator by \$x\$: \$\\dfrac{1 - 1/x}{1 + 2/x} \\to \\dfrac{1}{1} = 1\$ as \$x \\to \\infty\$. So \$y=1\$ is the horizontal asymptote.",
    "For the displacement s(t) = t^3 - 6t^2 + 9t, find the acceleration at t = 1.",
    "For the greatest integer function \$f(x) = [x]\$, find \$\\lim_{x \\to 3⁺}\$  f(x).",
    "For the greatest integer function \$f(x) = [x]\$, find \$\\lim_{x \\to 3⁻}\$  f(x).",
    "Given \$f(x) = 2x+1\$, \$g(x) = x^2\$, find \$(f \\cdot g)(3)\$.",
    "Given \$f(x) = 2x+1\$, \$g(x) = x^2\$, find \$(f+g)(3)\$.",
    "Given \$f(x) = 2x-3\$, \$g(x) = x^2+1\$, find \$(f \\circ g)(2)\$.",
    "Given \$f(x) = 3x\$, \$g(x) = x-5\$, find \$(f \\cdot g)(4)\$.",
    "Given \$f(x) = 3x\$, \$g(x) = x-5\$, find \$(f+g)(4)\$.",
    "Given \$f(x) = 3x+4\$, \$g(x) = x^2-2x\$, find \$(f \\circ g)(3)\$.",
    "Given \$f(x) = 4-2x\$, \$g(x) = x^2+3\$, find \$(f \\circ g)(1)\$.",
    "Given \$f(x) = 5-x\$, \$g(x) = x^2\$, find \$(f \\circ g)(3)\$.",
    "Given \$f(x) = x^2\$, \$g(x) = 3x-1\$, find \$(f \\circ g)(1)\$.",
    "Given \$f(x) = x^2+2\$, \$g(x) = 2x-1\$, find \$(f \\cdot g)(2)\$.",
    "Given \$f(x) = x^2+2\$, \$g(x) = 2x-1\$, find \$(f+g)(2)\$.",
    "Given \$f(x) = x^2-1\$, \$g(x) = x+2\$, find \$(f \\circ g)(-1)\$.",
    "Given \$f(x) = x^2-4\$, \$g(x) = x+2\$, find \$(f \\cdot g)(1)\$.",
    "Given \$f(x) = x^2-4\$, \$g(x) = x+2\$, find \$(f+g)(1)\$.",
    "Given \$f(x) = x^3\$, \$g(x) = x-1\$, find \$(f \\circ g)(2)\$.",
    "Given \$f(x) = |x|\$, \$g(x) = 2x-5\$, find \$(f \\circ g)(1)\$.",
    "If \$f(x) = -x+6\$, find \$f^{-1}(2)\$.",
    "If \$f(x) = 1/(x-2)\$ and \$g(x) = \\sqrt{x}\$, what is the domain of (f/g)(x)?",
    "If \$f(x) = 2x+7\$, find \$f^{-1}(3)\$.",
    "If \$f(x) = 3-x\$ for \$x < 2\$ and \$f(x) = x^2-1\$ for \$x \\geq 2\$, find \$\\lim_{x \\to 2⁺}\$  f(x).",
    "If \$f(x) = 3-x\$ for \$x < 2\$ and \$f(x) = x^2-1\$ for \$x \\geq 2\$, find \$\\lim_{x \\to 2⁻}\$  f(x).",
    "If \$f(x) = 3x-4\$, find \$f^{-1}(5)\$.",
    "If \$f(x) = 4x-3\$, find \$f^{-1}(9)\$.",
    "If \$f(x) = 5x - 2\$, find \$f^{-1}(8)\$.",
    "If \$f(x) = 5x+1\$, find \$f^{-1}(11)\$.",
    "If \$f(x) = \\ln(x^2 + 1)\$, find \$f'(2)\$.",
    "If \$f(x) = \\sqrt{x-1}\$ and \$g(x) = \\sqrt{3-x}\$, what is the domain of (f+g)(x)?",
    "If \$f(x) = \\sqrt{x}\$ and \$g(x) = x - 4\$, what is the domain of (f+g)(x)?",
    "If \$f(x) = \\sqrt{x}\$ and \$g(x) = x - 4\$, what is the domain of (g o f)(x), the composition g(f(x))?",
    "If \$f(x) = e^{3x}\$, find \$f'(0)\$.",
    "If \$f(x) = x^2\$ and \$g(x) = \\sqrt{x-1}\$, what is the domain of (f o g)(x), the composition f(g(x))?",
    "If \$x^2\$ + \$y^2\$ = 25, find dy/dx at the point (3,4).",
    "If \$x^3\$ + \$y^3\$ = 9, find dy/dx at the point (1,2).",
    "If a radioactive substance decays according to y(t) = y0 * e^(-kt), and \$k = \\frac{\\ln 2}{30}\$ per year, what is its half-life?",
    "If the graph of \$f(x) = \\sqrt{x}\$ is reflected about the x-axis and shifted 1 unit down, the resulting function is \$g(x) = ?\$",
    "If the graph of \$f(x) = x^2\$ is shifted 3 units to the right and 2 units up, the resulting function is \$g(x) = ?\$",
    "In the partial fraction decomposition (3x+1)/[(x-1)(x+2)] = A/(x-1) + B/(x+2), find A.",
    "In the partial fraction decomposition 1/[(x-1)(x+1)] = A/(x-1) + B/(x+1), find A.",
    "In the partial fraction decomposition 1/[(x-1)(x+1)] = A/(x-1) + B/(x+1), find B.",
    "In the partial fraction decomposition 1/[x(x-1)^2] = A/x + B/(x-1) + C/(x-1)^2, find C (the coefficient of the repeated-factor term 1/(x-1)^2).",
    "In the partial fraction decomposition 5/[(x-2)(x+3)] = A/(x-2) + B/(x+3), find A and B.",
    "Integrate term by term using the power rule for antiderivatives (\$\\int x^n \\, dx = \\dfrac{x^{n+1}}{n+1}\$) and the standard trigonometric antiderivatives: \$\\int 2 \\cdot x^{1} \\, dx = 2 \\cdot \\dfrac{x^{2}}{2}\$; \$\\int 7 \\, dx = 7x\$. Summing the terms and adding the constant of integration: \$\\int f(x) \\, dx = x^{2} + 7 x + C\$.",
    "Integrate term by term using the power rule for antiderivatives (\$\\int x^n \\, dx = \\dfrac{x^{n+1}}{n+1}\$) and the standard trigonometric antiderivatives: \$\\int 3 \\cdot \\sin(x) \\, dx = 3 \\cdot -\\cos(x)\$. Summing the terms and adding the constant of integration: \$\\int f(x) \\, dx = - 3 \\cos{\\left(x \\right)} + C\$.",
    "Integrate term by term using the power rule for antiderivatives (\$\\int x^n \\, dx = \\dfrac{x^{n+1}}{n+1}\$) and the standard trigonometric antiderivatives: \$\\int 3 \\cdot x^{2} \\, dx = 3 \\cdot \\dfrac{x^{3}}{3}\$. Summing the terms and adding the constant of integration: \$\\int f(x) \\, dx = x^{3} + C\$.",
    "Integrate term by term using the power rule for antiderivatives (\$\\int x^n \\, dx = \\dfrac{x^{n+1}}{n+1}\$) and the standard trigonometric antiderivatives: \$\\int 4 \\cdot x^{3} \\, dx = 4 \\cdot \\dfrac{x^{4}}{4}\$; \$\\int -2 \\cdot x^{1} \\, dx = -2 \\cdot \\dfrac{x^{2}}{2}\$. Summing the terms and adding the constant of integration: \$\\int f(x) \\, dx = x^{4} - x^{2} + C\$.",
    "Integrate term by term using the power rule for antiderivatives (\$\\int x^n \\, dx = \\dfrac{x^{n+1}}{n+1}\$) and the standard trigonometric antiderivatives: \$\\int 6 \\cdot x^{5} \\, dx = 6 \\cdot \\dfrac{x^{6}}{6}\$; \$\\int -3 \\, dx = -3x\$. Summing the terms and adding the constant of integration: \$\\int f(x) \\, dx = x^{6} - 3 x + C\$.",
    "Integrate term by term using the power rule for antiderivatives (\$\\int x^n \\, dx = \\dfrac{x^{n+1}}{n+1}\$) and the standard trigonometric antiderivatives: \$\\int \\cos(x) \\, dx = \\sin(x)\$. Summing the terms and adding the constant of integration: \$\\int f(x) \\, dx = \\sin{\\left(x \\right)} + C\$.",
    "Integrate term by term using the power rule for antiderivatives (\$\\int x^n \\, dx = \\dfrac{x^{n+1}}{n+1}\$) and the standard trigonometric antiderivatives: \$\\int \\sec^2(x) \\, dx = \\tan(x)\$. Summing the terms and adding the constant of integration: \$\\int f(x) \\, dx = \\frac{\\sin{\\left(x \\right)}}{\\cos{\\left(x \\right)}} + C\$.",
    "Integrate term by term using the power rule for antiderivatives (\$\\int x^n \\, dx = \\dfrac{x^{n+1}}{n+1}\$) and the standard trigonometric antiderivatives: \$\\int \\sin(x) \\, dx = -\\cos(x)\$. Summing the terms and adding the constant of integration: \$\\int f(x) \\, dx = - \\cos{\\left(x \\right)} + C\$.",
    "Integrate term by term using the power rule for antiderivatives (\$\\int x^n \\, dx = \\dfrac{x^{n+1}}{n+1}\$) and the standard trigonometric antiderivatives: \$\\int x^{4} \\, dx = \\dfrac{x^{5}}{5}\$; \$\\int 5 \\cdot x^{2} \\, dx = 5 \\cdot \\dfrac{x^{3}}{3}\$. Summing the terms and adding the constant of integration: \$\\int f(x) \\, dx = \\frac{x^{5}}{5} + \\frac{5 x^{3}}{3} + C\$.",
    "Just below \$3\$, on the interval \$[2, 3)\$, the greatest integer function \$[x]\$ stays constant at \$2\$ — it only steps up to \$3\$ once \$x\$ reaches \$3\$ itself. So the left-hand limit is \$\\lim_{x \\to 3^-} [x] = 2\$.",
    "Let \$f(x) = (x^2 - 9)/(x - 3)\$ for x not equal to 3, and \$f(3)\$ \$= 10\$. Classify the discontinuity of f at x = 3.",
    "Let \$u = 2 x + 1\$, so \$du = 2 \\, dx\$. \$\\int \\cos(2 x + 1) \\, dx = \\dfrac{1}{2} \\int \\cos(u) \\, du = \\dfrac{1}{2} \\sin(u) + C\$. Substituting back \$u = 2 x + 1\$: \$\\int \\cos(2 x + 1) \\, dx = \\frac{\\sin{\\left(2 x + 1 \\right)}}{2} + C\$.",
    "Let \$u = 3 x + 5\$, so \$du = 3 \\, dx\$. \$\\int \\left(3 x + 5\\right)^{4} \\, dx = \\dfrac{1}{3} \\int u^{4} \\, du = \\dfrac{1}{3} \\cdot \\dfrac{u^{5}}{5} + C\$. Substituting back \$u = 3 x + 5\$ and expanding: \$\\int \\left(3 x + 5\\right)^{4} \\, dx = \\frac{81 x^{5}}{5} + 135 x^{4} + 450 x^{3} + 750 x^{2} + 625 x + C\$.",
    "Let \$u = 4 - 3 x\$, so \$du = -3 \\, dx\$. \$\\int \\left(4 - 3 x\\right)^{3} \\, dx = \\dfrac{1}{-3} \\int u^{3} \\, du = \\dfrac{1}{-3} \\cdot \\dfrac{u^{4}}{4} + C\$. Substituting back \$u = 4 - 3 x\$ and expanding: \$\\int \\left(4 - 3 x\\right)^{3} \\, dx = - \\frac{27 x^{4}}{4} + 36 x^{3} - 72 x^{2} + 64 x + C\$.",
    "No — essential discontinuity",
    "No — jump discontinuity",
    "No — removable discontinuity",
    "Product Rule: \$(uv)' = u'v + uv'\$. With \$u = \\sin{\\left(x \\right)}\$ and \$v = \\cos{\\left(x \\right)}\$: \$u' = \\cos{\\left(x \\right)}\$ and \$v' = - \\sin{\\left(x \\right)}\$. So \$f'(x) = u'v + uv' = (\\cos{\\left(x \\right)})(\\cos{\\left(x \\right)}) + (\\sin{\\left(x \\right)})(- \\sin{\\left(x \\right)}) = \\cos{\\left(2 x \\right)}\$.",
    "Product Rule: \$(uv)' = u'v + uv'\$. With \$u = x\$ and \$v = \\cos{\\left(x \\right)}\$: \$u' = 1\$ and \$v' = - \\sin{\\left(x \\right)}\$. So \$f'(x) = u'v + uv' = (1)(\\cos{\\left(x \\right)}) + (x)(- \\sin{\\left(x \\right)}) = - x \\sin{\\left(x \\right)} + \\cos{\\left(x \\right)}\$.",
    "Product Rule: \$(uv)' = u'v + uv'\$. With \$u = x^{2}\$ and \$v = \\sin{\\left(x \\right)}\$: \$u' = 2 x\$ and \$v' = \\cos{\\left(x \\right)}\$. So \$f'(x) = u'v + uv' = (2 x)(\\sin{\\left(x \\right)}) + (x^{2})(\\cos{\\left(x \\right)}) = x \\left(x \\cos{\\left(x \\right)} + 2 \\sin{\\left(x \\right)}\\right)\$.",
    "Product Rule: \$(uv)' = u'v + uv'\$. With \$u = x^{2}\$ and \$v = x + 1\$: \$u' = 2 x\$ and \$v' = 1\$. So \$f'(x) = u'v + uv' = (2 x)(x + 1) + (x^{2})(1) = x \\left(3 x + 2\\right)\$.",
    "Quotient Rule: \$(u/v)' = \\dfrac{u'v - uv'}{v^2}\$. With \$u = 2 x + 1\$ and \$v = x^{2} + 1\$: \$u' = 2\$ and \$v' = 2 x\$. So \$f'(x) = \\dfrac{u'v - uv'}{v^2} = \\dfrac{(2)(x^{2} + 1) - (2 x + 1)(2 x)}{(x^{2} + 1)^2} = \\dfrac{- 2 x^{2} - 2 x + 2}{x^{4} + 2 x^{2} + 1}\$.",
    "Quotient Rule: \$(u/v)' = \\dfrac{u'v - uv'}{v^2}\$. With \$u = \\sin{\\left(x \\right)}\$ and \$v = x\$: \$u' = \\cos{\\left(x \\right)}\$ and \$v' = 1\$. So \$f'(x) = \\dfrac{u'v - uv'}{v^2} = \\dfrac{(\\cos{\\left(x \\right)})(x) - (\\sin{\\left(x \\right)})(1)}{(x)^2} = \\dfrac{x \\cos{\\left(x \\right)} - \\sin{\\left(x \\right)}}{x^{2}}\$.",
    "Quotient Rule: \$(u/v)' = \\dfrac{u'v - uv'}{v^2}\$. With \$u = x\$ and \$v = x + 1\$: \$u' = 1\$ and \$v' = 1\$. So \$f'(x) = \\dfrac{u'v - uv'}{v^2} = \\dfrac{(1)(x + 1) - (x)(1)}{(x + 1)^2} = \\dfrac{1}{x^{2} + 2 x + 1}\$.",
    "Quotient Rule: \$(u/v)' = \\dfrac{u'v - uv'}{v^2}\$. With \$u = x^{2}\$ and \$v = x - 2\$: \$u' = 2 x\$ and \$v' = 1\$. So \$f'(x) = \\dfrac{u'v - uv'}{v^2} = \\dfrac{(2 x)(x - 2) - (x^{2})(1)}{(x - 2)^2} = \\dfrac{x^{2} - 4 x}{x^{2} - 4 x + 4}\$.",
    "R",
    "R except x = -2",
    "R except x = 2",
    "R except x = 2 and x = -2",
    "R except x = 3",
    "Reflecting about the x-axis multiplies the function by \$-1\$, giving \$-\\sqrt{x}\$. Shifting 1 unit down then subtracts 1: \$g(x) = -\\sqrt{x} - 1\$.",
    "Replace \$x\$ by \$-x\$ and \$y\$ by \$-y\$: \$(-x)(-y) = xy\$, which equals the original left-hand side. Since the equation \$xy=4\$ is unchanged under this replacement, the curve is symmetric about the origin.",
    "Replace \$x\$ by \$-x\$: \$(-x)^{3} - (-x) = -x^{3} + x = -(x^{3}-x)\$. Since this equals the negative of the original expression, i.e. \$f(-x) = -f(x)\$, the function is odd and its graph is symmetric about the origin.",
    "Replace \$x\$ by \$-x\$: \$(-x)^{4} - 3(-x)^{2} + 1 = x^{4} - 3x^{2} + 1\$, which is identical to the original equation. Since the equation is unchanged when \$x\$ is replaced by \$-x\$, the curve is symmetric about the y-axis.",
    "Replacing \$x\$ with \$cx\$ (for \$c>1\$) inside a function compresses its graph horizontally by a factor of \$c\$. Here \$y=(2x)^{3}\$ replaces \$x\$ with \$2x\$, so the graph of \$y=x^{3}\$ is compressed horizontally by a factor of \$2\$.",
    "Rewrite \$\\dfrac{\\sin(3x)}{5x}\$ as \$\\frac{3}{5} \\cdot \\dfrac{\\sin(3x)}{3x}\$. Using \$\\lim_{x \\to 0} \\dfrac{\\sin(kx)}{kx} = 1\$ with \$k=3\$, the second factor tends to \$1\$, leaving \$\\lim_{x \\to 0} \\dfrac{\\sin(3x)}{5x} = \\frac{3}{5} \\cdot 1 = \\frac{3}{5}\$.",
    "Rewrite \$\\dfrac{\\sin(4x)}{x}\$ as \$4 \\cdot \\dfrac{\\sin(4x)}{4x}\$. Using \$\\lim_{x \\to 0} \\dfrac{\\sin(kx)}{kx} = 1\$ with \$k=4\$, the second factor tends to \$1\$, leaving \$\\lim_{x \\to 0} \\dfrac{\\sin(4x)}{x} = 4 \\cdot 1 = 4\$.",
    "Set \$x=0\$: \$0 + y^{2} = 9\$, so \$y^{2} = 9\$, giving \$y = 3\$ or \$y = -3\$.",
    "Set \$y = 2x+3\$ and solve for \$x\$: \$y - 3 = 2x\$, so \$x = \\dfrac{y-3}{2}\$. Swapping the roles of \$x\$ and \$y\$ gives \$f^{-1}(x) = \\dfrac{x-3}{2}\$.",
    "Set \$y = 5x-2\$ and solve for \$x\$: \$x = \\dfrac{y+2}{5}\$, so \$f^{-1}(x) = \\dfrac{x+2}{5}\$. Then \$f^{-1}(8) = \\dfrac{8+2}{5} = \\dfrac{10}{5} = 2\$. (Check: \$f(2) = 5(2)-2 = 8\$, confirming the inverse.)",
    "Set \$y = \\dfrac{x+1}{2}\$ and solve for \$x\$: \$2y = x+1\$, so \$x = 2y - 1\$. Swapping \$x\$ and \$y\$ gives \$f^{-1}(x) = 2x - 1\$.",
    "Set \$y = x^{3}\$ and solve for \$x\$: taking the cube root of both sides, \$x = y^{1/3}\$. Swapping \$x\$ and \$y\$ gives \$f^{-1}(x) = x^{1/3}\$.",
    "Shifting a graph \$c\$ units to the right replaces \$x\$ with \$x-c\$ inside the function, and shifting it \$d\$ units up adds \$d\$ to the whole function. So \$f(x) = x^{2}\$ shifted 3 right and 2 up becomes \$g(x) = (x-3)^{2} + 2\$.",
    "Simplify: \$\\frac{x^{2} - 25}{x - 5} = x + 5\$ for \$x \\neq 5\$, so \$\\lim_{x \\to 5} f(x) = 5 + 5 = 10\$, but the given \$f(5) = 7 \\neq 10\$. The limit exists but does not equal \$f(5)\$, so \$f\$ is discontinuous at \$x=5\$.",
    "Simplify: \$\\frac{x^{2} - 25}{x - 5} = x + 5\$ for \$x \\neq 5\$, so \$\\lim_{x \\to 5} f(x) = 5 + 5 = 10\$. This equals the given \$f(5) = 10\$, and since the limit exists and matches \$f(5)\$, \$f\$ is continuous at \$x=5\$.",
    "Since \$f(x) = 3 x^{2} - 5 x + 7\$ is continuous at \$x=2\$ (the denominator, if any, is not zero there), substitute directly: \$\\lim_{x \\to 2} 3 x^{2} - 5 x + 7 = 3 \\cdot 2^{2} - 5 \\cdot 2 + 7 = 9\$.",
    "Since \$f(x) = 5 x - 7\$ is continuous at \$x=3\$ (the denominator, if any, is not zero there), substitute directly: \$\\lim_{x \\to 3} 5 x - 7 = 5 \\cdot 3 - 7 = 8\$.",
    "Since \$f(x) = \\frac{2 x + 3}{x - 1}\$ is continuous at \$x=4\$ (the denominator, if any, is not zero there), substitute directly: \$\\lim_{x \\to 4} \\frac{2 x + 3}{x - 1} = \\frac{2 \\cdot 4 + 3}{4 - 1} = \\frac{11}{3}\$.",
    "Since \$f(x) = \\frac{x^{2} + 2 x}{x + 5}\$ is continuous at \$x=-2\$ (the denominator, if any, is not zero there), substitute directly: \$\\lim_{x \\to -2} \\frac{x^{2} + 2 x}{x + 5} = \\frac{\\left(-2\\right) \\left(2 + -2\\right)}{-2 + 5} = 0\$.",
    "Since \$f(x) = \\frac{x^{2} - 1}{x + 3}\$ is continuous at \$x=1\$ (the denominator, if any, is not zero there), substitute directly: \$\\lim_{x \\to 1} \\frac{x^{2} - 1}{x + 3} = \\frac{1^{2} - 1}{1 + 3} = 0\$.",
    "Since \$f(x) = x^{3} - 4 x + 1\$ is continuous at \$x=-1\$ (the denominator, if any, is not zero there), substitute directly: \$\\lim_{x \\to -1} x^{3} - 4 x + 1 = \\left(-1\\right)^{3} - 4 \\left(-1\\right) + 1 = 4\$.",
    "Since \$f^{-1}(x) = \\sqrt{x}\$ for \$x \\geq 0\$, \$f^{-1}(9) = \\sqrt{9} = 3\$. (Check: \$f(3) = 3^{2} = 9\$, confirming the inverse.)",
    "Since the numerator and denominator have the same degree, the horizontal asymptote is the ratio of leading coefficients: \$y = \\dfrac{2}{1} = 2\$, confirmed by \$\\lim_{x \\to \\infty} \\dfrac{2x^{2}+1}{x^{2}-4} = 2\$.",
    "The denominator vanishes at \$x = 3\$ (and the numerator, \$x+1=4\$, does not), so \$x = 3\$ is a vertical asymptote.",
    "The displacement of a particle moving along a line is s(t) = t^3 - 6t^2 + 9t. Find its velocity at t = 2.",
    "The domain of \$f+g\$ is the intersection of the domains of \$f\$ and \$g\$. \$f(x) = \\sqrt{x}\$ requires \$x \\geq 0\$, while \$g(x) = x - 4\$ is defined for all real \$x\$. The intersection is \$x \\geq 0\$.",
    "The function \$f(x) = (x^2 - 4)/(x - 2)\$ is undefined at x = 2. Classify the discontinuity at x = 2.",
    "The function \$f(x) = x^2\$ for x >= 0 has inverse \$f^{-1}(x) = \\sqrt{x}\$. Find \$f^{-1}(9)\$.",
    "The graph of \$y = f(x)\$ is stretched vertically by a factor of 3 and shifted 2 units to the left. Which formula describes the new graph in terms of f?",
    "The graph of \$y = x^2\$ is shifted 4 units to the right and 8 units down to form \$y = (x-4)^2 - 8\$. What is the lowest point (vertex) of the new graph?",
    "The greatest integer function \$f(x) = [x] (\$the largest integer <= x) is discontinuous at every integer. Classify the discontinuity at x = 2.",
    "The half-life is the time \$T\$ for which \$y(T) = \\dfrac{y_0}{2}\$, i.e. \$e^{-kT} = \\dfrac{1}{2}\$, so \$kT = \\ln 2\$, giving \$T = \\dfrac{\\ln 2}{k}\$. With \$k = \\dfrac{\\ln 2}{30}\$: \$T = \\dfrac{\\ln 2}{\\ln 2 / 30} = 30\$ years.",
    "The slope is \$f'(-1)\$ where \$f'(x) = 4 x\$, so \$f'(-1) = 4 \\left(-1\\right) = -4\$.",
    "The slope is \$f'(1)\$ where \$f'(x) = 2 x - 4\$, so \$f'(1) = 2 \\cdot 1 - 4 = -2\$.",
    "The slope is \$f'(2)\$ where \$f'(x) = 3 x^{2} - 3\$, so \$f'(2) = 3 \\cdot 2^{2} - 3 = 9\$.",
    "The slope is \$f'(3)\$ where \$f'(x) = 2 x\$, so \$f'(3) = 2 \\cdot 3 = 6\$.",
    "The slope of the tangent at \$x=x_0\$ is \$y'(x_0)\$. Here \$y' = 3x^{2}\$, so at \$x_0=1\$, the slope is \$y'(1) = 3(1)^{2} = 3\$.",
    "The velocity of a particle is v(t) = 3t^2 - 6t. Find its acceleration at t = 2.",
    "The vertex of \$y=x^{2}\$ is at the origin \$(0,0)\$. Shifting 4 units right moves the x-coordinate to \$4\$, and shifting 8 units down moves the y-coordinate to \$-8\$, giving the new vertex \$(4,-8)\$.",
    "The x-intercepts satisfy \$y=0\$: \$x^{2} - 5x + 6 = 0\$, which factors as \$(x-2)(x-3) = 0\$, giving \$x=2\$ or \$x=3\$.",
    "This is a \$0/0\$ form. Differentiate numerator and denominator separately: \$\\dfrac{d}{dx}[1 - \\cos{\\left(x \\right)}] = \\sin{\\left(x \\right)}\$ and \$\\dfrac{d}{dx}[x^{2}] = 2 x\$. By L'Hopital's Rule, \$\\lim_{x \\to 0} \\frac{1 - \\cos{\\left(x \\right)}}{x^{2}} = \\lim_{x \\to 0} \\dfrac{\\sin{\\left(x \\right)}}{2 x} = \\frac{\\sin{\\left(0 \\right)}}{2 \\cdot 0} = \\frac{1}{2}\$.",
    "This is a \$0/0\$ form. Differentiate numerator and denominator separately: \$\\dfrac{d}{dx}[\\sin{\\left(x \\right)}] = \\cos{\\left(x \\right)}\$ and \$\\dfrac{d}{dx}[x] = 1\$. By L'Hopital's Rule, \$\\lim_{x \\to 0} \\frac{\\sin{\\left(x \\right)}}{x} = \\lim_{x \\to 0} \\dfrac{\\cos{\\left(x \\right)}}{1} = \\cos{\\left(0 \\right)} = 1\$.",
    "This is a \$0/0\$ form. Differentiate numerator and denominator separately: \$\\dfrac{d}{dx}[x^{2} - 1] = 2 x\$ and \$\\dfrac{d}{dx}[x - 1] = 1\$. By L'Hopital's Rule, \$\\lim_{x \\to 1} \\frac{x^{2} - 1}{x - 1} = \\lim_{x \\to 1} \\dfrac{2 x}{1} = 2 \\cdot 1 = 2\$.",
    "This is a \$0/0\$ form. Differentiate numerator and denominator separately: \$\\dfrac{d}{dx}[x^{2} - 4] = 2 x\$ and \$\\dfrac{d}{dx}[x - 2] = 1\$. By L'Hopital's Rule, \$\\lim_{x \\to 2} \\frac{x^{2} - 4}{x - 2} = \\lim_{x \\to 2} \\dfrac{2 x}{1} = 2 \\cdot 2 = 4\$.",
    "To find \$f^{-1}(11)\$, solve \$f(x) = 11\$ for \$x\$: \$5 x + 1 = 11\$. Rearranging gives \$x = 2\$, so \$f^{-1}(11) = 2\$.",
    "To find \$f^{-1}(2)\$, solve \$f(x) = 2\$ for \$x\$: \$6 - x = 2\$. Rearranging gives \$x = 4\$, so \$f^{-1}(2) = 4\$.",
    "To find \$f^{-1}(3)\$, solve \$f(x) = 3\$ for \$x\$: \$2 x + 7 = 3\$. Rearranging gives \$x = -2\$, so \$f^{-1}(3) = -2\$.",
    "To find \$f^{-1}(5)\$, solve \$f(x) = 5\$ for \$x\$: \$3 x - 4 = 5\$. Rearranging gives \$x = 3\$, so \$f^{-1}(5) = 3\$.",
    "To find \$f^{-1}(9)\$, solve \$f(x) = 9\$ for \$x\$: \$4 x - 3 = 9\$. Rearranging gives \$x = 3\$, so \$f^{-1}(9) = 3\$.",
    "To obtain the graph of \$y = (2x)^3\$ from the graph of \$y = x^3\$, you should:",
    "Use first principles to find f'(x) for \$f(x) = 1/x (x != 0)\$.",
    "Use first principles to find f'(x) for \$f(x) = x^2 + 2x\$, then evaluate \$f'(1)\$.",
    "Use first principles to find f'(x) for \$f(x) = x^2 - 3x\$, then evaluate \$f'(2)\$.",
    "Use the definition of the derivative (first principles) -- that is, f'(x) as the limit, as h approaches 0, of the difference quotient [f(x+h) - f(x)]/h -- to find f'(x) for \$f(x) = x^2\$.",
    "Use the definition of the derivative (first principles) to find f'(x) for \$f(x) = 3x + 2\$.",
    "Using Integration by Parts, find \$\\int x \\cos(x) \\, dx\$.",
    "Using Integration by Parts, find \$\\int x \\sin(x) \\, dx\$.",
    "Using Integration by Parts, find \$\\int xe^{x} \\, dx\$.",
    "Using an appropriate substitution for the inner expression, \$\\int \\sin{\\left(5 x \\right)} \\, dx = - \\frac{\\cos{\\left(5 x \\right)}}{5} + C\$.",
    "Using integration by parts with \$u = x\$, \$dv = e^{x} \\, dx\$: \$v = e^{x}\$, so \$\\int x \\, e^{x} \\, dx = xe^{x} - \\int e^{x} \\, dx = \\left(x - 1\\right) e^{x} + C\$. Evaluating from \$0\$ to \$1\$: \$(\\left(-1 + 1\\right) e^{1}) - (\\left(-1 + 0\\right) e^{0}) = 0 - -1 = 1\$.",
    "Using substitution, an antiderivative is \$F(x) = \\frac{\\log{\\left(x^{2} + 4 \\right)}}{2}\$. Evaluating from \$x=0\$ to \$x=2\$: \$F(2) - F(0) = \\log{\\left(2 \\sqrt{2} \\right)} - \\log{\\left(2 \\right)} = \\log{\\left(\\sqrt{2} \\right)}\$.",
    "Using substitution, an antiderivative is \$F(x) = \\frac{\\sin^{3}{\\left(x \\right)}}{3}\$. Evaluating from \$x=0\$ to \$x=\\frac{\\pi}{2}\$: \$F(\\frac{\\pi}{2}) - F(0) = \\frac{1}{3} - 0 = \\frac{1}{3}\$.",
    "Using substitution, an antiderivative is \$F(x) = \\frac{x^{8}}{4} + x^{6} + \\frac{3 x^{4}}{2} + x^{2}\$. Evaluating from \$x=0\$ to \$x=1\$: \$F(1) - F(0) = \\frac{15}{4} - 0 = \\frac{15}{4}\$.",
    "Using the standard derivative formula for inverse trigonometric functions: \$\\dfrac{d}{dx}[\\arccos(x)] = - \\frac{1}{\\sqrt{1 - x^{2}}}\$.",
    "Using the standard derivative formula for inverse trigonometric functions: \$\\dfrac{d}{dx}[\\arcsin(x)] = \\frac{1}{\\sqrt{1 - x^{2}}}\$.",
    "Using the standard derivative formula for inverse trigonometric functions: \$\\dfrac{d}{dx}[\\arctan(x)] = \\frac{1}{x^{2} + 1}\$.",
    "Using the standard limit \$\\lim_{x \\to 0} \\dfrac{\\cos(x) - 1}{x} = 0\$ (equivalently \$\\lim_{x \\to 0} \\dfrac{1 - \\cos(x)}{x} = 0\$, since \$1-\\cos x\$ is a sign flip of \$\\cos x - 1\$): \$\\lim_{x \\to 0} \\frac{1 - \\cos{\\left(x \\right)}}{x} = 0\$.",
    "Velocity is \$v(t) = s'(t) = 16 - 2t\$. The ball is at its highest point when \$v(t)=0\$: \$16 - 2t = 0 \\Rightarrow t = 8\$.",
    "Velocity is \$v(t) = s'(t) = 3t^{2} - 12t + 9\$. At \$t=2\$: \$v(2) = 3(2)^{2} - 12(2) + 9 = 12 - 24 + 9 = -3\$.",
    "Vertical asymptotes of a proper rational function occur where the denominator is zero (and the numerator is not): \$x^{2} - 9 = 0 \\Rightarrow x = 3\$ or \$x=-3\$.",
    "What is the domain of \$f(x) = 1/(x-3)?\$",
    "What is the domain of \$f(x) = 1/(x^2-4)?\$",
    "What is the domain of \$f(x) = 1/\\sqrt{x+5}?\$",
    "What is the domain of \$f(x) = \\sqrt{9-x^2}?\$",
    "What is the domain of \$f(x) = \\sqrt{x+1}/(x-4)?\$",
    "What is the domain of \$f(x) = \\sqrt{x-2}?\$",
    "With \$u = 2 x + 1\$, \$du = 2 \\, dx\$. \$\\int \\dfrac{2}{2 x + 1} \\, dx = \\int \\dfrac{1}{u} \\, du = \\ln|u| + C = \\ln|2 x + 1| + C\$.",
    "With \$u = 5 x\$, \$du = 5 \\, dx\$. \$\\int e^{5 x} \\, dx = \\dfrac{1}{5} \\int e^u \\, du = \\dfrac{1}{5} e^u + C = \\dfrac{1}{5} e^{5 x} + C\$.",
    "With \$u = x\$ and \$dv = \\cos{\\left(x \\right)} \\, dx\$: \$du = dx\$ and \$v = \\sin{\\left(x \\right)}\$. Integration by parts, \$\\int u \\, dv = uv - \\int v \\, du\$, gives \$\\int x \\cos{\\left(x \\right)} \\, dx = x\\sin{\\left(x \\right)} - \\int \\sin{\\left(x \\right)} \\, dx = x \\sin{\\left(x \\right)} + \\cos{\\left(x \\right)} + C\$.",
    "With \$u = x\$ and \$dv = \\sin{\\left(x \\right)} \\, dx\$: \$du = dx\$ and \$v = - \\cos{\\left(x \\right)}\$. Integration by parts, \$\\int u \\, dv = uv - \\int v \\, du\$, gives \$\\int x \\sin{\\left(x \\right)} \\, dx = x- \\cos{\\left(x \\right)} - \\int - \\cos{\\left(x \\right)} \\, dx = - x \\cos{\\left(x \\right)} + \\sin{\\left(x \\right)} + C\$.",
    "With \$u = x\$ and \$dv = e^{x} \\, dx\$: \$du = dx\$ and \$v = e^{x}\$. Integration by parts, \$\\int u \\, dv = uv - \\int v \\, du\$, gives \$\\int x e^{x} \\, dx = xe^{x} - \\int e^{x} \\, dx = \\left(x - 1\\right) e^{x} + C\$.",
    "With \$u = x\$, \$du = 1 \\, dx\$. \$\\int \\dfrac{1}{x} \\, dx = \\int \\dfrac{1}{u} \\, du = \\ln|u| + C = \\ln|x| + C\$.",
    "With half-life 30 years, the decay model is \$y(t) = 100 \\cdot 2^{-t/30}\$ (equivalently \$y(t)=100e^{kt}\$ with \$k = -\\dfrac{\\ln 2}{30}\$, since \$y(30)=\\dfrac{100}{2}\$ fixes \$k\$). At \$t=100\$: \$y(100) = 100 \\cdot 2^{-100/30} \\approx 9.92\$ mg.",
    "Writing \$\\tan(x) = \\sin(x)/\\cos(x)\$ and substituting \$v = \\cos(x)\$ (so \$dv = -\\sin(x) \\, dx\$) gives \$\\int \\tan(x) \\, dx = -\\ln|\\cos(x)| + C\$, which is the same as \$\\ln|\\sec(x)| + C\$ (since \$-\\ln|\\cos(x)| = \\ln|\\cos(x)|^{-1} = \\ln|\\sec(x)|\$).",
    "Yes — f is continuous at x=5",
    "about 0.99 mg",
    "about 33.3 mg",
    "about 50 mg",
    "about 9.92 mg",
    "all real numbers",
    "all real x",
    "cannot be determined",
    "compress the graph of \$y = x^3\$ horizontally by a factor of 2",
    "does not exist",
    "does not exist (\$\\infty\$)",
    "does not exist and is not infinite",
    "essential (infinite) discontinuity",
    "essential discontinuity",
    "essential discontinuity that is not a jump",
    "f is actually continuous at x=2",
    "f is continuous at x=0",
    "f is continuous at x=1",
    "f is continuous at x=2",
    "f is continuous at x=3",
    "infinity",
    "jump discontinuity",
    "negative infinity",
    "neither",
    "neither (\$f''(1)\$ \$= 0)\$",
    "no critical points",
    "no interval",
    "no symmetry",
    "not a critical point",
    "point of inflection",
    "relative maximum",
    "relative minimum",
    "removable discontinuity",
    "shift the graph of \$y = x^3\$ to the right by 2 units",
    "stretch the graph of \$y = x^3\$ horizontally by a factor of 2",
    "stretch the graph of \$y = x^3\$ vertically by a factor of 2",
    "symmetric about the origin",
    "symmetric about the x-axis",
    "symmetric about the y-axis",
    "the limit does not exist",
    "the limit does not exist and is not infinite",
    "there are none",
    "x",
    "x = -2 and x = -3",
    "x = 0 and x = 6",
    "x = 1 and x = 6",
    "x = 2 and x = 3",
    "x = 3 and x = -3",
    "x = 9 and x = -9",
    "x not equal to 2",
    "x=0 is not a critical point",
    "xe^(x) + C",
  ];

  testWidgets(
    'every MTH121 field renders without a hard failure',
    (WidgetTester tester) async {
      final List<String> broken = <String>[];
      for (final String field in fields) {
        await tester.pumpWidget(
          MaterialApp(home: Scaffold(body: MathText(field))),
        );
        await tester.pumpAndSettle();
        final Object? err = tester.takeException();
        final bool hasMath = MathText.hasMath(field);
        final bool mathWidgetExists = !hasMath || find.byType(Math).evaluate().isNotEmpty;
        if (err != null) {
          // A Math widget existing in the tree despite an exception means
          // the formula parsed and built fine -- the exception is a
          // downstream debug-only layout assertion from this test's bare,
          // unconstrained-width harness (unlike the real app's cards/lists),
          // not a parsing failure. A release build never throws on layout
          // overflow, so that case is a soft pass here.
          if (!mathWidgetExists) {
            broken.add('EXCEPTION (\$err): \$field');
          }
          continue;
        }
        if (!mathWidgetExists) {
          broken.add('FALLBACK (no Math widget rendered): \$field');
        }
      }
      expect(broken, isEmpty, reason: broken.join('X'));
    },
  );
}
