// Auto-generated: every distinct LaTeX fragment extracted from the
// MTH 121 CBT question bank, verified to render through the real
// flutter_math_fork parser before the data went live. Not meant to be
// hand-maintained -- delete once the question bank content is stable.
import 'package:eduvora/core/widgets/math_text.dart';
import 'package:flutter/material.dart';
import 'package:flutter_math_fork/flutter_math.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  final List<String> expressions = <String>[
    "(-1, 1)",
    "(-\\infty, 2)",
    "(-\\infty, \\infty)",
    "(-\\infty,-1)",
    "(0, 2)",
    "(1 - x)e^{x} + C",
    "(1, \\infty)",
    "(1/2)ln|2x+1| + C",
    "(1/5)e^{5x} + C",
    "(2, \\infty)",
    "(cos x - 1)/x = 0",
    "(f \\cdot g)(1)",
    "(f \\cdot g)(1) = f(1) \\cdot g(1) = -3 \\cdot 3 = -9.",
    "(f \\cdot g)(2)",
    "(f \\cdot g)(2) = f(2) \\cdot g(2) = 6 \\cdot 3 = 18.",
    "(f \\cdot g)(3)",
    "(f \\cdot g)(3) = f(3) \\cdot g(3) = 7 \\cdot 9 = 63.",
    "(f \\cdot g)(4)",
    "(f \\cdot g)(4) = f(4) \\cdot g(4) = 12 \\cdot -1 = -12.",
    "(f \\circ g)(-1)",
    "(f \\circ g)(-1) = f(g(-1)) = f(1) = 0.",
    "(f \\circ g)(1)",
    "(f \\circ g)(1) = f(g(1)) = f(-3) = 3.",
    "(f \\circ g)(1) = f(g(1)) = f(2) = 4.",
    "(f \\circ g)(1) = f(g(1)) = f(4) = -4.",
    "(f \\circ g)(2)",
    "(f \\circ g)(2) = f(g(2)) = f(1) = 1.",
    "(f \\circ g)(2) = f(g(2)) = f(5) = 7.",
    "(f \\circ g)(3)",
    "(f \\circ g)(3) = f(g(3)) = f(3) = 13.",
    "(f \\circ g)(3) = f(g(3)) = f(9) = -4.",
    "(f+g)(1)",
    "(f+g)(1) = f(1) + g(1) = -3 + 3 = 0.",
    "(f+g)(2)",
    "(f+g)(2) = f(2) + g(2) = 6 + 3 = 9.",
    "(f+g)(3)",
    "(f+g)(3) = f(3) + g(3) = 7 + 9 = 16.",
    "(f+g)(4)",
    "(f+g)(4) = f(4) + g(4) = 12 + -1 = 11.",
    "(x - 1)e^{x} + C",
    "(x \\cos(x) + \\sin(x))/x^2",
    "(x \\cos(x) - \\sin(x))/x^2",
    "-1",
    "-1 + E",
    "-1, 1",
    "-1, 2",
    "-1, 3",
    "-1/(x^2 + 1)",
    "-1/3",
    "-1/4",
    "-1/\\cos(x)^2",
    "-1/\\sqrt{3} < x < 1/\\sqrt{3}",
    "-1/sqrt{1 - x^2}",
    "-1/x^2 + C",
    "-11/3",
    "-12",
    "-125/6",
    "-12\\pi",
    "-15/4",
    "-1<x<1",
    "-2",
    "-2 \\cos(2x + 3)",
    "-2 \\sin(2x + 1) + C",
    "-2, 2",
    "-2/3",
    "-22/3",
    "-24",
    "-27x^4/4 + 36x^3 - 72x^2 + 64x + C",
    "-2e^{2x - 1}",
    "-2x \\cos(x^2)",
    "-2x^2/(x^4 + 2x^2 + 1) - 2x/(x^4 + 2x^2 + 1) + 2/(x^4 + 2x^2 + 1)",
    "-3",
    "-3 \\cos(3x - 1)",
    "-3 \\cos(5x)/5 + C",
    "-3 \\cos(x)",
    "-3 \\cos(x) + C",
    "-3 \\leq x \\leq 3",
    "-3 \\leq x \\leq 3.",
    "-3 \\sin(x) + C",
    "-3/4",
    "-32/3",
    "-39/2",
    "-3x^2/(x^3 - 2)",
    "-4",
    "-4/3",
    "-4e^{4x}",
    "-5/(5x - 1)",
    "-5/9",
    "-6",
    "-64\\pi/3",
    "-6x/(3x^2 + 5)",
    "-8",
    "-8/3",
    "-81x^2 + 216x - 144 + C",
    "-81x^4/4 + 108x^3 - 216x^2 + 192x + C",
    "-81x^5/5 - 135x^4 - 450x^3 - 750x^2 - 625x + C",
    "-8\\pi",
    "-9",
    "-\\cos(5x)/5 + C",
    "-\\cos(x)",
    "-\\cos(x) + C",
    "-\\ln(2)/2",
    "-\\pi/5",
    "-\\sin(2x + 1)/2 + C",
    "-\\sin(2x)/2",
    "-\\sin(x)",
    "-\\sin(x) + C",
    "-\\sin(x) + \\cos(x)",
    "-\\sin(x)^2",
    "-\\tan(x)",
    "-\\tan(x) + C",
    "-e^{\\sin(x)}\\cos(x)",
    "-x \\cos(x) + C",
    "-x \\cos(x) + \\sin(x) + C",
    "-x \\sin(x)",
    "-x \\sin(x) + \\cos(x)",
    "-x \\sin(x) - \\cos(x) + C",
    "-x^2 \\cos(x)/2 + C",
    "0",
    "0, 2",
    "0, 3",
    "1",
    "1 - \\sin(x)",
    "1/(3x^2 + 5)",
    "1/(5x - 1)",
    "1/(x + 1)",
    "1/(x^2 + 1)",
    "1/(x^2 + 2x + 1)",
    "1/(x^3 - 2)",
    "1/2",
    "1/3",
    "1/4",
    "1/5",
    "1/\\cos(x)",
    "1/sqrt{1 - x^2}",
    "1/x",
    "1/x^2 + C",
    "10",
    "11",
    "11/3",
    "12",
    "12/5",
    "125/6",
    "128\\pi/3",
    "128x^4 - 1280x^3 + 4800x^2 - 8000x + 5000",
    "12\\pi",
    "12x^2 - 2 + C",
    "12x^3",
    "12x^4",
    "13",
    "137/6",
    "14",
    "14/3",
    "143",
    "14x^6",
    "14x^7",
    "15/2",
    "15/4",
    "16",
    "16/3",
    "16\\pi",
    "16\\pi/3",
    "18",
    "19",
    "19/4",
    "2",
    "2 + C",
    "2 \\cos(2x + 3)",
    "2/(x^2 + 1)",
    "2/3",
    "2/5",
    "20",
    "20x^3",
    "21x^2 - 4x + 1",
    "21x^3 - 4x^2 + x",
    "22/3",
    "24",
    "243x^5/5 + 405x^4 + 1350x^3 + 2250x^2 + 1875x + C",
    "24\\pi",
    "25",
    "25/3",
    "27",
    "27x^4/4 - 36x^3 + 72x^2 - 64x + C",
    "28/3",
    "2\\pi/5",
    "2e^{2x - 1}",
    "2ln|2x+1| + C",
    "2x",
    "2x + 7 + C",
    "2x \\cos(x)",
    "2x \\cos(x^2)",
    "2x \\sin(x)",
    "2x/(x - 2)",
    "2x/(x^2 + 2x + 1) + 1/(x^2 + 2x + 1)",
    "2x^2 + 14x + C",
    "2x^2 + 2x",
    "2x^3 + C",
    "2x^3 - 4x",
    "2x^4 - 2x^2 + C",
    "2x^5/5 + 10x^3/3 + C",
    "2x^6 - 6x + C",
    "2x^7 + 5",
    "3",
    "3 \\cos(3x - 1)",
    "3 \\cos(x)",
    "3 \\cos(x) + C",
    "3 \\log(2)/2",
    "3 \\sin(2x + 1)/2 + C",
    "3 \\sin(x)",
    "3/2",
    "3/4",
    "3/5",
    "30x^4",
    "30x^4 + C",
    "32/3",
    "324x^3 + 1620x^2 + 2700x + 1500 + C",
    "32x^3 - 240x^2 + 600x - 500",
    "33",
    "35/3",
    "36x^2",
    "39/2",
    "3x^2",
    "3x^2 + 2x",
    "3x^2 + C",
    "3x^2/(x^2 - 4x + 4) - 4x/(x^2 - 4x + 4)",
    "3x^2/(x^3 - 2)",
    "3x^4",
    "3x^4 + 6x^2 + 3",
    "4",
    "4/3",
    "4/5",
    "41/2",
    "42x - 4",
    "48",
    "4e^{4x}",
    "4x^3 + 10x + C",
    "4x^3 - 2x + C",
    "5",
    "5 \\cos(5x) + C",
    "5/(5x - 1)",
    "5/3",
    "5/4",
    "50",
    "55/2",
    "56",
    "5e^{5x} + C",
    "5x^4",
    "5x^5",
    "6",
    "63",
    "64/3",
    "64\\pi/3",
    "64x^3 - 480x^2 + 1200x - 1000",
    "65/2",
    "6\\pi",
    "6x",
    "6x + C",
    "6x/(3x^2 + 5)",
    "6x^2/(x^4 + 2x^2 + 1) + 2x/(x^4 + 2x^2 + 1) + 2/(x^4 + 2x^2 + 1)",
    "6x^5 + 12x^3 + 6x",
    "6x^5 - 16x^3 + 8x",
    "6x^5 - 3 + C",
    "6x^5 - 4",
    "6x^6 - 4x",
    "6x^7 + 18x^5 + 18x^3 + 6x",
    "6x^8 - 28x^6 + 40x^4 - 16x^2",
    "7",
    "7x^3 - 2x^2 + x",
    "8",
    "8/3",
    "81x^5/5 + 135x^4 + 450x^3 + 750x^2 + 625x + C",
    "84x^5",
    "8\\pi",
    "8x^3",
    "9",
    "9x^4 - 12x^2 + 4",
    "=",
    "= (Du)/u",
    "= -1/sqrt{1 - x^2}",
    "= -2",
    "= -27x^4/4 + 36x^3 - 72x^2 + 64x + C",
    "= -3 \\cos(x) + C",
    "= -4",
    "= -6",
    "= -\\cos(5x)/5 + C",
    "= -\\cos(x) + C",
    "= -\\sin(x)",
    "= -\\sin(x) + \\cos(x)",
    "= -ln|cos x| + C",
    "= 1/(x^2 + 1)",
    "= 1/sqrt{1 - x^2}",
    "= 12 \\cdot \\pi",
    "= 12 \\cdot x^3",
    "= 125/6",
    "= 14 \\cdot x^6",
    "= 2",
    "= 21 \\cdot x^2 - 4 \\cdot x + 1",
    "= 22/3",
    "= 24",
    "= 2u^1 \\cdot Du = 2(x^3 - 2x)^1 \\cdot (3 \\cdot x^2 - 2) = 6 \\cdot x^5 - 16 \\cdot x^3 + 8 \\cdot x",
    "= 3 \\cdot \\cos(x)",
    "= 32/3",
    "= 3e⁰ = 3",
    "= 3u^2 \\cdot Du = 3(x^2 + 1)^2 \\cdot (2 \\cdot x) = 6 \\cdot x^5 + 12 \\cdot x^3 + 6 \\cdot x",
    "= 4",
    "= 4/5",
    "= 4u^3 \\cdot Du = 4(2x - 5)^3 \\cdot (2) = 64 \\cdot x^3 - 480 \\cdot x^2 + 1200 \\cdot x - 1000",
    "= 5 \\cdot x^4",
    "= 6",
    "= 6 \\cdot x^5 - 4",
    "= 64 \\cdot \\pi/3",
    "= 8 \\cdot \\pi",
    "= 8/3",
    "= 81x^5/5 + 135x^4 + 450x^3 + 750x^2 + 625x + C",
    "= 9",
    "= \\cos(u) \\cdot Du",
    "= \\cos(x)",
    "= \\pi/5",
    "= \\sin(2x + 1)/2 + C",
    "= \\sin(x) + C",
    "= \\tan(x) + C",
    "= \\tan(x)^2 + 1",
    "= e^u \\cdot Du",
    "= x - 3",
    "= x^2 + 7x + C",
    "= x^3 + C",
    "= x^4 - x^2 + C",
    "= x^5/5 + 5x^3/3 + C",
    "= x^6 - 3x + C",
    "=-1",
    "=-2",
    "=0",
    "=1",
    "=10",
    "=3",
    "=6",
    "=7",
    "=7 \\neq 10",
    "=9",
    "D[\\ln(u)]",
    "D[\\sin(u)]",
    "D[e^u]",
    "D[u^2]",
    "D[u^3]",
    "D[u^4]",
    "Du=-\\sin(x)",
    "Du=2",
    "Du=2 \\cdot x",
    "Du=3",
    "Du=3 \\cdot x^2",
    "Du=4",
    "Du=5",
    "Du=6 \\cdot x",
    "Du=\\cos(x)",
    "F(-1) = 11/3 - (-11/3) = 22/3",
    "F(-1) = 6 - (0) = 6",
    "F(0) = 0 - (0) = 0",
    "F(0) = 1/4 - (0) = 1/4",
    "F(0) = 8/3 - (0) = 8/3",
    "F(1) = 20 - (1/2) = 39/2",
    "F(x) = -x^3/3 + 4x",
    "F(x) = 3x^2/2 - x",
    "F(x) = x^2 + x",
    "F(x) = x^3/3",
    "F(x) = x^3/3 - 2x^2 + 3x",
    "F(x) = x^4/4",
    "V = \\\\pi",
    "[x] = 3",
    "\\cos(2x + 3)",
    "\\cos(2x)",
    "\\cos(3x - 1)",
    "\\cos(5x)/5 + C",
    "\\cos(x)",
    "\\cos(x) + 1",
    "\\cos(x) + C",
    "\\cos(x)/x",
    "\\cos(x)^2",
    "\\cos(x)^{-2}",
    "\\cos(x^2)",
    "\\cot(x) + C",
    "\\dfrac{d}{dx}[2x^7 + 5]",
    "\\dfrac{d}{dx}[3 \\sin(x)]",
    "\\dfrac{d}{dx}[3x^4]",
    "\\dfrac{d}{dx}[7x^3 - 2x^2 + x]",
    "\\dfrac{d}{dx}[\\cos(x)]",
    "\\dfrac{d}{dx}[\\sin(x) + \\cos(x)]",
    "\\dfrac{d}{dx}[\\sin(x)]",
    "\\dfrac{d}{dx}[\\tan(x)]",
    "\\dfrac{d}{dx}[a \\cos(x)]",
    "\\dfrac{d}{dx}[a \\sin(x)]",
    "\\dfrac{d}{dx}[a \\tan(x)]",
    "\\dfrac{d}{dx}[x^2/2 - 3x]",
    "\\dfrac{d}{dx}[x^5]",
    "\\dfrac{d}{dx}[x^6 - 4x]",
    "\\infty",
    "\\int (3x + 5)^4 \\, dx",
    "\\int (4 - 3x)^3 \\, dx",
    "\\int 1/x \\, dx",
    "\\int 2/(2x+1) \\, dx",
    "\\int 2x + 7 \\, dx",
    "\\int 3 \\sin(x) \\, dx",
    "\\int 3x^2 \\, dx",
    "\\int 4x^3 - 2x \\, dx",
    "\\int 6x^5 - 3 \\, dx",
    "\\int \\cos(2x + 1) \\, dx",
    "\\int \\cos(x) \\, dx",
    "\\int \\sec(x)^2 \\, dx",
    "\\int \\sin(5x) \\, dx",
    "\\int \\sin(x) \\, dx",
    "\\int \\tan(x) \\, dx",
    "\\int e^{5x} \\, dx",
    "\\int sec^2(x) \\, dx",
    "\\int tan x \\, dx",
    "\\int x \\cos(x) \\, dx",
    "\\int x \\sin(x) \\, dx",
    "\\int x e^x \\, dx",
    "\\int x^4 + 5x^2 \\, dx",
    "\\int xe^{x} \\, dx",
    "\\int_{-1}^{1} -x^2 + x + 4 \\, dx",
    "\\int_{-1}^{1} 4 - x^2 \\, dx",
    "\\int_{-1}^{1} [(x + 3) - (x^2 - 1)] \\, dx",
    "\\int_{-1}^{2} 2x + 1 \\, dx",
    "\\int_{-2}^{2} 4 - x^2 \\, dx",
    "\\int_{-2}^{3} -x^2 + x + 6 \\, dx",
    "\\int_{-2}^{3} [(x + 5) - (x^2 - 1)] \\, dx",
    "\\int_{-3}^{2} -x^2 - x + 6 \\, dx",
    "\\int_{-3}^{2} [(6 - x) - (x^2)] \\, dx",
    "\\int_{0}^{1} (x^2)^2 \\, dx",
    "\\int_{0}^{1} 2x(x^2 + 1)^3 \\, dx",
    "\\int_{0}^{1} x \\cdot e^x \\, dx",
    "\\int_{0}^{1} x^3 \\, dx",
    "\\int_{0}^{2} x/(x^2 + 4) \\, dx",
    "\\int_{0}^{2} x^2 \\, dx",
    "\\int_{0}^{2} x^3 \\, dx",
    "\\int_{0}^{3} (2)^2 \\, dx",
    "\\int_{0}^{3} x^2 - 4x + 3 \\, dx",
    "\\int_{0}^{4} (sqrt{x})^2 \\, dx",
    "\\int_{0}^{4} (x)^2 \\, dx",
    "\\int_{0}^{4} 3x \\, dx",
    "\\int_{0}^{pi/2} \\sin(x)^2 \\cos(x) \\, dx",
    "\\int_{1}^{4} 3x - 1 \\, dx",
    "\\leq x",
    "\\lim_{x \\to -1} [x^3 - 4x + 1]",
    "\\lim_{x \\to -2} [(x^2 + 2x)/(x + 5)]",
    "\\lim_{x \\to 0}",
    "\\lim_{x \\to 0} [(1 - \\cos(x))/x^2]",
    "\\lim_{x \\to 0} [(1-cos x)/x]",
    "\\lim_{x \\to 0} [\\sin(3x)/(5x)]",
    "\\lim_{x \\to 0} [\\sin(4x)/x]",
    "\\lim_{x \\to 0} [\\sin(x)/x]",
    "\\lim_{x \\to 0} [x \\cdot \\sin(1/x)]",
    "\\lim_{x \\to 1} [(x^2 - 1)/(x + 3)]",
    "\\lim_{x \\to 1} [(x^2 - 1)/(x - 1)]",
    "\\lim_{x \\to 2} [(x^2 + x - 6)/(x - 2)]",
    "\\lim_{x \\to 2} [(x^2 - 4)/(x - 2)]",
    "\\lim_{x \\to 2} [(x^2 - 5x + 6)/(x - 2)]",
    "\\lim_{x \\to 2} [(x^3 - 8)/(x - 2)]",
    "\\lim_{x \\to 2} [3x^2 - 5x + 7]",
    "\\lim_{x \\to 2⁺}",
    "\\lim_{x \\to 2⁻}",
    "\\lim_{x \\to 3} [(x^2 - 9)/(x - 3)]",
    "\\lim_{x \\to 3} [5x - 7]",
    "\\lim_{x \\to 3⁺}",
    "\\lim_{x \\to 3⁻}",
    "\\lim_{x \\to 4} [(2x + 3)/(x - 1)]",
    "\\lim_{x \\to 5}",
    "\\lim_{x \\to \\infty} [(2x^2 + 3x)/(5x^2 - x + 1)]",
    "\\lim_{x \\to \\infty} [(3x + 1)/(6x + 5)]",
    "\\lim_{x \\to \\infty} [(4x^3 - x)/(2x^3 + 7)]",
    "\\lim_{x \\to \\infty} [(x + 3)/(x^2 - 4)]",
    "\\lim_{x \\to \\infty} [(x^2 + 1)/(x^3 + 2)]",
    "\\ln(2)",
    "\\ln(2)/2",
    "\\pi/3",
    "\\pi/5",
    "\\sec(x) + C",
    "\\sec(x)\\tan(x) + C",
    "\\sin(2)",
    "\\sin(2x + 1)/2 + C",
    "\\sin(2x)",
    "\\sin(3)",
    "\\sin(3x)/(3x) \\to 1",
    "\\sin(3x)/(5x) = (3/5) \\cdot [\\sin(3x)/(3x)]",
    "\\sin(kx)/x = k",
    "\\sin(x)",
    "\\sin(x) + C",
    "\\sin(x) + \\cos(x)",
    "\\sin(x) - \\cos(x)",
    "\\tan(x)",
    "\\tan(x) + C",
    "du=2dx",
    "du=5dx",
    "dv=e^x dx:",
    "dy/dx = -1/4",
    "dy/dx = -3/4",
    "dy/dx = -x/y",
    "dy/dx = -x^2/y^2",
    "e^{2x - 1}",
    "e^{3}",
    "e^{4x}",
    "e^{5x} + C",
    "e^{5x}/x + C",
    "e^{\\sin(x)}",
    "e^{\\sin(x)}\\cos(x)",
    "e^{x^2}",
    "f''(-1)",
    "f''(1)",
    "f''(2)",
    "f''(3)",
    "f''(x) = -2",
    "f''(x) = 0 gives x=2",
    "f''(x) = 12x^2 - 4",
    "f''(x) = 2",
    "f''(x) = 6 \\cdot x",
    "f''(x) = 6x - 12",
    "f'(-1)",
    "f'(0)",
    "f'(1)",
    "f'(2)",
    "f'(3)",
    "f'(x) = (x + 1)^{-2}",
    "f'(x) = (x \\cdot \\cos(x) - \\sin(x))/x^2",
    "f'(x) = -\\sin(x)^2 + \\cos(x)^2",
    "f'(x) = -\\tan(x)",
    "f'(x) = -x \\cdot \\sin(x) + \\cos(x)",
    "f'(x) = 0 and solving gives x = -1",
    "f'(x) = 0 and solving gives x = -2",
    "f'(x) = 0 and solving gives x = 3",
    "f'(x) = 2 \\cdot (-x^2 - x + 1)/(x^4 + 2 \\cdot x^2 + 1)",
    "f'(x) = 2 \\cdot \\cos(2 \\cdot x + 3)",
    "f'(x) = 2 \\cdot x",
    "f'(x) = 2 \\cdot x - 4",
    "f'(x) = 2 \\cdot x - 6",
    "f'(x) = 2 \\cdot x \\cdot \\cos(x^2)",
    "f'(x) = 2e^{2x - 1}",
    "f'(x) = 2x - 4",
    "f'(x) = 2x/(x^2+1)",
    "f'(x) = 2xe^{x^2}",
    "f'(x) = 3 \\cdot \\cos(3 \\cdot x - 1)",
    "f'(x) = 3 \\cdot x^2 + 2 \\cdot x",
    "f'(x) = 3 \\cdot x^2 - 12",
    "f'(x) = 3 \\cdot x^2 - 3",
    "f'(x) = 3e^{3x}",
    "f'(x) = 3x^2-3 = 3(x-1)(x+1)",
    "f'(x) = 3x^2/(x^3 - 2)",
    "f'(x) = 4 \\cdot x",
    "f'(x) = 4e^{4x}",
    "f'(x) = 5/(5x - 1)",
    "f'(x) = 6 \\cdot x^2 - 6 \\cdot x - 12",
    "f'(x) = 6x/(3x^2 + 5)",
    "f'(x) = e^{\\sin(x)}\\cos(x)",
    "f'(x) = x \\cdot (x - 4)/(x^2 - 4 \\cdot x + 4)",
    "f'(x) = x^2 \\cdot \\cos(x) + 2 \\cdot x \\cdot \\sin(x)",
    "f(-1)",
    "f(1)",
    "f(3)",
    "f(5)",
    "f(x) = (2x + 1)/(x^2 + 1)",
    "f(x) = (2x - 5)^4",
    "f(x) = (\\sin(x))/(x)",
    "f(x) = (x)/(x + 1)",
    "f(x) = (x^2 + 1)^3",
    "f(x) = (x^2)/(x - 2)",
    "f(x) = (x^2-25)/(x-5)",
    "f(x) = (x^3 - 2x)^2",
    "f(x) = -x+6",
    "f(x) = -x^2 + 6x - 5",
    "f(x) = 1/(x-3)?",
    "f(x) = 1/(x^2-4)?",
    "f(x) = 1/\\sqrt{x+5}?",
    "f(x) = 10",
    "f(x) = 2x+1",
    "f(x) = 2x+7",
    "f(x) = 2x-3",
    "f(x) = 2x^3 - 3x^2 - 12x + 4",
    "f(x) = 2x^7 + 5",
    "f(x) = 3 \\sin(x)",
    "f(x) = 3-x",
    "f(x) = 3x",
    "f(x) = 3x+4",
    "f(x) = 3x-4",
    "f(x) = 3x^4",
    "f(x) = 4-2x",
    "f(x) = 4x-3",
    "f(x) = 5-x",
    "f(x) = 5x+1",
    "f(x) = 7x^3 - 2x^2 + x",
    "f(x) = [x]",
    "f(x) = \\cos(x)",
    "f(x) = \\ln(3x^2 + 5)",
    "f(x) = \\ln(5x - 1)",
    "f(x) = \\ln(\\cos(x))",
    "f(x) = \\ln(x^2 + 1)",
    "f(x) = \\ln(x^3 - 2)",
    "f(x) = \\sin(2x + 3)",
    "f(x) = \\sin(3x - 1)",
    "f(x) = \\sin(x)",
    "f(x) = \\sin(x) + \\cos(x)",
    "f(x) = \\sin(x) \\cdot \\cos(x)",
    "f(x) = \\sin(x^2)",
    "f(x) = \\sqrt{9-x^2}?",
    "f(x) = \\sqrt{x+1}/(x-4)?",
    "f(x) = \\sqrt{x-2}?",
    "f(x) = \\tan(x)",
    "f(x) = a \\cos(x)",
    "f(x) = a \\sin(x)",
    "f(x) = a \\tan(x)",
    "f(x) = e^{2x - 1}",
    "f(x) = e^{3x}",
    "f(x) = e^{4x}",
    "f(x) = e^{\\sin(x)}",
    "f(x) = e^{x^2}",
    "f(x) = x \\cdot \\cos(x)",
    "f(x) = x^2",
    "f(x) = x^2 - 4x + 3",
    "f(x) = x^2 - 4x + 7",
    "f(x) = x^2 - 6x + 5",
    "f(x) = x^2 \\cdot \\sin(x)",
    "f(x) = x^2 \\cdot x + 1",
    "f(x) = x^2+2",
    "f(x) = x^2-1",
    "f(x) = x^2-4",
    "f(x) = x^2/2 - 3x",
    "f(x) = x^3",
    "f(x) = x^3 - 12x",
    "f(x) = x^3 - 3x",
    "f(x) = x^3 - 3x + 1",
    "f(x) = x^3 - 6x^2 + 9x",
    "f(x) = x^4 - 2x^2",
    "f(x) = x^5",
    "f(x) = x^6 - 4x",
    "f(x) = |x|",
    "f^{-1}(11)",
    "f^{-1}(2)",
    "f^{-1}(3)",
    "f^{-1}(5)",
    "f^{-1}(9)",
    "g(x) = 2x-1",
    "g(x) = 2x-5",
    "g(x) = 3x-1",
    "g(x) = x+2",
    "g(x) = x-1",
    "g(x) = x-5",
    "g(x) = x^2",
    "g(x) = x^2+1",
    "g(x) = x^2+3",
    "g(x) = x^2-2x",
    "ln|2x+1| + C",
    "ln|\\cos(x)| + C",
    "ln|\\sec(x)| + C",
    "ln|\\sin(x)| + C",
    "ln|x| + C",
    "sqrt{1 - x^2}",
    "v'=-\\sin(x)",
    "v'=1",
    "v'=2 \\cdot x",
    "v'=\\cos(x)",
    "x - 3",
    "x < -1/",
    "x < -5",
    "x < 2",
    "x < 3",
    "x > -1",
    "x > -5",
    "x > -5.",
    "x > 1/",
    "x > 2",
    "x > 3",
    "x \\cdot \\ln(x) + C",
    "x \\cos(x) - \\sin(x) + C",
    "x \\geq -1",
    "x \\geq -1, x \\neq 4",
    "x \\geq -5",
    "x \\geq 2",
    "x \\geq 2.",
    "x \\geq 3",
    "x \\leq -3",
    "x \\leq 2",
    "x \\neq 4",
    "x \\neq 5",
    "x \\sin(x) + C",
    "x \\sin(x) + \\cos(x) + C",
    "x(x \\cos(x) + 2 \\sin(x))",
    "x=-2",
    "x=0",
    "x^2",
    "x^2 + 7x + C",
    "x^2 - 3x",
    "x^2 \\cos(x)",
    "x^2 \\sin(x)/2 + C",
    "x^2/(x^2 - 4x + 4) - 4x/(x^2 - 4x + 4)",
    "x^2/2 - 3x",
    "x^2e^{x}/2 + C",
    "x^3 + C",
    "x^4 + 5x^2 + C",
    "x^4 - x^2 + C",
    "x^5",
    "x^5/5 + 5x^3/3 + C",
    "x^6 - 3x + C",
    "x^6 - 4x",
    "y = -1(x-1) + 0 = y = -1x + 1",
    "y = -1x",
    "y = -1x + 1",
    "y = -2(x--1) + 1 = y = -2x - 1",
    "y = -2x + 1",
    "y = -2x - 1",
    "y = -3x - 2",
    "y = -6x - 9",
    "y = 0x - 1",
    "y = 1x + 1",
    "y = 1x + 3",
    "y = 1x - 2",
    "y = 2 about the x-axis from x=0 to x=3",
    "y = 2x - 1",
    "y = 2x^2 + 1 at x = -1",
    "y = 3(x-1) + 1 = y = 3x - 2",
    "y = 3x",
    "y = 3x + 1",
    "y = 3x - 2",
    "y = 4 - x^2",
    "y = 6 - x and y = x^2 between x=-3 and x=2",
    "y = 6(x-3) + 9 = y = 6x - 9",
    "y = 6x + 9",
    "y = 6x - 9",
    "y = 9x + 6",
    "y = sqrt{x} about the x-axis from x=0 to x=4",
    "y = x + 3 and y = x^2 - 1 between x=-1 and x=1",
    "y = x + 5 and y = x^2 - 1 between x=-2 and x=3",
    "y = x about the x-axis from x=0 to x=4",
    "y = x^2",
    "y = x^2 - 3x + 2 at x = 1",
    "y = x^2 - 4x + 3 at x = 1",
    "y = x^2 about the x-axis from x=0 to x=1",
    "y = x^2 at x = -1",
    "y = x^2 at x = 3",
    "y = x^3",
    "y = x^3 - 3x at x = 2",
    "y = x^3 at x = 1",
  ];

  testWidgets(
    'every MTH 121 LaTeX fragment renders without error or fallback',
    (WidgetTester tester) async {
      final List<String> broken = <String>[];
      for (final String expr in expressions) {
        await tester.pumpWidget(
          MaterialApp(home: Scaffold(body: MathText("\$$expr\$"))),
        );
        await tester.pumpAndSettle();
        if (tester.takeException() != null) {
          broken.add('EXCEPTION: $expr');
          continue;
        }
        if (find.byType(Math).evaluate().isEmpty) {
          broken.add('FALLBACK (no Math widget rendered): $expr');
        }
      }
      expect(broken, isEmpty, reason: broken.join('\n'));
    },
  );
}
