// Auto-generated: every individual LaTeX token from the fully-
// latexified MTH 121 question bank, verified against the real
// flutter_math_fork parser -- both that it parses, and that it
// fits without overflowing a single render line.
import 'package:eduvora/core/widgets/math_text.dart';
import 'package:flutter/material.dart';
import 'package:flutter_math_fork/flutter_math.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  final List<String> expressions = <String>[
    "(-1, 1)",
    "(-1,0)",
    "(-\\infty, 2)",
    "(-\\infty, \\infty)",
    "(-\\infty,-1)",
    "(-x)(-y) = xy",
    "(-x)^{3} - (-x)",
    "(-x)^{4} - 3(-x)^{2} + 1",
    "(0, 2)",
    "(1 - x)e^{x} + C",
    "(1)(\\cos{\\left(x \\right)})",
    "(1, \\infty)",
    "(1,2)",
    "(1,4)",
    "(1/2)ln|2x+1| + C",
    "(1/5)e^{5x} + C",
    "(2 x)(\\sin{\\left(x \\right)})",
    "(2 x)(x + 1) + (x^{2})(1)",
    "(2, \\infty)",
    "(2,\\tfrac{1}{2})",
    "(2^{2} + 2 = 6)",
    "(3,4)",
    "(\\cos{\\left(x \\right)})(\\cos{\\left(x \\right)})",
    "(\\frac{0 \\left(9 - 6 \\cdot 0 + 0^{2}\\right)}{3}",
    "(\\frac{0^{3}}{3} = 0)",
    "(\\frac{0^{4}}{4} = 0)",
    "(\\frac{1 \\left(-2 + 3 \\cdot 1\\right)}{2}",
    "(\\frac{1 \\left(12 - 1^{2}\\right)}{3}",
    "(\\frac{1^{4}}{4} = \\frac{1}{4})",
    "(\\frac{2^{3}}{3} = \\frac{8}{3})",
    "(\\frac{3 \\cdot 0^{2}}{2})",
    "(\\frac{3 \\left(9 - 6 \\cdot 3 + 3^{2}\\right)}{3}",
    "(\\frac{4 \\left(-2 + 3 \\cdot 4\\right)}{2}",
    "(\\frac{\\left(-1\\right) \\left(12 - \\left(-1\\right)^{2}\\right)}{3}",
    "(\\frac{\\left(-1\\right) \\left(24 + 3 \\left(-1\\right) - 2 \\left(-1\\right)^{2}\\right)}{6})",
    "(\\frac{\\left(-2\\right) \\left(12 - \\left(-2\\right)^{2}\\right)}{3})",
    "(\\frac{\\left(-2\\right) \\left(36 + 3 \\left(-2\\right) - 2 \\left(-2\\right)^{2}\\right)}{6})",
    "(\\frac{\\left(-3\\right) \\left(36 - 3 \\left(-3\\right) - 2 \\left(-3\\right)^{2}\\right)}{6})",
    "(\\left(-1 + 0\\right) e^{0})",
    "(\\left(-1 + 1\\right) e^{1})",
    "(\\left(-1\\right)^{2} + -1 = 0)",
    "(\\sin{\\left(x \\right)})(- \\sin{\\left(x \\right)})",
    "(f \\cdot g)(1)",
    "(f \\cdot g)(1) = -3 \\cdot 3 = -9",
    "(f \\cdot g)(1) = f(1) \\cdot g(1)",
    "(f \\cdot g)(2)",
    "(f \\cdot g)(2) = 6 \\cdot 3 = 18",
    "(f \\cdot g)(2) = f(2) \\cdot g(2)",
    "(f \\cdot g)(3)",
    "(f \\cdot g)(3) = 7 \\cdot 9 = 63",
    "(f \\cdot g)(3) = f(3) \\cdot g(3)",
    "(f \\cdot g)(4)",
    "(f \\cdot g)(4) = 12 \\cdot -1 = -12",
    "(f \\cdot g)(4) = f(4) \\cdot g(4)",
    "(f \\circ g)(-1)",
    "(f \\circ g)(-1) = 0",
    "(f \\circ g)(-1) = f(g(-1))",
    "(f \\circ g)(1)",
    "(f \\circ g)(1) = -4",
    "(f \\circ g)(1) = 3",
    "(f \\circ g)(1) = 4",
    "(f \\circ g)(1) = f(g(1))",
    "(f \\circ g)(2)",
    "(f \\circ g)(2) = 1",
    "(f \\circ g)(2) = 7",
    "(f \\circ g)(2) = f(g(2))",
    "(f \\circ g)(3)",
    "(f \\circ g)(3) = -4",
    "(f \\circ g)(3) = 13",
    "(f \\circ g)(3) = f(g(3))",
    "(f+g)(1)",
    "(f+g)(1) = -3 + 3 = 0",
    "(f+g)(1) = f(1) + g(1)",
    "(f+g)(2)",
    "(f+g)(2) = 6 + 3 = 9",
    "(f+g)(2) = f(2) + g(2)",
    "(f+g)(3)",
    "(f+g)(3) = 7 + 9 = 16",
    "(f+g)(3) = f(3) + g(3)",
    "(f+g)(4)",
    "(f+g)(4) = 12 + -1 = 11",
    "(f+g)(4) = f(4) + g(4)",
    "(u/v)' = \\dfrac{u'v - uv'}{v^2}",
    "(uv)' = u'v + uv'",
    "(x - 1)e^{x} + C",
    "(x \\cos(x) + \\sin(x))/x^2",
    "(x \\cos(x) - \\sin(x))/x^2",
    "(x)(- \\sin{\\left(x \\right)})",
    "(x+h)^{2} + 2(x+h) - x^{2} - 2x",
    "(x+h)^{2} - 3(x+h) - x^{2} + 3x",
    "(x-2)(x-3) = 0",
    "(x-3)^{2} \\to 0^{+}",
    "(x^2 - 4)/(x - 2) is undefined at x",
    "(x^{2})(\\cos{\\left(x \\right)})",
    "(x_0,y_0)=(1,4)",
    "+",
    "-",
    "- 3 \\cos{\\left(x \\right)} + C",
    "- 4 x",
    "- \\cos{\\left(x \\right)} + C",
    "- \\frac{11}{3})",
    "- \\frac{1}{\\sqrt{1 - x^{2}}}",
    "- \\frac{27 x^{4}}{4}",
    "- \\frac{\\cos{\\left(5 x \\right)}}{5} + C",
    "- \\frac{x^{3}}{3}",
    "- \\tan{\\left(x \\right)}",
    "- x \\cos{\\left(x \\right)}",
    "- x \\sin{\\left(x \\right)}",
    "-(x^{3}-x)",
    "-1",
    "-1 + E",
    "-1 \\leq \\sin(1/x) \\leq 1",
    "-1 and x",
    "-1, 1",
    "-1, 2",
    "-1, 3",
    "-1/(x^2 + 1)",
    "-1/2",
    "-1/3",
    "-1/4",
    "-1/\\cos(x)^2",
    "-1/\\sqrt{1 - x^2}",
    "-1/\\sqrt{3} < x < 1/\\sqrt{3}",
    "-1/x",
    "-1/x^2",
    "-1/x^2 + C",
    "-11/3",
    "-12",
    "-125/6",
    "-12\\pi",
    "-15/4",
    "-2",
    "-2 \\cdot 2 x^{1}",
    "-2 \\cdot \\dfrac{x^{2}}{2}",
    "-2 \\cos(2x + 3)",
    "-2 \\sin(2x + 1) + C",
    "-2 and x",
    "-2, 2",
    "-2/3",
    "-22/3",
    "-24",
    "-27x^4/4 + 36x^3 - 72x^2 + 64x + C",
    "-2e^{2x - 1}",
    "-2x \\cos(x^2)",
    "-2x^2/(x^4 + 2x^2 + 1)",
    "-3",
    "-3 \\cdot 1 x^{0}",
    "-3 \\cos(3x - 1)",
    "-3 \\cos(5x)/5 + C",
    "-3 \\cos(x)",
    "-3 \\cos(x) + C",
    "-3 \\leq x \\leq 3",
    "-3 \\sin(x) + C",
    "-3 and x",
    "-3/4",
    "-32/3",
    "-39/2",
    "-3x^2/(x^3 - 2)",
    "-4",
    "-4 \\cdot 1 x^{0}",
    "-4/3",
    "-4e^{4x}",
    "-5/(5x - 1)",
    "-5/9",
    "-6",
    "-64\\pi/3",
    "-6x/(3x^2 + 5)",
    "-8",
    "-8/3",
    "-81x^2 + 216x - 144 + C",
    "-81x^4/4 + 108x^3 - 216x^2 + 192x + C",
    "-81x^5/5",
    "-8\\pi",
    "-9",
    "-\\cos(5x)/5 + C",
    "-\\cos(x)",
    "-\\cos(x) + C",
    "-\\dfrac{1}{2}",
    "-\\dfrac{1}{3}",
    "-\\dfrac{1}{x^{4}} \\to -\\infty",
    "-\\infty",
    "-\\ln(2)/2",
    "-\\ln|\\cos(x)|",
    "-\\pi/5",
    "-\\sin(2x + 1)/2 + C",
    "-\\sin(2x)/2",
    "-\\sin(x)",
    "-\\sin(x) + C",
    "-\\sin(x) + \\cos(x)",
    "-\\sin(x)^2",
    "-\\tan(x)",
    "-\\tan(x) + C",
    "-e^{\\sin(x)}\\cos(x)",
    "-x",
    "-x \\cos(x) + C",
    "-x \\cos(x) + \\sin(x) + C",
    "-x \\sin(x)",
    "-x \\sin(x) + \\cos(x)",
    "-x \\sin(x) - \\cos(x) + C",
    "-x^2 \\cos(x)/2 + C",
    "-x^{3} + x",
    "-y",
    "-|x|",
    "-|x| \\leq x\\sin(1/x) \\leq |x|",
    "0",
    "0 + y^{2} = 9",
    "0 - -1",
    "0 - 0",
    "0)",
    "0, 2",
    "0, 3",
    "0/0",
    "1",
    "1 + 1 = 2",
    "1 - \\sin(x)",
    "1 = A(0) + B(0) + C(1) \\Rightarrow C = 1",
    "1 = A(x+1) + B(x-1)",
    "1 = A(x-1)^{2} + Bx(x-1) + Cx",
    "1)",
    "1-\\cos x",
    "1/(3x^2 + 5)",
    "1/(5x - 1)",
    "1/(x + 1)",
    "1/(x^2 + 1)",
    "1/(x^2 + 2x + 1)",
    "1/(x^3 - 2)",
    "1/2",
    "1/2)",
    "1/3",
    "1/4",
    "1/5",
    "1/\\cos(x)",
    "1/\\sqrt{1 - x^2}",
    "1/x",
    "1/x^2",
    "1/x^2 + C",
    "10",
    "11",
    "11/3",
    "12",
    "12 - 24 + 9",
    "12 \\pi",
    "12 x^{3}",
    "12/5",
    "125/6",
    "1280x^3",
    "128\\pi/3",
    "128\\pi/5",
    "128x^4",
    "12\\pi",
    "12x^2 - 2 + C",
    "12x^2 - 3",
    "12x^2 - 6",
    "12x^3",
    "12x^4",
    "13",
    "135 x^{4}",
    "1350x^3",
    "135x^4",
    "137/6",
    "14",
    "14 x^{6}",
    "14/3",
    "143",
    "14x^6",
    "14x^7",
    "15/2",
    "15/4",
    "16",
    "16 - 2t = 0 \\Rightarrow t = 8",
    "16/3",
    "16\\pi",
    "16\\pi/3",
    "18",
    "1875x",
    "18\\pi",
    "19",
    "19/4",
    "2",
    "2 + 2 = 4",
    "2 + 3 = 5",
    "2 + C",
    "2 - 3 = -1",
    "2 \\cdot 1",
    "2 \\cdot 2",
    "2 \\cdot 7 x^{6}",
    "2 \\cdot \\dfrac{x^{2}}{2}",
    "2 \\cos(2x + 3)",
    "2 \\cos{\\left(2 x + 3 \\right)}",
    "2 \\neq 3",
    "2 e^{2 x - 1}",
    "2 x + 2 y(dy/dx) = 0",
    "2 x + 7 = 3",
    "2 x - 6 = 0",
    "2 x \\cos{\\left(x^{2} \\right)}",
    "2 x e^{x^{2}}",
    "2(x^{3} - 2 x)^{1} \\cdot (3 x^{2} - 2)",
    "2/(x^2 + 1)",
    "2/(x^4 + 2x^2 + 1)",
    "2/3",
    "2/5",
    "20",
    "20 - \\frac{1}{2}",
    "20)",
    "20x^3",
    "21 x^{2}",
    "21x^2 - 4x + 1",
    "21x^3 - 4x^2 + x",
    "22/3",
    "2250x^2",
    "24",
    "243x^5/5",
    "24\\pi",
    "24x",
    "25",
    "25/3",
    "27",
    "27\\pi",
    "27x^4/4 - 36x^3 + 72x^2 - 64x + C",
    "28/3",
    "2\\pi \\cdot \\dfrac{64}{5}",
    "2\\pi \\int_{0}^{1} x \\cdot x^{3} \\, dx",
    "2\\pi \\int_{0}^{1} x^{4} \\, dx",
    "2\\pi \\int_{0}^{2} x \\cdot f(x) \\, dx",
    "2\\pi \\int_{0}^{2} x \\cdot x^{2} \\, dx",
    "2\\pi \\int_{0}^{2} x^{3} \\, dx",
    "2\\pi \\int_{0}^{3} x \\cdot x \\, dx",
    "2\\pi \\int_{0}^{3} x^{2} \\, dx",
    "2\\pi \\int_{0}^{4} x \\cdot \\sqrt{x} \\, dx",
    "2\\pi \\int_{0}^{4} x^{3/2} \\, dx",
    "2\\pi \\left[9 - 0\\right]",
    "2\\pi \\left[F(1)-F(0)\\right]",
    "2\\pi \\left[F(2)-F(0)\\right]",
    "2\\pi \\left[F(3)-F(0)\\right]",
    "2\\pi \\left[F(4)-F(0)\\right]",
    "2\\pi \\left[\\dfrac{16}{4} - 0\\right]",
    "2\\pi \\left[\\dfrac{1}{5} - 0\\right]",
    "2\\pi \\left[\\dfrac{2}{5}(32) - 0\\right]",
    "2\\pi(4)",
    "2\\pi/3",
    "2\\pi/5",
    "2^{2} + 2 \\cdot 2 + 4 = 12",
    "2e^{2x - 1}",
    "2e^{2x}",
    "2ln|2x+1| + C",
    "2t - 4 = 0 \\Rightarrow t = 2",
    "2x",
    "2x + 7 + C",
    "2x + h",
    "2x \\cos(x)",
    "2x \\cos(x^2)",
    "2x \\sin(x)",
    "2x/(x - 2)",
    "2x/(x^2 + 2x + 1) + 1/(x^2 + 2x + 1)",
    "2x/(x^4 + 2x^2 + 1)",
    "2x^2 + 14x + C",
    "2x^2 + 2x",
    "2x^3 + C",
    "2x^3 - 4x",
    "2x^4 - 2x^2 + C",
    "2x^5/5 + 10x^3/3 + C",
    "2x^6 - 6x + C",
    "2x^7 + 5",
    "2xh + h^{2} + 2h",
    "2xh + h^{2} - 3h",
    "2y = x+1",
    "3",
    "3 + 3 = 6",
    "3 \\cdot -\\cos(x)",
    "3 \\cdot 2^{2} - 5 \\cdot 2 + 7",
    "3 \\cdot 4 x^{3}",
    "3 \\cdot \\cos(x)",
    "3 \\cdot \\dfrac{x^{3}}{3}",
    "3 \\cos(3x - 1)",
    "3 \\cos(x)",
    "3 \\cos(x) + C",
    "3 \\cos{\\left(3 x - 1 \\right)}",
    "3 \\left(x - 1\\right) \\left(x + 1\\right)",
    "3 \\log(2)/2",
    "3 \\sin(2x + 1)/2 + C",
    "3 \\sin(x)",
    "3 x - 4 = 5",
    "3 x^{2} + 3 y^{2}(dy/dx) = 0",
    "3 x^{2} - 12 = 0",
    "3 x^{2} - 3 = 0",
    "3(1)+1",
    "3(2)^{2} - 12(2) + 9",
    "3(x^{2} + 1)^{2} \\cdot (2 x)",
    "3/2",
    "3/4",
    "3/5",
    "30x^4",
    "30x^4 + C",
    "32/3",
    "324x^3 + 1620x^2 + 2700x + 1500 + C",
    "32\\pi/5",
    "32x^3 - 240x^2 + 600x - 500",
    "33",
    "35/3",
    "36 x^{3}",
    "36x^2",
    "38",
    "39/2",
    "3A \\Rightarrow A",
    "3x",
    "3x + y = -3",
    "3x+1 = A(x+2) + B(x-1)",
    "3x^2",
    "3x^2 + 2x",
    "3x^2 + C",
    "3x^2/(x^2 - 4x + 4) - 4x/(x^2 - 4x + 4)",
    "3x^2/(x^3 - 2)",
    "3x^4",
    "3x^4 + 6x^2 + 3",
    "3y = -(x+1)",
    "4",
    "4 \\cdot 1",
    "4 \\cdot \\dfrac{\\sin(4x)}{4x}",
    "4 \\cdot \\dfrac{x^{4}}{4}",
    "4 \\left(-1\\right)",
    "4 x",
    "4 x - 3 = 9",
    "4(2 x - 5)^{3} \\cdot (2)",
    "4)",
    "4.5",
    "4/3",
    "4/5",
    "405x^4",
    "41/2",
    "42x - 4",
    "450 x^{3}",
    "450x^3",
    "48",
    "4800x^2",
    "4\\pi",
    "4e^x",
    "4e^{2x}",
    "4e^{4x}",
    "4x^3 + 10x + C",
    "4x^3 - 2x + C",
    "4x^3 - 6x",
    "5",
    "5 = A(5) \\Rightarrow A=1",
    "5 = A(x+3) + B(x-2)",
    "5 = B(-5) \\Rightarrow B=-1",
    "5 \\cdot 3 - 7",
    "5 \\cdot \\dfrac{x^{3}}{3}",
    "5 \\cos(5x) + C",
    "5 x + 1 = 11",
    "5/(5x - 1)",
    "5/3",
    "5/4",
    "50",
    "5000",
    "55/2",
    "56",
    "5]",
    "5e^{5x} + C",
    "5x^4",
    "5x^5",
    "6",
    "6 - 0",
    "6 - x = 2",
    "6 - x and y",
    "6 \\cdot \\dfrac{x^{6}}{6}",
    "6 x",
    "6 x^{2} - 6 x - 12 = 0",
    "6 x^{5} + 12 x^{3} + 6 x",
    "6 x^{5} - 16 x^{3} + 8 x",
    "625 x",
    "625x",
    "63",
    "64 x",
    "64 x^{3} - 480 x^{2} + 1200 x - 1000",
    "64/3",
    "64\\pi/3",
    "64x^3 - 480x^2 + 1200x - 1000",
    "65/2",
    "6\\pi",
    "6x",
    "6x + C",
    "6x/(3x^2 + 5)",
    "6x^2/(x^4 + 2x^2 + 1)",
    "6x^5 + 12x^3 + 6x",
    "6x^5 - 16x^3 + 8x",
    "6x^5 - 3 + C",
    "6x^5 - 4",
    "6x^6 - 4x",
    "6x^7 + 18x^5 + 18x^3 + 6x",
    "6x^8 - 28x^6 + 40x^4 - 16x^2",
    "7",
    "7 \\cdot 3 x^{2}",
    "72 x^{2}",
    "750 x^{2}",
    "750x^2",
    "7x^3 - 2x^2 + x",
    "8",
    "8 \\pi",
    "8/3",
    "8000x",
    "81",
    "81x^5/5",
    "84x^5",
    "8\\pi",
    "8x^3",
    "9",
    "9 - x^{2} \\geq 0",
    "9\\pi",
    "9x^4 - 12x^2 + 4",
    "=",
    "= 0",
    "= 0)",
    "= 10",
    "=10",
    "=7",
    "A",
    "A = -1, B = 1",
    "A = 1, B = -1",
    "A = 1, B = 1",
    "A = 5, B = -5",
    "A(0) + B(-2) \\Rightarrow B",
    "A(2) + B(0) \\Rightarrow A",
    "A(3) \\Rightarrow 4",
    "B",
    "C",
    "F(1) - F(-1)",
    "F(1) - F(0)",
    "F(2) - F(-1)",
    "F(2) - F(-2)",
    "F(2) - F(-3)",
    "F(2) - F(0)",
    "F(3) - F(-2)",
    "F(3) - F(0)",
    "F(4) - F(0)",
    "F(4) - F(1)",
    "F(\\frac{\\pi}{2}) - F(0)",
    "F(x)",
    "F(x) = - \\frac{x^{3}}{3} + 4 x",
    "F(x) = 4 x",
    "F(x) = \\dfrac{2}{5}x^{5/2}",
    "F(x) = \\dfrac{x^{3}}{3}",
    "F(x) = \\dfrac{x^{4}}{4}",
    "F(x) = \\dfrac{x^{5}}{5}",
    "F(x) = \\frac{3 x^{2}}{2}",
    "F(x) = \\frac{3 x^{2}}{2} - x",
    "F(x) = \\frac{x^{2}}{2}",
    "F(x) = \\frac{x^{3}}{3}",
    "F(x) = \\frac{x^{3}}{3} - 2 x^{2} + 3 x",
    "F(x) = \\frac{x^{4}}{4}",
    "F(x) = \\frac{x^{5}}{5}",
    "F(x) = x^{2} + x",
    "V",
    "[0,5]",
    "[2, 3)",
    "[3, 4)",
    "[x]",
    "[x] (the largest integer <= x) is discontinuous at every integer",
    "\\cos x - 1",
    "\\cos(2 x + 3) \\cdot (2)",
    "\\cos(2x + 3)",
    "\\cos(2x)",
    "\\cos(3 x - 1) \\cdot (3)",
    "\\cos(3x - 1)",
    "\\cos(5x)/5 + C",
    "\\cos(u) \\cdot u'",
    "\\cos(x)",
    "\\cos(x) + 1",
    "\\cos(x) + C",
    "\\cos(x)/x",
    "\\cos(x)^2",
    "\\cos(x)^{-2}",
    "\\cos(x^2)",
    "\\cos(x^{2}) \\cdot (2 x)",
    "\\cos{\\left(0 \\right)}",
    "\\cos{\\left(2 x \\right)}",
    "\\cos{\\left(x \\right)}",
    "\\cos{\\left(x \\right)} \\, dx",
    "\\cot(x) + C",
    "\\dfrac{(1)(x + 1) - (x)(1)}{(x + 1)^2}",
    "\\dfrac{(2 x)(x - 2) - (x^{2})(1)}{(x - 2)^2}",
    "\\dfrac{(2)(x^{2} + 1) - (2 x + 1)(2 x)}{(x^{2} + 1)^2}",
    "\\dfrac{(\\cos{\\left(x \\right)})(x) - (\\sin{\\left(x \\right)})(1)}{(x)^2}",
    "\\dfrac{- 2 x^{2} - 2 x + 2}{x^{4} + 2 x^{2} + 1}",
    "\\dfrac{- \\sin{\\left(x \\right)}}{\\cos{\\left(x \\right)}}",
    "\\dfrac{-1}{x(x+h)}",
    "\\dfrac{-h}{h \\cdot x(x+h)}",
    "\\dfrac{1 - 1/x}{1 + 2/x} \\to \\dfrac{1}{1}",
    "\\dfrac{10}{5}",
    "\\dfrac{128\\pi}{5}",
    "\\dfrac{1}{(x-3)^{2}}",
    "\\dfrac{1}{-3} \\cdot \\dfrac{u^{4}}{4} + C",
    "\\dfrac{1}{-3} \\int u^{3} \\, du",
    "\\dfrac{1}{2}",
    "\\dfrac{1}{2} \\int \\cos(u) \\, du",
    "\\dfrac{1}{2} \\sin(u) + C",
    "\\dfrac{1}{3} \\cdot \\dfrac{u^{5}}{5} + C",
    "\\dfrac{1}{3} \\int u^{4} \\, du",
    "\\dfrac{1}{5} \\int e^u \\, du",
    "\\dfrac{1}{5} e^u + C",
    "\\dfrac{1}{5} e^{5 x} + C",
    "\\dfrac{1}{h} \\cdot \\dfrac{x - (x+h)}{x(x+h)}",
    "\\dfrac{1}{h}\\left(\\dfrac{1}{x+h} - \\dfrac{1}{x}\\right)",
    "\\dfrac{1}{x-2}",
    "\\dfrac{1}{x^{2} + 2 x + 1}",
    "\\dfrac{1}{x^{2}}",
    "\\dfrac{1}{x^{4}} \\to \\infty",
    "\\dfrac{1}{x} \\to -\\infty",
    "\\dfrac{1}{x} \\to \\infty",
    "\\dfrac{2 + \\frac{3}{x}}{5 - \\frac{1}{x} + \\frac{1}{x^{2}}}",
    "\\dfrac{2\\pi}{5}",
    "\\dfrac{2xh + h^2}{h}",
    "\\dfrac{3 + 1/x}{1 - 5/x} \\to \\dfrac{3}{1}",
    "\\dfrac{3 + \\frac{1}{x}}{6 + \\frac{5}{x}}",
    "\\dfrac{3 x + 1}{6 x + 5}",
    "\\dfrac{3 x^{2}}{x^{3} - 2}",
    "\\dfrac{3h}{h}",
    "\\dfrac{4 - \\frac{1}{x^{2}}}{2 + \\frac{7}{x^{3}}}",
    "\\dfrac{4}{3}",
    "\\dfrac{5}{5 x - 1}",
    "\\dfrac{6 x}{3 x^{2} + 5}",
    "\\dfrac{8+2}{5}",
    "\\dfrac{\\frac{1}{x} + \\frac{1}{x^{3}}}{1 + \\frac{2}{x^{3}}}",
    "\\dfrac{\\frac{1}{x} + \\frac{3}{x^{2}}}{1 - \\frac{4}{x^{2}}}",
    "\\dfrac{\\left(x - 1\\right) \\left(x + 1\\right)}{x - 1}",
    "\\dfrac{\\left(x - 2\\right) \\left(x + 2\\right)}{x - 2}",
    "\\dfrac{\\left(x - 2\\right) \\left(x + 3\\right)}{x - 2}",
    "\\dfrac{\\left(x - 2\\right) \\left(x^{2} + 2 x + 4\\right)}{x - 2}",
    "\\dfrac{\\left(x - 3\\right) \\left(x + 3\\right)}{x - 3}",
    "\\dfrac{\\left(x - 3\\right) \\left(x - 2\\right)}{x - 2}",
    "\\dfrac{\\sin(3x)}{5x}",
    "\\dfrac{\\sin(4x)}{x}",
    "\\dfrac{d}{dx}[-2 \\cdot x^{2}]",
    "\\dfrac{d}{dx}[-3 \\cdot x^{1}]",
    "\\dfrac{d}{dx}[-4 \\cdot x^{1}]",
    "\\dfrac{d}{dx}[1 - \\cos{\\left(x \\right)}]",
    "\\dfrac{d}{dx}[2 \\cdot x^{7}]",
    "\\dfrac{d}{dx}[3 \\cdot \\sin(x)]",
    "\\dfrac{d}{dx}[3 \\cdot x^{4}]",
    "\\dfrac{d}{dx}[7 \\cdot x^{3}]",
    "\\dfrac{d}{dx}[\\arccos(x)]",
    "\\dfrac{d}{dx}[\\arcsin(x)]",
    "\\dfrac{d}{dx}[\\arctan(x)]",
    "\\dfrac{d}{dx}[\\cos(x)] = -\\sin(x)",
    "\\dfrac{d}{dx}[\\frac{1}{2} \\cdot x^{2}]",
    "\\dfrac{d}{dx}[\\ln(u)]",
    "\\dfrac{d}{dx}[\\ln(u)] = \\dfrac{u'}{u}",
    "\\dfrac{d}{dx}[\\sin(u)]",
    "\\dfrac{d}{dx}[\\sin(x)] = \\cos(x)",
    "\\dfrac{d}{dx}[\\sin{\\left(x \\right)}]",
    "\\dfrac{d}{dx}[\\tan{\\left(x \\right)}]",
    "\\dfrac{d}{dx}[e^u]",
    "\\dfrac{d}{dx}[e^u] = e^u \\cdot u'",
    "\\dfrac{d}{dx}[u^{2}] = 2 u^{1} \\cdot u'",
    "\\dfrac{d}{dx}[u^{3}] = 3 u^{2} \\cdot u'",
    "\\dfrac{d}{dx}[u^{4}] = 4 u^{3} \\cdot u'",
    "\\dfrac{d}{dx}[x - 1] = 1",
    "\\dfrac{d}{dx}[x - 2] = 1",
    "\\dfrac{d}{dx}[x] = 1",
    "\\dfrac{d}{dx}[x^{1}] = 1 x^{0} = 1",
    "\\dfrac{d}{dx}[x^{2} - 1] = 2 x",
    "\\dfrac{d}{dx}[x^{2} - 4] = 2 x",
    "\\dfrac{d}{dx}[x^{2}] = 2 x",
    "\\dfrac{d}{dx}[x^{5}] = 5 x^{4} = 5 x^{4}",
    "\\dfrac{d}{dx}[x^{6}] = 6 x^{5} = 6 x^{5}",
    "\\dfrac{f(x+h) - f(x)}{h}",
    "\\dfrac{f(x+h)-f(x)}{h}",
    "\\dfrac{f(x+h)-f(x)}{h} = 2x + h + 2",
    "\\dfrac{f(x+h)-f(x)}{h} = 2x + h - 3",
    "\\dfrac{u'v - uv'}{v^2}",
    "\\dfrac{u'}{u}",
    "\\dfrac{x + 3}{x^{2} - 4}",
    "\\dfrac{x \\cos{\\left(x \\right)} - \\sin{\\left(x \\right)}}{x^{2}}",
    "\\dfrac{x \\left(2 x + 3\\right)}{5 x^{2} - x + 1}",
    "\\dfrac{x \\left(4 x^{2} - 1\\right)}{2 x^{3} + 7}",
    "\\dfrac{x-3}{|x-3|} = 1",
    "\\dfrac{x^{2} + 1}{x^{3} + 2}",
    "\\dfrac{x^{2} + x - 6}{x - 2}",
    "\\dfrac{x^{2} - 1}{x - 1}",
    "\\dfrac{x^{2} - 4 x}{x^{2} - 4 x + 4}",
    "\\dfrac{x^{2} - 4}{x - 2}",
    "\\dfrac{x^{2} - 5 x + 6}{x - 2}",
    "\\dfrac{x^{2} - 9}{x - 3}",
    "\\dfrac{x^{3} - 8}{x - 2}",
    "\\dfrac{|x|}{x} = \\dfrac{-x}{x} = -1",
    "\\dfrac{|x|}{x} = \\dfrac{x}{x} = 1",
    "\\frac{0}{0}",
    "\\frac{1 \\left(24 + 3 \\cdot 1 - 2 \\cdot 1^{2}\\right)}{6}",
    "\\frac{11}{3}",
    "\\frac{11}{3} - - \\frac{11}{3}",
    "\\frac{11}{3})",
    "\\frac{125}{6}",
    "\\frac{15}{4}",
    "\\frac{15}{4} - 0",
    "\\frac{1^{2} - 1}{1 + 3}",
    "\\frac{1}{2}",
    "\\frac{1}{2} \\cdot 2 x^{1}",
    "\\frac{1}{2})",
    "\\frac{1}{3}",
    "\\frac{1}{3} - 0",
    "\\frac{1}{4}",
    "\\frac{1}{4} - 0",
    "\\frac{1}{\\sqrt{1 - x^{2}}}",
    "\\frac{1}{x^{2} + 1}",
    "\\frac{2 \\cdot 2}{2^{2} + 1}",
    "\\frac{2 \\cdot 4 + 3}{4 - 1}",
    "\\frac{2 \\left(12 - 2^{2}\\right)}{3}",
    "\\frac{2 \\left(36 - 3 \\cdot 2 - 2 \\cdot 2^{2}\\right)}{6}",
    "\\frac{22}{3}",
    "\\frac{2^{3}}{3} - (\\frac{0^{3}}{3})",
    "\\frac{2^{4}}{4} - (\\frac{0^{4}}{4})",
    "\\frac{2}{5}",
    "\\frac{3 \\cdot 4^{2}}{2}",
    "\\frac{3 \\left(36 + 3 \\cdot 3 - 2 \\cdot 3^{2}\\right)}{6}",
    "\\frac{3 x^{2}}{x^{3} - 2}",
    "\\frac{3 x^{4}}{2}",
    "\\frac{32}{3}",
    "\\frac{39}{2}",
    "\\frac{3}{5}",
    "\\frac{3}{5} \\cdot 1",
    "\\frac{3}{5} \\cdot \\dfrac{\\sin(3x)}{3x}",
    "\\frac{4}{5}",
    "\\frac{5}{5 x - 1}",
    "\\frac{6 x}{3 x^{2} + 5}",
    "\\frac{64 \\pi}{3}",
    "\\frac{81 x^{5}}{5}",
    "\\frac{8}{3}",
    "\\frac{8}{3} - 0",
    "\\frac{\\left(-2\\right) \\left(2 + -2\\right)}{-2 + 5}",
    "\\frac{\\log{\\left(x^{2} + 4 \\right)}}{2}",
    "\\frac{\\pi}{5}",
    "\\frac{\\sin^{3}{\\left(x \\right)}}{3}",
    "\\frac{\\sin{\\left(0 \\right)}}{2 \\cdot 0}",
    "\\frac{\\sin{\\left(2 x + 1 \\right)}}{2}",
    "\\frac{\\sin{\\left(x \\right)}}{\\cos{\\left(x \\right)}}",
    "\\frac{x^{2} - 25}{x - 5} = x + 5",
    "\\frac{x^{2}}{2}",
    "\\frac{x^{5}}{5} + \\frac{5 x^{3}}{3} + C",
    "\\frac{x^{8}}{4}",
    "\\infty",
    "\\int",
    "\\int (3x + 5)^4 \\, dx",
    "\\int (4 - 3x)^3 \\, dx",
    "\\int -2 \\cdot x^{1} \\, dx",
    "\\int -3 \\, dx = -3x",
    "\\int 1/x \\, dx",
    "\\int 2 \\cdot x^{1} \\, dx",
    "\\int 2/(2x+1) \\, dx",
    "\\int 2x + 7 \\, dx",
    "\\int 3 \\cdot \\sin(x) \\, dx",
    "\\int 3 \\cdot x^{2} \\, dx",
    "\\int 3 \\sin(x) \\, dx",
    "\\int 3x^2 \\, dx",
    "\\int 4 \\cdot x^{3} \\, dx",
    "\\int 4x^3 - 2x \\, dx",
    "\\int 5 \\cdot x^{2} \\, dx",
    "\\int 6 \\cdot x^{5} \\, dx",
    "\\int 6x^5 - 3 \\, dx",
    "\\int 7 \\, dx = 7x",
    "\\int \\cos(2 x + 1) \\, dx",
    "\\int \\cos(2x + 1) \\, dx",
    "\\int \\cos(x) \\, dx",
    "\\int \\cos(x) \\, dx = \\sin(x)",
    "\\int \\dfrac{1}{u} \\, du",
    "\\int \\dfrac{1}{x} \\, dx",
    "\\int \\dfrac{2}{2 x + 1} \\, dx",
    "\\int \\left(3 x + 5\\right)^{4} \\, dx",
    "\\int \\left(4 - 3 x\\right)^{3} \\, dx",
    "\\int \\sec(x)^2 \\, dx",
    "\\int \\sec^2(x) \\, dx = \\tan(x)",
    "\\int \\sin(5x) \\, dx",
    "\\int \\sin(x) \\, dx",
    "\\int \\sin(x) \\, dx = -\\cos(x)",
    "\\int \\sin{\\left(5 x \\right)} \\, dx",
    "\\int \\sin{\\left(x \\right)} \\, dx",
    "\\int \\tan(x) \\, dx",
    "\\int \\tan(x) \\, dx = -\\ln|\\cos(x)| + C",
    "\\int e^{5 x} \\, dx",
    "\\int e^{5x} \\, dx",
    "\\int f(x) \\, dx",
    "\\int f(x) \\, dx = x^{2} + 7 x + C",
    "\\int f(x) \\, dx = x^{3} + C",
    "\\int f(x) \\, dx = x^{4} - x^{2} + C",
    "\\int f(x) \\, dx = x^{6} - 3 x + C",
    "\\int u \\, dv = uv - \\int v \\, du",
    "\\int x \\, e^{x} \\, dx",
    "\\int x \\cos(x) \\, dx",
    "\\int x \\cos{\\left(x \\right)} \\, dx",
    "\\int x \\sin(x) \\, dx",
    "\\int x \\sin{\\left(x \\right)} \\, dx",
    "\\int x e^{x} \\, dx",
    "\\int x^4 + 5x^2 \\, dx",
    "\\int x^n \\, dx = \\dfrac{x^{n+1}}{n+1}",
    "\\int x^{4} \\, dx = \\dfrac{x^{5}}{5}",
    "\\int xe^{x} \\, dx",
    "\\int_{-1}^{1} - x^{2} + x + 4 \\, dx",
    "\\int_{-1}^{1} 4 - x^2 \\, dx",
    "\\int_{-1}^{1} 4 - x^{2} \\, dx",
    "\\int_{-1}^{1} [(x + 3) - (x^{2} - 1)] \\, dx",
    "\\int_{-1}^{2} 2 x + 1 \\, dx",
    "\\int_{-1}^{2} 2x + 1 \\, dx",
    "\\int_{-2}^{2} 4 - x^{2} \\, dx",
    "\\int_{-2}^{3} - x^{2} + x + 6 \\, dx",
    "\\int_{-2}^{3} [(x + 5) - (x^{2} - 1)] \\, dx",
    "\\int_{-3}^{2} - x^{2} - x + 6 \\, dx",
    "\\int_{-3}^{2} [(6 - x) - (x^{2})] \\, dx",
    "\\int_{0}^{1} 2x(x^2 + 1)^3 \\, dx",
    "\\int_{0}^{1} x \\cdot e^x \\, dx",
    "\\int_{0}^{1} x^3 \\, dx",
    "\\int_{0}^{1} x^{3} \\, dx",
    "\\int_{0}^{2} x/(x^2 + 4) \\, dx",
    "\\int_{0}^{2} x^2 \\, dx",
    "\\int_{0}^{2} x^{2} \\, dx",
    "\\int_{0}^{2} x^{3} \\, dx",
    "\\int_{0}^{3} x^2 - 4x + 3 \\, dx",
    "\\int_{0}^{3} x^{2} - 4 x + 3 \\, dx",
    "\\int_{0}^{4} 3 x \\, dx",
    "\\int_{0}^{pi/2} \\sin(x)^2 \\cos(x) \\, dx",
    "\\int_{1}^{4} 3 x - 1 \\, dx",
    "\\int_{1}^{4} 3x - 1 \\, dx",
    "\\left(-1, 1\\right)",
    "\\left(-1\\right)^{3}",
    "\\left(-5, \\infty\\right)",
    "\\left(-\\infty, - \\frac{\\sqrt{3}}{3}\\right) \\cup \\left(\\frac{\\sqrt{3}}{3}, \\infty\\right)",
    "\\left(-\\infty, -2\\right) \\cup \\left(-2, 2\\right) \\cup \\left(2, \\infty\\right)",
    "\\left(-\\infty, 3\\right) \\cup \\left(3, \\infty\\right)",
    "\\left(2, \\infty\\right)",
    "\\left(x - 1\\right) e^{x} + C",
    "\\left[-1, 4\\right) \\cup \\left(4, \\infty\\right)",
    "\\left[-1, \\infty\\right)",
    "\\left[-3, 3\\right]",
    "\\left[2, \\infty\\right)",
    "\\lim_{h \\to 0} \\dfrac{f(x+h) - f(x)}{h}",
    "\\lim_{x \\to -1} [x^3 - 4x + 1]",
    "\\lim_{x \\to -1} x^{3} - 4 x + 1",
    "\\lim_{x \\to -2} [(x^2 + 2x)/(x + 5)]",
    "\\lim_{x \\to -2} \\frac{x^{2} + 2 x}{x + 5}",
    "\\lim_{x \\to 0^+} [|x|/x]",
    "\\lim_{x \\to 0^+} \\dfrac{|x|}{x} = 1",
    "\\lim_{x \\to 0^-} [|x|/x]",
    "\\lim_{x \\to 0^-} \\dfrac{|x|}{x} = -1",
    "\\lim_{x \\to 0} [(1 - \\cos(x))/x^2]",
    "\\lim_{x \\to 0} [(1-cos x)/x]",
    "\\lim_{x \\to 0} [-1/x^4]",
    "\\lim_{x \\to 0} [1/x^2]",
    "\\lim_{x \\to 0} [\\sin(3x)/(5x)]",
    "\\lim_{x \\to 0} [\\sin(4x)/x]",
    "\\lim_{x \\to 0} [\\sin(x)/x]",
    "\\lim_{x \\to 0} [x \\cdot \\sin(1/x)]",
    "\\lim_{x \\to 0} \\dfrac{1 - \\cos(x)}{x}",
    "\\lim_{x \\to 0} \\dfrac{1}{x^{2}} = \\infty",
    "\\lim_{x \\to 0} \\dfrac{\\cos(x) - 1}{x}",
    "\\lim_{x \\to 0} \\dfrac{\\cos{\\left(x \\right)}}{1}",
    "\\lim_{x \\to 0} \\dfrac{\\sin(3x)}{5x}",
    "\\lim_{x \\to 0} \\dfrac{\\sin(4x)}{x}",
    "\\lim_{x \\to 0} \\dfrac{\\sin(kx)}{kx} = 1",
    "\\lim_{x \\to 0} \\dfrac{\\sin{\\left(x \\right)}}{2 x}",
    "\\lim_{x \\to 0} \\frac{1 - \\cos{\\left(x \\right)}}{x^{2}}",
    "\\lim_{x \\to 0} \\frac{1 - \\cos{\\left(x \\right)}}{x}",
    "\\lim_{x \\to 0} \\frac{\\sin{\\left(x \\right)}}{x}",
    "\\lim_{x \\to 0} \\left(-\\dfrac{1}{x^{4}}\\right)",
    "\\lim_{x \\to 0} x\\sin(1/x) = 0",
    "\\lim_{x \\to 1^+} (4-x) = 4 - 1 = 3",
    "\\lim_{x \\to 1^+} [f(x)]",
    "\\lim_{x \\to 1^+} f(x)",
    "\\lim_{x \\to 1^+}(4-x)",
    "\\lim_{x \\to 1^-} (x+1) = 1 + 1 = 2",
    "\\lim_{x \\to 1^-} [f(x)]",
    "\\lim_{x \\to 1^-} f(x)",
    "\\lim_{x \\to 1^-}(x+1)",
    "\\lim_{x \\to 1} [(x^2 - 1)/(x + 3)]",
    "\\lim_{x \\to 1} [(x^2 - 1)/(x - 1)]",
    "\\lim_{x \\to 1} \\dfrac{2 x}{1}",
    "\\lim_{x \\to 1} \\frac{x^{2} - 1}{x + 3}",
    "\\lim_{x \\to 1} \\frac{x^{2} - 1}{x - 1}",
    "\\lim_{x \\to 1} f(x)",
    "\\lim_{x \\to 2^+} [1/(x-2)]",
    "\\lim_{x \\to 2^+} [x] = 2",
    "\\lim_{x \\to 2^+} \\dfrac{1}{x-2} = \\infty",
    "\\lim_{x \\to 2^+} f(x) = 2^{2} - 1 = 3",
    "\\lim_{x \\to 2^-} [1/(x-2)]",
    "\\lim_{x \\to 2^-} [x] = 1",
    "\\lim_{x \\to 2^-} \\dfrac{1}{x-2}",
    "\\lim_{x \\to 2^-} f(x) = 3 - 2 = 1",
    "\\lim_{x \\to 2} 3 x^{2} - 5 x + 7",
    "\\lim_{x \\to 2} [(x^2 + x - 6)/(x - 2)]",
    "\\lim_{x \\to 2} [(x^2 - 4)/(x - 2)]",
    "\\lim_{x \\to 2} [(x^2 - 5x + 6)/(x - 2)]",
    "\\lim_{x \\to 2} [(x^3 - 8)/(x - 2)]",
    "\\lim_{x \\to 2} [3x^2 - 5x + 7]",
    "\\lim_{x \\to 2} \\dfrac{(x-2)(x+2)}{x-2}",
    "\\lim_{x \\to 2} \\dfrac{2 x}{1}",
    "\\lim_{x \\to 2} \\dfrac{x^{2}-4}{x-2}",
    "\\lim_{x \\to 2} \\frac{x^{2} - 4}{x - 2}",
    "\\lim_{x \\to 2}(x+2)",
    "\\lim_{x \\to 2⁺}",
    "\\lim_{x \\to 2⁻}",
    "\\lim_{x \\to 3^+} [(x-3)/|x-3|]",
    "\\lim_{x \\to 3^+} [x] = 3",
    "\\lim_{x \\to 3^+} \\dfrac{x-3}{|x-3|} = 1",
    "\\lim_{x \\to 3^-} [x] = 2",
    "\\lim_{x \\to 3} 5 x - 7",
    "\\lim_{x \\to 3} [(x^2 - 9)/(x - 3)]",
    "\\lim_{x \\to 3} [1/(x-3)^2]",
    "\\lim_{x \\to 3} [5x - 7]",
    "\\lim_{x \\to 3} \\dfrac{1}{(x-3)^{2}}",
    "\\lim_{x \\to 3} \\dfrac{x^{2}-9}{x-3}",
    "\\lim_{x \\to 3}(x+3)",
    "\\lim_{x \\to 3⁺}",
    "\\lim_{x \\to 3⁻}",
    "\\lim_{x \\to 4} [(2x + 3)/(x - 1)]",
    "\\lim_{x \\to 4} \\frac{2 x + 3}{x - 1}",
    "\\lim_{x \\to 5} f(x) = 5 + 5 = 10",
    "\\lim_{x \\to \\infty} [(2x^2 + 3x)/(5x^2 - x + 1)]",
    "\\lim_{x \\to \\infty} [(3x + 1)/(6x + 5)]",
    "\\lim_{x \\to \\infty} [(4x^3 - x)/(2x^3 + 7)]",
    "\\lim_{x \\to \\infty} [(x + 3)/(x^2 - 4)]",
    "\\lim_{x \\to \\infty} [(x^2 + 1)/(x^3 + 2)]",
    "\\lim_{x \\to \\infty} \\dfrac{2x^{2}+1}{x^{2}-4}",
    "\\lim_{x \\to \\infty} \\dfrac{x-1}{x+2}",
    "\\lim_{x \\to \\infty} \\frac{2 x^{2} + 3 x}{5 x^{2} - x + 1}",
    "\\lim_{x \\to \\infty} \\frac{3 x + 1}{6 x + 5}",
    "\\lim_{x \\to \\infty} \\frac{4 x^{3} - x}{2 x^{3} + 7}",
    "\\lim_{x \\to \\infty} \\frac{x + 3}{x^{2} - 4}",
    "\\lim_{x \\to \\infty} \\frac{x^{2} + 1}{x^{3} + 2}",
    "\\ln(2)",
    "\\ln(2)/2",
    "\\ln|2 x + 1| + C",
    "\\ln|\\cos(x)|^{-1}",
    "\\ln|\\sec(x)|",
    "\\ln|\\sec(x)| + C",
    "\\ln|u| + C",
    "\\ln|x| + C",
    "\\log{\\left(2 \\right)}",
    "\\log{\\left(2 \\sqrt{2} \\right)}",
    "\\log{\\left(\\sqrt{2} \\right)}",
    "\\pi \\int_{0}^{1} [x^{2}]^2 \\, dx",
    "\\pi \\int_{0}^{1} x^{4} \\, dx",
    "\\pi \\int_{0}^{3} 4 \\, dx",
    "\\pi \\int_{0}^{3} [2]^2 \\, dx",
    "\\pi \\int_{0}^{4} [\\sqrt{x}]^2 \\, dx",
    "\\pi \\int_{0}^{4} [x]^2 \\, dx",
    "\\pi \\int_{0}^{4} x \\, dx",
    "\\pi \\int_{0}^{4} x^{2} \\, dx",
    "\\pi \\left[4 \\cdot 3 - \\left(4 \\cdot 0\\right)\\right]",
    "\\pi \\left[F(1) - F(0)\\right]",
    "\\pi \\left[F(3) - F(0)\\right]",
    "\\pi \\left[F(4) - F(0)\\right]",
    "\\pi \\left[\\frac{1^{5}}{5} - \\left(\\frac{0^{5}}{5}\\right)\\right]",
    "\\pi \\left[\\frac{4^{2}}{2} - \\left(\\frac{0^{2}}{2}\\right)\\right]",
    "\\pi \\left[\\frac{4^{3}}{3} - \\left(\\frac{0^{3}}{3}\\right)\\right]",
    "\\pi/3",
    "\\pi/4",
    "\\pi/5",
    "\\sec(x) + C",
    "\\sec(x)\\tan(x) + C",
    "\\sin(2)",
    "\\sin(2x + 1)/2 + C",
    "\\sin(2x)",
    "\\sin(3)",
    "\\sin(x)",
    "\\sin(x) + C",
    "\\sin(x) + \\cos(x)",
    "\\sin(x) - \\cos(x)",
    "\\sin{\\left(x \\right)}",
    "\\sin{\\left(x \\right)} + C",
    "\\sqrt{1 - x^2}",
    "\\sqrt{3}",
    "\\sqrt{x + 5} \\neq 0",
    "\\tan(x)",
    "\\tan(x) + C",
    "\\tan(x) = \\sin(x)/\\cos(x)",
    "\\tan^{2}{\\left(x \\right)} + 1",
    "\\textrm{(1,2).}",
    "\\textrm{(3,4).}",
    "\\textrm{(3x+1)/[(x-1)(x+2)]}",
    "\\textrm{(Check:}",
    "\\textrm{(Squeeze)}",
    "\\textrm{(always}",
    "\\textrm{(and}",
    "\\textrm{(an}",
    "\\textrm{(a}",
    "\\textrm{(decreasing).}",
    "\\textrm{(division}",
    "\\textrm{(does}",
    "\\textrm{(equivalently}",
    "\\textrm{(first}",
    "\\textrm{(increasing);}",
    "\\textrm{(infinite)}",
    "\\textrm{(just}",
    "\\textrm{(metres,}",
    "\\textrm{(redefining}",
    "\\textrm{(since}",
    "\\textrm{(so}",
    "\\textrm{(the}",
    "\\textrm{(valid}",
    "\\textrm{(v}",
    "\\textrm{(}",
    "\\textrm{),}",
    "\\textrm{).}",
    "\\textrm{):}",
    "\\textrm{)}",
    "\\textrm{+}",
    "\\textrm{,}",
    "\\textrm{--}",
    "\\textrm{-1.}",
    "\\textrm{-1}",
    "\\textrm{-2xe\\textasciicircum{}(x\\textasciicircum{}2)}",
    "\\textrm{-2}",
    "\\textrm{-3}",
    "\\textrm{-9}",
    "\\textrm{-axis}",
    "\\textrm{-f(x)}",
    "\\textrm{-x}",
    "\\textrm{-y}",
    "\\textrm{-}",
    "\\textrm{.}",
    "\\textrm{0)?}",
    "\\textrm{0,}",
    "\\textrm{0.}",
    "\\textrm{0?}",
    "\\textrm{0}",
    "\\textrm{1)}",
    "\\textrm{1.}",
    "\\textrm{1/(x-1)\\textasciicircum{}2).}",
    "\\textrm{1/[(x-1)(x+1)]}",
    "\\textrm{1/[x(x-1)\\textasciicircum{}2]}",
    "\\textrm{16t}",
    "\\textrm{1}",
    "\\textrm{2,}",
    "\\textrm{2.}",
    "\\textrm{25,}",
    "\\textrm{2xe\\textasciicircum{}(x\\textasciicircum{}2)}",
    "\\textrm{2}",
    "\\textrm{3,}",
    "\\textrm{3.}",
    "\\textrm{3t\\textasciicircum{}2}",
    "\\textrm{3}",
    "\\textrm{4.}",
    "\\textrm{4t}",
    "\\textrm{5/[(x-2)(x+3)]}",
    "\\textrm{6t.}",
    "\\textrm{6t\\textasciicircum{}2}",
    "\\textrm{6}",
    "\\textrm{9,}",
    "\\textrm{9.}",
    "\\textrm{9t,}",
    "\\textrm{9t.}",
    "\\textrm{9}",
    "\\textrm{:}",
    "\\textrm{;}",
    "\\textrm{=}",
    "\\textrm{>=}",
    "\\textrm{A.}",
    "\\textrm{A/(x-1)}",
    "\\textrm{A/(x-2)}",
    "\\textrm{A/x}",
    "\\textrm{Acceleration}",
    "\\textrm{An}",
    "\\textrm{Approaching}",
    "\\textrm{As}",
    "\\textrm{At}",
    "\\textrm{A}",
    "\\textrm{B.}",
    "\\textrm{B/(x+1),}",
    "\\textrm{B/(x+2),}",
    "\\textrm{B/(x+3),}",
    "\\textrm{B/(x-1)}",
    "\\textrm{Between}",
    "\\textrm{Both}",
    "\\textrm{By}",
    "\\textrm{C/(x-1)\\textasciicircum{}2,}",
    "\\textrm{Chain}",
    "\\textrm{Checking}",
    "\\textrm{Classify}",
    "\\textrm{Clearing}",
    "\\textrm{Combining}",
    "\\textrm{C}",
    "\\textrm{Derivative}",
    "\\textrm{Determine}",
    "\\textrm{Differentiate}",
    "\\textrm{Differentiating}",
    "\\textrm{Direct}",
    "\\textrm{Divide}",
    "\\textrm{Dividing}",
    "\\textrm{Evaluate}",
    "\\textrm{Evaluating}",
    "\\textrm{E}",
    "\\textrm{Factor:}",
    "\\textrm{Find}",
    "\\textrm{First}",
    "\\textrm{For}",
    "\\textrm{Fundamental}",
    "\\textrm{Given}",
    "\\textrm{Hence}",
    "\\textrm{Here}",
    "\\textrm{If}",
    "\\textrm{Integrate}",
    "\\textrm{Integration}",
    "\\textrm{In}",
    "\\textrm{Just}",
    "\\textrm{L'Hopital's}",
    "\\textrm{Letting}",
    "\\textrm{Let}",
    "\\textrm{Neither}",
    "\\textrm{No}",
    "\\textrm{Parts,}",
    "\\textrm{Point-slope}",
    "\\textrm{Product}",
    "\\textrm{Quotient}",
    "\\textrm{Rearranging}",
    "\\textrm{Replace}",
    "\\textrm{Rewrite}",
    "\\textrm{Rule,}",
    "\\textrm{Rule:}",
    "\\textrm{Rule}",
    "\\textrm{R}",
    "\\textrm{Sandwich}",
    "\\textrm{Second}",
    "\\textrm{Setting}",
    "\\textrm{Set}",
    "\\textrm{Simplify:}",
    "\\textrm{Since}",
    "\\textrm{Solving}",
    "\\textrm{So}",
    "\\textrm{Substituting}",
    "\\textrm{Summing}",
    "\\textrm{Swapping}",
    "\\textrm{Test}",
    "\\textrm{Then}",
    "\\textrm{Theorem,}",
    "\\textrm{Theorem.}",
    "\\textrm{The}",
    "\\textrm{This}",
    "\\textrm{To}",
    "\\textrm{Use}",
    "\\textrm{Using}",
    "\\textrm{Velocity}",
    "\\textrm{Vertical}",
    "\\textrm{What}",
    "\\textrm{With}",
    "\\textrm{Writing}",
    "\\textrm{Yes}",
    "\\textrm{[f(x+h)}",
    "\\textrm{a:}",
    "\\textrm{about}",
    "\\textrm{above,}",
    "\\textrm{above}",
    "\\textrm{absolute}",
    "\\textrm{acceleration}",
    "\\textrm{actually}",
    "\\textrm{adding}",
    "\\textrm{again,}",
    "\\textrm{again}",
    "\\textrm{all}",
    "\\textrm{along}",
    "\\textrm{and}",
    "\\textrm{antiderivatives:}",
    "\\textrm{antiderivatives}",
    "\\textrm{antiderivative}",
    "\\textrm{any,}",
    "\\textrm{an}",
    "\\textrm{applies,}",
    "\\textrm{approaches}",
    "\\textrm{appropriate}",
    "\\textrm{area}",
    "\\textrm{are}",
    "\\textrm{asymptote.}",
    "\\textrm{asymptotes}",
    "\\textrm{asymptote}",
    "\\textrm{as}",
    "\\textrm{at}",
    "\\textrm{a}",
    "\\textrm{back}",
    "\\textrm{ball}",
    "\\textrm{below,}",
    "\\textrm{below}",
    "\\textrm{between}",
    "\\textrm{be}",
    "\\textrm{both}",
    "\\textrm{bound.}",
    "\\textrm{bounded}",
    "\\textrm{bounds}",
    "\\textrm{bound}",
    "\\textrm{branch.}",
    "\\textrm{branch:}",
    "\\textrm{but}",
    "\\textrm{by}",
    "\\textrm{cancel}",
    "\\textrm{cannot}",
    "\\textrm{can}",
    "\\textrm{chain}",
    "\\textrm{changes,}",
    "\\textrm{changes.}",
    "\\textrm{changes}",
    "\\textrm{classify}",
    "\\textrm{coefficients:}",
    "\\textrm{coefficient}",
    "\\textrm{common}",
    "\\textrm{concave}",
    "\\textrm{concavity}",
    "\\textrm{conditions,}",
    "\\textrm{confirmed}",
    "\\textrm{confirming}",
    "\\textrm{constant}",
    "\\textrm{continuous}",
    "\\textrm{critical}",
    "\\textrm{cross}",
    "\\textrm{cube}",
    "\\textrm{curve}",
    "\\textrm{decomposition}",
    "\\textrm{decreases}",
    "\\textrm{decreasing?}",
    "\\textrm{decreasing}",
    "\\textrm{defined,}",
    "\\textrm{defined}",
    "\\textrm{defining}",
    "\\textrm{definition,}",
    "\\textrm{definition}",
    "\\textrm{degree,}",
    "\\textrm{denominator,}",
    "\\textrm{denominators:}",
    "\\textrm{denominator}",
    "\\textrm{derivative}",
    "\\textrm{determined}",
    "\\textrm{determine}",
    "\\textrm{differ,}",
    "\\textrm{difference}",
    "\\textrm{differentiating}",
    "\\textrm{directly:}",
    "\\textrm{discontinuity.}",
    "\\textrm{discontinuity}",
    "\\textrm{discontinuous}",
    "\\textrm{disc}",
    "\\textrm{displacement}",
    "\\textrm{does}",
    "\\textrm{domain}",
    "\\textrm{dy/dx}",
    "\\textrm{either}",
    "\\textrm{eliminates}",
    "\\textrm{endpoints:}",
    "\\textrm{equals}",
    "\\textrm{equal}",
    "\\textrm{equation.}",
    "\\textrm{equation}",
    "\\textrm{essential}",
    "\\textrm{evaluate}",
    "\\textrm{even}",
    "\\textrm{every}",
    "\\textrm{except}",
    "\\textrm{excludes}",
    "\\textrm{exist)}",
    "\\textrm{exist.}",
    "\\textrm{exists,}",
    "\\textrm{exists.}",
    "\\textrm{exists}",
    "\\textrm{exist}",
    "\\textrm{expanding:}",
    "\\textrm{expression,}",
    "\\textrm{expression}",
    "\\textrm{f'''(x)}",
    "\\textrm{f''(x)}",
    "\\textrm{f'(x)}",
    "\\textrm{f(-x)}",
    "\\textrm{f(x).}",
    "\\textrm{f(x)]/h}",
    "\\textrm{factors}",
    "\\textrm{factor}",
    "\\textrm{fails}",
    "\\textrm{find}",
    "\\textrm{finite}",
    "\\textrm{first}",
    "\\textrm{flip}",
    "\\textrm{form.}",
    "\\textrm{form:}",
    "\\textrm{formed}",
    "\\textrm{formula}",
    "\\textrm{form}",
    "\\textrm{for}",
    "\\textrm{fraction}",
    "\\textrm{from}",
    "\\textrm{function).}",
    "\\textrm{function,}",
    "\\textrm{functions:}",
    "\\textrm{function}",
    "\\textrm{f}",
    "\\textrm{get}",
    "\\textrm{given}",
    "\\textrm{gives}",
    "\\textrm{giving}",
    "\\textrm{goes}",
    "\\textrm{graph}",
    "\\textrm{greater}",
    "\\textrm{greatest}",
    "\\textrm{grows}",
    "\\textrm{has}",
    "\\textrm{have}",
    "\\textrm{height}",
    "\\textrm{here}",
    "\\textrm{highest}",
    "\\textrm{horizontal}",
    "\\textrm{h}",
    "\\textrm{i.e.}",
    "\\textrm{identical}",
    "\\textrm{if}",
    "\\textrm{implicitly}",
    "\\textrm{inconclusive}",
    "\\textrm{increasing?}",
    "\\textrm{increasing}",
    "\\textrm{indicate}",
    "\\textrm{indicating}",
    "\\textrm{infinite}",
    "\\textrm{infinity}",
    "\\textrm{inflection.}",
    "\\textrm{inflection}",
    "\\textrm{inner}",
    "\\textrm{integer}",
    "\\textrm{integrand}",
    "\\textrm{integration:}",
    "\\textrm{integration}",
    "\\textrm{interior}",
    "\\textrm{interval}",
    "\\textrm{into}",
    "\\textrm{inverse.)}",
    "\\textrm{inverse}",
    "\\textrm{in}",
    "\\textrm{is,}",
    "\\textrm{is}",
    "\\textrm{it,}",
    "\\textrm{itself.}",
    "\\textrm{its}",
    "\\textrm{it}",
    "\\textrm{jump}",
    "\\textrm{just}",
    "\\textrm{leading}",
    "\\textrm{leaves}",
    "\\textrm{leaving}",
    "\\textrm{left-hand}",
    "\\textrm{less}",
    "\\textrm{lies}",
    "\\textrm{limit,}",
    "\\textrm{limits}",
    "\\textrm{limit}",
    "\\textrm{line's}",
    "\\textrm{line}",
    "\\textrm{make}",
    "\\textrm{matches}",
    "\\textrm{match}",
    "\\textrm{maximum.}",
    "\\textrm{maximum}",
    "\\textrm{meaning}",
    "\\textrm{method,}",
    "\\textrm{minimum.}",
    "\\textrm{minimum}",
    "\\textrm{momentarily}",
    "\\textrm{more,}",
    "\\textrm{moving}",
    "\\textrm{multiplying}",
    "\\textrm{must}",
    "\\textrm{nature}",
    "\\textrm{negative),}",
    "\\textrm{negative,}",
    "\\textrm{negative}",
    "\\textrm{neither}",
    "\\textrm{never}",
    "\\textrm{non-negative:}",
    "\\textrm{none}",
    "\\textrm{normal's}",
    "\\textrm{normal}",
    "\\textrm{not),}",
    "\\textrm{not):}",
    "\\textrm{not,}",
    "\\textrm{not}",
    "\\textrm{no}",
    "\\textrm{number),}",
    "\\textrm{number,}",
    "\\textrm{numerator,}",
    "\\textrm{numerator}",
    "\\textrm{object's}",
    "\\textrm{object}",
    "\\textrm{occur}",
    "\\textrm{odd}",
    "\\textrm{of}",
    "\\textrm{once}",
    "\\textrm{one-sided}",
    "\\textrm{one}",
    "\\textrm{only}",
    "\\textrm{on}",
    "\\textrm{origin.}",
    "\\textrm{original}",
    "\\textrm{origin}",
    "\\textrm{or}",
    "\\textrm{partial}",
    "\\textrm{particle}",
    "\\textrm{parts,}",
    "\\textrm{parts}",
    "\\textrm{patched}",
    "\\textrm{perpendicular}",
    "\\textrm{point(s)}",
    "\\textrm{point-slope}",
    "\\textrm{point.}",
    "\\textrm{points.}",
    "\\textrm{points}",
    "\\textrm{point}",
    "\\textrm{position}",
    "\\textrm{positive),}",
    "\\textrm{positive,}",
    "\\textrm{positive}",
    "\\textrm{power}",
    "\\textrm{present:}",
    "\\textrm{principles)}",
    "\\textrm{principles}",
    "\\textrm{proper}",
    "\\textrm{quotient}",
    "\\textrm{rational}",
    "\\textrm{ratio}",
    "\\textrm{reaches}",
    "\\textrm{reach}",
    "\\textrm{real}",
    "\\textrm{rearranges}",
    "\\textrm{reciprocal,}",
    "\\textrm{redefining}",
    "\\textrm{region}",
    "\\textrm{relative}",
    "\\textrm{relevant}",
    "\\textrm{removable}",
    "\\textrm{removed}",
    "\\textrm{repeated-factor}",
    "\\textrm{replaced}",
    "\\textrm{replacement,}",
    "\\textrm{replacing}",
    "\\textrm{respect}",
    "\\textrm{rest}",
    "\\textrm{revolving}",
    "\\textrm{right-hand}",
    "\\textrm{roles}",
    "\\textrm{root}",
    "\\textrm{rule.}",
    "\\textrm{rule}",
    "\\textrm{s(t)}",
    "\\textrm{same}",
    "\\textrm{satisfy}",
    "\\textrm{says}",
    "\\textrm{seconds).}",
    "\\textrm{second}",
    "\\textrm{separately:}",
    "\\textrm{shell}",
    "\\textrm{shows}",
    "\\textrm{side,}",
    "\\textrm{side.}",
    "\\textrm{sides,}",
    "\\textrm{sides}",
    "\\textrm{sign}",
    "\\textrm{simplifies}",
    "\\textrm{since}",
    "\\textrm{single}",
    "\\textrm{slightly}",
    "\\textrm{slope}",
    "\\textrm{smallest}",
    "\\textrm{small}",
    "\\textrm{solid}",
    "\\textrm{solve}",
    "\\textrm{so}",
    "\\textrm{square}",
    "\\textrm{standard}",
    "\\textrm{stays}",
    "\\textrm{steps}",
    "\\textrm{still}",
    "\\textrm{straight}",
    "\\textrm{substitute}",
    "\\textrm{substituting}",
    "\\textrm{substitution,}",
    "\\textrm{substitution}",
    "\\textrm{symmetric}",
    "\\textrm{symmetry}",
    "\\textrm{t\\textasciicircum{}2}",
    "\\textrm{t\\textasciicircum{}3}",
    "\\textrm{taking}",
    "\\textrm{tangent's}",
    "\\textrm{tangent,}",
    "\\textrm{tangent}",
    "\\textrm{tends}",
    "\\textrm{tend}",
    "\\textrm{term:}",
    "\\textrm{terms:}",
    "\\textrm{terms}",
    "\\textrm{term}",
    "\\textrm{test.}",
    "\\textrm{test}",
    "\\textrm{than}",
    "\\textrm{that}",
    "\\textrm{then}",
    "\\textrm{there),}",
    "\\textrm{there).}",
    "\\textrm{there.}",
    "\\textrm{therefore}",
    "\\textrm{there}",
    "\\textrm{these}",
    "\\textrm{the}",
    "\\textrm{third}",
    "\\textrm{this}",
    "\\textrm{though}",
    "\\textrm{through}",
    "\\textrm{thrown}",
    "\\textrm{time}",
    "\\textrm{to}",
    "\\textrm{treating}",
    "\\textrm{trigonometric}",
    "\\textrm{t}",
    "\\textrm{unchanged.}",
    "\\textrm{unchanged}",
    "\\textrm{undefined}",
    "\\textrm{under}",
    "\\textrm{unequal,}",
    "\\textrm{unequal}",
    "\\textrm{up?}",
    "\\textrm{upward}",
    "\\textrm{up}",
    "\\textrm{uses}",
    "\\textrm{use}",
    "\\textrm{using}",
    "\\textrm{v(t)}",
    "\\textrm{value,}",
    "\\textrm{values.}",
    "\\textrm{value}",
    "\\textrm{vanishes}",
    "\\textrm{velocity}",
    "\\textrm{vertical}",
    "\\textrm{volume}",
    "\\textrm{what}",
    "\\textrm{when}",
    "\\textrm{where}",
    "\\textrm{which}",
    "\\textrm{while}",
    "\\textrm{without}",
    "\\textrm{with}",
    "\\textrm{would}",
    "\\textrm{x-axis,}",
    "\\textrm{x-axis}",
    "\\textrm{x-coordinate}",
    "\\textrm{x-intercepts}",
    "\\textrm{x=0}",
    "\\textrm{x=1.}",
    "\\textrm{x=1}",
    "\\textrm{x=2.}",
    "\\textrm{x=2}",
    "\\textrm{x=3.}",
    "\\textrm{x=3}",
    "\\textrm{x=4.}",
    "\\textrm{x=5?}",
    "\\textrm{x=5}",
    "\\textrm{x\\textasciicircum{}2}",
    "\\textrm{xe\\textasciicircum{}(x)}",
    "\\textrm{xy}",
    "\\textrm{x}",
    "\\textrm{y-axis.}",
    "\\textrm{y-axis}",
    "\\textrm{y-intercepts}",
    "\\textrm{y\\textasciicircum{}2}",
    "\\textrm{y}",
    "\\textrm{zero),}",
    "\\textrm{zero:}",
    "\\textrm{zero}",
    "\\textrm{—}",
    "a(1) = 6(1) - 12 = -6",
    "a(2) = 6(2) - 6 = 6",
    "a(t) = v'(t) = 6t - 6",
    "a(t) = v'(t) = s''(t) = 6t - 12",
    "du = -3 \\, dx",
    "du = 1 \\, dx",
    "du = 2 \\, dx",
    "du = 3 \\, dx",
    "du = 5 \\, dx",
    "du = dx",
    "dv = -\\sin(x) \\, dx",
    "dv = \\cos{\\left(x \\right)} \\, dx",
    "dv = \\sin{\\left(x \\right)} \\, dx",
    "dv = e^{x} \\, dx",
    "dy/dx",
    "dy/dx = - \\frac{1}{4} = - \\frac{1}{4}",
    "dy/dx = - \\frac{3}{4} = - \\frac{3}{4}",
    "dy/dx = - \\frac{x^{2}}{y^{2}}",
    "dy/dx = - \\frac{x}{y}",
    "e^u \\cdot u'",
    "e^{2 x - 1} \\cdot 2",
    "e^{2x - 1}",
    "e^{2x}",
    "e^{3}",
    "e^{4x}",
    "e^{5x} + C",
    "e^{5x}/x + C",
    "e^{\\sin(x)}",
    "e^{\\sin(x)}\\cos(x)",
    "e^{\\sin{\\left(x \\right)}} \\cdot \\cos{\\left(x \\right)}",
    "e^{\\sin{\\left(x \\right)}} \\cos{\\left(x \\right)}",
    "e^{x^2}",
    "e^{x^{2}} \\cdot 2 x",
    "f",
    "f'",
    "f'''(x) = -\\cos(x)",
    "f''(-1) = 6 \\left(-1\\right) = -6",
    "f''(0)",
    "f''(0) < 0",
    "f''(0) = -8 < 0",
    "f''(1)",
    "f''(1) = 12(1) - 6 = 6 > 0",
    "f''(1) = 6 \\cdot 1 = 6",
    "f''(1) = 6(1) = 6",
    "f''(1) > 0",
    "f''(2) = 2 = 2",
    "f''(2) = 6(2) - 6 = 6 > 0",
    "f''(3) = -2 = -2",
    "f''(x)",
    "f''(x) = -2",
    "f''(x) = -\\sin(x)",
    "f''(x) = -x^{-2} = -\\dfrac{1}{x^{2}}",
    "f''(x) = 12x - 6",
    "f''(x) = 12x^{2} - 6",
    "f''(x) = 12x^{2} - 8",
    "f''(x) = 2",
    "f''(x) = 2 \\cdot 2 e^{2x} = 4 e^{2x}",
    "f''(x) = 4 \\left(3 x^{2} - 1\\right)",
    "f''(x) = 6 \\left(x - 2\\right)",
    "f''(x) = 6 x",
    "f''(x) = 6x",
    "f''(x) = 6x - 6",
    "f''(x) > 0",
    "f''(x)=0",
    "f'(-1)",
    "f'(-1) = -2",
    "f'(-1) = 4 \\left(-1\\right) = -4",
    "f'(0)",
    "f'(0) = 3 e^{3 \\cdot 0} = 3",
    "f'(1)",
    "f'(1) = -1",
    "f'(1) = 2 \\cdot 1 - 4 = -2",
    "f'(1) = 2(1) + 2 = 4",
    "f'(1) = 3",
    "f'(2)",
    "f'(2) = 2(2) - 3 = 1",
    "f'(2) = 3 \\cdot 2^{2} - 3 = 9",
    "f'(3)",
    "f'(3) = 2 \\cdot 3 = 6",
    "f'(3) = 6",
    "f'(x)",
    "f'(x) < 0",
    "f'(x) = - \\sin{\\left(x \\right)}",
    "f'(x) = -\\dfrac{1}{x^{2}}",
    "f'(x) = 0",
    "f'(x) = 1 + \\tan^{2}{\\left(x \\right)}",
    "f'(x) = 12 x^{3}",
    "f'(x) = 14 x^{6}",
    "f'(x) = 2 \\left(x - 2\\right)",
    "f'(x) = 2 e^{2x}",
    "f'(x) = 2 x",
    "f'(x) = 2 x - 4",
    "f'(x) = 2 x - 6",
    "f'(x) = 21 x^{2} - 4 x + 1",
    "f'(x) = 2x",
    "f'(x) = 2x + 2",
    "f'(x) = 2x - 3",
    "f'(x) = 2x - 4 = 0",
    "f'(x) = 3",
    "f'(x) = 3 \\cos{\\left(x \\right)}",
    "f'(x) = 3 e^{3 x}",
    "f'(x) = 3 x^{2} - 12",
    "f'(x) = 3 x^{2} - 3",
    "f'(x) = 3x^{2} - 2",
    "f'(x) = 3x^{2} - 3 = 3(x-1)(x+1)",
    "f'(x) = 3x^{2} - 6x = 3x(x-2)",
    "f'(x) = 4 x",
    "f'(x) = 4x^{3} - 6x",
    "f'(x) = 4x^{3} - 8x = 4x(x^{2}-2)",
    "f'(x) = 5 x^{4}",
    "f'(x) = 6 x^{2} - 6 x - 12",
    "f'(x) = 6 x^{5} - 4",
    "f'(x) = 6x^{2} - 6x = 6x(x-1)",
    "f'(x) = \\cos(x)",
    "f'(x) = \\cos{\\left(x \\right)}",
    "f'(x) = \\dfrac{1}{x}",
    "f'(x) = \\frac{2 x}{x^{2} + 1}",
    "f'(x) = e^{4 x} \\cdot 4 = 4 e^{4 x}",
    "f'(x) = x - 3",
    "f'(x) > 0",
    "f(-1) = 1",
    "f(-3) = \\left|{-3}\\right| = 3",
    "f(-x) = -f(x)",
    "f(0)=3",
    "f(1) = 0",
    "f(1) = 1",
    "f(1) = 1^{2} - 1 = 0",
    "f(1) = 1^{2} - 4 = -3",
    "f(1) = 1^{3} = 1",
    "f(2)",
    "f(2) = -1",
    "f(2) = 2^{2} + 2 = 6",
    "f(2) = 2^{2} = 4",
    "f(2) = 4-8+3=-1",
    "f(2) = 5(2)-2 = 8",
    "f(2)=4",
    "f(3)",
    "f(3) = 10 \\neq 6",
    "f(3) = 2 \\cdot 3 + 1 = 7",
    "f(3) = 3 \\cdot 3 + 4 = 13",
    "f(3) = 3^{2} = 9",
    "f(3) = 9",
    "f(3)=6",
    "f(4) = 3 \\cdot 4 = 12",
    "f(4) = 4 - 2 \\cdot 4 = -4",
    "f(5)",
    "f(5) = 10",
    "f(5) = 2 \\cdot 5 - 3 = 7",
    "f(5) = 25-20+3=8",
    "f(5) = 7 \\neq 10",
    "f(9) = 5 - 9 = -4",
    "f(x)",
    "f(x) = (2x + 1)/(x^2 + 1)",
    "f(x) = (2x - 5)^4",
    "f(x) = (\\sin(x))/(x)",
    "f(x) = (x + 1)/2",
    "f(x) = (x)/(x + 1)",
    "f(x) = (x^2 + 1)^3",
    "f(x) = (x^2 - 9)/(x - 3)",
    "f(x) = (x^2)/(x - 2)",
    "f(x) = (x^2-25)/(x-5)",
    "f(x) = (x^3 - 2x)^2",
    "f(x) = -x+6",
    "f(x) = -x^2 + 6x - 5",
    "f(x) = 1/(x-3)?",
    "f(x) = 1/(x^2-4)?",
    "f(x) = 1/\\sqrt{x+5}?",
    "f(x) = 1/x (x != 0)",
    "f(x) = 1/x at x = 0",
    "f(x) = 11",
    "f(x) = 2",
    "f(x) = 2 x - 3",
    "f(x) = 2x + 3",
    "f(x) = 2x+1",
    "f(x) = 2x+7",
    "f(x) = 2x-3",
    "f(x) = 2x^3 - 3x^2 + 2",
    "f(x) = 2x^3 - 3x^2 - 12x + 4",
    "f(x) = 2x^7 + 5",
    "f(x) = 3",
    "f(x) = 3 - x",
    "f(x) = 3 \\sin(x)",
    "f(x) = 3 x + 4",
    "f(x) = 3 x^{2} - 5 x + 7",
    "f(x) = 3-x",
    "f(x) = 3x",
    "f(x) = 3x + 2",
    "f(x) = 3x+4",
    "f(x) = 3x-4",
    "f(x) = 3x^4",
    "f(x) = 4 - 2 x",
    "f(x) = 4-2x",
    "f(x) = 4-x",
    "f(x) = 4x-3",
    "f(x) = 5",
    "f(x) = 5 - x",
    "f(x) = 5 x - 7",
    "f(x) = 5-x",
    "f(x) = 5x - 2",
    "f(x) = 5x+1",
    "f(x) = 7x^3 - 2x^2 + x",
    "f(x) = 9",
    "f(x) = [x]",
    "f(x) = \\cos(x)",
    "f(x) = \\frac{1}{\\sqrt{x + 5}}",
    "f(x) = \\frac{1}{x - 3}",
    "f(x) = \\frac{1}{x^{2} - 4}",
    "f(x) = \\frac{2 x + 3}{x - 1}",
    "f(x) = \\frac{\\sqrt{x + 1}}{x - 4}",
    "f(x) = \\frac{x^{2} + 2 x}{x + 5}",
    "f(x) = \\frac{x^{2} - 1}{x + 3}",
    "f(x) = \\left|{x}\\right|",
    "f(x) = \\ln(3x^2 + 5)",
    "f(x) = \\ln(5x - 1)",
    "f(x) = \\ln(\\cos(x))",
    "f(x) = \\ln(x)",
    "f(x) = \\ln(x^2 + 1)",
    "f(x) = \\ln(x^3 - 2)",
    "f(x) = \\sin(2x + 3)",
    "f(x) = \\sin(3x - 1)",
    "f(x) = \\sin(x)",
    "f(x) = \\sin(x) + \\cos(x)",
    "f(x) = \\sin(x) \\cdot \\cos(x)",
    "f(x) = \\sin(x^2)",
    "f(x) = \\sqrt{9 - x^{2}}",
    "f(x) = \\sqrt{9-x^2}?",
    "f(x) = \\sqrt{x - 2}",
    "f(x) = \\sqrt{x+1}/(x-4)?",
    "f(x) = \\sqrt{x-2}?",
    "f(x) = \\tan(x)",
    "f(x) = a \\cos(x)",
    "f(x) = a \\sin(x)",
    "f(x) = a \\tan(x)",
    "f(x) = e^{2x - 1}",
    "f(x) = e^{2x}",
    "f(x) = e^{3x}",
    "f(x) = e^{4x}",
    "f(x) = e^{\\sin(x)}",
    "f(x) = e^{x^2}",
    "f(x) = x \\cdot \\cos(x)",
    "f(x) = x+1",
    "f(x) = x^2",
    "f(x) = x^2 + 2x",
    "f(x) = x^2 - 3x",
    "f(x) = x^2 - 4x + 3",
    "f(x) = x^2 - 4x + 7",
    "f(x) = x^2 - 6x + 5",
    "f(x) = x^2 \\cdot \\sin(x)",
    "f(x) = x^2 \\cdot x + 1",
    "f(x) = x^2+2",
    "f(x) = x^2-1",
    "f(x) = x^2-4",
    "f(x) = x^2/2 - 3x",
    "f(x) = x^3",
    "f(x) = x^3 - 12x",
    "f(x) = x^3 - 2x",
    "f(x) = x^3 - 3x",
    "f(x) = x^3 - 3x + 1",
    "f(x) = x^3 - 3x^2",
    "f(x) = x^3 - 6x^2 + 9x",
    "f(x) = x^4 - 2x^2",
    "f(x) = x^4 - 3x^2",
    "f(x) = x^4 - 4x^2",
    "f(x) = x^5",
    "f(x) = x^6 - 4x",
    "f(x) = x^{2}",
    "f(x) = x^{2} - 1",
    "f(x) = x^{3}",
    "f(x) = x^{3} - 4 x + 1",
    "f(x) = |x|",
    "f(x+h) - f(x)",
    "f(x+h) = (x+h)^2 = x^2 + 2xh + h^2",
    "f(x+h) = 3(x+h) + 2 = 3x + 3h + 2",
    "f^{-1}(11)",
    "f^{-1}(11) = 2",
    "f^{-1}(2)",
    "f^{-1}(2) = 4",
    "f^{-1}(3)",
    "f^{-1}(3) = -2",
    "f^{-1}(5)",
    "f^{-1}(5) = 3",
    "f^{-1}(8)",
    "f^{-1}(9)",
    "f^{-1}(9) = 3",
    "f^{-1}(9) = \\sqrt{9} = 3",
    "f^{-1}(x) = (x+3)/2",
    "f^{-1}(x) = (x-1)/2",
    "f^{-1}(x) = (x-3)/2",
    "f^{-1}(x) = 1/x^3",
    "f^{-1}(x) = 2x + 1",
    "f^{-1}(x) = 2x - 1",
    "f^{-1}(x) = 2x-3",
    "f^{-1}(x) = 3x",
    "f^{-1}(x) = \\dfrac{x+2}{5}",
    "f^{-1}(x) = \\dfrac{x-3}{2}",
    "f^{-1}(x) = \\sqrt{x}",
    "f^{-1}(x) = x/2 - 1",
    "f^{-1}(x) = x/2 - 3",
    "f^{-1}(x) = x^3",
    "f^{-1}(x) = x^{1/3}",
    "g(-1)",
    "g(-1) = -1 + 2 = 1",
    "g(-1) = 1",
    "g(1)",
    "g(1) = -3",
    "g(1) = 1 + 2 = 3",
    "g(1) = 1^{2} + 3 = 4",
    "g(1) = 2",
    "g(1) = 2 \\cdot 1 - 5 = -3",
    "g(1) = 3 \\cdot 1 - 1 = 2",
    "g(1) = 4",
    "g(2)",
    "g(2) = 1",
    "g(2) = 2 - 1 = 1",
    "g(2) = 2 \\cdot 2 - 1 = 3",
    "g(2) = 2^{2} + 1 = 5",
    "g(2) = 5",
    "g(3)",
    "g(3) = 3",
    "g(3) = 3^{2} - 2 \\cdot 3 = 3",
    "g(3) = 3^{2} = 9",
    "g(3) = 9",
    "g(4) = 4 - 5 = -1",
    "g(x) = 2 x - 5",
    "g(x) = 2x-1",
    "g(x) = 2x-5",
    "g(x) = 3 x - 1",
    "g(x) = 3x-1",
    "g(x) = x + 2",
    "g(x) = x - 1",
    "g(x) = x+2",
    "g(x) = x-1",
    "g(x) = x-5",
    "g(x) = x^2",
    "g(x) = x^2+1",
    "g(x) = x^2+3",
    "g(x) = x^2-2x",
    "g(x) = x^{2}",
    "g(x) = x^{2} + 1",
    "g(x) = x^{2} + 3",
    "g(x) = x^{2} - 2 x",
    "h \\neq 0",
    "h \\to 0",
    "k=3",
    "k=4",
    "ln|2x+1| + C",
    "ln|\\cos(x)| + C",
    "ln|\\sec(x)| + C",
    "ln|\\sin(x)| + C",
    "ln|x| + C",
    "m=6",
    "t = 1",
    "t = 16",
    "t = 2",
    "t = 3",
    "t = 32",
    "t = 4",
    "t = 8",
    "t=1",
    "t=2",
    "u = 2 x + 1",
    "u = 2 x + 3",
    "u = 2 x - 1",
    "u = 2 x - 5",
    "u = 3 x",
    "u = 3 x + 5",
    "u = 3 x - 1",
    "u = 3 x^{2} + 5",
    "u = 4 - 3 x",
    "u = 4 x",
    "u = 5 x",
    "u = 5 x - 1",
    "u = \\cos{\\left(x \\right)}",
    "u = \\sin{\\left(x \\right)}",
    "u = x",
    "u = x^{2}",
    "u = x^{2} + 1",
    "u = x^{3} - 2",
    "u = x^{3} - 2 x",
    "u' = - \\sin{\\left(x \\right)}",
    "u' = 1",
    "u' = 2",
    "u' = 2 x",
    "u' = 3",
    "u' = 3 x^{2}",
    "u' = 3 x^{2} - 2",
    "u' = 4",
    "u' = 5",
    "u' = 6 x",
    "u' = \\cos{\\left(x \\right)}",
    "u'v + uv'",
    "v = - \\cos{\\left(x \\right)}",
    "v = \\cos(x)",
    "v = \\cos{\\left(x \\right)}",
    "v = \\sin{\\left(x \\right)}",
    "v = e^{x}",
    "v = x",
    "v = x + 1",
    "v = x - 2",
    "v = x^{2} + 1",
    "v' = - \\sin{\\left(x \\right)}",
    "v' = 1",
    "v' = 2 x",
    "v' = \\cos{\\left(x \\right)}",
    "v(2)",
    "v(t) = 0",
    "v(t) = s'(t) = 16 - 2t",
    "v(t) = s'(t) = 2t - 4",
    "v(t) = s'(t) = 3t^{2} - 12t + 9",
    "v(t)=0",
    "x",
    "x + 1",
    "x + 1 \\geq 0",
    "x + 2",
    "x + 3",
    "x + 3 and y",
    "x + 3y = -1",
    "x + 4y = 4",
    "x + 5 and y",
    "x - 2 \\geq 0",
    "x - 3",
    "x - 3 > 0",
    "x - 3 \\neq 0",
    "x - 4 \\neq 0",
    "x < -1/",
    "x < -5",
    "x < 0",
    "x < 1",
    "x < 2",
    "x < 3",
    "x = -1",
    "x = -1, 1",
    "x = -1, 2",
    "x = -2",
    "x = -2 \\textrm{ and } x = 2",
    "x = -2, 2",
    "x = -3",
    "x = -5",
    "x = 0",
    "x = 2",
    "x = 2y - 1",
    "x = 3",
    "x = 4",
    "x = \\dfrac{y+2}{5}",
    "x = \\dfrac{y-3}{2}",
    "x = y^{1/3}",
    "x > -1",
    "x > -5",
    "x > 0",
    "x > 0.",
    "x > 1/",
    "x > 2",
    "x > 3",
    "x \\cdot \\ln(x) + C",
    "x \\cos(x) - \\sin(x) + C",
    "x \\geq -1",
    "x \\geq -1, x \\neq 4",
    "x \\geq -5",
    "x \\geq 0",
    "x \\geq 1",
    "x \\geq 2",
    "x \\geq 3",
    "x \\in \\left(-1, 1\\right)",
    "x \\in \\left(2, \\infty\\right)",
    "x \\left(3 x + 2\\right)",
    "x \\left(x \\cos{\\left(x \\right)} + 2 \\sin{\\left(x \\right)}\\right)",
    "x \\leq -3",
    "x \\leq 2",
    "x \\neq 0",
    "x \\neq 1",
    "x \\neq 2",
    "x \\neq 3",
    "x \\neq 5",
    "x \\sin(x) + C",
    "x \\sin(x) + \\cos(x) + C",
    "x \\sin{\\left(x \\right)}",
    "x \\to 0",
    "x \\to 0^{+}",
    "x \\to 0^{-}",
    "x \\to 2^{+}",
    "x \\to 2^{-}",
    "x \\to 3",
    "x \\to \\infty",
    "x(x \\cos(x) + 2 \\sin(x))",
    "x+1=4",
    "x- \\cos{\\left(x \\right)}",
    "x-2 \\to 0^{+}",
    "x-2 \\to 0^{-}",
    "x<0",
    "x<1",
    "x=-1",
    "x=-2",
    "x=-3",
    "x=0",
    "x=0, \\sqrt{2}, -\\sqrt{2}",
    "x=1",
    "x=2",
    "x=3",
    "x=4",
    "x=5",
    "x=\\frac{\\pi}{2}",
    "x=x_0",
    "x>0",
    "x\\sin{\\left(x \\right)}",
    "x^2",
    "x^2 + 7x + C",
    "x^2 - 1 between x",
    "x^2 - 3x",
    "x^2 - 4x + 3 on the closed interval [0",
    "x^2 \\cos(x)",
    "x^2 \\sin(x)/2 + C",
    "x^2 between x",
    "x^2/(x^2 - 4x + 4) - 4x/(x^2 - 4x + 4)",
    "x^2/2 - 3x",
    "x^2e^{x}/2 + C",
    "x^3",
    "x^3 + C",
    "x^4 + 5x^2 + C",
    "x^4 - x^2 + C",
    "x^5",
    "x^5/5 + 5x^3/3 + C",
    "x^6 - 3x + C",
    "x^6 - 4x",
    "x^{-1}",
    "x^{1}",
    "x^{2}",
    "x^{2} + 2 x + 4",
    "x^{2} + y^{2} = 25",
    "x^{2} - 4 \\neq 0",
    "x^{2} - 5x + 6 = 0",
    "x^{2} - 9 = 0 \\Rightarrow x = 3",
    "x^{2} \\to 0^{+}",
    "x^{3}",
    "x^{3} + y^{3} = 9",
    "x^{4} - 3x^{2} + 1",
    "x^{4} \\to 0^{+}",
    "x^{6}",
    "x_0=1",
    "xe^{x} - \\int e^{x} \\, dx",
    "xy=4",
    "y",
    "y - 0 = -1(x - 1)",
    "y - 0 = -\\dfrac{1}{3}(x - (-1))",
    "y - 1 = -2(x - -1)",
    "y - 1 = 3(x - 1)",
    "y - 3 = 2x",
    "y - 4 = 6(x - 1)",
    "y - 9 = 6(x - 3)",
    "y - \\dfrac{1}{2} = 4(x-2)",
    "y - f(a) = f'(a)(x-a)",
    "y - y_0 = m(x - x_0)",
    "y = (2x^2 + 1)/(x^2 - 4)",
    "y = (3x + 1)/(x - 5)",
    "y = (x + 1)/(x - 3)",
    "y = (x - 1)/(x + 2)",
    "y = -1",
    "y = -1/5",
    "y = -1x",
    "y = -1x + 1",
    "y = -2x + 1",
    "y = -2x - 1",
    "y = -3",
    "y = -3 and y = 3",
    "y = -3x - 2",
    "y = -3x - 3",
    "y = -4",
    "y = -6x - 9",
    "y = -9 and y = 9",
    "y = -x/4 + 1",
    "y = 0",
    "y = 0 only",
    "y = 0x - 1",
    "y = 1",
    "y = 1/(x^2 - 9)",
    "y = 1/x at the point (2",
    "y = 1x + 1",
    "y = 1x + 3",
    "y = 1x - 2",
    "y = 2",
    "y = 2x + 2",
    "y = 2x - 1",
    "y = 2x+3",
    "y = 2x^2 + 1 at x = -1",
    "y = 3",
    "y = 3 only",
    "y = 3x",
    "y = 3x + 1",
    "y = 3x + 3",
    "y = 3x - 2",
    "y = 3x^2 + 1 at the point (1",
    "y = 4 - x^2",
    "y = 4x - 15/2",
    "y = 4x - 7",
    "y = 4x - \\dfrac{15}{2}",
    "y = 5",
    "y = 5x-2",
    "y = 6x + 4",
    "y = 6x + 9",
    "y = 6x - 2",
    "y = 6x - 9",
    "y = 9x + 6",
    "y = \\dfrac{2}{1} = 2",
    "y = \\dfrac{x+1}{2}",
    "y = \\sqrt{x}",
    "y = \\sqrt{x} from x=0 to x=4",
    "y = f(x) is symmetric",
    "y = x",
    "y = x from x=0 to x=3",
    "y = x^2",
    "y = x^2 - 3x + 2 at x = 1",
    "y = x^2 - 4x + 3 at the point (3",
    "y = x^2 - 4x + 3 at x = 1",
    "y = x^2 - 5x + 6",
    "y = x^2 at x = -1",
    "y = x^2 at x = 3",
    "y = x^2 from x=0 to x=2",
    "y = x^3",
    "y = x^3 + 1 at the point (-1",
    "y = x^3 - 3x at x = 2",
    "y = x^3 - x",
    "y = x^3 at the point (1",
    "y = x^3 at x = 1",
    "y = x^3 from x=0 to x=1",
    "y = x^4 - 3x^2 + 1",
    "y = x^{3}",
    "y' = -\\dfrac{1}{x^{2}}",
    "y' = 2x - 4",
    "y' = 3x^{2}",
    "y' = 6x",
    "y'(-1) = 3",
    "y'(1) = 3(1)^{2} = 3",
    "y'(1) = 6",
    "y'(2) = -\\dfrac{1}{4}",
    "y'(3) = 2(3) - 4 = 2",
    "y'(x_0)",
    "y=0",
    "y=1",
    "y=3",
    "y=3 x",
    "y=4 - x^{2}",
    "y=6 - x",
    "y=x + 3",
    "y=x + 5",
    "y=x^{2}",
    "y=x^{2} - 1",
    "y=x^{3}",
    "y^2",
    "y^3",
    "y^{2} = 9",
    "|x-3| = x-3",
    "|x|",
    "|x| = -x",
    "|x| = x",
  ];

  testWidgets(
    'every MTH 121 LaTeX token renders without error or fallback',
    (WidgetTester tester) async {
      final List<String> broken = <String>[];
      for (final String expr in expressions) {
        await tester.pumpWidget(
          MaterialApp(home: Scaffold(body: MathText("\$$expr\$"))),
        );
        await tester.pumpAndSettle();
        final Object? err = tester.takeException();
        final bool mathWidgetExists = find.byType(Math).evaluate().isNotEmpty;
        if (err != null) {
          if (!mathWidgetExists) {
            broken.add('EXCEPTION (\$err): \$expr');
          }
          continue;
        }
        if (!mathWidgetExists) {
          broken.add('FALLBACK (no Math widget rendered): \$expr');
        }
      }
      expect(broken, isEmpty, reason: broken.join('X'));
    },
  );
}
