// Auto-generated: every distinct question/option/explanation field
// from the MTH122 bank, verified against the real
// flutter_math_fork renderer via MathText's mixed prose+LaTeX path.
import 'package:eduvora/core/widgets/math_text.dart';
import 'package:flutter/material.dart';
import 'package:flutter_math_fork/flutter_math.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  final List<String> fields = <String>[
    "\$(-3, 0)\$",
    "\$(0, 3)\$",
    "\$(0, \\pm 4)\$",
    "\$(10, 10)\$",
    "\$(12, 0)\$",
    "\$(3, 0)\$",
    "\$(3, 2)\$",
    "\$(5, 5)\$",
    "\$(6, 4)\$",
    "\$(\\pm 3, 0)\$",
    "\$(\\pm 4, 0)\$",
    "\$(\\pm 5, 0)\$",
    "\$(x + 1)^2 + (y - 2)^2 = 9\$",
    "\$(x - 1)^2 + (y + 2)^2 = 3\$",
    "\$(x - 1)^2 + (y + 2)^2 = 9\$",
    "\$(x - 1)^2 + (y - 2)^2 = 9\$",
    "\$-12\$",
    "\$-12\$ m/s\$^2\$",
    "\$-2\\mathbf{i} + \\mathbf{j} - 3\\mathbf{k}\$",
    "\$-3\$",
    "\$-3\$ m/s",
    "\$-3\\mathbf{i} - 4\\mathbf{j}\$",
    "\$-4\$",
    "\$-5\\mathbf{i} + 5\\mathbf{j} - 5\\mathbf{k}\$",
    "\$-\\cos t\\,\\mathbf{i} - \\sin t\\,\\mathbf{j}\$",
    "\$-\\frac{2}{3}\$",
    "\$-\\frac{3}{2}\$",
    "\$-\\mathbf{i} - 5\\mathbf{j} + \\mathbf{k}\$",
    "\$-\\mathbf{k}\$",
    "\$-\\sin t\\,\\mathbf{i} + \\cos t\\,\\mathbf{j} + \\mathbf{k}\$",
    "\$-\\sin t\\,\\mathbf{i} + \\cos t\\,\\mathbf{j} + t\\mathbf{k}\$",
    "\$0 < e < 1\$",
    "\$0\$",
    "\$0.25\$",
    "\$0.5\$",
    "\$0.75\$ m/s",
    "\$0.8\$ N",
    "\$1\$",
    "\$1\$ s",
    "\$1, 2, 2\$",
    "\$1.25\$ m/s",
    "\$1.5\$ m/s",
    "\$1.5\$ s",
    "\$1.67\$ N",
    "\$10\$",
    "\$10\$ N s",
    "\$10\$ m",
    "\$10\$ m/s\$^2\$",
    "\$11\$",
    "\$12\$",
    "\$12\$ m/s",
    "\$12\$ m/s\$^2\$",
    "\$12\\mathbf{i} + 6\\mathbf{j}\$",
    "\$12\\mathbf{i} - 7\\mathbf{j} + 12\\mathbf{k}\$",
    "\$13\$",
    "\$144\$ kg",
    "\$15\$ N",
    "\$16\$",
    "\$16\$ N s",
    "\$16\$ kg m/s",
    "\$16\$ m/s",
    "\$16\$ m/s\$^2\$",
    "\$17\$ m/s",
    "\$18\$ N",
    "\$18\$ N s",
    "\$18\$ kg",
    "\$2\$",
    "\$2\$ m",
    "\$2\$ m/s",
    "\$2\$ m/s\$^2\$",
    "\$2\$ s",
    "\$2.5\$ m/s\$^2\$",
    "\$20\$ m",
    "\$20\$ m/s",
    "\$24\$ N s",
    "\$24\$ kg m/s",
    "\$24\$ m",
    "\$25\$",
    "\$26\$",
    "\$2\\mathbf{a} = 10\\mathbf{i} - 6\\mathbf{j} + 4\\mathbf{k}\$. Adding \$\\mathbf{b}\$: \$(10-2)\\mathbf{i} + (-6+1)\\mathbf{j} + (4+4)\\mathbf{k} = 8\\mathbf{i} - 5\\mathbf{j} + 8\\mathbf{k}\$.",
    "\$2\\mathbf{i} + 2\\mathbf{j} + 2\\mathbf{k}\$",
    "\$2\\mathbf{i} + 3\\mathbf{j} + \\mathbf{k}\$",
    "\$2\\mathbf{i} + 3\\mathbf{j} - 2\\mathbf{k}\$",
    "\$2\\mathbf{i} + 3\\mathbf{j} - \\sin t\\,\\mathbf{k}\$",
    "\$2\\mathbf{i} + 3t\\mathbf{j}\$",
    "\$2\\mathbf{i} + 4\\mathbf{j} + 2\\mathbf{k}\$",
    "\$2\\mathbf{i} + 6t\\mathbf{j}\$",
    "\$2\\mathbf{i} + \\mathbf{j} + 3\\mathbf{k}\$",
    "\$2\\mathbf{i} - 4\\mathbf{j} - 6\\mathbf{k}\$",
    "\$2\\mathbf{i} - \\mathbf{j} + 3\\mathbf{k}\$",
    "\$2\\pi\$ s",
    "\$2t\\mathbf{i} + 3\\mathbf{j} + \\cos t\\,\\mathbf{k}\$",
    "\$2t\\mathbf{i} + 3t\\mathbf{j} - \\cos t\\,\\mathbf{k}\$",
    "\$2t\\mathbf{i} + 3t^2\\mathbf{j}\$",
    "\$3\$",
    "\$3\$ kg m/s",
    "\$3\$ m/s",
    "\$3\$ m/s\$^2\$",
    "\$3\$ s",
    "\$3(\\mathbf{i} + 2\\mathbf{j} + 2\\mathbf{k})\$",
    "\$30\$ N s",
    "\$30\$ kg",
    "\$30^{\\circ}\$",
    "\$32\$",
    "\$32\$ m",
    "\$36\$",
    "\$36\$ m/s\$^2\$",
    "\$3\\mathbf{a} = 6\\mathbf{i} - 3\\mathbf{j} + 9\\mathbf{k}\$ and \$2\\mathbf{b} = 2\\mathbf{i} + 8\\mathbf{j} - 4\\mathbf{k}\$. Subtracting: \$(6-2)\\mathbf{i} + (-3-8)\\mathbf{j} + (9+4)\\mathbf{k} = 4\\mathbf{i} - 11\\mathbf{j} + 13\\mathbf{k}\$.",
    "\$3\\mathbf{i} + 2\\mathbf{j} + 2\\mathbf{k}\$",
    "\$3\\mathbf{i} + 2\\mathbf{j} + \\mathbf{k}\$",
    "\$3\\mathbf{i} + 2\\mathbf{j}\$",
    "\$3\\mathbf{i} + 3\\mathbf{j} + 5\\mathbf{k}\$",
    "\$3\\mathbf{i} + 3\\mathbf{j} + \\mathbf{k}\$",
    "\$3\\mathbf{i} + 4\\mathbf{j} + 6\\mathbf{k}\$",
    "\$3\\mathbf{i} + 4\\mathbf{j}\$",
    "\$3\\mathbf{i} - 2\\mathbf{j} + 6\\mathbf{k}\$",
    "\$3x + 4y = 25\$",
    "\$3x + 4y = 5\$",
    "\$3x - 4y = 25\$",
    "\$4\$",
    "\$4\$ N s",
    "\$4\$ kg",
    "\$4\$ m",
    "\$4\$ m/s",
    "\$4\$ s",
    "\$4.5\$ s",
    "\$40\$ m",
    "\$44\$ m",
    "\$45\$ N",
    "\$45^{\\circ}\$",
    "\$48\$ kg m/s",
    "\$48\$ m/s",
    "\$48\$ m/s\$^2\$",
    "\$4\\mathbf{i} + 11\\mathbf{j} + 13\\mathbf{k}\$",
    "\$4\\mathbf{i} - 11\\mathbf{j} + 13\\mathbf{k}\$",
    "\$4x + 3y = 25\$",
    "\$5\$",
    "\$5\$ m/s",
    "\$5\$ m/s\$^2\$",
    "\$5\\mathbf{i} + 5\\mathbf{j} + 5\\mathbf{k}\$",
    "\$5\\mathbf{i} + 8\\mathbf{j} + 6\\mathbf{k}\$",
    "\$5\\mathbf{i} - 5\\mathbf{j} + 5\\mathbf{k}\$",
    "\$6\$",
    "\$6\$ N s",
    "\$6\$ m/s",
    "\$6\$ m/s\$^2\$",
    "\$60^{\\circ}\$",
    "\$68\$ m",
    "\$6\\mathbf{i} + 12\\mathbf{j}\$",
    "\$6\\mathbf{i} + 2\\mathbf{j}\$",
    "\$6\\mathbf{i} + 3\\mathbf{j}\$",
    "\$6\\mathbf{i} + 4\\mathbf{j} + 2\\mathbf{k}\$",
    "\$6\\mathbf{i} + 6\\mathbf{j}\$",
    "\$6\\mathbf{i} - 3\\mathbf{j} + 9\\mathbf{k}\$",
    "\$6\\mathbf{j} + 2\\mathbf{k}\$",
    "\$6\\mathbf{j}\$",
    "\$6\\sqrt{2}\$ m/s",
    "\$6t\\mathbf{j}\$",
    "\$7\$",
    "\$7\$ m/s",
    "\$7\$ m/s\$^2\$",
    "\$72\$ m/s",
    "\$8\$",
    "\$8\$ N",
    "\$8\$ m/s",
    "\$8\$ s",
    "\$80\$ N",
    "\$80\$ m",
    "\$80\$ m/s",
    "\$80\$ m/s\$^2\$",
    "\$8\\mathbf{i} + 5\\mathbf{j} + 5\\mathbf{k}\$",
    "\$8\\mathbf{i} - 5\\mathbf{j} + 4\\mathbf{k}\$",
    "\$8\\mathbf{i} - 5\\mathbf{j} + 8\\mathbf{k}\$",
    "\$8\\pi\$ s",
    "\$9\$ m/s",
    "\$9\$ m/s\$^2\$",
    "\$9\$ s",
    "\$90^{\\circ}\$",
    "\$T = 2\\pi L/g\$",
    "\$T = 2\\pi\\sqrt{L/g}\$",
    "\$T = 2\\pi\\sqrt{g/L}\$",
    "\$T = \\sqrt{2\\pi L/g}\$",
    "\$\\alpha, \\beta, \\gamma\$ measured in radians",
    "\$\\cos\\alpha, \\cos\\beta, \\cos\\gamma\$",
    "\$\\cos\\theta = \\dfrac{\\mathbf{a}\\cdot\\mathbf{b}}{|\\mathbf{a}||\\mathbf{b}|} = \\dfrac{1}{(1)(\\sqrt{2})} = \\dfrac{1}{\\sqrt{2}}\$, so \$\\theta = 45^{\\circ}\$.",
    "\$\\ddot{x} = -\\omega^2 \\dot{x}\$",
    "\$\\ddot{x} = -\\omega^2 x\$",
    "\$\\ddot{x} = \\omega^2 x\$",
    "\$\\dfrac{d\\mathbf{r}}{dt} = 3t^{2}\\mathbf{i} + 2t\\mathbf{j} + \\mathbf{k}\$. Substituting \$t=1\$ gives \$3\\mathbf{i} + 2\\mathbf{j} + \\mathbf{k}\$.",
    "\$\\dfrac{dy}{dx} = 2x\$, so at \$x=2\$ the gradient is \$4\$. Using \$y-y_1=m(x-x_1)\$: \$y-4 = 4(x-2)\$, which simplifies to \$y = 4x-4\$.",
    "\$\\dfrac{dy}{dx} = 3x^{2}\$, so at \$x=1\$ the gradient is \$3(1)^{2} = 3\$.",
    "\$\\dot{x} = -\\omega^2 x\$",
    "\$\\frac{1}{2}\$",
    "\$\\frac{1}{2}, 1, 1\$",
    "\$\\frac{1}{2}\\mathbf{i} + \\mathbf{j} + \\mathbf{k}\$",
    "\$\\frac{1}{3}\$",
    "\$\\frac{1}{3}(\\mathbf{i} + 2\\mathbf{j} + 2\\mathbf{k})\$",
    "\$\\frac{1}{3}, \\frac{2}{3}, \\frac{2}{3}\$",
    "\$\\frac{1}{5}(\\mathbf{i} + 2\\mathbf{j} + 2\\mathbf{k})\$",
    "\$\\frac{1}{9}(\\mathbf{i} + 2\\mathbf{j} + 2\\mathbf{k})\$",
    "\$\\frac{1}{9}, \\frac{2}{9}, \\frac{2}{9}\$",
    "\$\\frac{25}{16}\$",
    "\$\\frac{26}{17}\$",
    "\$\\frac{2}{3}\$",
    "\$\\frac{3}{2}\$",
    "\$\\frac{3}{4}\$",
    "\$\\frac{3}{5}\$",
    "\$\\frac{4}{5}\$",
    "\$\\frac{5}{4}\$",
    "\$\\frac{5}{6}\$",
    "\$\\frac{6}{25}\$",
    "\$\\frac{6}{5}\$",
    "\$\\frac{9}{25}\$",
    "\$\\frac{\\pi}{2}\$ s",
    "\$\\frac{\\pi}{4}\$ s",
    "\$\\int_0^1 6t^{2}dt = 2\$, \$\\int_0^1 4t\\,dt = 2\$, and \$\\int_0^1 2\\,dt = 2\$, giving \$2\\mathbf{i} + 2\\mathbf{j} + 2\\mathbf{k}\$.",
    "\$\\mathbf{a} = 2\\mathbf{b}\$, so one vector is a scalar multiple of the other. Two such vectors are parallel and therefore linearly dependent.",
    "\$\\mathbf{a} \\cdot \\mathbf{b} = (2)(3) + (3)(-2) = 6 - 6 = 0\$. A vanishing scalar product between two non-zero vectors means the angle between them is \$90^{\\circ}\$, so they are perpendicular.",
    "\$\\mathbf{a}\\cdot\\mathbf{b} = (3)(2) + (-1)(4) + (2)(-1) = 6 - 4 - 2 = 0\$.",
    "\$\\mathbf{i} + 5\\mathbf{j} - 5\\mathbf{k}\$",
    "\$\\mathbf{i} + \\mathbf{j} + \\mathbf{k}\$",
    "\$\\mathbf{i} + \\mathbf{j}\$",
    "\$\\mathbf{i} - 5\\mathbf{j} + 5\\mathbf{k}\$",
    "\$\\mathbf{k}\$",
    "\$\\mathbf{v} = 6t\\mathbf{i} + 6t^{2}\\mathbf{j}\$, so \$\\mathbf{a} = \\dfrac{d\\mathbf{v}}{dt} = 6\\mathbf{i} + 12t\\mathbf{j}\$. At \$t=1\$: \$\\mathbf{a} = 6\\mathbf{i} + 12\\mathbf{j}\$.",
    "\$\\overrightarrow{AB} = \\mathbf{b} - \\mathbf{a} = (4-1)\\mathbf{i} + (6-2)\\mathbf{j} + (3-3)\\mathbf{k} = 3\\mathbf{i} + 4\\mathbf{j}\$.",
    "\$\\sin t\\,\\mathbf{i} - \\cos t\\,\\mathbf{j} + \\mathbf{k}\$",
    "\$\\sin\\alpha, \\sin\\beta, \\sin\\gamma\$",
    "\$\\sqrt{11}\$",
    "\$\\sqrt{34}\$",
    "\$\\sqrt{41}\$",
    "\$\\sqrt{7}\$",
    "\$\\tan\\alpha, \\tan\\beta, \\tan\\gamma\$",
    "\$d = \\dfrac{|5(0)+12(0)-26|}{\\sqrt{5^{2}+12^{2}}} = \\dfrac{26}{\\sqrt{169}} = \\dfrac{26}{13} = 2\$.",
    "\$d = \\sqrt{(7-3)^{2}+(1-4)^{2}} = \\sqrt{16+9} = \\sqrt{25} = 5\$.",
    "\$d = \\sqrt{(x_2-x_1)^{2} + (y_2-y_1)^{2}} = \\sqrt{(4-1)^{2}+(6-2)^{2}} = \\sqrt{9+16} = \\sqrt{25} = 5\$.",
    "\$e = 0\$",
    "\$e = 0\$ only",
    "\$e = 0.5\$",
    "\$e = 1\$",
    "\$e > 1\$",
    "\$e\$ times the relative velocity of approach",
    "\$k = -10\$",
    "\$k = -5\$",
    "\$k = 10\$",
    "\$k = 2\$",
    "\$k = 20\$",
    "\$k = 5\$",
    "\$k = 6\$",
    "\$m_1 + m_2 = 0\$",
    "\$m_1 = m_2\$",
    "\$m_1 m_2 = -1\$",
    "\$m_1 m_2 = 1\$",
    "\$t = 0\$ s and \$t = 3\$ s",
    "\$t = 1\$ s and \$t = 3\$ s",
    "\$t = 1\$ s and \$t = 9\$ s",
    "\$t = 2\$ s only",
    "\$t^2\\mathbf{i} + 3\\mathbf{j} + \\cos t\\,\\mathbf{k}\$",
    "\$v = \\dfrac{ds}{dt} = 6t^{2}-6t+4\$. At \$t=2\$: \$v = 24-12+4 = 16\$ m/s.",
    "\$x = -12\$",
    "\$x = -3\$",
    "\$x = 3\$",
    "\$y = -3\$",
    "\$y = -4x + 12\$",
    "\$y = -\\frac{1}{4}x + 4\$",
    "\$y = -\\frac{1}{4}x + \\frac{9}{2}\$",
    "\$y = 2x + 5\$",
    "\$y = 2x\$",
    "\$y = 3x + 1\$",
    "\$y = 3x - 1\$",
    "\$y = 3x - 5\$",
    "\$y = 4x + 4\$",
    "\$y = 4x - 2\$",
    "\$y = 4x - 4\$",
    "\$y = \\frac{1}{4}x + \\frac{7}{2}\$",
    "\$y = \\pm\\frac{3}{4}x\$",
    "\$y = \\pm\\frac{4}{3}x\$",
    "\$y = \\pm\\frac{5}{4}x\$",
    "\$y = \\pm\\frac{9}{16}x\$",
    "\$|\\mathbf{a}| = \\sqrt{2^{2}+3^{2}+6^{2}} = \\sqrt{4+9+36} = \\sqrt{49} = 7\$.",
    "\$|\\mathbf{a}| = \\sqrt{6^{2}+(-2)^{2}+3^{2}} = \\sqrt{36+4+9} = \\sqrt{49} = 7\$.",
    "A ball is projected vertically upward with speed \$20\$ m/s. Taking \$g = 10\$ m/s\$^2\$, find the maximum height reached.",
    "A ball is projected vertically upward with speed \$20\$ m/s. Taking \$g = 10\$ m/s\$^2\$, find the total time before it returns to the point of projection.",
    "A ball of mass \$2\$ kg moving at \$5\$ m/s rebounds along the same line at \$3\$ m/s. Find the magnitude of the impulse it receives.",
    "A body accelerates uniformly from \$10\$ m/s to \$30\$ m/s in \$4\$ s. Find its acceleration.",
    "A body of mass \$2\$ kg moving at \$6\$ m/s collides with a stationary body of mass \$4\$ kg, and the two move off together. Find their common velocity.",
    "A body of mass \$3\$ kg has its velocity changed from \$2\$ m/s to \$8\$ m/s along a straight line. Find the impulse it receives.",
    "A body starts with velocity \$5\$ m/s and moves with constant acceleration \$3\$ m/s\$^2\$. Find its velocity after \$4\$ s.",
    "A body starts with velocity \$5\$ m/s and moves with constant acceleration \$3\$ m/s\$^2\$. Find the distance covered in \$4\$ s.",
    "A car travelling at \$20\$ m/s decelerates uniformly at \$5\$ m/s\$^2\$. How far does it travel before coming to rest?",
    "A circle has the segment joining \$(0, 0)\$ and \$(4, 6)\$ as a diameter. Find its centre and radius.",
    "A conic section has eccentricity \$e\$. The conic is an ellipse when:",
    "A force acts on a body of mass \$5\$ kg, giving it an acceleration of \$3\$ m/s\$^2\$. Find the magnitude of the force.",
    "A horizontal force of \$50\$ N acts on a \$10\$ kg block against a frictional force of \$20\$ N. Find the acceleration of the block.",
    "A line has gradient \$\\frac{2}{3}\$. What is the gradient of any line perpendicular to it?",
    "A particle has velocity \$\\mathbf{v} = 6\\mathbf{i} + 6\\mathbf{j}\$ m/s. Find its speed.",
    "A particle moves along a line with displacement \$s = 2t^3 - 3t^2 + 4t\$ metres. Find its velocity at \$t = 2\$ s.",
    "A particle moves along a straight line with displacement \$s = t^3 - 6t^2 + 9t\$ metres. Find its acceleration at \$t = 4\$ s.",
    "A particle moves along a straight line with displacement \$s = t^3 - 6t^2 + 9t\$ metres. Find its velocity at \$t = 4\$ s.",
    "A particle moves in a circle of radius \$3\$ m with constant angular speed \$4\$ rad/s. Find its linear speed.",
    "A particle moves in a circle of radius \$3\$ m with constant angular speed \$4\$ rad/s. Find the magnitude of its acceleration.",
    "A particle moves in a plane with position vector \$\\mathbf{r} = 3t^2\\mathbf{i} + 2t^3\\mathbf{j}\$. Find its acceleration at \$t = 1\$.",
    "A particle moves in a plane with position vector \$\\mathbf{r} = 3t^2\\mathbf{i} + 2t^3\\mathbf{j}\$. Find its velocity at \$t = 1\$.",
    "A particle moves so that its acceleration is always directed toward a fixed point and is proportional to its distance from that point. This motion is described by the equation:",
    "A particle moves with displacement \$s = t^3 - 6t^2 + 9t\$ metres. At what times is the particle momentarily at rest?",
    "A particle performs simple harmonic motion of amplitude \$5\$ m with angular frequency \$4\$ rad/s. Find its maximum speed.",
    "A particle performs simple harmonic motion with \$\\ddot{x} = -16x\$. Find the period of the motion.",
    "A perfectly elastic impact conserves kinetic energy, and the speed of separation equals the speed of approach, which requires \$e = 1\$. A perfectly inelastic impact has \$e = 0\$.",
    "A projectile is fired at \$40\$ m/s at \$30^{\\circ}\$ to the horizontal. Taking \$g = 10\$ m/s\$^2\$, find the greatest height it reaches.",
    "A projectile is launched with speed \$20\$ m/s at \$45^{\\circ}\$ to the horizontal. Taking \$g = 10\$ m/s\$^2\$, find its horizontal range.",
    "A resultant force of \$24\$ N acts on a body, producing an acceleration of \$6\$ m/s\$^2\$. Find the mass of the body.",
    "A stone is released from rest at a height of \$45\$ m. Taking \$g = 10\$ m/s\$^2\$, find the time it takes to reach the ground.",
    "A vector makes angles \$\\alpha\$, \$\\beta\$ and \$\\gamma\$ with the positive \$x\$, \$y\$ and \$z\$ axes respectively. Its direction cosines are:",
    "Acceleration is \$a = \\dfrac{d^{2}s}{dt^{2}} = 6t-12\$. At \$t=4\$: \$a = 24-12 = 12\$ m/s\$^{2}\$.",
    "According to Hooke's law, the tension in an elastic string stretched beyond its natural length is:",
    "Add corresponding components: \$(2+1)\\mathbf{i} + (-1+4)\\mathbf{j} + (3-2)\\mathbf{k} = 3\\mathbf{i} + 3\\mathbf{j} + \\mathbf{k}\$.",
    "At the highest point \$v=0\$. Using \$v^{2} = u^{2} - 2gh\$: \$0 = 400 - 20h\$, so \$h = 20\$ m.",
    "Both products always yield a scalar quantity",
    "Both products always yield a vector quantity",
    "By Newton's second law, \$F = ma = (5)(3) = 15\$ N.",
    "By the right-handed convention for the standard basis vectors, \$\\mathbf{i} \\times \\mathbf{j} = \\mathbf{k}\$.",
    "Comparing \$y^{2}=12x\$ with the standard form \$y^{2}=4ax\$ gives \$4a=12\$, so \$a=3\$. The focus of \$y^{2}=4ax\$ is at \$(a,0)\$, which is \$(3,0)\$.",
    "Comparing with \$\\ddot{x} = -\\omega^{2}x\$ gives \$\\omega^{2}=16\$, so \$\\omega = 4\$. The period is \$T = \\dfrac{2\\pi}{\\omega} = \\dfrac{2\\pi}{4} = \\dfrac{\\pi}{2}\$ s.",
    "Comparing with the standard form \$(x-a)^{2}+(y-b)^{2}=r^{2}\$: \$a=2\$, \$b=-3\$ and \$r^{2}=25\$, so the centre is \$(2,-3)\$ and the radius is \$5\$.",
    "Differentiate each component separately with respect to \$t\$: \$\\dfrac{d}{dt}(t^{2}) = 2t\$, \$\\dfrac{d}{dt}(3t) = 3\$, and \$\\dfrac{d}{dt}(\\sin t) = \\cos t\$.",
    "Differentiating \$y^{2}=8x\$ implicitly gives \$2y\\dfrac{dy}{dx}=8\$, so \$\\dfrac{dy}{dx} = \\dfrac{4}{y}\$. At the point \$(2,4)\$ this is \$\\dfrac{4}{4} = 1\$.",
    "Differentiating componentwise: \$\\dfrac{d}{dt}(\\cos t) = -\\sin t\$, \$\\dfrac{d}{dt}(\\sin t) = \\cos t\$, and \$\\dfrac{d}{dt}(t) = 1\$.",
    "Evaluate \$\\displaystyle\\int_{0}^{1} \\left(2t\\,\\mathbf{i} + 3t^2\\mathbf{j} + \\mathbf{k}\\right)\\,dt\$.",
    "Evaluate \$\\displaystyle\\int_{0}^{1}\\left(6t^2\\mathbf{i} + 4t\\mathbf{j} + 2\\mathbf{k}\\right)dt\$.",
    "Evaluate \$\\mathbf{i} \\times \\mathbf{j}\$.",
    "Expanding the determinant, the \$\\mathbf{i}\$ component is \$(1)(2)-(-1)(3) = 5\$, the \$\\mathbf{j}\$ component is \$-[(2)(2)-(-1)(1)] = -5\$, and the \$\\mathbf{k}\$ component is \$(2)(3)-(1)(1) = 5\$. So \$\\mathbf{a} \\times \\mathbf{b} = 5\\mathbf{i} - 5\\mathbf{j} + 5\\mathbf{k}\$.",
    "Find the angle between the vectors \$\\mathbf{a} = \\mathbf{i}\$ and \$\\mathbf{b} = \\mathbf{i} + \\mathbf{j}\$.",
    "Find the area of the parallelogram whose adjacent sides are \$\\mathbf{a} = 3\\mathbf{i}\$ and \$\\mathbf{b} = 4\\mathbf{j}\$.",
    "Find the area of the triangle with vertices \$(0, 0)\$, \$(4, 0)\$ and \$(0, 3)\$.",
    "Find the centre and radius of the circle \$(x - 2)^2 + (y + 3)^2 = 25\$.",
    "Find the centre and radius of the circle \$x^2 + y^2 - 4x + 6y - 12 = 0\$.",
    "Find the distance between the points \$(3, 4)\$ and \$(7, 1)\$.",
    "Find the distance between the points \$A(1, 2)\$ and \$B(4, 6)\$.",
    "Find the equation of the circle with centre \$(1, -2)\$ and radius \$3\$.",
    "Find the equation of the normal to the curve \$y = x^2\$ at the point \$(2, 4)\$.",
    "Find the equation of the straight line through the point \$(2, 5)\$ with gradient \$3\$.",
    "Find the equation of the tangent to the circle \$x^2 + y^2 = 25\$ at the point \$(3, 4)\$.",
    "Find the equation of the tangent to the curve \$y = x^2\$ at the point \$(2, 4)\$.",
    "Find the gradient of the line joining \$A(1, 3)\$ and \$B(5, 7)\$.",
    "Find the gradient of the tangent to the curve \$y = x^3\$ at the point \$(1, 1)\$.",
    "Find the gradient of the tangent to the parabola \$y^2 = 8x\$ at the point \$(2, 4)\$.",
    "Find the length of the tangent drawn from the point \$(5, 0)\$ to the circle \$x^2 + y^2 = 9\$.",
    "Find the magnitude of \$\\mathbf{a} = 6\\mathbf{i} - 2\\mathbf{j} + 3\\mathbf{k}\$.",
    "Find the magnitude of the vector \$\\mathbf{a} = 2\\mathbf{i} + 3\\mathbf{j} + 6\\mathbf{k}\$.",
    "Find the magnitude of the vector \$\\mathbf{a} = 3\\mathbf{i} - 4\\mathbf{j}\$.",
    "Find the midpoint of the line segment joining \$A(2, 3)\$ and \$B(8, 7)\$.",
    "Find the momentum of a body of mass \$4\$ kg moving with velocity \$12\$ m/s.",
    "Find the perpendicular distance from the origin to the line \$5x + 12y - 26 = 0\$.",
    "Find the perpendicular distance from the point \$(1, 2)\$ to the line \$3x + 4y - 5 = 0\$.",
    "Find the radius of the circle \$x^2 + y^2 - 6x + 8y = 0\$.",
    "Find the unit vector in the direction of \$\\mathbf{a} = \\mathbf{i} + 2\\mathbf{j} + 2\\mathbf{k}\$.",
    "First \$\\dfrac{d\\mathbf{r}}{dt} = 2t\\mathbf{i} + 3t^{2}\\mathbf{j}\$. Differentiating again gives \$\\dfrac{d^{2}\\mathbf{r}}{dt^{2}} = 2\\mathbf{i} + 6t\\mathbf{j}\$.",
    "First \$|\\mathbf{a}| = \\sqrt{1^{2}+2^{2}+2^{2}} = \\sqrt{9} = 3\$. The unit vector is \$\\hat{\\mathbf{a}} = \\dfrac{\\mathbf{a}}{|\\mathbf{a}|} = \\dfrac{1}{3}(\\mathbf{i}+2\\mathbf{j}+2\\mathbf{k})\$.",
    "For \$x^{2}+y^{2}+2gx+2fy+c=0\$ the centre is \$(-g,-f)\$ and the radius is \$\\sqrt{g^{2}+f^{2}-c}\$. Here \$2g=-4\$ so \$g=-2\$; \$2f=6\$ so \$f=3\$; \$c=-12\$. The centre is \$(2,-3)\$ and the radius is \$\\sqrt{4+9+12} = \\sqrt{25} = 5\$.",
    "For \$y^{2}=4ax\$ the latus rectum has length \$4a\$. Here \$4a=16\$, so the latus rectum is \$16\$ units long.",
    "For a hyperbola, \$b^{2}=a^{2}(e^{2}-1)\$, so \$e = \\sqrt{1+\\dfrac{b^{2}}{a^{2}}}\$. With \$a^{2}=16\$ and \$b^{2}=9\$: \$e = \\sqrt{1+\\dfrac{9}{16}} = \\sqrt{\\dfrac{25}{16}} = \\dfrac{5}{4}\$.",
    "For a particle moving along a curved path, the direction of the instantaneous velocity vector at any point is:",
    "For a projectile launched at a fixed speed over level ground, the horizontal range is greatest when the angle of projection is:",
    "For a simple pendulum of length \$L\$ undergoing small oscillations, the period is given by:",
    "For circular motion the linear speed is \$v = r\\omega = (3)(4) = 12\$ m/s.",
    "For perpendicular lines the product of the gradients is \$-1\$, so the required gradient is \$m_2 = -\\dfrac{1}{m_1} = -\\dfrac{1}{2/3} = -\\dfrac{3}{2}\$.",
    "For small oscillations the pendulum performs simple harmonic motion with \$\\omega^{2} = \\dfrac{g}{L}\$, so the period is \$T = \\dfrac{2\\pi}{\\omega} = 2\\pi\\sqrt{\\dfrac{L}{g}}\$.",
    "For smooth spheres the impulse acts only along the line of centres (the common normal). With no tangential impulse, the tangential velocity components are unaffected by the impact; only the normal components change.",
    "For the direct impact of two smooth elastic spheres with coefficient of restitution \$e\$, Newton's experimental law states that the relative velocity of separation is:",
    "For the ellipse \$\\dfrac{x^2}{25} + \\dfrac{y^2}{9} = 1\$, find the coordinates of the foci.",
    "For the ellipse \$\\dfrac{x^2}{25} + \\dfrac{y^2}{9} = 1\$, find the eccentricity.",
    "For the ellipse \$\\dfrac{x^2}{25} + \\dfrac{y^2}{9} = 1\$, find the length of the major axis.",
    "For the hyperbola \$\\dfrac{x^2}{16} - \\dfrac{y^2}{9} = 1\$, find the eccentricity.",
    "For the hyperbola \$\\dfrac{x^2}{16} - \\dfrac{y^2}{9} = 1\$, find the equations of the asymptotes.",
    "For the parabola \$y^2 = 12x\$, find the coordinates of the focus.",
    "For the parabola \$y^2 = 12x\$, find the equation of the directrix.",
    "For the parabola \$y^2 = 16x\$, find the length of the latus rectum.",
    "For uniform circular motion the acceleration is directed toward the centre with magnitude \$a = r\\omega^{2} = (3)(4)^{2} = 48\$ m/s\$^{2}\$.",
    "For what value of \$k\$ are \$\\mathbf{a} = 2\\mathbf{i} + k\\mathbf{j} + \\mathbf{k}\$ and \$\\mathbf{b} = 3\\mathbf{i} - \\mathbf{j} + 4\\mathbf{k}\$ perpendicular?",
    "For what value of \$k\$ are the vectors \$\\mathbf{a} = 3\\mathbf{i} + k\\mathbf{j}\$ and \$\\mathbf{b} = 6\\mathbf{i} + 10\\mathbf{j}\$ parallel?",
    "From \$F = ma\$, the mass is \$m = \\dfrac{F}{a} = \\dfrac{24}{6} = 4\$ kg.",
    "Given \$\\mathbf{a} = 2\\mathbf{i} + 3\\mathbf{j}\$ and \$\\mathbf{b} = 3\\mathbf{i} - 2\\mathbf{j}\$, what can be concluded about these vectors?",
    "Given \$\\mathbf{a} = 2\\mathbf{i} + \\mathbf{j} - \\mathbf{k}\$ and \$\\mathbf{b} = \\mathbf{i} + 3\\mathbf{j} + 2\\mathbf{k}\$, find \$\\mathbf{a} \\times \\mathbf{b}\$.",
    "Given \$\\mathbf{a} = 2\\mathbf{i} - \\mathbf{j} + 3\\mathbf{k}\$ and \$\\mathbf{b} = \\mathbf{i} + 4\\mathbf{j} - 2\\mathbf{k}\$, find \$3\\mathbf{a} - 2\\mathbf{b}\$.",
    "Given \$\\mathbf{a} = 2\\mathbf{i} - \\mathbf{j} + 3\\mathbf{k}\$ and \$\\mathbf{b} = \\mathbf{i} + 4\\mathbf{j} - 2\\mathbf{k}\$, find \$\\mathbf{a} + \\mathbf{b}\$.",
    "Given \$\\mathbf{a} = 2\\mathbf{i} - \\mathbf{j} + 3\\mathbf{k}\$ and \$\\mathbf{b} = \\mathbf{i} + 4\\mathbf{j} - 2\\mathbf{k}\$, find \$\\mathbf{a} - \\mathbf{b}\$.",
    "Given \$\\mathbf{a} = 3\\mathbf{i} - \\mathbf{j} + 2\\mathbf{k}\$ and \$\\mathbf{b} = 2\\mathbf{i} + 4\\mathbf{j} - \\mathbf{k}\$, find \$\\mathbf{a} \\cdot \\mathbf{b}\$.",
    "Given \$\\mathbf{a} = 5\\mathbf{i} - 3\\mathbf{j} + 2\\mathbf{k}\$ and \$\\mathbf{b} = -2\\mathbf{i} + \\mathbf{j} + 4\\mathbf{k}\$, find \$2\\mathbf{a} + \\mathbf{b}\$.",
    "Given \$\\mathbf{a} = \\mathbf{i} + 2\\mathbf{j} + 3\\mathbf{k}\$ and \$\\mathbf{b} = 4\\mathbf{i} - 5\\mathbf{j} + 6\\mathbf{k}\$, find \$\\mathbf{a} \\cdot \\mathbf{b}\$.",
    "Given \$\\mathbf{a} = \\mathbf{i} + 2\\mathbf{j}\$ and \$\\mathbf{b} = 3\\mathbf{j} + \\mathbf{k}\$, find \$\\mathbf{a} \\times \\mathbf{b}\$.",
    "Given \$\\mathbf{r}(t) = \\cos t\\,\\mathbf{i} + \\sin t\\,\\mathbf{j} + t\\mathbf{k}\$, find \$\\dfrac{d\\mathbf{r}}{dt}\$.",
    "Given \$\\mathbf{r}(t) = t^2\\mathbf{i} + 3t\\mathbf{j} + \\sin t\\,\\mathbf{k}\$, find \$\\dfrac{d\\mathbf{r}}{dt}\$.",
    "Given \$\\mathbf{r}(t) = t^2\\mathbf{i} + t^3\\mathbf{j}\$, find \$\\dfrac{d^2\\mathbf{r}}{dt^2}\$.",
    "Given \$\\mathbf{r}(t) = t^3\\mathbf{i} + t^2\\mathbf{j} + t\\mathbf{k}\$, evaluate \$\\dfrac{d\\mathbf{r}}{dt}\$ at \$t = 1\$.",
    "Given the points \$A(1, 2, 3)\$ and \$B(4, 6, 3)\$, find the vector \$\\overrightarrow{AB}\$.",
    "Gravity acts vertically only, so there is no horizontal acceleration. The horizontal velocity component is therefore unchanged throughout the flight.",
    "Here \$2g=-6\$ so \$g=-3\$; \$2f=8\$ so \$f=4\$; and \$c=0\$. The radius is \$\\sqrt{g^{2}+f^{2}-c} = \\sqrt{9+16-0} = \\sqrt{25} = 5\$.",
    "Here \$a^{2}=25\$ and \$b^{2}=9\$, so \$a=5\$ and \$b=3\$. The eccentricity satisfies \$b^{2}=a^{2}(1-e^{2})\$, giving \$e = \\sqrt{1-\\dfrac{b^{2}}{a^{2}}} = \\sqrt{1-\\dfrac{9}{25}} = \\sqrt{\\dfrac{16}{25}} = \\dfrac{4}{5}\$.",
    "Hooke's law states that the tension is proportional to the extension: \$T = \\dfrac{\\lambda e}{L}\$, where \$e\$ is the extension, \$L\$ the natural length and \$\\lambda\$ the modulus of elasticity.",
    "If \$l\$, \$m\$ and \$n\$ are the direction cosines of a vector, then \$l^2 + m^2 + n^2\$ equals:",
    "If two non-zero vectors \$\\mathbf{a}\$ and \$\\mathbf{b}\$ satisfy \$\\mathbf{a} \\times \\mathbf{b} = \\mathbf{0}\$, then the vectors must be:",
    "Impulse equals the change in momentum: \$I = m(v-u) = 3(8-2) = 18\$ N s.",
    "In a perfectly elastic direct impact between two smooth spheres, the coefficient of restitution has the value:",
    "In simple harmonic motion the speed is greatest at the centre, where \$v_{\\max} = a\\omega = (5)(4) = 20\$ m/s.",
    "Integrate each component over \$[0,1]\$: \$\\int_0^1 2t\\,dt = 1\$, \$\\int_0^1 3t^{2}\\,dt = 1\$, and \$\\int_0^1 1\\,dt = 1\$. So the result is \$\\mathbf{i} + \\mathbf{j} + \\mathbf{k}\$.",
    "Momentum is \$p = mv = (4)(12) = 48\$ kg m/s.",
    "Momentum is conserved: \$(2)(6) + (4)(0) = (2+4)v\$, so \$12 = 6v\$ and \$v = 2\$ m/s.",
    "Multiply corresponding components and add: \$\\mathbf{a} \\cdot \\mathbf{b} = (1)(4) + (2)(-5) + (3)(6) = 4 - 10 + 18 = 12\$.",
    "Neglecting air resistance, the horizontal component of a projectile's velocity during its flight:",
    "Newton's experimental law gives \$v_2 - v_1 = -e(u_2 - u_1)\$: the speed of separation is \$e\$ times the speed of approach, where the coefficient of restitution \$e\$ satisfies \$0 \\leq e \\leq 1\$.",
    "Newton's first law (the law of inertia) says a body's state of rest or uniform motion persists unless a net external force acts on it to change that state.",
    "Newton's first law of motion states that a body remains at rest, or continues to move with uniform velocity in a straight line, unless:",
    "Newton's second law of motion states that the rate of change of momentum of a body is:",
    "Newton's second law states that the rate of change of momentum is proportional to the applied force and occurs along the line of that force, which gives \$F = ma\$ for constant mass.",
    "Newton's third law of motion states that:",
    "Newton's third law states that when one body exerts a force on a second, the second exerts a force of equal magnitude and opposite direction on the first.",
    "No scalar \$\\lambda\$ satisfies \$\\mathbf{i} = \\lambda\\mathbf{j}\$, since the two point along different axes. Neither is a multiple of the other, so they are linearly independent.",
    "Parallel vectors satisfy \$\\mathbf{a} = \\lambda\\mathbf{b}\$. Comparing \$\\mathbf{i}\$ components, \$3 = 6\\lambda\$ so \$\\lambda = \\dfrac{1}{2}\$. Comparing \$\\mathbf{j}\$ components, \$k = 10\\lambda = 10 \\cdot \\dfrac{1}{2} = 5\$.",
    "Perpendicular lines satisfy \$m_1 m_2 = -1\$; equal gradients (\$m_1 = m_2\$) instead characterise parallel lines.",
    "Perpendicular vectors have zero scalar product: \$(2)(3) + (k)(-1) + (1)(4) = 0\$, i.e. \$6 - k + 4 = 0\$, giving \$k = 10\$.",
    "Simple harmonic motion is defined by \$\\ddot{x} = -\\omega^{2}x\$: the acceleration is proportional to the displacement and the minus sign makes it always point back toward the fixed centre.",
    "Since \$R = \\dfrac{u^{2}\\sin 2\\theta}{g}\$, the range is greatest when \$\\sin 2\\theta\$ is greatest, i.e. \$\\sin 2\\theta = 1\$, giving \$2\\theta = 90^{\\circ}\$ and \$\\theta = 45^{\\circ}\$.",
    "Since \$a^{2}=25 > b^{2}=9\$, the major axis lies along the \$x\$-axis and has length \$2a = 2(5) = 10\$.",
    "Since \$|\\mathbf{a} \\times \\mathbf{b}| = |\\mathbf{a}||\\mathbf{b}|\\sin\\theta\$, a vanishing vector product between non-zero vectors forces \$\\sin\\theta = 0\$, i.e. \$\\theta = 0^{\\circ}\$ or \$180^{\\circ}\$ -- the vectors are parallel.",
    "Speed is the magnitude of the velocity: \$|\\mathbf{v}| = \\sqrt{6^{2}+6^{2}} = \\sqrt{72} = 6\\sqrt{2}\$ m/s.",
    "Substituting \$(0,0)\$: \$0 + 0 - 0 + 0 = 0\$, which satisfies the equation. In general a circle \$x^{2}+y^{2}+2gx+2fy+c=0\$ passes through the origin exactly when \$c=0\$, as here.",
    "Substituting \$a=1\$, \$b=-2\$ and \$r=3\$ into \$(x-a)^{2}+(y-b)^{2}=r^{2}\$ gives \$(x-1)^{2}+(y+2)^{2}=9\$.",
    "Subtract corresponding components: \$(2-1)\\mathbf{i} + (-1-4)\\mathbf{j} + (3-(-2))\\mathbf{k} = \\mathbf{i} - 5\\mathbf{j} + 5\\mathbf{k}\$.",
    "Taking \$g = 10\$ m/s\$^2\$, find the weight of a body of mass \$8\$ kg.",
    "Taking the initial direction as positive, the final velocity is \$-3\$ m/s. The impulse is \$m(v-u) = 2(-3-5) = -16\$ N s, so its magnitude is \$16\$ N s.",
    "The \$\\mathbf{i}\$ component is \$(2)(1)-(0)(3) = 2\$; the \$\\mathbf{j}\$ component is \$-[(1)(1)-(0)(0)] = -1\$; the \$\\mathbf{k}\$ component is \$(1)(3)-(2)(0) = 3\$. So \$\\mathbf{a}\\times\\mathbf{b} = 2\\mathbf{i} - \\mathbf{j} + 3\\mathbf{k}\$.",
    "The area of the parallelogram equals \$|\\mathbf{a} \\times \\mathbf{b}|\$. Here \$\\mathbf{a} \\times \\mathbf{b} = 12\\mathbf{k}\$, so the area is \$12\$.",
    "The asymptotes of \$\\dfrac{x^{2}}{a^{2}}-\\dfrac{y^{2}}{b^{2}}=1\$ are \$y = \\pm\\dfrac{b}{a}x\$. With \$a=4\$ and \$b=3\$, they are \$y = \\pm\\dfrac{3}{4}x\$.",
    "The centre is the midpoint of the diameter: \$\\left(\\dfrac{0+4}{2},\\dfrac{0+6}{2}\\right) = (2,3)\$. The radius is the distance from the centre to an endpoint: \$\\sqrt{(4-2)^{2}+(6-3)^{2}} = \\sqrt{4+9} = \\sqrt{13}\$.",
    "The circle \$x^2 + y^2 - 6x + 8y = 0\$ passes through which of these points?",
    "The coefficient of restitution is \$e = \\dfrac{\\text{speed of separation}}{\\text{speed of approach}} = \\dfrac{3}{6} = 0.5\$.",
    "The direction cosines are precisely the cosines of the angles the vector makes with the coordinate axes: \$l=\\cos\\alpha\$, \$m=\\cos\\beta\$, \$n=\\cos\\gamma\$.",
    "The direction cosines are the components of a unit vector, so their squares sum to the square of that unit vector's magnitude: \$l^{2}+m^{2}+n^{2} = 1\$ for every vector.",
    "The direction cosines are the components of the unit vector: \$l = \\dfrac{a_1}{|\\mathbf{a}|}\$, \$m = \\dfrac{a_2}{|\\mathbf{a}|}\$, \$n = \\dfrac{a_3}{|\\mathbf{a}|}\$. With \$|\\mathbf{a}| = 3\$: \$l = \\dfrac{1}{3}\$, \$m = \\dfrac{2}{3}\$, \$n = \\dfrac{2}{3}\$.",
    "The direction cosines of the vector \$\\mathbf{a} = \\mathbf{i} + 2\\mathbf{j} + 2\\mathbf{k}\$ are:",
    "The distance from \$(x_0,y_0)\$ to \$ax+by+c=0\$ is \$\\dfrac{|ax_0+by_0+c|}{\\sqrt{a^{2}+b^{2}}} = \\dfrac{|3(1)+4(2)-5|}{\\sqrt{9+16}} = \\dfrac{6}{5}\$.",
    "The eccentricity classifies the conic: \$e<1\$ gives an ellipse, \$e=1\$ a parabola, and \$e>1\$ a hyperbola (a circle is the special case \$e=0\$).",
    "The gradient is \$m = \\dfrac{y_2-y_1}{x_2-x_1} = \\dfrac{7-3}{5-1} = \\dfrac{4}{4} = 1\$.",
    "The magnitude is \$|\\mathbf{a}| = \\sqrt{3^{2}+(-4)^{2}} = \\sqrt{9+16} = \\sqrt{25} = 5\$.",
    "The midpoint is \$\\left(\\dfrac{x_1+x_2}{2}, \\dfrac{y_1+y_2}{2}\\right) = \\left(\\dfrac{2+8}{2}, \\dfrac{3+7}{2}\\right) = (5, 5)\$.",
    "The normal to a circle at any point on its circumference always passes through:",
    "The particle is at rest when \$v = 3t^{2}-12t+9 = 0\$, i.e. \$3(t-1)(t-3)=0\$, which gives \$t=1\$ s and \$t=3\$ s.",
    "The range is \$R = \\dfrac{u^{2}\\sin 2\\theta}{g}\$. With \$u=20\$, \$\\theta=45^{\\circ}\$ (so \$\\sin 90^{\\circ}=1\$) and \$g=10\$: \$R = \\dfrac{400}{10} = 40\$ m.",
    "The resultant force is \$50 - 20 = 30\$ N. By Newton's second law, \$a = \\dfrac{F}{m} = \\dfrac{30}{10} = 3\$ m/s\$^{2}\$.",
    "The scalar (dot) product \$\\mathbf{a}\\cdot\\mathbf{b} = |\\mathbf{a}||\\mathbf{b}|\\cos\\theta\$ is a number, whereas the vector (cross) product produces a vector perpendicular to both \$\\mathbf{a}\$ and \$\\mathbf{b}\$.",
    "The scalar product yields a scalar, while the vector product yields a vector",
    "The scalar product yields a vector, while the vector product yields a scalar",
    "The tangent at a point on a circle is perpendicular to the radius drawn to that point. The normal is perpendicular to the tangent, so it lies along that radius and therefore passes through the centre.",
    "The tangent gradient at \$(2,4)\$ is \$4\$, so the normal gradient is \$-\\dfrac{1}{4}\$. Then \$y-4 = -\\dfrac{1}{4}(x-2)\$, giving \$y = -\\dfrac{1}{4}x + \\dfrac{1}{2} + 4 = -\\dfrac{1}{4}x + \\dfrac{9}{2}\$.",
    "The tangent length from \$(x_0,y_0)\$ to \$x^{2}+y^{2}=r^{2}\$ is \$\\sqrt{x_0^{2}+y_0^{2}-r^{2}} = \\sqrt{25+0-9} = \\sqrt{16} = 4\$.",
    "The tangent to \$x^{2}+y^{2}=r^{2}\$ at the point \$(x_1,y_1)\$ on the circle is \$xx_1 + yy_1 = r^{2}\$. With \$(x_1,y_1)=(3,4)\$ and \$r^{2}=25\$: \$3x+4y=25\$.",
    "The time to reach the top is \$\\dfrac{u}{g} = \\dfrac{20}{10} = 2\$ s, and by symmetry the descent takes the same time. The total time is \$2 \\times 2 = 4\$ s.",
    "The vertical component of the initial velocity is \$u\\sin\\theta = 40\\sin 30^{\\circ} = 20\$ m/s. The greatest height is \$\\dfrac{(u\\sin\\theta)^{2}}{2g} = \\dfrac{400}{20} = 20\$ m.",
    "They are both unit vectors, since each has magnitude one",
    "They are equal, since both are standard basis vectors",
    "They are identical, since they have equal magnitudes",
    "They are linearly dependent, since both have magnitude one",
    "They are linearly dependent, since one is a scalar multiple of the other",
    "They are linearly independent, since neither is a scalar multiple of the other",
    "They are parallel, since their scalar product is zero",
    "They are perpendicular, since their scalar product is zero",
    "They are perpendicular, since their scalar product vanishes",
    "They are perpendicular, since their vector product is zero",
    "Two lines have gradients \$m_1\$ and \$m_2\$. The lines are perpendicular if and only if:",
    "Two spheres approach each other along a line with relative speed \$6\$ m/s and separate with relative speed \$3\$ m/s. Find the coefficient of restitution.",
    "Using \$\\text{Area} = \\dfrac{1}{2}|x_1(y_2-y_3) + x_2(y_3-y_1) + x_3(y_1-y_2)|\$: \$\\dfrac{1}{2}|0(0-3) + 4(3-0) + 0(0-0)| = \\dfrac{1}{2}(12) = 6\$.",
    "Using \$h = \\dfrac{1}{2}gt^{2}\$ with \$u=0\$: \$45 = \\dfrac{1}{2}(10)t^{2} = 5t^{2}\$, so \$t^{2}=9\$ and \$t=3\$ s.",
    "Using \$s = ut + \\dfrac{1}{2}at^{2}\$: \$s = 5(4) + \\dfrac{1}{2}(3)(16) = 20 + 24 = 44\$ m.",
    "Using \$v = u + at\$ with \$u=5\$, \$a=3\$ and \$t=4\$: \$v = 5 + 3(4) = 5+12 = 17\$ m/s.",
    "Using \$v = u + at\$: \$30 = 10 + 4a\$, so \$4a = 20\$ and \$a = 5\$ m/s\$^{2}\$.",
    "Using \$v^{2} = u^{2} + 2as\$ with \$v=0\$, \$u=20\$ and \$a=-5\$: \$0 = 400 - 10s\$, so \$s = 40\$ m.",
    "Using \$y - y_1 = m(x - x_1)\$: \$y - 5 = 3(x - 2)\$, so \$y - 5 = 3x - 6\$, giving \$y = 3x - 1\$.",
    "Velocity is \$\\dfrac{d\\mathbf{r}}{dt}\$, the limit of a chord direction as the time interval shrinks to zero. That limiting direction is the tangent to the path, so the velocity is always tangential.",
    "Velocity is \$\\mathbf{v} = \\dfrac{d\\mathbf{r}}{dt} = 6t\\mathbf{i} + 6t^{2}\\mathbf{j}\$. At \$t=1\$: \$\\mathbf{v} = 6\\mathbf{i} + 6\\mathbf{j}\$.",
    "Velocity is \$v = \\dfrac{ds}{dt} = 3t^{2}-12t+9\$. At \$t=4\$: \$v = 3(16)-12(4)+9 = 48-48+9 = 9\$ m/s.",
    "Weight is the gravitational force on the body: \$W = mg = (8)(10) = 80\$ N.",
    "When two smooth spheres collide obliquely, the components of their velocities along the common tangent at the point of contact are:",
    "Which statement about the scalar and vector products of two vectors is correct?",
    "Which statement correctly describes the vectors \$\\mathbf{a} = 2\\mathbf{i} + 4\\mathbf{j}\$ and \$\\mathbf{b} = \\mathbf{i} + 2\\mathbf{j}\$?",
    "Which statement correctly describes the vectors \$\\mathbf{a} = \\mathbf{i}\$ and \$\\mathbf{b} = \\mathbf{j}\$?",
    "With \$4a=12\$ we have \$a=3\$. The directrix of \$y^{2}=4ax\$ is the line \$x=-a\$, so here it is \$x=-3\$.",
    "With \$a=5\$ and \$e=\\dfrac{4}{5}\$, the foci lie at \$(\\pm ae, 0)\$. Since \$ae = 5 \\cdot \\dfrac{4}{5} = 4\$, the foci are \$(\\pm 4, 0)\$.",
    "a body continues in its state of rest unless acted upon by a force",
    "along the normal to the path at that point",
    "along the tangent to the path at that point",
    "always equal to zero whenever the body is in uniform motion",
    "always exactly equal to the relative velocity of approach",
    "always parallel to the acceleration vector",
    "always reduced to zero immediately after the impact",
    "both of unit magnitude",
    "centre \$(-2, 3)\$, radius \$5\$",
    "centre \$(2, -3)\$, radius \$25\$",
    "centre \$(2, -3)\$, radius \$5\$",
    "centre \$(2, -3)\$, radius \$\\sqrt{12}\$",
    "centre \$(2, 3)\$, radius \$13\$",
    "centre \$(2, 3)\$, radius \$5\$",
    "centre \$(2, 3)\$, radius \$\\sqrt{13}\$",
    "centre \$(2, 3)\$, radius \$\\sqrt{26}\$",
    "centre \$(4, -6)\$, radius \$5\$",
    "centre \$(4, 6)\$, radius \$\\sqrt{13}\$",
    "changes direction at the highest point of the path",
    "decreases steadily until it reaches zero at the highest point",
    "directed toward the centre of curvature of the path",
    "directly proportional to the extension produced",
    "entirely independent of the relative velocity of approach",
    "equal in magnitude but opposite in direction",
    "increases steadily as the projectile falls",
    "independent of the direction in which the applied force acts",
    "independent of the extension, depending only on the string's material",
    "inversely proportional to the extension produced",
    "inversely proportional to the magnitude of the applied force",
    "it is acted upon by an external resultant force",
    "it is moving through a perfectly smooth medium",
    "its mass is changed by an external agent",
    "its momentum is equal to zero at that instant",
    "parallel to each other",
    "perpendicular to each other",
    "proportional to the applied force and along that force's direction",
    "proportional to the square of the extension produced",
    "reduced by a factor equal to the coefficient of restitution",
    "remains constant throughout the motion",
    "reversed in direction but unchanged in magnitude",
    "the acceleration produced is proportional to the applied force",
    "the centre of the circle",
    "the magnitude of the vector",
    "the midpoint of the circle's vertical diameter",
    "the origin \$(0, 0)\$",
    "the origin of the coordinate system",
    "the point \$(1, 1)\$",
    "the point \$(3, -4)\$",
    "the point \$(6, 8)\$",
    "the point where the circle meets the x-axis",
    "the square of the magnitude",
    "the sum of the two spheres' initial velocities before impact",
    "the total momentum of an isolated system is always conserved",
    "to every action there is an equal and opposite reaction",
    "unchanged, because the spheres are smooth and exert no tangential impulse",
  ];

  testWidgets(
    'every MTH122 field renders without a hard failure',
    (WidgetTester tester) async {
      final List<String> broken = <String>[];
      for (final String field in fields) {
        await tester.pumpWidget(
          MaterialApp(home: Scaffold(body: MathText(field))),
        );
        await tester.pumpAndSettle();
        final Object? err = tester.takeException();
        final bool hasMath = MathText.hasMath(field);
        final bool mathWidgetExists = !hasMath || find.byType(Math).evaluate().isNotEmpty;
        if (err != null) {
          // A Math widget existing in the tree despite an exception means
          // the formula parsed and built fine -- the exception is a
          // downstream debug-only layout assertion from this test's bare,
          // unconstrained-width harness (unlike the real app's cards/lists),
          // not a parsing failure. A release build never throws on layout
          // overflow, so that case is a soft pass here.
          if (!mathWidgetExists) {
            broken.add('EXCEPTION (\$err): \$field');
          }
          continue;
        }
        if (!mathWidgetExists) {
          broken.add('FALLBACK (no Math widget rendered): \$field');
        }
      }
      expect(broken, isEmpty, reason: broken.join('X'));
    },
  );
}
