// Auto-generated: every individual LaTeX token from the fully-
// latexified MTH 121 question bank, verified against the real
// flutter_math_fork parser -- both that it parses, and that it
// fits without overflowing a single render line.
import 'package:eduvora/core/widgets/math_text.dart';
import 'package:flutter/material.dart';
import 'package:flutter_math_fork/flutter_math.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  final List<String> expressions = <String>[
    "(-1, 1)",
    "(-\\infty, 2)",
    "(-\\infty, \\infty)",
    "(-\\infty,-1)",
    "(0, 2)",
    "(1 - x)e^{x} + C",
    "(1)(\\cos{\\left(x \\right)})",
    "(1, \\infty)",
    "(1,2)",
    "(1/2)ln|2x+1| + C",
    "(1/5)e^{5x} + C",
    "(2 x)(\\sin{\\left(x \\right)})",
    "(2 x)(x + 1) + (x^{2})(1)",
    "(2, \\infty)",
    "(2^{2} + 2 = 6)",
    "(3,4)",
    "(\\cos{\\left(x \\right)})(\\cos{\\left(x \\right)})",
    "(\\frac{0 \\left(9 - 6 \\cdot 0 + 0^{2}\\right)}{3}",
    "(\\frac{0^{3}}{3} = 0)",
    "(\\frac{0^{4}}{4} = 0)",
    "(\\frac{1 \\left(-2 + 3 \\cdot 1\\right)}{2}",
    "(\\frac{1 \\left(12 - 1^{2}\\right)}{3}",
    "(\\frac{1^{4}}{4} = \\frac{1}{4})",
    "(\\frac{2^{3}}{3} = \\frac{8}{3})",
    "(\\frac{3 \\cdot 0^{2}}{2})",
    "(\\frac{3 \\left(9 - 6 \\cdot 3 + 3^{2}\\right)}{3}",
    "(\\frac{4 \\left(-2 + 3 \\cdot 4\\right)}{2}",
    "(\\frac{\\left(-1\\right) \\left(12 - \\left(-1\\right)^{2}\\right)}{3}",
    "(\\frac{\\left(-1\\right) \\left(24 + 3 \\left(-1\\right) - 2 \\left(-1\\right)^{2}\\right)}{6})",
    "(\\frac{\\left(-2\\right) \\left(12 - \\left(-2\\right)^{2}\\right)}{3})",
    "(\\frac{\\left(-2\\right) \\left(36 + 3 \\left(-2\\right) - 2 \\left(-2\\right)^{2}\\right)}{6})",
    "(\\frac{\\left(-3\\right) \\left(36 - 3 \\left(-3\\right) - 2 \\left(-3\\right)^{2}\\right)}{6})",
    "(\\left(-1 + 0\\right) e^{0})",
    "(\\left(-1 + 1\\right) e^{1})",
    "(\\left(-1\\right)^{2} + -1 = 0)",
    "(\\sin{\\left(x \\right)})(- \\sin{\\left(x \\right)})",
    "(f \\cdot g)(1)",
    "(f \\cdot g)(1) = -3 \\cdot 3 = -9",
    "(f \\cdot g)(1) = f(1) \\cdot g(1)",
    "(f \\cdot g)(2)",
    "(f \\cdot g)(2) = 6 \\cdot 3 = 18",
    "(f \\cdot g)(2) = f(2) \\cdot g(2)",
    "(f \\cdot g)(3)",
    "(f \\cdot g)(3) = 7 \\cdot 9 = 63",
    "(f \\cdot g)(3) = f(3) \\cdot g(3)",
    "(f \\cdot g)(4)",
    "(f \\cdot g)(4) = 12 \\cdot -1 = -12",
    "(f \\cdot g)(4) = f(4) \\cdot g(4)",
    "(f \\circ g)(-1)",
    "(f \\circ g)(-1) = 0",
    "(f \\circ g)(-1) = f(g(-1))",
    "(f \\circ g)(1)",
    "(f \\circ g)(1) = -4",
    "(f \\circ g)(1) = 3",
    "(f \\circ g)(1) = 4",
    "(f \\circ g)(1) = f(g(1))",
    "(f \\circ g)(2)",
    "(f \\circ g)(2) = 1",
    "(f \\circ g)(2) = 7",
    "(f \\circ g)(2) = f(g(2))",
    "(f \\circ g)(3)",
    "(f \\circ g)(3) = -4",
    "(f \\circ g)(3) = 13",
    "(f \\circ g)(3) = f(g(3))",
    "(f+g)(1)",
    "(f+g)(1) = -3 + 3 = 0",
    "(f+g)(1) = f(1) + g(1)",
    "(f+g)(2)",
    "(f+g)(2) = 6 + 3 = 9",
    "(f+g)(2) = f(2) + g(2)",
    "(f+g)(3)",
    "(f+g)(3) = 7 + 9 = 16",
    "(f+g)(3) = f(3) + g(3)",
    "(f+g)(4)",
    "(f+g)(4) = 12 + -1 = 11",
    "(f+g)(4) = f(4) + g(4)",
    "(u/v)' = \\dfrac{u'v - uv'}{v^2}",
    "(uv)' = u'v + uv'",
    "(x - 1)e^{x} + C",
    "(x \\cos(x) + \\sin(x))/x^2",
    "(x \\cos(x) - \\sin(x))/x^2",
    "(x)(- \\sin{\\left(x \\right)})",
    "(x^{2})(\\cos{\\left(x \\right)})",
    "- 3 \\cos{\\left(x \\right)} + C",
    "- 4 x",
    "- \\cos{\\left(x \\right)} + C",
    "- \\frac{11}{3})",
    "- \\frac{1}{\\sqrt{1 - x^{2}}}",
    "- \\frac{27 x^{4}}{4}",
    "- \\frac{\\cos{\\left(5 x \\right)}}{5} + C",
    "- \\frac{x^{3}}{3}",
    "- \\tan{\\left(x \\right)}",
    "- x \\cos{\\left(x \\right)}",
    "- x \\sin{\\left(x \\right)}",
    "-1",
    "-1 + E",
    "-1 \\leq \\sin(1/x) \\leq 1",
    "-1 and x",
    "-1, 1",
    "-1, 2",
    "-1, 3",
    "-1/(x^2 + 1)",
    "-1/3",
    "-1/4",
    "-1/\\cos(x)^2",
    "-1/\\sqrt{3} < x < 1/\\sqrt{3}",
    "-1/sqrt{1 - x^2}",
    "-1/x^2 + C",
    "-11/3",
    "-12",
    "-125/6",
    "-12\\pi",
    "-15/4",
    "-2",
    "-2 \\cdot 2 x^{1}",
    "-2 \\cdot \\dfrac{x^{2}}{2}",
    "-2 \\cos(2x + 3)",
    "-2 \\sin(2x + 1) + C",
    "-2 and x",
    "-2, 2",
    "-2/3",
    "-22/3",
    "-24",
    "-27x^4/4 + 36x^3 - 72x^2 + 64x + C",
    "-2e^{2x - 1}",
    "-2x \\cos(x^2)",
    "-2x^2/(x^4 + 2x^2 + 1)",
    "-3",
    "-3 \\cdot 1 x^{0}",
    "-3 \\cos(3x - 1)",
    "-3 \\cos(5x)/5 + C",
    "-3 \\cos(x)",
    "-3 \\cos(x) + C",
    "-3 \\leq x \\leq 3",
    "-3 \\sin(x) + C",
    "-3 and x",
    "-3/4",
    "-32/3",
    "-39/2",
    "-3x^2/(x^3 - 2)",
    "-4",
    "-4 \\cdot 1 x^{0}",
    "-4/3",
    "-4e^{4x}",
    "-5/(5x - 1)",
    "-5/9",
    "-6",
    "-64\\pi/3",
    "-6x/(3x^2 + 5)",
    "-8",
    "-8/3",
    "-81x^2 + 216x - 144 + C",
    "-81x^4/4 + 108x^3 - 216x^2 + 192x + C",
    "-81x^5/5",
    "-8\\pi",
    "-9",
    "-\\cos(5x)/5 + C",
    "-\\cos(x)",
    "-\\cos(x) + C",
    "-\\ln(2)/2",
    "-\\ln|\\cos(x)|",
    "-\\pi/5",
    "-\\sin(2x + 1)/2 + C",
    "-\\sin(2x)/2",
    "-\\sin(x)",
    "-\\sin(x) + C",
    "-\\sin(x) + \\cos(x)",
    "-\\sin(x)^2",
    "-\\tan(x)",
    "-\\tan(x) + C",
    "-e^{\\sin(x)}\\cos(x)",
    "-x \\cos(x) + C",
    "-x \\cos(x) + \\sin(x) + C",
    "-x \\sin(x)",
    "-x \\sin(x) + \\cos(x)",
    "-x \\sin(x) - \\cos(x) + C",
    "-x^2 \\cos(x)/2 + C",
    "-|x|",
    "-|x| \\leq x\\sin(1/x) \\leq |x|",
    "0",
    "0 - -1",
    "0 - 0",
    "0 to x",
    "0)",
    "0, 2",
    "0, 3",
    "0/0",
    "1",
    "1 + 1 = 2",
    "1 - \\sin(x)",
    "1-\\cos x",
    "1/(3x^2 + 5)",
    "1/(5x - 1)",
    "1/(x + 1)",
    "1/(x^2 + 1)",
    "1/(x^2 + 2x + 1)",
    "1/(x^3 - 2)",
    "1/2",
    "1/3",
    "1/4",
    "1/5",
    "1/\\cos(x)",
    "1/sqrt{1 - x^2}",
    "1/x",
    "1/x^2 + C",
    "10",
    "11",
    "11/3",
    "12",
    "12 \\pi",
    "12 x^{3}",
    "12/5",
    "125/6",
    "1280x^3",
    "128\\pi/3",
    "128x^4",
    "12\\pi",
    "12x^2 - 2 + C",
    "12x^3",
    "12x^4",
    "13",
    "135 x^{4}",
    "1350x^3",
    "135x^4",
    "137/6",
    "14",
    "14 x^{6}",
    "14/3",
    "143",
    "14x^6",
    "14x^7",
    "15/2",
    "15/4",
    "16",
    "16/3",
    "16\\pi",
    "16\\pi/3",
    "18",
    "1875x",
    "19",
    "19/4",
    "2",
    "2 + 2 = 4",
    "2 + 3 = 5",
    "2 + C",
    "2 - 3 = -1",
    "2 \\cdot 1",
    "2 \\cdot 2",
    "2 \\cdot 7 x^{6}",
    "2 \\cdot \\dfrac{x^{2}}{2}",
    "2 \\cos(2x + 3)",
    "2 \\cos{\\left(2 x + 3 \\right)}",
    "2 e^{2 x - 1}",
    "2 x + 2 y(dy/dx) = 0",
    "2 x + 7 = 3",
    "2 x - 6 = 0",
    "2 x \\cos{\\left(x^{2} \\right)}",
    "2 x e^{x^{2}}",
    "2(x^{3} - 2 x)^{1} \\cdot (3 x^{2} - 2)",
    "2/(x^2 + 1)",
    "2/(x^4 + 2x^2 + 1)",
    "2/3",
    "2/5",
    "20",
    "20 - \\frac{1}{2}",
    "20)",
    "20x^3",
    "21 x^{2}",
    "21x^2 - 4x + 1",
    "21x^3 - 4x^2 + x",
    "22/3",
    "2250x^2",
    "24",
    "243x^5/5",
    "24\\pi",
    "25",
    "25/3",
    "27",
    "27x^4/4 - 36x^3 + 72x^2 - 64x + C",
    "28/3",
    "2\\pi/5",
    "2^{2} + 2 \\cdot 2 + 4 = 12",
    "2e^{2x - 1}",
    "2ln|2x+1| + C",
    "2x",
    "2x + 7 + C",
    "2x \\cos(x)",
    "2x \\cos(x^2)",
    "2x \\sin(x)",
    "2x/(x - 2)",
    "2x/(x^2 + 2x + 1) + 1/(x^2 + 2x + 1)",
    "2x/(x^4 + 2x^2 + 1)",
    "2x^2 + 14x + C",
    "2x^2 + 2x",
    "2x^3 + C",
    "2x^3 - 4x",
    "2x^4 - 2x^2 + C",
    "2x^5/5 + 10x^3/3 + C",
    "2x^6 - 6x + C",
    "2x^7 + 5",
    "3",
    "3 + 3 = 6",
    "3 \\cdot -\\cos(x)",
    "3 \\cdot 2^{2} - 5 \\cdot 2 + 7",
    "3 \\cdot 4 x^{3}",
    "3 \\cdot \\cos(x)",
    "3 \\cdot \\dfrac{x^{3}}{3}",
    "3 \\cos(3x - 1)",
    "3 \\cos(x)",
    "3 \\cos(x) + C",
    "3 \\cos{\\left(3 x - 1 \\right)}",
    "3 \\left(x - 1\\right) \\left(x + 1\\right)",
    "3 \\log(2)/2",
    "3 \\sin(2x + 1)/2 + C",
    "3 \\sin(x)",
    "3 x - 4 = 5",
    "3 x^{2} + 3 y^{2}(dy/dx) = 0",
    "3 x^{2} - 12 = 0",
    "3 x^{2} - 3 = 0",
    "3(x^{2} + 1)^{2} \\cdot (2 x)",
    "3/2",
    "3/4",
    "3/5",
    "30x^4",
    "30x^4 + C",
    "32/3",
    "324x^3 + 1620x^2 + 2700x + 1500 + C",
    "32x^3 - 240x^2 + 600x - 500",
    "33",
    "35/3",
    "36 x^{3}",
    "36x^2",
    "39/2",
    "3x^2",
    "3x^2 + 2x",
    "3x^2 + C",
    "3x^2/(x^2 - 4x + 4) - 4x/(x^2 - 4x + 4)",
    "3x^2/(x^3 - 2)",
    "3x^4",
    "3x^4 + 6x^2 + 3",
    "4",
    "4 \\cdot 1",
    "4 \\cdot \\dfrac{\\sin(4x)}{4x}",
    "4 \\cdot \\dfrac{x^{4}}{4}",
    "4 \\left(-1\\right)",
    "4 x",
    "4 x - 3 = 9",
    "4(2 x - 5)^{3} \\cdot (2)",
    "4/3",
    "4/5",
    "405x^4",
    "41/2",
    "42x - 4",
    "450 x^{3}",
    "450x^3",
    "48",
    "4800x^2",
    "4e^{4x}",
    "4x^3 + 10x + C",
    "4x^3 - 2x + C",
    "5",
    "5 \\cdot 3 - 7",
    "5 \\cdot \\dfrac{x^{3}}{3}",
    "5 \\cos(5x) + C",
    "5 x + 1 = 11",
    "5/(5x - 1)",
    "5/3",
    "5/4",
    "50",
    "5000",
    "55/2",
    "56",
    "5e^{5x} + C",
    "5x^4",
    "5x^5",
    "6",
    "6 - 0",
    "6 - x = 2",
    "6 - x and y",
    "6 \\cdot \\dfrac{x^{6}}{6}",
    "6 x",
    "6 x^{2} - 6 x - 12 = 0",
    "6 x^{5} + 12 x^{3} + 6 x",
    "6 x^{5} - 16 x^{3} + 8 x",
    "625 x",
    "625x",
    "63",
    "64 x",
    "64 x^{3} - 480 x^{2} + 1200 x - 1000",
    "64/3",
    "64\\pi/3",
    "64x^3 - 480x^2 + 1200x - 1000",
    "65/2",
    "6\\pi",
    "6x",
    "6x + C",
    "6x/(3x^2 + 5)",
    "6x^2/(x^4 + 2x^2 + 1)",
    "6x^5 + 12x^3 + 6x",
    "6x^5 - 16x^3 + 8x",
    "6x^5 - 3 + C",
    "6x^5 - 4",
    "6x^6 - 4x",
    "6x^7 + 18x^5 + 18x^3 + 6x",
    "6x^8 - 28x^6 + 40x^4 - 16x^2",
    "7",
    "7 \\cdot 3 x^{2}",
    "72 x^{2}",
    "750 x^{2}",
    "750x^2",
    "7x^3 - 2x^2 + x",
    "8",
    "8 \\pi",
    "8/3",
    "8000x",
    "81x^5/5",
    "84x^5",
    "8\\pi",
    "8x^3",
    "9",
    "9 - x^{2} \\geq 0",
    "9x^4 - 12x^2 + 4",
    "=10",
    "=7",
    "C",
    "F(1) - F(-1)",
    "F(1) - F(0)",
    "F(2) - F(-1)",
    "F(2) - F(-2)",
    "F(2) - F(-3)",
    "F(2) - F(0)",
    "F(3) - F(-2)",
    "F(3) - F(0)",
    "F(4) - F(0)",
    "F(4) - F(1)",
    "F(\\frac{\\pi}{2}) - F(0)",
    "F(x)",
    "F(x) = - \\frac{x^{3}}{3} + 4 x",
    "F(x) = 4 x",
    "F(x) = \\frac{3 x^{2}}{2}",
    "F(x) = \\frac{3 x^{2}}{2} - x",
    "F(x) = \\frac{x^{2}}{2}",
    "F(x) = \\frac{x^{3}}{3}",
    "F(x) = \\frac{x^{3}}{3} - 2 x^{2} + 3 x",
    "F(x) = \\frac{x^{4}}{4}",
    "F(x) = \\frac{x^{5}}{5}",
    "F(x) = x^{2} + x",
    "V",
    "[2, 3)",
    "[3, 4)",
    "[x]",
    "\\cos x - 1",
    "\\cos(2 x + 3) \\cdot (2)",
    "\\cos(2x + 3)",
    "\\cos(2x)",
    "\\cos(3 x - 1) \\cdot (3)",
    "\\cos(3x - 1)",
    "\\cos(5x)/5 + C",
    "\\cos(u) \\cdot u'",
    "\\cos(x)",
    "\\cos(x) + 1",
    "\\cos(x) + C",
    "\\cos(x)/x",
    "\\cos(x)^2",
    "\\cos(x)^{-2}",
    "\\cos(x^2)",
    "\\cos(x^{2}) \\cdot (2 x)",
    "\\cos{\\left(0 \\right)}",
    "\\cos{\\left(2 x \\right)}",
    "\\cos{\\left(x \\right)}",
    "\\cos{\\left(x \\right)} \\, dx",
    "\\cot(x) + C",
    "\\dfrac{(1)(x + 1) - (x)(1)}{(x + 1)^2}",
    "\\dfrac{(2 x)(x - 2) - (x^{2})(1)}{(x - 2)^2}",
    "\\dfrac{(2)(x^{2} + 1) - (2 x + 1)(2 x)}{(x^{2} + 1)^2}",
    "\\dfrac{(\\cos{\\left(x \\right)})(x) - (\\sin{\\left(x \\right)})(1)}{(x)^2}",
    "\\dfrac{- 2 x^{2} - 2 x + 2}{x^{4} + 2 x^{2} + 1}",
    "\\dfrac{- \\sin{\\left(x \\right)}}{\\cos{\\left(x \\right)}}",
    "\\dfrac{1}{-3} \\cdot \\dfrac{u^{4}}{4} + C",
    "\\dfrac{1}{-3} \\int u^{3} \\, du",
    "\\dfrac{1}{2} \\int \\cos(u) \\, du",
    "\\dfrac{1}{2} \\sin(u) + C",
    "\\dfrac{1}{3} \\cdot \\dfrac{u^{5}}{5} + C",
    "\\dfrac{1}{3} \\int u^{4} \\, du",
    "\\dfrac{1}{5} \\int e^u \\, du",
    "\\dfrac{1}{5} e^u + C",
    "\\dfrac{1}{5} e^{5 x} + C",
    "\\dfrac{1}{x^{2} + 2 x + 1}",
    "\\dfrac{2 + \\frac{3}{x}}{5 - \\frac{1}{x} + \\frac{1}{x^{2}}}",
    "\\dfrac{3 + \\frac{1}{x}}{6 + \\frac{5}{x}}",
    "\\dfrac{3 x + 1}{6 x + 5}",
    "\\dfrac{3 x^{2}}{x^{3} - 2}",
    "\\dfrac{4 - \\frac{1}{x^{2}}}{2 + \\frac{7}{x^{3}}}",
    "\\dfrac{5}{5 x - 1}",
    "\\dfrac{6 x}{3 x^{2} + 5}",
    "\\dfrac{\\frac{1}{x} + \\frac{1}{x^{3}}}{1 + \\frac{2}{x^{3}}}",
    "\\dfrac{\\frac{1}{x} + \\frac{3}{x^{2}}}{1 - \\frac{4}{x^{2}}}",
    "\\dfrac{\\left(x - 1\\right) \\left(x + 1\\right)}{x - 1}",
    "\\dfrac{\\left(x - 2\\right) \\left(x + 2\\right)}{x - 2}",
    "\\dfrac{\\left(x - 2\\right) \\left(x + 3\\right)}{x - 2}",
    "\\dfrac{\\left(x - 2\\right) \\left(x^{2} + 2 x + 4\\right)}{x - 2}",
    "\\dfrac{\\left(x - 3\\right) \\left(x + 3\\right)}{x - 3}",
    "\\dfrac{\\left(x - 3\\right) \\left(x - 2\\right)}{x - 2}",
    "\\dfrac{\\sin(3x)}{5x}",
    "\\dfrac{\\sin(4x)}{x}",
    "\\dfrac{d}{dx}[-2 \\cdot x^{2}]",
    "\\dfrac{d}{dx}[-3 \\cdot x^{1}]",
    "\\dfrac{d}{dx}[-4 \\cdot x^{1}]",
    "\\dfrac{d}{dx}[1 - \\cos{\\left(x \\right)}]",
    "\\dfrac{d}{dx}[2 \\cdot x^{7}]",
    "\\dfrac{d}{dx}[3 \\cdot \\sin(x)]",
    "\\dfrac{d}{dx}[3 \\cdot x^{4}]",
    "\\dfrac{d}{dx}[7 \\cdot x^{3}]",
    "\\dfrac{d}{dx}[\\arccos(x)]",
    "\\dfrac{d}{dx}[\\arcsin(x)]",
    "\\dfrac{d}{dx}[\\arctan(x)]",
    "\\dfrac{d}{dx}[\\cos(x)] = -\\sin(x)",
    "\\dfrac{d}{dx}[\\frac{1}{2} \\cdot x^{2}]",
    "\\dfrac{d}{dx}[\\ln(u)]",
    "\\dfrac{d}{dx}[\\ln(u)] = \\dfrac{u'}{u}",
    "\\dfrac{d}{dx}[\\sin(u)]",
    "\\dfrac{d}{dx}[\\sin(x)] = \\cos(x)",
    "\\dfrac{d}{dx}[\\sin{\\left(x \\right)}]",
    "\\dfrac{d}{dx}[\\tan{\\left(x \\right)}]",
    "\\dfrac{d}{dx}[e^u]",
    "\\dfrac{d}{dx}[e^u] = e^u \\cdot u'",
    "\\dfrac{d}{dx}[u^{2}] = 2 u^{1} \\cdot u'",
    "\\dfrac{d}{dx}[u^{3}] = 3 u^{2} \\cdot u'",
    "\\dfrac{d}{dx}[u^{4}] = 4 u^{3} \\cdot u'",
    "\\dfrac{d}{dx}[x - 1] = 1",
    "\\dfrac{d}{dx}[x - 2] = 1",
    "\\dfrac{d}{dx}[x] = 1",
    "\\dfrac{d}{dx}[x^{1}] = 1 x^{0} = 1",
    "\\dfrac{d}{dx}[x^{2} - 1] = 2 x",
    "\\dfrac{d}{dx}[x^{2} - 4] = 2 x",
    "\\dfrac{d}{dx}[x^{2}] = 2 x",
    "\\dfrac{d}{dx}[x^{5}] = 5 x^{4} = 5 x^{4}",
    "\\dfrac{d}{dx}[x^{6}] = 6 x^{5} = 6 x^{5}",
    "\\dfrac{u'v - uv'}{v^2}",
    "\\dfrac{u'}{u}",
    "\\dfrac{x + 3}{x^{2} - 4}",
    "\\dfrac{x \\cos{\\left(x \\right)} - \\sin{\\left(x \\right)}}{x^{2}}",
    "\\dfrac{x \\left(2 x + 3\\right)}{5 x^{2} - x + 1}",
    "\\dfrac{x \\left(4 x^{2} - 1\\right)}{2 x^{3} + 7}",
    "\\dfrac{x^{2} + 1}{x^{3} + 2}",
    "\\dfrac{x^{2} + x - 6}{x - 2}",
    "\\dfrac{x^{2} - 1}{x - 1}",
    "\\dfrac{x^{2} - 4 x}{x^{2} - 4 x + 4}",
    "\\dfrac{x^{2} - 4}{x - 2}",
    "\\dfrac{x^{2} - 5 x + 6}{x - 2}",
    "\\dfrac{x^{2} - 9}{x - 3}",
    "\\dfrac{x^{3} - 8}{x - 2}",
    "\\frac{0}{0}",
    "\\frac{1 \\left(24 + 3 \\cdot 1 - 2 \\cdot 1^{2}\\right)}{6}",
    "\\frac{11}{3}",
    "\\frac{11}{3} - - \\frac{11}{3}",
    "\\frac{11}{3})",
    "\\frac{125}{6}",
    "\\frac{15}{4}",
    "\\frac{15}{4} - 0",
    "\\frac{1^{2} - 1}{1 + 3}",
    "\\frac{1}{2}",
    "\\frac{1}{2} \\cdot 2 x^{1}",
    "\\frac{1}{2})",
    "\\frac{1}{3}",
    "\\frac{1}{3} - 0",
    "\\frac{1}{4}",
    "\\frac{1}{4} - 0",
    "\\frac{1}{\\sqrt{1 - x^{2}}}",
    "\\frac{1}{x^{2} + 1}",
    "\\frac{2 \\cdot 2}{2^{2} + 1}",
    "\\frac{2 \\cdot 4 + 3}{4 - 1}",
    "\\frac{2 \\left(12 - 2^{2}\\right)}{3}",
    "\\frac{2 \\left(36 - 3 \\cdot 2 - 2 \\cdot 2^{2}\\right)}{6}",
    "\\frac{22}{3}",
    "\\frac{2^{3}}{3} - (\\frac{0^{3}}{3})",
    "\\frac{2^{4}}{4} - (\\frac{0^{4}}{4})",
    "\\frac{2}{5}",
    "\\frac{3 \\cdot 4^{2}}{2}",
    "\\frac{3 \\left(36 + 3 \\cdot 3 - 2 \\cdot 3^{2}\\right)}{6}",
    "\\frac{3 x^{2}}{x^{3} - 2}",
    "\\frac{3 x^{4}}{2}",
    "\\frac{32}{3}",
    "\\frac{39}{2}",
    "\\frac{3}{5}",
    "\\frac{3}{5} \\cdot 1",
    "\\frac{3}{5} \\cdot \\dfrac{\\sin(3x)}{3x}",
    "\\frac{4}{5}",
    "\\frac{5}{5 x - 1}",
    "\\frac{6 x}{3 x^{2} + 5}",
    "\\frac{64 \\pi}{3}",
    "\\frac{81 x^{5}}{5}",
    "\\frac{8}{3}",
    "\\frac{8}{3} - 0",
    "\\frac{\\left(-2\\right) \\left(2 + -2\\right)}{-2 + 5}",
    "\\frac{\\log{\\left(x^{2} + 4 \\right)}}{2}",
    "\\frac{\\pi}{5}",
    "\\frac{\\sin^{3}{\\left(x \\right)}}{3}",
    "\\frac{\\sin{\\left(0 \\right)}}{2 \\cdot 0}",
    "\\frac{\\sin{\\left(2 x + 1 \\right)}}{2}",
    "\\frac{\\sin{\\left(x \\right)}}{\\cos{\\left(x \\right)}}",
    "\\frac{x^{2} - 25}{x - 5} = x + 5",
    "\\frac{x^{2}}{2}",
    "\\frac{x^{5}}{5} + \\frac{5 x^{3}}{3} + C",
    "\\frac{x^{8}}{4}",
    "\\infty",
    "\\int",
    "\\int (3x + 5)^4 \\, dx",
    "\\int (4 - 3x)^3 \\, dx",
    "\\int -2 \\cdot x^{1} \\, dx",
    "\\int -3 \\, dx = -3x",
    "\\int 1/x \\, dx",
    "\\int 2 \\cdot x^{1} \\, dx",
    "\\int 2/(2x+1) \\, dx",
    "\\int 2x + 7 \\, dx",
    "\\int 3 \\cdot \\sin(x) \\, dx",
    "\\int 3 \\cdot x^{2} \\, dx",
    "\\int 3 \\sin(x) \\, dx",
    "\\int 3x^2 \\, dx",
    "\\int 4 \\cdot x^{3} \\, dx",
    "\\int 4x^3 - 2x \\, dx",
    "\\int 5 \\cdot x^{2} \\, dx",
    "\\int 6 \\cdot x^{5} \\, dx",
    "\\int 6x^5 - 3 \\, dx",
    "\\int 7 \\, dx = 7x",
    "\\int \\cos(2 x + 1) \\, dx",
    "\\int \\cos(2x + 1) \\, dx",
    "\\int \\cos(x) \\, dx",
    "\\int \\cos(x) \\, dx = \\sin(x)",
    "\\int \\dfrac{1}{u} \\, du",
    "\\int \\dfrac{1}{x} \\, dx",
    "\\int \\dfrac{2}{2 x + 1} \\, dx",
    "\\int \\left(3 x + 5\\right)^{4} \\, dx",
    "\\int \\left(4 - 3 x\\right)^{3} \\, dx",
    "\\int \\sec(x)^2 \\, dx",
    "\\int \\sec^2(x) \\, dx = \\tan(x)",
    "\\int \\sin(5x) \\, dx",
    "\\int \\sin(x) \\, dx",
    "\\int \\sin(x) \\, dx = -\\cos(x)",
    "\\int \\sin{\\left(5 x \\right)} \\, dx",
    "\\int \\sin{\\left(x \\right)} \\, dx",
    "\\int \\tan(x) \\, dx",
    "\\int \\tan(x) \\, dx = -\\ln|\\cos(x)| + C",
    "\\int e^{5 x} \\, dx",
    "\\int e^{5x} \\, dx",
    "\\int f(x) \\, dx",
    "\\int f(x) \\, dx = x^{2} + 7 x + C",
    "\\int f(x) \\, dx = x^{3} + C",
    "\\int f(x) \\, dx = x^{4} - x^{2} + C",
    "\\int f(x) \\, dx = x^{6} - 3 x + C",
    "\\int u \\, dv = uv - \\int v \\, du",
    "\\int x \\, e^{x} \\, dx",
    "\\int x \\cos(x) \\, dx",
    "\\int x \\cos{\\left(x \\right)} \\, dx",
    "\\int x \\sin(x) \\, dx",
    "\\int x \\sin{\\left(x \\right)} \\, dx",
    "\\int x e^{x} \\, dx",
    "\\int x^4 + 5x^2 \\, dx",
    "\\int x^n \\, dx = \\dfrac{x^{n+1}}{n+1}",
    "\\int x^{4} \\, dx = \\dfrac{x^{5}}{5}",
    "\\int xe^{x} \\, dx",
    "\\int_{-1}^{1} - x^{2} + x + 4 \\, dx",
    "\\int_{-1}^{1} 4 - x^2 \\, dx",
    "\\int_{-1}^{1} 4 - x^{2} \\, dx",
    "\\int_{-1}^{1} [(x + 3) - (x^{2} - 1)] \\, dx",
    "\\int_{-1}^{2} 2 x + 1 \\, dx",
    "\\int_{-1}^{2} 2x + 1 \\, dx",
    "\\int_{-2}^{2} 4 - x^{2} \\, dx",
    "\\int_{-2}^{3} - x^{2} + x + 6 \\, dx",
    "\\int_{-2}^{3} [(x + 5) - (x^{2} - 1)] \\, dx",
    "\\int_{-3}^{2} - x^{2} - x + 6 \\, dx",
    "\\int_{-3}^{2} [(6 - x) - (x^{2})] \\, dx",
    "\\int_{0}^{1} 2x(x^2 + 1)^3 \\, dx",
    "\\int_{0}^{1} x \\cdot e^x \\, dx",
    "\\int_{0}^{1} x^3 \\, dx",
    "\\int_{0}^{1} x^{3} \\, dx",
    "\\int_{0}^{2} x/(x^2 + 4) \\, dx",
    "\\int_{0}^{2} x^2 \\, dx",
    "\\int_{0}^{2} x^{2} \\, dx",
    "\\int_{0}^{2} x^{3} \\, dx",
    "\\int_{0}^{3} x^2 - 4x + 3 \\, dx",
    "\\int_{0}^{3} x^{2} - 4 x + 3 \\, dx",
    "\\int_{0}^{4} 3 x \\, dx",
    "\\int_{0}^{pi/2} \\sin(x)^2 \\cos(x) \\, dx",
    "\\int_{1}^{4} 3 x - 1 \\, dx",
    "\\int_{1}^{4} 3x - 1 \\, dx",
    "\\left(-1, 1\\right)",
    "\\left(-1\\right)^{3}",
    "\\left(-5, \\infty\\right)",
    "\\left(-\\infty, - \\frac{\\sqrt{3}}{3}\\right) \\cup \\left(\\frac{\\sqrt{3}}{3}, \\infty\\right)",
    "\\left(-\\infty, -2\\right) \\cup \\left(-2, 2\\right) \\cup \\left(2, \\infty\\right)",
    "\\left(-\\infty, 3\\right) \\cup \\left(3, \\infty\\right)",
    "\\left(2, \\infty\\right)",
    "\\left(x - 1\\right) e^{x} + C",
    "\\left[-1, 4\\right) \\cup \\left(4, \\infty\\right)",
    "\\left[-1, \\infty\\right)",
    "\\left[-3, 3\\right]",
    "\\left[2, \\infty\\right)",
    "\\lim_{x \\to -1} [x^3 - 4x + 1]",
    "\\lim_{x \\to -1} x^{3} - 4 x + 1",
    "\\lim_{x \\to -2} [(x^2 + 2x)/(x + 5)]",
    "\\lim_{x \\to -2} \\frac{x^{2} + 2 x}{x + 5}",
    "\\lim_{x \\to 0} [(1 - \\cos(x))/x^2]",
    "\\lim_{x \\to 0} [(1-cos x)/x]",
    "\\lim_{x \\to 0} [\\sin(3x)/(5x)]",
    "\\lim_{x \\to 0} [\\sin(4x)/x]",
    "\\lim_{x \\to 0} [\\sin(x)/x]",
    "\\lim_{x \\to 0} [x \\cdot \\sin(1/x)]",
    "\\lim_{x \\to 0} \\dfrac{1 - \\cos(x)}{x}",
    "\\lim_{x \\to 0} \\dfrac{\\cos(x) - 1}{x}",
    "\\lim_{x \\to 0} \\dfrac{\\cos{\\left(x \\right)}}{1}",
    "\\lim_{x \\to 0} \\dfrac{\\sin(3x)}{5x}",
    "\\lim_{x \\to 0} \\dfrac{\\sin(4x)}{x}",
    "\\lim_{x \\to 0} \\dfrac{\\sin(kx)}{kx} = 1",
    "\\lim_{x \\to 0} \\dfrac{\\sin{\\left(x \\right)}}{2 x}",
    "\\lim_{x \\to 0} \\frac{1 - \\cos{\\left(x \\right)}}{x^{2}}",
    "\\lim_{x \\to 0} \\frac{1 - \\cos{\\left(x \\right)}}{x}",
    "\\lim_{x \\to 0} \\frac{\\sin{\\left(x \\right)}}{x}",
    "\\lim_{x \\to 0} x\\sin(1/x) = 0",
    "\\lim_{x \\to 1} [(x^2 - 1)/(x + 3)]",
    "\\lim_{x \\to 1} [(x^2 - 1)/(x - 1)]",
    "\\lim_{x \\to 1} \\dfrac{2 x}{1}",
    "\\lim_{x \\to 1} \\frac{x^{2} - 1}{x + 3}",
    "\\lim_{x \\to 1} \\frac{x^{2} - 1}{x - 1}",
    "\\lim_{x \\to 2^+} f(x) = 2^{2} - 1 = 3",
    "\\lim_{x \\to 2^-} f(x) = 3 - 2 = 1",
    "\\lim_{x \\to 2} 3 x^{2} - 5 x + 7",
    "\\lim_{x \\to 2} [(x^2 + x - 6)/(x - 2)]",
    "\\lim_{x \\to 2} [(x^2 - 4)/(x - 2)]",
    "\\lim_{x \\to 2} [(x^2 - 5x + 6)/(x - 2)]",
    "\\lim_{x \\to 2} [(x^3 - 8)/(x - 2)]",
    "\\lim_{x \\to 2} [3x^2 - 5x + 7]",
    "\\lim_{x \\to 2} \\dfrac{2 x}{1}",
    "\\lim_{x \\to 2} \\frac{x^{2} - 4}{x - 2}",
    "\\lim_{x \\to 2⁺}",
    "\\lim_{x \\to 2⁻}",
    "\\lim_{x \\to 3^+} [x] = 3",
    "\\lim_{x \\to 3^-} [x] = 2",
    "\\lim_{x \\to 3} 5 x - 7",
    "\\lim_{x \\to 3} [(x^2 - 9)/(x - 3)]",
    "\\lim_{x \\to 3} [5x - 7]",
    "\\lim_{x \\to 3⁺}",
    "\\lim_{x \\to 3⁻}",
    "\\lim_{x \\to 4} [(2x + 3)/(x - 1)]",
    "\\lim_{x \\to 4} \\frac{2 x + 3}{x - 1}",
    "\\lim_{x \\to 5} f(x) = 5 + 5 = 10",
    "\\lim_{x \\to \\infty} [(2x^2 + 3x)/(5x^2 - x + 1)]",
    "\\lim_{x \\to \\infty} [(3x + 1)/(6x + 5)]",
    "\\lim_{x \\to \\infty} [(4x^3 - x)/(2x^3 + 7)]",
    "\\lim_{x \\to \\infty} [(x + 3)/(x^2 - 4)]",
    "\\lim_{x \\to \\infty} [(x^2 + 1)/(x^3 + 2)]",
    "\\lim_{x \\to \\infty} \\frac{2 x^{2} + 3 x}{5 x^{2} - x + 1}",
    "\\lim_{x \\to \\infty} \\frac{3 x + 1}{6 x + 5}",
    "\\lim_{x \\to \\infty} \\frac{4 x^{3} - x}{2 x^{3} + 7}",
    "\\lim_{x \\to \\infty} \\frac{x + 3}{x^{2} - 4}",
    "\\lim_{x \\to \\infty} \\frac{x^{2} + 1}{x^{3} + 2}",
    "\\ln(2)",
    "\\ln(2)/2",
    "\\ln|2 x + 1| + C",
    "\\ln|\\cos(x)|^{-1}",
    "\\ln|\\sec(x)|",
    "\\ln|\\sec(x)| + C",
    "\\ln|u| + C",
    "\\ln|x| + C",
    "\\log{\\left(2 \\right)}",
    "\\log{\\left(2 \\sqrt{2} \\right)}",
    "\\log{\\left(\\sqrt{2} \\right)}",
    "\\pi \\int_{0}^{1} [x^{2}]^2 \\, dx",
    "\\pi \\int_{0}^{1} x^{4} \\, dx",
    "\\pi \\int_{0}^{3} 4 \\, dx",
    "\\pi \\int_{0}^{3} [2]^2 \\, dx",
    "\\pi \\int_{0}^{4} [\\sqrt{x}]^2 \\, dx",
    "\\pi \\int_{0}^{4} [x]^2 \\, dx",
    "\\pi \\int_{0}^{4} x \\, dx",
    "\\pi \\int_{0}^{4} x^{2} \\, dx",
    "\\pi \\left[4 \\cdot 3 - \\left(4 \\cdot 0\\right)\\right]",
    "\\pi \\left[F(1) - F(0)\\right]",
    "\\pi \\left[F(3) - F(0)\\right]",
    "\\pi \\left[F(4) - F(0)\\right]",
    "\\pi \\left[\\frac{1^{5}}{5} - \\left(\\frac{0^{5}}{5}\\right)\\right]",
    "\\pi \\left[\\frac{4^{2}}{2} - \\left(\\frac{0^{2}}{2}\\right)\\right]",
    "\\pi \\left[\\frac{4^{3}}{3} - \\left(\\frac{0^{3}}{3}\\right)\\right]",
    "\\pi/3",
    "\\pi/5",
    "\\sec(x) + C",
    "\\sec(x)\\tan(x) + C",
    "\\sin(2)",
    "\\sin(2x + 1)/2 + C",
    "\\sin(2x)",
    "\\sin(3)",
    "\\sin(x)",
    "\\sin(x) + C",
    "\\sin(x) + \\cos(x)",
    "\\sin(x) - \\cos(x)",
    "\\sin{\\left(x \\right)}",
    "\\sin{\\left(x \\right)} + C",
    "\\sqrt{x + 5} \\neq 0",
    "\\tan(x)",
    "\\tan(x) + C",
    "\\tan(x) = \\sin(x)/\\cos(x)",
    "\\tan^{2}{\\left(x \\right)} + 1",
    "\\text{(1,2).}",
    "\\text{(3,4).}",
    "\\text{(Squeeze)}",
    "\\text{(does}",
    "\\text{(equivalently}",
    "\\text{(since}",
    "\\text{(so}",
    "\\text{(the}",
    "\\text{(valid}",
    "\\text{(}",
    "\\text{(∞)}",
    "\\text{).}",
    "\\text{):}",
    "\\text{)}",
    "\\text{+}",
    "\\text{,}",
    "\\text{-1}",
    "\\text{-2xe\\textasciicircum{}(x\\textasciicircum{}2)}",
    "\\text{-2}",
    "\\text{-axis}",
    "\\text{.}",
    "\\text{1}",
    "\\text{25,}",
    "\\text{2xe\\textasciicircum{}(x\\textasciicircum{}2)}",
    "\\text{2}",
    "\\text{3}",
    "\\text{9,}",
    "\\text{:}",
    "\\text{;}",
    "\\text{=}",
    "\\text{An}",
    "\\text{Approaching}",
    "\\text{As}",
    "\\text{At}",
    "\\text{Between}",
    "\\text{By}",
    "\\text{Chain}",
    "\\text{Combining}",
    "\\text{C}",
    "\\text{Derivative}",
    "\\text{Differentiate}",
    "\\text{Direct}",
    "\\text{Divide}",
    "\\text{Evaluate}",
    "\\text{Evaluating}",
    "\\text{E}",
    "\\text{Factor:}",
    "\\text{Find}",
    "\\text{First}",
    "\\text{For}",
    "\\text{Fundamental}",
    "\\text{Given}",
    "\\text{Here}",
    "\\text{If}",
    "\\text{Integrate}",
    "\\text{Integration}",
    "\\text{Just}",
    "\\text{L'Hopital's}",
    "\\text{Let}",
    "\\text{No}",
    "\\text{Parts,}",
    "\\text{Product}",
    "\\text{Quotient}",
    "\\text{Rearranging}",
    "\\text{Rewrite}",
    "\\text{Rule,}",
    "\\text{Rule:}",
    "\\text{Rule}",
    "\\text{R}",
    "\\text{Sandwich}",
    "\\text{Second}",
    "\\text{Setting}",
    "\\text{Simplify:}",
    "\\text{Since}",
    "\\text{Solving}",
    "\\text{So}",
    "\\text{Substituting}",
    "\\text{Summing}",
    "\\text{Test}",
    "\\text{Then}",
    "\\text{Theorem,}",
    "\\text{Theorem.}",
    "\\text{The}",
    "\\text{This}",
    "\\text{To}",
    "\\text{Use}",
    "\\text{Using}",
    "\\text{What}",
    "\\text{With}",
    "\\text{Writing}",
    "\\text{Yes}",
    "\\text{a:}",
    "\\text{above,}",
    "\\text{above}",
    "\\text{adding}",
    "\\text{all}",
    "\\text{and}",
    "\\text{antiderivatives:}",
    "\\text{antiderivatives}",
    "\\text{antiderivative}",
    "\\text{any,}",
    "\\text{an}",
    "\\text{applies,}",
    "\\text{appropriate}",
    "\\text{area}",
    "\\text{as}",
    "\\text{at}",
    "\\text{a}",
    "\\text{back}",
    "\\text{below,}",
    "\\text{below}",
    "\\text{between}",
    "\\text{be}",
    "\\text{both}",
    "\\text{bounded}",
    "\\text{bounds}",
    "\\text{branch.}",
    "\\text{but}",
    "\\text{by}",
    "\\text{cancel}",
    "\\text{changes,}",
    "\\text{changes}",
    "\\text{common}",
    "\\text{concave}",
    "\\text{concavity}",
    "\\text{conditions,}",
    "\\text{constant}",
    "\\text{continuous}",
    "\\text{critical}",
    "\\text{cross}",
    "\\text{decreasing?}",
    "\\text{decreasing}",
    "\\text{defined,}",
    "\\text{denominator,}",
    "\\text{denominator}",
    "\\text{derivative}",
    "\\text{directly:}",
    "\\text{discontinuity}",
    "\\text{discontinuous}",
    "\\text{disc}",
    "\\text{does}",
    "\\text{domain}",
    "\\text{dy/dx}",
    "\\text{equals}",
    "\\text{equal}",
    "\\text{equation}",
    "\\text{essential}",
    "\\text{evaluate}",
    "\\text{every}",
    "\\text{except}",
    "\\text{excludes}",
    "\\text{exist)}",
    "\\text{exists}",
    "\\text{exist}",
    "\\text{expanding:}",
    "\\text{expression,}",
    "\\text{expression}",
    "\\text{f(x).}",
    "\\text{factor}",
    "\\text{find}",
    "\\text{flip}",
    "\\text{form.}",
    "\\text{formed}",
    "\\text{formula}",
    "\\text{form}",
    "\\text{for}",
    "\\text{from}",
    "\\text{functions:}",
    "\\text{function}",
    "\\text{f}",
    "\\text{get}",
    "\\text{given}",
    "\\text{gives}",
    "\\text{giving}",
    "\\text{goes}",
    "\\text{greatest}",
    "\\text{highest}",
    "\\text{if}",
    "\\text{implicitly}",
    "\\text{increasing?}",
    "\\text{increasing}",
    "\\text{indicating}",
    "\\text{inflection.}",
    "\\text{inflection}",
    "\\text{inner}",
    "\\text{integer}",
    "\\text{integrand}",
    "\\text{integration:}",
    "\\text{integration}",
    "\\text{interval}",
    "\\text{into}",
    "\\text{inverse}",
    "\\text{in}",
    "\\text{is}",
    "\\text{it,}",
    "\\text{itself.}",
    "\\text{it}",
    "\\text{jump}",
    "\\text{just}",
    "\\text{leaving}",
    "\\text{left-hand}",
    "\\text{lies}",
    "\\text{limit}",
    "\\text{line}",
    "\\text{matches}",
    "\\text{maximum.}",
    "\\text{maximum}",
    "\\text{method,}",
    "\\text{minimum.}",
    "\\text{minimum}",
    "\\text{multiplying}",
    "\\text{must}",
    "\\text{negative,}",
    "\\text{negative}",
    "\\text{non-negative:}",
    "\\text{not}",
    "\\text{no}",
    "\\text{numerator}",
    "\\text{of}",
    "\\text{once}",
    "\\text{only}",
    "\\text{on}",
    "\\text{or}",
    "\\text{parts,}",
    "\\text{parts}",
    "\\text{point(s)}",
    "\\text{point-slope}",
    "\\text{points}",
    "\\text{point}",
    "\\text{positive,}",
    "\\text{positive}",
    "\\text{power}",
    "\\text{present:}",
    "\\text{reaches}",
    "\\text{real}",
    "\\text{region}",
    "\\text{relative}",
    "\\text{relevant}",
    "\\text{removable}",
    "\\text{respect}",
    "\\text{revolving}",
    "\\text{right-hand}",
    "\\text{root}",
    "\\text{rule}",
    "\\text{same}",
    "\\text{second}",
    "\\text{separately:}",
    "\\text{shows}",
    "\\text{sides}",
    "\\text{sign}",
    "\\text{simplifies}",
    "\\text{since}",
    "\\text{slope}",
    "\\text{solid}",
    "\\text{solve}",
    "\\text{so}",
    "\\text{square}",
    "\\text{standard}",
    "\\text{stays}",
    "\\text{steps}",
    "\\text{substitute}",
    "\\text{substituting}",
    "\\text{substitution,}",
    "\\text{substitution}",
    "\\text{tangent}",
    "\\text{tends}",
    "\\text{tend}",
    "\\text{term:}",
    "\\text{terms:}",
    "\\text{terms}",
    "\\text{term}",
    "\\text{there),}",
    "\\text{there.}",
    "\\text{these}",
    "\\text{the}",
    "\\text{this}",
    "\\text{through}",
    "\\text{to}",
    "\\text{treating}",
    "\\text{trigonometric}",
    "\\text{under}",
    "\\text{up?}",
    "\\text{up}",
    "\\text{using}",
    "\\text{volume}",
    "\\text{where}",
    "\\text{which}",
    "\\text{with}",
    "\\text{x-axis,}",
    "\\text{x-coordinate}",
    "\\text{x=2.}",
    "\\text{x=4.}",
    "\\text{x=5?}",
    "\\text{x=5}",
    "\\text{xe\\textasciicircum{}(x)}",
    "\\text{x}",
    "\\text{x²}",
    "\\text{x³}",
    "\\text{y²}",
    "\\text{y³}",
    "\\text{zero:}",
    "\\text{zero}",
    "\\text{—}",
    "\\text{√3}",
    "\\text{∞}",
    "du = -3 \\, dx",
    "du = 1 \\, dx",
    "du = 2 \\, dx",
    "du = 3 \\, dx",
    "du = 5 \\, dx",
    "du = dx",
    "dv = -\\sin(x) \\, dx",
    "dv = \\cos{\\left(x \\right)} \\, dx",
    "dv = \\sin{\\left(x \\right)} \\, dx",
    "dv = e^{x} \\, dx",
    "dy/dx",
    "dy/dx = - \\frac{1}{4} = - \\frac{1}{4}",
    "dy/dx = - \\frac{3}{4} = - \\frac{3}{4}",
    "dy/dx = - \\frac{x^{2}}{y^{2}}",
    "dy/dx = - \\frac{x}{y}",
    "e^u \\cdot u'",
    "e^{2 x - 1} \\cdot 2",
    "e^{2x - 1}",
    "e^{3}",
    "e^{4x}",
    "e^{5x} + C",
    "e^{5x}/x + C",
    "e^{\\sin(x)}",
    "e^{\\sin(x)}\\cos(x)",
    "e^{\\sin{\\left(x \\right)}} \\cdot \\cos{\\left(x \\right)}",
    "e^{\\sin{\\left(x \\right)}} \\cos{\\left(x \\right)}",
    "e^{x^2}",
    "e^{x^{2}} \\cdot 2 x",
    "f",
    "f''(-1) = 6 \\left(-1\\right) = -6",
    "f''(1) = 6 \\cdot 1 = 6",
    "f''(2) = 2 = 2",
    "f''(3) = -2 = -2",
    "f''(x)",
    "f''(x) = -2",
    "f''(x) = 2",
    "f''(x) = 4 \\left(3 x^{2} - 1\\right)",
    "f''(x) = 6 \\left(x - 2\\right)",
    "f''(x) = 6 x",
    "f''(x) > 0",
    "f''(x)=0",
    "f'(-1)",
    "f'(-1) = -2",
    "f'(-1) = 4 \\left(-1\\right) = -4",
    "f'(0)",
    "f'(0) = 3 e^{3 \\cdot 0} = 3",
    "f'(1)",
    "f'(1) = -1",
    "f'(1) = 2 \\cdot 1 - 4 = -2",
    "f'(1) = 3",
    "f'(2)",
    "f'(2) = 3 \\cdot 2^{2} - 3 = 9",
    "f'(3)",
    "f'(3) = 2 \\cdot 3 = 6",
    "f'(3) = 6",
    "f'(x)",
    "f'(x) < 0",
    "f'(x) = - \\sin{\\left(x \\right)}",
    "f'(x) = 0",
    "f'(x) = 1 + \\tan^{2}{\\left(x \\right)}",
    "f'(x) = 12 x^{3}",
    "f'(x) = 14 x^{6}",
    "f'(x) = 2 \\left(x - 2\\right)",
    "f'(x) = 2 x",
    "f'(x) = 2 x - 4",
    "f'(x) = 2 x - 6",
    "f'(x) = 21 x^{2} - 4 x + 1",
    "f'(x) = 3 \\cos{\\left(x \\right)}",
    "f'(x) = 3 e^{3 x}",
    "f'(x) = 3 x^{2} - 12",
    "f'(x) = 3 x^{2} - 3",
    "f'(x) = 4 x",
    "f'(x) = 5 x^{4}",
    "f'(x) = 6 x^{2} - 6 x - 12",
    "f'(x) = 6 x^{5} - 4",
    "f'(x) = \\cos{\\left(x \\right)}",
    "f'(x) = \\frac{2 x}{x^{2} + 1}",
    "f'(x) = e^{4 x} \\cdot 4 = 4 e^{4 x}",
    "f'(x) = x - 3",
    "f'(x) > 0",
    "f(-1) = 1",
    "f(-3) = \\left|{-3}\\right| = 3",
    "f(1) = 0",
    "f(1) = 1",
    "f(1) = 1^{2} - 1 = 0",
    "f(1) = 1^{2} - 4 = -3",
    "f(1) = 1^{3} = 1",
    "f(2) = 2^{2} + 2 = 6",
    "f(2) = 2^{2} = 4",
    "f(3) = 2 \\cdot 3 + 1 = 7",
    "f(3) = 3 \\cdot 3 + 4 = 13",
    "f(3) = 9",
    "f(4) = 3 \\cdot 4 = 12",
    "f(4) = 4 - 2 \\cdot 4 = -4",
    "f(5)",
    "f(5) = 10",
    "f(5) = 2 \\cdot 5 - 3 = 7",
    "f(5) = 7 \\neq 10",
    "f(9) = 5 - 9 = -4",
    "f(x) = (2x + 1)/(x^2 + 1)",
    "f(x) = (2x - 5)^4",
    "f(x) = (\\sin(x))/(x)",
    "f(x) = (x)/(x + 1)",
    "f(x) = (x^2 + 1)^3",
    "f(x) = (x^2)/(x - 2)",
    "f(x) = (x^2-25)/(x-5)",
    "f(x) = (x^3 - 2x)^2",
    "f(x) = -x+6",
    "f(x) = -x^2 + 6x - 5",
    "f(x) = 1/(x-3)?",
    "f(x) = 1/(x^2-4)?",
    "f(x) = 1/\\sqrt{x+5}?",
    "f(x) = 11",
    "f(x) = 2",
    "f(x) = 2 x - 3",
    "f(x) = 2x+1",
    "f(x) = 2x+7",
    "f(x) = 2x-3",
    "f(x) = 2x^3 - 3x^2 - 12x + 4",
    "f(x) = 2x^7 + 5",
    "f(x) = 3",
    "f(x) = 3 - x",
    "f(x) = 3 \\sin(x)",
    "f(x) = 3 x + 4",
    "f(x) = 3 x^{2} - 5 x + 7",
    "f(x) = 3-x",
    "f(x) = 3x",
    "f(x) = 3x+4",
    "f(x) = 3x-4",
    "f(x) = 3x^4",
    "f(x) = 4 - 2 x",
    "f(x) = 4-2x",
    "f(x) = 4x-3",
    "f(x) = 5",
    "f(x) = 5 - x",
    "f(x) = 5 x - 7",
    "f(x) = 5-x",
    "f(x) = 5x+1",
    "f(x) = 7x^3 - 2x^2 + x",
    "f(x) = 9",
    "f(x) = [x]",
    "f(x) = \\cos(x)",
    "f(x) = \\frac{1}{\\sqrt{x + 5}}",
    "f(x) = \\frac{1}{x - 3}",
    "f(x) = \\frac{1}{x^{2} - 4}",
    "f(x) = \\frac{2 x + 3}{x - 1}",
    "f(x) = \\frac{\\sqrt{x + 1}}{x - 4}",
    "f(x) = \\frac{x^{2} + 2 x}{x + 5}",
    "f(x) = \\frac{x^{2} - 1}{x + 3}",
    "f(x) = \\left|{x}\\right|",
    "f(x) = \\ln(3x^2 + 5)",
    "f(x) = \\ln(5x - 1)",
    "f(x) = \\ln(\\cos(x))",
    "f(x) = \\ln(x^2 + 1)",
    "f(x) = \\ln(x^3 - 2)",
    "f(x) = \\sin(2x + 3)",
    "f(x) = \\sin(3x - 1)",
    "f(x) = \\sin(x)",
    "f(x) = \\sin(x) + \\cos(x)",
    "f(x) = \\sin(x) \\cdot \\cos(x)",
    "f(x) = \\sin(x^2)",
    "f(x) = \\sqrt{9 - x^{2}}",
    "f(x) = \\sqrt{9-x^2}?",
    "f(x) = \\sqrt{x - 2}",
    "f(x) = \\sqrt{x+1}/(x-4)?",
    "f(x) = \\sqrt{x-2}?",
    "f(x) = \\tan(x)",
    "f(x) = a \\cos(x)",
    "f(x) = a \\sin(x)",
    "f(x) = a \\tan(x)",
    "f(x) = e^{2x - 1}",
    "f(x) = e^{3x}",
    "f(x) = e^{4x}",
    "f(x) = e^{\\sin(x)}",
    "f(x) = e^{x^2}",
    "f(x) = x \\cdot \\cos(x)",
    "f(x) = x^2",
    "f(x) = x^2 - 4x + 3",
    "f(x) = x^2 - 4x + 7",
    "f(x) = x^2 - 6x + 5",
    "f(x) = x^2 \\cdot \\sin(x)",
    "f(x) = x^2 \\cdot x + 1",
    "f(x) = x^2+2",
    "f(x) = x^2-1",
    "f(x) = x^2-4",
    "f(x) = x^2/2 - 3x",
    "f(x) = x^3",
    "f(x) = x^3 - 12x",
    "f(x) = x^3 - 3x",
    "f(x) = x^3 - 3x + 1",
    "f(x) = x^3 - 6x^2 + 9x",
    "f(x) = x^4 - 2x^2",
    "f(x) = x^5",
    "f(x) = x^6 - 4x",
    "f(x) = x^{2}",
    "f(x) = x^{2} - 1",
    "f(x) = x^{3}",
    "f(x) = x^{3} - 4 x + 1",
    "f(x) = |x|",
    "f^{-1}(11)",
    "f^{-1}(11) = 2",
    "f^{-1}(2)",
    "f^{-1}(2) = 4",
    "f^{-1}(3)",
    "f^{-1}(3) = -2",
    "f^{-1}(5)",
    "f^{-1}(5) = 3",
    "f^{-1}(9)",
    "f^{-1}(9) = 3",
    "g(-1)",
    "g(-1) = -1 + 2 = 1",
    "g(-1) = 1",
    "g(1)",
    "g(1) = -3",
    "g(1) = 1 + 2 = 3",
    "g(1) = 1^{2} + 3 = 4",
    "g(1) = 2",
    "g(1) = 2 \\cdot 1 - 5 = -3",
    "g(1) = 3 \\cdot 1 - 1 = 2",
    "g(1) = 4",
    "g(2)",
    "g(2) = 1",
    "g(2) = 2 - 1 = 1",
    "g(2) = 2 \\cdot 2 - 1 = 3",
    "g(2) = 2^{2} + 1 = 5",
    "g(2) = 5",
    "g(3)",
    "g(3) = 3",
    "g(3) = 3^{2} - 2 \\cdot 3 = 3",
    "g(3) = 3^{2} = 9",
    "g(3) = 9",
    "g(4) = 4 - 5 = -1",
    "g(x) = 2 x - 5",
    "g(x) = 2x-1",
    "g(x) = 2x-5",
    "g(x) = 3 x - 1",
    "g(x) = 3x-1",
    "g(x) = x + 2",
    "g(x) = x - 1",
    "g(x) = x+2",
    "g(x) = x-1",
    "g(x) = x-5",
    "g(x) = x^2",
    "g(x) = x^2+1",
    "g(x) = x^2+3",
    "g(x) = x^2-2x",
    "g(x) = x^{2}",
    "g(x) = x^{2} + 1",
    "g(x) = x^{2} + 3",
    "g(x) = x^{2} - 2 x",
    "k=3",
    "k=4",
    "ln|2x+1| + C",
    "ln|\\cos(x)| + C",
    "ln|\\sec(x)| + C",
    "ln|\\sin(x)| + C",
    "ln|x| + C",
    "sqrt{1 - x^2}",
    "sqrt{x} about the x-axis from x",
    "u = 2 x + 1",
    "u = 2 x + 3",
    "u = 2 x - 1",
    "u = 2 x - 5",
    "u = 3 x",
    "u = 3 x + 5",
    "u = 3 x - 1",
    "u = 3 x^{2} + 5",
    "u = 4 - 3 x",
    "u = 4 x",
    "u = 5 x",
    "u = 5 x - 1",
    "u = \\cos{\\left(x \\right)}",
    "u = \\sin{\\left(x \\right)}",
    "u = x",
    "u = x^{2}",
    "u = x^{2} + 1",
    "u = x^{3} - 2",
    "u = x^{3} - 2 x",
    "u' = - \\sin{\\left(x \\right)}",
    "u' = 1",
    "u' = 2",
    "u' = 2 x",
    "u' = 3",
    "u' = 3 x^{2}",
    "u' = 3 x^{2} - 2",
    "u' = 4",
    "u' = 5",
    "u' = 6 x",
    "u' = \\cos{\\left(x \\right)}",
    "u'v + uv'",
    "v = - \\cos{\\left(x \\right)}",
    "v = \\cos(x)",
    "v = \\cos{\\left(x \\right)}",
    "v = \\sin{\\left(x \\right)}",
    "v = e^{x}",
    "v = x",
    "v = x + 1",
    "v = x - 2",
    "v = x^{2} + 1",
    "v' = - \\sin{\\left(x \\right)}",
    "v' = 1",
    "v' = 2 x",
    "v' = \\cos{\\left(x \\right)}",
    "x",
    "x + 1",
    "x + 1 \\geq 0",
    "x + 2",
    "x + 3",
    "x + 3 and y",
    "x + 5 and y",
    "x - 2 \\geq 0",
    "x - 3",
    "x - 3 \\neq 0",
    "x - 4 \\neq 0",
    "x < -1/",
    "x < -5",
    "x < 2",
    "x < 3",
    "x = -1, 1",
    "x = -1, 2",
    "x = -2",
    "x = -2 \\text{ and } x = 2",
    "x = -2, 2",
    "x = -5",
    "x = 2",
    "x = 3",
    "x = 4",
    "x > -1",
    "x > -5",
    "x > 1/",
    "x > 2",
    "x > 3",
    "x \\cdot \\ln(x) + C",
    "x \\cos(x) - \\sin(x) + C",
    "x \\geq -1",
    "x \\geq -1, x \\neq 4",
    "x \\geq -5",
    "x \\geq 2",
    "x \\geq 3",
    "x \\in \\left(-1, 1\\right)",
    "x \\in \\left(2, \\infty\\right)",
    "x \\left(3 x + 2\\right)",
    "x \\left(x \\cos{\\left(x \\right)} + 2 \\sin{\\left(x \\right)}\\right)",
    "x \\leq -3",
    "x \\leq 2",
    "x \\neq 0",
    "x \\neq 1",
    "x \\neq 2",
    "x \\neq 3",
    "x \\neq 5",
    "x \\sin(x) + C",
    "x \\sin(x) + \\cos(x) + C",
    "x \\sin{\\left(x \\right)}",
    "x \\to 0",
    "x \\to \\infty",
    "x(x \\cos(x) + 2 \\sin(x))",
    "x- \\cos{\\left(x \\right)}",
    "x=-1",
    "x=-2",
    "x=-3",
    "x=0",
    "x=1",
    "x=2",
    "x=3",
    "x=4",
    "x=5",
    "x=\\frac{\\pi}{2}",
    "x\\sin{\\left(x \\right)}",
    "x^2",
    "x^2 + 7x + C",
    "x^2 - 1 between x",
    "x^2 - 3x",
    "x^2 \\cos(x)",
    "x^2 \\sin(x)/2 + C",
    "x^2 between x",
    "x^2/(x^2 - 4x + 4) - 4x/(x^2 - 4x + 4)",
    "x^2/2 - 3x",
    "x^2e^{x}/2 + C",
    "x^3 + C",
    "x^4 + 5x^2 + C",
    "x^4 - x^2 + C",
    "x^5",
    "x^5/5 + 5x^3/3 + C",
    "x^6 - 3x + C",
    "x^6 - 4x",
    "x^{1}",
    "x^{2}",
    "x^{2} + 2 x + 4",
    "x^{2} + y^{2} = 25",
    "x^{2} - 4 \\neq 0",
    "x^{3}",
    "x^{3} + y^{3} = 9",
    "x^{6}",
    "xe^{x} - \\int e^{x} \\, dx",
    "y",
    "y - 0 = -1(x - 1)",
    "y - 1 = -2(x - -1)",
    "y - 1 = 3(x - 1)",
    "y - 9 = 6(x - 3)",
    "y - f(a) = f'(a)(x-a)",
    "y = -1x",
    "y = -1x + 1",
    "y = -2x + 1",
    "y = -2x - 1",
    "y = -3x - 2",
    "y = -6x - 9",
    "y = 0x - 1",
    "y = 1x + 1",
    "y = 1x + 3",
    "y = 1x - 2",
    "y = 2 about the x-axis from x=0 to x=3",
    "y = 2x - 1",
    "y = 2x^2 + 1 at x = -1",
    "y = 3x",
    "y = 3x + 1",
    "y = 3x - 2",
    "y = 4 - x^2",
    "y = 6x + 9",
    "y = 6x - 9",
    "y = 9x + 6",
    "y = x about the x-axis from x=0 to x=4",
    "y = x^2",
    "y = x^2 - 3x + 2 at x = 1",
    "y = x^2 - 4x + 3 at x = 1",
    "y = x^2 about the x-axis from x=0 to x=1",
    "y = x^2 at x = -1",
    "y = x^2 at x = 3",
    "y = x^3",
    "y = x^3 - 3x at x = 2",
    "y = x^3 at x = 1",
    "y=3 x",
    "y=4 - x^{2}",
    "y=6 - x",
    "y=x + 3",
    "y=x + 5",
    "y=x^{2}",
    "y=x^{2} - 1",
    "y=x^{3}",
    "|x|",
  ];

  testWidgets(
    'every MTH 121 LaTeX token renders without error or fallback',
    (WidgetTester tester) async {
      final List<String> broken = <String>[];
      for (final String expr in expressions) {
        await tester.pumpWidget(
          MaterialApp(home: Scaffold(body: MathText("\$$expr\$"))),
        );
        await tester.pumpAndSettle();
        final Object? err = tester.takeException();
        final bool mathWidgetExists = find.byType(Math).evaluate().isNotEmpty;
        if (err != null) {
          // The Math widget existing in the tree despite an exception
          // means KaTeX successfully parsed and built the formula -- the
          // exception is a downstream LAYOUT assertion (this test's bare
          // Scaffold has no width constraint, unlike the real app's
          // cards/lists), not a parsing failure. A release build never
          // throws on layout overflow (it's a debug-only assertion), so
          // that case is a soft pass here. Only a missing Math widget --
          // meaning MathText's onErrorFallback kicked in, or the widget
          // never built at all -- is a genuine hard failure.
          if (!mathWidgetExists) {
            broken.add('EXCEPTION ($err): $expr');
          }
          continue;
        }
        if (!mathWidgetExists) {
          broken.add('FALLBACK (no Math widget rendered): $expr');
        }
      }
      expect(broken, isEmpty, reason: broken.join('X'));
    },
  );
}
