// GENERATED by tools/gen_legal.py -- edit the script, not this file.
import 'package:flutter/foundation.dart';

@immutable
class LegalSection {
  const LegalSection(this.heading, this.paragraphs, this.bullets);
  final String heading;
  final List<String> paragraphs;
  final List<String> bullets;
}

@immutable
class LegalDoc {
  const LegalDoc({
    required this.title,
    required this.updated,
    required this.intro,
    required this.sections,
  });
  final String title;
  final String updated;
  final String intro;
  final List<LegalSection> sections;
}

class LegalContent {
  static const LegalDoc terms = LegalDoc(
    title: 'Terms of Use',
    updated: '20 September 2026',
    intro: 'These terms explain how you may use Eduvora. By creating an account or using the app you agree to them. If you do not agree, please do not use Eduvora.',
    sections: <LegalSection>[
      LegalSection('Who we are', <String>['Eduvora is an independent study app for Nigerian students. It is run by Eduvora, operated by Dominic Emeka, Nigeria. You can reach us at hello@eduvora.ng.', 'Eduvora is NOT part of, affiliated with, or endorsed by the University of Nigeria, Nsukka or any other school, university, polytechnic or college. School names, course codes and logos are used only to show which school and course a page is for.'], <String>[]),
      LegalSection('Practice questions are not official exams', <String>['CBT papers in Eduvora are practice questions written to help you revise. They are not official examination papers, they are not past questions unless clearly stated, and they do not predict what will appear in any real exam.', 'We work hard to make the questions accurate, but we cannot promise they are free of mistakes. Always check important facts with your lecturer, course outline and recommended textbooks. We are not responsible for exam results.'], <String>[]),
      LegalSection('Your account', <String>[], <String>['You must be at least 16 years old to use Eduvora.', 'Give accurate information and keep your password safe. You are responsible for what happens on your account.', 'One person, one account. Do not share your account or paid access with other people.']),
      LegalSection('Acceptable use', <String>['When using Eduvora you agree not to:'], <String>['harass, bully, threaten or impersonate anyone;', 'post hate speech, sexual content, or anything illegal;', 'upload material you do not have the right to share, including copyrighted books, handouts or exam papers;', 'cheat, leak real exam questions, or use Eduvora to help anyone cheat in an examination;', 'copy, resell or scrape Eduvora questions or content, or try to break, overload or bypass the app or its payment system.', 'We may remove content or suspend accounts that break these rules.']),
      LegalSection('Paid access', <String>['Some CBT papers can be unlocked for a fee. The price, what you get and how long access lasts are shown before you pay. Prices are in Nigerian naira (NGN).', 'Payments are processed by Paystack. We never see or store your card details.', 'Paid access is for your own use and is tied to one device at a time. If you need to move to a new device, contact us.', 'Because access to digital content starts immediately, payments are non-refundable once access has been granted. If you were charged but access was not delivered, contact us with your payment reference and we will fix it or refund you.', 'We may change prices or what is free or paid in future. Changes do not affect access you have already paid for.'], <String>[]),
      LegalSection('Referral programme', <String>['You may share your referral code. When someone signs up with your code and makes a purchase, you earn a commission on that purchase (currently 10%), shown in the Refer and earn screen.'], <String>['The minimum withdrawal is NGN 1,000.', 'Payouts are made manually by us to the account you provide, and may take some days.', 'Referring yourself, fake accounts, spam, or misleading people are not allowed. We may cancel commissions and close accounts where we find this.', 'We may change or stop the programme, but commissions already earned will still be honoured.']),
      LegalSection('Content you post or upload', <String>['You keep ownership of what you post (materials, messages, community posts). By posting, you give Eduvora permission to store it and show it to other users as part of the app.', 'You promise that you own it or have the right to share it. If you believe something on Eduvora infringes your rights, email us at hello@eduvora.ng and we will review it promptly.'], <String>[]),
      LegalSection('Our content', <String>['The Eduvora app, its design and the questions we write belong to us or our licensors. You may use them for your own personal study only.'], <String>[]),
      LegalSection('Availability and changes', <String>['We try to keep Eduvora running, but we cannot promise it will always be available or error-free. We may change, pause or stop any feature.'], <String>[]),
      LegalSection('Limits of liability', <String>['Eduvora is provided "as is". To the extent the law allows, we are not liable for indirect or consequential loss, or for exam results, arising from use of the app. Nothing in these terms removes any right you have under Nigerian law that cannot be removed.'], <String>[]),
      LegalSection('Ending your account', <String>['You can stop using Eduvora any time. You can ask us to delete your account by emailing hello@eduvora.ng. We may suspend or close accounts that break these terms.'], <String>[]),
      LegalSection('Changes and governing law', <String>['We may update these terms. When we make important changes we will tell you in the app. Continuing to use Eduvora after a change means you accept it.', 'These terms are governed by the laws of the Federal Republic of Nigeria.'], <String>[]),
      LegalSection('Contact', <String>['Questions? Email hello@eduvora.ng.'], <String>[]),
    ],
  );
  static const LegalDoc privacy = LegalDoc(
    title: 'Privacy Policy',
    updated: '20 September 2026',
    intro: 'This policy explains what information Eduvora collects, why, and the choices you have. We handle your data in line with the Nigeria Data Protection Act 2023.',
    sections: <LegalSection>[
      LegalSection('Who is responsible', <String>['Eduvora, operated by Dominic Emeka, Nigeria is the controller of your data. Contact: hello@eduvora.ng.'], <String>[]),
      LegalSection('What we collect', <String>[], <String>['Account details: your name, email address and profile picture (if you sign in with Google), and your password if you use email sign-up (stored securely, never in plain text).', 'Academic profile: your school, faculty, department, level, and optionally your matric number and bio.', 'Your activity: CBT attempts and scores, courses you use, materials you upload, and posts, comments and messages you send in the community, groups, chats and tutor features.', 'Payments: payment status and reference numbers from Paystack. We never see or store your card or bank login details.', 'Referrals: your referral code, who you referred, commissions earned, and payout details you give us when withdrawing.', 'Device information: a random device ID generated by the app, used to tie paid access to one device, plus basic technical data such as browser or app version.']),
      LegalSection('How we use it', <String>[], <String>['To create your account and show you courses, papers and materials for your faculty and level.', 'To unlock paid access, prevent misuse, and pay referral commissions.', 'To run community features, keep the app safe, and respond to support requests.', 'To improve Eduvora, for example by looking at which features are used.', 'We do not sell your personal data.']),
      LegalSection('Who we share it with', <String>['We share data only with services that help us run Eduvora:'], <String>['Supabase, which hosts our database, sign-in and file storage;', 'Google, if you choose to sign in with Google;', 'Paystack, which processes payments;', 'Vercel, which hosts the website version of Eduvora.', 'Other students can see your name, profile picture, school and what you post publicly in the community. Your email, matric number and payment details are not shown to other students.', 'We may also share information if the law requires it.']),
      LegalSection('Where it is stored', <String>['Your data is stored with our service providers, some of whom operate outside Nigeria. We choose providers that protect data with appropriate security.'], <String>[]),
      LegalSection('How long we keep it', <String>['We keep your data while your account is active. If you ask us to delete your account we will remove your personal data, except records we must keep for payments, fraud prevention or the law.'], <String>[]),
      LegalSection('Your rights', <String>['You can ask us to:'], <String>['give you a copy of your data;', 'correct anything that is wrong (you can also edit most of it in your profile);', 'delete your data or account;', 'stop using your data for a particular purpose.', 'Email hello@eduvora.ng and we will respond within a reasonable time. You also have the right to complain to the Nigeria Data Protection Commission.']),
      LegalSection('Security', <String>['We use reasonable technical measures to protect your data, but no system is perfectly secure. Keep your password private.'], <String>[]),
      LegalSection('Children', <String>['Eduvora is for students aged 16 and above. If you believe a younger child has signed up, email us and we will remove the account.'], <String>[]),
      LegalSection('Changes to this policy', <String>['We may update this policy. When we make important changes we will tell you in the app.'], <String>[]),
      LegalSection('Contact', <String>['Questions or requests? Email hello@eduvora.ng.'], <String>[]),
    ],
  );
}
